parameters:
  ground_estimate_window_size:
    name: "/control/maneuver_controller/ground_estimate_window_size"
    type: "int"
  ground_estimate_update_period_ms:
    name: "/control/maneuver_controller/ground_estimate_update_period_ms"
    type: "int"
  ground_estimate_initial_delay_s:
    name: "/control/maneuver_controller/ground_estimate_initial_delay_s"
    type: "float"
  landed_altitude_threshold:
    name: "/control/maneuver_controller/landed_altitude_threshold"
    type: "float"
  on_cable_max_euc_distance:
    name: "/control/maneuver_controller/on_cable_max_euc_distance"
    type: "float"
  fail_on_unable_to_locate:
    name: "/control/maneuver_controller/fail_on_unable_to_locate"
    type: "bool"
  combined_drone_awareness_pub_period_ms:
    name: "/control/maneuver_controller/combined_drone_awareness_pub_period_ms"
    type: "int"
  maneuver_publish_period_ms:
    name: "/control/maneuver_controller/maneuver_publish_period_ms"
    type: "int"
  maneuver_register_update_timeout_s:
    name: "/control/maneuver_controller/maneuver_register_update_timeout_s"
    type: "float"
  maneuver_start_timeout_s:
    name: "/control/maneuver_controller/maneuver_start_timeout_s"
    type: "float"
  maneuver_queue_size:
    name: "/control/maneuver_controller/maneuver_queue_size"
    type: "int"
  maneuver_execution_period_ms:
    name: "/control/maneuver_controller/maneuver_execution_period_ms"
    type: "int"
  use_nans_when_hovering:
    name: "/control/maneuver_controller/use_nans_when_hovering"
    type: "bool"
  no_maneuver_idle_cnt_s:
    name: "/control/maneuver_controller/no_maneuver_idle_cnt_s"
    type: "float"
  hover_by_object_max_euc_dist:
    name: "/control/maneuver_controller/hover_by_object_max_euc_dist"
    type: "float"
  hover_on_cable_default_z_velocity:
    name: "/control/maneuver_controller/hover_on_cable_default_z_velocity"
    type: "float"
  hover_on_cable_default_yaw_rate:
    name: "/control/maneuver_controller/hover_on_cable_default_yaw_rate"
    type: "float"
  maneuver_wait_for_execute_poll_ms:
    name: "/control/maneuver_controller/maneuver_wait_for_execute_poll_ms"
    type: "int"
  maneuver_evaluate_done_poll_ms:
    name: "/control/maneuver_controller/maneuver_evaluate_done_poll_ms"
    type: "int"
  reached_position_euclidean_distance_threshold:
    name: "/control/maneuver_controller/reached_position_euclidean_distance_threshold"
    type: "float"
  minimum_target_altitude:
    name: "/control/maneuver_controller/minimum_target_altitude"
    type: "float"
  cable_landing_min_z_distance:
    name: "/control/maneuver_controller/cable_landing_min_z_distance"
    type: "float"
  cable_landing_max_z_distance:
    name: "/control/maneuver_controller/cable_landing_max_z_distance"
    type: "float"
  cable_landing_max_initial_distance_error:
    name: "/control/maneuver_controller/cable_landing_max_initial_distance_error"
    type: "float"
  cable_landing_max_initial_yaw_error:
    name: "/control/maneuver_controller/cable_landing_max_initial_yaw_error"
    type: "float"
  cable_landing_safety_zone_radius:
    name: "/control/maneuver_controller/cable_landing_safety_zone_radius"
    type: "float"
  cable_landing_safety_margin_max_xy_position_error:
    name: "/control/maneuver_controller/cable_landing_safety_margin_max_xy_position_error"
    type: "float"
  cable_landing_safety_margin_max_xy_velocity:
    name: "/control/maneuver_controller/cable_landing_safety_margin_max_xy_velocity"
    type: "float"
  cable_landing_safety_margin_max_yaw_error:
    name: "/control/maneuver_controller/cable_landing_safety_margin_max_yaw_error"
    type: "float"
  cable_landing_safety_margin_max_yaw_rate:
    name: "/control/maneuver_controller/cable_landing_safety_margin_max_yaw_rate"
    type: "float"
  cable_landing_reference_truncate_radius:
    name: "/control/maneuver_controller/cable_landing_reference_truncate_radius"
    type: "float"
  cable_takeoff_min_target_cable_distance:
    name: "/control/maneuver_controller/cable_takeoff_min_target_cable_distance"
    type: "float"
  cable_takeoff_max_target_cable_distance:
    name: "/control/maneuver_controller/cable_takeoff_max_target_cable_distance"
    type: "float"
  generate_trajectories_asynchronously_with_delay:
    name: "/control/maneuver_controller/generate_trajectories_asynchronously_with_delay"
    type: "bool"
  generate_trajectories_poll_period_ms:
    name: "/control/maneuver_controller/generate_trajectories_poll_period_ms"
    type: "int"
  generate_trajectories_timeout_ms:
    name: "/control/maneuver_controller/generate_trajectories_timeout_ms"
    type: "int"
  cable_gripper_frame_id:
    name: "/tf/cable_gripper_frame_id"
    type: "string"
  drone_frame_id:
    name: "/tf/drone_frame_id"
    type: "string"
  world_frame_id:
    name: "/tf/world_frame_id"
    type: "string"
  ground_frame_id:
    name: "/tf/ground_frame_id"
    type: "string"

parameter_bundles:
  combined_drone_awareness_handler:
    ground_estimate_window_size:
      remap_name: "ground_estimate_window_size"
      update: false
    ground_estimate_update_period_ms:
      remap_name: "ground_estimate_update_period_ms"
      update: false
    ground_estimate_initial_delay_s:
      remap_name: "ground_estimate_initial_delay_s"
      update: false
    landed_altitude_threshold:
      remap_name: "landed_altitude_threshold"
      update: true
    on_cable_max_euc_distance:
      remap_name: "on_cable_max_euc_distance"
      update: true
    fail_on_unable_to_locate:
      remap_name: "fail_on_unable_to_locate"
      update: false
    combined_drone_awareness_pub_period_ms:
      remap_name: "combined_drone_awareness_pub_period_ms"
      update: false
    cable_gripper_frame_id:
      remap_name: "cable_gripper_frame_id"
      update: false
    drone_frame_id:
      remap_name: "drone_frame_id"
      update: false
    world_frame_id:
      remap_name: "world_frame_id"
      update: false
    ground_frame_id:
      remap_name: "ground_frame_id"
      update: false

  maneuver_scheduler:
    maneuver_publish_period_ms:
      remap_name: "maneuver_publish_period_ms"
      update: false
    maneuver_register_update_timeout_s:
      remap_name: "maneuver_register_update_timeout_s"
      update: false
    maneuver_start_timeout_s:
      remap_name: "maneuver_start_timeout_s"
      update: false
    maneuver_queue_size:
      remap_name: "maneuver_queue_size"
      update: false
    maneuver_execution_period_ms:
      remap_name: "maneuver_execution_period_ms"
      update: false
    use_nans_when_hovering:
      remap_name: "use_nans_when_hovering"
      update: false
    no_maneuver_idle_cnt_s:
      remap_name: "no_maneuver_idle_cnt_s"
      update: false
    hover_by_object_max_euc_dist:
      remap_name: "hover_by_object_max_euc_dist"
      update: true
    hover_on_cable_default_z_velocity:
      remap_name: "hover_on_cable_default_z_velocity"
      update: true
    hover_on_cable_default_yaw_rate:
      remap_name: "hover_on_cable_default_yaw_rate"
      update: true

  trajectory_generator_client:
    generate_trajectories_asynchronously_with_delay:
      remap_name: "generate_trajectories_asynchronously_with_delay"
      update: false
    generate_trajectories_poll_period_ms:
      remap_name: "generate_trajectories_poll_period_ms"
      update: false
    generate_trajectories_timeout_ms:
      remap_name: "generate_trajectories_timeout_ms"
      update: false

  hover_on_cable_maneuver_server:
    cable_gripper_frame_id:
      remap_name: "gripper_frame_id"
      update: false

  fly_to_position_maneuver_server:
    reached_position_euclidean_distance_threshold:
      remap_name: "reached_position_euclidean_distance_threshold"
      update: true
    minimum_target_altitude:
      remap_name: "minimum_target_altitude"
      update: true
    world_frame_id:
      remap_name: "world_frame_id"
      update: false

  fly_to_object_maneuver_server:
    reached_position_euclidean_distance_threshold:
      remap_name: "reached_position_euclidean_distance_threshold"
      update: true
    minimum_target_altitude:
      remap_name: "minimum_target_altitude"
      update: true
    world_frame_id:
      remap_name: "world_frame_id"
      update: false

  cable_landing_maneuver_server:
    cable_landing_min_z_distance:
      remap_name: "cable_landing_min_z_distance"
      update: true
    cable_landing_max_z_distance:
      remap_name: "cable_landing_max_z_distance"
      update: true
    cable_landing_max_initial_distance_error:
      remap_name: "cable_landing_max_initial_distance_error"
      update: true
    cable_landing_max_initial_yaw_error:
      remap_name: "cable_landing_max_initial_yaw_error"
      update: true
    reached_position_euclidean_distance_threshold:
      remap_name: "reached_position_euclidean_distance_threshold"
      update: true
    cable_gripper_frame_id:
      remap_name: "gripper_frame_id"
      update: false
    drone_frame_id:
      remap_name: "drone_frame_id"
      update: false
    world_frame_id:
      remap_name: "world_frame_id"
      update: false
    hover_on_cable_default_z_velocity:
      remap_name: "hover_on_cable_default_z_velocity"
      update: true
    hover_on_cable_default_yaw_rate:
      remap_name: "hover_on_cable_default_yaw_rate"
      update: true
    cable_landing_safety_zone_radius:
      remap_name: "cable_landing_safety_zone_radius"
      update: true
    cable_landing_safety_margin_max_xy_position_error:
      remap_name: "cable_landing_safety_margin_max_xy_position_error"
      update: true
    cable_landing_safety_margin_max_xy_velocity:
      remap_name: "cable_landing_safety_margin_max_xy_velocity"
      update: true
    cable_landing_safety_margin_max_yaw_error:
      remap_name: "cable_landing_safety_margin_max_yaw_error"
      update: true
    cable_landing_safety_margin_max_yaw_rate:
      remap_name: "cable_landing_safety_margin_max_yaw_rate"
      update: true
    cable_landing_reference_truncate_radius:
      remap_name: "cable_landing_reference_truncate_radius"
      update: true

  cable_takeoff_maneuver_server:
    cable_takeoff_min_target_cable_distance:
      remap_name: "cable_takeoff_min_target_cable_distance"
      update: true
    cable_takeoff_max_target_cable_distance:
      remap_name: "cable_takeoff_max_target_cable_distance"
      update: true
    reached_position_euclidean_distance_threshold:
      remap_name: "reached_position_euclidean_distance_threshold"
      update: true
    drone_frame_id:
      remap_name: "drone_frame_id"
      update: false
    world_frame_id:
      remap_name: "world_frame_id"
      update: false
    
    

  
  