III-Drone: iii_drone::perception::hough_transformer_node::HoughTransformerNode Class Reference
iii_drone::perception::hough_transformer_node::HoughTransformerNode Class Reference
Node for computing hough transform on images to detect powerline direction.
#include <hough_transformer_node.hpp>
Public Member Functions
HoughTransformerNode (const std::string &node_name="hough_transformer", const std::string &node_namespace="/perception/hough_transformer", const rclcpp::NodeOptions &options=rclcpp::NodeOptions())
Constructor.
~HoughTransformerNode ()
Destructor.
Private Member Functions
void OnCameraMsg (const sensor_msgs::msg::Image::SharedPtr _msg)
Callback function for the image topic.
Private Attributes
HoughTransformerConfigurator configurator_
Configurator object.
HoughTransformer hough_transformer_
HoughTransformer object.
rclcpp::Subscription< sensor_msgs::msg::Image >::SharedPtr camera_subscription_
Subscription object for the image topic.
rclcpp::Publisher< std_msgs::msg::Float32 >::SharedPtr cable_yaw_publisher_
Publisher object for the cable yaw angle.
Detailed Description
Node for computing hough transform on images to detect powerline direction.
Definition at line 62 of file hough_transformer_node.hpp.
Constructor & Destructor Documentation
HoughTransformerNode()
HoughTransformerNode::HoughTransformerNode (const std::string & node_name = "hough_transformer", const std::string & node_namespace = "/perception/hough_transformer", const rclcpp::NodeOptions & options = rclcpp::NodeOptions())
Constructor.
Parameters
node_name Name of the node
node_namespace Namespace of the node
options Options for the node
Definition at line 13 of file hough_transformer_node.cpp.
  : Node(
    node_name,
    node_namespace,
    options
), configurator_(this),
hough_transformer_(configurator_.hough_transformer_parameters()) {
    // Topics:
    cable_yaw_publisher_ = this->create_publisher<std_msgs::msg::Float32>(
        "cable_yaw_angle",
        10
    );
    rclcpp::QoS qos = rclcpp::QoS(rclcpp::KeepLast(10));
    qos.best_effort();
    qos.durability_volatile();
    camera_subscription_ = this->create_subscription<sensor_msgs::msg::Image>(
        "/sensor/cable_camera/image_raw",
        qos,
        std::bind(
            &HoughTransformerNode::OnCameraMsg,
            this,
            std::placeholders::_1
        )
    );
}
References cable_yaw_publisher_, camera_subscription_, and OnCameraMsg().
~HoughTransformerNode()
HoughTransformerNode::~HoughTransformerNode ()
Destructor.
Definition at line 46 of file hough_transformer_node.cpp.
{
    RCLCPP_INFO(this->get_logger(),  "Shutting down hough transformer node..");
}
Member Function Documentation
OnCameraMsg()
void HoughTransformerNode::OnCameraMsg (const sensor_msgs::msg::Image::SharedPtr _msg) private
Callback function for the image topic.
Parameters
_msg Message containing the image
Definition at line 53 of file hough_transformer_node.cpp.
{
    cv_bridge::CvImagePtr cv_ptr = cv_bridge::toCvCopy(
        _msg,
        _msg->encoding
    );
    cv::Mat img = cv_ptr->image;
    float angle;
    bool success = hough_transformer_.ComputeAngle(
        img,
        angle
    );
    if (success){
        std_msgs::msg::Float32 pl_direction;
        pl_direction.data = angle;
        cable_yaw_publisher_->publish(pl_direction);
        // RCLCPP debug published hough angle
        RCLCPP_DEBUG(this->get_logger(), "Hough angle: %f", angle);
    } else {
        // RCLCPP debug no lines detected
        RCLCPP_DEBUG(this->get_logger(), "No lines detected");
    }
}
References cable_yaw_publisher_, iii_drone::perception::HoughTransformer::ComputeAngle(), and hough_transformer_.
Referenced by HoughTransformerNode().
Member Data Documentation
cable_yaw_publisher_
rclcpp::Publisher<std_msgs::msg::Float32>::SharedPtr iii_drone::perception::hough_transformer_node::HoughTransformerNode::cable_yaw_publisher_ private
Publisher object for the cable yaw angle.
Definition at line 108 of file hough_transformer_node.hpp.
Referenced by HoughTransformerNode(), and OnCameraMsg().
camera_subscription_
rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr iii_drone::perception::hough_transformer_node::HoughTransformerNode::camera_subscription_ private
Subscription object for the image topic.
Definition at line 96 of file hough_transformer_node.hpp.
Referenced by HoughTransformerNode().
configurator_
HoughTransformerConfigurator iii_drone::perception::hough_transformer_node::HoughTransformerNode::configurator_ private
Configurator object.
Definition at line 86 of file hough_transformer_node.hpp.
hough_transformer_
HoughTransformer iii_drone::perception::hough_transformer_node::HoughTransformerNode::hough_transformer_ private
HoughTransformer object.
Definition at line 91 of file hough_transformer_node.hpp.
Referenced by OnCameraMsg().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/perception/hough_transformer_node/hough_transformer_node.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/perception/hough_transformer_node/hough_transformer_node.cpp