III-Drone: iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator Class Reference
iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator Class Reference
#include <continuous_mission_orchestrator_node.hpp>
Public Types
using FlyUnderCable = iii_drone_interfaces::action::FlyUnderCable
using GoalHandleFlyUnderCable = rclcpp_action::ClientGoalHandle<FlyUnderCable>
using CableLanding = iii_drone_interfaces::action::CableLanding
using GoalHandleCableLanding = rclcpp_action::ClientGoalHandle<CableLanding>
using DisarmOnCable = iii_drone_interfaces::action::DisarmOnCable
using GoalHandleDisarmOnCable = rclcpp_action::ClientGoalHandle<DisarmOnCable>
using ArmOnCable = iii_drone_interfaces::action::ArmOnCable
using GoalHandleArmOnCable = rclcpp_action::ClientGoalHandle<ArmOnCable>
using CableTakeoff = iii_drone_interfaces::action::CableTakeoff
using GoalHandleCableTakeoff = rclcpp_action::ClientGoalHandle<CableTakeoff>
Public Member Functions
ContinuousMissionOrchestrator (const std::string &node_name="continuous_mission_orchestrator", const std::string &node_namespace="/mission/continuous_mission_orchestrator", const rclcpp::NodeOptions &options=rclcpp::NodeOptions())
Private Types
enum state_t {
manual , wait_for_target_line , flying_under_cable , inspecting ,
landing_on_cable , closing_gripper , disarming_on_cable , charging ,
arming_on_cable , opening_gripper , taking_off_from_cable , error
}
Private Member Functions
void flyUnderCableGoalResponseCallback (const GoalHandleFlyUnderCable::SharedPtr &goal_handle)
void flyUnderCableFeedbackCallback (GoalHandleFlyUnderCable::SharedPtr, const std::shared_ptr< const FlyUnderCable::Feedback > feedback)
void flyUnderCableResultCallback (const GoalHandleFlyUnderCable::WrappedResult &result)
void startFlyUnderCable ()
bool flyUnderCableTerminated ()
bool flyUnderCableSucceeded ()
void cancelFlyUnderCable ()
void cableLandingGoalResponseCallback (const GoalHandleCableLanding::SharedPtr &goal_handle)
void cableLandingFeedbackCallback (GoalHandleCableLanding::SharedPtr, const std::shared_ptr< const CableLanding::Feedback > feedback)
void cableLandingResultCallback (const GoalHandleCableLanding::WrappedResult &result)
void startCableLanding ()
bool cableLandingTerminated ()
bool cableLandingSucceeded ()
void cancelCableLanding ()
void disarmOnCableGoalResponseCallback (const GoalHandleDisarmOnCable::SharedPtr &goal_handle)
void disarmOnCableFeedbackCallback (GoalHandleDisarmOnCable::SharedPtr, const std::shared_ptr< const DisarmOnCable::Feedback > feedback)
void disarmOnCableResultCallback (const GoalHandleDisarmOnCable::WrappedResult &result)
void startDisarmOnCable ()
bool disarmOnCableTerminated ()
bool disarmOnCableSucceeded ()
void cancelDisarmOnCable ()
void armOnCableGoalResponseCallback (const GoalHandleArmOnCable::SharedPtr &goal_handle)
void armOnCableFeedbackCallback (GoalHandleArmOnCable::SharedPtr, const std::shared_ptr< const ArmOnCable::Feedback > feedback)
void armOnCableResultCallback (const GoalHandleArmOnCable::WrappedResult &result)
void startArmOnCable ()
bool armOnCableTerminated ()
bool armOnCableSucceeded ()
void cancelArmOnCable ()
void cableTakeoffGoalResponseCallback (const GoalHandleCableTakeoff::SharedPtr &goal_handle)
void cableTakeoffFeedbackCallback (GoalHandleCableTakeoff::SharedPtr, const std::shared_ptr< const CableTakeoff::Feedback > feedback)
void cableTakeoffResultCallback (const GoalHandleCableTakeoff::WrappedResult &result)
void startCableTakeoff ()
bool cableTakeoffTerminated ()
bool cableTakeoffSucceeded ()
void cancelCableTakeoff ()
void gripperCommandResponseCallback (rclcpp::Client< iii_drone_interfaces::srv::GripperCommand >::SharedFuture future)
void sendGripperCommand (bool close)
bool gripperCommandTerminated ()
bool gripperCommandSucceeded ()
bool getLastGripperCommandClose ()
void setTargetCableIdSrvCallback (const std::shared_ptr< rmw_request_id_t > request_header, const std::shared_ptr< iii_drone_interfaces::srv::SetTargetCableId::Request > request, const std::shared_ptr< iii_drone_interfaces::srv::SetTargetCableId::Response > response)
int8_t getTargetCableId ()
void setTargetCableId (int8_t cable_id)
bool targetCableIdChanged ()
void setTargetCableIdChanged (bool changed)
void batteryVoltageCallback (std_msgs::msg::Float32::SharedPtr msg)
float getBatteryVoltage ()
void setBatteryVoltage (float voltage)
bool batteryVoltageLow ()
void setBatteryVoltageLow (bool low)
bool batteryVoltageHigh ()
void setBatteryVoltageHigh (bool high)
void chargingPowerCallback (std_msgs::msg::Float32::SharedPtr msg)
float getChargingPower ()
bool chargingPowerLow ()
void chargerOperatingModeCallback (iii_drone_interfaces::msg::ChargerOperatingMode::SharedPtr msg)
iii_drone_interfaces::msg::ChargerOperatingMode getChargerOperatingMode ()
void chargerStatusCallback (iii_drone_interfaces::msg::ChargerStatus::SharedPtr msg)
iii_drone_interfaces::msg::ChargerStatus getChargerStatus ()
bool chargerStatusDisabled ()
void setChargerStatusDisabled (bool disabled)
bool chargerStatusCharging ()
void setChargerStatusCharging (bool charging)
bool chargerStatusFullyCharged ()
void setChargerStatusFullyCharged (bool fully_charged)
void gripperStatusCallback (iii_drone_interfaces::msg::GripperStatus::SharedPtr msg)
iii_drone_interfaces::msg::GripperStatus getGripperStatus ()
bool gripperIsClosed ()
bool gripperIsOpen ()
rclcpp::Time getChargingStartTime ()
void initiateChargingSrvCallback (const std::shared_ptr< rmw_request_id_t > request_header, const std::shared_ptr< iii_drone_interfaces::srv::InitiateCharging::Request > request, const std::shared_ptr< iii_drone_interfaces::srv::InitiateCharging::Response > response)
bool initiateChargingSrvCalled ()
void clearInitiateChargingSrvCalled ()
void interruptChargingSrvCallback (const std::shared_ptr< rmw_request_id_t > request_header, const std::shared_ptr< iii_drone_interfaces::srv::InterruptCharging::Request > request, const std::shared_ptr< iii_drone_interfaces::srv::InterruptCharging::Response > response)
bool interruptChargingSrvCalled ()
void clearInterruptChargingSrvCalled ()
void prolongChargingSrvCallback (const std::shared_ptr< rmw_request_id_t > request_header, const std::shared_ptr< iii_drone_interfaces::srv::ProlongCharging::Request > request, const std::shared_ptr< iii_drone_interfaces::srv::ProlongCharging::Response > response)
bool prolongChargingUntilInterrupted ()
float getProlongChargingForSeconds ()
float getProlongChargingUntilNewBatteryVoltage ()
void clearProlongCharging ()
void evaluateChargingStatus ()
bool getStartChargingFlag ()
void setStartChargingFlag (bool flag)
bool getStopChargingFlag ()
void setStopChargingFlag (bool flag)
void controlStateCallback (iii_drone_interfaces::msg::ControlState::SharedPtr msg)
iii_drone_interfaces::msg::ControlState getControlState ()
void setControlState (iii_drone_interfaces::msg::ControlState control_state)
bool isInControllableState ()
bool isInControllableState (iii_drone_interfaces::msg::ControlState control_state)
state_t getState ()
void setState (state_t state)
void stateMachineCallback ()
void stateMachineManual ()
void stateMachineWaitForTargetLine ()
void stateMachineFlyingUnderCable ()
void stateMachineInspecting ()
void stateMachineLandingOnCable ()
void stateMachineClosingGripper ()
void stateMachineDisarmingOnCable ()
void stateMachineCharging ()
void stateMachineArmingOnCable ()
void stateMachineOpeningGripper ()
void stateMachineTakingOffFromCable ()
void stateMachineError ()
void startActionTimeoutCounter ()
bool actionTimeout ()
void publishCallback ()
Private Attributes
rclcpp_action::Client< FlyUnderCable >::SharedPtr fly_under_cable_client_
bool fly_under_cable_response_received_
bool fly_under_cable_goal_accepted_
bool fly_under_cable_active_
bool fly_under_cable_success_
std::mutex fly_under_cable_mutex_
rclcpp_action::Client< CableLanding >::SharedPtr cable_landing_client_
bool cable_landing_response_received_
bool cable_landing_goal_accepted_
bool cable_landing_active_
bool cable_landing_success_
std::mutex cable_landing_mutex_
int cable_landing_counter_
rclcpp_action::Client< DisarmOnCable >::SharedPtr disarm_on_cable_client_
bool disarm_on_cable_response_received_
bool disarm_on_cable_goal_accepted_
bool disarm_on_cable_active_
bool disarm_on_cable_success_
std::mutex disarm_on_cable_mutex_
rclcpp_action::Client< ArmOnCable >::SharedPtr arm_on_cable_client_
bool arm_on_cable_response_received_
bool arm_on_cable_goal_accepted_
bool arm_on_cable_active_
bool arm_on_cable_success_
std::mutex arm_on_cable_mutex_
rclcpp_action::Client< CableTakeoff >::SharedPtr cable_takeoff_client_
bool cable_takeoff_response_received_
bool cable_takeoff_goal_accepted_
bool cable_takeoff_active_
bool cable_takeoff_success_
std::mutex cable_takeoff_mutex_
rclcpp::Client< iii_drone_interfaces::srv::GripperCommand >::SharedPtr gripper_command_client_
bool gripper_command_response_received_
bool gripper_command_active_
bool gripper_command_success_
bool last_gripper_command_close_ = false
std::mutex gripper_command_mutex_
rclcpp::Service< iii_drone_interfaces::srv::SetTargetCableId >::SharedPtr set_target_cable_id_srv_
int8_t target_cable_id_ = -1
bool target_cable_id_changed_ = false
std::mutex target_cable_id_mutex_
rclcpp::Subscription< std_msgs::msg::Float32 >::SharedPtr battery_voltage_sub_
float battery_voltage_ = false
bool battery_voltage_low_ = false
bool battery_voltage_high_ = false
std::mutex battery_voltage_mutex_
rclcpp::Subscription< std_msgs::msg::Float32 >::SharedPtr charging_power_sub_
float charging_power_ = false
bool charging_power_low_ = false
std::mutex charging_power_mutex_
rclcpp::Subscription< iii_drone_interfaces::msg::ChargerOperatingMode >::SharedPtr charger_operating_mode_sub_
iii_drone_interfaces::msg::ChargerOperatingMode charger_operating_mode_
std::mutex charger_operating_mode_mutex_
rclcpp::Subscription< iii_drone_interfaces::msg::ChargerStatus >::SharedPtr charger_status_sub_
iii_drone_interfaces::msg::ChargerStatus charger_status_
bool charger_status_disabled_ = false
bool charger_status_charging_ = false
bool charger_status_fully_charged_ = false
std::mutex charger_status_mutex_
rclcpp::Subscription< iii_drone_interfaces::msg::GripperStatus >::SharedPtr gripper_status_sub_
iii_drone_interfaces::msg::GripperStatus gripper_status_
std::mutex gripper_status_mutex_
rclcpp::Time charging_start_time_
std::mutex charging_start_time_mutex_
rclcpp::Service< iii_drone_interfaces::srv::InitiateCharging >::SharedPtr initiate_charging_srv_server_
bool initiate_charging_srv_called_ = false
std::mutex initiate_charging_srv_called_mutex_
rclcpp::Service< iii_drone_interfaces::srv::InterruptCharging >::SharedPtr interrupt_charging_srv_server_
bool interrupt_charging_srv_called_ = false
std::mutex interrupt_charging_srv_called_mutex_
rclcpp::Service< iii_drone_interfaces::srv::ProlongCharging >::SharedPtr prolong_charging_srv_server_
bool prolong_charging_until_interrupted_ = false
float prolong_charging_for_seconds_ = -1
float prolong_charging_until_new_battery_voltage_ = -1
std::mutex prolong_charging_mutex_
bool start_charging_flag_ {false}
std::mutex start_charging_flag_mutex_
bool stop_charging_flag_ {false}
std::mutex stop_charging_flag_mutex_
rclcpp::Subscription< iii_drone_interfaces::msg::ControlState >::SharedPtr control_state_sub_
iii_drone_interfaces::msg::ControlState control_state_
std::mutex control_state_mutex_
std::shared_ptr< tf2_ros::TransformListener > transform_listener_ {nullptr}
std::unique_ptr< tf2_ros::Buffer > tf_buffer_
state_t state_ = manual
std::mutex state_mutex_
rclcpp::TimerBase::SharedPtr state_machine_timer_
rclcpp::Time action_start_time_
rclcpp::Publisher< std_msgs::msg::String >::SharedPtr state_pub_
rclcpp::TimerBase::SharedPtr publish_timer_
Detailed Description
Definition at line 64 of file continuous_mission_orchestrator_node.hpp.
Member Typedef Documentation
ArmOnCable
using iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::ArmOnCable = iii_drone_interfaces::action::ArmOnCable
Definition at line 75 of file continuous_mission_orchestrator_node.hpp.
CableLanding
using iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::CableLanding = iii_drone_interfaces::action::CableLanding
Definition at line 69 of file continuous_mission_orchestrator_node.hpp.
CableTakeoff
using iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::CableTakeoff = iii_drone_interfaces::action::CableTakeoff
Definition at line 78 of file continuous_mission_orchestrator_node.hpp.
DisarmOnCable
using iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::DisarmOnCable = iii_drone_interfaces::action::DisarmOnCable
Definition at line 72 of file continuous_mission_orchestrator_node.hpp.
FlyUnderCable
using iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::FlyUnderCable = iii_drone_interfaces::action::FlyUnderCable
Definition at line 66 of file continuous_mission_orchestrator_node.hpp.
GoalHandleArmOnCable
using iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::GoalHandleArmOnCable = rclcpp_action::ClientGoalHandle<ArmOnCable>
Definition at line 76 of file continuous_mission_orchestrator_node.hpp.
GoalHandleCableLanding
using iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::GoalHandleCableLanding = rclcpp_action::ClientGoalHandle<CableLanding>
Definition at line 70 of file continuous_mission_orchestrator_node.hpp.
GoalHandleCableTakeoff
using iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::GoalHandleCableTakeoff = rclcpp_action::ClientGoalHandle<CableTakeoff>
Definition at line 79 of file continuous_mission_orchestrator_node.hpp.
GoalHandleDisarmOnCable
using iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::GoalHandleDisarmOnCable = rclcpp_action::ClientGoalHandle<DisarmOnCable>
Definition at line 73 of file continuous_mission_orchestrator_node.hpp.
GoalHandleFlyUnderCable
using iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::GoalHandleFlyUnderCable = rclcpp_action::ClientGoalHandle<FlyUnderCable>
Definition at line 67 of file continuous_mission_orchestrator_node.hpp.
Member Enumeration Documentation
state_t
enum iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::state_t private
Enumerator
manual
wait_for_target_line
flying_under_cable
inspecting
landing_on_cable
closing_gripper
disarming_on_cable
charging
arming_on_cable
opening_gripper
taking_off_from_cable
error
Definition at line 317 of file continuous_mission_orchestrator_node.hpp.
                     {
            manual,
            wait_for_target_line,
            flying_under_cable,
            inspecting,
            landing_on_cable,
            closing_gripper,
            disarming_on_cable,
            charging,
            arming_on_cable,
            opening_gripper,
            taking_off_from_cable,
            error
        } state_t;
Constructor & Destructor Documentation
ContinuousMissionOrchestrator()
ContinuousMissionOrchestrator::ContinuousMissionOrchestrator (const std::string & node_name = "continuous_mission_orchestrator", const std::string & node_namespace = "/mission/continuous_mission_orchestrator", const rclcpp::NodeOptions & options = rclcpp::NodeOptions())
Definition at line 16 of file continuous_mission_orchestrator_node.cpp.
                                                                                     :
        Node(node_name, node_namespace, options) {
    RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator()");
    // Parameters:
    this->declare_parameter<bool>("simulation", false);
    this->declare_parameter<float>("under_cable_target_distance", 1.5);
    this->declare_parameter<bool>("use_charger_gripper_info", true);
    this->declare_parameter<int>("cable_landing_max_retries", 3);
    this->declare_parameter<float>("battery_voltage_low_threshold", 22.2);
    this->declare_parameter<float>("battery_voltage_high_threshold", 25.);
    this->declare_parameter<float>("charging_power_low_threshold", 0.1);
    this->declare_parameter<int>("action_timeout_ms", 1000);
    this->declare_parameter<int>("charging_minimum_duration_s", 10);
    this->declare_parameter<int>("charging_maximum_duration_s", -1);
    // Action clients:
    this->fly_under_cable_client_ = rclcpp_action::create_client<FlyUnderCable>(
       this, "/control/flight_controller/fly_under_cable"
    );
    this->cable_landing_client_ = rclcpp_action::create_client<CableLanding>(
       this, "/control/flight_controller/cable_landing"
    );
    this->disarm_on_cable_client_ = rclcpp_action::create_client<DisarmOnCable>(
       this, "/control/flight_controller/disarm_on_cable"
    );
    this->arm_on_cable_client_ = rclcpp_action::create_client<ArmOnCable>(
       this, "/control/flight_controller/arm_on_cable"
    );
    this->cable_takeoff_client_ = rclcpp_action::create_client<CableTakeoff>(
       this, "/control/flight_controller/cable_takeoff"
    );
    // Gripper command client:
    this->gripper_command_client_ = this->create_client<iii_drone_interfaces::srv::GripperCommand>(
        "/payload/charger_gripper/gripper_command"
    );
    // Target cable service:
    set_target_cable_id_srv_ = this->create_service<iii_drone_interfaces::srv::SetTargetCableId>(
        "set_target_cable_id",
        std::bind(&ContinuousMissionOrchestrator::setTargetCableIdSrvCallback, this, _1, _2, _3)
    );
    // Charger/gripper status:
    battery_voltage_sub_ = this->create_subscription<std_msgs::msg::Float32>(
        "/payload/charger_gripper/battery_voltage", 10,
        std::bind(&ContinuousMissionOrchestrator::batteryVoltageCallback, this, std::placeholders::_1));
    charging_power_sub_ = this->create_subscription<std_msgs::msg::Float32>(
        "/payload/charger_gripper/charging_power", 10,
        std::bind(&ContinuousMissionOrchestrator::chargingPowerCallback, this, std::placeholders::_1));
    charger_operating_mode_sub_ = this->create_subscription<iii_drone_interfaces::msg::ChargerOperatingMode>(
        "/payload/charger_gripper/charger_operating_mode", 10,
        std::bind(&ContinuousMissionOrchestrator::chargerOperatingModeCallback, this, std::placeholders::_1));
    charger_status_sub_ = this->create_subscription<iii_drone_interfaces::msg::ChargerStatus>(
        "/payload/charger_gripper/charger_status", 10,
        std::bind(&ContinuousMissionOrchestrator::chargerStatusCallback, this, std::placeholders::_1));
    gripper_status_sub_ = this->create_subscription<iii_drone_interfaces::msg::GripperStatus>(
        "/payload/charger_gripper/gripper_status", 10,
        std::bind(&ContinuousMissionOrchestrator::gripperStatusCallback, this, std::placeholders::_1));
    // Charging:
    initiate_charging_srv_server_ = this->create_service<iii_drone_interfaces::srv::InitiateCharging>(
        "initiate_charging",
        std::bind(&ContinuousMissionOrchestrator::initiateChargingSrvCallback, this, _1, _2, _3)
    );
    interrupt_charging_srv_server_ = this->create_service<iii_drone_interfaces::srv::InterruptCharging>(
        "interrupt_charging",
        std::bind(&ContinuousMissionOrchestrator::interruptChargingSrvCallback, this, _1, _2, _3)
    );
    // Control state:
    control_state_sub_ = this->create_subscription<iii_drone_interfaces::msg::ControlState>(
        "/control/flight_controller/control_state", 10,
        std::bind(&ContinuousMissionOrchestrator::controlStateCallback, this, std::placeholders::_1));
    // tf
    tf_buffer_ = std::make_unique<tf2_ros::Buffer>(this->get_clock());
    transform_listener_ = std::make_shared<tf2_ros::TransformListener>(*tf_buffer_);
    // State machine:
    state_machine_timer_ = this->create_wall_timer(
        std::chrono::milliseconds(100), std::bind(&ContinuousMissionOrchestrator::stateMachineCallback, this)
    );
    state_pub_ = this->create_publisher<std_msgs::msg::String>("state", 10);
    // Publishing:
    publish_timer_ = this->create_wall_timer(
        std::chrono::milliseconds(100), std::bind(&ContinuousMissionOrchestrator::publishCallback, this)
    );
}
References arm_on_cable_client_, battery_voltage_sub_, batteryVoltageCallback(), cable_landing_client_, cable_takeoff_client_, charger_operating_mode_sub_, charger_status_sub_, chargerOperatingModeCallback(), chargerStatusCallback(), charging_power_sub_, chargingPowerCallback(), control_state_sub_, controlStateCallback(), disarm_on_cable_client_, fly_under_cable_client_, gripper_command_client_, gripper_status_sub_, gripperStatusCallback(), initiate_charging_srv_server_, initiateChargingSrvCallback(), interrupt_charging_srv_server_, interruptChargingSrvCallback(), publish_timer_, publishCallback(), set_target_cable_id_srv_, setTargetCableIdSrvCallback(), state_machine_timer_, state_pub_, stateMachineCallback(), tf_buffer_, and transform_listener_.
Member Function Documentation
actionTimeout()
bool ContinuousMissionOrchestrator::actionTimeout () private
Definition at line 2385 of file continuous_mission_orchestrator_node.cpp.
{
    float action_timeout_ms;
    this->get_parameter("action_timeout_ms", action_timeout_ms);
    return (this->now() - action_start_time_).nanoseconds() / 1000000 > action_timeout_ms;
}
References action_start_time_.
Referenced by stateMachineArmingOnCable(), stateMachineDisarmingOnCable(), stateMachineFlyingUnderCable(), stateMachineLandingOnCable(), stateMachineOpeningGripper(), and stateMachineTakingOffFromCable().
armOnCableFeedbackCallback()
void ContinuousMissionOrchestrator::armOnCableFeedbackCallback (GoalHandleArmOnCable::SharedPtr , const std::shared_ptr< const ArmOnCable::Feedback > feedback) private
Definition at line 506 of file continuous_mission_orchestrator_node.cpp.
  { }
Referenced by startArmOnCable().
armOnCableGoalResponseCallback()
void ContinuousMissionOrchestrator::armOnCableGoalResponseCallback (const GoalHandleArmOnCable::SharedPtr & goal_handle) private
Definition at line 482 of file continuous_mission_orchestrator_node.cpp.
{
    bool goal_accepted = false;
    if (!goal_handle) {
        RCLCPP_ERROR(this->get_logger(), "ContinuousMissionOrchestrator::armOnCableGoalResponseCallback(): Goal was rejected by server");
        goal_accepted = false;
    } else {
        RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::armOnCableGoalResponseCallback(): Goal accepted by server, waiting for result");
        goal_accepted = true;
    }
    std::lock_guard<std::mutex> lock(arm_on_cable_mutex_);
    arm_on_cable_response_received_ = true;
    arm_on_cable_goal_accepted_ = goal_accepted;
    arm_on_cable_active_ = goal_accepted;
}
References arm_on_cable_active_, arm_on_cable_goal_accepted_, arm_on_cable_mutex_, and arm_on_cable_response_received_.
Referenced by startArmOnCable().
armOnCableResultCallback()
void ContinuousMissionOrchestrator::armOnCableResultCallback (const GoalHandleArmOnCable::WrappedResult & result) private
Definition at line 511 of file continuous_mission_orchestrator_node.cpp.
{
    bool arm_on_cable_active = false;
    bool arm_on_cable_success = false;
    switch (result.code) {
        case rclcpp_action::ResultCode::SUCCEEDED:
            RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::armOnCableResultCallback(): ArmOnCable succeeded");
            arm_on_cable_active = false;
            arm_on_cable_success = true;
            break;
        case rclcpp_action::ResultCode::ABORTED:
            RCLCPP_WARN(this->get_logger(), "ContinuousMissionOrchestrator::armOnCableResultCallback(): ArmOnCable was aborted");
            arm_on_cable_active = false;
            arm_on_cable_success = false;
            break;
        case rclcpp_action::ResultCode::CANCELED:
            RCLCPP_WARN(this->get_logger(), "ContinuousMissionOrchestrator::armOnCableResultCallback(): ArmOnCable was canceled");
            arm_on_cable_active = false;
            arm_on_cable_success = false;
            break;
        default:
            RCLCPP_ERROR(this->get_logger(), "ContinuousMissionOrchestrator::armOnCableResultCallback(): Unknown result code for ArmOnCable");
            arm_on_cable_active = false;
            arm_on_cable_success = false;
            break;
    }
    std::lock_guard<std::mutex> lock(arm_on_cable_mutex_);
    arm_on_cable_active_ = arm_on_cable_active;
    arm_on_cable_success_ = arm_on_cable_success;
}
References arm_on_cable_active_, arm_on_cable_mutex_, and arm_on_cable_success_.
Referenced by startArmOnCable().
armOnCableSucceeded()
bool ContinuousMissionOrchestrator::armOnCableSucceeded () private
Definition at line 585 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(arm_on_cable_mutex_);
    return arm_on_cable_goal_accepted_ && arm_on_cable_success_;
}
References arm_on_cable_goal_accepted_, arm_on_cable_mutex_, and arm_on_cable_success_.
Referenced by stateMachineArmingOnCable().
armOnCableTerminated()
bool ContinuousMissionOrchestrator::armOnCableTerminated () private
Definition at line 577 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(arm_on_cable_mutex_);
    return (!arm_on_cable_active_) && arm_on_cable_response_received_;
}
References arm_on_cable_active_, arm_on_cable_mutex_, and arm_on_cable_response_received_.
Referenced by stateMachineArmingOnCable().
batteryVoltageCallback()
void ContinuousMissionOrchestrator::batteryVoltageCallback (std_msgs::msg::Float32::SharedPtr msg) private
Definition at line 848 of file continuous_mission_orchestrator_node.cpp.
{
    float tlo, thi;
    this->get_parameter("battery_voltage_low_threshold", tlo);
    this->get_parameter("battery_voltage_high_threshold", thi);
    std::lock_guard<std::mutex> lock(battery_voltage_mutex_);
    battery_voltage_ = msg->data;
    if (battery_voltage_ < tlo) {
        battery_voltage_low_ = true;
        battery_voltage_high_ = false;
    } else if (battery_voltage_ > thi) {
        battery_voltage_low_ = false;
        battery_voltage_high_ = true;
    } else {
        battery_voltage_low_ = false;
        battery_voltage_high_ = false;
    }
}
References battery_voltage_, battery_voltage_high_, battery_voltage_low_, and battery_voltage_mutex_.
Referenced by ContinuousMissionOrchestrator().
batteryVoltageHigh()
bool ContinuousMissionOrchestrator::batteryVoltageHigh () private
Definition at line 900 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(battery_voltage_mutex_);
    return battery_voltage_high_;
}
References battery_voltage_high_, and battery_voltage_mutex_.
Referenced by evaluateChargingStatus().
batteryVoltageLow()
bool ContinuousMissionOrchestrator::batteryVoltageLow () private
Definition at line 884 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(battery_voltage_mutex_);
    return battery_voltage_low_;
}
References battery_voltage_low_, and battery_voltage_mutex_.
Referenced by evaluateChargingStatus().
cableLandingFeedbackCallback()
void ContinuousMissionOrchestrator::cableLandingFeedbackCallback (GoalHandleCableLanding::SharedPtr , const std::shared_ptr< const CableLanding::Feedback > feedback) private
Definition at line 263 of file continuous_mission_orchestrator_node.cpp.
  { }
Referenced by startCableLanding().
cableLandingGoalResponseCallback()
void ContinuousMissionOrchestrator::cableLandingGoalResponseCallback (const GoalHandleCableLanding::SharedPtr & goal_handle) private
Definition at line 239 of file continuous_mission_orchestrator_node.cpp.
{
    bool goal_accepted = false;
    if (!goal_handle) {
        RCLCPP_ERROR(this->get_logger(), "ContinuousMissionOrchestrator::cableLandingGoalResponseCallback(): CableLanding goal was rejected by server");
        goal_accepted = false;
    } else {
        RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::cableLandingGoalResponseCallback(): Goal accepted by server, waiting for result");
        goal_accepted = true;
    }
    std::lock_guard<std::mutex> lock(cable_landing_mutex_);
    cable_landing_response_received_ = true;
    cable_landing_goal_accepted_ = goal_accepted;
    cable_landing_active_ = goal_accepted;
}
References cable_landing_active_, cable_landing_goal_accepted_, cable_landing_mutex_, and cable_landing_response_received_.
Referenced by startCableLanding().
cableLandingResultCallback()
void ContinuousMissionOrchestrator::cableLandingResultCallback (const GoalHandleCableLanding::WrappedResult & result) private
Definition at line 268 of file continuous_mission_orchestrator_node.cpp.
{
    bool cable_landing_active = false;
    bool cable_landing_success = false;
    switch (result.code) {
        case rclcpp_action::ResultCode::SUCCEEDED:
            RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::cableLandingResultCallback(): CableLanding succeeded");
            cable_landing_active = false;
            cable_landing_success = true;
            break;
        case rclcpp_action::ResultCode::ABORTED:
            RCLCPP_WARN(this->get_logger(), "ContinuousMissionOrchestrator::cableLandingResultCallback(): CableLanding was aborted");
            cable_landing_active = false;
            cable_landing_success = false;
            break;
        case rclcpp_action::ResultCode::CANCELED:
            RCLCPP_WARN(this->get_logger(), "ContinuousMissionOrchestrator::cableLandingResultCallback(): CableLanding was canceled");
            cable_landing_active = false;
            cable_landing_success = false;
            break;
        default:
            RCLCPP_ERROR(this->get_logger(), "ContinuousMissionOrchestrator::cableLandingResultCallback(): Unknown result code for CableLanding");
            cable_landing_active = false;
            cable_landing_success = false;
            break;
    }
    std::lock_guard<std::mutex> lock(cable_landing_mutex_);
    cable_landing_active_ = cable_landing_active;
    cable_landing_success_ = cable_landing_success;
}
References cable_landing_active_, cable_landing_mutex_, and cable_landing_success_.
Referenced by startCableLanding().
cableLandingSucceeded()
bool ContinuousMissionOrchestrator::cableLandingSucceeded () private
Definition at line 343 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(cable_landing_mutex_);
    return cable_landing_goal_accepted_ && cable_landing_success_;
}
References cable_landing_goal_accepted_, cable_landing_mutex_, and cable_landing_success_.
Referenced by stateMachineLandingOnCable().
cableLandingTerminated()
bool ContinuousMissionOrchestrator::cableLandingTerminated () private
Definition at line 335 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(cable_landing_mutex_);
    return (!cable_landing_active_) && cable_landing_response_received_;
}
References cable_landing_active_, cable_landing_mutex_, and cable_landing_response_received_.
Referenced by stateMachineLandingOnCable().
cableTakeoffFeedbackCallback()
void ContinuousMissionOrchestrator::cableTakeoffFeedbackCallback (GoalHandleCableTakeoff::SharedPtr , const std::shared_ptr< const CableTakeoff::Feedback > feedback) private
Definition at line 627 of file continuous_mission_orchestrator_node.cpp.
  { }
Referenced by startCableTakeoff().
cableTakeoffGoalResponseCallback()
void ContinuousMissionOrchestrator::cableTakeoffGoalResponseCallback (const GoalHandleCableTakeoff::SharedPtr & goal_handle) private
Definition at line 603 of file continuous_mission_orchestrator_node.cpp.
{
    bool goal_accepted = false;
    if (!goal_handle) {
        RCLCPP_ERROR(this->get_logger(), "ContinuousMissionOrchestrator::cableTakeoffGoalResponseCallback(): Goal was rejected by server");
        goal_accepted = false;
    } else {
        RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::cableTakeoffGoalResponseCallback(): Goal was accepted by server");
        goal_accepted = true;
    }
    std::lock_guard<std::mutex> lock(cable_takeoff_mutex_);
    cable_takeoff_response_received_ = true;
    cable_takeoff_goal_accepted_ = goal_accepted;
    cable_takeoff_active_ = goal_accepted;
}
References cable_takeoff_active_, cable_takeoff_goal_accepted_, cable_takeoff_mutex_, and cable_takeoff_response_received_.
Referenced by startCableTakeoff().
cableTakeoffResultCallback()
void ContinuousMissionOrchestrator::cableTakeoffResultCallback (const GoalHandleCableTakeoff::WrappedResult & result) private
Definition at line 632 of file continuous_mission_orchestrator_node.cpp.
{
    bool cable_takeoff_active = false;
    bool cable_takeoff_success = false;
    switch (result.code) {
        case rclcpp_action::ResultCode::SUCCEEDED:
            RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::cableTakeoffResultCallback(): CableTakeoff succeeded");
            cable_takeoff_active = false;
            cable_takeoff_success = true;
            break;
        case rclcpp_action::ResultCode::ABORTED:
            RCLCPP_WARN(this->get_logger(), "ContinuousMissionOrchestrator::cableTakeoffResultCallback(): CableTakeoff was aborted");
            cable_takeoff_active = false;
            cable_takeoff_success = false;
            break;
        case rclcpp_action::ResultCode::CANCELED:
            RCLCPP_WARN(this->get_logger(), "ContinuousMissionOrchestrator::cableTakeoffResultCallback(): CableTakeoff was canceled");
            cable_takeoff_active = false;
            cable_takeoff_success = false;
            break;
        default:
            RCLCPP_ERROR(this->get_logger(), "ContinuousMissionOrchestrator::cableTakeoffResultCallback(): Unknown result code for CableTakeoff");
            cable_takeoff_active = false;
            cable_takeoff_success = false;
            break;
    }
    std::lock_guard<std::mutex> lock(cable_takeoff_mutex_);
    cable_takeoff_active_ = cable_takeoff_active;
    cable_takeoff_success_ = cable_takeoff_success;
}
References cable_takeoff_active_, cable_takeoff_mutex_, and cable_takeoff_success_.
Referenced by startCableTakeoff().
cableTakeoffSucceeded()
bool ContinuousMissionOrchestrator::cableTakeoffSucceeded () private
Definition at line 709 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(cable_takeoff_mutex_);
    return cable_takeoff_goal_accepted_ && cable_takeoff_success_;
}
References cable_takeoff_goal_accepted_, cable_takeoff_mutex_, and cable_takeoff_success_.
Referenced by stateMachineTakingOffFromCable().
cableTakeoffTerminated()
bool ContinuousMissionOrchestrator::cableTakeoffTerminated () private
Definition at line 701 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(cable_takeoff_mutex_);
    return (!cable_takeoff_active_) && cable_takeoff_response_received_;
}
References cable_takeoff_active_, cable_takeoff_mutex_, and cable_takeoff_response_received_.
Referenced by stateMachineTakingOffFromCable().
cancelArmOnCable()
void ContinuousMissionOrchestrator::cancelArmOnCable () private
Definition at line 593 of file continuous_mission_orchestrator_node.cpp.
{
    RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::cancelArmOnCable(): Canceling ArmOnCable");
    arm_on_cable_client_->async_cancel_all_goals();
}
References arm_on_cable_client_.
cancelCableLanding()
void ContinuousMissionOrchestrator::cancelCableLanding () private
Definition at line 351 of file continuous_mission_orchestrator_node.cpp.
{
    RCLCPP_WARN(this->get_logger(), "ContinuousMissionOrchestrator::cancelCableLanding(): Canceling CableLanding");
    cable_landing_client_->async_cancel_all_goals();
}
References cable_landing_client_.
Referenced by stateMachineLandingOnCable().
cancelCableTakeoff()
void ContinuousMissionOrchestrator::cancelCableTakeoff () private
Definition at line 717 of file continuous_mission_orchestrator_node.cpp.
{
    RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::cancelCableTakeoff(): Canceling CableTakeoff");
    cable_takeoff_client_->async_cancel_all_goals();
}
References cable_takeoff_client_.
cancelDisarmOnCable()
void ContinuousMissionOrchestrator::cancelDisarmOnCable () private
Definition at line 472 of file continuous_mission_orchestrator_node.cpp.
{
    RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::cancelDisarmOnCable(): Canceling DisarmOnCable");
    disarm_on_cable_client_->async_cancel_all_goals();
}
References disarm_on_cable_client_.
cancelFlyUnderCable()
void ContinuousMissionOrchestrator::cancelFlyUnderCable () private
Definition at line 229 of file continuous_mission_orchestrator_node.cpp.
{
    RCLCPP_WARN(this->get_logger(), "ContinuousMissionOrchestrator::cancelFlyUnderCable(): Canceling FlyUnderCable");
    fly_under_cable_client_->async_cancel_all_goals();
}
References fly_under_cable_client_.
Referenced by stateMachineFlyingUnderCable().
chargerOperatingModeCallback()
void ContinuousMissionOrchestrator::chargerOperatingModeCallback (iii_drone_interfaces::msg::ChargerOperatingMode::SharedPtr msg) private
Definition at line 952 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(charger_operating_mode_mutex_);
    charger_operating_mode_ = *msg;
}
References charger_operating_mode_, and charger_operating_mode_mutex_.
Referenced by ContinuousMissionOrchestrator().
chargerStatusCallback()
void ContinuousMissionOrchestrator::chargerStatusCallback (iii_drone_interfaces::msg::ChargerStatus::SharedPtr msg) private
Definition at line 968 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(charger_status_mutex_);
    charger_status_ = *msg;
    if (charger_status_.charger_status == charger_status_.CHARGER_STATUS_DISABLED) {
        charger_status_disabled_ = true;
        charger_status_charging_ = false;
        charger_status_fully_charged_ = false;
    } else if (charger_status_.charger_status == charger_status_.CHARGER_STATUS_CHARGING) {
        charger_status_disabled_ = false;
        charger_status_charging_ = true;
        charger_status_fully_charged_ = false;
    } else if (charger_status_.charger_status == charger_status_.CHARGER_STATUS_FULLY_CHARGED) {
        charger_status_disabled_ = false;
        charger_status_charging_ = false;
        charger_status_fully_charged_ = true;
    } else {
        charger_status_disabled_ = false;
        charger_status_charging_ = false;
        charger_status_fully_charged_ = false;
    }
}
References charger_status_, charger_status_charging_, charger_status_disabled_, charger_status_fully_charged_, and charger_status_mutex_.
Referenced by ContinuousMissionOrchestrator().
chargerStatusCharging()
bool ContinuousMissionOrchestrator::chargerStatusCharging () private
Definition at line 1028 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(charger_status_mutex_);
    return charger_status_charging_;
}
References charger_status_charging_, and charger_status_mutex_.
Referenced by evaluateChargingStatus().
chargerStatusDisabled()
bool ContinuousMissionOrchestrator::chargerStatusDisabled () private
Definition at line 1010 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(charger_status_mutex_);
    return charger_status_disabled_;
}
References charger_status_disabled_, and charger_status_mutex_.
chargerStatusFullyCharged()
bool ContinuousMissionOrchestrator::chargerStatusFullyCharged () private
Definition at line 1045 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(charger_status_mutex_);
    return charger_status_fully_charged_;
}
References charger_status_fully_charged_, and charger_status_mutex_.
chargingPowerCallback()
void ContinuousMissionOrchestrator::chargingPowerCallback (std_msgs::msg::Float32::SharedPtr msg) private
Definition at line 916 of file continuous_mission_orchestrator_node.cpp.
{
    float tlo;
    this->get_parameter("charging_power_low_threshold", tlo);
    std::lock_guard<std::mutex> lock(charging_power_mutex_);
    charging_power_ = msg->data;
    if (charging_power_ < tlo) {
        charging_power_low_ = true;
    } else {
        charging_power_low_ = false;
    }
}
References charging_power_, charging_power_low_, and charging_power_mutex_.
Referenced by ContinuousMissionOrchestrator().
chargingPowerLow()
bool ContinuousMissionOrchestrator::chargingPowerLow () private
Definition at line 944 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(charging_power_mutex_);
    return charging_power_low_;
}
References charging_power_low_, and charging_power_mutex_.
Referenced by evaluateChargingStatus().
clearInitiateChargingSrvCalled()
void ContinuousMissionOrchestrator::clearInitiateChargingSrvCalled () private
Definition at line 1172 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(initiate_charging_srv_called_mutex_);
    initiate_charging_srv_called_ = false;
}
References initiate_charging_srv_called_, and initiate_charging_srv_called_mutex_.
Referenced by evaluateChargingStatus().
clearInterruptChargingSrvCalled()
void ContinuousMissionOrchestrator::clearInterruptChargingSrvCalled () private
Definition at line 1218 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(interrupt_charging_srv_called_mutex_);
    interrupt_charging_srv_called_ = false;
}
References interrupt_charging_srv_called_, and interrupt_charging_srv_called_mutex_.
Referenced by evaluateChargingStatus().
clearProlongCharging()
void ContinuousMissionOrchestrator::clearProlongCharging () private
Definition at line 1324 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(prolong_charging_mutex_);
    prolong_charging_until_interrupted_ = false;
    prolong_charging_for_seconds_ = -1;
    prolong_charging_until_new_battery_voltage_ = -1;
}
References prolong_charging_for_seconds_, prolong_charging_mutex_, prolong_charging_until_interrupted_, and prolong_charging_until_new_battery_voltage_.
Referenced by evaluateChargingStatus().
controlStateCallback()
void ContinuousMissionOrchestrator::controlStateCallback (iii_drone_interfaces::msg::ControlState::SharedPtr msg) private
Definition at line 1491 of file continuous_mission_orchestrator_node.cpp.
{
    setControlState(*msg);
}
References setControlState().
Referenced by ContinuousMissionOrchestrator().
disarmOnCableFeedbackCallback()
void ContinuousMissionOrchestrator::disarmOnCableFeedbackCallback (GoalHandleDisarmOnCable::SharedPtr , const std::shared_ptr< const DisarmOnCable::Feedback > feedback) private
Definition at line 385 of file continuous_mission_orchestrator_node.cpp.
  { }
Referenced by startDisarmOnCable().
disarmOnCableGoalResponseCallback()
void ContinuousMissionOrchestrator::disarmOnCableGoalResponseCallback (const GoalHandleDisarmOnCable::SharedPtr & goal_handle) private
Definition at line 361 of file continuous_mission_orchestrator_node.cpp.
{
    bool goal_accepted = false;
    if (!goal_handle) {
        RCLCPP_ERROR(this->get_logger(), "ContinuousMissionOrchestrator::disarmOnCableGoalResponseCallback(): DisarmOnCable goal was rejected by server");
        goal_accepted = false;
    } else {
        RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::disarmOnCableGoalResponseCallback(): Goal accepted by server, waiting for result");
        goal_accepted = true;
    }
    std::lock_guard<std::mutex> lock(disarm_on_cable_mutex_);
    disarm_on_cable_response_received_ = true;
    disarm_on_cable_goal_accepted_ = goal_accepted;
    disarm_on_cable_active_ = goal_accepted;
}
References disarm_on_cable_active_, disarm_on_cable_goal_accepted_, disarm_on_cable_mutex_, and disarm_on_cable_response_received_.
Referenced by startDisarmOnCable().
disarmOnCableResultCallback()
void ContinuousMissionOrchestrator::disarmOnCableResultCallback (const GoalHandleDisarmOnCable::WrappedResult & result) private
Definition at line 390 of file continuous_mission_orchestrator_node.cpp.
{
    bool disarm_on_cable_active = false;
    bool disarm_on_cable_success = false;
    switch (result.code) {
        case rclcpp_action::ResultCode::SUCCEEDED:
            RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::disarmOnCableResultCallback(): DisarmOnCable succeeded");
            disarm_on_cable_active = false;
            disarm_on_cable_success = true;
            break;
        case rclcpp_action::ResultCode::ABORTED:
            RCLCPP_WARN(this->get_logger(), "ContinuousMissionOrchestrator::disarmOnCableResultCallback(): DisarmOnCable was aborted");
            disarm_on_cable_active = false;
            disarm_on_cable_success = false;
            break;
        case rclcpp_action::ResultCode::CANCELED:
            RCLCPP_WARN(this->get_logger(), "ContinuousMissionOrchestrator::disarmOnCableResultCallback(): DisarmOnCable was canceled");
            disarm_on_cable_active = false;
            disarm_on_cable_success = false;
            break;
        default:
            RCLCPP_ERROR(this->get_logger(), "ContinuousMissionOrchestrator::disarmOnCableResultCallback(): Unknown result code for DisarmOnCable");
            disarm_on_cable_active = false;
            disarm_on_cable_success = false;
            break;
    }
    std::lock_guard<std::mutex> lock(disarm_on_cable_mutex_);
    disarm_on_cable_active_ = disarm_on_cable_active;
    disarm_on_cable_success_ = disarm_on_cable_success;
}
References disarm_on_cable_active_, disarm_on_cable_mutex_, and disarm_on_cable_success_.
Referenced by startDisarmOnCable().
disarmOnCableSucceeded()
bool ContinuousMissionOrchestrator::disarmOnCableSucceeded () private
Definition at line 464 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(disarm_on_cable_mutex_);
    return disarm_on_cable_goal_accepted_ && disarm_on_cable_success_;
}
References disarm_on_cable_goal_accepted_, disarm_on_cable_mutex_, and disarm_on_cable_success_.
Referenced by stateMachineDisarmingOnCable().
disarmOnCableTerminated()
bool ContinuousMissionOrchestrator::disarmOnCableTerminated () private
Definition at line 456 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(disarm_on_cable_mutex_);
    return (!disarm_on_cable_active_) && disarm_on_cable_response_received_;
}
References disarm_on_cable_active_, disarm_on_cable_mutex_, and disarm_on_cable_response_received_.
Referenced by stateMachineDisarmingOnCable().
evaluateChargingStatus()
void ContinuousMissionOrchestrator::evaluateChargingStatus () private
Definition at line 1334 of file continuous_mission_orchestrator_node.cpp.
{
    bool start_charging_flag = false;
    bool stop_charging_flag = false;
    int charging_minimum_duration_s;
    int charging_maximum_duration_s;
    bool use_charger_gripper_info;
    bool simulation;
    float charging_duration_s;
    bool has_charged_minimum_seconds;
    bool has_charged_maximum_seconds;
    // Get state:
    state_t state = getState();
    switch (state) {
        case manual:
        case wait_for_target_line:
        case flying_under_cable:
            start_charging_flag = false;
            stop_charging_flag = false;
            clearInitiateChargingSrvCalled();
            clearInterruptChargingSrvCalled();
            clearProlongCharging();
            break;
        case inspecting:
        case landing_on_cable:
        case closing_gripper:
        case disarming_on_cable:
            start_charging_flag = batteryVoltageLow() || initiateChargingSrvCalled();
            stop_charging_flag = false;
            clearInterruptChargingSrvCalled();
            clearProlongCharging();
            break;
        case charging:
        case arming_on_cable:
        case opening_gripper:
        case taking_off_from_cable:
            stop_charging_flag = false;
            charging_minimum_duration_s;
            this->get_parameter("charging_minimum_duration_s", charging_minimum_duration_s);
            charging_maximum_duration_s;
            this->get_parameter("charging_maximum_duration_s", charging_maximum_duration_s);
            use_charger_gripper_info;
            this->get_parameter("use_charger_gripper_info", use_charger_gripper_info);
            simulation;
            this->get_parameter("simulation", simulation);
            use_charger_gripper_info &= !simulation;
            charging_duration_s = (this->get_clock()->now() - charging_start_time_).seconds();
            has_charged_minimum_seconds = (charging_minimum_duration_s < 0) || (charging_duration_s >= charging_minimum_duration_s);
            has_charged_maximum_seconds = (charging_maximum_duration_s > 0) && (charging_duration_s >= charging_maximum_duration_s);
            if (!prolongChargingUntilInterrupted()) {
                if (use_charger_gripper_info) {
                    stop_charging_flag |= batteryVoltageHigh() || chargingPowerLow() || !chargerStatusCharging();
                    stop_charging_flag &= has_charged_minimum_seconds;
                }
                stop_charging_flag |= has_charged_maximum_seconds;
            }
            stop_charging_flag |= interruptChargingSrvCalled();
            start_charging_flag = false;
            clearInitiateChargingSrvCalled();
            clearProlongCharging();
            break;
        default:
        case error:
            start_charging_flag = false;
            stop_charging_flag = false;
            clearInitiateChargingSrvCalled();
            clearInterruptChargingSrvCalled();
            clearProlongCharging();
            break;
    }
    if (start_charging_flag) {
        RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::evaluateChargingStatus(): Start charging flag set");
    }
    if (stop_charging_flag) {
        RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::evaluateChargingStatus(): Stop charging flag set");
    }
    setStartChargingFlag(start_charging_flag);
    setStopChargingFlag(stop_charging_flag);
}
References arming_on_cable, batteryVoltageHigh(), batteryVoltageLow(), chargerStatusCharging(), charging, charging_start_time_, chargingPowerLow(), clearInitiateChargingSrvCalled(), clearInterruptChargingSrvCalled(), clearProlongCharging(), closing_gripper, disarming_on_cable, error, flying_under_cable, getState(), initiateChargingSrvCalled(), inspecting, interruptChargingSrvCalled(), landing_on_cable, manual, opening_gripper, prolongChargingUntilInterrupted(), setStartChargingFlag(), setStopChargingFlag(), taking_off_from_cable, and wait_for_target_line.
Referenced by stateMachineCallback().
flyUnderCableFeedbackCallback()
void ContinuousMissionOrchestrator::flyUnderCableFeedbackCallback (GoalHandleFlyUnderCable::SharedPtr , const std::shared_ptr< const FlyUnderCable::Feedback > feedback) private
Definition at line 138 of file continuous_mission_orchestrator_node.cpp.
  { }
Referenced by startFlyUnderCable().
flyUnderCableGoalResponseCallback()
void ContinuousMissionOrchestrator::flyUnderCableGoalResponseCallback (const GoalHandleFlyUnderCable::SharedPtr & goal_handle) private
Definition at line 114 of file continuous_mission_orchestrator_node.cpp.
{
    bool goal_accepted = false;
    if (!goal_handle) {
        RCLCPP_ERROR(this->get_logger(), "ContinuousMissionOrchestrator::flyUnderCableGoalResponseCallback(): FlyUnderCable goal was rejected by server");
        goal_accepted = false;
    } else {
        RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::flyUnderCableGoalResponseCallback(): Goal accepted by server, waiting for result");
        goal_accepted = true;
    }
    std::lock_guard<std::mutex> lock(fly_under_cable_mutex_);
    fly_under_cable_response_received_ = true;
    fly_under_cable_goal_accepted_ = goal_accepted;
    fly_under_cable_active_ = goal_accepted;
}
References fly_under_cable_active_, fly_under_cable_goal_accepted_, fly_under_cable_mutex_, and fly_under_cable_response_received_.
Referenced by startFlyUnderCable().
flyUnderCableResultCallback()
void ContinuousMissionOrchestrator::flyUnderCableResultCallback (const GoalHandleFlyUnderCable::WrappedResult & result) private
Definition at line 143 of file continuous_mission_orchestrator_node.cpp.
{
    bool fly_under_cable_active = false;
    bool fly_under_cable_success = false;
    switch (result.code) {
        case rclcpp_action::ResultCode::SUCCEEDED:
            RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::flyUnderCableResultCallback(): FlyUnderCable succeeded");
            fly_under_cable_active = false;
            fly_under_cable_success = true;
            break;
        case rclcpp_action::ResultCode::ABORTED:
            RCLCPP_WARN(this->get_logger(), "ContinuousMissionOrchestrator::flyUnderCableResultCallback(): FlyUnderCable was aborted");
            fly_under_cable_active = false;
            fly_under_cable_success = false;
            break;
        case rclcpp_action::ResultCode::CANCELED:
            RCLCPP_WARN(this->get_logger(), "ContinuousMissionOrchestrator::flyUnderCableResultCallback(): FlyUnderCable was canceled");
            fly_under_cable_active = false;
            fly_under_cable_success = false;
            break;
        default:
            RCLCPP_ERROR(this->get_logger(), "ContinuousMissionOrchestrator::flyUnderCableResultCallback(): Unknown result code for FlyUnderCable");
            fly_under_cable_active = false;
            fly_under_cable_success = false;
            break;
    }
    std::lock_guard<std::mutex> lock(fly_under_cable_mutex_);
    fly_under_cable_active_ = fly_under_cable_active;
    fly_under_cable_success_ = fly_under_cable_success;
}
References fly_under_cable_active_, fly_under_cable_mutex_, and fly_under_cable_success_.
Referenced by startFlyUnderCable().
flyUnderCableSucceeded()
bool ContinuousMissionOrchestrator::flyUnderCableSucceeded () private
Definition at line 221 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(fly_under_cable_mutex_);
    return fly_under_cable_goal_accepted_ && fly_under_cable_success_;
}
References fly_under_cable_goal_accepted_, fly_under_cable_mutex_, and fly_under_cable_success_.
Referenced by stateMachineFlyingUnderCable().
flyUnderCableTerminated()
bool ContinuousMissionOrchestrator::flyUnderCableTerminated () private
Definition at line 213 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(fly_under_cable_mutex_);
    return (!fly_under_cable_active_) && fly_under_cable_response_received_;
}
References fly_under_cable_active_, fly_under_cable_mutex_, and fly_under_cable_response_received_.
Referenced by stateMachineFlyingUnderCable().
getBatteryVoltage()
float ContinuousMissionOrchestrator::getBatteryVoltage () private
Definition at line 876 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(battery_voltage_mutex_);
    return battery_voltage_;
}
References battery_voltage_, and battery_voltage_mutex_.
getChargerOperatingMode()
iii_drone_interfaces::msg::ChargerOperatingMode ContinuousMissionOrchestrator::getChargerOperatingMode () private
Definition at line 960 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(charger_operating_mode_mutex_);
    return charger_operating_mode_;
}
References charger_operating_mode_, and charger_operating_mode_mutex_.
getChargerStatus()
iii_drone_interfaces::msg::ChargerStatus ContinuousMissionOrchestrator::getChargerStatus () private
Definition at line 1001 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(charger_status_mutex_);
    return charger_status_;
}
References charger_status_, and charger_status_mutex_.
getChargingPower()
float ContinuousMissionOrchestrator::getChargingPower () private
Definition at line 936 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(charging_power_mutex_);
    return charging_power_;
}
References charging_power_, and charging_power_mutex_.
getChargingStartTime()
rclcpp::Time ContinuousMissionOrchestrator::getChargingStartTime () private
Definition at line 1126 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(charging_start_time_mutex_);
    return charging_start_time_;
}
References charging_start_time_, and charging_start_time_mutex_.
getControlState()
iii_drone_interfaces::msg::ControlState ContinuousMissionOrchestrator::getControlState () private
Definition at line 1497 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(control_state_mutex_);
    return control_state_;
}
References control_state_, and control_state_mutex_.
Referenced by isInControllableState(), stateMachineArmingOnCable(), stateMachineCharging(), stateMachineDisarmingOnCable(), stateMachineFlyingUnderCable(), stateMachineInspecting(), stateMachineLandingOnCable(), stateMachineManual(), and stateMachineTakingOffFromCable().
getGripperStatus()
iii_drone_interfaces::msg::GripperStatus ContinuousMissionOrchestrator::getGripperStatus () private
Definition at line 1070 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(gripper_status_mutex_);
    return gripper_status_;
}
References gripper_status_, and gripper_status_mutex_.
Referenced by gripperIsClosed(), gripperIsOpen(), and stateMachineLandingOnCable().
getLastGripperCommandClose()
bool ContinuousMissionOrchestrator::getLastGripperCommandClose () private
Definition at line 789 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(gripper_command_mutex_);
    return last_gripper_command_close_;
}
References gripper_command_mutex_, and last_gripper_command_close_.
Referenced by gripperIsClosed(), and gripperIsOpen().
getProlongChargingForSeconds()
float ContinuousMissionOrchestrator::getProlongChargingForSeconds () private
Definition at line 1308 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(prolong_charging_mutex_);
    return prolong_charging_for_seconds_;
}
References prolong_charging_for_seconds_, and prolong_charging_mutex_.
getProlongChargingUntilNewBatteryVoltage()
float ContinuousMissionOrchestrator::getProlongChargingUntilNewBatteryVoltage () private
Definition at line 1316 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(prolong_charging_mutex_);
    return prolong_charging_until_new_battery_voltage_;
}
References prolong_charging_mutex_, and prolong_charging_until_new_battery_voltage_.
getStartChargingFlag()
bool ContinuousMissionOrchestrator::getStartChargingFlag () private
Definition at line 1458 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(start_charging_flag_mutex_);
    return start_charging_flag_;
}
References start_charging_flag_, and start_charging_flag_mutex_.
Referenced by stateMachineInspecting(), and stateMachineTakingOffFromCable().
getState()
ContinuousMissionOrchestrator::state_t ContinuousMissionOrchestrator::getState () private
Definition at line 1543 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(state_mutex_);
    return state_;
}
References state_, and state_mutex_.
Referenced by evaluateChargingStatus(), initiateChargingSrvCallback(), interruptChargingSrvCallback(), prolongChargingSrvCallback(), publishCallback(), and stateMachineCallback().
getStopChargingFlag()
bool ContinuousMissionOrchestrator::getStopChargingFlag () private
Definition at line 1474 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(stop_charging_flag_mutex_);
    return stop_charging_flag_;
}
References stop_charging_flag_, and stop_charging_flag_mutex_.
Referenced by stateMachineCharging().
getTargetCableId()
int8_t ContinuousMissionOrchestrator::getTargetCableId () private
Definition at line 814 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(target_cable_id_mutex_);
    return target_cable_id_;
}
References target_cable_id_, and target_cable_id_mutex_.
Referenced by startCableLanding(), startFlyUnderCable(), stateMachineInspecting(), and stateMachineWaitForTargetLine().
gripperCommandResponseCallback()
void ContinuousMissionOrchestrator::gripperCommandResponseCallback (rclcpp::Client< iii_drone_interfaces::srv::GripperCommand >::SharedFuture future) private
Definition at line 727 of file continuous_mission_orchestrator_node.cpp.
{
    bool gripper_command_success = false;
    auto response = future.get();
    if (response->gripper_command_response == iii_drone_interfaces::srv::GripperCommand::Response::GRIPPER_COMMAND_RESPONSE_SUCCESS) {
        RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::gripperCommandResponseCallback(): GripperCommand service succeeded");
        gripper_command_success = true;
    } else {
        RCLCPP_WARN(this->get_logger(), "ContinuousMissionOrchestrator::gripperCommandResponseCallback(): GripperCommand service failed");
        gripper_command_success = false;
    }
    std::lock_guard<std::mutex> lock(gripper_command_mutex_);
    gripper_command_response_received_ = true;
    gripper_command_success_ = gripper_command_success;
    gripper_command_active_ = false;
}
References gripper_command_active_, gripper_command_mutex_, gripper_command_response_received_, and gripper_command_success_.
Referenced by sendGripperCommand().
gripperCommandSucceeded()
bool ContinuousMissionOrchestrator::gripperCommandSucceeded () private
Definition at line 781 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(gripper_command_mutex_);
    return gripper_command_success_;
}
References gripper_command_mutex_, and gripper_command_success_.
Referenced by gripperIsClosed(), gripperIsOpen(), stateMachineClosingGripper(), and stateMachineOpeningGripper().
gripperCommandTerminated()
bool ContinuousMissionOrchestrator::gripperCommandTerminated () private
Definition at line 773 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(gripper_command_mutex_);
    return (!gripper_command_active_) && gripper_command_response_received_;
}
References gripper_command_active_, gripper_command_mutex_, and gripper_command_response_received_.
Referenced by stateMachineClosingGripper(), and stateMachineOpeningGripper().
gripperIsClosed()
bool ContinuousMissionOrchestrator::gripperIsClosed () private
Definition at line 1078 of file continuous_mission_orchestrator_node.cpp.
{
    bool use_charger_gripper_info;
    this->get_parameter("use_charger_gripper_info", use_charger_gripper_info);
    bool simulation;
    this->get_parameter("simulation", simulation);
    use_charger_gripper_info &= !simulation;
    if (use_charger_gripper_info) {
        iii_drone_interfaces::msg::GripperStatus gripper_status = getGripperStatus();
        return gripper_status.gripper_status == iii_drone_interfaces::msg::GripperStatus::GRIPPER_STATUS_CLOSED;
    } else {
        return getLastGripperCommandClose() && gripperCommandSucceeded();
    }
}
References getGripperStatus(), getLastGripperCommandClose(), and gripperCommandSucceeded().
gripperIsOpen()
bool ContinuousMissionOrchestrator::gripperIsOpen () private
Definition at line 1101 of file continuous_mission_orchestrator_node.cpp.
{
    bool use_charger_gripper_info;
    this->get_parameter("use_charger_gripper_info", use_charger_gripper_info);
    bool simulation;
    this->get_parameter("simulation", simulation);
    use_charger_gripper_info &= !simulation;
    if (use_charger_gripper_info) {
        iii_drone_interfaces::msg::GripperStatus gripper_status = getGripperStatus();
        return gripper_status.gripper_status == iii_drone_interfaces::msg::GripperStatus::GRIPPER_STATUS_OPEN;
    } else {
        return !getLastGripperCommandClose() && gripperCommandSucceeded();
    }
}
References getGripperStatus(), getLastGripperCommandClose(), and gripperCommandSucceeded().
Referenced by stateMachineOpeningGripper().
gripperStatusCallback()
void ContinuousMissionOrchestrator::gripperStatusCallback (iii_drone_interfaces::msg::GripperStatus::SharedPtr msg) private
Definition at line 1062 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(gripper_status_mutex_);
    gripper_status_ = *msg;
}
References gripper_status_, and gripper_status_mutex_.
Referenced by ContinuousMissionOrchestrator().
initiateChargingSrvCallback()
void ContinuousMissionOrchestrator::initiateChargingSrvCallback (const std::shared_ptr< rmw_request_id_t > request_header, const std::shared_ptr< iii_drone_interfaces::srv::InitiateCharging::Request > request, const std::shared_ptr< iii_drone_interfaces::srv::InitiateCharging::Response > response) private
Definition at line 1134 of file continuous_mission_orchestrator_node.cpp.
  {
    (void)request_header;
    state_t state = getState();
    if (state != inspecting) {
        RCLCPP_WARN(this->get_logger(), "ContinuousMissionOrchestrator::initiateChargingSrvCallback(): Received request to initiate charging, but can only initiate charging when in state inspecting.");
        response->success = false;
        return;
    }
    RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::initiateChargingSrvCallback(): Received request to initiate charging");
    std::lock_guard<std::mutex> lock(initiate_charging_srv_called_mutex_);
    initiate_charging_srv_called_ = true;
    response->success = true;
}
References getState(), initiate_charging_srv_called_, initiate_charging_srv_called_mutex_, and inspecting.
Referenced by ContinuousMissionOrchestrator().
initiateChargingSrvCalled()
bool ContinuousMissionOrchestrator::initiateChargingSrvCalled () private
Definition at line 1164 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(initiate_charging_srv_called_mutex_);
    return initiate_charging_srv_called_;
}
References initiate_charging_srv_called_, and initiate_charging_srv_called_mutex_.
Referenced by evaluateChargingStatus().
interruptChargingSrvCallback()
void ContinuousMissionOrchestrator::interruptChargingSrvCallback (const std::shared_ptr< rmw_request_id_t > request_header, const std::shared_ptr< iii_drone_interfaces::srv::InterruptCharging::Request > request, const std::shared_ptr< iii_drone_interfaces::srv::InterruptCharging::Response > response) private
Definition at line 1180 of file continuous_mission_orchestrator_node.cpp.
  {
    (void)request_header;
    state_t state = getState();
    if (state != charging) {
        RCLCPP_WARN(this->get_logger(), "ContinuousMissionOrchestrator::interruptChargingSrvCallback(): Received request to interrupt charging, but can only interrupt charging when in state charging.");
        response->success = false;
        return;
    }
    RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::interruptChargingSrvCallback(): Received request to interrupt charging");
    std::lock_guard<std::mutex> lock(interrupt_charging_srv_called_mutex_);
    interrupt_charging_srv_called_ = true;
    response->success = true;
}
References charging, getState(), interrupt_charging_srv_called_, and interrupt_charging_srv_called_mutex_.
Referenced by ContinuousMissionOrchestrator().
interruptChargingSrvCalled()
bool ContinuousMissionOrchestrator::interruptChargingSrvCalled () private
Definition at line 1210 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(interrupt_charging_srv_called_mutex_);
    return interrupt_charging_srv_called_;
}
References interrupt_charging_srv_called_, and interrupt_charging_srv_called_mutex_.
Referenced by evaluateChargingStatus().
isInControllableState() [1/2]
bool ContinuousMissionOrchestrator::isInControllableState () private
Definition at line 1513 of file continuous_mission_orchestrator_node.cpp.
{
    iii_drone_interfaces::msg::ControlState control_state = getControlState();
    return isInControllableState(control_state);
}
References getControlState(), and isInControllableState().
Referenced by isInControllableState(), stateMachineArmingOnCable(), stateMachineClosingGripper(), stateMachineDisarmingOnCable(), stateMachineFlyingUnderCable(), stateMachineLandingOnCable(), stateMachineOpeningGripper(), stateMachineTakingOffFromCable(), and stateMachineWaitForTargetLine().
isInControllableState() [2/2]
bool ContinuousMissionOrchestrator::isInControllableState (iii_drone_interfaces::msg::ControlState control_state) private
Definition at line 1521 of file continuous_mission_orchestrator_node.cpp.
{
    switch(control_state.state) {
        case iii_drone_interfaces::msg::ControlState::CONTROL_STATE_INIT:
        case iii_drone_interfaces::msg::ControlState::CONTROL_STATE_ON_GROUND_NON_OFFBOARD:
        case iii_drone_interfaces::msg::ControlState::CONTROL_STATE_IN_FLIGHT_NON_OFFBOARD:
        case iii_drone_interfaces::msg::ControlState::CONTROL_STATE_ARMING:
        case iii_drone_interfaces::msg::ControlState::CONTROL_STATE_SETTING_OFFBOARD:
        case iii_drone_interfaces::msg::ControlState::CONTROL_STATE_TAKING_OFF:
        case iii_drone_interfaces::msg::ControlState::CONTROL_STATE_LANDING:
            return false;
        default:
            return true;
    }
}
prolongChargingSrvCallback()
void ContinuousMissionOrchestrator::prolongChargingSrvCallback (const std::shared_ptr< rmw_request_id_t > request_header, const std::shared_ptr< iii_drone_interfaces::srv::ProlongCharging::Request > request, const std::shared_ptr< iii_drone_interfaces::srv::ProlongCharging::Response > response) private
Definition at line 1226 of file continuous_mission_orchestrator_node.cpp.
  {
    (void)request_header;
    state_t state = getState();
    if (state != charging) {
        RCLCPP_WARN(this->get_logger(), "ContinuousMissionOrchestrator::prolongChargingSrvCallback(): Received request to prolong charging, but vehicle is not charging");
        response->success = false;
        return;
    }
    RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::prolongChargingSrvCallback(): Received request to prolong charging");
    std::lock_guard<std::mutex> lock(prolong_charging_mutex_);
    if (request->prolong_mode == iii_drone_interfaces::srv::ProlongCharging::Request::PROLONG_MODE_UNTIL_INTERRUPTED) {
        prolong_charging_until_interrupted_ = true;
        prolong_charging_for_seconds_ = -1;
        prolong_charging_until_new_battery_voltage_ = -1;
    } else if (request->prolong_mode == iii_drone_interfaces::srv::ProlongCharging::Request::PROLONG_MODE_FOR_TIME) {
        RCLCPP_FATAL(this->get_logger(), "ContinuousMissionOrchestrator::prolongChargingSrvCallback(): PROLONG_MODE_FOR_TIME not implemented yet");
        prolong_charging_until_interrupted_ = false;
        prolong_charging_for_seconds_ = request->prolong_time_s;
        prolong_charging_until_new_battery_voltage_ = -1;
    } else if (request->prolong_mode == iii_drone_interfaces::srv::ProlongCharging::Request::PROLONG_MODE_UNTIL_NEW_BATTERY_VOLTAGE) {
        RCLCPP_FATAL(this->get_logger(), "ContinuousMissionOrchestrator::prolongChargingSrvCallback(): PROLONG_MODE_UNTIL_NEW_BATTERY_VOLTAGE not implemented yet");
        prolong_charging_until_interrupted_ = false;
        prolong_charging_for_seconds_ = -1;
        prolong_charging_until_new_battery_voltage_ = request->new_battery_voltage;
    } else if (request->prolong_mode == iii_drone_interfaces::srv::ProlongCharging::Request::PROLONG_MODE_FOR_TIME_OR_NEW_BATTERY_VOLTAGE) {
        RCLCPP_FATAL(this->get_logger(), "ContinuousMissionOrchestrator::prolongChargingSrvCallback(): PROLONG_MODE_FOR_TIME_OR_NEW_BATTERY_VOLTAGE not implemented yet");
        prolong_charging_until_interrupted_ = false;
        prolong_charging_for_seconds_ = request->prolong_time_s;
        prolong_charging_until_new_battery_voltage_ = request->new_battery_voltage;
    } else if (request->prolong_mode == iii_drone_interfaces::srv::ProlongCharging::Request::PROLONG_MODE_CLEAR) {
        prolong_charging_until_interrupted_ = false;
        prolong_charging_for_seconds_ = -1;
        prolong_charging_until_new_battery_voltage_ = -1;
    } else {
        RCLCPP_ERROR(this->get_logger(), "ContinuousMissionOrchestrator::prolongChargingSrvCallback(): Invalid prolong mode");
        response->success = false;
        return;
    }
    response->success = true;
}
References charging, getState(), prolong_charging_for_seconds_, prolong_charging_mutex_, prolong_charging_until_interrupted_, and prolong_charging_until_new_battery_voltage_.
prolongChargingUntilInterrupted()
bool ContinuousMissionOrchestrator::prolongChargingUntilInterrupted () private
Definition at line 1300 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(prolong_charging_mutex_);
    return prolong_charging_until_interrupted_;
}
References prolong_charging_mutex_, and prolong_charging_until_interrupted_.
Referenced by evaluateChargingStatus().
publishCallback()
void ContinuousMissionOrchestrator::publishCallback () private
Definition at line 2394 of file continuous_mission_orchestrator_node.cpp.
{
    // Publish state:
    std_msgs::msg::String msg;
    switch (getState())
    {
    case manual:
        msg.data = "manual";
        break;
    case wait_for_target_line:
        msg.data = "wait_for_target_line";
        break;
    case flying_under_cable:
        msg.data = "flying_under_cable";
        break;
    case inspecting:
        msg.data = "inspecting";
        break;
    case landing_on_cable:
        msg.data = "landing_on_cable";
        break;
    case closing_gripper:
        msg.data = "closing_gripper";
        break;
    case disarming_on_cable:
        msg.data = "disarming_on_cable";
        break;
    case charging:
        msg.data = "charging";
        break;
    case arming_on_cable:
        msg.data = "arming_on_cable";
        break;
    case opening_gripper:
        msg.data = "opening_gripper";
        break;
    case taking_off_from_cable:
        msg.data = "taking_off_from_cable";
        break;
    default:
    case error:
        msg.data = "error";
        break;
    }
    state_pub_->publish(msg);
}
References arming_on_cable, charging, closing_gripper, disarming_on_cable, error, flying_under_cable, getState(), inspecting, landing_on_cable, manual, opening_gripper, state_pub_, taking_off_from_cable, and wait_for_target_line.
Referenced by ContinuousMissionOrchestrator().
sendGripperCommand()
void ContinuousMissionOrchestrator::sendGripperCommand (bool close) private
Definition at line 754 of file continuous_mission_orchestrator_node.cpp.
{
    RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::sendGripperCommand(): Sending GripperCommand service request to %s gripper", close ? "close" : "open");
    {
        std::lock_guard<std::mutex> lock(gripper_command_mutex_);
        gripper_command_response_received_ = false;
        gripper_command_active_ = true;
        gripper_command_success_ = false;
    }
    auto request = std::make_shared<iii_drone_interfaces::srv::GripperCommand::Request>();
    request->gripper_command = close ? iii_drone_interfaces::srv::GripperCommand::Request::GRIPPER_COMMAND_CLOSE : iii_drone_interfaces::srv::GripperCommand::Request::GRIPPER_COMMAND_OPEN;
    auto future = gripper_command_client_->async_send_request(request, std::bind(&ContinuousMissionOrchestrator::gripperCommandResponseCallback, this, std::placeholders::_1));
}
References gripper_command_active_, gripper_command_client_, gripper_command_mutex_, gripper_command_response_received_, gripper_command_success_, and gripperCommandResponseCallback().
Referenced by stateMachineArmingOnCable(), stateMachineClosingGripper(), and stateMachineInspecting().
setBatteryVoltage()
void iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::setBatteryVoltage (float voltage) private
setBatteryVoltageHigh()
void ContinuousMissionOrchestrator::setBatteryVoltageHigh (bool high) private
Definition at line 908 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(battery_voltage_mutex_);
    battery_voltage_high_ = battery_voltage_high;
}
References battery_voltage_high_, and battery_voltage_mutex_.
setBatteryVoltageLow()
void ContinuousMissionOrchestrator::setBatteryVoltageLow (bool low) private
Definition at line 892 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(battery_voltage_mutex_);
    battery_voltage_low_ = battery_voltage_low;
}
References battery_voltage_low_, and battery_voltage_mutex_.
setChargerStatusCharging()
void ContinuousMissionOrchestrator::setChargerStatusCharging (bool charging) private
Definition at line 1036 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(charger_status_mutex_);
    charger_status_charging_ = charger_status_charging;
}
References charger_status_charging_, and charger_status_mutex_.
setChargerStatusDisabled()
void ContinuousMissionOrchestrator::setChargerStatusDisabled (bool disabled) private
Definition at line 1019 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(charger_status_mutex_);
    charger_status_disabled_ = charger_status_disabled;
}
References charger_status_disabled_, and charger_status_mutex_.
setChargerStatusFullyCharged()
void ContinuousMissionOrchestrator::setChargerStatusFullyCharged (bool fully_charged) private
Definition at line 1053 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(charger_status_mutex_);
    charger_status_fully_charged_ = charger_status_fully_charged;
}
References charger_status_fully_charged_, and charger_status_mutex_.
setControlState()
void ContinuousMissionOrchestrator::setControlState (iii_drone_interfaces::msg::ControlState control_state) private
Definition at line 1505 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(control_state_mutex_);
    control_state_ = control_state;
}
References control_state_, and control_state_mutex_.
Referenced by controlStateCallback().
setStartChargingFlag()
void ContinuousMissionOrchestrator::setStartChargingFlag (bool flag) private
Definition at line 1466 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(start_charging_flag_mutex_);
    start_charging_flag_ = start_charging_flag;
}
References start_charging_flag_, and start_charging_flag_mutex_.
Referenced by evaluateChargingStatus().
setState()
void ContinuousMissionOrchestrator::setState (state_t state) private
Definition at line 1551 of file continuous_mission_orchestrator_node.cpp.
{
    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        state_ = state;
    }
    switch(state) {
        case flying_under_cable:
            setTargetCableIdChanged(false);
            break;
        case charging:
            {
                std::lock_guard<std::mutex> lock(charging_start_time_mutex_);
                charging_start_time_ = this->get_clock()->now();
            }
            break;
        default:
            break;
    }
}
References charging, charging_start_time_, charging_start_time_mutex_, flying_under_cable, setTargetCableIdChanged(), state_, and state_mutex_.
Referenced by stateMachineArmingOnCable(), stateMachineCharging(), stateMachineClosingGripper(), stateMachineDisarmingOnCable(), stateMachineFlyingUnderCable(), stateMachineInspecting(), stateMachineLandingOnCable(), stateMachineManual(), stateMachineOpeningGripper(), stateMachineTakingOffFromCable(), and stateMachineWaitForTargetLine().
setStopChargingFlag()
void ContinuousMissionOrchestrator::setStopChargingFlag (bool flag) private
Definition at line 1482 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(stop_charging_flag_mutex_);
    stop_charging_flag_ = stop_charging_flag;
}
References stop_charging_flag_, and stop_charging_flag_mutex_.
Referenced by evaluateChargingStatus().
setTargetCableId()
void ContinuousMissionOrchestrator::setTargetCableId (int8_t cable_id) private
Definition at line 822 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(target_cable_id_mutex_);
    target_cable_id_ = target_cable_id;
}
References target_cable_id_, and target_cable_id_mutex_.
Referenced by setTargetCableIdSrvCallback(), stateMachineClosingGripper(), stateMachineFlyingUnderCable(), stateMachineInspecting(), stateMachineLandingOnCable(), and stateMachineWaitForTargetLine().
setTargetCableIdChanged()
void ContinuousMissionOrchestrator::setTargetCableIdChanged (bool changed) private
Definition at line 838 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(target_cable_id_mutex_);
    target_cable_id_changed_ = changed;
}
References target_cable_id_changed_, and target_cable_id_mutex_.
Referenced by setState(), and setTargetCableIdSrvCallback().
setTargetCableIdSrvCallback()
void ContinuousMissionOrchestrator::setTargetCableIdSrvCallback (const std::shared_ptr< rmw_request_id_t > request_header, const std::shared_ptr< iii_drone_interfaces::srv::SetTargetCableId::Request > request, const std::shared_ptr< iii_drone_interfaces::srv::SetTargetCableId::Response > response) private
Definition at line 799 of file continuous_mission_orchestrator_node.cpp.
  {
    (void)request_header;
    RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::setTargetCableIdSrvCallback(): Received SetTargetCableId service request with target_cable_id = %d", request->target_cable_id);
    setTargetCableId(request->target_cable_id);
    setTargetCableIdChanged(true);
}
References setTargetCableId(), and setTargetCableIdChanged().
Referenced by ContinuousMissionOrchestrator().
startActionTimeoutCounter()
void ContinuousMissionOrchestrator::startActionTimeoutCounter () private
Definition at line 2379 of file continuous_mission_orchestrator_node.cpp.
{
    action_start_time_ = this->now();
}
References action_start_time_.
Referenced by stateMachineArmingOnCable(), stateMachineDisarmingOnCable(), stateMachineFlyingUnderCable(), stateMachineLandingOnCable(), stateMachineOpeningGripper(), and stateMachineTakingOffFromCable().
startArmOnCable()
void ContinuousMissionOrchestrator::startArmOnCable () private
Definition at line 546 of file continuous_mission_orchestrator_node.cpp.
{
    RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::startArmOnCable(): Starting ArmOnCable");
    {
        std::lock_guard<std::mutex> lock(arm_on_cable_mutex_);
        arm_on_cable_response_received_ = false;
        arm_on_cable_active_ = false;
        arm_on_cable_success_ = false;
        arm_on_cable_goal_accepted_ = false;
    }
    auto goal_msg = ArmOnCable::Goal();
    auto goal_options = rclcpp_action::Client<ArmOnCable>::SendGoalOptions();
    goal_options.goal_response_callback = std::bind(
        &ContinuousMissionOrchestrator::armOnCableGoalResponseCallback, this, std::placeholders::_1
    );
    goal_options.feedback_callback = std::bind(
        &ContinuousMissionOrchestrator::armOnCableFeedbackCallback, this, std::placeholders::_1, std::placeholders::_2
    );
    goal_options.result_callback = std::bind(
        &ContinuousMissionOrchestrator::armOnCableResultCallback, this, std::placeholders::_1
    );
    auto goal_handle_future = arm_on_cable_client_->async_send_goal(goal_msg, goal_options);
}
References arm_on_cable_active_, arm_on_cable_client_, arm_on_cable_goal_accepted_, arm_on_cable_mutex_, arm_on_cable_response_received_, arm_on_cable_success_, armOnCableFeedbackCallback(), armOnCableGoalResponseCallback(), and armOnCableResultCallback().
Referenced by stateMachineCharging().
startCableLanding()
void ContinuousMissionOrchestrator::startCableLanding () private
Definition at line 303 of file continuous_mission_orchestrator_node.cpp.
{
    RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::startCableLanding(): Starting CableLanding");
    {
        std::lock_guard<std::mutex> lock(cable_landing_mutex_);
        cable_landing_response_received_ = false;
        cable_landing_active_ = false;
        cable_landing_success_ = false;
        cable_landing_goal_accepted_ = false;
    }
    auto goal_msg = CableLanding::Goal();
    goal_msg.target_cable_id = getTargetCableId();
    auto goal_options = rclcpp_action::Client<CableLanding>::SendGoalOptions();
    goal_options.goal_response_callback = std::bind(
        &ContinuousMissionOrchestrator::cableLandingGoalResponseCallback, this, std::placeholders::_1
    );
    goal_options.feedback_callback = std::bind(
        &ContinuousMissionOrchestrator::cableLandingFeedbackCallback, this, std::placeholders::_1, std::placeholders::_2
    );
    goal_options.result_callback = std::bind(
        &ContinuousMissionOrchestrator::cableLandingResultCallback, this, std::placeholders::_1
    );
    auto goal_handle_future = cable_landing_client_->async_send_goal(goal_msg, goal_options);
}
References cable_landing_active_, cable_landing_client_, cable_landing_goal_accepted_, cable_landing_mutex_, cable_landing_response_received_, cable_landing_success_, cableLandingFeedbackCallback(), cableLandingGoalResponseCallback(), cableLandingResultCallback(), and getTargetCableId().
Referenced by stateMachineClosingGripper(), stateMachineLandingOnCable(), and stateMachineTakingOffFromCable().
startCableTakeoff()
void ContinuousMissionOrchestrator::startCableTakeoff () private
Definition at line 667 of file continuous_mission_orchestrator_node.cpp.
{
    RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::startCableTakeoff(): Starting CableTakeoff");
    {
        std::lock_guard<std::mutex> lock(cable_takeoff_mutex_);
        cable_takeoff_response_received_ = false;
        cable_takeoff_active_ = false;
        cable_takeoff_success_ = false;
        cable_takeoff_goal_accepted_ = false;
    }
    auto goal_msg = CableTakeoff::Goal();
    float target_cable_distance;
    this->get_parameter("under_cable_target_distance", target_cable_distance);
    goal_msg.target_cable_distance = target_cable_distance;
    auto goal_options = rclcpp_action::Client<CableTakeoff>::SendGoalOptions();
    goal_options.goal_response_callback = std::bind(
        &ContinuousMissionOrchestrator::cableTakeoffGoalResponseCallback, this, std::placeholders::_1
    );
    goal_options.feedback_callback = std::bind(
        &ContinuousMissionOrchestrator::cableTakeoffFeedbackCallback, this, std::placeholders::_1, std::placeholders::_2
    );
    goal_options.result_callback = std::bind(
        &ContinuousMissionOrchestrator::cableTakeoffResultCallback, this, std::placeholders::_1
    );
    auto goal_handle_future = cable_takeoff_client_->async_send_goal(goal_msg, goal_options);
}
References cable_takeoff_active_, cable_takeoff_client_, cable_takeoff_goal_accepted_, cable_takeoff_mutex_, cable_takeoff_response_received_, cable_takeoff_success_, cableTakeoffFeedbackCallback(), cableTakeoffGoalResponseCallback(), and cableTakeoffResultCallback().
Referenced by stateMachineOpeningGripper().
startDisarmOnCable()
void ContinuousMissionOrchestrator::startDisarmOnCable () private
Definition at line 425 of file continuous_mission_orchestrator_node.cpp.
{
    RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::startDisarmOnCable(): Starting DisarmOnCable");
    {
        std::lock_guard<std::mutex> lock(disarm_on_cable_mutex_);
        disarm_on_cable_response_received_ = false;
        disarm_on_cable_active_ = false;
        disarm_on_cable_success_ = false;
        disarm_on_cable_goal_accepted_ = false;
    }
    auto goal_msg = DisarmOnCable::Goal();
    auto goal_options = rclcpp_action::Client<DisarmOnCable>::SendGoalOptions();
    goal_options.goal_response_callback = std::bind(
        &ContinuousMissionOrchestrator::disarmOnCableGoalResponseCallback, this, std::placeholders::_1
    );
    goal_options.feedback_callback = std::bind(
        &ContinuousMissionOrchestrator::disarmOnCableFeedbackCallback, this, std::placeholders::_1, std::placeholders::_2
    );
    goal_options.result_callback = std::bind(
        &ContinuousMissionOrchestrator::disarmOnCableResultCallback, this, std::placeholders::_1
    );
    auto goal_handle_future = disarm_on_cable_client_->async_send_goal(goal_msg, goal_options);
}
References disarm_on_cable_active_, disarm_on_cable_client_, disarm_on_cable_goal_accepted_, disarm_on_cable_mutex_, disarm_on_cable_response_received_, disarm_on_cable_success_, disarmOnCableFeedbackCallback(), disarmOnCableGoalResponseCallback(), and disarmOnCableResultCallback().
Referenced by stateMachineLandingOnCable().
startFlyUnderCable()
void ContinuousMissionOrchestrator::startFlyUnderCable () private
Definition at line 178 of file continuous_mission_orchestrator_node.cpp.
{
    RCLCPP_INFO(this->get_logger(), "ContinuousMissionOrchestrator::startFlyUnderCable(): Starting FlyUnderCable");
    {
        std::lock_guard<std::mutex> lock(fly_under_cable_mutex_);
        fly_under_cable_response_received_ = false;
        fly_under_cable_active_ = false;
        fly_under_cable_success_ = false;
        fly_under_cable_goal_accepted_ = false;
    }
    auto goal_msg = FlyUnderCable::Goal();
    goal_msg.target_cable_id = getTargetCableId();
    float target_cable_distance;
    this->get_parameter("under_cable_target_distance", target_cable_distance);
    goal_msg.target_cable_distance = target_cable_distance;
    auto goal_options = rclcpp_action::Client<FlyUnderCable>::SendGoalOptions();
    goal_options.goal_response_callback = std::bind(
        &ContinuousMissionOrchestrator::flyUnderCableGoalResponseCallback, this, std::placeholders::_1
    );
    goal_options.feedback_callback = std::bind(
        &ContinuousMissionOrchestrator::flyUnderCableFeedbackCallback, this, std::placeholders::_1, std::placeholders::_2
    );
    goal_options.result_callback = std::bind(
        &ContinuousMissionOrchestrator::flyUnderCableResultCallback, this, std::placeholders::_1
    );
    auto goal_handle_future = fly_under_cable_client_->async_send_goal(goal_msg, goal_options);
}
References fly_under_cable_active_, fly_under_cable_client_, fly_under_cable_goal_accepted_, fly_under_cable_mutex_, fly_under_cable_response_received_, fly_under_cable_success_, flyUnderCableFeedbackCallback(), flyUnderCableGoalResponseCallback(), flyUnderCableResultCallback(), and getTargetCableId().
Referenced by stateMachineInspecting(), and stateMachineWaitForTargetLine().
stateMachineArmingOnCable()
void ContinuousMissionOrchestrator::stateMachineArmingOnCable () private
Definition at line 2177 of file continuous_mission_orchestrator_node.cpp.
{
    static bool action_timer_started = false;
    iii_drone_interfaces::msg::ControlState control_state = getControlState();
    if (!isInControllableState(control_state)) {
        RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineArmingOnCable(): Vehicle is not controllable, entering error state");
        setState(error);
        return;
    }
    if (!armOnCableTerminated()) {
        return;
    }
    if (armOnCableSucceeded() && control_state.state == iii_drone_interfaces::msg::ControlState::CONTROL_STATE_ON_CABLE_ARMED) {
        RCLCPP_INFO(get_logger(), "ContinuousMissionOrchestrator::stateMachineArmingOnCable(): Arm on cable succeeded and vehicle is armed on cable, entering opening_gripper state");
        action_timer_started = false;
        sendGripperCommand(false);
        setState(opening_gripper);
    } else if (armOnCableSucceeded()) {
        if (!action_timer_started) {
            RCLCPP_WARN(get_logger(), "ContinuousMissionOrchestrator::stateMachineArmingOnCable(): Arm on cable succeeded but vehicle is not armed on cable, starting action timer");
            action_timer_started = true;
            startActionTimeoutCounter();
        } else if (actionTimeout()) {
            RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineArmingOnCable(): Arm on cable succeeded but vehicle is not armed on cable and action timer expired, entering error state");
            setState(error);
        }
    } else if (!armOnCableSucceeded()) {
        RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineArmingOnCable(): Arm on cable failed, entering error state");
        setState(error);
    }
}
References actionTimeout(), armOnCableSucceeded(), armOnCableTerminated(), error, getControlState(), isInControllableState(), opening_gripper, sendGripperCommand(), setState(), and startActionTimeoutCounter().
Referenced by stateMachineCallback().
stateMachineCallback()
void ContinuousMissionOrchestrator::stateMachineCallback () private
Definition at line 1583 of file continuous_mission_orchestrator_node.cpp.
{
    evaluateChargingStatus();
    state_t state = getState();
    switch(state) {
        default:
        case manual:
            stateMachineManual();
            break;
        case wait_for_target_line:
            stateMachineWaitForTargetLine();
            break;
        case flying_under_cable:
            stateMachineFlyingUnderCable();
            break;
        case inspecting:
            stateMachineInspecting();
            break;
        case closing_gripper:
            stateMachineClosingGripper();
            break;
        case landing_on_cable:
            stateMachineLandingOnCable();
            break;
        case disarming_on_cable:
            stateMachineDisarmingOnCable();
            break;
        case charging:
            stateMachineCharging();
            break;
        case arming_on_cable:
            stateMachineArmingOnCable();
            break;
        case opening_gripper:
            stateMachineOpeningGripper();
            break;
        case taking_off_from_cable:
            stateMachineTakingOffFromCable();
            break;
        case error:
            stateMachineError();
            break;
    }
}
References arming_on_cable, charging, closing_gripper, disarming_on_cable, error, evaluateChargingStatus(), flying_under_cable, getState(), inspecting, landing_on_cable, manual, opening_gripper, stateMachineArmingOnCable(), stateMachineCharging(), stateMachineClosingGripper(), stateMachineDisarmingOnCable(), stateMachineError(), stateMachineFlyingUnderCable(), stateMachineInspecting(), stateMachineLandingOnCable(), stateMachineManual(), stateMachineOpeningGripper(), stateMachineTakingOffFromCable(), stateMachineWaitForTargetLine(), taking_off_from_cable, and wait_for_target_line.
Referenced by ContinuousMissionOrchestrator().
stateMachineCharging()
void ContinuousMissionOrchestrator::stateMachineCharging () private
Definition at line 2149 of file continuous_mission_orchestrator_node.cpp.
{
    iii_drone_interfaces::msg::ControlState control_state = getControlState();
    if (control_state.state != iii_drone_interfaces::msg::ControlState::CONTROL_STATE_ON_CABLE_DISARMED) {
        RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineCharging(): Vehicle is not disarmed on cable, entering error state");
        setState(error);
        return;
    }
    if (getStopChargingFlag()) {
        RCLCPP_INFO(get_logger(), "ContinuousMissionOrchestrator::stateMachineCharging(): Stop charging flag set, entering arming_on_cable state");
        startArmOnCable();
        setState(arming_on_cable);
        return;
    }
}
References arming_on_cable, error, getControlState(), getStopChargingFlag(), setState(), and startArmOnCable().
Referenced by stateMachineCallback().
stateMachineClosingGripper()
void ContinuousMissionOrchestrator::stateMachineClosingGripper () private
Definition at line 2003 of file continuous_mission_orchestrator_node.cpp.
{
    static bool action_timer_started = false;
    if (!isInControllableState()) {
        RCLCPP_ERROR(get_logger(), "ContinuousMissionOrchestrator::stateMachineClosingGripper(): Vehicle is not controllable, entering manual state");
        action_timer_started = false;
        sendGripperCommand(false);
        setTargetCableId(-1);
        setState(manual);
        return;
    }
    if (!gripperCommandTerminated()) {
        return;
    }
    // iii_drone_interfaces::msg::GripperStatus gripper_status = getGripperStatus();
    // bool gripper_is_closed = gripper_status.gripper_status == iii_drone_interfaces::msg::GripperStatus::GRIPPER_STATUS_CLOSED;
    // if (gripperCommandSucceeded() && gripper_is_closed) {
    //     RCLCPP_INFO(get_logger(), "ContinuousMissionOrchestrator::stateMachineClosingGripper(): Gripper command succeeded and gripper is closed, entering disarming_on_cable state");
    //     action_timer_started = false;
    //     startDisarmOnCable();
    //     setState(disarming_on_cable);
    // } else if (gripperCommandSucceeded()) {
    //     if (!action_timer_started) {
    //         RCLCPP_WARN(get_logger(), "ContinuousMissionOrchestrator::stateMachineClosingGripper(): Gripper command succeeded but gripper is not closed, starting action timer");
    //         action_timer_started = true;
    //         startActionTimeoutCounter();
    //     } else if (actionTimeout()) {
    //         RCLCPP_WARN(get_logger(), "ContinuousMissionOrchestrator::stateMachineClosingGripper(): Gripper command succeeded but gripper is not closed and gripper timer expired, entering taking_off_from_cable state");
    //         action_timer_started = false;
    //         startCableTakeoff();
    //         setState(taking_off_from_cable);
    //     }
    if (gripperCommandSucceeded()) {
        RCLCPP_INFO(get_logger(), "ContinuousMissionOrchestrator::stateMachineClosingGripper(): Gripper command succeeded, entering landing_on_cable state");
        this->get_parameter("cable_landing_max_retries", cable_landing_counter_);
        cable_landing_counter_--;
        if (cable_landing_counter_ < 0) {
            RCLCPP_WARN(this->get_logger(), "ContinuousMissionOrchestrator::stateMachineClosingGripper(): Parameter cable_landing_max_retries below 1. Continuing with a single attempt.");
            cable_landing_counter_ = 0;
        }
        startCableLanding();
        setState(landing_on_cable);
        return;
    } else {
        RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineClosingGripper(): Gripper command failed, entering error state");
        setState(error);
    }
}
References cable_landing_counter_, error, gripperCommandSucceeded(), gripperCommandTerminated(), isInControllableState(), landing_on_cable, manual, sendGripperCommand(), setState(), setTargetCableId(), and startCableLanding().
Referenced by stateMachineCallback().
stateMachineDisarmingOnCable()
void ContinuousMissionOrchestrator::stateMachineDisarmingOnCable () private
Definition at line 2090 of file continuous_mission_orchestrator_node.cpp.
{
    static bool action_timer_started = false;
    iii_drone_interfaces::msg::ControlState control_state = getControlState();
    if (!isInControllableState(control_state)) {
        RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineDisarmingOnCable(): Vehicle is not controllable, entering error state");
        setState(error);
        return;
    }
    if (!disarmOnCableTerminated()) {
        return;
    }
    if (disarmOnCableSucceeded() && control_state.state == iii_drone_interfaces::msg::ControlState::CONTROL_STATE_ON_CABLE_DISARMED) {
        RCLCPP_INFO(get_logger(), "ContinuousMissionOrchestrator::stateMachineDisarmingOnCable(): Disarm on cable succeeded and vehicle is disarmed on cable, entering charging state");
        action_timer_started = false;
        setState(charging);
    } else if (disarmOnCableSucceeded()) {
        if (!action_timer_started) {
            RCLCPP_WARN(get_logger(), "ContinuousMissionOrchestrator::stateMachineDisarmingOnCable(): Disarm on cable succeeded but vehicle is not disarmed on cable, starting action timer");
            action_timer_started = true;
            startActionTimeoutCounter();
        } else if (actionTimeout()) {
            RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineDisarmingOnCable(): Disarm on cable succeeded but vehicle is not disarmed on cable and action timer expired, entering error state");
            setState(error);
        }
    } else if (!disarmOnCableSucceeded()) {
        RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineDisarmingOnCable(): Disarm on cable failed, entering error state");
        action_timer_started = false;
        setState(error);
    }
}
References actionTimeout(), charging, disarmOnCableSucceeded(), disarmOnCableTerminated(), error, getControlState(), isInControllableState(), setState(), and startActionTimeoutCounter().
Referenced by stateMachineCallback().
stateMachineError()
void ContinuousMissionOrchestrator::stateMachineError () private
Definition at line 2373 of file continuous_mission_orchestrator_node.cpp.
{
    RCLCPP_FATAL_THROTTLE(get_logger(), *get_clock(), 1000, "ContinuousMissionOrchestrator::stateMachineError(): Error state");
}
Referenced by stateMachineCallback().
stateMachineFlyingUnderCable()
void ContinuousMissionOrchestrator::stateMachineFlyingUnderCable () private
Definition at line 1683 of file continuous_mission_orchestrator_node.cpp.
{
    static bool action_timer_started = false;
    // Check control state:
    iii_drone_interfaces::msg::ControlState control_state = getControlState();
    if (!isInControllableState(control_state)) {
        RCLCPP_ERROR(get_logger(), "ContinuousMissionOrchestrator::stateMachineFlyingUnderCable(): Vehicle is not controllable, entering manual state");
        action_timer_started = false;
        cancelFlyUnderCable();
        setTargetCableId(-1);
        setState(manual);
        return;
    }
    if (!flyUnderCableTerminated()) {
        return;
    }
    if (flyUnderCableSucceeded() && control_state.state == iii_drone_interfaces::msg::ControlState::CONTROL_STATE_HOVERING_UNDER_CABLE) {
        RCLCPP_INFO(get_logger(), "ContinuousMissionOrchestrator::stateMachineFlyingUnderCable(): Vehicle is hovering under cable, entering inspecting state");
        action_timer_started = false;
        setState(inspecting);
    } else if (flyUnderCableSucceeded()) {
        if (!action_timer_started) {
            RCLCPP_WARN(get_logger(), "ContinuousMissionOrchestrator::stateMachineFlyingUnderCable(): FlyUnderCable action succeeded but vehicle is not hovering under cable, starting action timer");
            action_timer_started = true;
            startActionTimeoutCounter();
        } else if (actionTimeout()) {
            RCLCPP_ERROR(get_logger(), "ContinuousMissionOrchestrator::stateMachineFlyingUnderCable(): FlyUnderCable action succeeded but vehicle is not hovering under cable, action timer timed out, entering error state");
            setState(error);
        }
    } else if (!flyUnderCableSucceeded()) {
        RCLCPP_ERROR(get_logger(), "ContinuousMissionOrchestrator::stateMachineFlyingUnderCable(): FlyUnderCable action failed, resetting target cable id and entering wait_for_target_line state");
        action_timer_started = false;
        setTargetCableId(-1);
        setState(wait_for_target_line);
    }
}
References actionTimeout(), cancelFlyUnderCable(), error, flyUnderCableSucceeded(), flyUnderCableTerminated(), getControlState(), inspecting, isInControllableState(), manual, setState(), setTargetCableId(), startActionTimeoutCounter(), and wait_for_target_line.
Referenced by stateMachineCallback().
stateMachineInspecting()
void ContinuousMissionOrchestrator::stateMachineInspecting () private
Definition at line 1751 of file continuous_mission_orchestrator_node.cpp.
{
    // Check control state:
    iii_drone_interfaces::msg::ControlState control_state = getControlState();
    if (control_state.state != iii_drone_interfaces::msg::ControlState::CONTROL_STATE_HOVERING_UNDER_CABLE) {
        RCLCPP_ERROR(get_logger(), "ContinuousMissionOrchestrator::stateMachineInspecting(): Vehicle is not hovering under cable, resetting target cable id and entering manual state");
        setTargetCableId(-1);
        setState(manual);
        return;
    }
    // Check if target line has changed:
    int8_t target_cable_id = getTargetCableId();
    if (target_cable_id < 0) {
        RCLCPP_ERROR(get_logger(), "ContinuousMissionOrchestrator::stateMachineInspecting(): New target cable id is negative, entering wait_for_target_line state");
        setState(wait_for_target_line);
        return;
    } else if (targetCableIdChanged()) {
        RCLCPP_INFO(get_logger(), "ContinuousMissionOrchestrator::stateMachineInspecting(): New target cable id %d registered, entering flying_under_cable state", target_cable_id);
        startFlyUnderCable();
        setState(flying_under_cable);
        return;
    }
    // // Check start charging flag:
    // if (getStartChargingFlag()) {
    //     RCLCPP_INFO(get_logger(), "ContinuousMissionOrchestrator::stateMachineInspecting(): Start charging flag set, entering landing_on_cable state");
    //     this->get_parameter("cable_landing_max_retries", cable_landing_counter_);
    //     cable_landing_counter_--;
    //     if (cable_landing_counter_ < 0) {
    //         RCLCPP_WARN(this->get_logger(), "ContinuousMissionOrchestrator::stateMachineClosingGripper(): Parameter cable_landing_max_retries below 1. Continuing with a single attempt.");
    //         cable_landing_counter_ = 0;
    //     }
    //     startCableLanding();
    //     setState(landing_on_cable);
    //     return;
    // }
    // Check start charging flag:
    if (getStartChargingFlag()) {
        RCLCPP_INFO(get_logger(), "ContinuousMissionOrchestrator::stateMachineInspecting(): Start charging flag set, entering closing_gripper state");
        sendGripperCommand(true);
        setState(closing_gripper);
        return;
    }
}
References closing_gripper, flying_under_cable, getControlState(), getStartChargingFlag(), getTargetCableId(), manual, sendGripperCommand(), setState(), setTargetCableId(), startFlyUnderCable(), targetCableIdChanged(), and wait_for_target_line.
Referenced by stateMachineCallback().
stateMachineLandingOnCable()
void ContinuousMissionOrchestrator::stateMachineLandingOnCable () private
Definition at line 1826 of file continuous_mission_orchestrator_node.cpp.
{
    static bool action_timer_started = false;
    iii_drone_interfaces::msg::ControlState control_state = getControlState();
    if (!isInControllableState(control_state)) {
        RCLCPP_ERROR(get_logger(), "ContinuousMissionOrchestrator::stateMachineLandingOnCable(): Vehicle is not controllable, entering manual state");
        action_timer_started = false;
        cancelCableLanding();
        setTargetCableId(-1);
        setState(manual);
        return;
    }
    if (!cableLandingTerminated()) {
        return;
    }
    iii_drone_interfaces::msg::GripperStatus gripper_status = getGripperStatus();
    bool gripper_is_closed = gripper_status.gripper_status == iii_drone_interfaces::msg::GripperStatus::GRIPPER_STATUS_CLOSED;
    if (cableLandingSucceeded() && control_state.state == iii_drone_interfaces::msg::ControlState::CONTROL_STATE_ON_CABLE_ARMED && gripper_is_closed) {
        action_timer_started = false;
        RCLCPP_INFO(get_logger(), "ContinuousMissionOrchestrator::stateMachineLandingOnCable(): Cable landing succeeded and gripper is closed, entering disarming_on_cable state");
        startDisarmOnCable();
        setState(disarming_on_cable);
    } else if (cableLandingSucceeded()) {
        if (!action_timer_started) {
            RCLCPP_WARN(get_logger(), "ContinuousMissionOrchestrator::stateMachineLandingOnCable(): Cable landing succeeded but vehicle is not on cable armed or gripper is not closed, starting action timer");
            action_timer_started = true;
            startActionTimeoutCounter();
        } else if (actionTimeout()) {
            RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineLandingOnCable(): Cable landing succeeded but vehicle is not on cable armed or gripper is not closed and action timer expired, entering error state");
            setState(error);
        }
    } else if (!cableLandingSucceeded()) {
        action_timer_started = false;
        if (control_state.state == iii_drone_interfaces::msg::ControlState::CONTROL_STATE_HOVERING_UNDER_CABLE) {
            if (cable_landing_counter_ <= 0) {
                RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineLandingOnCable(): Cable landing failed and no retries left, entering error state");
                setState(error);
                return;
            } else {
                RCLCPP_WARN(get_logger(), "ContinuousMissionOrchestrator::stateMachineLandingOnCable(): Cable landing failed, %d retr%s left, entering landing_on_cable state", cable_landing_counter_, cable_landing_counter_ == 1 ? "y" : "ies");
                cable_landing_counter_--;
                startCableLanding();
            }
        } else if (control_state.state != iii_drone_interfaces::msg::ControlState::CONTROL_STATE_DURING_CABLE_TAKEOFF && control_state.state != iii_drone_interfaces::msg::ControlState::CONTROL_STATE_DURING_CABLE_LANDING) {
            RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineLandingOnCable(): Cable landing failed and vehicle is not hovering under cable, not during cable takeoff, and not during cable landing, entering error state");
            setState(error);
        }
    }
    // if (cableLandingSucceeded() && control_state.state == iii_drone_interfaces::msg::ControlState::CONTROL_STATE_ON_CABLE_ARMED) {
    //     action_timer_started = false;
    //     // if (!gripperIsClosed()) {
    //     //     RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineLandingOnCable(): Cable landing succeeded but gripper is not closed, entering error state");
    //     //     setState(error);
    //     // } else {
    //     //     RCLCPP_INFO(get_logger(), "ContinuousMissionOrchestrator::stateMachineLandingOnCable(): Cable landing succeeded and gripper is closed, entering disarming_on_cable state");
    //     // }
    //     RCLCPP_INFO(get_logger(), "ContinuousMissionOrchestrator::stateMachineLandingOnCable(): Cable landing succeeded, entering closing_gripper state");
    //     sendGripperCommand(true);
    //     setState(closing_gripper);
    // } else if (cableLandingSucceeded()) {
    //     if (!action_timer_started) {
    //         RCLCPP_WARN(get_logger(), "ContinuousMissionOrchestrator::stateMachineLandingOnCable(): Cable landing succeeded but vehicle is not on cable armed, starting action timer");
    //         action_timer_started = true;
    //         startActionTimeoutCounter();
    //     } else if (actionTimeout()) {
    //         RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineLandingOnCable(): Cable landing succeeded but vehicle is not on cable armed and action timer expired, entering error state");
    //         setState(error);
    //     }
    // } else if (!cableLandingSucceeded()) {
    //     action_timer_started = false;
    //     if (control_state.state == iii_drone_interfaces::msg::ControlState::CONTROL_STATE_HOVERING_UNDER_CABLE) {
    //         if (cable_landing_counter_ <= 0) {
    //             RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineLandingOnCable(): Cable landing failed and no retries left, entering error state");
    //             setState(error);
    //             return;
    //         } else {
    //             RCLCPP_WARN(get_logger(), "ContinuousMissionOrchestrator::stateMachineLandingOnCable(): Cable landing failed, %d retr%s left, entering landing_on_cable state", cable_landing_counter_, cable_landing_counter_ == 1 ? "y" : "ies");
    //             cable_landing_counter_--;
    //             startCableLanding();
    //         }
    //     } else if (control_state.state != iii_drone_interfaces::msg::ControlState::CONTROL_STATE_DURING_CABLE_LANDING) {
    //         RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineLandingOnCable(): Cable landing failed and vehicle is not hovering under cable, entering error state");
    //         setState(error);
    //     }
    // }
}
References actionTimeout(), cable_landing_counter_, cableLandingSucceeded(), cableLandingTerminated(), cancelCableLanding(), disarming_on_cable, error, getControlState(), getGripperStatus(), isInControllableState(), manual, setState(), setTargetCableId(), startActionTimeoutCounter(), startCableLanding(), and startDisarmOnCable().
Referenced by stateMachineCallback().
stateMachineManual()
void ContinuousMissionOrchestrator::stateMachineManual () private
Definition at line 1644 of file continuous_mission_orchestrator_node.cpp.
{
    iii_drone_interfaces::msg::ControlState control_state = getControlState();
    if (control_state.state == iii_drone_interfaces::msg::ControlState::CONTROL_STATE_HOVERING || control_state.state == iii_drone_interfaces::msg::ControlState::CONTROL_STATE_HOVERING_UNDER_CABLE) {
        RCLCPP_INFO(get_logger(), "ContinuousMissionOrchestrator::stateMachineManual(): Vehicle is controllable, entering wait_for_target_line state");
        setState(wait_for_target_line);
    }
}
References getControlState(), setState(), and wait_for_target_line.
Referenced by stateMachineCallback().
stateMachineOpeningGripper()
void ContinuousMissionOrchestrator::stateMachineOpeningGripper () private
Definition at line 2236 of file continuous_mission_orchestrator_node.cpp.
{
    static bool action_timer_started = false;
    if (!isInControllableState()) {
        RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineOpeningGripper(): Vehicle is not controllable, entering error state");
        setState(error);
        return;
    }
    if (!gripperCommandTerminated()) {
        return;
    }
    if (gripperCommandSucceeded() && gripperIsOpen()) {
        RCLCPP_INFO(get_logger(), "ContinuousMissionOrchestrator::stateMachineOpeningGripper(): Gripper command succeeded and gripper is open, entering taking_off_from_cable state");
        action_timer_started = false;
        startCableTakeoff();
        setState(taking_off_from_cable);
    } else if (gripperCommandSucceeded()) {
        if (!action_timer_started) {
            RCLCPP_WARN(get_logger(), "ContinuousMissionOrchestrator::stateMachineOpeningGripper(): Gripper command succeeded but gripper is not open, starting action timer");
            action_timer_started = true;
            startActionTimeoutCounter();
        } else if (actionTimeout()) {
            RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineOpeningGripper(): Gripper command succeeded but gripper is not open and action timer expired, entering error state");
            setState(error);
        }
    } else if (!gripperCommandSucceeded()) {
        RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineOpeningGripper(): Gripper command failed, entering error state");
        setState(error);
    }
}
References actionTimeout(), error, gripperCommandSucceeded(), gripperCommandTerminated(), gripperIsOpen(), isInControllableState(), setState(), startActionTimeoutCounter(), startCableTakeoff(), and taking_off_from_cable.
Referenced by stateMachineCallback().
stateMachineTakingOffFromCable()
void ContinuousMissionOrchestrator::stateMachineTakingOffFromCable () private
Definition at line 2292 of file continuous_mission_orchestrator_node.cpp.
{
    static bool action_timer_started = false;
    iii_drone_interfaces::msg::ControlState control_state = getControlState();
    if (!isInControllableState(control_state)) {
        RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineTakingOffFromCable(): Vehicle is not controllable, entering error state");
        setState(error);
        return;
    }
    if (!cableTakeoffTerminated()) {
        return;
    }
    if (cableTakeoffSucceeded() && control_state.state == iii_drone_interfaces::msg::ControlState::CONTROL_STATE_HOVERING_UNDER_CABLE) {
        if (getStartChargingFlag()) {
            if (cable_landing_counter_ <= 0) {
                RCLCPP_ERROR(get_logger(), "ContinuousMissionOrchestrator::stateMachineTakingOffFromCable(): Cable takeoff succeeded and vehicle is hovering under cable and start charging flag is still set, but no cable landing retries left, entering error state");
                setState(error);
            } else {
                RCLCPP_WARN(get_logger(), "ContinuousMissionOrchestrator::stateMachineTakingOffFromCable(): Cable takeoff succeeded and vehicle is hovering under cable and start charging flag is still set, entering landing_on_cable state");
                action_timer_started = false;
                cable_landing_counter_--;
                startCableLanding();
                setState(landing_on_cable);
            }
            return;
        }
        RCLCPP_INFO(get_logger(), "ContinuousMissionOrchestrator::stateMachineTakingOffFromCable(): Cable takeoff succeeded and vehicle is hovering under cable, entering inspecting state");
        action_timer_started = false;
        setState(inspecting);
    } else if (cableTakeoffSucceeded()) {
        if (!action_timer_started) {
            RCLCPP_WARN(get_logger(), "ContinuousMissionOrchestrator::stateMachineTakingOffFromCable(): Cable takeoff succeeded but vehicle is not hovering under cable, starting action timer");
            action_timer_started = true;
            startActionTimeoutCounter();
        } else if (actionTimeout()) {
            RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineTakingOffFromCable(): Cable takeoff succeeded but vehicle is not hovering under cable and action timer expired, entering error state");
            setState(error);
        }
    } else if (!cableTakeoffSucceeded()) {
        RCLCPP_FATAL(get_logger(), "ContinuousMissionOrchestrator::stateMachineTakingOffFromCable(): Cable takeoff failed, entering error state");
        setState(error);
    }
}
References actionTimeout(), cable_landing_counter_, cableTakeoffSucceeded(), cableTakeoffTerminated(), error, getControlState(), getStartChargingFlag(), inspecting, isInControllableState(), landing_on_cable, setState(), startActionTimeoutCounter(), and startCableLanding().
Referenced by stateMachineCallback().
stateMachineWaitForTargetLine()
void ContinuousMissionOrchestrator::stateMachineWaitForTargetLine () private
Definition at line 1657 of file continuous_mission_orchestrator_node.cpp.
{
    if (!isInControllableState()) {
        RCLCPP_ERROR(get_logger(), "ContinuousMissionOrchestrator::stateMachineWaitForTargetLine(): Vehicle is not controllable, entering manual state");
        setTargetCableId(-1);
        setState(manual);
        return;
    }
    int8_t target_cable_id = getTargetCableId();
    if (target_cable_id >= 0) {
        RCLCPP_INFO(get_logger(), "ContinuousMissionOrchestrator::stateMachineWaitForTargetLine(): Target cable id %d registered, entering flying_under_cable state", target_cable_id);
        startFlyUnderCable();
        setState(flying_under_cable);
    }
}
References flying_under_cable, getTargetCableId(), isInControllableState(), manual, setState(), setTargetCableId(), and startFlyUnderCable().
Referenced by stateMachineCallback().
targetCableIdChanged()
bool ContinuousMissionOrchestrator::targetCableIdChanged () private
Definition at line 830 of file continuous_mission_orchestrator_node.cpp.
{
    std::lock_guard<std::mutex> lock(target_cable_id_mutex_);
    return target_cable_id_changed_;
}
References target_cable_id_changed_, and target_cable_id_mutex_.
Referenced by stateMachineInspecting().
Member Data Documentation
action_start_time_
rclcpp::Time iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::action_start_time_ private
Definition at line 353 of file continuous_mission_orchestrator_node.hpp.
Referenced by actionTimeout(), and startActionTimeoutCounter().
arm_on_cable_active_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::arm_on_cable_active_ private
Definition at line 147 of file continuous_mission_orchestrator_node.hpp.
Referenced by armOnCableGoalResponseCallback(), armOnCableResultCallback(), armOnCableTerminated(), and startArmOnCable().
arm_on_cable_client_
rclcpp_action::Client<ArmOnCable>::SharedPtr iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::arm_on_cable_client_ private
Definition at line 140 of file continuous_mission_orchestrator_node.hpp.
Referenced by cancelArmOnCable(), ContinuousMissionOrchestrator(), and startArmOnCable().
arm_on_cable_goal_accepted_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::arm_on_cable_goal_accepted_ private
Definition at line 146 of file continuous_mission_orchestrator_node.hpp.
Referenced by armOnCableGoalResponseCallback(), armOnCableSucceeded(), and startArmOnCable().
arm_on_cable_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::arm_on_cable_mutex_ private
Definition at line 149 of file continuous_mission_orchestrator_node.hpp.
Referenced by armOnCableGoalResponseCallback(), armOnCableResultCallback(), armOnCableSucceeded(), armOnCableTerminated(), and startArmOnCable().
arm_on_cable_response_received_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::arm_on_cable_response_received_ private
Definition at line 145 of file continuous_mission_orchestrator_node.hpp.
Referenced by armOnCableGoalResponseCallback(), armOnCableTerminated(), and startArmOnCable().
arm_on_cable_success_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::arm_on_cable_success_ private
Definition at line 148 of file continuous_mission_orchestrator_node.hpp.
Referenced by armOnCableResultCallback(), armOnCableSucceeded(), and startArmOnCable().
battery_voltage_
float iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::battery_voltage_ = false private
Definition at line 204 of file continuous_mission_orchestrator_node.hpp.
Referenced by batteryVoltageCallback(), and getBatteryVoltage().
battery_voltage_high_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::battery_voltage_high_ = false private
Definition at line 206 of file continuous_mission_orchestrator_node.hpp.
Referenced by batteryVoltageCallback(), batteryVoltageHigh(), and setBatteryVoltageHigh().
battery_voltage_low_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::battery_voltage_low_ = false private
Definition at line 205 of file continuous_mission_orchestrator_node.hpp.
Referenced by batteryVoltageCallback(), batteryVoltageLow(), and setBatteryVoltageLow().
battery_voltage_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::battery_voltage_mutex_ private
Definition at line 207 of file continuous_mission_orchestrator_node.hpp.
Referenced by batteryVoltageCallback(), batteryVoltageHigh(), batteryVoltageLow(), getBatteryVoltage(), setBatteryVoltageHigh(), and setBatteryVoltageLow().
battery_voltage_sub_
rclcpp::Subscription<std_msgs::msg::Float32>::SharedPtr iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::battery_voltage_sub_ private
Definition at line 202 of file continuous_mission_orchestrator_node.hpp.
Referenced by ContinuousMissionOrchestrator().
cable_landing_active_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::cable_landing_active_ private
Definition at line 111 of file continuous_mission_orchestrator_node.hpp.
Referenced by cableLandingGoalResponseCallback(), cableLandingResultCallback(), cableLandingTerminated(), and startCableLanding().
cable_landing_client_
rclcpp_action::Client<CableLanding>::SharedPtr iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::cable_landing_client_ private
Definition at line 104 of file continuous_mission_orchestrator_node.hpp.
Referenced by cancelCableLanding(), ContinuousMissionOrchestrator(), and startCableLanding().
cable_landing_counter_
int iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::cable_landing_counter_ private
Definition at line 120 of file continuous_mission_orchestrator_node.hpp.
Referenced by stateMachineClosingGripper(), stateMachineLandingOnCable(), and stateMachineTakingOffFromCable().
cable_landing_goal_accepted_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::cable_landing_goal_accepted_ private
Definition at line 110 of file continuous_mission_orchestrator_node.hpp.
Referenced by cableLandingGoalResponseCallback(), cableLandingSucceeded(), and startCableLanding().
cable_landing_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::cable_landing_mutex_ private
Definition at line 113 of file continuous_mission_orchestrator_node.hpp.
Referenced by cableLandingGoalResponseCallback(), cableLandingResultCallback(), cableLandingSucceeded(), cableLandingTerminated(), and startCableLanding().
cable_landing_response_received_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::cable_landing_response_received_ private
Definition at line 109 of file continuous_mission_orchestrator_node.hpp.
Referenced by cableLandingGoalResponseCallback(), cableLandingTerminated(), and startCableLanding().
cable_landing_success_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::cable_landing_success_ private
Definition at line 112 of file continuous_mission_orchestrator_node.hpp.
Referenced by cableLandingResultCallback(), cableLandingSucceeded(), and startCableLanding().
cable_takeoff_active_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::cable_takeoff_active_ private
Definition at line 164 of file continuous_mission_orchestrator_node.hpp.
Referenced by cableTakeoffGoalResponseCallback(), cableTakeoffResultCallback(), cableTakeoffTerminated(), and startCableTakeoff().
cable_takeoff_client_
rclcpp_action::Client<CableTakeoff>::SharedPtr iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::cable_takeoff_client_ private
Definition at line 157 of file continuous_mission_orchestrator_node.hpp.
Referenced by cancelCableTakeoff(), ContinuousMissionOrchestrator(), and startCableTakeoff().
cable_takeoff_goal_accepted_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::cable_takeoff_goal_accepted_ private
Definition at line 163 of file continuous_mission_orchestrator_node.hpp.
Referenced by cableTakeoffGoalResponseCallback(), cableTakeoffSucceeded(), and startCableTakeoff().
cable_takeoff_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::cable_takeoff_mutex_ private
Definition at line 166 of file continuous_mission_orchestrator_node.hpp.
Referenced by cableTakeoffGoalResponseCallback(), cableTakeoffResultCallback(), cableTakeoffSucceeded(), cableTakeoffTerminated(), and startCableTakeoff().
cable_takeoff_response_received_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::cable_takeoff_response_received_ private
Definition at line 162 of file continuous_mission_orchestrator_node.hpp.
Referenced by cableTakeoffGoalResponseCallback(), cableTakeoffTerminated(), and startCableTakeoff().
cable_takeoff_success_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::cable_takeoff_success_ private
Definition at line 165 of file continuous_mission_orchestrator_node.hpp.
Referenced by cableTakeoffResultCallback(), cableTakeoffSucceeded(), and startCableTakeoff().
charger_operating_mode_
iii_drone_interfaces::msg::ChargerOperatingMode iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::charger_operating_mode_ private
Definition at line 225 of file continuous_mission_orchestrator_node.hpp.
Referenced by chargerOperatingModeCallback(), and getChargerOperatingMode().
charger_operating_mode_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::charger_operating_mode_mutex_ private
Definition at line 226 of file continuous_mission_orchestrator_node.hpp.
Referenced by chargerOperatingModeCallback(), and getChargerOperatingMode().
charger_operating_mode_sub_
rclcpp::Subscription<iii_drone_interfaces::msg::ChargerOperatingMode>::SharedPtr iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::charger_operating_mode_sub_ private
Definition at line 223 of file continuous_mission_orchestrator_node.hpp.
Referenced by ContinuousMissionOrchestrator().
charger_status_
iii_drone_interfaces::msg::ChargerStatus iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::charger_status_ private
Definition at line 231 of file continuous_mission_orchestrator_node.hpp.
Referenced by chargerStatusCallback(), and getChargerStatus().
charger_status_charging_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::charger_status_charging_ = false private
Definition at line 233 of file continuous_mission_orchestrator_node.hpp.
Referenced by chargerStatusCallback(), chargerStatusCharging(), and setChargerStatusCharging().
charger_status_disabled_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::charger_status_disabled_ = false private
Definition at line 232 of file continuous_mission_orchestrator_node.hpp.
Referenced by chargerStatusCallback(), chargerStatusDisabled(), and setChargerStatusDisabled().
charger_status_fully_charged_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::charger_status_fully_charged_ = false private
Definition at line 234 of file continuous_mission_orchestrator_node.hpp.
Referenced by chargerStatusCallback(), chargerStatusFullyCharged(), and setChargerStatusFullyCharged().
charger_status_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::charger_status_mutex_ private
Definition at line 235 of file continuous_mission_orchestrator_node.hpp.
Referenced by chargerStatusCallback(), chargerStatusCharging(), chargerStatusDisabled(), chargerStatusFullyCharged(), getChargerStatus(), setChargerStatusCharging(), setChargerStatusDisabled(), and setChargerStatusFullyCharged().
charger_status_sub_
rclcpp::Subscription<iii_drone_interfaces::msg::ChargerStatus>::SharedPtr iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::charger_status_sub_ private
Definition at line 229 of file continuous_mission_orchestrator_node.hpp.
Referenced by ContinuousMissionOrchestrator().
charging_power_
float iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::charging_power_ = false private
Definition at line 217 of file continuous_mission_orchestrator_node.hpp.
Referenced by chargingPowerCallback(), and getChargingPower().
charging_power_low_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::charging_power_low_ = false private
Definition at line 218 of file continuous_mission_orchestrator_node.hpp.
Referenced by chargingPowerCallback(), and chargingPowerLow().
charging_power_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::charging_power_mutex_ private
Definition at line 219 of file continuous_mission_orchestrator_node.hpp.
Referenced by chargingPowerCallback(), chargingPowerLow(), and getChargingPower().
charging_power_sub_
rclcpp::Subscription<std_msgs::msg::Float32>::SharedPtr iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::charging_power_sub_ private
Definition at line 215 of file continuous_mission_orchestrator_node.hpp.
Referenced by ContinuousMissionOrchestrator().
charging_start_time_
rclcpp::Time iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::charging_start_time_ private
Definition at line 254 of file continuous_mission_orchestrator_node.hpp.
Referenced by evaluateChargingStatus(), getChargingStartTime(), and setState().
charging_start_time_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::charging_start_time_mutex_ private
Definition at line 255 of file continuous_mission_orchestrator_node.hpp.
Referenced by getChargingStartTime(), and setState().
control_state_
iii_drone_interfaces::msg::ControlState iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::control_state_ private
Definition at line 304 of file continuous_mission_orchestrator_node.hpp.
Referenced by getControlState(), and setControlState().
control_state_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::control_state_mutex_ private
Definition at line 305 of file continuous_mission_orchestrator_node.hpp.
Referenced by getControlState(), and setControlState().
control_state_sub_
rclcpp::Subscription<iii_drone_interfaces::msg::ControlState>::SharedPtr iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::control_state_sub_ private
Definition at line 302 of file continuous_mission_orchestrator_node.hpp.
Referenced by ContinuousMissionOrchestrator().
disarm_on_cable_active_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::disarm_on_cable_active_ private
Definition at line 130 of file continuous_mission_orchestrator_node.hpp.
Referenced by disarmOnCableGoalResponseCallback(), disarmOnCableResultCallback(), disarmOnCableTerminated(), and startDisarmOnCable().
disarm_on_cable_client_
rclcpp_action::Client<DisarmOnCable>::SharedPtr iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::disarm_on_cable_client_ private
Definition at line 123 of file continuous_mission_orchestrator_node.hpp.
Referenced by cancelDisarmOnCable(), ContinuousMissionOrchestrator(), and startDisarmOnCable().
disarm_on_cable_goal_accepted_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::disarm_on_cable_goal_accepted_ private
Definition at line 129 of file continuous_mission_orchestrator_node.hpp.
Referenced by disarmOnCableGoalResponseCallback(), disarmOnCableSucceeded(), and startDisarmOnCable().
disarm_on_cable_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::disarm_on_cable_mutex_ private
Definition at line 132 of file continuous_mission_orchestrator_node.hpp.
Referenced by disarmOnCableGoalResponseCallback(), disarmOnCableResultCallback(), disarmOnCableSucceeded(), disarmOnCableTerminated(), and startDisarmOnCable().
disarm_on_cable_response_received_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::disarm_on_cable_response_received_ private
Definition at line 128 of file continuous_mission_orchestrator_node.hpp.
Referenced by disarmOnCableGoalResponseCallback(), disarmOnCableTerminated(), and startDisarmOnCable().
disarm_on_cable_success_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::disarm_on_cable_success_ private
Definition at line 131 of file continuous_mission_orchestrator_node.hpp.
Referenced by disarmOnCableResultCallback(), disarmOnCableSucceeded(), and startDisarmOnCable().
fly_under_cable_active_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::fly_under_cable_active_ private
Definition at line 94 of file continuous_mission_orchestrator_node.hpp.
Referenced by flyUnderCableGoalResponseCallback(), flyUnderCableResultCallback(), flyUnderCableTerminated(), and startFlyUnderCable().
fly_under_cable_client_
rclcpp_action::Client<FlyUnderCable>::SharedPtr iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::fly_under_cable_client_ private
Definition at line 87 of file continuous_mission_orchestrator_node.hpp.
Referenced by cancelFlyUnderCable(), ContinuousMissionOrchestrator(), and startFlyUnderCable().
fly_under_cable_goal_accepted_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::fly_under_cable_goal_accepted_ private
Definition at line 93 of file continuous_mission_orchestrator_node.hpp.
Referenced by flyUnderCableGoalResponseCallback(), flyUnderCableSucceeded(), and startFlyUnderCable().
fly_under_cable_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::fly_under_cable_mutex_ private
Definition at line 96 of file continuous_mission_orchestrator_node.hpp.
Referenced by flyUnderCableGoalResponseCallback(), flyUnderCableResultCallback(), flyUnderCableSucceeded(), flyUnderCableTerminated(), and startFlyUnderCable().
fly_under_cable_response_received_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::fly_under_cable_response_received_ private
Definition at line 92 of file continuous_mission_orchestrator_node.hpp.
Referenced by flyUnderCableGoalResponseCallback(), flyUnderCableTerminated(), and startFlyUnderCable().
fly_under_cable_success_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::fly_under_cable_success_ private
Definition at line 95 of file continuous_mission_orchestrator_node.hpp.
Referenced by flyUnderCableResultCallback(), flyUnderCableSucceeded(), and startFlyUnderCable().
gripper_command_active_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::gripper_command_active_ private
Definition at line 178 of file continuous_mission_orchestrator_node.hpp.
Referenced by gripperCommandResponseCallback(), gripperCommandTerminated(), and sendGripperCommand().
gripper_command_client_
rclcpp::Client<iii_drone_interfaces::srv::GripperCommand>::SharedPtr iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::gripper_command_client_ private
Definition at line 174 of file continuous_mission_orchestrator_node.hpp.
Referenced by ContinuousMissionOrchestrator(), and sendGripperCommand().
gripper_command_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::gripper_command_mutex_ private
Definition at line 181 of file continuous_mission_orchestrator_node.hpp.
Referenced by getLastGripperCommandClose(), gripperCommandResponseCallback(), gripperCommandSucceeded(), gripperCommandTerminated(), and sendGripperCommand().
gripper_command_response_received_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::gripper_command_response_received_ private
Definition at line 177 of file continuous_mission_orchestrator_node.hpp.
Referenced by gripperCommandResponseCallback(), gripperCommandTerminated(), and sendGripperCommand().
gripper_command_success_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::gripper_command_success_ private
Definition at line 179 of file continuous_mission_orchestrator_node.hpp.
Referenced by gripperCommandResponseCallback(), gripperCommandSucceeded(), and sendGripperCommand().
gripper_status_
iii_drone_interfaces::msg::GripperStatus iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::gripper_status_ private
Definition at line 246 of file continuous_mission_orchestrator_node.hpp.
Referenced by getGripperStatus(), and gripperStatusCallback().
gripper_status_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::gripper_status_mutex_ private
Definition at line 247 of file continuous_mission_orchestrator_node.hpp.
Referenced by getGripperStatus(), and gripperStatusCallback().
gripper_status_sub_
rclcpp::Subscription<iii_drone_interfaces::msg::GripperStatus>::SharedPtr iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::gripper_status_sub_ private
Definition at line 244 of file continuous_mission_orchestrator_node.hpp.
Referenced by ContinuousMissionOrchestrator().
initiate_charging_srv_called_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::initiate_charging_srv_called_ = false private
Definition at line 262 of file continuous_mission_orchestrator_node.hpp.
Referenced by clearInitiateChargingSrvCalled(), initiateChargingSrvCallback(), and initiateChargingSrvCalled().
initiate_charging_srv_called_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::initiate_charging_srv_called_mutex_ private
Definition at line 263 of file continuous_mission_orchestrator_node.hpp.
Referenced by clearInitiateChargingSrvCalled(), initiateChargingSrvCallback(), and initiateChargingSrvCalled().
initiate_charging_srv_server_
rclcpp::Service<iii_drone_interfaces::srv::InitiateCharging>::SharedPtr iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::initiate_charging_srv_server_ private
Definition at line 258 of file continuous_mission_orchestrator_node.hpp.
Referenced by ContinuousMissionOrchestrator().
interrupt_charging_srv_called_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::interrupt_charging_srv_called_ = false private
Definition at line 271 of file continuous_mission_orchestrator_node.hpp.
Referenced by clearInterruptChargingSrvCalled(), interruptChargingSrvCallback(), and interruptChargingSrvCalled().
interrupt_charging_srv_called_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::interrupt_charging_srv_called_mutex_ private
Definition at line 272 of file continuous_mission_orchestrator_node.hpp.
Referenced by clearInterruptChargingSrvCalled(), interruptChargingSrvCallback(), and interruptChargingSrvCalled().
interrupt_charging_srv_server_
rclcpp::Service<iii_drone_interfaces::srv::InterruptCharging>::SharedPtr iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::interrupt_charging_srv_server_ private
Definition at line 267 of file continuous_mission_orchestrator_node.hpp.
Referenced by ContinuousMissionOrchestrator().
last_gripper_command_close_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::last_gripper_command_close_ = false private
Definition at line 180 of file continuous_mission_orchestrator_node.hpp.
Referenced by getLastGripperCommandClose().
prolong_charging_for_seconds_
float iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::prolong_charging_for_seconds_ = -1 private
Definition at line 281 of file continuous_mission_orchestrator_node.hpp.
Referenced by clearProlongCharging(), getProlongChargingForSeconds(), and prolongChargingSrvCallback().
prolong_charging_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::prolong_charging_mutex_ private
Definition at line 283 of file continuous_mission_orchestrator_node.hpp.
Referenced by clearProlongCharging(), getProlongChargingForSeconds(), getProlongChargingUntilNewBatteryVoltage(), prolongChargingSrvCallback(), and prolongChargingUntilInterrupted().
prolong_charging_srv_server_
rclcpp::Service<iii_drone_interfaces::srv::ProlongCharging>::SharedPtr iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::prolong_charging_srv_server_ private
Definition at line 276 of file continuous_mission_orchestrator_node.hpp.
prolong_charging_until_interrupted_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::prolong_charging_until_interrupted_ = false private
Definition at line 280 of file continuous_mission_orchestrator_node.hpp.
Referenced by clearProlongCharging(), prolongChargingSrvCallback(), and prolongChargingUntilInterrupted().
prolong_charging_until_new_battery_voltage_
float iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::prolong_charging_until_new_battery_voltage_ = -1 private
Definition at line 282 of file continuous_mission_orchestrator_node.hpp.
Referenced by clearProlongCharging(), getProlongChargingUntilNewBatteryVoltage(), and prolongChargingSrvCallback().
publish_timer_
rclcpp::TimerBase::SharedPtr iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::publish_timer_ private
Definition at line 359 of file continuous_mission_orchestrator_node.hpp.
Referenced by ContinuousMissionOrchestrator().
set_target_cable_id_srv_
rclcpp::Service<iii_drone_interfaces::srv::SetTargetCableId>::SharedPtr iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::set_target_cable_id_srv_ private
Definition at line 189 of file continuous_mission_orchestrator_node.hpp.
Referenced by ContinuousMissionOrchestrator().
start_charging_flag_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::start_charging_flag_ {false} private
Definition at line 291 of file continuous_mission_orchestrator_node.hpp.
{false};
Referenced by getStartChargingFlag(), and setStartChargingFlag().
start_charging_flag_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::start_charging_flag_mutex_ private
Definition at line 292 of file continuous_mission_orchestrator_node.hpp.
Referenced by getStartChargingFlag(), and setStartChargingFlag().
state_
state_t iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::state_ = manual private
Definition at line 332 of file continuous_mission_orchestrator_node.hpp.
Referenced by getState(), and setState().
state_machine_timer_
rclcpp::TimerBase::SharedPtr iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::state_machine_timer_ private
Definition at line 337 of file continuous_mission_orchestrator_node.hpp.
Referenced by ContinuousMissionOrchestrator().
state_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::state_mutex_ private
Definition at line 333 of file continuous_mission_orchestrator_node.hpp.
Referenced by getState(), and setState().
state_pub_
rclcpp::Publisher<std_msgs::msg::String>::SharedPtr iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::state_pub_ private
Definition at line 358 of file continuous_mission_orchestrator_node.hpp.
Referenced by ContinuousMissionOrchestrator(), and publishCallback().
stop_charging_flag_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::stop_charging_flag_ {false} private
Definition at line 296 of file continuous_mission_orchestrator_node.hpp.
{false};
Referenced by getStopChargingFlag(), and setStopChargingFlag().
stop_charging_flag_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::stop_charging_flag_mutex_ private
Definition at line 297 of file continuous_mission_orchestrator_node.hpp.
Referenced by getStopChargingFlag(), and setStopChargingFlag().
target_cable_id_
int8_t iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::target_cable_id_ = -1 private
Definition at line 193 of file continuous_mission_orchestrator_node.hpp.
Referenced by getTargetCableId(), and setTargetCableId().
target_cable_id_changed_
bool iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::target_cable_id_changed_ = false private
Definition at line 194 of file continuous_mission_orchestrator_node.hpp.
Referenced by setTargetCableIdChanged(), and targetCableIdChanged().
target_cable_id_mutex_
std::mutex iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::target_cable_id_mutex_ private
Definition at line 195 of file continuous_mission_orchestrator_node.hpp.
Referenced by getTargetCableId(), setTargetCableId(), setTargetCableIdChanged(), and targetCableIdChanged().
tf_buffer_
std::unique_ptr<tf2_ros::Buffer> iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::tf_buffer_ private
Definition at line 314 of file continuous_mission_orchestrator_node.hpp.
Referenced by ContinuousMissionOrchestrator().
transform_listener_
std::shared_ptr<tf2_ros::TransformListener> iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestrator::transform_listener_ {nullptr} private
Definition at line 313 of file continuous_mission_orchestrator_node.hpp.
{nullptr};
Referenced by ContinuousMissionOrchestrator().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/mission/continuous_mission_orchestrator_node/continuous_mission_orchestrator_node.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/mission/continuous_mission_orchestrator_node/continuous_mission_orchestrator_node.cpp