III-Drone: iii_drone::utils::Timestamp Class Reference
iii_drone::utils::Timestamp Class Reference
Timestamp class for storing and loading thread safe ROS2 timestamps.
#include <timestamp.hpp>
Public Member Functions
Timestamp ()
Default constructor.
Timestamp (const rclcpp::Time &stamp)
Constructor from ROS2 timestamp.
void Update ()
Updates the timestamp to now.
Timestamp & operator= (const rclcpp::Time &stamp)
Assignment operator.
Timestamp & operator= (const Timestamp &timestamp)
Assignment operator.
operator rclcpp::Time () const
Cast operator.
Private Attributes
rclcpp::Time stamp_
The ROS2 timestamp.
std::shared_mutex mutex_
Mutex for thread safety.
Detailed Description
Timestamp class for storing and loading thread safe ROS2 timestamps.
Definition at line 28 of file timestamp.hpp.
Constructor & Destructor Documentation
Timestamp() [1/2]
Timestamp::Timestamp ()
Default constructor.
Definition at line 13 of file timestamp.cpp.
                     {
    Update();
}
References Update().
Timestamp() [2/2]
Timestamp::Timestamp (const rclcpp::Time & stamp)
Constructor from ROS2 timestamp.
Parameters
stamp The ROS2 timestamp.
Definition at line 17 of file timestamp.cpp.
{
    stamp_ = stamp;
}
References stamp_.
Member Function Documentation
operator rclcpp::Time()
Timestamp::operator rclcpp::Time () const
Cast operator.
Definition at line 43 of file timestamp.cpp.
{
    std::shared_lock<std::shared_mutex> lock(mutex_);
    return stamp_;
}
operator=() [1/2]
Timestamp & Timestamp::operator= (const rclcpp::Time & stamp)
Assignment operator.
Definition at line 27 of file timestamp.cpp.
{
    std::unique_lock<std::shared_mutex> lock(mutex_);
    stamp_ = stamp;
    return *this;
}
References mutex_, and stamp_.
operator=() [2/2]
Timestamp & Timestamp::operator= (const Timestamp & timestamp)
Assignment operator.
Definition at line 35 of file timestamp.cpp.
{
    std::unique_lock<std::shared_mutex> lock(mutex_);
    stamp_ = timestamp;
    return *this;
}
References mutex_, and stamp_.
Update()
void Timestamp::Update ()
Updates the timestamp to now.
Definition at line 21 of file timestamp.cpp.
                       {
    std::unique_lock<std::shared_mutex> lock(mutex_);
    stamp_ = rclcpp::Clock().now();
}
References mutex_, and stamp_.
Referenced by iii_drone::perception::Powerline::CleanupLines(), iii_drone::perception::Powerline::ComputeInterLinePositions(), iii_drone::perception::PowerlineDirection::PowerlineDirection(), iii_drone::perception::PowerlineDirection::Predict(), iii_drone::perception::SingleLine::Predict(), iii_drone::perception::Powerline::Reset(), iii_drone::perception::SingleLine::SetDirection(), iii_drone::perception::SingleLine::SetPosition(), Timestamp(), iii_drone::perception::SingleLine::Update(), iii_drone::perception::PowerlineDirection::Update(), iii_drone::perception::Powerline::UpdateDirection(), iii_drone::perception::Powerline::UpdateLine(), and iii_drone::perception::Powerline::UpdateOdometry().
Member Data Documentation
mutex_
std::shared_mutex iii_drone::utils::Timestamp::mutex_ mutable private
Mutex for thread safety.
Definition at line 71 of file timestamp.hpp.
Referenced by operator=(), operator=(), and Update().
stamp_
rclcpp::Time iii_drone::utils::Timestamp::stamp_ private
The ROS2 timestamp.
Definition at line 66 of file timestamp.hpp.
Referenced by operator=(), operator=(), Timestamp(), and Update().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/utils/timestamp.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/utils/timestamp.cpp