III-Drone: iii_drone::utils::drone_frame_broadcaster_node::DroneFrameBroadcasterConfigurator Class Reference
iii_drone::utils::drone_frame_broadcaster_node::DroneFrameBroadcasterConfigurator Class Reference
Class for handling parameters for HoughTransformer.
#include <drone_frame_broadcaster_node_configurator.hpp>
Public Member Functions
DroneFrameBroadcasterConfigurator (rclcpp::Node *node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Constructor.
DroneFrameBroadcasterConfigurator (rclcpp::Node *node, const rclcpp::QoS &qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Constructor.
const std::string drone_frame_id () const
Get the drone frame ID.
const std::string world_frame_id () const
Get the world frame ID.
Public Member Functions inherited from iii_drone::configuration::Configurator
Configurator (rclcpp::Node *node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Configurator (rclcpp::Node *node, const rclcpp::QoS &qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
~Configurator ()
template<typename T >
void DeclareParameter (const std::string &name)
rclcpp::Parameter GetParameter (const std::string &name) const
Get a parameter.
std::vector< rclcpp::Parameter > GetParameters (const std::vector< std::string > &names) const
Gets multiple parameters.
void SyncParameters (const std::vector< std::string > &names={})
Synchronizes parameters with the parameter server. Should never be necessary.
void PrintParameters () const
Prints all parameters to the console.
Private Member Functions
void declareNodeParameters ()
Declares the node specific parameters.
Additional Inherited Members
Static Public Member Functions inherited from iii_drone::configuration::Configurator
template<typename T >
static std::string GetParameterTypeString ()
Static function for getting string representation of a parameter type from template type.
Protected Attributes inherited from iii_drone::configuration::Configurator
rclcpp::Node * node_
Detailed Description
Class for handling parameters for HoughTransformer.
Definition at line 30 of file drone_frame_broadcaster_node_configurator.hpp.
Constructor & Destructor Documentation
DroneFrameBroadcasterConfigurator() [1/2]
DroneFrameBroadcasterConfigurator::DroneFrameBroadcasterConfigurator (rclcpp::Node * node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback = nullptr)
Constructor.
Parameters
node Reference to the handling node
after_parameter_change_callback Callback function called after successful parameter change, default is nullptr
Definition at line 14 of file drone_frame_broadcaster_node_configurator.cpp.
  : Configurator(
        node,
        after_parameter_change_callback
    ) {
    declareNodeParameters();
}
References declareNodeParameters().
DroneFrameBroadcasterConfigurator() [2/2]
DroneFrameBroadcasterConfigurator::DroneFrameBroadcasterConfigurator (rclcpp::Node * node, const rclcpp::QoS & qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback = nullptr)
Constructor.
Parameters
node Reference to the handling node
qos QoS profile for the parameter event subscription
after_parameter_change_callback Callback function called after successful parameter change, default is nullptr
Definition at line 26 of file drone_frame_broadcaster_node_configurator.cpp.
  : Configurator(
        node,
        qos,
        after_parameter_change_callback
    ) {
    declareNodeParameters();
}
References declareNodeParameters().
Member Function Documentation
declareNodeParameters()
void DroneFrameBroadcasterConfigurator::declareNodeParameters () private
Declares the node specific parameters.
Returns
void
Definition at line 52 of file drone_frame_broadcaster_node_configurator.cpp.
{
    DeclareParameter<std::string>("/tf/drone_frame_id");
    DeclareParameter<std::string>("/tf/world_frame_id");
}
References Configurator::DeclareParameter< std::string >().
Referenced by DroneFrameBroadcasterConfigurator(), and DroneFrameBroadcasterConfigurator().
drone_frame_id()
const std::string DroneFrameBroadcasterConfigurator::drone_frame_id () const
Get the drone frame ID.
Returns
Drone frame ID
Definition at line 40 of file drone_frame_broadcaster_node_configurator.cpp.
{
    return GetParameter("/tf/drone_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by iii_drone::utils::drone_frame_broadcaster_node::DroneFrameBroadcasterNode::odometryCallback().
world_frame_id()
const std::string DroneFrameBroadcasterConfigurator::world_frame_id () const
Get the world frame ID.
Returns
World frame ID
Definition at line 46 of file drone_frame_broadcaster_node_configurator.cpp.
{
    return GetParameter("/tf/world_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by iii_drone::utils::drone_frame_broadcaster_node::DroneFrameBroadcasterNode::odometryCallback().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/utils/drone_frame_broadcaster_node/drone_frame_broadcaster_node_configurator.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/utils/drone_frame_broadcaster_node/drone_frame_broadcaster_node_configurator.cpp