III-Drone: iii_drone::perception::Powerline Class Reference
iii_drone::perception::Powerline Class Reference
Class for estimation of the powerline cable poses. Attention: Requires the tf_buffer to be set after construction.
#include <powerline.hpp>
Classes
struct inter_line_positions_t
The inter line positions struct type.
Public Member Functions
Powerline (std::shared_ptr< PowerlineParameters > powerline_parameters)
Constructor.
const iii_drone::adapters::PowerlineAdapter ToAdapter (bool only_visible=false) const
Converts to a PowerlineAdapter.
const iii_drone::adapters::PointCloudAdapter ToPointCloudAdapter (bool only_visible=false) const
Converts to a PointCloudAdapter.
const std::vector< SingleLine > GetVisibleLines () const
Returns the lines that are currently in the sensor FOV.
int GetLinesCount () const
Returns the number of tracked lines.
iii_drone::types::point_t UpdateLine (const iii_drone::types::point_t &point)
Updates from a point. If match is found, runs the Kalman Filter update step for the matching line, otherwise creates a new line. Returns the projected point.
void UpdateDirection (const iii_drone::types::quaternion_t &pl_direction)
Updates the powerline direction and updates the projection plane.
void UpdateOdometry (const iii_drone::types::pose_t &drone_pose)
Updates the powerline from odometry.
void CleanupLines ()
Cleans up the lines that are not in the sensor FOV.
void ComputeInterLinePositions ()
Computes the inter line positions.
void Reset ()
Resets the powerline object.
std::shared_ptr< tf2_ros::Buffer > & tf_buffer ()
tf_buffer setter.
const rclcpp::Time stamp () const
Stamp getter.
const iii_drone::types::quaternion_t powerline_direction () const
Returns the powerline quaternion direction.
const iii_drone::types::plane_t projection_plane () const
Returns the powerline projection plane.
const iii_drone::types::pose_t drone_pose () const
Returns the drone quaternion orientation.
Private Member Functions
void updateProjectionPlane ()
Updates the projection plane.
int findMatchingLine (const iii_drone::types::point_t &point) const
Finds the matching line for a point.
void registerNewLine (const iii_drone::types::point_t &point)
Registers a new line.
const iii_drone::types::point_t projectPoint (const iii_drone::types::point_t &point) const
Projects a point onto the powerline projection plane.
void predictLines ()
Runs the Kalman Filter predict step for all lines.
Private Attributes
iii_drone::utils::Timestamp stamp_
Time stamp for latest change.
std::shared_ptr< PowerlineParameters > parameters_
The powerline parameters.
std::shared_ptr< tf2_ros::Buffer > tf_buffer_
The tf buffer.
std::vector< SingleLine > lines_
The currently tracked lines.
std::vector< inter_line_positions_t > inter_line_positions_
The inter line positions.
std::shared_mutex lines_mutex_
Mutex for protection of lines and inter line positions.
iii_drone::utils::History< iii_drone::types::quaternion_t > pl_dir_history_
The powerline direction quaternion history.
iii_drone::utils::History< iii_drone::types::pose_t > drone_pose_history_
The drone pose history.
iii_drone::utils::Atomic< iii_drone::types::plane_t > projection_plane_
The powerline projection plane.
iii_drone::utils::Atomic< int > id_cnt_ = 0
The counter for unique line ids.
Detailed Description
Class for estimation of the powerline cable poses. Attention: Requires the tf_buffer to be set after construction.
Definition at line 67 of file powerline.hpp.
Constructor & Destructor Documentation
Powerline()
Powerline::Powerline (std::shared_ptr< PowerlineParameters > powerline_parameters)
Constructor.
Parameters
powerline_parameters Pointer to the powerline parameters.
Definition at line 15 of file powerline.cpp.
    : parameters_(powerline_parameters),
    pl_dir_history_(1),
    drone_pose_history_(2) {
    Reset();
}
References Reset().
Member Function Documentation
CleanupLines()
void Powerline::CleanupLines ()
Cleans up the lines that are not in the sensor FOV.
Definition at line 216 of file powerline.cpp.
{
    std::unique_lock<std::shared_mutex> lines_lock(lines_mutex_);
    lines_.erase(
        std::remove_if(
            lines_.begin(),
            lines_.end(),
            [](SingleLine& line) {
                return !line.IsAlive();
            }
        ),
        lines_.end()
    );
    std::vector<inter_line_positions_t> new_pos_vec;
    for (unsigned int i = 0; i < inter_line_positions_.size(); i++) {
        bool line_1_found = false;
        bool line_2_found = false;
        for (unsigned int j = 0; j < lines_.size(); j++) {
            if (lines_[j].id() == inter_line_positions_[i].line_id_1) {
                line_1_found = true;
            } else if (lines_[j].id() == inter_line_positions_[i].line_id_2) {
                line_2_found = true;
            }
            if (line_1_found && line_2_found) {
                new_pos_vec.push_back(inter_line_positions_[i]);
                break;
            }
        }
    }
    inter_line_positions_ = new_pos_vec;
    stamp_.Update();
}
References inter_line_positions_, lines_, lines_mutex_, stamp_, and iii_drone::utils::Timestamp::Update().
Referenced by iii_drone::perception::pl_mapper_node::PowerlineMapperNode::mmWaveCallback().
ComputeInterLinePositions()
void Powerline::ComputeInterLinePositions ()
Computes the inter line positions.
Definition at line 267 of file powerline.cpp.
{
    quaternion_t direction = pl_dir_history_[0];
    quaternion_t q_pl_to_drone = quatInv(direction);
    rotation_matrix_t R_pl_to_drone = quatToMat(q_pl_to_drone);
    std::unique_lock<std::shared_mutex> lines_lock(lines_mutex_);
    if (lines_.empty()) {
        return;
    }
    for (unsigned int i = 0; i < lines_.size()-1; i++) {
        bool in_fov = lines_[i].IsInFOV();
        if (!in_fov) {
            continue;
        }
        for (unsigned int j = i+1; j < lines_.size(); j++) {
            if (!lines_[j].IsInFOV()) {
                continue;
            }
            bool ilp_found = false;
            for (unsigned int k = 0; k < inter_line_positions_.size(); k++) {
                if (inter_line_positions_[k].line_id_1 == lines_[i].id() && inter_line_positions_[k].line_id_2 == lines_[j].id()) {
                    vector_t vec = lines_[j].position() - lines_[i].position();
                    vec = R_pl_to_drone * vec;
                    inter_line_positions_[k].inter_line_position_window.push_back(vec);
                    while(inter_line_positions_[k].inter_line_position_window.size() > (unsigned int)parameters_->inter_pos_window_size()) {
                        inter_line_positions_[k].inter_line_position_window.erase(inter_line_positions_[k].inter_line_position_window.begin());
                    }
                    ilp_found = true;
                    break;
                } else if (inter_line_positions_[k].line_id_1 == lines_[j].id() && inter_line_positions_[k].line_id_2 == lines_[i].id()) {
                    vector_t vec = lines_[i].position() - lines_[j].position();
                    vec = R_pl_to_drone * vec;
                    inter_line_positions_[k].inter_line_position_window.push_back(vec);
                    while(inter_line_positions_[k].inter_line_position_window.size() > (unsigned int)parameters_->inter_pos_window_size()) {
                        inter_line_positions_[k].inter_line_position_window.erase(inter_line_positions_[k].inter_line_position_window.begin());
                    }
                    ilp_found = true;
                    break;
                }
            }
            if (!ilp_found) {
                throw std::runtime_error("Inter line position not found.");
            }
        }
    }
    stamp_.Update();
}
References inter_line_positions_, lines_, lines_mutex_, parameters_, pl_dir_history_, iii_drone::math::quatInv(), iii_drone::math::quatToMat(), stamp_, and iii_drone::utils::Timestamp::Update().
Referenced by iii_drone::perception::pl_mapper_node::PowerlineMapperNode::mmWaveCallback().
drone_pose()
const pose_t Powerline::drone_pose () const
Returns the drone quaternion orientation.
Returns
The drone quaternion orientation.
Definition at line 407 of file powerline.cpp.
{
    if (drone_pose_history_.empty()) {
        pose_t pose;
        pose.position = point_t::Zero();
        pose.orientation = quaternion_t::Identity();
        return pose;
    } else {
        return drone_pose_history_[0];
    }
}
References drone_pose_history_, iii_drone::utils::History< T >::empty(), iii_drone::types::pose_t::orientation, and iii_drone::types::pose_t::position.
Referenced by predictLines(), and UpdateOdometry().
findMatchingLine()
int Powerline::findMatchingLine (const iii_drone::types::point_t & point) const private
Finds the matching line for a point.
Parameters
point The point to find the matching line for.
Returns
The id of the matching line.
Definition at line 441 of file powerline.cpp.
{
    std::shared_lock<std::shared_mutex> lock(lines_mutex_);
    int best_idx = -1;
    float best_dist = std::numeric_limits<float>::infinity();
    for (unsigned int i = 0; i < lines_.size(); i++) {
        vector_t vec = (vector_t)(point - lines_[i].position());
        float dist = sqrt(vec.dot(vec));
        if (dist < parameters_->matching_line_max_dist() && dist < best_dist) {
            best_dist = dist;
            best_idx = i;
        }
    }
    return best_idx;
}
References lines_, and lines_mutex_.
Referenced by UpdateLine().
GetLinesCount()
int Powerline::GetLinesCount () const
Returns the number of tracked lines.
Returns
The number of tracked lines.
Definition at line 114 of file powerline.cpp.
{
    std::shared_lock<std::shared_mutex> lock(lines_mutex_);
    return lines_.size();
}
References lines_, and lines_mutex_.
GetVisibleLines()
const std::vector< SingleLine > Powerline::GetVisibleLines () const
Returns the lines that are currently in the sensor FOV.
Returns
The lines that are currently in the sensor FOV.
Definition at line 94 of file powerline.cpp.
{
    std::shared_lock<std::shared_mutex> lock(lines_mutex_);
    std::vector<SingleLine> ret_lines;
    for (unsigned int i = 0; i < lines_.size(); i++) {
        if (lines_[i].IsVisible()) {
            ret_lines.push_back(SingleLine(lines_[i]));
        }
    }
    return ret_lines;
}
References lines_, and lines_mutex_.
powerline_direction()
const quaternion_t Powerline::powerline_direction () const
Returns the powerline quaternion direction.
Returns
The powerline quaternion direction.
Definition at line 387 of file powerline.cpp.
{
    if (pl_dir_history_.empty()) {
        return quaternion_t::Identity();
    } else {
        return pl_dir_history_[0];
    }
}
References iii_drone::utils::History< T >::empty(), and pl_dir_history_.
predictLines()
void Powerline::predictLines () private
Runs the Kalman Filter predict step for all lines.
Definition at line 508 of file powerline.cpp.
{
    vector_t delta_position;
    quaternion_t delta_quat, q_drone_to_pl;
    pose_t drone_pose = drone_pose_history_[0];
    pose_t last_drone_pose = drone_pose_history_[-1];
    rotation_matrix_t W_R_D1 = quatToMat(last_drone_pose.orientation);
    rotation_matrix_t W_R_D2 = quatToMat(drone_pose.orientation);
    rotation_matrix_t D2_R_W = W_R_D2.transpose();
    delta_quat = matToQuat(D2_R_W*W_R_D1);
    delta_position = drone_pose.position - last_drone_pose.position;
    delta_position = D2_R_W * delta_position;
    q_drone_to_pl = pl_dir_history_[0];
    rotation_matrix_t R_drone_to_pl = quatToMat(q_drone_to_pl);
    plane_t projection_plane = projection_plane_;
    {
        std::unique_lock<std::shared_mutex> lock(lines_mutex_);
        std::vector<unsigned int> non_visible_line_indices;
        for (unsigned int i = 0; i < lines_.size(); i++) {
            if (lines_[i].IsInFOV()) {
                lines_[i].Predict(delta_position, delta_quat, projection_plane);
            } else {
                non_visible_line_indices.push_back(i);
            }
        }
        for (unsigned int i = 0; i < non_visible_line_indices.size(); i++) {
            unsigned int idx = non_visible_line_indices[i];
            std::vector<point_t> expected_positions;
            for (unsigned int j = 0; j < inter_line_positions_.size(); j++) {
                if (inter_line_positions_[j].inter_line_position_window.size() < 1)
                    continue;
                int id1 = inter_line_positions_[j].line_id_1;
                int id2 = inter_line_positions_[j].line_id_2;
                bool id1_match = id1 == lines_[idx].id();
                bool id2_match = id2 == lines_[idx].id();
                if (id1_match || id2_match) {
                    int ref_line_id = id1_match ? id2 : id1;
                    point_t reference_line_point;
                    bool ref_line_point_found = false;
                    for (unsigned int k = 0; k < lines_.size(); k++) {
                        if (k == idx)
                            continue;
                        if (lines_[k].id() == ref_line_id && lines_[k].IsInFOV()) {
                            reference_line_point = lines_[k].position();
                            ref_line_point_found = true;
                            break;
                        }
                    }
                    if (ref_line_point_found) {
                        vector_t mean_vec = inter_line_positions_[j].inter_line_position_window[0];
                        for (unsigned int k = 1; k < inter_line_positions_[j].inter_line_position_window.size(); k++) {
                            mean_vec += inter_line_positions_[j].inter_line_position_window[k];
                        }
                        mean_vec /= inter_line_positions_[j].inter_line_position_window.size();
                        float mult = id1_match ? -1. : 1.;
                        mean_vec *= mult;
                        mean_vec = R_drone_to_pl * mean_vec;
                        point_t expected_pos = reference_line_point + mean_vec;
                        expected_positions.push_back(expected_pos);
                    }
                }
            }
            if (expected_positions.size() > 0) {
                point_t mean_pos = expected_positions[0];
                for (unsigned int j = 1; j < expected_positions.size(); j++) {
                    mean_pos += expected_positions[j];
                }
                mean_pos /= expected_positions.size();
                lines_[idx].SetPosition(mean_pos);
            } else {
                lines_[idx].Predict(delta_position, delta_quat, projection_plane);
            }
        }
    }
}
References drone_pose(), drone_pose_history_, inter_line_positions_, lines_, lines_mutex_, iii_drone::math::matToQuat(), iii_drone::types::pose_t::orientation, pl_dir_history_, iii_drone::types::pose_t::position, projection_plane(), projection_plane_, and iii_drone::math::quatToMat().
Referenced by UpdateOdometry().
projection_plane()
const plane_t Powerline::projection_plane () const
Returns the powerline projection plane.
Returns
The powerline projection plane.
Definition at line 401 of file powerline.cpp.
{
    return projection_plane_;
}
References projection_plane_.
Referenced by predictLines(), and ToAdapter().
projectPoint()
const point_t Powerline::projectPoint (const iii_drone::types::point_t & point) const private
Projects a point onto the powerline projection plane.
Parameters
point The point to project.
Returns
The projected point.
Definition at line 498 of file powerline.cpp.
{
    point_t projected_point;
    projected_point = projectPointOnPlane(point, projection_plane_);
    return projected_point;
}
References projection_plane_, and iii_drone::math::projectPointOnPlane().
Referenced by UpdateLine().
registerNewLine()
void Powerline::registerNewLine (const iii_drone::types::point_t & point) private
Registers a new line.
Parameters
point The point to register the new line from.
Definition at line 466 of file powerline.cpp.
{
    quaternion_t pl_quat = pl_dir_history_[0];
    int new_id = id_cnt_ + 1;
    id_cnt_ = new_id;
    auto new_line = SingleLine(
        new_id,
        point,
        pl_quat,
        tf_buffer_,
        parameters_
    );
    std::unique_lock<std::shared_mutex> lines_lock(lines_mutex_);
    for (unsigned int i = 0; i < lines_.size(); i++) {
        inter_line_positions_t ilp;
        ilp.line_id_1 = lines_[i].id();
        ilp.line_id_2 = new_id;
        inter_line_positions_.push_back(ilp);
    }
    lines_.push_back(new_line);
}
References id_cnt_, inter_line_positions_, iii_drone::perception::Powerline::inter_line_positions_t::line_id_1, iii_drone::perception::Powerline::inter_line_positions_t::line_id_2, lines_, lines_mutex_, parameters_, pl_dir_history_, and tf_buffer_.
Referenced by UpdateLine().
Reset()
void Powerline::Reset ()
Resets the powerline object.
Definition at line 352 of file powerline.cpp.
                      {
    {
        std::unique_lock<std::shared_mutex> lock(lines_mutex_);
        lines_.clear();
        inter_line_positions_.clear();
    }
    pl_dir_history_.clear();
    drone_pose_history_.clear();
    projection_plane_ = createPlane(point_t(0, 0, 0), vector_t(1, 0, 0));
    id_cnt_ = 0;
    stamp_.Update();
}
References iii_drone::utils::History< T >::clear(), iii_drone::types::createPlane(), drone_pose_history_, id_cnt_, inter_line_positions_, lines_, lines_mutex_, pl_dir_history_, projection_plane_, stamp_, and iii_drone::utils::Timestamp::Update().
Referenced by Powerline().
stamp()
const rclcpp::Time Powerline::stamp () const
Stamp getter.
Definition at line 381 of file powerline.cpp.
{
    return stamp_;
}
References stamp_.
Referenced by iii_drone::perception::pl_mapper_node::PowerlineMapperNode::publishPoints().
tf_buffer()
std::shared_ptr< tf2_ros::Buffer > & Powerline::tf_buffer ()
tf_buffer setter.
Definition at line 375 of file powerline.cpp.
{
    return tf_buffer_;
}
References tf_buffer_.
Referenced by iii_drone::perception::pl_mapper_node::PowerlineMapperNode::PowerlineMapperNode().
ToAdapter()
const iii_drone::adapters::PowerlineAdapter Powerline::ToAdapter (bool only_visible = false) const
Converts to a PowerlineAdapter.
Parameters
only_visible Whether to only return the visible lines, default false.
Returns
The PowerlineAdapter.
Definition at line 24 of file powerline.cpp.
{
    std::shared_lock<std::shared_mutex> lines_lock(lines_mutex_);
    std::vector<iii_drone::adapters::SingleLineAdapter> line_adapters;
    for (unsigned int i = 0; i < lines_.size(); i++) {
        if (only_visible && !lines_[i].IsVisible()) {
            continue;
        }
        line_adapters.push_back(lines_[i].ToAdapter());
    }
    lines_lock.unlock();
    plane_t projection_plane = projection_plane_;
    iii_drone::adapters::PowerlineAdapter adapter(
        stamp_,
        line_adapters,
        projection_plane
    );
    return adapter;
}
References lines_, lines_mutex_, projection_plane(), projection_plane_, stamp_, and ToAdapter().
Referenced by iii_drone::perception::pl_mapper_node::PowerlineMapperNode::publishPowerline(), and ToAdapter().
ToPointCloudAdapter()
const iii_drone::adapters::PointCloudAdapter Powerline::ToPointCloudAdapter (bool only_visible = false) const
Converts to a PointCloudAdapter.
Parameters
only_visible Whether to only return the visible lines, default false.
Returns
The PointCloudAdapter.
Definition at line 56 of file powerline.cpp.
{
    std::shared_lock<std::shared_mutex> lines_lock(lines_mutex_);
    std::vector<point_t> points;
    if (!only_visible) {
        for (unsigned int i = 0; i < lines_.size(); i++) {
            points.push_back(lines_[i].position());
        }
    } else {
        for (unsigned int i = 0; i < lines_.size(); i++) {
            if (lines_[i].IsVisible()) {
                points.push_back(lines_[i].position());
            }
        }
    }
    lines_lock.unlock();
    iii_drone::adapters::PointCloudAdapter adapter(
        stamp_,
        parameters_->drone_frame_id(),
        points
    );
    return adapter;
}
References lines_, lines_mutex_, parameters_, and stamp_.
Referenced by iii_drone::perception::pl_mapper_node::PowerlineMapperNode::publishPowerline().
UpdateDirection()
void Powerline::UpdateDirection (const iii_drone::types::quaternion_t & pl_direction)
Updates the powerline direction and updates the projection plane.
Parameters
pl_direction The powerline direction.
Definition at line 167 of file powerline.cpp.
{
    pl_dir_history_ = pl_direction;
    {
        std::unique_lock<std::shared_mutex> lock(lines_mutex_);
        for (unsigned int i = 0; i < lines_.size(); i++) {
            lines_[i].SetDirection(pl_direction);
        }
    }
    if (!drone_pose_history_.full()) {
        return;
    }
    updateProjectionPlane();
    stamp_.Update();
}
References drone_pose_history_, iii_drone::utils::History< T >::full(), lines_, lines_mutex_, pl_dir_history_, stamp_, iii_drone::utils::Timestamp::Update(), and updateProjectionPlane().
Referenced by iii_drone::perception::pl_mapper_node::PowerlineMapperNode::plDirectionCallback().
UpdateLine()
point_t Powerline::UpdateLine (const iii_drone::types::point_t & point)
Updates from a point. If match is found, runs the Kalman Filter update step for the matching line, otherwise creates a new line. Returns the projected point.
Parameters
point The point to update from.
Returns
The projected point.
Definition at line 122 of file powerline.cpp.
{
    if (!pl_dir_history_.full() || !drone_pose_history_.full()) {
        return point;
    }
    point_t projected_point = projectPoint(point);
    int match_index = findMatchingLine(projected_point);
    int line_count;
    {
        std::shared_lock<std::shared_mutex> shared_lines_lock(lines_mutex_);
        line_count = lines_.size();
    }
    if (match_index == -1 && line_count >= parameters_->max_lines()) {
        return projected_point;
    } else if (match_index == -1) {
        registerNewLine(projected_point);
    } else {
        std::unique_lock<std::shared_mutex> unique_lines_lock(lines_mutex_);
        lines_[match_index].Update(projected_point);
    }
    stamp_.Update();
    return projected_point;
}
References drone_pose_history_, findMatchingLine(), iii_drone::utils::History< T >::full(), lines_, lines_mutex_, parameters_, pl_dir_history_, projectPoint(), registerNewLine(), stamp_, and iii_drone::utils::Timestamp::Update().
Referenced by iii_drone::perception::pl_mapper_node::PowerlineMapperNode::mmWaveCallback().
UpdateOdometry()
void Powerline::UpdateOdometry (const iii_drone::types::pose_t & drone_pose)
Updates the powerline from odometry.
Parameters
drone_pose The drone pose.
Definition at line 195 of file powerline.cpp.
{
    drone_pose_history_ = drone_pose;
    if (!drone_pose_history_.full()) {
        return;
    }
    if (!pl_dir_history_.full()) {
        return;
    }
    predictLines();
    stamp_.Update();
}
References drone_pose(), drone_pose_history_, iii_drone::utils::History< T >::full(), pl_dir_history_, predictLines(), stamp_, and iii_drone::utils::Timestamp::Update().
Referenced by iii_drone::perception::pl_mapper_node::PowerlineMapperNode::odometryCallback().
updateProjectionPlane()
void Powerline::updateProjectionPlane () private
Updates the projection plane.
Definition at line 425 of file powerline.cpp.
{
    quaternion_t direction_tmp = pl_dir_history_[0];
    point_t plane_p(0, 0, 0);
    vector_t unit_x(1, 0, 0);
    euler_angles_t eul = quatToEul(direction_tmp);
    vector_t plane_normal = rotateVector(eulToMat(eul), unit_x);
    projection_plane_ = createPlane(plane_p, plane_normal);
}
References iii_drone::types::createPlane(), iii_drone::math::eulToMat(), pl_dir_history_, projection_plane_, iii_drone::math::quatToEul(), and iii_drone::math::rotateVector().
Referenced by UpdateDirection().
Member Data Documentation
drone_pose_history_
iii_drone::utils::History<iii_drone::types::pose_t> iii_drone::perception::Powerline::drone_pose_history_ private
The drone pose history.
Definition at line 232 of file powerline.hpp.
Referenced by drone_pose(), predictLines(), Reset(), UpdateDirection(), UpdateLine(), and UpdateOdometry().
id_cnt_
iii_drone::utils::Atomic<int> iii_drone::perception::Powerline::id_cnt_ = 0 private
The counter for unique line ids.
Definition at line 242 of file powerline.hpp.
Referenced by registerNewLine(), and Reset().
inter_line_positions_
std::vector<inter_line_positions_t> iii_drone::perception::Powerline::inter_line_positions_ private
The inter line positions.
Definition at line 217 of file powerline.hpp.
Referenced by CleanupLines(), ComputeInterLinePositions(), predictLines(), registerNewLine(), and Reset().
lines_
std::vector<SingleLine> iii_drone::perception::Powerline::lines_ private
The currently tracked lines.
Definition at line 212 of file powerline.hpp.
Referenced by CleanupLines(), ComputeInterLinePositions(), findMatchingLine(), GetLinesCount(), GetVisibleLines(), predictLines(), registerNewLine(), Reset(), ToAdapter(), ToPointCloudAdapter(), UpdateDirection(), and UpdateLine().
lines_mutex_
std::shared_mutex iii_drone::perception::Powerline::lines_mutex_ mutable private
Mutex for protection of lines and inter line positions.
Definition at line 222 of file powerline.hpp.
Referenced by CleanupLines(), ComputeInterLinePositions(), findMatchingLine(), GetLinesCount(), GetVisibleLines(), predictLines(), registerNewLine(), Reset(), ToAdapter(), ToPointCloudAdapter(), UpdateDirection(), and UpdateLine().
parameters_
std::shared_ptr<PowerlineParameters> iii_drone::perception::Powerline::parameters_ private
The powerline parameters.
Definition at line 187 of file powerline.hpp.
Referenced by ComputeInterLinePositions(), registerNewLine(), ToPointCloudAdapter(), and UpdateLine().
pl_dir_history_
iii_drone::utils::History<iii_drone::types::quaternion_t> iii_drone::perception::Powerline::pl_dir_history_ private
The powerline direction quaternion history.
Definition at line 227 of file powerline.hpp.
Referenced by ComputeInterLinePositions(), powerline_direction(), predictLines(), registerNewLine(), Reset(), UpdateDirection(), UpdateLine(), UpdateOdometry(), and updateProjectionPlane().
projection_plane_
iii_drone::utils::Atomic<iii_drone::types::plane_t> iii_drone::perception::Powerline::projection_plane_ private
The powerline projection plane.
Definition at line 237 of file powerline.hpp.
Referenced by predictLines(), projection_plane(), projectPoint(), Reset(), ToAdapter(), and updateProjectionPlane().
stamp_
iii_drone::utils::Timestamp iii_drone::perception::Powerline::stamp_ private
Time stamp for latest change.
Definition at line 182 of file powerline.hpp.
Referenced by CleanupLines(), ComputeInterLinePositions(), Reset(), stamp(), ToAdapter(), ToPointCloudAdapter(), UpdateDirection(), UpdateLine(), and UpdateOdometry().
tf_buffer_
std::shared_ptr<tf2_ros::Buffer> iii_drone::perception::Powerline::tf_buffer_ private
The tf buffer.
Definition at line 192 of file powerline.hpp.
Referenced by registerNewLine(), and tf_buffer().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/perception/powerline.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/perception/powerline.cpp