III-Drone: iii_drone::adapters::px4::TrajectorySetpointAdapter Class Reference
iii_drone::adapters::px4::TrajectorySetpointAdapter Class Reference
PX4 trajectory setpoint adapter class.
#include <trajectory_setpoint_adapter.hpp>
Public Member Functions
TrajectorySetpointAdapter ()
Default constructor.
TrajectorySetpointAdapter (const rclcpp::Time &stamp)
Constructor.
TrajectorySetpointAdapter (const iii_drone::control::Reference &reference)
Constructor from iii::control::Reference.
TrajectorySetpointAdapter (const iii_drone::adapters::ReferenceAdapter &reference_adapter)
Constructor from iii_drone::adapters::ReferenceAdapter.
TrajectorySetpointAdapter (const iii_drone::control::State &state)
Constructor from iii_drone::control::State.
void SetOnlyPosition ()
px4_msgs::msg::TrajectorySetpoint ToMsg () const
Convert the object to a PX4 trajectory setpoint message.
const rclcpp::Time & stamp () const
Timestamp getter.
const iii_drone::types::point_t & position () const
Position getter.
const iii_drone::types::vector_t & velocity () const
Velocity getter.
const iii_drone::types::vector_t & acceleration () const
Acceleration getter.
const double & yaw () const
Yaw getter.
const double & yawspeed () const
Yaw speed getter.
Private Member Functions
void init (const rclcpp::Time &stamp, const iii_drone::types::point_t &position, const iii_drone::types::vector_t &velocity, const iii_drone::types::vector_t &acceleration, const double &yaw, const double &yawspeed)
Initialize the object.
Private Attributes
rclcpp::Time stamp_
ROS2 time stamp.
iii_drone::types::point_t position_
Setpoint position.
iii_drone::types::vector_t velocity_
Setpoint velocity.
iii_drone::types::vector_t acceleration_
Setpoint acceleration.
double yaw_
Setpoint yaw.
double yawspeed_
Setpoint yaw speed.
Detailed Description
PX4 trajectory setpoint adapter class.
Definition at line 48 of file trajectory_setpoint_adapter.hpp.
Constructor & Destructor Documentation
TrajectorySetpointAdapter() [1/5]
TrajectorySetpointAdapter::TrajectorySetpointAdapter ()
Default constructor.
Definition at line 17 of file trajectory_setpoint_adapter.cpp.
{
    init(
        rclcpp::Time(0, 0, RCL_ROS_TIME),
        {NAN, NAN, NAN},
        {NAN, NAN, NAN},
        {NAN, NAN, NAN},
        NAN,
        NAN
    );
}
References init().
TrajectorySetpointAdapter() [2/5]
TrajectorySetpointAdapter::TrajectorySetpointAdapter (const rclcpp::Time & stamp)
Constructor.
Parameters
stamp ROS2 time stamp
Definition at line 30 of file trajectory_setpoint_adapter.cpp.
{
    init(
        stamp,
        {NAN, NAN, NAN},
        {NAN, NAN, NAN},
        {NAN, NAN, NAN},
        NAN,
        NAN
    );
}
References init(), and stamp().
TrajectorySetpointAdapter() [3/5]
TrajectorySetpointAdapter::TrajectorySetpointAdapter (const iii_drone::control::Reference & reference)
Constructor from iii::control::Reference.
Parameters
reference iii::control::Reference
Definition at line 43 of file trajectory_setpoint_adapter.cpp.
{
    init(
        reference.stamp(),
        reference.position(),
        reference.velocity(),
        reference.acceleration(),
        reference.yaw(),
        reference.yaw_rate()
    );
}
References iii_drone::control::Reference::acceleration(), init(), iii_drone::control::Reference::position(), iii_drone::control::Reference::stamp(), iii_drone::control::Reference::velocity(), iii_drone::control::Reference::yaw(), and iii_drone::control::Reference::yaw_rate().
TrajectorySetpointAdapter() [4/5]
TrajectorySetpointAdapter::TrajectorySetpointAdapter (const iii_drone::adapters::ReferenceAdapter & reference_adapter)
Constructor from iii_drone::adapters::ReferenceAdapter.
Parameters
reference_adapter iii_drone::adapters::ReferenceAdapter
Definition at line 56 of file trajectory_setpoint_adapter.cpp.
{
    Reference reference = reference_adapter.reference();
    init(
        reference.stamp(),
        reference.position(),
        reference.velocity(),
        reference.acceleration(),
        reference.yaw(),
        reference.yaw_rate()
    );
}
References iii_drone::control::Reference::acceleration(), init(), iii_drone::control::Reference::position(), iii_drone::adapters::ReferenceAdapter::reference(), iii_drone::control::Reference::stamp(), iii_drone::control::Reference::velocity(), iii_drone::control::Reference::yaw(), and iii_drone::control::Reference::yaw_rate().
TrajectorySetpointAdapter() [5/5]
TrajectorySetpointAdapter::TrajectorySetpointAdapter (const iii_drone::control::State & state)
Constructor from iii_drone::control::State.
Parameters
state iii_drone::control::State
Definition at line 71 of file trajectory_setpoint_adapter.cpp.
{
    quaternion_t q = state.quaternion();
    euler_angles_t euler = quatToEul(q);
    init(
        state.stamp(),
        state.position(),
        state.velocity(),
        {NAN, NAN, NAN},
        euler[2],
        state.angular_velocity()[2] // Fix this in the future
    );
}
References iii_drone::control::State::angular_velocity(), init(), iii_drone::control::State::position(), iii_drone::control::State::quaternion(), iii_drone::math::quatToEul(), iii_drone::control::State::stamp(), and iii_drone::control::State::velocity().
Member Function Documentation
acceleration()
const vector_t & TrajectorySetpointAdapter::acceleration () const
Acceleration getter.
Returns
Setpoint acceleration
Definition at line 133 of file trajectory_setpoint_adapter.cpp.
{
    return acceleration_;
}
References acceleration_.
Referenced by init().
init()
void TrajectorySetpointAdapter::init (const rclcpp::Time & stamp, const iii_drone::types::point_t & position, const iii_drone::types::vector_t & velocity, const iii_drone::types::vector_t & acceleration, const double & yaw, const double & yawspeed) private
Initialize the object.
Parameters
stamp ROS2 time stamp
position Setpoint position
velocity Setpoint velocity
acceleration Setpoint acceleration
yaw Setpoint yaw
yawspeed Setpoint yaw speed
Returns
void
Definition at line 145 of file trajectory_setpoint_adapter.cpp.
  {
    stamp_ = stamp;
    position_ = position;
    velocity_ = velocity;
    acceleration_ = acceleration;
    yaw_ = yaw;
    yawspeed_ = yawspeed;
}
References acceleration(), acceleration_, position(), position_, stamp(), stamp_, velocity(), velocity_, yaw(), yaw_, yawspeed(), and yawspeed_.
Referenced by TrajectorySetpointAdapter(), TrajectorySetpointAdapter(), TrajectorySetpointAdapter(), TrajectorySetpointAdapter(), and TrajectorySetpointAdapter().
position()
const point_t & TrajectorySetpointAdapter::position () const
Position getter.
Returns
Setpoint position
Definition at line 125 of file trajectory_setpoint_adapter.cpp.
{
    return position_;
}
References position_.
Referenced by init().
SetOnlyPosition()
void TrajectorySetpointAdapter::SetOnlyPosition ()
Definition at line 87 of file trajectory_setpoint_adapter.cpp.
{
    velocity_ = {NAN, NAN, NAN};
    acceleration_ = {NAN, NAN, NAN};
    yawspeed_ = NAN;
}
References acceleration_, velocity_, and yawspeed_.
stamp()
const rclcpp::Time & TrajectorySetpointAdapter::stamp () const
Timestamp getter.
Returns
ROS2 time stamp
Definition at line 121 of file trajectory_setpoint_adapter.cpp.
{
    return stamp_;
}
References stamp_.
Referenced by init(), and TrajectorySetpointAdapter().
ToMsg()
px4_msgs::msg::TrajectorySetpoint TrajectorySetpointAdapter::ToMsg () const
Convert the object to a PX4 trajectory setpoint message.
Returns
PX4 trajectory setpoint message
Definition at line 94 of file trajectory_setpoint_adapter.cpp.
{
    px4_msgs::msg::TrajectorySetpoint trajectory_setpoint_msg;
    trajectory_setpoint_msg.timestamp = stamp_.nanoseconds() / 1000;
    for (int i = 0; i < 3; i++) {
        double multiplier = 1.0;
        if (i == 1 || i == 2) {
            multiplier = -1.0;
        }
        trajectory_setpoint_msg.position[i] = multiplier*position_[i];
        trajectory_setpoint_msg.velocity[i] = multiplier*velocity_[i];
        trajectory_setpoint_msg.acceleration[i] = multiplier*acceleration_[i];
    }
    trajectory_setpoint_msg.yaw = -yaw_;
    trajectory_setpoint_msg.yawspeed = -yawspeed_;
    return trajectory_setpoint_msg;
}
References acceleration_, position_, stamp_, velocity_, yaw_, and yawspeed_.
velocity()
const vector_t & TrajectorySetpointAdapter::velocity () const
Velocity getter.
Returns
Setpoint velocity
Definition at line 129 of file trajectory_setpoint_adapter.cpp.
{
    return velocity_;
}
References velocity_.
Referenced by init().
yaw()
const double & TrajectorySetpointAdapter::yaw () const
Yaw getter.
Returns
Setpoint yaw
Definition at line 137 of file trajectory_setpoint_adapter.cpp.
{
    return yaw_;
}
References yaw_.
Referenced by init().
yawspeed()
const double & TrajectorySetpointAdapter::yawspeed () const
Yaw speed getter.
Returns
Setpoint yaw speed
Definition at line 141 of file trajectory_setpoint_adapter.cpp.
{
    return yawspeed_;
}
References yawspeed_.
Referenced by init().
Member Data Documentation
acceleration_
iii_drone::types::vector_t iii_drone::adapters::px4::TrajectorySetpointAdapter::acceleration_ private
Setpoint acceleration.
Definition at line 179 of file trajectory_setpoint_adapter.hpp.
Referenced by acceleration(), init(), SetOnlyPosition(), and ToMsg().
position_
iii_drone::types::point_t iii_drone::adapters::px4::TrajectorySetpointAdapter::position_ private
Setpoint position.
Definition at line 169 of file trajectory_setpoint_adapter.hpp.
Referenced by init(), position(), and ToMsg().
stamp_
rclcpp::Time iii_drone::adapters::px4::TrajectorySetpointAdapter::stamp_ private
ROS2 time stamp.
Definition at line 164 of file trajectory_setpoint_adapter.hpp.
Referenced by init(), stamp(), and ToMsg().
velocity_
iii_drone::types::vector_t iii_drone::adapters::px4::TrajectorySetpointAdapter::velocity_ private
Setpoint velocity.
Definition at line 174 of file trajectory_setpoint_adapter.hpp.
Referenced by init(), SetOnlyPosition(), ToMsg(), and velocity().
yaw_
double iii_drone::adapters::px4::TrajectorySetpointAdapter::yaw_ private
Setpoint yaw.
Definition at line 184 of file trajectory_setpoint_adapter.hpp.
Referenced by init(), ToMsg(), and yaw().
yawspeed_
double iii_drone::adapters::px4::TrajectorySetpointAdapter::yawspeed_ private
Setpoint yaw speed.
Definition at line 189 of file trajectory_setpoint_adapter.hpp.
Referenced by init(), SetOnlyPosition(), ToMsg(), and yawspeed().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/adapters/px4/trajectory_setpoint_adapter.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/adapters/px4/trajectory_setpoint_adapter.cpp