III-Drone: iii_drone::perception::PowerlineDirection Class Reference
iii_drone::perception::PowerlineDirection Class Reference
Class for computing the powerline direction and converting to ROS2 message, as well as Kalman Filtering.
#include <powerline_direction.hpp>
Classes
struct kf_est_t
Struct for holding Kalman filtering data.
Public Member Functions
PowerlineDirection (std::shared_ptr< PowerlineDirectionParameters > parameters)
Default constructor.
~PowerlineDirection ()
Destructor.
const geometry_msgs::msg::PoseStamped ToPoseStampedMsg (const std::string &drone_frame_id) const
Converts to pose stamped message.
const geometry_msgs::msg::QuaternionStamped ToQuaternionStampedMsg (const std::string &drone_frame_id) const
Converts to quaternion stamped message.
void Update (float pl_yaw)
Runs the Kalman Filter update step from an observed yaw angle.
void Predict (const iii_drone::types::quaternion_t &drone_quat)
Runs the Kalman Filter predict step from a drone quaternion.
void UpdatePowerlineAdapter (const iii_drone_interfaces::msg::Powerline::SharedPtr msg)
Updates the PowerlineAdapter object.
const iii_drone::types::quaternion_t quaternion () const
Powerline quaternion getter.
const rclcpp::Time stamp () const
Stamp getter.
Private Member Functions
bool anyCableInFOV () const
Checks if any cable is in the field of view.
const iii_drone::types::euler_angles_t computePowerlineEulerAngles (const float &pl_yaw, const iii_drone::types::quaternion_t &drone_quat)
Computes the powerline euler angles from observed powerline yaw.
float mapAngle (float curr_angle, float new_angle) const
Maps the angle into continuous range based on current angle.
float mapAngle2 (float curr_angle, float new_angle) const
Maps the angle into continuous range based on current angle.
float backmapAngle (float angle) const
Maps the angle back into the correct range after having performed the Kalman filter.
void resetKalmanFilter ()
Resets the Kalman filter estimates.
Private Attributes
iii_drone::utils::Timestamp stamp_
Time stamp for latest change.
std::shared_ptr< PowerlineDirectionParameters > parameters_
The powerline direction parameters.
kf_est_t pl_angle_est_ [3]
Kalman filter estimates.
iii_drone::utils::History< iii_drone::types::quaternion_t > drone_quat_history_
The drone quaternions.
iii_drone::utils::History< iii_drone::types::quaternion_t > pl_quat_history_
The powerline quaternion.
iii_drone::adapters::PowerlineAdapter pl_
The Powerline object.
std::shared_mutex pl_mutex_
Mutex for powerline access.
Detailed Description
Class for computing the powerline direction and converting to ROS2 message, as well as Kalman Filtering.
Definition at line 51 of file powerline_direction.hpp.
Constructor & Destructor Documentation
PowerlineDirection()
PowerlineDirection::PowerlineDirection (std::shared_ptr< PowerlineDirectionParameters > parameters)
Default constructor.
Parameters
parameters The powerline direction parameters.
Definition at line 13 of file powerline_direction.cpp.
    : parameters_(parameters),
    drone_quat_history_(2),
    pl_quat_history_(1) {
    resetKalmanFilter();
    stamp_.Update();
}
References resetKalmanFilter(), stamp_, and iii_drone::utils::Timestamp::Update().
~PowerlineDirection()
PowerlineDirection::~PowerlineDirection ()
Destructor.
Definition at line 24 of file powerline_direction.cpp.
{ }
Member Function Documentation
anyCableInFOV()
bool PowerlineDirection::anyCableInFOV () const private
Checks if any cable is in the field of view.
Returns
bool True if any cable is in the field of view
Definition at line 202 of file powerline_direction.cpp.
{
    std::shared_lock<std::shared_mutex> lock(pl_mutex_);
    if (pl_.single_line_adapters().size() == 0) {
        return true;
    }
    if (pl_.GetVisibleLineAdapters().size() == 0) {
        return false;
    }
    return true;
}
References iii_drone::adapters::PowerlineAdapter::GetVisibleLineAdapters(), pl_, pl_mutex_, and iii_drone::adapters::PowerlineAdapter::single_line_adapters().
Referenced by Update().
backmapAngle()
float PowerlineDirection::backmapAngle (float angle) const private
Maps the angle back into the correct range after having performed the Kalman filter.
Parameters
angle Angle to map
Returns
float Back mapped angle
Definition at line 368 of file powerline_direction.cpp.
{
    if (angle > M_PI) {
        return angle-2*M_PI;
    } else if (angle < -M_PI) {
        return angle+2*M_PI;
    } else {
        return angle;
    }
}
Referenced by Predict(), and Update().
computePowerlineEulerAngles()
const iii_drone::types::euler_angles_t PowerlineDirection::computePowerlineEulerAngles (const float & pl_yaw, const iii_drone::types::quaternion_t & drone_quat) private
Computes the powerline euler angles from observed powerline yaw.
Parameters
pl_yaw The observed powerline yaw.
drone_quat The drone quaternion.
Returns
iii_drone::types::euler_angles_t The powerline euler angles.
Definition at line 240 of file powerline_direction.cpp.
  {
    using namespace iii_drone::types;
    using namespace iii_drone::math;
    static float W_pl_yaw_ = 0;
    quaternion_t W_Q_D = drone_quat;
    rotation_matrix_t W_R_D = quatToMat(W_Q_D);
    vector_t unit_x(1,0,0);
    euler_angles_t pl_eul(0,0,pl_yaw);
    vector_t D_v = eulToMat(pl_eul) * unit_x;
    vector_t W_v(
        -(D_v(1)*W_R_D(0,1) - D_v(0)*W_R_D(1,1))/(W_R_D(0,0)*W_R_D(1,1) - W_R_D(0,1)*W_R_D(1,0)),
        (D_v(1)*W_R_D(0,0) - D_v(0)*W_R_D(1,0))/(W_R_D(0,0)*W_R_D(1,1) - W_R_D(0,1)*W_R_D(1,0)),
        0
    );
    float pl_angle = atan2(W_v[1], W_v[0]);
    pl_angle = mapAngle(W_pl_yaw_, pl_angle);
    W_pl_yaw_ = pl_angle;
    euler_angles_t W_pl_eul(0,0,pl_angle);
    W_v = eulToMat(W_pl_eul) * unit_x;
    W_v /= W_v.norm();
    euler_angles_t pi_2_yaw(0,0,M_PI_2);
    vector_t W_P_x = W_v;
    vector_t W_P_y = eulToMat(pi_2_yaw)*W_P_x;
    vector_t W_P_z(0,0,1);
    rotation_matrix_t W_R_P;
    for (int i = 0; i < 3; i++) {
        W_R_P(i,0) = W_P_x(i);
        W_R_P(i,1) = W_P_y(i);
        W_R_P(i,2) = W_P_z(i);
    }
    rotation_matrix_t D_R_P = W_R_D * W_R_P;
    quaternion_t D_Q_P = matToQuat(D_R_P);
    euler_angles_t D_eul_P = quatToEul(D_Q_P);
    return D_eul_P;
}
References mapAngle().
Referenced by Update().
mapAngle()
float PowerlineDirection::mapAngle (float curr_angle, float new_angle) const private
Maps the angle into continuous range based on current angle.
Parameters
curr_angle Current angle
new_angle New angle
Returns
float Mapped angle
Definition at line 300 of file powerline_direction.cpp.
        {
    float angle_candidates[5];
    angle_candidates[0] = new_angle;
    if (new_angle > 0) {
        angle_candidates[1] = new_angle - M_PI;
        angle_candidates[2] = new_angle - 2*M_PI;
        angle_candidates[3] = new_angle + M_PI;
        angle_candidates[4] = new_angle + 2*M_PI;
    } else {
        angle_candidates[1] = new_angle + M_PI;
        angle_candidates[2] = new_angle + 2*M_PI;
        angle_candidates[3] = new_angle - M_PI;
        angle_candidates[4] = new_angle - 2*M_PI;
    }
    float best_angle = angle_candidates[0];
    float best_angle_diff = abs(angle_candidates[0]-curr_angle);
    for (int i = 0; i < 5; i++) {
        float diff = abs(angle_candidates[i]-curr_angle);
        if (diff < best_angle_diff) {
            best_angle_diff = diff;
            best_angle = angle_candidates[i];
        }
    }
    return best_angle;
}
Referenced by computePowerlineEulerAngles().
mapAngle2()
float PowerlineDirection::mapAngle2 (float curr_angle, float new_angle) const private
Maps the angle into continuous range based on current angle.
Parameters
curr_angle Current angle
new_angle New angle
Returns
float Mapped angle
Definition at line 341 of file powerline_direction.cpp.
        {
    float angle_candidates[3];
    angle_candidates[0] = new_angle;
    angle_candidates[1] = new_angle + M_PI;
    angle_candidates[2] = new_angle - M_PI;
    float best_angle = angle_candidates[0];
    float best_angle_diff = abs(angle_candidates[0]-curr_angle);
    for (int i = 0; i < 3; i++) {
        float diff = abs(angle_candidates[i]-curr_angle);
        if (diff < best_angle_diff) {
            best_angle_diff = diff;
            best_angle = angle_candidates[i];
        }
    }
    return best_angle;
}
Referenced by Update().
Predict()
void PowerlineDirection::Predict (const iii_drone::types::quaternion_t & drone_quat)
Runs the Kalman Filter predict step from a drone quaternion.
Parameters
drone_quat The drone quaternion.
Works!!!!! #impericalmethod
Definition at line 150 of file powerline_direction.cpp.
{
    using namespace iii_drone::types;
    using namespace iii_drone::math;
    drone_quat_history_ = drone_quat;
    if (!drone_quat_history_.full()) {
        return;
    }
    if (!pl_quat_history_.full()) {
        return;
    }
    quaternion_t inv_last_drone_quat = quatInv(drone_quat_history_[-1]);
    quaternion_t delta_drone_quat = quatMultiply(drone_quat, inv_last_drone_quat);
    quaternion_t pl_quat = pl_quat_history_[0];
    pl_quat = quatMultiply(
        delta_drone_quat,
        pl_quat
    );
    pl_quat_history_ = pl_quat;
    euler_angles_t eul = quatToEul(pl_quat);
    for (int i = 0; i < 3; i++) {
        pl_angle_est_[i].var_est += parameters_->kf_q();
        pl_angle_est_[i].state_est = backmapAngle(eul(i));
    }
    stamp_.Update();
}
References backmapAngle(), drone_quat_history_, iii_drone::utils::History< T >::full(), parameters_, pl_angle_est_, pl_quat_history_, stamp_, iii_drone::perception::PowerlineDirection::kf_est_t::state_est, iii_drone::utils::Timestamp::Update(), and iii_drone::perception::PowerlineDirection::kf_est_t::var_est.
Referenced by iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::odometryCallback().
quaternion()
const iii_drone::types::quaternion_t PowerlineDirection::quaternion () const
Powerline quaternion getter.
Definition at line 222 of file powerline_direction.cpp.
{
    if (pl_quat_history_.empty()) {
        return iii_drone::types::quaternion_t::Identity();
    }
    return pl_quat_history_[0];
}
References iii_drone::utils::History< T >::empty(), and pl_quat_history_.
resetKalmanFilter()
void PowerlineDirection::resetKalmanFilter () private
Resets the Kalman filter estimates.
Definition at line 381 of file powerline_direction.cpp.
{
    iii_drone::types::euler_angles_t pl_eul;
    if (pl_quat_history_.empty()) {
        pl_eul = iii_drone::types::euler_angles_t(0,0,0);
    } else {
        pl_eul = iii_drone::math::quatToEul(pl_quat_history_[0]);
    }
    pl_angle_est_[0].state_est = pl_eul(0);
    pl_angle_est_[0].var_est = 0.1;
    pl_angle_est_[1].state_est = pl_eul(1);
    pl_angle_est_[1].var_est = 0.1;
    pl_angle_est_[2].state_est = pl_eul(2);
    pl_angle_est_[2].var_est = 0.1;
}
References iii_drone::utils::History< T >::empty(), pl_angle_est_, pl_quat_history_, iii_drone::math::quatToEul(), iii_drone::perception::PowerlineDirection::kf_est_t::state_est, and iii_drone::perception::PowerlineDirection::kf_est_t::var_est.
Referenced by PowerlineDirection(), and Update().
stamp()
const rclcpp::Time PowerlineDirection::stamp () const
Stamp getter.
Definition at line 234 of file powerline_direction.cpp.
{
    return stamp_;
}
References stamp_.
ToPoseStampedMsg()
const geometry_msgs::msg::PoseStamped PowerlineDirection::ToPoseStampedMsg (const std::string & drone_frame_id) const
Converts to pose stamped message.
Parameters
drone_frame_id The drone frame id.
Returns
geometry_msgs::msg::PoseStamped The pose stamped message.
Definition at line 26 of file powerline_direction.cpp.
{
    geometry_msgs::msg::PoseStamped msg;
    msg.header.stamp = (rclcpp::Time)stamp_;
    msg.header.frame_id = drone_frame_id;
    iii_drone::types::quaternion_t pl_quat;
    if (pl_quat_history_.empty()) {
        pl_quat = iii_drone::types::quaternion_t::Identity();
    } else {
        pl_quat = pl_quat_history_[0];
    }
    msg.pose = iii_drone::types::poseMsgFromPose(
        iii_drone::types::point_t::Zero(),
        pl_quat
    );
    return msg;
}
References iii_drone::utils::History< T >::empty(), pl_quat_history_, iii_drone::types::poseMsgFromPose(), and stamp_.
Referenced by iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::publishPowerlineDirection().
ToQuaternionStampedMsg()
const geometry_msgs::msg::QuaternionStamped PowerlineDirection::ToQuaternionStampedMsg (const std::string & drone_frame_id) const
Converts to quaternion stamped message.
Parameters
drone_frame_id The drone frame id.
Returns
geometry_msgs::msg::QuaternionStamped The quaternion stamped message.
Definition at line 54 of file powerline_direction.cpp.
{
    geometry_msgs::msg::QuaternionStamped msg;
    msg.header.stamp = (rclcpp::Time)stamp_;
    msg.header.frame_id = drone_frame_id;
    if (pl_quat_history_.empty()) {
        msg.quaternion = iii_drone::types::quaternionMsgFromQuaternion(iii_drone::types::quaternion_t::Identity());
    } else {
        msg.quaternion = iii_drone::types::quaternionMsgFromQuaternion(pl_quat_history_[0]);
    }
    return msg;
}
References iii_drone::utils::History< T >::empty(), pl_quat_history_, iii_drone::types::quaternionMsgFromQuaternion(), and stamp_.
Referenced by iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::publishPowerlineDirection().
Update()
void PowerlineDirection::Update (float pl_yaw)
Runs the Kalman Filter update step from an observed yaw angle.
Parameters
pl_yaw The observed powerline yaw.
Definition at line 75 of file powerline_direction.cpp.
{
    using namespace iii_drone::types;
    using namespace iii_drone::math;
    if (drone_quat_history_.empty()) {
        return;
    }
    quaternion_t drone_quat = drone_quat_history_[0];
    if (pl_quat_history_.empty()) {
        euler_angles_t pl_eul = computePowerlineEulerAngles(pl_yaw, drone_quat);
        quaternion_t pl_quat = eulToQuat(pl_eul);
        pl_quat_history_ = pl_quat;
        resetKalmanFilter();
        stamp_.Update();
        return;
    }
    if (!anyCableInFOV()) {
        return;
    }
    euler_angles_t D_eul_P = computePowerlineEulerAngles(pl_yaw, drone_quat);
    for (int i = 0; i < 3; i++) {
        float angle = false ? mapAngle2(pl_angle_est_[i].state_est, D_eul_P(i)) : D_eul_P(i);
        // if (!received_angle_) {
        //     pl_angle_est_[i].state_est = backmapAngle(angle);
        //     if (i==2) {
        //         received_angle_ = true;
        //     }
        // } else {
            float y_bar = angle - pl_angle_est_[i].state_est;
            float s = pl_angle_est_[i].var_est + parameters_->kf_r();
            float k = pl_angle_est_[i].var_est / s;
            pl_angle_est_[i].state_est += k*y_bar;
            pl_angle_est_[i].var_est *= 1-k;
            pl_angle_est_[i].state_est = backmapAngle(pl_angle_est_[i].state_est);
        // }
        D_eul_P(i) = pl_angle_est_[i].state_est;
        pl_quat_history_ = eulToQuat(D_eul_P);
    }
    stamp_.Update();
}
References anyCableInFOV(), backmapAngle(), computePowerlineEulerAngles(), drone_quat_history_, iii_drone::utils::History< T >::empty(), mapAngle2(), parameters_, pl_angle_est_, pl_quat_history_, resetKalmanFilter(), stamp_, iii_drone::perception::PowerlineDirection::kf_est_t::state_est, iii_drone::utils::Timestamp::Update(), and iii_drone::perception::PowerlineDirection::kf_est_t::var_est.
Referenced by iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::PowerlineDirectionComputerNode().
UpdatePowerlineAdapter()
void PowerlineDirection::UpdatePowerlineAdapter (const iii_drone_interfaces::msg::Powerline::SharedPtr msg)
Updates the PowerlineAdapter object.
Parameters
msg The powerline ROS2 message.
Definition at line 194 of file powerline_direction.cpp.
{
    std::unique_lock<std::shared_mutex> lock(pl_mutex_);
    pl_.UpdateFromMsg(*msg);
}
References pl_, pl_mutex_, and iii_drone::adapters::PowerlineAdapter::UpdateFromMsg().
Referenced by iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::PowerlineDirectionComputerNode().
Member Data Documentation
drone_quat_history_
iii_drone::utils::History<iii_drone::types::quaternion_t> iii_drone::perception::PowerlineDirection::drone_quat_history_ private
The drone quaternions.
Definition at line 203 of file powerline_direction.hpp.
Referenced by Predict(), and Update().
parameters_
std::shared_ptr<PowerlineDirectionParameters> iii_drone::perception::PowerlineDirection::parameters_ private
The powerline direction parameters.
Definition at line 123 of file powerline_direction.hpp.
Referenced by Predict(), and Update().
pl_
iii_drone::adapters::PowerlineAdapter iii_drone::perception::PowerlineDirection::pl_ private
The Powerline object.
Definition at line 213 of file powerline_direction.hpp.
Referenced by anyCableInFOV(), and UpdatePowerlineAdapter().
pl_angle_est_
kf_est_t iii_drone::perception::PowerlineDirection::pl_angle_est_[3] private
Kalman filter estimates.
Definition at line 193 of file powerline_direction.hpp.
Referenced by Predict(), resetKalmanFilter(), and Update().
pl_mutex_
std::shared_mutex iii_drone::perception::PowerlineDirection::pl_mutex_ mutable private
Mutex for powerline access.
Definition at line 218 of file powerline_direction.hpp.
Referenced by anyCableInFOV(), and UpdatePowerlineAdapter().
pl_quat_history_
iii_drone::utils::History<iii_drone::types::quaternion_t> iii_drone::perception::PowerlineDirection::pl_quat_history_ private
The powerline quaternion.
Definition at line 208 of file powerline_direction.hpp.
Referenced by Predict(), quaternion(), resetKalmanFilter(), ToPoseStampedMsg(), ToQuaternionStampedMsg(), and Update().
stamp_
iii_drone::utils::Timestamp iii_drone::perception::PowerlineDirection::stamp_ private
Time stamp for latest change.
Definition at line 118 of file powerline_direction.hpp.
Referenced by PowerlineDirection(), Predict(), stamp(), ToPoseStampedMsg(), ToQuaternionStampedMsg(), and Update().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/perception/powerline_direction.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/perception/powerline_direction.cpp