III-Drone: iii_drone::control::maneuver::FlyToPositionManeuverServer Class Reference
iii_drone::control::maneuver::FlyToPositionManeuverServer Class Reference
Class for serving flying to a position.
#include <fly_to_position_maneuver_server.hpp>
Public Member Functions
FlyToPositionManeuverServer (rclcpp::Node *node, CombinedDroneAwarenessHandler::SharedPtr combined_drone_awareness_handler, const std::string &action_name, unsigned int wait_for_execute_poll_ms, unsigned int evaluate_done_poll_ms, iii_drone::control::maneuver::FlyToPositionManeuverServerParameters::SharedPtr fly_to_position_maneuver_server_parameters, iii_drone::control::TrajectoryGeneratorClient::SharedPtr trajectory_generator_client)
Constructor.
bool CanExecuteManeuver (const Maneuver &maneuver, const combined_drone_awareness_t &drone_awareness) const override
Whether the maneuver can be executed.
combined_drone_awareness_t ExpectedAwarenessAfterExecution (const Maneuver &maneuver) override
Expected awareness after execution.
Public Member Functions inherited from iii_drone::control::maneuver::ManeuverServer
ManeuverServer (rclcpp::Node *node, CombinedDroneAwarenessHandler::SharedPtr awareness_handler, const std::string &action_name, unsigned int wait_for_execute_poll_ms, unsigned int evaluate_done_poll_ms)
Constructor.
void Start (std::function< bool(Maneuver, bool &)> register_maneuver_function, std::function< bool(Maneuver)> update_manuever_function, std::function< bool(Maneuver)> cancel_maneuver_function, std::function< bool(Maneuver)> verify_maneuver_in_queue_function, std::function< bool(Maneuver)> verify_maneuver_active_function, std::function< void(Maneuver)> done_callback, ReferenceCallbackToken::SharedPtr reference_callback_token, std::map< iii_drone::control::maneuver::maneuver_type_t, std::shared_ptr< ManeuverServer > > registered_maneuvers)
Method to start the maneuver server. The maneuver server will reject any new goals until started.
void Stop ()
Method to stop the maneuver server. The maneuver server will reject any new goals until started.
std::string action_name () const
Action name getter.
bool running () const
Returns whether the maneuver server is running.
Private Types
using FlyToPosition = iii_drone_interfaces::action::FlyToPosition
using GoalHandleFlyToPosition = rclcpp_action::ServerGoalHandle<FlyToPosition>
Private Member Functions
maneuver_type_t maneuver_type () const override
The maneuver type (MANEUVER_TYPE_FLY_TO_POSITION)
void startExecution (Maneuver &maneuver) override
Starts the execution of the maneuver.
bool canCancel () override
Whether the maneuver can be canceled, always returns true.
iii_drone::control::Reference computeReference (const iii_drone::control::State &state) override
Compute the reference.
bool hasSucceeded (Maneuver &maneuver) override
Whether the maneuver has succeeded, returns true if the drone is within the position tolerance.
bool hasFailed (Maneuver &maneuver) override
Whether the maneuver has failed.
void publishFeedback (Maneuver &maneuver) override
Publishes the feedback.
void publishResultAndFinalize (Maneuver &maneuver, maneuver_result_type_t maneuver_result_type) override
Publishes the result and finalizes the maneuver according to the maneuver result type.
void registerReferenceCallbackOnSuccess (const Maneuver &maneuver) override
Registers the hover reference callback on success.
Private Attributes
iii_drone::control::maneuver::FlyToPositionManeuverServerParameters::SharedPtr parameters_
The fly to position maneuver server parameters shared pointer.
iii_drone::control::TrajectoryGeneratorClient::SharedPtr trajectory_generator_client_
The trajectory generator client shared pointer.
iii_drone::utils::Atomic< iii_drone::control::Reference > target_reference_
The target reference.
iii_drone::utils::Atomic< bool > first_iteration_ = true
Flag for first iteration.
Additional Inherited Members
Public Types inherited from iii_drone::control::maneuver::ManeuverServer
typedef std::shared_ptr< ManeuverServer > SharedPtr
Shared pointer type.
Protected Types inherited from iii_drone::control::maneuver::ManeuverServer
enum maneuver_result_type_t { MANEUVER_RESULT_TYPE_SUCCEED , MANEUVER_RESULT_TYPE_CANCEL , MANEUVER_RESULT_TYPE_ABORT }
Maneuver result type enum.
Protected Member Functions inherited from iii_drone::control::maneuver::ManeuverServer
const CombinedDroneAwarenessHandler::SharedPtr & awareness_handler () const
Combined drone awareness handler, accessible to derived classes through the protected method.
const iii_drone::utils::Atomic< iii_drone::control::maneuver::Maneuver > & current_maneuver () const
The currently executing maneuver, accessible to derived classes through the protected method.
rclcpp::Node * node () const
Node pointer getter.
std::map< iii_drone::control::maneuver::maneuver_type_t, std::shared_ptr< iii_drone::control::maneuver::ManeuverServer > > registered_maneuvers () const
Registered maneuvers map getter.
void registerCallback (const std::function< Reference(const State &)> &callback)
Registers a callback function for the reference. The callback function should be registered with the reference callback token.
template<typename ActionT >
void createServer ()
Creates the underlying action server.
Detailed Description
Class for serving flying to a position.
Definition at line 43 of file fly_to_position_maneuver_server.hpp.
Member Typedef Documentation
FlyToPosition
using iii_drone::control::maneuver::FlyToPositionManeuverServer::FlyToPosition = iii_drone_interfaces::action::FlyToPosition private
Definition at line 44 of file fly_to_position_maneuver_server.hpp.
GoalHandleFlyToPosition
using iii_drone::control::maneuver::FlyToPositionManeuverServer::GoalHandleFlyToPosition = rclcpp_action::ServerGoalHandle<FlyToPosition> private
Definition at line 45 of file fly_to_position_maneuver_server.hpp.
Constructor & Destructor Documentation
FlyToPositionManeuverServer()
FlyToPositionManeuverServer::FlyToPositionManeuverServer (rclcpp::Node * node, CombinedDroneAwarenessHandler::SharedPtr combined_drone_awareness_handler, const std::string & action_name, unsigned int wait_for_execute_poll_ms, unsigned int evaluate_done_poll_ms, iii_drone::control::maneuver::FlyToPositionManeuverServerParameters::SharedPtr fly_to_position_maneuver_server_parameters, iii_drone::control::TrajectoryGeneratorClient::SharedPtr trajectory_generator_client)
Constructor.
Parameters
node Node pointer
combined_drone_awareness_handler Combined drone awareness handler pointer
action_name Action name
wait_for_execute_poll_ms Wait for execute poll milliseconds
evaluate_done_poll_ms Evaluate done poll milliseconds
fly_to_position_maneuver_server_parameters Fly to position maneuver server parameters
trajectory_generator_client Trajectory generator client shared pointer
Definition at line 16 of file fly_to_position_maneuver_server.cpp.
  : ManeuverServer(
    node,
    combined_drone_awareness_handler,
    action_name,
    wait_for_execute_poll_ms,
    evaluate_done_poll_ms
),  parameters_(parameters),
    trajectory_generator_client_(trajectory_generator_client) {
    createServer<iii_drone_interfaces::action::FlyToPosition>();
}
References iii_drone::control::maneuver::ManeuverServer::createServer< iii_drone_interfaces::action::FlyToPosition >().
Member Function Documentation
canCancel()
bool FlyToPositionManeuverServer::canCancel () override private virtual
Whether the maneuver can be canceled, always returns true.
Returns
bool Whether the maneuver can be canceled.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 113 of file fly_to_position_maneuver_server.cpp.
{
    return true;
}
CanExecuteManeuver()
bool FlyToPositionManeuverServer::CanExecuteManeuver (const Maneuver & maneuver, const combined_drone_awareness_t & drone_awareness) const override virtual
Whether the maneuver can be executed.
Parameters
maneuver The maneuver.
drone_awareness The drone awareness.
Returns
bool Whether the maneuver can be executed.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 37 of file fly_to_position_maneuver_server.cpp.
        {
    if (maneuver.maneuver_type() != MANEUVER_TYPE_FLY_TO_POSITION) {
        return false;
    }
    auto cda_handler = awareness_handler();
    std::shared_ptr<fly_to_position_maneuver_params_t> fly_to_position_maneuver_params = std::static_pointer_cast<fly_to_position_maneuver_params_t>(maneuver.maneuver_params());
    point_t target_position_in_world_frame = fly_to_position_maneuver_params->transform_target_position(
        parameters_->world_frame_id(),
        cda_handler->tf_buffer()
    );
    bool target_position_valid = target_position_in_world_frame[2] - cda_handler->ground_altitude_estimate() >= parameters_->minimum_target_altitude();
    return drone_awareness.in_flight() &&
        drone_awareness.offboard &&
        target_position_valid;
}
References iii_drone::control::maneuver::ManeuverServer::awareness_handler(), iii_drone::control::combined_drone_awareness_t::in_flight(), iii_drone::control::maneuver::Maneuver::maneuver_params(), iii_drone::control::maneuver::Maneuver::maneuver_type(), iii_drone::control::maneuver::MANEUVER_TYPE_FLY_TO_POSITION, iii_drone::control::maneuver::FlyToPositionManeuverServerParameters::minimum_target_altitude(), iii_drone::control::combined_drone_awareness_t::offboard, parameters_, and iii_drone::control::maneuver::FlyToPositionManeuverServerParameters::world_frame_id().
computeReference()
Reference FlyToPositionManeuverServer::computeReference (const iii_drone::control::State & state) override private virtual
Compute the reference.
Parameters
state The current state.
Returns
The reference.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 117 of file fly_to_position_maneuver_server.cpp.
{
    Reference ref;
    if (parameters_->generate_trajectories_asynchronously_with_delay()) {
        if (first_iteration_) {
            if (trajectory_generator_client_->busy()) {
                std::string error_message = "FlyToPositionManeuverServer::computeReference(): Trajectory generator client is busy on first iteration, cannot start execution of maneuver.";
                RCLCPP_FATAL(node()->get_logger(), error_message.c_str());
                throw std::runtime_error(error_message);
            }
            trajectory_generator_client_->Reset(state);
            ref = trajectory_generator_client_->GetReferenceTrajectory().references()[0];
            trajectory_generator_client_->ComputeReferenceTrajectoryAsync(
                state,
                target_reference_,
                true,
                true,
                MPC_mode_t::positional
            );
            first_iteration_ = false;
        } else {
            while (!trajectory_generator_client_->done()) {
                rclcpp::sleep_for(std::chrono::milliseconds(parameters_->generate_trajectories_poll_period_ms()));
            }
            ref = trajectory_generator_client_->GetReferenceTrajectory().references()[1];
            trajectory_generator_client_->ComputeReferenceTrajectoryAsync(
                state,
                target_reference_,
                false,
                false,
                MPC_mode_t::positional
            );
        }
    } else {
        if (trajectory_generator_client_->busy()) {
            std::string error_message = "FlyToPositionManeuverServer::computeReference(): Trajectory generator client is busy on first iteration, cannot start execution of maneuver.";
            RCLCPP_FATAL(node()->get_logger(), error_message.c_str());
            throw std::runtime_error(error_message);
        }
        bool first_it = first_iteration_;
        if (first_it) {
            trajectory_generator_client_->Reset(state);
            first_iteration_ = false;
        }
        trajectory_generator_client_->ComputeReferenceTrajectoryBlocking(
            state,
            target_reference_,
            first_it,
            first_it,
            MPC_mode_t::positional,
            parameters_->generate_trajectories_poll_period_ms()
        );
        ref = trajectory_generator_client_->GetReferenceTrajectory().references()[0];
    }
    return ref;
}
References iii_drone::control::TrajectoryGeneratorClient::busy(), iii_drone::control::TrajectoryGeneratorClient::ComputeReferenceTrajectoryAsync(), iii_drone::control::TrajectoryGeneratorClient::ComputeReferenceTrajectoryBlocking(), iii_drone::control::TrajectoryGeneratorClient::done(), first_iteration_, iii_drone::control::maneuver::FlyToPositionManeuverServerParameters::generate_trajectories_asynchronously_with_delay(), iii_drone::control::maneuver::FlyToPositionManeuverServerParameters::generate_trajectories_poll_period_ms(), iii_drone::control::TrajectoryGeneratorClient::GetReferenceTrajectory(), iii_drone::control::maneuver::ManeuverServer::node(), parameters_, iii_drone::control::positional, iii_drone::control::ReferenceTrajectory::references(), iii_drone::control::TrajectoryGeneratorClient::Reset(), target_reference_, and trajectory_generator_client_.
ExpectedAwarenessAfterExecution()
combined_drone_awareness_t FlyToPositionManeuverServer::ExpectedAwarenessAfterExecution (const Maneuver & maneuver) override virtual
Expected awareness after execution.
Parameters
maneuver The maneuver.
Returns
The expected awareness after execution.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 63 of file fly_to_position_maneuver_server.cpp.
{
    combined_drone_awareness_t awareness_after;
    awareness_after.armed = true;
    awareness_after.offboard = true;
    awareness_after.target_adapter = TargetAdapter();
    awareness_after.target_position_known = false;
    awareness_after.drone_location = DRONE_LOCATION_IN_FLIGHT;
    return awareness_after;
}
References iii_drone::control::combined_drone_awareness_t::armed, iii_drone::control::combined_drone_awareness_t::drone_location, iii_drone::control::DRONE_LOCATION_IN_FLIGHT, iii_drone::control::combined_drone_awareness_t::offboard, iii_drone::control::combined_drone_awareness_t::target_adapter, and iii_drone::control::combined_drone_awareness_t::target_position_known.
hasFailed()
bool FlyToPositionManeuverServer::hasFailed (Maneuver & maneuver) override private virtual
Whether the maneuver has failed.
Parameters
maneuver The maneuver.
Returns
bool Whether the maneuver has failed.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 234 of file fly_to_position_maneuver_server.cpp.
{
    auto cda_handler = awareness_handler();
    return !cda_handler->in_flight()
        || !cda_handler->offboard()
        || !cda_handler->armed();
}
References iii_drone::control::maneuver::ManeuverServer::awareness_handler().
hasSucceeded()
bool FlyToPositionManeuverServer::hasSucceeded (Maneuver & maneuver) override private virtual
Whether the maneuver has succeeded, returns true if the drone is within the position tolerance.
Parameters
maneuver The maneuver.
Returns
bool Whether the maneuver has succeeded.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 208 of file fly_to_position_maneuver_server.cpp.
{
    auto cda_handler = awareness_handler();
    State state = cda_handler->GetState();
    Eigen::Vector4d euc_pos = {
        state.position()[0],
        state.position()[1],
        state.position()[2],
        state.yaw()
    };
    Eigen::Vector4d target_euc_pos = {
        target_reference_->position()[0],
        target_reference_->position()[1],
        target_reference_->position()[2],
        target_reference_->yaw()
    };
    double distance = (euc_pos - target_euc_pos).norm();
    return distance < parameters_->reached_position_euclidean_distance_threshold();
}
References iii_drone::control::maneuver::ManeuverServer::awareness_handler(), parameters_, iii_drone::control::Reference::position(), iii_drone::control::State::position(), iii_drone::control::maneuver::FlyToPositionManeuverServerParameters::reached_position_euclidean_distance_threshold(), target_reference_, iii_drone::control::Reference::yaw(), and iii_drone::control::State::yaw().
maneuver_type()
maneuver_type_t FlyToPositionManeuverServer::maneuver_type () const override private virtual
The maneuver type (MANEUVER_TYPE_FLY_TO_POSITION)
Returns
The maneuver type.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 77 of file fly_to_position_maneuver_server.cpp.
{
    return MANEUVER_TYPE_FLY_TO_POSITION;
}
References iii_drone::control::maneuver::MANEUVER_TYPE_FLY_TO_POSITION.
publishFeedback()
void FlyToPositionManeuverServer::publishFeedback (Maneuver & maneuver) override private virtual
Publishes the feedback.
Parameters
maneuver The maneuver.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 244 of file fly_to_position_maneuver_server.cpp.
{
    auto feedback = std::make_shared<iii_drone_interfaces::action::FlyToPosition::Feedback>();
    ReferenceTrajectory reference_trajectory = trajectory_generator_client_->GetReferenceTrajectory();
    ReferenceTrajectoryAdapter reference_trajectory_adapter(reference_trajectory);
    feedback->planned_path = reference_trajectory_adapter.ToPathMsg(parameters_->world_frame_id());
    feedback->vehicle_pose = StateAdapter(awareness_handler()->GetState()).ToPoseStampedMsg(parameters_->world_frame_id());
    auto goal_handle = std::static_pointer_cast<GoalHandleFlyToPosition>(maneuver.goal_handle());
    goal_handle->publish_feedback(feedback);
}
References iii_drone::control::maneuver::ManeuverServer::awareness_handler(), iii_drone::control::TrajectoryGeneratorClient::GetReferenceTrajectory(), iii_drone::control::maneuver::Maneuver::goal_handle(), parameters_, iii_drone::adapters::ReferenceTrajectoryAdapter::ToPathMsg(), iii_drone::adapters::StateAdapter::ToPoseStampedMsg(), trajectory_generator_client_, and iii_drone::control::maneuver::FlyToPositionManeuverServerParameters::world_frame_id().
publishResultAndFinalize()
void FlyToPositionManeuverServer::publishResultAndFinalize (Maneuver & maneuver, maneuver_result_type_t maneuver_result_type) override private virtual
Publishes the result and finalizes the maneuver according to the maneuver result type.
Parameters
maneuver The maneuver.
maneuver_result_type The maneuver result type.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 261 of file fly_to_position_maneuver_server.cpp.
  {
    auto result = std::make_shared<iii_drone_interfaces::action::FlyToPosition::Result>();
    auto goal_handle = std::static_pointer_cast<GoalHandleFlyToPosition>(maneuver.goal_handle());
    switch (maneuver_result_type) {
        case MANEUVER_RESULT_TYPE_SUCCEED:
            result->success = true;
            goal_handle->succeed(result);
            break;
        case MANEUVER_RESULT_TYPE_ABORT:
            result->success = false;
            goal_handle->abort(result);
            break;
        case MANEUVER_RESULT_TYPE_CANCEL:
            result->success = false;
            goal_handle->canceled(result);
            break;
    }
}
References iii_drone::control::maneuver::Maneuver::goal_handle(), iii_drone::control::maneuver::ManeuverServer::MANEUVER_RESULT_TYPE_ABORT, iii_drone::control::maneuver::ManeuverServer::MANEUVER_RESULT_TYPE_CANCEL, and iii_drone::control::maneuver::ManeuverServer::MANEUVER_RESULT_TYPE_SUCCEED.
registerReferenceCallbackOnSuccess()
void FlyToPositionManeuverServer::registerReferenceCallbackOnSuccess (const Maneuver & maneuver) override private virtual
Registers the hover reference callback on success.
Parameters
maneuver The maneuver.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 286 of file fly_to_position_maneuver_server.cpp.
{
    auto registered_hover_maneuver = registered_maneuvers().find(MANEUVER_TYPE_HOVER);
    std::shared_ptr<HoverManeuverServer> hover_maneuver_server = std::static_pointer_cast<HoverManeuverServer>(registered_hover_maneuver->second);
    hover_maneuver_server->Update(target_reference_);
    registerCallback(
        std::bind(
            &HoverManeuverServer::GetReference,
            hover_maneuver_server,
            std::placeholders::_1
        )
    );
}
References iii_drone::control::maneuver::HoverManeuverServer::GetReference(), iii_drone::control::maneuver::MANEUVER_TYPE_HOVER, iii_drone::control::maneuver::ManeuverServer::registerCallback(), iii_drone::control::maneuver::ManeuverServer::registered_maneuvers(), and target_reference_.
startExecution()
void FlyToPositionManeuverServer::startExecution (Maneuver & maneuver) override private virtual
Starts the execution of the maneuver.
Parameters
maneuver The maneuver.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 81 of file fly_to_position_maneuver_server.cpp.
{
    auto cda_handler = awareness_handler();
    std::shared_ptr<fly_to_position_maneuver_params_t> fly_to_position_maneuver_params = std::static_pointer_cast<fly_to_position_maneuver_params_t>(maneuver.maneuver_params());
    point_t target_position_in_world_frame = fly_to_position_maneuver_params->transform_target_position(
        parameters_->world_frame_id(),
        cda_handler->tf_buffer()
    );
    target_reference_ = iii_drone::control::Reference(
        target_position_in_world_frame,
        fly_to_position_maneuver_params->target_yaw
    );
    if (trajectory_generator_client_->busy()) {
        std::string error_message = "FlyToPositionManeuverServer::startExecution(): Trajectory generator client is busy, cannot start execution of maneuver.";
        RCLCPP_FATAL(node()->get_logger(), error_message.c_str());
        throw std::runtime_error(error_message);
    }
    first_iteration_ = true;
    cda_handler->ClearTarget();
}
References iii_drone::control::maneuver::ManeuverServer::awareness_handler(), iii_drone::control::TrajectoryGeneratorClient::busy(), first_iteration_, iii_drone::control::maneuver::Maneuver::maneuver_params(), iii_drone::control::maneuver::ManeuverServer::node(), parameters_, target_reference_, trajectory_generator_client_, and iii_drone::control::maneuver::FlyToPositionManeuverServerParameters::world_frame_id().
Member Data Documentation
first_iteration_
iii_drone::utils::Atomic<bool> iii_drone::control::maneuver::FlyToPositionManeuverServer::first_iteration_ = true private
Flag for first iteration.
Definition at line 190 of file fly_to_position_maneuver_server.hpp.
Referenced by computeReference(), and startExecution().
parameters_
iii_drone::control::maneuver::FlyToPositionManeuverServerParameters::SharedPtr iii_drone::control::maneuver::FlyToPositionManeuverServer::parameters_ private
The fly to position maneuver server parameters shared pointer.
Definition at line 175 of file fly_to_position_maneuver_server.hpp.
Referenced by CanExecuteManeuver(), computeReference(), hasSucceeded(), publishFeedback(), and startExecution().
target_reference_
iii_drone::utils::Atomic<iii_drone::control::Reference> iii_drone::control::maneuver::FlyToPositionManeuverServer::target_reference_ private
The target reference.
Definition at line 185 of file fly_to_position_maneuver_server.hpp.
Referenced by computeReference(), hasSucceeded(), registerReferenceCallbackOnSuccess(), and startExecution().
trajectory_generator_client_
iii_drone::control::TrajectoryGeneratorClient::SharedPtr iii_drone::control::maneuver::FlyToPositionManeuverServer::trajectory_generator_client_ private
The trajectory generator client shared pointer.
Definition at line 180 of file fly_to_position_maneuver_server.hpp.
Referenced by computeReference(), publishFeedback(), and startExecution().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/maneuver/fly_to_position_maneuver_server.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/maneuver/fly_to_position_maneuver_server.cpp