III-Drone: iii_drone::configuration::Configurator Class Reference
iii_drone::configuration::Configurator Class Reference
Class for handling parameters of a node. The class works in conjunction with the ConfigurationServer node. The class will declare parameters with the ConfigurationServer node and will subscribe to the parameter event topic in order to update the local copy of the parameters.
#include <configurator.hpp>
Public Member Functions
Configurator (rclcpp::Node *node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Configurator (rclcpp::Node *node, const rclcpp::QoS &qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
~Configurator ()
template<typename T >
void DeclareParameter (const std::string &name)
rclcpp::Parameter GetParameter (const std::string &name) const
Get a parameter.
std::vector< rclcpp::Parameter > GetParameters (const std::vector< std::string > &names) const
Gets multiple parameters.
void SyncParameters (const std::vector< std::string > &names={})
Synchronizes parameters with the parameter server. Should never be necessary.
void PrintParameters () const
Prints all parameters to the console.
Static Public Member Functions
template<typename T >
static std::string GetParameterTypeString ()
Static function for getting string representation of a parameter type from template type.
Protected Attributes
rclcpp::Node * node_
Private Member Functions
void parameterEventCallback (rcl_interfaces::msg::ParameterEvent parameter_event)
bool sendDeclareParameterRequest (const std::string &name, const std::string &type, std::string &message)
Sends a DeclareParameter request to the ConfigurationServer node, which will declare the parameter in the parameter server.
bool sendGetParameterRequest (const std::string &name, rclcpp::Parameter &parameter)
Sends a GetParameters request to the ConfigurationServer node, which will return the parameter.
bool sendGetParametersRequest (const std::vector< std::string > &names, std::vector< rclcpp::Parameter > &parameters)
Sends a GetParameters request to the ConfigurationServer node, which will return the parameters.
Private Attributes
std::vector< rclcpp::Parameter > parameters_
std::unique_ptr< rclcpp::QoS > qos_ = nullptr
QoS settings for the parameter event subscription.
std::shared_mutex parameters_mutex_
rclcpp::Client< iii_drone_interfaces::srv::DeclareParameter >::SharedPtr declare_parameter_client_
DeclareParameter service client.
rclcpp::Client< rcl_interfaces::srv::GetParameters >::SharedPtr get_parameters_client_
GetParameters service client.
rclcpp::Subscription< rcl_interfaces::msg::ParameterEvent >::SharedPtr parameter_events_subscriber_
/parameter_events subscriber.
std::function< void(const rclcpp::Parameter &) after_parameter_change_callback_)
Detailed Description
Class for handling parameters of a node. The class works in conjunction with the ConfigurationServer node. The class will declare parameters with the ConfigurationServer node and will subscribe to the parameter event topic in order to update the local copy of the parameters.
Definition at line 46 of file configurator.hpp.
Constructor & Destructor Documentation
Configurator() [1/2]
Configurator::Configurator (rclcpp::Node * node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback = nullptr)
Definition at line 15 of file configurator.cpp.
  : after_parameter_change_callback_(after_parameter_change_callback) {
    RCLCPP_DEBUG(node->get_logger(), "Configurator::Configurator(): Initializing configurator");
    node_ = node;
    declare_parameter_client_ = node_->create_client<iii_drone_interfaces::srv::DeclareParameter>("/configuration/configuration_server/declare_parameter");
    get_parameters_client_ = node_->create_client<rcl_interfaces::srv::GetParameters>("/configuration/configuration_server/configuration_server/get_parameters");
    parameter_events_subscriber_ = node_->create_subscription<rcl_interfaces::msg::ParameterEvent>(
        "/parameter_events",
        10,
        std::bind(
            &Configurator::parameterEventCallback,
            this,
            std::placeholders::_1
        )
    );
}
References declare_parameter_client_, get_parameters_client_, node_, parameter_events_subscriber_, and parameterEventCallback().
Configurator() [2/2]
Configurator::Configurator (rclcpp::Node * node, const rclcpp::QoS & qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback = nullptr)
Definition at line 39 of file configurator.cpp.
  : after_parameter_change_callback_(after_parameter_change_callback) {
    RCLCPP_DEBUG(node->get_logger(), "Configurator::Configurator(): Initializing configurator");
    node_ = node;
    qos_ = std::make_unique<rclcpp::QoS>(qos);
    declare_parameter_client_ = node_->create_client<iii_drone_interfaces::srv::DeclareParameter>("/configuration/configuration_server/declare_parameter");
    get_parameters_client_ = node_->create_client<rcl_interfaces::srv::GetParameters>("/configuration/configuration_server/configuration_server/get_parameters");
    parameter_events_subscriber_ = node_->create_subscription<rcl_interfaces::msg::ParameterEvent>(
        "/parameter_events",
        *qos_,
        std::bind(
            &Configurator::parameterEventCallback,
            this,
            std::placeholders::_1
        )
    );
}
References declare_parameter_client_, get_parameters_client_, node_, parameter_events_subscriber_, parameterEventCallback(), and qos_.
~Configurator()
Configurator::~Configurator ()
Definition at line 67 of file configurator.cpp.
{ }
Member Function Documentation
DeclareParameter()
template<typename T > template void Configurator::DeclareParameter< float > (const std::string & name)
Definition at line 70 of file configurator.cpp.
{
    RCLCPP_DEBUG(node_->get_logger(), "Configurator::DeclareParameter(): Declaring parameter %s", name.c_str());
    {
        std::shared_lock<std::shared_mutex> shared_lock(parameters_mutex_);
        // Check if parameter is already declared:
        for (auto & p : parameters_) {
            if (p.get_name() == name) {
                RCLCPP_WARN(
                    node_->get_logger(),
                    "Configurator::DeclareParameter(): Parameter %s already declared.",
                    name.c_str()
                );
                return;
            }
        }
    }
    // Send DeclareParameter request:
    std::string message;
    if (!sendDeclareParameterRequest(
            name,
            GetParameterTypeString<T>(),
            message
        )
    ) {
        std::string fatal_message = "Configurator::DeclareParameter(): Failed to declare parameter " + name + " with error message " + message + ".";
        RCLCPP_FATAL(
            node_->get_logger(),
            fatal_message.c_str()
        );
        throw std::runtime_error(fatal_message);
    }
    // Get parameter value:
    rclcpp::Parameter parameter;
    if (!sendGetParameterRequest(
            name,
            parameter
        )
    ) {
        std::string fatal_message = "Configurator::DeclareParameter(): Failed to get parameter " + name + ".";
        RCLCPP_FATAL(
            node_->get_logger(),
            fatal_message.c_str()
        );
        throw std::runtime_error(fatal_message);
    }
    // Add parameter to the list of parameters:
    std::unique_lock<std::shared_mutex> unique_lock(parameters_mutex_);
    parameters_.push_back(parameter);
    // lock.unlock();
}
References GetParameterTypeString(), node_, parameters_, parameters_mutex_, sendDeclareParameterRequest(), and sendGetParameterRequest().
GetParameter()
rclcpp::Parameter Configurator::GetParameter (const std::string & name) const
Get a parameter.
Parameters
name Name of the parameter
Returns
The parameter
Definition at line 147 of file configurator.cpp.
{
    std::vector<rclcpp::Parameter> parameters = GetParameters({name});
    return parameters[0];
}
References GetParameters(), and GetParameterTypeString().
Referenced by iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestratorConfigurator::action_timeout_ms(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::alive_cnt_ceiling(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::alive_cnt_high_thresh(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::alive_cnt_low_thresh(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::always_armed_for_debug(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::always_hover_in_offboard(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::arm_cnt_timeout(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::arming_on_cable_spool_up_time_s(), iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestratorConfigurator::battery_voltage_high_threshold(), iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestratorConfigurator::battery_voltage_low_threshold(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::cable_gripper_frame_id(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::cable_gripper_frame_id(), iii_drone::perception::hough_transformer_node::HoughTransformerConfigurator::cable_gripper_frame_id(), iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::cable_gripper_frame_id(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::cable_gripper_frame_id(), iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestratorConfigurator::cable_landing_max_retries(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::cable_landing_target_upwards_velocity(), iii_drone::perception::hough_transformer_node::HoughTransformerConfigurator::canny_kernel_size(), iii_drone::perception::hough_transformer_node::HoughTransformerConfigurator::canny_low_threshold(), iii_drone::perception::hough_transformer_node::HoughTransformerConfigurator::canny_ratio(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::cartesian_PID_integral_reset_error_threshold(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::cartesian_PID_Kd(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::cartesian_PID_Ki(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::cartesian_PID_Kp(), iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestratorConfigurator::charging_maximum_duration_s(), iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestratorConfigurator::charging_minimum_duration_s(), iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestratorConfigurator::charging_power_low_threshold(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::direct_target_setpoint_dist_threshold(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::disarm_on_cable_cnt_timeout(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::disarm_on_cable_flight_termination_timeout_s(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::disarm_on_cable_mode(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::disarm_on_cable_thrust_decrease_time_s(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::disarm_on_cable_thrust_wait_for_disarm_time_s(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::disarming_on_cable_max_descend_distance(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::drone_frame_id(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::drone_frame_id(), iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator::drone_frame_id(), iii_drone::perception::hough_transformer_node::HoughTransformerConfigurator::drone_frame_id(), iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::drone_frame_id(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::drone_frame_id(), iii_drone::utils::drone_frame_broadcaster_node::DroneFrameBroadcasterConfigurator::drone_frame_id(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::dt(), iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator::dt(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::fail_on_unable_to_locate(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::generate_trajectories_asynchronously_with_delay(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::generate_trajectories_poll_period_ms(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::ground_estimate_update_period_ms(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::ground_estimate_window_size(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::ground_frame_id(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::hover_by_object_max_euc_dist(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::hover_on_cable_default_yaw_rate(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::hover_on_cable_default_z_velocity(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::hover_under_cable_on_aborted_cable_landing(), iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::init_sleep_time_ms(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::init_sleep_time_ms(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::initBehaviorStateParameters(), iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator::initMPCParametersObject(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::inter_pos_window_size(), iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::kf_q(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::kf_q(), iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::kf_r(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::kf_r(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::land_cnt_timeout(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::landed_altitude_threshold(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::landed_altitude_threshold(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::landed_on_powerline_non_offboard_max_euc_distance(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::maneuver_evaluate_done_poll_ms(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::maneuver_execution_period_ms(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::maneuver_queue_size(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::maneuver_register_update_timeout_s(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::maneuver_start_timeout_s(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::maneuver_wait_for_execute_poll_ms(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::matching_line_max_dist(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::max_lines(), iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::max_point_dist(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::max_point_dist(), iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::min_point_dist(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::min_point_dist(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::minimum_target_altitude(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::minimum_target_altitude(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::mmwave_frame_id(), iii_drone::perception::hough_transformer_node::HoughTransformerConfigurator::mmwave_frame_id(), iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::mmwave_frame_id(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::mmwave_frame_id(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::MPC_N(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::MPC_use_state_feedback(), iii_drone::perception::hough_transformer_node::HoughTransformerConfigurator::n_lines_include(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::no_maneuver_idle_cnt_s(), iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::odometry_callback_period_ms(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::odometry_callback_period_ms(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::offboard_cnt_timeout(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::on_cable_control_mode(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::on_cable_max_euc_distance(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::on_cable_upwards_thrust(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::on_cable_upwards_velocity(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::px4_offboard_mode_ids(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::reached_position_euclidean_distance_threshold(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::reached_position_euclidean_distance_threshold(), iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestratorConfigurator::simulation(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::simulation(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::strict_max_point_dist(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::strict_min_point_dist(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::strict_view_cone_slope(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::target_cable_cnt_timeout(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::target_cable_fixed_position_distance_threshold(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::target_cable_safety_margin_distance_threshold(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::target_cable_safety_margin_max_euc_acceleration(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::target_cable_safety_margin_max_euc_distance(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::target_cable_safety_margin_max_euc_velocity(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::target_cable_safety_margin_max_yaw_distance(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::target_cable_safety_margin_max_yaw_velocity(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::target_cable_set_point_truncate_distance_threshold(), iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestratorConfigurator::under_cable_target_distance(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::update_home_position(), iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator::updateMPCParametersObjectCallback(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::use_cartesian_PID(), iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestratorConfigurator::use_charger_gripper_info(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::use_gripper_status_condition(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::use_ground_altitude_offset(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::use_nans_when_hovering(), iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::view_cone_slope(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::view_cone_slope(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::world_frame_id(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::world_frame_id(), iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator::world_frame_id(), iii_drone::perception::hough_transformer_node::HoughTransformerConfigurator::world_frame_id(), iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::world_frame_id(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::world_frame_id(), and iii_drone::utils::drone_frame_broadcaster_node::DroneFrameBroadcasterConfigurator::world_frame_id().
GetParameters()
std::vector< rclcpp::Parameter > Configurator::GetParameters (const std::vector< std::string > & names) const
Gets multiple parameters.
Parameters
names Names of the parameters
Returns
std::vector<rclcpp::Parameter> Vector of parameters
Definition at line 155 of file configurator.cpp.
{
    std::shared_lock<std::shared_mutex> lock(parameters_mutex_);
    std::vector<rclcpp::Parameter> parameters;
    // Search for the parameter:
    for (auto & name : names) {
        // Check if the parameter is in the list of parameters:
        for (auto & p : parameters_) {
            if (p.get_name() == name) {
                parameters.push_back(p);
                break;
            }
        }
    }
    if (parameters.size() != names.size()) {
        std::string fatal_message = "Configurator::GetParameters(): Some parameters could not be found.";
        RCLCPP_FATAL(
            node_->get_logger(),
            fatal_message.c_str()
        );
        throw std::runtime_error(fatal_message);
    }
    return parameters;
}
References GetParameterTypeString(), node_, parameters_, and parameters_mutex_.
Referenced by GetParameter().
GetParameterTypeString()
template<typename T > template std::string Configurator::GetParameterTypeString< float > () static
Static function for getting string representation of a parameter type from template type.
Template Parameters
T Type of the parameter
Returns
String representation of the parameter type
Definition at line 258 of file configurator.cpp.
{
    if (std::is_same<T, bool>::value) {
        return "bool";
    } else if (std::is_same<T, int>::value) {
        return "int";
    } else if (std::is_same<T, float>::value) {
        return "float";
    } else if (std::is_same<T, double>::value) {
        return "float";
    } else if (std::is_same<T, std::string>::value) {
        return "string";
    } else if (std::is_same<T, std::vector<bool>>::value) {
        return "bool_array";
    } else if (std::is_same<T, std::vector<int>>::value) {
        return "int_array";
    } else if (std::is_same<T, std::vector<float>>::value) {
        return "float_array";
    } else if (std::is_same<T, std::vector<double>>::value) {
        return "float_array";
    } else if (std::is_same<T, std::vector<std::string>>::value) {
        return "string_array";
    } else {
        std::string fatal_message = "Configurator::GetParameterTypeString(): Parameter type not supported.";
        throw std::runtime_error(fatal_message);
    }
}
References GetParameterTypeString().
Referenced by iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator::declareMPCParameters(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::declareNodeParameters(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::declareNodeParameters(), iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestratorConfigurator::declareNodeParameters(), iii_drone::perception::hough_transformer_node::HoughTransformerConfigurator::declareNodeParameters(), iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::declareNodeParameters(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::declareNodeParameters(), DeclareParameter(), GetParameter(), GetParameters(), GetParameterTypeString(), iii_drone::perception::hough_transformer_node::HoughTransformerConfigurator::HoughTransformerConfigurator(), iii_drone::perception::hough_transformer_node::HoughTransformerConfigurator::HoughTransformerConfigurator(), iii_drone::perception::hough_transformer_node::HoughTransformerConfigurator::houghTransformerConfiguratorParameterChangeCallback(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::initBehaviorStateParameters(), iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator::initMPCParametersObject(), parameterEventCallback(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::plMapperOnParameterChange(), iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::PowerlineDirectionComputerConfigurator(), iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::PowerlineDirectionComputerConfigurator(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::PowerlineMapperConfigurator(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::PowerlineMapperConfigurator(), PrintParameters(), sendDeclareParameterRequest(), sendGetParameterRequest(), sendGetParametersRequest(), SyncParameters(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::updateBehavorStateParametersObjectCallback(), iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator::updateMPCParametersObjectCallback(), and iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::updateParametersObjectsCallback().
parameterEventCallback()
void Configurator::parameterEventCallback (rcl_interfaces::msg::ParameterEvent parameter_event) private
Definition at line 332 of file configurator.cpp.
{
    std::unique_lock<std::shared_mutex> lock(parameters_mutex_);
    // Search for the parameter:
    for (auto & p : parameter_event.changed_parameters) {
        // Check if the parameter is in the list of parameters:
        for (unsigned int i = 0; i < parameters_.size(); i++) {
            rclcpp::Parameter & parameter = parameters_[i];
            if (parameter.get_name() == p.name) {
                if (p.value.type != parameter.get_type()) {
                    std::string fatal_message = "Configurator::parameterEventCallback(): Parameter " + p.name + " has type " + std::to_string(p.value.type) + " but expected type " + std::to_string(parameter.get_type()) + ".";
                    RCLCPP_FATAL(
                        node_->get_logger(),
                        fatal_message.c_str()
                    );
                    throw std::runtime_error(fatal_message);
                }
                parameters_[i] = rclcpp::Parameter::from_parameter_msg(p);
                if (after_parameter_change_callback_ != nullptr) {
                    after_parameter_change_callback_(parameters_[i]);
                }
                break;
            }
        }
    }
}
References after_parameter_change_callback_, GetParameterTypeString(), node_, parameters_, and parameters_mutex_.
Referenced by Configurator(), and Configurator().
PrintParameters()
void Configurator::PrintParameters () const
Prints all parameters to the console.
Returns
void
Definition at line 310 of file configurator.cpp.
{
    std::shared_lock<std::shared_mutex> lock(parameters_mutex_);
    RCLCPP_INFO(
        node_->get_logger(),
        "Configurator::PrintParameters(): Printing parameters:"
    );
    for (auto & p : parameters_) {
        RCLCPP_INFO(
            node_->get_logger(),
            "Configurator::PrintParameters(): %s: %s",
            p.get_name().c_str(),
            p.value_to_string().c_str()
        );
    }
}
References GetParameterTypeString(), node_, parameters_, and parameters_mutex_.
sendDeclareParameterRequest()
bool Configurator::sendDeclareParameterRequest (const std::string & name, const std::string & type, std::string & message) private
Sends a DeclareParameter request to the ConfigurationServer node, which will declare the parameter in the parameter server.
Parameters
name Name of the parameter
type Type string representation of the parameter
Returns
bool True if the parameter was declared successfully, false otherwise
Definition at line 374 of file configurator.cpp.
  {
    // Call DeclareParameter service:
    auto request = std::make_shared<iii_drone_interfaces::srv::DeclareParameter::Request>();
    request->name = name;
    request->type = type;
    // Wait for service:
    if (!declare_parameter_client_->wait_for_service(std::chrono::seconds(5))) {
        std::string fatal_message = "Configurator::DeclareParameter(): Service DeclareParameter not available after 5 seconds.";
        RCLCPP_FATAL(
            node_->get_logger(),
            fatal_message.c_str()
        );
        throw std::runtime_error(fatal_message);
    }
    if (!declare_parameter_client_->service_is_ready()) {
        std::string fatal_message = "Configurator::DeclareParameter(): Service DeclareParameter not available.";
        RCLCPP_FATAL(
            node_->get_logger(),
            fatal_message.c_str()
        );
        throw std::runtime_error(fatal_message);
    }
    // Call service:
    auto future = declare_parameter_client_->async_send_request(request);
    if(rclcpp::spin_until_future_complete(
        node_->get_node_base_interface(),
        future
    ) != rclcpp::FutureReturnCode::SUCCESS) {
        std::cout << "6.7" << std::endl;
        RCLCPP_FATAL(
            node_->get_logger(),
            "Configurator::sendDeclareParameterRequest(): Service DeclareParameter timed out."
        );
        throw std::runtime_error("Failed to call service DeclareParameter.");
    }
    if (!future.valid()) {
        std::cout << "6.8" << std::endl;
        RCLCPP_FATAL(
            node_->get_logger(),
            "Configurator::sendDeclareParameterRequest(): Service DeclareParameter failed."
        );
        throw std::runtime_error("Failed to call service DeclareParameter.");
    }
    auto result = future.get();
    message = result->message;
    return result->succeeded;
}
References declare_parameter_client_, GetParameterTypeString(), and node_.
Referenced by DeclareParameter().
sendGetParameterRequest()
bool Configurator::sendGetParameterRequest (const std::string & name, rclcpp::Parameter & parameter) private
Sends a GetParameters request to the ConfigurationServer node, which will return the parameter.
Parameters
name Name of the parameter
parameter Parameter out reference
Returns
bool True if the parameter could be fetched.
Definition at line 453 of file configurator.cpp.
  {
    std::vector<std::string> names;
    names.push_back(name);
    std::vector<rclcpp::Parameter> parameters;
    if (!sendGetParametersRequest(
            names,
            parameters
        )
    ) {
        return false;
    }
    parameter = parameters[0];
    return true;
}
References GetParameterTypeString(), and sendGetParametersRequest().
Referenced by DeclareParameter().
sendGetParametersRequest()
bool Configurator::sendGetParametersRequest (const std::vector< std::string > & names, std::vector< rclcpp::Parameter > & parameters) private
Sends a GetParameters request to the ConfigurationServer node, which will return the parameters.
Parameters
names Names of the parameters
parameters Parameters out reference
Returns
bool True if the parameters could be fetched.
Definition at line 479 of file configurator.cpp.
  {
    // Call GetParameters service:
    auto request = std::make_shared<rcl_interfaces::srv::GetParameters::Request>();
    request->names = names;
    // Wait for service:
    if (!get_parameters_client_->wait_for_service(std::chrono::seconds(5))) {
        std::string fatal_message = "Configurator::GetParameter(): Service GetParameter not available after 5 seconds.";
        RCLCPP_FATAL(
            node_->get_logger(),
            fatal_message.c_str()
        );
        throw std::runtime_error(fatal_message);
    }
    // Call service:
    auto future = get_parameters_client_->async_send_request(request);
    // Wait for result:
    if (rclcpp::spin_until_future_complete(
            node_->get_node_base_interface(),
            future
        ) != rclcpp::FutureReturnCode::SUCCESS
    ) {
        RCLCPP_FATAL(
            node_->get_logger(),
            "Configurator::sendGetParametersRequest(): Service GetParameters timed out."
        );
        throw std::runtime_error("Failed to call service GetParameters.");
    }
    if (!future.valid()) {
        RCLCPP_FATAL(
            node_->get_logger(),
            "Configurator::sendGetParametersRequest(): Service GetParameters failed."
        );
        throw std::runtime_error("Failed to call service GetParameters.");
    }
    auto result = future.get();
    // Check if the service call was successful:
    if (result->values.size() != names.size()) {
        RCLCPP_FATAL(
            node_->get_logger(),
            "Configurator::sendGetParametersRequest(): Service GetParameters failed, some parameters could not be found."
        );
        throw std::runtime_error("Failed to call service GetParameters failed, some parameters could not be found.");
    }
    parameters.resize(names.size());
    for (unsigned int i = 0; i < names.size(); i++) {
        parameters[i] = rclcpp::Parameter(
            names[i],
            result->values[i]
        );
    }
    return true;
}
References get_parameters_client_, GetParameterTypeString(), and node_.
Referenced by sendGetParameterRequest(), and SyncParameters().
SyncParameters()
void Configurator::SyncParameters (const std::vector< std::string > & names = {})
Synchronizes parameters with the parameter server. Should never be necessary.
Parameters
names Names of the parameters, default is empty (all parameters)
Returns
void
Definition at line 194 of file configurator.cpp.
{
    std::vector<std::string> names_to_sync;
    if (names.size() == 0) {
        // Get all parameters:
        for (auto & p : parameters_) {
            names_to_sync.push_back(p.get_name());
        }
    } else {
        names_to_sync = names;
    }
    std::vector<rclcpp::Parameter> parameters;
    if (!sendGetParametersRequest(
            names_to_sync,
            parameters
        )
    ) {
        std::string fatal_message = "Configurator::SyncParameters(): Failed to get parameters.";
        RCLCPP_FATAL(
            node_->get_logger(),
            fatal_message.c_str()
        );
        throw std::runtime_error(fatal_message);
    }
    // Check if the parameters are correct:
    for (unsigned int i = 0; i < parameters.size(); i++) {
        if (parameters[i].get_type() != parameters_[i].get_type() || parameters[i].get_name() != parameters_[i].get_name()) {
            std::string fatal_message = "Configurator::SyncParameters(): Parameter " + parameters[i].get_name() + " has type " + std::to_string(parameters[i].get_type()) + " but expected type " + std::to_string(parameters_[i].get_type()) + ".";
            RCLCPP_FATAL(
                node_->get_logger(),
                fatal_message.c_str()
            );
            throw std::runtime_error(fatal_message);
        }
    }
    std::unique_lock<std::shared_mutex> lock(parameters_mutex_);
    // Update parameters:
    parameters_ = parameters;
}
References GetParameterTypeString(), node_, parameters_, parameters_mutex_, and sendGetParametersRequest().
Member Data Documentation
after_parameter_change_callback_
std::function<void(const rclcpp::Parameter &) iii_drone::configuration::Configurator::after_parameter_change_callback_) private
Definition at line 183 of file configurator.hpp.
Referenced by parameterEventCallback().
declare_parameter_client_
rclcpp::Client<iii_drone_interfaces::srv::DeclareParameter>::SharedPtr iii_drone::configuration::Configurator::declare_parameter_client_ private
DeclareParameter service client.
Definition at line 159 of file configurator.hpp.
Referenced by Configurator(), Configurator(), and sendDeclareParameterRequest().
get_parameters_client_
rclcpp::Client<rcl_interfaces::srv::GetParameters>::SharedPtr iii_drone::configuration::Configurator::get_parameters_client_ private
GetParameters service client.
Definition at line 164 of file configurator.hpp.
Referenced by Configurator(), Configurator(), and sendGetParametersRequest().
node_
rclcpp::Node* iii_drone::configuration::Configurator::node_ protected
Definition at line 138 of file configurator.hpp.
Referenced by Configurator(), Configurator(), DeclareParameter(), GetParameters(), parameterEventCallback(), PrintParameters(), sendDeclareParameterRequest(), sendGetParametersRequest(), and SyncParameters().
parameter_events_subscriber_
rclcpp::Subscription<rcl_interfaces::msg::ParameterEvent>::SharedPtr iii_drone::configuration::Configurator::parameter_events_subscriber_ private
/parameter_events subscriber.
Definition at line 169 of file configurator.hpp.
Referenced by Configurator(), and Configurator().
parameters_
std::vector<rclcpp::Parameter> iii_drone::configuration::Configurator::parameters_ private
Definition at line 144 of file configurator.hpp.
Referenced by DeclareParameter(), GetParameters(), parameterEventCallback(), PrintParameters(), and SyncParameters().
parameters_mutex_
std::shared_mutex iii_drone::configuration::Configurator::parameters_mutex_ mutable private
Definition at line 154 of file configurator.hpp.
Referenced by DeclareParameter(), GetParameters(), parameterEventCallback(), PrintParameters(), and SyncParameters().
qos_
std::unique_ptr<rclcpp::QoS> iii_drone::configuration::Configurator::qos_ = nullptr private
QoS settings for the parameter event subscription.
Definition at line 149 of file configurator.hpp.
Referenced by Configurator().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/configuration/configurator.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/configuration/configurator.cpp