III-Drone: iii_drone::control::TrajectoryGenerator Class Reference
iii_drone::control::TrajectoryGenerator Class Reference
#include <trajectory_generator.hpp>
Public Member Functions
TrajectoryGenerator (std::shared_ptr< const MPCParameters > positional_mpc_params, std::shared_ptr< const MPCParameters > cable_landing_mpc_params, std::shared_ptr< const MPCParameters > cable_takeoff_mpc_params)
Constructor.
ReferenceTrajectory ComputeReferenceTrajectory (State state, Reference reference, bool set_target, bool reset, MPC_mode_t mpc_mode)
Computes the reference trajectory for the MPC.
Private Member Functions
void setupMPC (std::shared_ptr< const MPCParameters > mpc_params, bool set_target, bool first, bool reset, iii_drone::control::State &state, iii_drone::control::State &prev_state, iii_drone::control::Reference &reference, iii_drone::control::Reference &reference_internal, int &reset_target, int &reset_trajectory, int &reset_bounds, int &reset_weights, bool &use_state_feedback, double planned_traj[120], double x[6], double target[6])
Sets up the MPC.
void stepMPC (double *x, double *u, double *planned_traj, double *target, int reset_target, int reset_trajectory, int reset_bounds, int reset_weights, std::shared_ptr< const MPCParameters > mpc_parameters)
Runs the actual MPC one step.
ReferenceTrajectory postProcessMPC (rclcpp::Time t0, int N, double dt, double *u, double *planned_traj, double target_yaw)
Post processes the MPC results.
Private Attributes
std::shared_ptr< const MPCParameters > positional_mpc_params_
The MPC parameters.
std::shared_ptr< const MPCParameters > cable_landing_mpc_params_
std::shared_ptr< const MPCParameters > cable_takeoff_mpc_params_
Detailed Description
Definition at line 46 of file trajectory_generator.hpp.
Constructor & Destructor Documentation
TrajectoryGenerator()
TrajectoryGenerator::TrajectoryGenerator (std::shared_ptr< const MPCParameters > positional_mpc_params, std::shared_ptr< const MPCParameters > cable_landing_mpc_params, std::shared_ptr< const MPCParameters > cable_takeoff_mpc_params)
Constructor.
Parameters
positional_mpc_params The positional MPC parameters
cable_landing_mpc_params The cable landing MPC parameters
cable_takeoff_mpc_params The cable takeoff MPC parameters
Definition at line 14 of file trajectory_generator.cpp.
  : positional_mpc_params_(positional_mpc_params),
    cable_landing_mpc_params_(cable_landing_mpc_params),
    cable_takeoff_mpc_params_(cable_takeoff_mpc_params) { }
Member Function Documentation
ComputeReferenceTrajectory()
ReferenceTrajectory TrajectoryGenerator::ComputeReferenceTrajectory (State state, Reference reference, bool set_target, bool reset, MPC_mode_t mpc_mode)
Computes the reference trajectory for the MPC.
Parameters
state The current vehicle state
reference The reference state
set_target Whether to update the target state
reset Whether to reset the MPC
mpc_mode The MPC mode
Returns
The MPC reference trajectory
Definition at line 22 of file trajectory_generator.cpp.
  {
    // Variables:
    std::shared_ptr<const MPCParameters> mpc_params;
    switch(mpc_mode) {
        case MPC_mode_t::positional:
            mpc_params = positional_mpc_params_;
            break;
        case MPC_mode_t::cable_landing:
            mpc_params = cable_landing_mpc_params_;
            break;
        case MPC_mode_t::cable_takeoff:
            mpc_params = cable_takeoff_mpc_params_;
            break;
    }
    static bool first = true;
    static int MPC_N = mpc_params->N();
    static double dt = mpc_params->dt();
    static bool use_state_feedback = mpc_params->use_state_feedback();
    static double planned_traj[120];
    static double x[6];
    static double u[3];
    static double target[6];
    static int reset_target;
    static int reset_trajectory;
    static int reset_bounds;
    static int reset_weights;
    static State prev_state = state;
    static Reference ref;
    rclcpp::Time t0 = state.stamp();
    setupMPC(
        mpc_params,
        set_target,
        first,
        reset,
        state,
        prev_state,
        reference,
        ref,
        reset_target,
        reset_trajectory,
        reset_bounds,
        reset_weights,
        use_state_feedback,
        planned_traj,
        x,
        target
    );
    prev_state = state;
    // Run MPC:
    stepMPC(
        x,
        u,
        planned_traj,
        target,
        reset_target,
        reset_trajectory,
        reset_bounds,
        reset_weights,
        mpc_params
    );
    // Output:
    return postProcessMPC(
        t0,
        MPC_N,
        dt,
        u,
        planned_traj,
        target[5]
    );
}
References iii_drone::control::cable_landing, cable_landing_mpc_params_, iii_drone::control::cable_takeoff, cable_takeoff_mpc_params_, iii_drone::control::positional, positional_mpc_params_, postProcessMPC(), setupMPC(), iii_drone::control::State::stamp(), and stepMPC().
Referenced by iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNode::computeReferenceTrajectoryCallback().
postProcessMPC()
ReferenceTrajectory TrajectoryGenerator::postProcessMPC (rclcpp::Time t0, int N, double dt, double * u, double * planned_traj, double target_yaw) private
Post processes the MPC results.
Parameters
t0 The MPC start time
N The MPC horizon
dt The MPC timestep
u The MPC control input
planned_traj The MPC planned trajectory
target_yaw The MPC target yaw
Returns
The MPC reference trajectory
Definition at line 342 of file trajectory_generator.cpp.
  {
    std::vector<Reference> trajectory_vector;
    trajectory_vector.resize(N);
    rclcpp::Time stamp = t0;
    for (int i = 0; i < N; i++) {
        point_t reference_position(
            planned_traj[i*6+0],
            planned_traj[i*6+1],
            planned_traj[i*6+2]
        );
        vector_t reference_velocity(
            planned_traj[i*6+3],
            planned_traj[i*6+4],
            planned_traj[i*6+5]
        );
        Reference ref;
        if (i == 0) {
            vector_t reference_acceleration(
                u[0],
                u[1],
                u[2]
            );
            ref = Reference(
                reference_position,
                target_yaw,
                reference_velocity,
                0,
                reference_acceleration,
                NAN,
                stamp
            );
        } else {
            ref = Reference(
                reference_position,
                target_yaw,
                reference_velocity,
                0,
                vector_t::Zero(),
                NAN,
                stamp
            );
        }
        trajectory_vector.push_back(ref);
        stamp = rclcpp::Time(stamp.nanoseconds() + dt*1e9);
    }
    return ReferenceTrajectory(trajectory_vector);
}
Referenced by ComputeReferenceTrajectory().
setupMPC()
void TrajectoryGenerator::setupMPC (std::shared_ptr< const MPCParameters > mpc_params, bool set_target, bool first, bool reset, iii_drone::control::State & state, iii_drone::control::State & prev_state, iii_drone::control::Reference & reference, iii_drone::control::Reference & reference_internal, int & reset_target, int & reset_trajectory, int & reset_bounds, int & reset_weights, bool & use_state_feedback, double planned_traj[120], double x[6], double target[6]) private
Sets up the MPC.
Parameters
mpc_params The MPC parameters
set_target Whether to update the target state
first Whether this is the first MPC call
reset Whether to reset the MPC
state The current vehicle state
prev_state The previous vehicle state
reference The reference state
reference_internal The internal reference state
reset_target Whether to reset the MPC target state
reset_trajectory Whether to reset the MPC trajectory
reset_bounds Whether to reset the MPC bounds
reset_weights Whether to reset the MPC weights
use_state_feedback Whether to use state feedback
planned_traj The MPC planned trajectory
x The MPC state
target The MPC target state
Returns
void
Definition at line 117 of file trajectory_generator.cpp.
  {
    if (set_target || first || reset) {
        reference_internal = reference;
    }
    if (first || reset) {
        prev_state = state;
    }
    // Initialization:
    if (reset) {
        reset_trajectory = 1;
        reset_bounds = 1;
        reset_weights = 1;
    } else {
        reset_trajectory = 0;
        reset_bounds = 0;
        reset_weights = 0;
    }
    reset_target = set_target;
    if (reset_trajectory) {
        use_state_feedback = mpc_params->use_state_feedback();
    }
    if (set_target) {
        point_t reference_position = reference_internal.position();
        vector_t reference_velocity = reference_internal.velocity();
        for (int i = 0; i < 3; i++) {
            target[i] = reference_position[i];
            target[i+3] = reference_velocity[i];
        }
    }
    if (first || reset) {
        point_t vehicle_position = state.position();
        for (int i = 0; i < mpc_params->N(); i++) {
            for (int j = 0; j < 3; j++) {
                planned_traj[i*6+j] = vehicle_position[j];
            }
            for (int j = 3; j < 6; j++) {
                planned_traj[i*6+j] = 0;
            }
        }
        for (int i = 0; i < 6; i++) x[i] = planned_traj[i];
    }
    // No state progression:
    if (use_state_feedback || reset) {
        point_t vehicle_position = state.position();
        vector_t vehicle_velocity = state.velocity();
        for (int i = 0; i < 3; i++) {
            x[i] = vehicle_position[i];
            x[i+3] = vehicle_velocity[i];
        }
    }
}
References iii_drone::control::Reference::position(), iii_drone::control::State::position(), iii_drone::control::Reference::velocity(), and iii_drone::control::State::velocity().
Referenced by ComputeReferenceTrajectory().
stepMPC()
void TrajectoryGenerator::stepMPC (double * x, double * u, double * planned_traj, double * target, int reset_target, int reset_trajectory, int reset_bounds, int reset_weights, std::shared_ptr< const MPCParameters > mpc_parameters) private
Runs the actual MPC one step.
Parameters
x The MPC state
u The MPC control input
planned_traj The MPC planned trajectory
target The MPC target state
reset_target Whether to reset the MPC target state
reset_trajectory Whether to reset the MPC trajectory
reset_bounds Whether to reset the MPC bounds
reset_weights Whether to reset the MPC weights
mpc_parameters The MPC parameters
Returns
void
Definition at line 222 of file trajectory_generator.cpp.
  {
    const int N = 10;
    static pos_MPC::struct10_T Info;
    static pos_MPC::struct4_T mpcmovestate;
    static pos_MPC::struct5_T mpconlinedata;
    // if (reset_target && reset_bounds && reset_weights && reset_trajectory) {
    //  RCLCPP_INFO(this->get_logger(), "Resetting MPC fully");
    // }
    if (reset_trajectory) {
        for(int i = 0; i < 81; i++) mpcmovestate.Covariance[i] = 0;
        for(int i=0; i < 3; i++) mpcmovestate.Disturbance[i] = 0;
        for(int i = 0; i < 6*2*N; i++) mpcmovestate.iA[i] = 0;
        for(int i=0; i < 3; i++) mpcmovestate.LastMove[i] = 0;
        for(int i=0; i < 6; i++) mpcmovestate.Plant[i] = x[i];
    }
    if (reset_bounds) {
        vector_t a_max = mpc_parameters->a_max();
        vector_t v_max = mpc_parameters->v_max();
        mpconlinedata.limits.umax[0] = a_max[0];
        mpconlinedata.limits.umax[1] = a_max[1];
        mpconlinedata.limits.umax[2] = a_max[2];
        mpconlinedata.limits.umin[0] = -a_max[0];
        mpconlinedata.limits.umin[1] = -a_max[1];
        mpconlinedata.limits.umin[2] = -a_max[2];
        mpconlinedata.limits.ymax[0] = 100000;
        mpconlinedata.limits.ymax[1] = 100000;
        mpconlinedata.limits.ymax[2] = 100000;
        mpconlinedata.limits.ymax[3] = v_max[0];
        mpconlinedata.limits.ymax[4] = v_max[1];
        mpconlinedata.limits.ymax[5] = v_max[2];
        mpconlinedata.limits.ymin[0] = -100000;
        mpconlinedata.limits.ymin[1] = -100000;
        mpconlinedata.limits.ymin[2] = -100000;
        mpconlinedata.limits.ymin[3] = -v_max[0];
        mpconlinedata.limits.ymin[4] = -v_max[1];
        mpconlinedata.limits.ymin[5] = -v_max[2];
    }
    if (reset_target) {
        // RCLCPP_DEBUG(this->get_logger(), "MPC resetting Target");
        // RCLCPP_DEBUG(this->get_logger(), "MPC Thread State: %f, %f, %f", x[0], x[1], x[2]);
        // RCLCPP_DEBUG(this->get_logger(), "MPC Thread Target: %f, %f, %f", target[0], target[1], target[2]);
        for (int i = 0; i < 6; i++) {
            mpconlinedata.signals.ref[i] = target[i];
        }
    }
    if (reset_weights) {
        vector_t wp = mpc_parameters->wp();
        vector_t wv = mpc_parameters->wv();
        vector_t wa = mpc_parameters->wa();
        vector_t wj = mpc_parameters->wj();
        mpconlinedata.weights.du[0] = wj[0];
        mpconlinedata.weights.du[1] = wj[1];
        mpconlinedata.weights.du[2] = wj[2];
        mpconlinedata.weights.u[0] = wa[0];
        mpconlinedata.weights.u[1] = wa[1];
        mpconlinedata.weights.u[2] = wa[2];
        mpconlinedata.weights.y[0] = wp[0];
        mpconlinedata.weights.y[1] = wp[1];
        mpconlinedata.weights.y[2] = wp[2];
        mpconlinedata.weights.y[3] = wv[0];
        mpconlinedata.weights.y[4] = wv[1];
        mpconlinedata.weights.y[5] = wv[2];
    }
    for(int i = 0; i < 6; i++) mpconlinedata.signals.ym[i] = x[i];
    // if (mpc_mode == cable_takeoff) {
    //  RCLCPP_DEBUG(this->get_logger(), "MPC Thread Target stored: %f, %f, %f", mpconlinedata.signals.ref[0], mpconlinedata.signals.ref[1], mpconlinedata.signals.ref[2]);
    //  RCLCPP_DEBUG(this->get_logger(), "MPC Thread State stored: %f, %f, %f", mpconlinedata.signals.ym[0], mpconlinedata.signals.ym[1], mpconlinedata.signals.ym[2]);
    //  RCLCPP_DEBUG(this->get_logger(), "MPC Thread wxyz stored: %f, %f, %f, %f", mpconlinedata.weights.y[0], mpconlinedata.weights.y[1], mpconlinedata.weights.y[2]);
    //  RCLCPP_DEBUG(this->get_logger(), "MPC Thread wvxyz stored: %f, %f, %f, %f", mpconlinedata.weights.y[3], mpconlinedata.weights.y[4], mpconlinedata.weights.y[5]);
    // }
    pos_MPC::coder::mpcmoveCodeGeneration(&mpcmovestate, &mpconlinedata, u, &Info);
    for (int j = 0; j < 6; j++) x[j] = Info.Yopt[j*(N+1)+1];
    for (int i = 0; i < N; i++) {
        for (int j = 0; j < 6; j++) planned_traj[i*6+j] = Info.Yopt[j*(N+1)+(i+1)];
    }
}
References pos_MPC::struct4_T::Covariance, pos_MPC::struct4_T::Disturbance, pos_MPC::struct7_T::du, pos_MPC::struct4_T::iA, pos_MPC::struct4_T::LastMove, pos_MPC::struct5_T::limits, pos_MPC::coder::mpcmoveCodeGeneration(), pos_MPC::struct4_T::Plant, pos_MPC::struct6_T::ref, pos_MPC::struct5_T::signals, pos_MPC::struct7_T::u, pos_MPC::struct8_T::umax, pos_MPC::struct8_T::umin, pos_MPC::struct5_T::weights, pos_MPC::struct7_T::y, pos_MPC::struct6_T::ym, pos_MPC::struct8_T::ymax, pos_MPC::struct8_T::ymin, and pos_MPC::struct10_T::Yopt.
Referenced by ComputeReferenceTrajectory().
Member Data Documentation
cable_landing_mpc_params_
std::shared_ptr<const MPCParameters> iii_drone::control::TrajectoryGenerator::cable_landing_mpc_params_ private
Definition at line 84 of file trajectory_generator.hpp.
Referenced by ComputeReferenceTrajectory().
cable_takeoff_mpc_params_
std::shared_ptr<const MPCParameters> iii_drone::control::TrajectoryGenerator::cable_takeoff_mpc_params_ private
Definition at line 84 of file trajectory_generator.hpp.
Referenced by ComputeReferenceTrajectory().
positional_mpc_params_
std::shared_ptr<const MPCParameters> iii_drone::control::TrajectoryGenerator::positional_mpc_params_ private
The MPC parameters.
Definition at line 84 of file trajectory_generator.hpp.
Referenced by ComputeReferenceTrajectory().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/trajectory_generator.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/trajectory_generator.cpp