III-Drone: iii_drone::control::flight_controller_node::FlightController Class Reference
iii_drone::control::flight_controller_node::FlightController Class Reference
The trajectory controller node.
#include <flight_controller_node.hpp>
Public Member Functions
FlightController (const std::string &node_name="flight_controller", const std::string &node_namespace="/control/flight_controller", const rclcpp::NodeOptions &options=rclcpp::NodeOptions())
Construct a new Trajectory Controller object.
~FlightController ()
Destroy the Trajectory Controller object.
Private Attributes
CombinedDroneAwarenessHandler::SharedPtr combined_drone_awareness_handler_
maneuver::ManeuverScheduler::SharedPtr maneuver_scheduler_
FlightControllerConfigurator configurator_
The trajectory controller node configurator.
rclcpp::Publisher< px4_msgs::msg::TrajectorySetpoint >::SharedPtr trajectory_setpoint_pub_
PX4 trajectory setpoint publisher.
iii_drone::utils::Atomic< iii_drone::adapters::px4::TrajectorySetpointAdapter > trajectory_setpoint_adapter_
Trajectory setpoint adapter.
std::shared_ptr< tf2_ros::TransformListener > transform_listener_ {nullptr}
ROS2 transform listener.
tf2_ros::Buffer::SharedPtr tf_buffer_
ROS2 transform buffer.
std::unique_ptr< tf2_ros::TransformBroadcaster > tf_broadcaster_
ROS2 transform broadcaster.
Detailed Description
The trajectory controller node.
Definition at line 146 of file flight_controller_node.hpp.
Constructor & Destructor Documentation
FlightController()
FlightController::FlightController (const std::string & node_name = "flight_controller", const std::string & node_namespace = "/control/flight_controller", const rclcpp::NodeOptions & options = rclcpp::NodeOptions())
Construct a new Trajectory Controller object.
Parameters
node_name The name of the node
node_namespace The namespace of the node
options The node options
Definition at line 15 of file flight_controller_node.cpp.
  : Node(
    node_name,
    node_namespace,
    options
),  configurator_(this),
    vehicle_odometry_adapter_history_(2) { //,
// request_queue_(1),
// request_reply_queue_(2),
// request_reply_poll_rate_(50ms),
// request_completion_poll_rate_(100ms) {
    if (configurator_.use_cartesian_PID() && configurator_.always_hover_in_offboard()) {
        RCLCPP_FATAL(
            this->get_logger(),
            "use_cartesian_PID and always_hover_in_offboard are not compatible"
        );
        exit(1);
    }
    quaternion_t temp_q(1,0,0,0);
    vector_t temp_vec(0,0,0);
    odom_q_ = temp_q;
    odom_pos_ = temp_vec;
    odom_vel_ = temp_vec;
    odom_last_vel_ = temp_vec;
    odom_acc_ = temp_vec;
    odom_ang_vel_ = temp_vec;
    // tf
    tf_buffer_ = std::make_unique<tf2_ros::Buffer>(this->get_clock());
    transform_listener_ = std::make_shared<tf2_ros::TransformListener>(*tf_buffer_);
    tf_broadcaster_ = std::make_unique<tf2_ros::TransformBroadcaster>(*this);
    // Takeoff action:
    this->takeoff_server_ = rclcpp_action::create_server<Takeoff>(
        this,
        "takeoff",
        std::bind(&FlightController::handleGoalTakeoff, this, std::placeholders::_1, std::placeholders::_2),
        std::bind(&FlightController::handleCancelTakeoff, this, std::placeholders::_1),
        std::bind(&FlightController::handleAcceptedTakeoff, this, std::placeholders::_1)
    );
    // Landing action:
    this->landing_server_ = rclcpp_action::create_server<Landing>(
        this,
        "landing",
        std::bind(&FlightController::handleGoalLanding, this, std::placeholders::_1, std::placeholders::_2),
        std::bind(&FlightController::handleCancelLanding, this, std::placeholders::_1),
        std::bind(&FlightController::handleAcceptedLanding, this, std::placeholders::_1)
    );
    // Fly to position action:
    this->fly_to_position_server_ = rclcpp_action::create_server<FlyToPosition>(
        this,
        "fly_to_position",
        std::bind(&FlightController::handleGoalFlyToPosition, this, std::placeholders::_1, std::placeholders::_2),
        std::bind(&FlightController::handleCancelFlyToPosition, this, std::placeholders::_1),
        std::bind(&FlightController::handleAcceptedFlyToPosition, this, std::placeholders::_1)
    );
    // Fly under cable action:
    this->fly_under_cable_server_ = rclcpp_action::create_server<FlyUnderCable>(
        this,
        "fly_under_cable",
        std::bind(&FlightController::handleGoalFlyUnderCable, this, std::placeholders::_1, std::placeholders::_2),
        std::bind(&FlightController::handleCancelFlyUnderCable, this, std::placeholders::_1),
        std::bind(&FlightController::handleAcceptedFlyUnderCable, this, std::placeholders::_1)
    );
    // Cable landing action:
    this->cable_landing_server_ = rclcpp_action::create_server<CableLanding>(
        this,
        "cable_landing",
        std::bind(&FlightController::handleGoalCableLanding, this, std::placeholders::_1, std::placeholders::_2),
        std::bind(&FlightController::handleCancelCableLanding, this, std::placeholders::_1),
        std::bind(&FlightController::handleAcceptedCableLanding, this, std::placeholders::_1)
    );
    // Cable takeoff action:
    this->cable_takeoff_server_ = rclcpp_action::create_server<CableTakeoff>(
        this,
        "cable_takeoff",
        std::bind(&FlightController::handleGoalCableTakeoff, this, std::placeholders::_1, std::placeholders::_2),
        std::bind(&FlightController::handleCancelCableTakeoff, this, std::placeholders::_1),
        std::bind(&FlightController::handleAcceptedCableTakeoff, this, std::placeholders::_1)
    );
    // Arm on cable action:
    this->arm_on_cable_server_ = rclcpp_action::create_server<ArmOnCable>(
        this,
        "arm_on_cable",
        std::bind(&FlightController::handleGoalArmOnCable, this, std::placeholders::_1, std::placeholders::_2),
        std::bind(&FlightController::handleCancelArmOnCable, this, std::placeholders::_1),
        std::bind(&FlightController::handleAcceptedArmOnCable, this, std::placeholders::_1)
    );
    // Disarm on cable action:
    this->disarm_on_cable_server_ = rclcpp_action::create_server<DisarmOnCable>(
        this,
        "disarm_on_cable",
        std::bind(&FlightController::handleGoalDisarmOnCable, this, std::placeholders::_1, std::placeholders::_2),
        std::bind(&FlightController::handleCancelDisarmOnCable, this, std::placeholders::_1),
        std::bind(&FlightController::handleAcceptedDisarmOnCable, this, std::placeholders::_1)
    );
    // Publishers and subscriptions:
    setpoint_pose_pub_ = this->create_publisher<geometry_msgs::msg::PoseStamped>("setpoint_pose", 10);
    offboard_control_mode_pub_ =
        this->create_publisher<px4_msgs::msg::OffboardControlMode>("/fmu/in/offboard_control_mode", 10);
    trajectory_setpoint_pub_ =
        this->create_publisher<px4_msgs::msg::TrajectorySetpoint>("/fmu/in/trajectory_setpoint", 10);
    vehicle_command_pub_ =
        this->create_publisher<px4_msgs::msg::VehicleCommand>("/fmu/in/vehicle_command", 10);
    control_state_pub_ =
        this->create_publisher<iii_drone_interfaces::msg::ControlState>("control_state", 10);
    target_cable_id_pub_ =
        this->create_publisher<std_msgs::msg::Int16>("target_cable_id", 10);
    rclcpp::QoS px4_sub_qos(rclcpp::KeepLast(1));
    px4_sub_qos.transient_local();
    px4_sub_qos.best_effort();
    vehicle_status_sub_ = create_subscription<px4_msgs::msg::VehicleStatus>(
        "/fmu/out/vehicle_status",
        px4_sub_qos,
        [this](px4_msgs::msg::VehicleStatus::ConstSharedPtr msg) {
            vehicle_status_adapter_ = iii_drone::adapters::px4::VehicleStatusAdapter(*msg);
        }
    );
    vehicle_odometry_sub_ = this->create_subscription<px4_msgs::msg::VehicleOdometry>(
        "/fmu/out/vehicle_odometry",
        px4_sub_qos,
        [this](px4_msgs::msg::VehicleOdometry::ConstSharedPtr msg) {
            vehicle_odometry_adapter_history_ = iii_drone::adapters::px4::VehicleOdometryAdapter(*msg);
        }
    );
    powerline_sub_ = this->create_subscription<iii_drone_interfaces::msg::Powerline>(
        "/perception/pl_mapper/powerline",
        10,
        [this](iii_drone_interfaces::msg::Powerline::ConstSharedPtr msg) {
            powerline_adapter_history_ = iii_drone::adapters::PowerlineAdapter(*msg);
        }
    );
    gripper_status_sub_ = this->create_subscription<iii_drone_interfaces::msg::GripperStatus>(
        "/payload/charger_gripper/gripper_status",
        10,
        [this](iii_drone_interfaces::msg::GripperStatus::ConstSharedPtr msg) {
            gripper_status_adapter_.UpdateFromMsg(*msg);
        }
    );
    main_state_machine_timer_ = this->create_wall_timer(
        std::chrono::milliseconds((int)(configurator_.dt()*1000)),
        std::bind(
            &FlightController::stateMachineCallback,
            this
        )
    );
    // RCLCPP debug successfully initilized trajectory controller
    RCLCPP_INFO(this->get_logger(), "Successfully initialized trajectory controller");
}
References iii_drone::control::flight_controller_node::FlightControllerConfigurator::always_hover_in_offboard(), configurator_, iii_drone::control::flight_controller_node::FlightControllerConfigurator::dt(), tf_broadcaster_, tf_buffer_, trajectory_setpoint_pub_, transform_listener_, and iii_drone::control::flight_controller_node::FlightControllerConfigurator::use_cartesian_PID().
~FlightController()
FlightController::~FlightController ()
Destroy the Trajectory Controller object.
Definition at line 193 of file flight_controller_node.cpp.
{
    RCLCPP_INFO(this->get_logger(),  "Shutting down offboard control..");
    // land();
    std::this_thread::sleep_for(std::chrono::milliseconds(50));
}
Member Data Documentation
combined_drone_awareness_handler_
CombinedDroneAwarenessHandler::SharedPtr iii_drone::control::flight_controller_node::FlightController::combined_drone_awareness_handler_ private
Definition at line 194 of file flight_controller_node.hpp.
configurator_
FlightControllerConfigurator iii_drone::control::flight_controller_node::FlightController::configurator_ private
The trajectory controller node configurator.
Definition at line 574 of file flight_controller_node.hpp.
Referenced by FlightController().
maneuver_scheduler_
maneuver::ManeuverScheduler::SharedPtr iii_drone::control::flight_controller_node::FlightController::maneuver_scheduler_ private
Definition at line 196 of file flight_controller_node.hpp.
tf_broadcaster_
std::unique_ptr<tf2_ros::TransformBroadcaster> iii_drone::control::flight_controller_node::FlightController::tf_broadcaster_ private
ROS2 transform broadcaster.
Definition at line 672 of file flight_controller_node.hpp.
Referenced by FlightController().
tf_buffer_
tf2_ros::Buffer::SharedPtr iii_drone::control::flight_controller_node::FlightController::tf_buffer_ private
ROS2 transform buffer.
Definition at line 667 of file flight_controller_node.hpp.
Referenced by FlightController().
trajectory_setpoint_adapter_
iii_drone::utils::Atomic<iii_drone::adapters::px4::TrajectorySetpointAdapter> iii_drone::control::flight_controller_node::FlightController::trajectory_setpoint_adapter_ private
Trajectory setpoint adapter.
Definition at line 636 of file flight_controller_node.hpp.
trajectory_setpoint_pub_
rclcpp::Publisher<px4_msgs::msg::TrajectorySetpoint>::SharedPtr iii_drone::control::flight_controller_node::FlightController::trajectory_setpoint_pub_ private
PX4 trajectory setpoint publisher.
Definition at line 631 of file flight_controller_node.hpp.
Referenced by FlightController().
transform_listener_
std::shared_ptr<tf2_ros::TransformListener> iii_drone::control::flight_controller_node::FlightController::transform_listener_ {nullptr} private
ROS2 transform listener.
Definition at line 662 of file flight_controller_node.hpp.
{nullptr};
Referenced by FlightController().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/_flight_controller_node/flight_controller_node.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/_flight_controller_node/flight_controller_node.cpp