III-Drone: iii_drone::control::TrajectoryGeneratorClient Class Reference
iii_drone::control::TrajectoryGeneratorClient Class Reference
Trajectory generator client class. Exposes API to generate reference trajectories by invoking the trajectory generator service.
#include <trajectory_generator_client.hpp>
Public Types
typedef std::shared_ptr< TrajectoryGeneratorClient > SharedPtr
Shared pointer type.
Public Member Functions
TrajectoryGeneratorClient (rclcpp::Node *node)
Constructor.
void Reset (const iii_drone::control::State &state=iii_drone::control::State())
Resets the client with the current state.
void Cancel ()
Cancels the trajectory generation if it is active.
void ComputeReferenceTrajectoryAsync (const iii_drone::control::State &state, const iii_drone::control::Reference &reference, bool set_reference, bool reset, MPC_mode_t mpc_mode)
Starts generating a trajectory.
void ComputeReferenceTrajectoryBlocking (const iii_drone::control::State &state, const iii_drone::control::Reference &reference, bool set_reference, bool reset, MPC_mode_t mpc_mode, unsigned int poll_period_ms)
Generates a trajectory and blocks until it is done.
iii_drone::control::ReferenceTrajectory GetReferenceTrajectory () const
Returns the reference trajectory.
bool busy () const
Returns true if the trajectory generator is busy.
bool done () const
Returns true if the trajectory generator is done.
Private Member Functions
void serviceResultCallback (const rclcpp::Client< iii_drone_interfaces::srv::ComputeReferenceTrajectory >::SharedFuture future)
Service result callback.
Private Attributes
rclcpp::Node * node_
Node pointer.
rclcpp::Client< iii_drone_interfaces::srv::ComputeReferenceTrajectory >::SharedPtr client_
Service client.
iii_drone::utils::History< iii_drone::adapters::ReferenceTrajectoryAdapter > reference_trajectory_adapter_history_
Reference trajectory adapter history.
iii_drone::utils::Atomic< bool > busy_
Busy flag.
iii_drone::utils::Atomic< bool > done_
Done flag.
rclcpp::Client< iii_drone_interfaces::srv::ComputeReferenceTrajectory >::SharedFuture future_
Service future.
Detailed Description
Trajectory generator client class. Exposes API to generate reference trajectories by invoking the trajectory generator service.
Definition at line 53 of file trajectory_generator_client.hpp.
Member Typedef Documentation
SharedPtr
typedef std::shared_ptr<TrajectoryGeneratorClient> iii_drone::control::TrajectoryGeneratorClient::SharedPtr
Shared pointer type.
Definition at line 140 of file trajectory_generator_client.hpp.
Constructor & Destructor Documentation
TrajectoryGeneratorClient()
TrajectoryGeneratorClient::TrajectoryGeneratorClient (rclcpp::Node * node)
Constructor.
Parameters
node Node pointer
Definition at line 15 of file trajectory_generator_client.cpp.
    : node_(node)
{
    // Create service client
    client_ = node_->create_client<iii_drone_interfaces::srv::ComputeReferenceTrajectory>(
        "/control/trajectory_generator/compute_reference_trajectory"
    );
    // Wait for service
    while (!client_->wait_for_service(std::chrono::seconds(1))) {
        if (!rclcpp::ok()) {
            RCLCPP_ERROR(node_->get_logger(), "Interrupted while waiting for the service. Exiting.");
            rclcpp::shutdown();
        }
        RCLCPP_INFO(node_->get_logger(), "Compute reference trajectory service not available, waiting again...");
    }
    Reset();
}
References client_, node_, and Reset().
Member Function Documentation
busy()
bool TrajectoryGeneratorClient::busy () const
Returns true if the trajectory generator is busy.
Returns
true if the trajectory generator is busy
Definition at line 132 of file trajectory_generator_client.cpp.
{
    return busy_;
}
References busy_.
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::computeReference(), iii_drone::control::maneuver::FlyToPositionManeuverServer::computeReference(), iii_drone::control::maneuver::FlyToObjectManeuverServer::startExecution(), and iii_drone::control::maneuver::FlyToPositionManeuverServer::startExecution().
Cancel()
void TrajectoryGeneratorClient::Cancel ()
Cancels the trajectory generation if it is active.
Definition at line 52 of file trajectory_generator_client.cpp.
{
    client_->clear_on_new_response_callback();
    busy_ = false;
    done_ = false;
}
References busy_, client_, and done_.
Referenced by Reset().
ComputeReferenceTrajectoryAsync()
void TrajectoryGeneratorClient::ComputeReferenceTrajectoryAsync (const iii_drone::control::State & state, const iii_drone::control::Reference & reference, bool set_reference, bool reset, MPC_mode_t mpc_mode)
Starts generating a trajectory.
Parameters
state Current state
reference Reference
set_reference Updates the internal MPC reference if true
reset Resets the internal MPC if true
mpc_mode The MPC mode
Exceptions
std::runtime_error if the trajectory generator is busy
Definition at line 61 of file trajectory_generator_client.cpp.
  {
    // Set busy flag
    busy_ = true;
    // Set done flag
    done_ = false;
    // Create request
    auto request = std::make_shared<iii_drone_interfaces::srv::ComputeReferenceTrajectory::Request>();
    // Set request
    request->state = StateAdapter(state).ToMsg();
    request->reference = ReferenceAdapter(reference).ToMsg();
    request->set_reference = set_reference;
    request->reset = reset;
    request->mpc_mode.mode = mpc_mode;
    // Send request
    auto future = client_->async_send_request(
        request,
        std::bind(
            &TrajectoryGeneratorClient::serviceResultCallback,
            this,
            std::placeholders::_1
        )
    );
    future_ = future.future;
}
References busy_, client_, done_, future_, serviceResultCallback(), iii_drone::adapters::ReferenceAdapter::ToMsg(), and iii_drone::adapters::StateAdapter::ToMsg().
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::computeReference(), iii_drone::control::maneuver::FlyToPositionManeuverServer::computeReference(), and ComputeReferenceTrajectoryBlocking().
ComputeReferenceTrajectoryBlocking()
void TrajectoryGeneratorClient::ComputeReferenceTrajectoryBlocking (const iii_drone::control::State & state, const iii_drone::control::Reference & reference, bool set_reference, bool reset, MPC_mode_t mpc_mode, unsigned int poll_period_ms)
Generates a trajectory and blocks until it is done.
Parameters
state Current state
reference Reference
set_reference Updates the internal MPC reference if true
reset Resets the internal MPC if true
mpc_mode The MPC mode
poll_period_ms Poll period in milliseconds
Exceptions
std::runtime_error if the trajectory generator is busy
Definition at line 101 of file trajectory_generator_client.cpp.
  {
    ComputeReferenceTrajectoryAsync(
        state,
        reference,
        set_reference,
        reset,
        mpc_mode
    );
    while (!done()) {
        rclcpp::sleep_for(std::chrono::milliseconds(poll_period_ms));
    }
}
References ComputeReferenceTrajectoryAsync(), and done().
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::computeReference(), and iii_drone::control::maneuver::FlyToPositionManeuverServer::computeReference().
done()
bool TrajectoryGeneratorClient::done () const
Returns true if the trajectory generator is done.
Returns
true if the trajectory generator is done
Definition at line 138 of file trajectory_generator_client.cpp.
{
    return done_;
}
References done_.
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::computeReference(), iii_drone::control::maneuver::FlyToPositionManeuverServer::computeReference(), and ComputeReferenceTrajectoryBlocking().
GetReferenceTrajectory()
ReferenceTrajectory TrajectoryGeneratorClient::GetReferenceTrajectory () const
Returns the reference trajectory.
Returns
reference trajectory
Exceptions
std::runtime_error if no reference trajectory has been generated
Definition at line 126 of file trajectory_generator_client.cpp.
{
    return reference_trajectory_adapter_history_[0].reference_trajectory();
}
References reference_trajectory_adapter_history_.
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::computeReference(), iii_drone::control::maneuver::FlyToPositionManeuverServer::computeReference(), iii_drone::control::maneuver::FlyToObjectManeuverServer::publishFeedback(), and iii_drone::control::maneuver::FlyToPositionManeuverServer::publishFeedback().
Reset()
void TrajectoryGeneratorClient::Reset (const iii_drone::control::State & state = iii_drone::control::State())
Resets the client with the current state.
Parameters
state Current state
Definition at line 37 of file trajectory_generator_client.cpp.
{
    Cancel();
    Reference reference(
        state.position(),
        state.yaw()
    );
    reference_trajectory_adapter_history_ = History<ReferenceTrajectoryAdapter>(1);
    reference_trajectory_adapter_history_ = ReferenceTrajectoryAdapter(reference);
}
References Cancel(), iii_drone::control::State::position(), reference_trajectory_adapter_history_, and iii_drone::control::State::yaw().
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::computeReference(), iii_drone::control::maneuver::FlyToPositionManeuverServer::computeReference(), and TrajectoryGeneratorClient().
serviceResultCallback()
void TrajectoryGeneratorClient::serviceResultCallback (const rclcpp::Client< iii_drone_interfaces::srv::ComputeReferenceTrajectory >::SharedFuture future) private
Service result callback.
Parameters
future Future
Definition at line 144 of file trajectory_generator_client.cpp.
  {
    // Get response
    auto response = future.get();
    // Check if response is valid
    if (!response) {
        std::string error_message = "TrajectoryGeneratorClient::serviceResultCallback(): Service response is invalid.";
        RCLCPP_ERROR(node_->get_logger(), error_message.c_str());
        throw std::runtime_error(error_message);
    }
    // Create reference trajectory adapter
    ReferenceTrajectoryAdapter reference_trajectory_adapter(response->reference_trajectory);
    // Add reference trajectory adapter to history
    reference_trajectory_adapter_history_.Store(reference_trajectory_adapter);
    // Set busy flag
    busy_ = false;
    // Set done flag
    done_ = true;
}
References busy_, done_, node_, reference_trajectory_adapter_history_, and iii_drone::utils::History< T >::Store().
Referenced by ComputeReferenceTrajectoryAsync().
Member Data Documentation
busy_
iii_drone::utils::Atomic<bool> iii_drone::control::TrajectoryGeneratorClient::busy_ private
Busy flag.
Definition at line 161 of file trajectory_generator_client.hpp.
Referenced by busy(), Cancel(), ComputeReferenceTrajectoryAsync(), and serviceResultCallback().
client_
rclcpp::Client<iii_drone_interfaces::srv::ComputeReferenceTrajectory>::SharedPtr iii_drone::control::TrajectoryGeneratorClient::client_ private
Service client.
Definition at line 151 of file trajectory_generator_client.hpp.
Referenced by Cancel(), ComputeReferenceTrajectoryAsync(), and TrajectoryGeneratorClient().
done_
iii_drone::utils::Atomic<bool> iii_drone::control::TrajectoryGeneratorClient::done_ private
Done flag.
Definition at line 166 of file trajectory_generator_client.hpp.
Referenced by Cancel(), ComputeReferenceTrajectoryAsync(), done(), and serviceResultCallback().
future_
rclcpp::Client<iii_drone_interfaces::srv::ComputeReferenceTrajectory>::SharedFuture iii_drone::control::TrajectoryGeneratorClient::future_ private
Service future.
Definition at line 171 of file trajectory_generator_client.hpp.
Referenced by ComputeReferenceTrajectoryAsync().
node_
rclcpp::Node* iii_drone::control::TrajectoryGeneratorClient::node_ private
Node pointer.
Definition at line 146 of file trajectory_generator_client.hpp.
Referenced by serviceResultCallback(), and TrajectoryGeneratorClient().
reference_trajectory_adapter_history_
iii_drone::utils::History<iii_drone::adapters::ReferenceTrajectoryAdapter> iii_drone::control::TrajectoryGeneratorClient::reference_trajectory_adapter_history_ private
Reference trajectory adapter history.
Definition at line 156 of file trajectory_generator_client.hpp.
Referenced by GetReferenceTrajectory(), Reset(), and serviceResultCallback().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/trajectory_generator_client.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/trajectory_generator_client.cpp