III-Drone: iii_drone::control::maneuver::ManeuverScheduler Class Reference
iii_drone::control::maneuver::ManeuverScheduler Class Reference
Class that schedules execution of drone maneuvers. Maneuver server are registered using the dedicated functions. Each registered maneuver is associated with a type and a maneuver server. The server exposes an action that can be used to execute the maneuver. This class is responsible for scheduling the execution of the registered maneuvers, including checking whether a maneuver can be executed immediately or later. Maneuvers are queued for later execution. When a maneuver is finished, the next maneuver is started using the maneuver server API.
#include <maneuver_scheduler.hpp>
Public Types
typedef std::shared_ptr< ManeuverScheduler > SharedPtr
Shared pointer type.
typedef std::unique_ptr< ManeuverScheduler > UniquePtr
Unique pointer type.
Public Member Functions
ManeuverScheduler (rclcpp::Node *node, const iii_drone::control::CombinedDroneAwarenessHandler::SharedPtr combined_drone_awareness_handler, const iii_drone::control::maneuver::ManeuverSchedulerParameters::SharedPtr parameters, rclcpp::CallbackGroup::SharedPtr maneuver_execution_callback_group)
Constructor.
void RegisterManeuverServer (iii_drone::control::maneuver::maneuver_type_t maneuver_type, ManeuverServer::SharedPtr maneuver_server)
Registers a maneuver type with a maneuver server.
combined_drone_awareness_t ProjectExpectedAwarenessFull (const iii_drone::control::maneuver::Maneuver &maneuver) const
Returns the expected combined drone awareness upon completion or failure of given maneuver type, considering the full maneuver queue.
bool ProjectExpectedAwarenessSingle (const iii_drone::control::maneuver::Maneuver &maneuver, const combined_drone_awareness_t &awareness_before, combined_drone_awareness_t &awareness_after) const
Returns the expected combined drone awareness upon completion or failure of given maneuver type, given a current combined drone awareness.
bool CanExecute (const iii_drone::control::maneuver::Maneuver &maneuver) const
Returns whether a given maneuver can immediately execute.
bool CanSchedule (const iii_drone::control::maneuver::Maneuver &maneuver) const
Returns whether a given maneuver can execute later.
bool RegisterManeuver (iii_drone::control::maneuver::Maneuver maneuver, bool &will_execute_immediately)
Registers a maneuver with the maneuver scheduler. To be called from a maneuver server. If the maneuver execution timer is not running, it is started. After call to this function, the maneuver must be updated with the correct goal handle using the UpdateManeuver() method before it is selected for execution. This must happen before the timeout, otherwise the maneuver is aborted.
bool UpdateManeuver (iii_drone::control::maneuver::Maneuver maneuver)
Updates a maneuver entry which has been registered with the correct goal handle after the maneuver has been selected for execution.
bool CancelManeuver (iii_drone::control::maneuver::Maneuver maneuver)
Cancels a maneuver entry which has been registered before execution starts.
iii_drone::control::maneuver::Maneuver current_maneuver () const
Get copy of the currently executing maneuver. The currently executing maneuver is of type MANEUVER_TYPE_NONE if no maneuver is being executed.
bool maneuverIsExecutingOrPending () const
Get whether a maneuver is being executed or pending.
Private Types
using ReferenceCallbackToken = iii_drone::utils::Token<iii_drone::utils::Atomic<std::function<Reference(const State &)>>>
Private Member Functions
bool maneuverCanExecute (const iii_drone::control::maneuver::Maneuver &maneuver, const iii_drone::control::combined_drone_awareness_t &awareness) const
Evaluates whether a maneuver can be executed given an awareness.
void onManeuverCompleted (iii_drone::control::maneuver::Maneuver maneuver)
OnManeuverCompleted callback. Called every time a maneuver is completed.
void onReferenceCallbackTokenReacquired ()
Callback function for when the token is yielded from a maneuver server. Registers the hovering reference callback function if the maneuver failed.
void onHoveringFail ()
Callback for when hovering fails (hover by object or hover on cable).
void maneuverExecutionTimerCallback ()
The maneuver execution timer callback.
void progressScheduler ()
Progresses the scheduler. If a maneuver is executing, evaluates whether it has terminated. If a maneuver maneuver has terminated successfully, the next maneuver is started. If a maneuver has terminated unsuccessfully, all maneuvers are canceled by clearing the maneuver queue. When a maneuver stops executing, one of the hover maneuver server callbacks are registered through the onFinishedManeuver callback. Whenever no maneuver is executing, a counter counts down. When the counter reaches 0 without a maneuver scheduled for execution, the timer for running the maneuver execution loop is stopped.
void fetchNextReferenceAndPublish ()
Fetches the next reference and publishes it. Will fetch the reference using the registered callback, either associated with a maneuver server during active execution or one of the hover server callbacks. When the maneuver execution timer is stopped, no more references will be published until a new maneuver is scheduled and the timer is restarted.
void cancelAllPendingManeuvers ()
Cancels all pending maneuvers.
Private Attributes
rclcpp::Node * node_
Reference to the node for creating of ROS2 objects.
iii_drone::control::CombinedDroneAwarenessHandler::SharedPtr combined_drone_awareness_handler_
Shared pointer to the combined drone awareness handler for retrieving drone awareness.
iii_drone::control::maneuver::ManeuverSchedulerParameters::SharedPtr parameters_
The maneuver scheduler parameters.
rclcpp::CallbackGroup::SharedPtr maneuver_execution_callback_group_
The maneuver execution callback group.
iii_drone::control::maneuver::ManeuverQueue::UniquePtr maneuver_queue_
The maneuver queue.
iii_drone::utils::Atomic< iii_drone::control::maneuver::Maneuver > current_maneuver_
The current maneuver.
std::shared_mutex maneuver_mutex_
Maneuver mutex.
rclcpp::TimerBase::SharedPtr maneuver_execution_timer_
Main timer for maneuver execution.
iii_drone::utils::Atomic< std::function< Reference(const State &)> reference_callback_)
The reference callback function atomic.
ReferenceCallbackToken reference_callback_token_
The master token for the reference callback function access.
iii_drone::utils::Atomic< int > no_maneuver_idle_cnt_ = -1
The counter for the number of iterations without a maneuver before the scheduler goes from hovering to idle.
rclcpp::Publisher< iii_drone_interfaces::msg::Reference >::SharedPtr reference_publisher_
ROS2 reference publisher.
std::map< iii_drone::control::maneuver::maneuver_type_t, iii_drone::control::maneuver::ManeuverServer::SharedPtr > registered_maneuvers_
The registered maneuvers. Map of maneuver type to maneuver server base class.
Detailed Description
Class that schedules execution of drone maneuvers. Maneuver server are registered using the dedicated functions. Each registered maneuver is associated with a type and a maneuver server. The server exposes an action that can be used to execute the maneuver. This class is responsible for scheduling the execution of the registered maneuvers, including checking whether a maneuver can be executed immediately or later. Maneuvers are queued for later execution. When a maneuver is finished, the next maneuver is started using the maneuver server API.
Definition at line 73 of file maneuver_scheduler.hpp.
Member Typedef Documentation
ReferenceCallbackToken
using iii_drone::control::maneuver::ManeuverScheduler::ReferenceCallbackToken = iii_drone::utils::Token<iii_drone::utils::Atomic<std::function<Reference(const State &)>>> private
Definition at line 74 of file maneuver_scheduler.hpp.
SharedPtr
typedef std::shared_ptr<ManeuverScheduler> iii_drone::control::maneuver::ManeuverScheduler::SharedPtr
Shared pointer type.
Definition at line 199 of file maneuver_scheduler.hpp.
UniquePtr
typedef std::unique_ptr<ManeuverScheduler> iii_drone::control::maneuver::ManeuverScheduler::UniquePtr
Unique pointer type.
Definition at line 204 of file maneuver_scheduler.hpp.
Constructor & Destructor Documentation
ManeuverScheduler()
ManeuverScheduler::ManeuverScheduler (rclcpp::Node * node, const iii_drone::control::CombinedDroneAwarenessHandler::SharedPtr combined_drone_awareness_handler, const iii_drone::control::maneuver::ManeuverSchedulerParameters::SharedPtr parameters, rclcpp::CallbackGroup::SharedPtr maneuver_execution_callback_group)
Constructor.
Parameters
node Simple pointer to the containing node.
combined_drone_awareness_handler Shared pointer to the combined drone awareness handler for retrieving drone awareness.
parameters Shared pointer to the parameters for the maneuver scheduler.
maneuver_execution_callback_group Shared pointer to the callback group for parallel maneuver execution.
Definition at line 17 of file maneuver_scheduler.cpp.
  : node_(node),
    combined_drone_awareness_handler_(combined_drone_awareness_handler),
    parameters_(parameters),
    maneuver_execution_callback_group_(maneuver_execution_callback_group),
    reference_callback_token_(
        reference_callback_,
        std::bind(
            &ManeuverScheduler::onReferenceCallbackTokenReacquired,
            this
        )
    ) {
    maneuver_queue_ = std::make_unique<ManeuverQueue>(parameters_->maneuver_queue_size());
    current_maneuver_ = Maneuver();
    reference_publisher_ = node_->create_publisher<iii_drone_interfaces::msg::Reference>(
        "reference",
        10 // Fix QoS
    );
    maneuver_execution_timer_ = node_->create_wall_timer(
        std::chrono::milliseconds(parameters_->maneuver_execution_period_ms()),
        std::bind(
            &ManeuverScheduler::maneuverExecutionTimerCallback,
            this
        ),
        maneuver_execution_callback_group_
    );
    maneuver_execution_timer_->cancel();
}
References current_maneuver_, maneuver_execution_callback_group_, iii_drone::control::maneuver::ManeuverSchedulerParameters::maneuver_execution_period_ms(), maneuver_execution_timer_, maneuver_queue_, iii_drone::control::maneuver::ManeuverSchedulerParameters::maneuver_queue_size(), maneuverExecutionTimerCallback(), node_, parameters_, and reference_publisher_.
Member Function Documentation
cancelAllPendingManeuvers()
void ManeuverScheduler::cancelAllPendingManeuvers () private
Cancels all pending maneuvers.
Returns
void
Definition at line 727 of file maneuver_scheduler.cpp.
{
    std::unique_lock<std::shared_mutex> lck(maneuver_mutex_);
    maneuver_queue_->Clear();
    current_maneuver_ = Maneuver();
}
References iii_drone::control::maneuver::ManeuverQueue::Clear(), current_maneuver_, maneuver_mutex_, and maneuver_queue_.
Referenced by onHoveringFail(), and progressScheduler().
CancelManeuver()
bool ManeuverScheduler::CancelManeuver (iii_drone::control::maneuver::Maneuver maneuver)
Cancels a maneuver entry which has been registered before execution starts.
Parameters
maneuver The maneuver. Must have been terminated using the Terminate() method.
Returns
true if the maneuver was successfully canceled, false if the maneuver is not in the queue.
Definition at line 343 of file maneuver_scheduler.cpp.
{
    if (!maneuver.terminated()) {
        std::string msg = "ManeuverScheduler::CancelManeuver(): maneuver was not terminated before canceling with the scheduler.";
        RCLCPP_FATAL(rclcpp::get_logger("rclcpp"), msg.c_str());
        throw std::runtime_error(msg);
    }
    std::shared_lock<std::shared_mutex> lck(maneuver_mutex_);
    if (!maneuver_queue_->Update(maneuver)) {
        if (maneuver == *current_maneuver_) {
            current_maneuver_ = maneuver;
            return true;
        } else {
            return false;
        }
    } else {
        return true;
    }
}
References current_maneuver_, maneuver_mutex_, maneuver_queue_, iii_drone::control::maneuver::Maneuver::terminated(), and iii_drone::control::maneuver::ManeuverQueue::Update().
Referenced by RegisterManeuverServer().
CanExecute()
bool ManeuverScheduler::CanExecute (const iii_drone::control::maneuver::Maneuver & maneuver) const
Returns whether a given maneuver can immediately execute.
Parameters
maneuver The maneuver.
Returns
true if the maneuver can immediately execute.
Definition at line 233 of file maneuver_scheduler.cpp.
{
    if (maneuverIsExecutingOrPending()) {
        return false;
    }
    return maneuverCanExecute(
        maneuver,
        combined_drone_awareness_handler_->combined_drone_awareness()
    );
}
References iii_drone::control::CombinedDroneAwarenessHandler::combined_drone_awareness(), combined_drone_awareness_handler_, maneuverCanExecute(), and maneuverIsExecutingOrPending().
Referenced by RegisterManeuver().
CanSchedule()
bool ManeuverScheduler::CanSchedule (const iii_drone::control::maneuver::Maneuver & maneuver) const
Returns whether a given maneuver can execute later.
Parameters
maneuver The maneuver.
Returns
true if the maneuver can execute later.
Definition at line 248 of file maneuver_scheduler.cpp.
{
    try {
        ProjectExpectedAwarenessFull(maneuver);
    } catch (std::runtime_error & e) {
        return false;
    }
    return true;
}
References ProjectExpectedAwarenessFull().
Referenced by RegisterManeuver().
current_maneuver()
iii_drone::control::maneuver::Maneuver ManeuverScheduler::current_maneuver () const
Get copy of the currently executing maneuver. The currently executing maneuver is of type MANEUVER_TYPE_NONE if no maneuver is being executed.
Returns
The current maneuver.
Definition at line 378 of file maneuver_scheduler.cpp.
{
    return current_maneuver_;
}
References current_maneuver_.
Referenced by ProjectExpectedAwarenessFull().
fetchNextReferenceAndPublish()
void ManeuverScheduler::fetchNextReferenceAndPublish () private
Fetches the next reference and publishes it. Will fetch the reference using the registered callback, either associated with a maneuver server during active execution or one of the hover server callbacks. When the maneuver execution timer is stopped, no more references will be published until a new maneuver is scheduled and the timer is restarted.
Returns
void
Definition at line 717 of file maneuver_scheduler.cpp.
{
    Reference ref = (*reference_callback_)(combined_drone_awareness_handler_->GetState());
    ReferenceAdapter ref_adapter(ref);
    reference_publisher_->publish(ref_adapter.ToMsg());
}
References combined_drone_awareness_handler_, iii_drone::control::CombinedDroneAwarenessHandler::GetState(), and reference_publisher_.
Referenced by maneuverExecutionTimerCallback().
maneuverCanExecute()
bool ManeuverScheduler::maneuverCanExecute (const iii_drone::control::maneuver::Maneuver & maneuver, const iii_drone::control::combined_drone_awareness_t & awareness) const private
Evaluates whether a maneuver can be executed given an awareness.
Parameters
maneuver The maneuver.
awareness The combined drone awareness.
Returns
true if the maneuver can be executed.
Definition at line 396 of file maneuver_scheduler.cpp.
        {
    // Find registered maneuver coresponding to the maneuver type
    auto registered_maneuver = registered_maneuvers_.find(maneuver.maneuver_type());
    if (registered_maneuver == registered_maneuvers_.end()) {
        // Log error
        std::string msg = "ManeuverScheduler::maneuverCanExecute(): maneuver type " + std::to_string(maneuver.maneuver_type()) + " not registered.";
        RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), msg.c_str());
        return false;
    }
    // Check if the maneuver can execute
    return registered_maneuver->second->CanExecuteManeuver(
        maneuver,
        awareness
    );
    // switch(maneuver.type) {
    //     case maneuver::MANEUVER_TYPE_CABLE_LANDING:
    //         return behavior_state.in_flight() &&
    //             behavior_state.offboard &&
    //             behavior_state.has_target_cable &&
    //             behavior_state.target_cable_position_known;
    //     case maneuver::MANEUVER_TYPE_CABLE_TAKEOFF:
    //         return behavior_state.on_cable() &&
    //             behavior_state.offboard &&
    //             behavior_state.armed &&
    //             behavior_state.has_target_cable &&
    //             behavior_state.target_cable_position_known;
    //     default:
    //         return true;
    // }
}
References iii_drone::control::maneuver::Maneuver::maneuver_type(), and registered_maneuvers_.
Referenced by CanExecute(), and ProjectExpectedAwarenessSingle().
maneuverExecutionTimerCallback()
void ManeuverScheduler::maneuverExecutionTimerCallback () private
The maneuver execution timer callback.
Definition at line 522 of file maneuver_scheduler.cpp.
{
    progressScheduler();
    fetchNextReferenceAndPublish();
}
References fetchNextReferenceAndPublish(), and progressScheduler().
Referenced by ManeuverScheduler().
maneuverIsExecutingOrPending()
bool ManeuverScheduler::maneuverIsExecutingOrPending () const
Get whether a maneuver is being executed or pending.
Returns
true if a maneuver is being executed or pending.
Definition at line 384 of file maneuver_scheduler.cpp.
{
    if (!maneuver_queue_->empty()) {
        return true;
    }
    return ((Maneuver)current_maneuver_).maneuver_type() != iii_drone::control::maneuver::MANEUVER_TYPE_NONE;
}
References current_maneuver_, iii_drone::control::maneuver::ManeuverQueue::empty(), maneuver_queue_, and iii_drone::control::maneuver::MANEUVER_TYPE_NONE.
Referenced by CanExecute(), and progressScheduler().
onHoveringFail()
void ManeuverScheduler::onHoveringFail () private
Callback for when hovering fails (hover by object or hover on cable).
Returns
void
Definition at line 516 of file maneuver_scheduler.cpp.
{
    cancelAllPendingManeuvers();
}
References cancelAllPendingManeuvers().
Referenced by RegisterManeuverServer().
onManeuverCompleted()
void ManeuverScheduler::onManeuverCompleted (iii_drone::control::maneuver::Maneuver maneuver) private
OnManeuverCompleted callback. Called every time a maneuver is completed.
Parameters
maneuver The maneuver. This maneuver must have been terminated using the Termiante() method.
Definition at line 442 of file maneuver_scheduler.cpp.
{
    std::shared_lock<std::shared_mutex> lck(maneuver_mutex_);
    if (!maneuver.terminated()) {
        std::string msg = "ManeuverScheduler::onManeuverCompleted(): maneuver was not terminated before completing.";
        RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), msg.c_str());
    }
    current_maneuver_ = maneuver;
}
References current_maneuver_, maneuver_mutex_, and iii_drone::control::maneuver::Maneuver::terminated().
Referenced by RegisterManeuverServer().
onReferenceCallbackTokenReacquired()
void ManeuverScheduler::onReferenceCallbackTokenReacquired () private
Callback function for when the token is yielded from a maneuver server. Registers the hovering reference callback function if the maneuver failed.
Returns
void
Definition at line 457 of file maneuver_scheduler.cpp.
{
    if (!reference_callback_token_.master_has_token()) {
        std::string msg = "ManeuverScheduler::onReferenceCallbackTokenReacquired(): master does not have token.";
        RCLCPP_FATAL(rclcpp::get_logger("rclcpp"), msg.c_str());
        throw std::runtime_error(msg);
    }
    if (!current_maneuver_->terminated()) {
        std::string msg = "ManeuverScheduler::onReferenceCallbackTokenReacquired(): maneuver is not terminated.";
        RCLCPP_FATAL(rclcpp::get_logger("rclcpp"), msg.c_str());
        throw std::runtime_error(msg);
    }
    if (!current_maneuver_->success()) {
        auto registered_maneuver = registered_maneuvers_.find(MANEUVER_TYPE_HOVER);
        std::shared_ptr<HoverManeuverServer> maneuver_server = std::static_pointer_cast<HoverManeuverServer>(registered_maneuver->second);
        reference_callback_token_.resource() = std::bind(
            &HoverManeuverServer::GetReference,
            &(*maneuver_server),
            std::placeholders::_1
        );
    }
    // switch(maneuver_type) {
    //     case MANEUVER_TYPE_CABLE_LANDING: {
    //         auto registered_maneuver = registered_maneuvers_.find(MANEUVER_TYPE_HOVER_ON_CABLE);
    //         std::shared_ptr<HoverOnCableManeuverServer> maneuver_server = std::static_pointer_cast<HoverOnCableManeuverServer>(registered_maneuver->second);
    //         maneuver_server->Update(
    //             parameters_->hover_on_cable_default_z_velocity(),
    //             parameters_->hover_on_cable_default_yaw_rate()
    //         );
    //         reference_callback_token_.resource() = std::bind(
    //             &HoverOnCableManeuverServer::GetReference,
    //             &(*maneuver_server),
    //             std::placeholders::_1
    //         );
    //         break;
    //     }
    // }
}
References current_maneuver_, iii_drone::control::maneuver::HoverManeuverServer::GetReference(), iii_drone::control::maneuver::MANEUVER_TYPE_HOVER, iii_drone::utils::Token< T >::master_has_token(), reference_callback_token_, registered_maneuvers_, iii_drone::utils::Token< T >::resource(), iii_drone::control::maneuver::Maneuver::success(), and iii_drone::control::maneuver::Maneuver::terminated().
progressScheduler()
void ManeuverScheduler::progressScheduler () private
Progresses the scheduler. If a maneuver is executing, evaluates whether it has terminated. If a maneuver maneuver has terminated successfully, the next maneuver is started. If a maneuver has terminated unsuccessfully, all maneuvers are canceled by clearing the maneuver queue. When a maneuver stops executing, one of the hover maneuver server callbacks are registered through the onFinishedManeuver callback. Whenever no maneuver is executing, a counter counts down. When the counter reaches 0 without a maneuver scheduled for execution, the timer for running the maneuver execution loop is stopped.
Returns
void
Definition at line 530 of file maneuver_scheduler.cpp.
{
    static bool waiting_for_maneuver_to_start = false;
    static std::string waiting_for_maneuver_to_start_action_name;
    std::unique_lock<std::shared_mutex> lck(maneuver_mutex_);
    auto on_no_maneuver = [this](Maneuver previous_maneuver) {
        if (!previous_maneuver.success()) {
            no_maneuver_idle_cnt_ = parameters_->no_maneuver_idle_cnt_s() * 1000 / parameters_->maneuver_execution_period_ms();
        } else {
            switch (previous_maneuver.maneuver_type()) {
                case MANEUVER_TYPE_HOVER: {
                    hover_maneuver_params_t maneuver_params(previous_maneuver.maneuver_params());
                    no_maneuver_idle_cnt_ = maneuver_params.duration_s * 1000 / parameters_->maneuver_execution_period_ms();
                    break;
                }
                case MANEUVER_TYPE_HOVER_BY_OBJECT: {
                    hover_by_object_maneuver_params_t maneuver_params(previous_maneuver.maneuver_params());
                    no_maneuver_idle_cnt_ = maneuver_params.duration_s * 1000 / parameters_->maneuver_execution_period_ms();
                    break;
                }
                case MANEUVER_TYPE_HOVER_ON_CABLE: {
                    hover_on_cable_maneuver_params_t maneuver_params(previous_maneuver.maneuver_params());
                    no_maneuver_idle_cnt_ = maneuver_params.duration_s * 1000 / parameters_->maneuver_execution_period_ms();
                    break;
                }
                case MANEUVER_TYPE_NONE:
                    if (*no_maneuver_idle_cnt_ >= 0)
                        (*no_maneuver_idle_cnt_)--;
                    break;
                default:
                    no_maneuver_idle_cnt_ = parameters_->no_maneuver_idle_cnt_s() * 1000 / parameters_->maneuver_execution_period_ms();
                    break;
            }
        }
        if (*no_maneuver_idle_cnt_ < 0) {
            maneuver_execution_timer_->cancel();
        }
    };
    auto on_failure = [this, &on_no_maneuver](Maneuver previous_maneuver) {
        previous_maneuver.Terminate(false);
        cancelAllPendingManeuvers();
        reference_callback_token_.DenyAll();
        on_no_maneuver(previous_maneuver);
    };
    // Check if a maneuver is executing
    if (maneuverIsExecutingOrPending()) {
        // Check if the current maneuver is completed
        if(current_maneuver_->terminated()) {
            if (!reference_callback_token_.master_has_token()) {
                std::string msg = "ManeuverScheduler::progressScheduler(): master does not have token.";
                RCLCPP_FATAL(rclcpp::get_logger("rclcpp"), msg.c_str());
                throw std::runtime_error(msg);
            }
            // Check if the maneuver was successful
            if (current_maneuver_->success()) {
                // Check if there are more maneuvers in the queue
                Maneuver maneuver;
                if (maneuver_queue_->Pop(maneuver)) {
                    // Progress to the next maneuver
                    current_maneuver_ = maneuver;
                    // Start the maneuver execution:
                    current_maneuver_->Start();
                    // Find the maneuver server:
                    auto registered_maneuver = registered_maneuvers_.find(maneuver.maneuver_type());
                    // Get the action name:
                    waiting_for_maneuver_to_start_action_name = registered_maneuver->second->action_name();
                    // Set waiting for start:
                    waiting_for_maneuver_to_start = true;
                    // Reset no_maneuver_idle_cnt:
                    *no_maneuver_idle_cnt_ = -1;
                } else {
                    on_no_maneuver(current_maneuver_);
                    current_maneuver_ = Maneuver();
                }
            } else {
                on_failure(current_maneuver_);
            }
        } else {
            // Current maneuver has not terminated.
            if (waiting_for_maneuver_to_start) {
                // Check that the maneuver has a goal handle:
                if (current_maneuver_->goal_handle() == nullptr) {
                    // Check that the update timeout has elapsed:
                    rclcpp::Time maneuver_creation_time = current_maneuver_->creation_time();
                    rclcpp::Time current_time = node_->now();
                    if ((current_time - maneuver_creation_time).seconds() > parameters_->maneuver_register_update_timeout_s()) {
                        on_failure(current_maneuver_);
                    }
                    return;
                }
                if (reference_callback_token_.has_requested_token(waiting_for_maneuver_to_start_action_name)) {
                    // Give the token:
                    reference_callback_token_.Give(waiting_for_maneuver_to_start_action_name);
                    // Reset the flag:
                    waiting_for_maneuver_to_start = false;
                } else {
                    rclcpp::Time maneuver_start_time = current_maneuver_->start_time();
                    rclcpp::Time current_time = node_->now();
                    if ((current_time - maneuver_start_time).seconds() > parameters_->maneuver_start_timeout_s()) {
                        on_failure(current_maneuver_);
                    }
                }
            }
        }
    } else {
        if (current_maneuver_->maneuver_type() != MANEUVER_TYPE_NONE) {
            std::string msg = "ManeuverScheduler::progressScheduler(): maneuver is not executing or pending, but current maneuver is not MANEUVER_TYPE_NONE.";
            RCLCPP_FATAL(rclcpp::get_logger("rclcpp"), msg.c_str());
            throw std::runtime_error(msg);
        }
        on_no_maneuver(current_maneuver_);
    }
}
References cancelAllPendingManeuvers(), iii_drone::control::maneuver::Maneuver::creation_time(), current_maneuver_, iii_drone::utils::Token< T >::DenyAll(), iii_drone::control::maneuver::hover_maneuver_params_t::duration_s, iii_drone::control::maneuver::hover_by_object_maneuver_params_t::duration_s, iii_drone::control::maneuver::hover_on_cable_maneuver_params_t::duration_s, iii_drone::utils::Token< T >::Give(), iii_drone::control::maneuver::Maneuver::goal_handle(), iii_drone::utils::Token< T >::has_requested_token(), iii_drone::control::maneuver::ManeuverSchedulerParameters::maneuver_execution_period_ms(), maneuver_execution_timer_, maneuver_mutex_, maneuver_queue_, iii_drone::control::maneuver::ManeuverSchedulerParameters::maneuver_register_update_timeout_s(), iii_drone::control::maneuver::ManeuverSchedulerParameters::maneuver_start_timeout_s(), iii_drone::control::maneuver::Maneuver::maneuver_type(), iii_drone::control::maneuver::MANEUVER_TYPE_HOVER, iii_drone::control::maneuver::MANEUVER_TYPE_HOVER_BY_OBJECT, iii_drone::control::maneuver::MANEUVER_TYPE_HOVER_ON_CABLE, iii_drone::control::maneuver::MANEUVER_TYPE_NONE, maneuverIsExecutingOrPending(), iii_drone::utils::Token< T >::master_has_token(), no_maneuver_idle_cnt_, iii_drone::control::maneuver::ManeuverSchedulerParameters::no_maneuver_idle_cnt_s(), node_, parameters_, iii_drone::control::maneuver::ManeuverQueue::Pop(), reference_callback_token_, registered_maneuvers_, iii_drone::control::maneuver::Maneuver::Start(), iii_drone::control::maneuver::Maneuver::start_time(), iii_drone::control::maneuver::Maneuver::success(), and iii_drone::control::maneuver::Maneuver::terminated().
Referenced by maneuverExecutionTimerCallback().
ProjectExpectedAwarenessFull()
combined_drone_awareness_t ManeuverScheduler::ProjectExpectedAwarenessFull (const iii_drone::control::maneuver::Maneuver & maneuver) const
Returns the expected combined drone awareness upon completion or failure of given maneuver type, considering the full maneuver queue.
Parameters
maneuver The maneuver.
Returns
The expected combined drone awareness upon completion of given maneuver.
Exceptions
std::runtime_error if a maneuver in the queue cannot be executed and parameter fail_on_corrupted_queue is true.
Definition at line 143 of file maneuver_scheduler.cpp.
{
    std::vector<Maneuver> maneuver_queue = maneuver_queue_->vector();
    Maneuver current_maneuver = current_maneuver_.Load();
    if (maneuver_queue.size() == 0 || maneuver_queue[0] != current_maneuver) {
        maneuver_queue.insert(
            maneuver_queue.begin(),
            current_maneuver
        );
    }
    maneuver_queue.push_back(maneuver);
    combined_drone_awareness_t awareness = combined_drone_awareness_handler_->combined_drone_awareness();
    for (unsigned int i = 0; i < maneuver_queue.size(); i++) {
        combined_drone_awareness_t next_awareness;
        if (
            !ProjectExpectedAwarenessSingle(
                maneuver_queue[i],
                awareness,
                next_awareness
            )
        ) {
            throw std::runtime_error("ManeuverScheduler::ProjectExpectedAwarenessFull(): maneuver queue is invalid");
        }
        awareness = next_awareness;
    }
    return awareness;
}
References iii_drone::control::CombinedDroneAwarenessHandler::combined_drone_awareness(), combined_drone_awareness_handler_, current_maneuver(), current_maneuver_, iii_drone::utils::Atomic< T >::Load(), maneuver_queue_, ProjectExpectedAwarenessSingle(), and iii_drone::control::maneuver::ManeuverQueue::vector().
Referenced by CanSchedule().
ProjectExpectedAwarenessSingle()
bool ManeuverScheduler::ProjectExpectedAwarenessSingle (const iii_drone::control::maneuver::Maneuver & maneuver, const combined_drone_awareness_t & awareness_before, combined_drone_awareness_t & awareness_after) const
Returns the expected combined drone awareness upon completion or failure of given maneuver type, given a current combined drone awareness.
Parameters
maneuver The maneuver to be executed at the end of the current queue.
awareness_before The inital combined drone awareness.
awareness_after The combined drone awareness after the maneuver.
Returns
Whether the maneuver could execute succesfully.
Definition at line 186 of file maneuver_scheduler.cpp.
        {
    if (maneuver.maneuver_type() == MANEUVER_TYPE_NONE) {
        awareness_after = awareness_before;
        return true;
    }
    if (!maneuverCanExecute(maneuver, awareness_before)) {
        return false;
    }
    // Find maneuver server:
    auto registered_maneuver = registered_maneuvers_.find(maneuver.maneuver_type());
    awareness_after = registered_maneuver->second->ExpectedAwarenessAfterExecution(maneuver);
    // switch(maneuver.maneuver_type()) {
        // case maneuver::MANEUVER_TYPE_CABLE_LANDING:
        //     awareness_after.armed = true;
        //     awareness_after.offboard = true;
        //     awareness_after.has_target_cable = true;
        //     awareness_after.drone_location = DRONE_LOCATION_ON_CABLE;
        //     break;
        // case maneuver::MANEUVER_TYPE_CABLE_TAKEOFF:
        //     awareness_after.armed = true;
        //     awareness_after.offboard = true;
        //     awareness_after.has_target_cable = true;
        //     awareness_after.drone_location = DRONE_LOCATION_IN_FLIGHT;
        //     break;
    // }
    return true;
}
References iii_drone::control::maneuver::Maneuver::maneuver_type(), iii_drone::control::maneuver::MANEUVER_TYPE_NONE, maneuverCanExecute(), and registered_maneuvers_.
Referenced by ProjectExpectedAwarenessFull().
RegisterManeuver()
bool ManeuverScheduler::RegisterManeuver (iii_drone::control::maneuver::Maneuver maneuver, bool & will_execute_immediately)
Registers a maneuver with the maneuver scheduler. To be called from a maneuver server. If the maneuver execution timer is not running, it is started. After call to this function, the maneuver must be updated with the correct goal handle using the UpdateManeuver() method before it is selected for execution. This must happen before the timeout, otherwise the maneuver is aborted.
Parameters
maneuver The maneuver.
will_execute_immediately Whether the maneuver will execute immediately, output.
Returns
true if the maneuver was successfully registered, false if the maneuver is rejected by the scheduler.
Definition at line 264 of file maneuver_scheduler.cpp.
  {
    std::shared_lock<std::shared_mutex> lck(maneuver_mutex_);
    if (!CanSchedule(maneuver)) {
        return false;
    }
    if (!maneuver_queue_->Push(maneuver)) {
        return false;
    }
    will_execute_immediately = CanExecute(maneuver);
    if (maneuver_execution_timer_->is_canceled()) {
        maneuver_execution_timer_->reset();
    }
    return true;
}
References CanExecute(), CanSchedule(), maneuver_execution_timer_, maneuver_mutex_, maneuver_queue_, and iii_drone::control::maneuver::ManeuverQueue::Push().
Referenced by RegisterManeuverServer().
RegisterManeuverServer()
void ManeuverScheduler::RegisterManeuverServer (iii_drone::control::maneuver::maneuver_type_t maneuver_type, ManeuverServer::SharedPtr maneuver_server)
Registers a maneuver type with a maneuver server.
Parameters
maneuver_type The maneuver type.
server The maneuver server shared pointer.
Definition at line 56 of file maneuver_scheduler.cpp.
  {
    // Check if the maneuver type is already registered
    if (registered_maneuvers_.find(maneuver_type) != registered_maneuvers_.end()) {
        std::string msg = "ManeuverScheduler::RegisterManeuverServer(): maneuver type " + std::to_string(maneuver_type) + " already registered, but was attempted registered again.";
        RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), msg.c_str());
        return;
    }
    registered_maneuvers_.insert(
        std::pair<maneuver_type_t, ManeuverServer::SharedPtr>(
            maneuver_type,
            maneuver_server
        )
    );
    maneuver_server->Start(
        std::bind(
            &ManeuverScheduler::RegisterManeuver,
            this,
            std::placeholders::_1,
            std::placeholders::_2
        ),
        std::bind(
            &ManeuverScheduler::UpdateManeuver,
            this,
            std::placeholders::_1
        ),
        std::bind(
            &ManeuverScheduler::CancelManeuver,
            this,
            std::placeholders::_1
        ),
        [this](Maneuver maneuver) -> bool {
            std::shared_lock<std::shared_mutex> lck(maneuver_mutex_);
            Maneuver mn = maneuver_queue_->Find(maneuver.uuid());
            return mn == maneuver || maneuver == *current_maneuver_;
        },
        [this](Maneuver maneuver) -> bool {
            std::shared_lock<std::shared_mutex> lck(maneuver_mutex_);
            return maneuver == *current_maneuver_;
        },
        std::bind(
            &ManeuverScheduler::onManeuverCompleted,
            this,
            std::placeholders::_1
        ),
        std::make_shared<ReferenceCallbackToken>(
            reference_callback_token_.CreateSlaveHandle(
                maneuver_server->action_name()
            )
        ),
        registered_maneuvers_
    );
    if (maneuver_type == MANEUVER_TYPE_HOVER_BY_OBJECT) {
        std::static_pointer_cast<HoverByObjectManeuverServer>(maneuver_server)->RegisterOnFailCallback(
            std::bind(
                &ManeuverScheduler::onHoveringFail,
                this
            )
        );
    } else if (maneuver_type == MANEUVER_TYPE_HOVER_ON_CABLE) {
        std::static_pointer_cast<HoverOnCableManeuverServer>(maneuver_server)->RegisterOnFailCallback(
            std::bind(
                &ManeuverScheduler::onHoveringFail,
                this
            )
        );
    }
}
References CancelManeuver(), iii_drone::utils::Token< T >::CreateSlaveHandle(), current_maneuver_, iii_drone::control::maneuver::ManeuverQueue::Find(), maneuver_mutex_, maneuver_queue_, iii_drone::control::maneuver::MANEUVER_TYPE_HOVER_BY_OBJECT, iii_drone::control::maneuver::MANEUVER_TYPE_HOVER_ON_CABLE, onHoveringFail(), onManeuverCompleted(), reference_callback_token_, registered_maneuvers_, RegisterManeuver(), UpdateManeuver(), and iii_drone::control::maneuver::Maneuver::uuid().
Referenced by iii_drone::control::maneuver_controller_node::ManeuverControllerNode::registerManeuverServers().
UpdateManeuver()
bool ManeuverScheduler::UpdateManeuver (iii_drone::control::maneuver::Maneuver maneuver)
Updates a maneuver entry which has been registered with the correct goal handle after the maneuver has been selected for execution.
Parameters
maneuver The maneuver.
Returns
true if the maneuver was successfully updated, false if the maneuver is not in the queue or has timed out.
Definition at line 295 of file maneuver_scheduler.cpp.
{
    std::shared_lock<std::shared_mutex> lck(maneuver_mutex_);
    Maneuver old_maneuver = maneuver_queue_->Find(maneuver.uuid());
    if (old_maneuver == Maneuver()) {
        return false;
    }
    rclcpp::Time maneuver_creation_time = old_maneuver.creation_time();
    rclcpp::Time current_time = node_->now();
    if ((current_time - maneuver_creation_time).seconds() > parameters_->maneuver_register_update_timeout_s()) {
        maneuver.Terminate(false);
        maneuver_queue_->Update(maneuver);
        return false;
    }
    if(!maneuver_queue_->Update(maneuver)) {
        if (maneuver == *current_maneuver_) {
            current_maneuver_ = maneuver;
            return true;
        } else {
            return false;
        }
    } else {
        return true;
    }
}
References iii_drone::control::maneuver::Maneuver::creation_time(), current_maneuver_, iii_drone::control::maneuver::ManeuverQueue::Find(), maneuver_mutex_, maneuver_queue_, iii_drone::control::maneuver::ManeuverSchedulerParameters::maneuver_register_update_timeout_s(), node_, parameters_, iii_drone::control::maneuver::Maneuver::Terminate(), iii_drone::control::maneuver::ManeuverQueue::Update(), and iii_drone::control::maneuver::Maneuver::uuid().
Referenced by RegisterManeuverServer().
Member Data Documentation
combined_drone_awareness_handler_
iii_drone::control::CombinedDroneAwarenessHandler::SharedPtr iii_drone::control::maneuver::ManeuverScheduler::combined_drone_awareness_handler_ private
Shared pointer to the combined drone awareness handler for retrieving drone awareness.
Definition at line 243 of file maneuver_scheduler.hpp.
Referenced by CanExecute(), fetchNextReferenceAndPublish(), and ProjectExpectedAwarenessFull().
current_maneuver_
iii_drone::utils::Atomic<iii_drone::control::maneuver::Maneuver> iii_drone::control::maneuver::ManeuverScheduler::current_maneuver_ private
The current maneuver.
Definition at line 263 of file maneuver_scheduler.hpp.
Referenced by cancelAllPendingManeuvers(), CancelManeuver(), current_maneuver(), maneuverIsExecutingOrPending(), ManeuverScheduler(), onManeuverCompleted(), onReferenceCallbackTokenReacquired(), progressScheduler(), ProjectExpectedAwarenessFull(), RegisterManeuverServer(), and UpdateManeuver().
maneuver_execution_callback_group_
rclcpp::CallbackGroup::SharedPtr iii_drone::control::maneuver::ManeuverScheduler::maneuver_execution_callback_group_ private
The maneuver execution callback group.
Definition at line 253 of file maneuver_scheduler.hpp.
Referenced by ManeuverScheduler().
maneuver_execution_timer_
rclcpp::TimerBase::SharedPtr iii_drone::control::maneuver::ManeuverScheduler::maneuver_execution_timer_ private
Main timer for maneuver execution.
Definition at line 273 of file maneuver_scheduler.hpp.
Referenced by ManeuverScheduler(), progressScheduler(), and RegisterManeuver().
maneuver_mutex_
std::shared_mutex iii_drone::control::maneuver::ManeuverScheduler::maneuver_mutex_ mutable private
Maneuver mutex.
Definition at line 268 of file maneuver_scheduler.hpp.
Referenced by cancelAllPendingManeuvers(), CancelManeuver(), onManeuverCompleted(), progressScheduler(), RegisterManeuver(), RegisterManeuverServer(), and UpdateManeuver().
maneuver_queue_
iii_drone::control::maneuver::ManeuverQueue::UniquePtr iii_drone::control::maneuver::ManeuverScheduler::maneuver_queue_ private
The maneuver queue.
Definition at line 258 of file maneuver_scheduler.hpp.
Referenced by cancelAllPendingManeuvers(), CancelManeuver(), maneuverIsExecutingOrPending(), ManeuverScheduler(), progressScheduler(), ProjectExpectedAwarenessFull(), RegisterManeuver(), RegisterManeuverServer(), and UpdateManeuver().
no_maneuver_idle_cnt_
iii_drone::utils::Atomic<int> iii_drone::control::maneuver::ManeuverScheduler::no_maneuver_idle_cnt_ = -1 private
The counter for the number of iterations without a maneuver before the scheduler goes from hovering to idle.
Definition at line 288 of file maneuver_scheduler.hpp.
Referenced by progressScheduler().
node_
rclcpp::Node* iii_drone::control::maneuver::ManeuverScheduler::node_ private
Reference to the node for creating of ROS2 objects.
Definition at line 238 of file maneuver_scheduler.hpp.
Referenced by ManeuverScheduler(), progressScheduler(), and UpdateManeuver().
parameters_
iii_drone::control::maneuver::ManeuverSchedulerParameters::SharedPtr iii_drone::control::maneuver::ManeuverScheduler::parameters_ private
The maneuver scheduler parameters.
Definition at line 248 of file maneuver_scheduler.hpp.
Referenced by ManeuverScheduler(), progressScheduler(), and UpdateManeuver().
reference_callback_
iii_drone::utils::Atomic<std::function<Reference(const State &)> iii_drone::control::maneuver::ManeuverScheduler::reference_callback_) private
The reference callback function atomic.
Definition at line 278 of file maneuver_scheduler.hpp.
reference_callback_token_
ReferenceCallbackToken iii_drone::control::maneuver::ManeuverScheduler::reference_callback_token_ private
The master token for the reference callback function access.
Definition at line 283 of file maneuver_scheduler.hpp.
Referenced by onReferenceCallbackTokenReacquired(), progressScheduler(), and RegisterManeuverServer().
reference_publisher_
rclcpp::Publisher<iii_drone_interfaces::msg::Reference>::SharedPtr iii_drone::control::maneuver::ManeuverScheduler::reference_publisher_ private
ROS2 reference publisher.
Definition at line 300 of file maneuver_scheduler.hpp.
Referenced by fetchNextReferenceAndPublish(), and ManeuverScheduler().
registered_maneuvers_
std::map<iii_drone::control::maneuver::maneuver_type_t, iii_drone::control::maneuver::ManeuverServer::SharedPtr> iii_drone::control::maneuver::ManeuverScheduler::registered_maneuvers_ private
The registered maneuvers. Map of maneuver type to maneuver server base class.
Definition at line 341 of file maneuver_scheduler.hpp.
Referenced by maneuverCanExecute(), onReferenceCallbackTokenReacquired(), progressScheduler(), ProjectExpectedAwarenessSingle(), and RegisterManeuverServer().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/maneuver/maneuver_scheduler.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/maneuver/maneuver_scheduler.cpp