III-Drone: iii_drone::control::BehaviorState Class Reference
iii_drone::control::BehaviorState Class Reference
Class that represents the behavior state of the drone.
#include <behavior_state.hpp>
Public Types
typedef std::shared_ptr< BehaviorState > SharedPtr
Shared pointer type.
Public Member Functions
BehaviorState (iii_drone::control::BehaviorStateParameters::SharedPtr parameters, iii_drone::utils::History< iii_drone::adapters::px4::VehicleStatusAdapter >::SharedPtr vehicle_status_adapter_history, iii_drone::utils::History< iii_drone::adapters::px4::VehicleOdometryAdapter >::SharedPtr vehicle_odometry_adapter_history, iii_drone::utils::History< iii_drone::adapters::PowerlineAdapter >::SharedPtr powerline_adapter_history, iii_drone::utils::History< iii_drone::adapters::GripperStatusAdapter >::SharedPtr gripper_status_adapter_history, iii_drone::utils::Atomic< double >::SharedPtr ground_altitude_estimate, iii_drone::utils::Atomic< int >::SharedPtr target_cable_id, iii_drone::control::maneuver::ManeuverQueue::SharedPtr maneuver_queue, iii_drone::utils::Atomic< iii_drone::control::maneuver::maneuver_t >::SharedPtr current_manuever, tf2_ros::Buffer::SharedPtr tf_buffer)
Constructor.
behavior_state_t ProjectExpectedBehaviorState (iii_drone::control::maneuver::maneuver_t maneuver) const
Returns the expected behavior state upon completion or failure of given maneuver type, considering the full maneuver queue.
behavior_state_t ProjectExpectedBehaviorState (iii_drone::control::maneuver::maneuver_t maneuver, iii_drone::control::behavior_state_t behavior_state) const
Returns the expected behavior state upon completion or failure of given maneuver type, given a current behavior state.
bool CanExecute (iii_drone::control::maneuver::maneuver_t maneuver) const
Returns the expected behavior state upon completion or failure of given maneuver type,.
bool CanSchedule (iii_drone::control::maneuver::maneuver_t maneuver) const
Returns whether a given maneuver can execute later.
bool armed () const
Whether the drone is armed.
bool offboard () const
Whether the drone is in offboard mode.
bool has_target_cable () const
Whether the drone has a target cable.
bool target_cable_position_known () const
Whether the position of the target cable is known.
bool on_ground () const
Whether the drone is on the ground.
bool on_cable () const
Whether the drone is on a cable.
bool in_flight () const
Whether the drone is in flight.
int on_cable_id () const
Return the id of the cable that the drone is on if it is on a cable, -1 otherwise.
drone_location_t drone_location (int &on_cable_id) const
Returns the drone location, checks the drone location and sets the on_cable_id if the drone is on a cable.
drone_location_t drone_location () const
Returns the drone location.
iii_drone::control::maneuver::maneuver_t current_maneuver () const
Get the current maneuver.
bool maneuver_executing () const
Get whether a maneuver is being executed.
behavior_state_t behavior_state () const
Get the behavior state of the drone.
Private Member Functions
bool maneuverCanExecute (iii_drone::control::maneuver::maneuver_t maneuver, iii_drone::control::behavior_state_t behavior_state) const
Evaluates whether a maneuver can be executed given a behavior state.
Private Attributes
iii_drone::control::BehaviorStateParameters::SharedPtr parameters_
The parameters for the behavior state object.
iii_drone::utils::History< iii_drone::adapters::px4::VehicleStatusAdapter >::SharedPtr vehicle_status_adapter_history_
The vehicle status adapter history.
iii_drone::utils::History< iii_drone::adapters::px4::VehicleOdometryAdapter >::SharedPtr vehicle_odometry_adapter_history_
The vehicle odometry adapter history.
iii_drone::utils::History< iii_drone::adapters::PowerlineAdapter >::SharedPtr powerline_adapter_history_
The powerline adapter history.
iii_drone::utils::History< iii_drone::adapters::GripperStatusAdapter >::SharedPtr gripper_status_adapter_history_
The gripper status adapter history.
iii_drone::utils::Atomic< double >::SharedPtr ground_altitude_estimate_
The ground altitude estimate.
iii_drone::utils::Atomic< int >::SharedPtr target_cable_id_
The target cable id.
iii_drone::control::maneuver::ManeuverQueue::SharedPtr maneuver_queue_
The maneuver queue.
iii_drone::utils::Atomic< iii_drone::control::maneuver::maneuver_t >::SharedPtr current_maneuver_
The current maneuver.
tf2_ros::Buffer::SharedPtr tf_buffer_
The tf buffer.
Detailed Description
Class that represents the behavior state of the drone.
Definition at line 97 of file behavior_state.hpp.
Member Typedef Documentation
SharedPtr
typedef std::shared_ptr<BehaviorState> iii_drone::control::BehaviorState::SharedPtr
Shared pointer type.
Definition at line 273 of file behavior_state.hpp.
Constructor & Destructor Documentation
BehaviorState()
BehaviorState::BehaviorState (iii_drone::control::BehaviorStateParameters::SharedPtr parameters, iii_drone::utils::History< iii_drone::adapters::px4::VehicleStatusAdapter >::SharedPtr vehicle_status_adapter_history, iii_drone::utils::History< iii_drone::adapters::px4::VehicleOdometryAdapter >::SharedPtr vehicle_odometry_adapter_history, iii_drone::utils::History< iii_drone::adapters::PowerlineAdapter >::SharedPtr powerline_adapter_history, iii_drone::utils::History< iii_drone::adapters::GripperStatusAdapter >::SharedPtr gripper_status_adapter_history, iii_drone::utils::Atomic< double >::SharedPtr ground_altitude_estimate, iii_drone::utils::Atomic< int >::SharedPtr target_cable_id, iii_drone::control::maneuver::ManeuverQueue::SharedPtr maneuver_queue, iii_drone::utils::Atomic< iii_drone::control::maneuver::maneuver_t >::SharedPtr current_manuever, tf2_ros::Buffer::SharedPtr tf_buffer)
Constructor.
Parameters
parameters The parameters for the behavior state object.
vehicle_status_adapter_history The vehicle status adapter history.
vehicle_odometry_adapter_history The vehicle odometry adapter history.
powerline_adapter_history The powerline adapter history.
gripper_status_adapter_history The gripper status adapter history.
ground_altitude_estimate The ground altitude estimate.
target_cable_id The target cable id.
maneuver_queue The maneuver queue.
current_manuever The current maneuver.
tf_buffer The tf buffer.
Definition at line 17 of file behavior_state.cpp.
  : parameters_(parameters),
    vehicle_status_adapter_history_(vehicle_status_adapter_history),
    vehicle_odometry_adapter_history_(vehicle_odometry_adapter_history),
    powerline_adapter_history_(powerline_adapter_history),
    gripper_status_adapter_history_(gripper_status_adapter_history),
    ground_altitude_estimate_(ground_altitude_estimate),
    target_cable_id_(target_cable_id),
    maneuver_queue_(maneuver_queue),
    current_maneuver_(current_maneuver),
    tf_buffer_(tf_buffer) { }
Member Function Documentation
armed()
bool BehaviorState::armed () const
Whether the drone is armed.
Returns
true if the drone is armed.
Definition at line 178 of file behavior_state.cpp.
{
    if (vehicle_status_adapter_history_->empty()) {
        return false;
    }
    return (*vehicle_status_adapter_history_)[0].arming_state() == iii_drone::adapters::px4::ARMING_STATE_ARMED;
}
References iii_drone::adapters::px4::ARMING_STATE_ARMED, iii_drone::utils::History< T >::empty(), and vehicle_status_adapter_history_.
Referenced by behavior_state().
behavior_state()
behavior_state_t BehaviorState::behavior_state () const
Get the behavior state of the drone.
Returns
The behavior state of the drone.
Definition at line 367 of file behavior_state.cpp.
{
    behavior_state_t behavior_state;
    behavior_state.armed = armed();
    behavior_state.offboard = offboard();
    behavior_state.has_target_cable = has_target_cable();
    behavior_state.target_cable_position_known = target_cable_position_known();
    behavior_state.drone_location = drone_location(behavior_state.on_cable_id);
    behavior_state.maneuver_is_executing = maneuver_executing();
    behavior_state.current_maneuver = current_maneuver();
    return behavior_state;
}
References iii_drone::control::behavior_state_t::armed, armed(), behavior_state(), iii_drone::control::behavior_state_t::current_maneuver, current_maneuver(), iii_drone::control::behavior_state_t::drone_location, drone_location(), iii_drone::control::behavior_state_t::has_target_cable, has_target_cable(), maneuver_executing(), iii_drone::control::behavior_state_t::maneuver_is_executing, iii_drone::control::behavior_state_t::offboard, offboard(), iii_drone::control::behavior_state_t::on_cable_id, iii_drone::control::behavior_state_t::target_cable_position_known, and target_cable_position_known().
Referenced by behavior_state(), CanExecute(), maneuverCanExecute(), and ProjectExpectedBehaviorState().
CanExecute()
bool BehaviorState::CanExecute (iii_drone::control::maneuver::maneuver_t maneuver) const
Returns the expected behavior state upon completion or failure of given maneuver type,.
Parameters
maneuver The maneuver.
behavior_state The behavior state.
Returns
The expected behavior state upon completion of given maneuver.
Returns whether a given maneuver can immediately execute
Parameters
maneuver The maneuver.
Returns
true if the maneuver can immediately execute.
Definition at line 153 of file behavior_state.cpp.
{
    return maneuverCanExecute(
        maneuver,
        behavior_state()
    );
}
References behavior_state(), and maneuverCanExecute().
CanSchedule()
bool BehaviorState::CanSchedule (iii_drone::control::maneuver::maneuver_t maneuver) const
Returns whether a given maneuver can execute later.
Parameters
maneuver The maneuver.
Returns
true if the maneuver can execute later.
Definition at line 162 of file behavior_state.cpp.
{
    try {
        ProjectExpectedBehaviorState(maneuver);
    } catch (std::runtime_error & e) {
        return false;
    }
    return true;
}
References ProjectExpectedBehaviorState().
current_maneuver()
iii_drone::control::maneuver::maneuver_t BehaviorState::current_maneuver () const
Get the current maneuver.
Returns
The current maneuver.
Definition at line 347 of file behavior_state.cpp.
{
    return current_maneuver_->Load();
}
References current_maneuver_, and iii_drone::utils::Atomic< T >::Load().
Referenced by behavior_state(), maneuver_executing(), and ProjectExpectedBehaviorState().
drone_location() [1/2]
drone_location_t BehaviorState::drone_location () const
Returns the drone location.
Returns
The drone location.
Definition at line 339 of file behavior_state.cpp.
{
    int on_cable_id_out;
    return drone_location(on_cable_id_out);
}
References drone_location().
Referenced by behavior_state(), drone_location(), and drone_location().
drone_location() [2/2]
drone_location_t BehaviorState::drone_location (int & on_cable_id) const
Returns the drone location, checks the drone location and sets the on_cable_id if the drone is on a cable.
Parameters
on_cable_id The id of the cable that the drone is on if it is on a cable, -1 otherwise.
Returns
The drone location.
Definition at line 306 of file behavior_state.cpp.
{
    drone_location_t drone_location = DRONE_LOCATION_UNKNOWN;
    if (vehicle_odometry_adapter_history_->empty()) {
        on_cable_id_out = -1;
        drone_location = DRONE_LOCATION_UNKNOWN;
    } else if (on_ground()) {
        on_cable_id_out = -1;
        drone_location = DRONE_LOCATION_ON_GROUND;
    } else {
        on_cable_id_out = on_cable_id();
        if (on_cable_id_out >= 0) {
            drone_location = DRONE_LOCATION_ON_CABLE;
        } else {
            drone_location = DRONE_LOCATION_IN_FLIGHT;
        }
    }
    return drone_location;
}
References drone_location(), iii_drone::control::DRONE_LOCATION_IN_FLIGHT, iii_drone::control::DRONE_LOCATION_ON_CABLE, iii_drone::control::DRONE_LOCATION_ON_GROUND, iii_drone::control::DRONE_LOCATION_UNKNOWN, iii_drone::utils::History< T >::empty(), on_cable_id(), on_ground(), and vehicle_odometry_adapter_history_.
has_target_cable()
bool BehaviorState::has_target_cable () const
Whether the drone has a target cable.
Returns
true if the drone has a target cable.
Definition at line 202 of file behavior_state.cpp.
{
    return target_cable_id_->Load() >= 0;
}
References iii_drone::utils::Atomic< T >::Load(), and target_cable_id_.
Referenced by behavior_state().
in_flight()
bool BehaviorState::in_flight () const
Whether the drone is in flight.
Returns
true if the drone is in flight.
Definition at line 250 of file behavior_state.cpp.
{
    return !on_ground() && !on_cable();
}
References on_cable(), and on_ground().
maneuver_executing()
bool BehaviorState::maneuver_executing () const
Get whether a maneuver is being executed.
Returns
true if a maneuver is being executed.
Definition at line 353 of file behavior_state.cpp.
{
    if (!(*maneuver_queue_).empty()) {
        return true;
    }
    iii_drone::control::maneuver::maneuver_t current_maneuver = current_maneuver_->Load();
    return current_maneuver.type != iii_drone::control::maneuver::MANEUVER_TYPE_NONE;
}
References current_maneuver(), current_maneuver_, iii_drone::utils::Atomic< T >::Load(), iii_drone::control::maneuver::MANEUVER_TYPE_NONE, and iii_drone::control::maneuver::maneuver_t::type.
Referenced by behavior_state().
maneuverCanExecute()
bool BehaviorState::maneuverCanExecute (iii_drone::control::maneuver::maneuver_t maneuver, iii_drone::control::behavior_state_t behavior_state) const private
Evaluates whether a maneuver can be executed given a behavior state.
Parameters
maneuver The maneuver.
behavior_state The behavior state.
Returns
true if the maneuver can be executed.
Definition at line 383 of file behavior_state.cpp.
        {
    if (behavior_state.maneuver_is_executing) {
        return false;
    }
    switch(maneuver.type) {
        case maneuver::MANEUVER_TYPE_TAKEOFF: {
            std::shared_ptr<takeoff_maneuver_params_t> takeoff_maneuver_params = std::static_pointer_cast<takeoff_maneuver_params_t>(maneuver.params);
            float target_altitude = takeoff_maneuver_params->target_altitude;
            bool target_altitude_valid = target_altitude >= parameters_->minimum_target_altitude();
            return behavior_state.armed &&
                behavior_state.offboard &&
                behavior_state.on_ground() &&
                target_altitude_valid;
        }
        case maneuver::MANEUVER_TYPE_LANDING:
            return behavior_state.in_flight();
        case maneuver::MANEUVER_TYPE_FLY_TO_POSITION: {
            std::shared_ptr<fly_to_position_maneuver_params_t> fly_to_position_maneuver_params = std::static_pointer_cast<fly_to_position_maneuver_params_t>(maneuver.params);
            point_t target_position_in_world_frame = fly_to_position_maneuver_params->transform_target_position(
                parameters_->world_frame_id(),
                tf_buffer_
            );
            bool target_position_valid = target_position_in_world_frame[2] - ground_altitude_estimate_->Load() >= parameters_->minimum_target_altitude();
            return behavior_state.in_flight() &&
                behavior_state.offboard &&
                target_position_valid;
        }
        case maneuver::MANEUVER_TYPE_FLY_TO_OBJECT:
            return behavior_state.in_flight() &&
                behavior_state.offboard;
        case maneuver::MANEUVER_TYPE_CABLE_LANDING:
            return behavior_state.in_flight() &&
                behavior_state.offboard &&
                behavior_state.has_target_cable &&
                behavior_state.target_cable_position_known;
        case maneuver::MANEUVER_TYPE_CABLE_TAKEOFF:
            return behavior_state.on_cable() &&
                behavior_state.offboard &&
                behavior_state.armed &&
                behavior_state.has_target_cable &&
                behavior_state.target_cable_position_known;
        case maneuver::MANEUVER_TYPE_DISARM_ON_CABLE:
            return behavior_state.on_cable() &&
                behavior_state.offboard &&
                behavior_state.armed &&
                behavior_state.has_target_cable &&
                behavior_state.target_cable_position_known;
        case maneuver::MANEUVER_TYPE_ARM_ON_CABLE:
            return behavior_state.on_cable() &&
                !behavior_state.armed &&
                behavior_state.has_target_cable &&
                behavior_state.target_cable_position_known;
        default:
            return true;
    }
}
References iii_drone::control::behavior_state_t::armed, behavior_state(), ground_altitude_estimate_, iii_drone::control::behavior_state_t::has_target_cable, iii_drone::control::behavior_state_t::in_flight(), iii_drone::utils::Atomic< T >::Load(), iii_drone::control::behavior_state_t::maneuver_is_executing, iii_drone::control::maneuver::MANEUVER_TYPE_ARM_ON_CABLE, iii_drone::control::maneuver::MANEUVER_TYPE_CABLE_LANDING, iii_drone::control::maneuver::MANEUVER_TYPE_CABLE_TAKEOFF, iii_drone::control::maneuver::MANEUVER_TYPE_DISARM_ON_CABLE, iii_drone::control::maneuver::MANEUVER_TYPE_FLY_TO_OBJECT, iii_drone::control::maneuver::MANEUVER_TYPE_FLY_TO_POSITION, iii_drone::control::maneuver::MANEUVER_TYPE_LANDING, iii_drone::control::maneuver::MANEUVER_TYPE_TAKEOFF, iii_drone::control::BehaviorStateParameters::minimum_target_altitude(), iii_drone::control::behavior_state_t::offboard, iii_drone::control::behavior_state_t::on_cable(), iii_drone::control::behavior_state_t::on_ground(), parameters_, iii_drone::control::maneuver::maneuver_t::params, iii_drone::control::behavior_state_t::target_cable_position_known, tf_buffer_, iii_drone::control::maneuver::maneuver_t::type, and iii_drone::control::BehaviorStateParameters::world_frame_id().
Referenced by CanExecute(), and ProjectExpectedBehaviorState().
offboard()
bool BehaviorState::offboard () const
Whether the drone is in offboard mode.
Returns
true if the drone is in offboard mode.
Definition at line 190 of file behavior_state.cpp.
{
    if (vehicle_status_adapter_history_->empty()) {
        return false;
    }
    return (*vehicle_status_adapter_history_)[0].nav_state() == iii_drone::adapters::px4::NAVIGATION_STATE_OFFBOARD;
}
References iii_drone::utils::History< T >::empty(), iii_drone::adapters::px4::NAVIGATION_STATE_OFFBOARD, and vehicle_status_adapter_history_.
Referenced by behavior_state().
on_cable()
bool BehaviorState::on_cable () const
Whether the drone is on a cable.
Returns
true if the drone is on a cable.
Definition at line 244 of file behavior_state.cpp.
{
    return on_cable_id() >= 0;
}
References on_cable_id().
Referenced by in_flight().
on_cable_id()
int BehaviorState::on_cable_id () const
Return the id of the cable that the drone is on if it is on a cable, -1 otherwise.
Returns
The id of the cable that the drone is on if it is on a cable, -1 otherwise.
Definition at line 256 of file behavior_state.cpp.
{
    if (vehicle_odometry_adapter_history_->empty()) {
        return false;
    }
    if (powerline_adapter_history_->empty()) {
        return false;
    }
    iii_drone::adapters::px4::VehicleOdometryAdapter vehicle_odometry_adapter = (*vehicle_odometry_adapter_history_)[0];
    point_t drone_position = vehicle_odometry_adapter.position();
    geometry_msgs::msg::TransformStamped transform_stamped = tf_buffer_->lookupTransform(
        parameters_->cable_gripper_frame_id(),
        parameters_->drone_frame_id(),
        tf2::TimePointZero
    );
    vector_t v_drone_to_gripper = vectorFromTransformMsg(transform_stamped.transform);
    point_t gripper_position = drone_position + v_drone_to_gripper;
    iii_drone::adapters::PowerlineAdapter powerline_adapter = (*powerline_adapter_history_)[0];
    iii_drone::adapters::SingleLineAdapter closest_line;
    try {
        closest_line = powerline_adapter.GetClosestLine(gripper_position);
    } catch (std::runtime_error & e) {
        return -1;
    }
    point_t closest_line_position = closest_line.position();
    if ((closest_line_position - gripper_position).norm() <= parameters_->on_cable_max_euc_distance()) {
        return closest_line.id();
    }
    return -1;
}
References iii_drone::control::BehaviorStateParameters::cable_gripper_frame_id(), iii_drone::control::BehaviorStateParameters::drone_frame_id(), iii_drone::utils::History< T >::empty(), iii_drone::adapters::PowerlineAdapter::GetClosestLine(), iii_drone::adapters::SingleLineAdapter::id(), iii_drone::control::BehaviorStateParameters::on_cable_max_euc_distance(), parameters_, iii_drone::adapters::px4::VehicleOdometryAdapter::position(), iii_drone::adapters::SingleLineAdapter::position(), powerline_adapter_history_, tf_buffer_, iii_drone::types::vectorFromTransformMsg(), and vehicle_odometry_adapter_history_.
Referenced by drone_location(), and on_cable().
on_ground()
bool BehaviorState::on_ground () const
Whether the drone is on the ground.
Returns
true if the drone is on the ground.
Definition at line 228 of file behavior_state.cpp.
{
    if (vehicle_odometry_adapter_history_->empty()) {
        return false;
    }
    iii_drone::adapters::px4::VehicleOdometryAdapter vehicle_odometry_adapter = (*vehicle_odometry_adapter_history_)[0];
    point_t position = vehicle_odometry_adapter.position();
    return position[2] <= ground_altitude_estimate_->Load() + parameters_->landed_altitude_threshold();
}
References iii_drone::utils::History< T >::empty(), ground_altitude_estimate_, iii_drone::control::BehaviorStateParameters::landed_altitude_threshold(), iii_drone::utils::Atomic< T >::Load(), parameters_, iii_drone::adapters::px4::VehicleOdometryAdapter::position(), and vehicle_odometry_adapter_history_.
Referenced by drone_location(), and in_flight().
ProjectExpectedBehaviorState() [1/2]
behavior_state_t BehaviorState::ProjectExpectedBehaviorState (iii_drone::control::maneuver::maneuver_t maneuver) const
Returns the expected behavior state upon completion or failure of given maneuver type, considering the full maneuver queue.
Parameters
maneuver The maneuver.
Returns
The expected behavior state upon completion of given maneuver.
Exceptions
std::runtime_error if a maneuver in the queue cannot be executed.
Definition at line 39 of file behavior_state.cpp.
{
    std::vector<maneuver_t> maneuver_queue = (*maneuver_queue_).vector();
    maneuver_t current_maneuver = current_maneuver_->Load();
    if (maneuver_queue.size() == 0 || maneuver_queue[0] != current_maneuver) {
        maneuver_queue.insert(
            maneuver_queue.begin(),
            current_maneuver
        );
    }
    maneuver_queue.push_back(maneuver);
    behavior_state_t bhst = behavior_state();
    bhst.maneuver_is_executing = false;
    bhst.current_maneuver = maneuver_t();
    for (unsigned int i = 0; i < maneuver_queue.size(); i++) {
        if (
            !maneuverCanExecute(
                maneuver_queue[i],
                bhst
            )
        ) {
            throw std::runtime_error("BehaviorState::ProjectExpectedBehaviorState: maneuver queue is invalid");
        }
        bhst = ProjectExpectedBehaviorState(
            maneuver_queue[i],
            bhst
        );
    }
    return bhst;
}
References behavior_state(), iii_drone::control::behavior_state_t::current_maneuver, current_maneuver(), current_maneuver_, iii_drone::utils::Atomic< T >::Load(), iii_drone::control::behavior_state_t::maneuver_is_executing, maneuverCanExecute(), and ProjectExpectedBehaviorState().
Referenced by CanSchedule(), and ProjectExpectedBehaviorState().
ProjectExpectedBehaviorState() [2/2]
behavior_state_t BehaviorState::ProjectExpectedBehaviorState (iii_drone::control::maneuver::maneuver_t maneuver, iii_drone::control::behavior_state_t behavior_state) const
Returns the expected behavior state upon completion or failure of given maneuver type, given a current behavior state.
Parameters
maneuver The maneuver.
behavior_state The behavior state.
Returns
The expected behavior state upon completion of given maneuver.
Definition at line 84 of file behavior_state.cpp.
        {
    behavior_state_t bhst_out = bhst;
    bhst_out.maneuver_is_executing = false;
    bhst_out.current_maneuver = maneuver_t();
    switch(maneuver.type) {
        case maneuver::MANEUVER_TYPE_TAKEOFF:
            bhst_out.armed = true;
            bhst_out.offboard = true;
            bhst_out.drone_location = DRONE_LOCATION_IN_FLIGHT;
            break;
        case maneuver::MANEUVER_TYPE_LANDING:
            bhst_out.armed = false;
            bhst_out.offboard = false;
            bhst_out.drone_location = DRONE_LOCATION_ON_GROUND;
            break;
        case maneuver::MANEUVER_TYPE_FLY_TO_POSITION:
            bhst_out.armed = true;
            bhst_out.offboard = true;
            bhst_out.drone_location = DRONE_LOCATION_IN_FLIGHT;
            break;
        case maneuver::MANEUVER_TYPE_FLY_TO_OBJECT:
            bhst_out.armed = true;
            bhst_out.offboard = true;
            bhst_out.drone_location = DRONE_LOCATION_IN_FLIGHT;
            break;
        case maneuver::MANEUVER_TYPE_CABLE_LANDING:
            bhst_out.armed = true;
            bhst_out.offboard = true;
            bhst_out.drone_location = DRONE_LOCATION_ON_CABLE;
            break;
        case maneuver::MANEUVER_TYPE_CABLE_TAKEOFF:
            bhst_out.armed = true;
            bhst_out.offboard = true;
            bhst_out.drone_location = DRONE_LOCATION_IN_FLIGHT;
            break;
        case maneuver::MANEUVER_TYPE_DISARM_ON_CABLE:
            bhst_out.armed = false;
            bhst_out.offboard = false;
            bhst_out.drone_location = DRONE_LOCATION_ON_CABLE;
            break;
        case maneuver::MANEUVER_TYPE_ARM_ON_CABLE:
            bhst_out.armed = true;
            bhst_out.offboard = true;
            bhst_out.drone_location = DRONE_LOCATION_ON_CABLE;
            break;
        default:
            break;
    }
    return bhst_out;
}
References iii_drone::control::behavior_state_t::armed, iii_drone::control::behavior_state_t::current_maneuver, iii_drone::control::behavior_state_t::drone_location, iii_drone::control::DRONE_LOCATION_IN_FLIGHT, iii_drone::control::DRONE_LOCATION_ON_CABLE, iii_drone::control::DRONE_LOCATION_ON_GROUND, iii_drone::control::behavior_state_t::maneuver_is_executing, iii_drone::control::maneuver::MANEUVER_TYPE_ARM_ON_CABLE, iii_drone::control::maneuver::MANEUVER_TYPE_CABLE_LANDING, iii_drone::control::maneuver::MANEUVER_TYPE_CABLE_TAKEOFF, iii_drone::control::maneuver::MANEUVER_TYPE_DISARM_ON_CABLE, iii_drone::control::maneuver::MANEUVER_TYPE_FLY_TO_OBJECT, iii_drone::control::maneuver::MANEUVER_TYPE_FLY_TO_POSITION, iii_drone::control::maneuver::MANEUVER_TYPE_LANDING, iii_drone::control::maneuver::MANEUVER_TYPE_TAKEOFF, iii_drone::control::behavior_state_t::offboard, and iii_drone::control::maneuver::maneuver_t::type.
target_cable_position_known()
bool BehaviorState::target_cable_position_known () const
Whether the position of the target cable is known.
Returns
true if the position of the target cable is known.
Definition at line 208 of file behavior_state.cpp.
{
    if (powerline_adapter_history_->empty()) {
        return false;
    }
    int target_cable_id = target_cable_id_->Load();
    if (target_cable_id < 0) {
        return false;
    }
    return (*powerline_adapter_history_)[0].HasLine(target_cable_id);
}
References iii_drone::utils::History< T >::empty(), iii_drone::utils::Atomic< T >::Load(), powerline_adapter_history_, and target_cable_id_.
Referenced by behavior_state().
Member Data Documentation
current_maneuver_
iii_drone::utils::Atomic<iii_drone::control::maneuver::maneuver_t>::SharedPtr iii_drone::control::BehaviorState::current_maneuver_ private
The current maneuver.
Definition at line 332 of file behavior_state.hpp.
Referenced by current_maneuver(), maneuver_executing(), and ProjectExpectedBehaviorState().
gripper_status_adapter_history_
iii_drone::utils::History<iii_drone::adapters::GripperStatusAdapter>::SharedPtr iii_drone::control::BehaviorState::gripper_status_adapter_history_ private
The gripper status adapter history.
Definition at line 312 of file behavior_state.hpp.
ground_altitude_estimate_
iii_drone::utils::Atomic<double>::SharedPtr iii_drone::control::BehaviorState::ground_altitude_estimate_ private
The ground altitude estimate.
Definition at line 317 of file behavior_state.hpp.
Referenced by maneuverCanExecute(), and on_ground().
maneuver_queue_
iii_drone::control::maneuver::ManeuverQueue::SharedPtr iii_drone::control::BehaviorState::maneuver_queue_ private
The maneuver queue.
Definition at line 327 of file behavior_state.hpp.
parameters_
iii_drone::control::BehaviorStateParameters::SharedPtr iii_drone::control::BehaviorState::parameters_ private
The parameters for the behavior state object.
Definition at line 292 of file behavior_state.hpp.
Referenced by maneuverCanExecute(), on_cable_id(), and on_ground().
powerline_adapter_history_
iii_drone::utils::History<iii_drone::adapters::PowerlineAdapter>::SharedPtr iii_drone::control::BehaviorState::powerline_adapter_history_ private
The powerline adapter history.
Definition at line 307 of file behavior_state.hpp.
Referenced by on_cable_id(), and target_cable_position_known().
target_cable_id_
iii_drone::utils::Atomic<int>::SharedPtr iii_drone::control::BehaviorState::target_cable_id_ private
The target cable id.
Definition at line 322 of file behavior_state.hpp.
Referenced by has_target_cable(), and target_cable_position_known().
tf_buffer_
tf2_ros::Buffer::SharedPtr iii_drone::control::BehaviorState::tf_buffer_ private
The tf buffer.
Definition at line 337 of file behavior_state.hpp.
Referenced by maneuverCanExecute(), and on_cable_id().
vehicle_odometry_adapter_history_
iii_drone::utils::History<iii_drone::adapters::px4::VehicleOdometryAdapter>::SharedPtr iii_drone::control::BehaviorState::vehicle_odometry_adapter_history_ private
The vehicle odometry adapter history.
Definition at line 302 of file behavior_state.hpp.
Referenced by drone_location(), on_cable_id(), and on_ground().
vehicle_status_adapter_history_
iii_drone::utils::History<iii_drone::adapters::px4::VehicleStatusAdapter>::SharedPtr iii_drone::control::BehaviorState::vehicle_status_adapter_history_ private
The vehicle status adapter history.
Definition at line 297 of file behavior_state.hpp.
Referenced by armed(), and offboard().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/behavior_state.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/behavior_state.cpp