III-Drone: iii_drone::control::maneuver_controller_node::ManeuverControllerNode Class Reference
iii_drone::control::maneuver_controller_node::ManeuverControllerNode Class Reference
The ManeuverControllerNode class. Responsible for execution of maneuvers. Uses the CombinedDroneAwarenessHandler to get the state of the drone and the environment. Uses the ManeuverScheduler to schedule and execute maneuvers. Creates all maneuver servers and registers them with the ManeuverScheduler. Exposes action servers contained in the registered maneuver servers. Exposes a topic for publishing the reference, contained in the ManeuverScheduler.
#include <maneuver_controller_node.hpp>
Public Member Functions
ManeuverControllerNode (const std::string &node_name="maneuver_controller", const std::string &node_namespace="/control/maneuver_controller", const rclcpp::NodeOptions &options=rclcpp::NodeOptions())
Constructor. Creates the node, initializes the configurator, the transform buffer and listener, the combined drone awareness handler, the maneuver scheduler. Creates and registers all maneuver servers with the maneuver scheduler.
~ManeuverControllerNode ()
Destructor.
Private Member Functions
void registerManeuverServers ()
Creates and registers all maneuver servers with the maneuver scheduler.
Private Attributes
ManeuverControllerNodeConfigurator configurator_
Configurator for handling configuration parameters of the node. Exposes parameters for the maneuver scheduler and the maneuver servers.
tf2_ros::Buffer::SharedPtr tf_buffer_
The transform buffer. Shared with the CombinedDroneAwarenessHandler.
std::shared_ptr< tf2_ros::TransformListener > tf_listener_
The transform listener for listening to transforms and updating the transform buffer.
iii_drone::control::CombinedDroneAwarenessHandler::SharedPtr combined_drone_awareness_handler_
The combined drone awareness handler shared pointer. Shared with the maneuver servers and the maneuver scheduler.
iii_drone::control::TrajectoryGeneratorClient::SharedPtr trajectory_generator_client_
The trajectory generator client shared pointer.
rclcpp::CallbackGroup::SharedPtr maneuver_execution_cb_group_
The maneuver execution callback group. Enables multi processing of the execution of maneuvers (scheduling and computing references).
iii_drone::control::maneuver::ManeuverScheduler::UniquePtr maneuver_scheduler_
The maneuver scheduler shared pointer. Responsible for scheduling and executing maneuvers.
std::shared_ptr< iii_drone::control::maneuver::HoverManeuverServer > hover_maneuver_server_
The hover maneuver server shared pointer. Will serve hover action requests as well as generate hover references in between maneuvers for the maneuver scheduler to use.
std::shared_ptr< iii_drone::control::maneuver::HoverByObjectManeuverServer > hover_by_object_maneuver_server_
The hover by object maneuver server shared pointer. Will serve hover by object action requests as well as generate hover by object references in between maneuvers for the maneuver scheduler to use.
std::shared_ptr< iii_drone::control::maneuver::HoverOnCableManeuverServer > hover_on_cable_maneuver_server_
The hover on cable maneuver server shared pointer. Will serve hover on cable action requests as well as generate hover on cable references in between maneuvers for the maneuver scheduler to use.
std::shared_ptr< iii_drone::control::maneuver::FlyToPositionManeuverServer > fly_to_position_maneuver_server_
The fly to position maneuver server shared pointer. Will serve fly to position action requests.
std::shared_ptr< iii_drone::control::maneuver::FlyToObjectManeuverServer > fly_to_object_maneuver_server_
The fly to object maneuver server shared pointer. Will serve fly to object action requests.
Detailed Description
The ManeuverControllerNode class. Responsible for execution of maneuvers. Uses the CombinedDroneAwarenessHandler to get the state of the drone and the environment. Uses the ManeuverScheduler to schedule and execute maneuvers. Creates all maneuver servers and registers them with the ManeuverScheduler. Exposes action servers contained in the registered maneuver servers. Exposes a topic for publishing the reference, contained in the ManeuverScheduler.
When creating new maneuvers, take the following steps:
Create a new action type in the iii_drone_interfaces package.
Create a new maneuver type in the maneuver_types.hpp file.
If necessary, create a maneuver parameters struct in the maneuver_types.hpp file.
Create a new maneuver server class in the maneuver directory, inheriting from ManeuverServer, implement the virtual methods.
Create a new maneuver server in the registerManeuverServers method of this class and register it with the ManeuverScheduler.
Definition at line 68 of file maneuver_controller_node.hpp.
Constructor & Destructor Documentation
ManeuverControllerNode()
ManeuverControllerNode::ManeuverControllerNode (const std::string & node_name = "maneuver_controller", const std::string & node_namespace = "/control/maneuver_controller", const rclcpp::NodeOptions & options = rclcpp::NodeOptions())
Constructor. Creates the node, initializes the configurator, the transform buffer and listener, the combined drone awareness handler, the maneuver scheduler. Creates and registers all maneuver servers with the maneuver scheduler.
Parameters
node_name The name of the node.
node_namespace The namespace of the node.
options The node options.
Definition at line 17 of file maneuver_controller_node.cpp.
  : Node(
    node_name,
    node_namespace,
    options
),  configurator_(this) {
    tf_buffer_ = std::make_shared<tf2_ros::Buffer>(get_clock());
    tf_listener_ = std::make_shared<tf2_ros::TransformListener>(*tf_buffer_);
    combined_drone_awareness_handler_ = std::make_shared<CombinedDroneAwarenessHandler>(
        configurator_.combined_drone_awareness_handler_parameters(),
        tf_buffer_,
        this
    );
    std::vector<int64_t> px4_offboard_mode_ids = configurator_.px4_offboard_mode_ids();
    for (const auto & id : px4_offboard_mode_ids) {
        combined_drone_awareness_handler_->RegisterOffboardMode(id);
    }
    trajectory_generator_client_ = std::make_shared<TrajectoryGeneratorClient>(this);
    maneuver_execution_cb_group_ = this->create_callback_group(
        rclcpp::CallbackGroupType::MutuallyExclusive
    );
    maneuver_scheduler_ = std::make_unique<ManeuverScheduler>(
        this,
        combined_drone_awareness_handler_,
        configurator_.maneuver_scheduler_parameters(),
        maneuver_execution_cb_group_
    );
    registerManeuverServers();
}
References combined_drone_awareness_handler_, iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::combined_drone_awareness_handler_parameters(), configurator_, maneuver_execution_cb_group_, maneuver_scheduler_, iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::maneuver_scheduler_parameters(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::px4_offboard_mode_ids(), registerManeuverServers(), iii_drone::control::CombinedDroneAwarenessHandler::RegisterOffboardMode(), tf_buffer_, tf_listener_, and trajectory_generator_client_.
~ManeuverControllerNode()
ManeuverControllerNode::~ManeuverControllerNode ()
Destructor.
Definition at line 59 of file maneuver_controller_node.cpp.
{
    RCLCPP_INFO(get_logger(), "Shutting down maneuver controller node");
}
Member Function Documentation
registerManeuverServers()
void ManeuverControllerNode::registerManeuverServers () private
Creates and registers all maneuver servers with the maneuver scheduler.
Definition at line 63 of file maneuver_controller_node.cpp.
{
    hover_maneuver_server_ = std::make_shared<HoverManeuverServer>(
        this,
        combined_drone_awareness_handler_,
        "hover",
        configurator_.maneuver_wait_for_execute_poll_ms(),
        configurator_.maneuver_evaluate_done_poll_ms(),
        configurator_.use_nans_when_hovering()
    );
    maneuver_scheduler_->RegisterManeuverServer(
        MANEUVER_TYPE_HOVER,
        std::static_pointer_cast<ManeuverServer>(hover_maneuver_server_)
    );
    hover_by_object_maneuver_server_ = std::make_shared<HoverByObjectManeuverServer>(
        this,
        combined_drone_awareness_handler_,
        "hover_by_object",
        configurator_.maneuver_wait_for_execute_poll_ms(),
        configurator_.maneuver_evaluate_done_poll_ms(),
        configurator_.use_nans_when_hovering(),
        configurator_.hover_by_object_max_euc_dist()
    );
    maneuver_scheduler_->RegisterManeuverServer(
        MANEUVER_TYPE_HOVER_BY_OBJECT,
        std::static_pointer_cast<ManeuverServer>(hover_by_object_maneuver_server_)
    );
    hover_on_cable_maneuver_server_ = std::make_shared<HoverOnCableManeuverServer>(
        this,
        combined_drone_awareness_handler_,
        "hover_on_cable",
        configurator_.maneuver_wait_for_execute_poll_ms(),
        configurator_.maneuver_evaluate_done_poll_ms(),
        configurator_.hover_on_cable_default_z_velocity(),
        configurator_.hover_on_cable_default_yaw_rate()
    );
    maneuver_scheduler_->RegisterManeuverServer(
        MANEUVER_TYPE_HOVER_ON_CABLE,
        std::static_pointer_cast<ManeuverServer>(hover_on_cable_maneuver_server_)
    );
    fly_to_position_maneuver_server_ = std::make_shared<FlyToPositionManeuverServer>(
        this,
        combined_drone_awareness_handler_,
        "fly_to_position",
        configurator_.maneuver_wait_for_execute_poll_ms(),
        configurator_.maneuver_evaluate_done_poll_ms(),
        configurator_.fly_to_position_maneuver_server_parameters(),
        trajectory_generator_client_
    );
    maneuver_scheduler_->RegisterManeuverServer(
        MANEUVER_TYPE_FLY_TO_POSITION,
        std::static_pointer_cast<ManeuverServer>(fly_to_position_maneuver_server_)
    );
    fly_to_object_maneuver_server_ = std::make_shared<FlyToObjectManeuverServer>(
        this,
        combined_drone_awareness_handler_,
        "fly_to_object",
        configurator_.maneuver_wait_for_execute_poll_ms(),
        configurator_.maneuver_evaluate_done_poll_ms(),
        configurator_.fly_to_object_maneuver_server_parameters(),
        trajectory_generator_client_
    );
}
References combined_drone_awareness_handler_, configurator_, fly_to_object_maneuver_server_, iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::fly_to_object_maneuver_server_parameters(), fly_to_position_maneuver_server_, iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::fly_to_position_maneuver_server_parameters(), hover_by_object_maneuver_server_, iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::hover_by_object_max_euc_dist(), hover_maneuver_server_, iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::hover_on_cable_default_yaw_rate(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::hover_on_cable_default_z_velocity(), hover_on_cable_maneuver_server_, iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::maneuver_evaluate_done_poll_ms(), maneuver_scheduler_, iii_drone::control::maneuver::MANEUVER_TYPE_FLY_TO_POSITION, iii_drone::control::maneuver::MANEUVER_TYPE_HOVER, iii_drone::control::maneuver::MANEUVER_TYPE_HOVER_BY_OBJECT, iii_drone::control::maneuver::MANEUVER_TYPE_HOVER_ON_CABLE, iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::maneuver_wait_for_execute_poll_ms(), iii_drone::control::maneuver::ManeuverScheduler::RegisterManeuverServer(), trajectory_generator_client_, and iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::use_nans_when_hovering().
Referenced by ManeuverControllerNode().
Member Data Documentation
combined_drone_awareness_handler_
iii_drone::control::CombinedDroneAwarenessHandler::SharedPtr iii_drone::control::maneuver_controller_node::ManeuverControllerNode::combined_drone_awareness_handler_ private
The combined drone awareness handler shared pointer. Shared with the maneuver servers and the maneuver scheduler.
Definition at line 112 of file maneuver_controller_node.hpp.
Referenced by ManeuverControllerNode(), and registerManeuverServers().
configurator_
ManeuverControllerNodeConfigurator iii_drone::control::maneuver_controller_node::ManeuverControllerNode::configurator_ private
Configurator for handling configuration parameters of the node. Exposes parameters for the maneuver scheduler and the maneuver servers.
Definition at line 96 of file maneuver_controller_node.hpp.
Referenced by ManeuverControllerNode(), and registerManeuverServers().
fly_to_object_maneuver_server_
std::shared_ptr<iii_drone::control::maneuver::FlyToObjectManeuverServer> iii_drone::control::maneuver_controller_node::ManeuverControllerNode::fly_to_object_maneuver_server_ private
The fly to object maneuver server shared pointer. Will serve fly to object action requests.
Definition at line 163 of file maneuver_controller_node.hpp.
Referenced by registerManeuverServers().
fly_to_position_maneuver_server_
std::shared_ptr<iii_drone::control::maneuver::FlyToPositionManeuverServer> iii_drone::control::maneuver_controller_node::ManeuverControllerNode::fly_to_position_maneuver_server_ private
The fly to position maneuver server shared pointer. Will serve fly to position action requests.
Definition at line 157 of file maneuver_controller_node.hpp.
Referenced by registerManeuverServers().
hover_by_object_maneuver_server_
std::shared_ptr<iii_drone::control::maneuver::HoverByObjectManeuverServer> iii_drone::control::maneuver_controller_node::ManeuverControllerNode::hover_by_object_maneuver_server_ private
The hover by object maneuver server shared pointer. Will serve hover by object action requests as well as generate hover by object references in between maneuvers for the maneuver scheduler to use.
Definition at line 144 of file maneuver_controller_node.hpp.
Referenced by registerManeuverServers().
hover_maneuver_server_
std::shared_ptr<iii_drone::control::maneuver::HoverManeuverServer> iii_drone::control::maneuver_controller_node::ManeuverControllerNode::hover_maneuver_server_ private
The hover maneuver server shared pointer. Will serve hover action requests as well as generate hover references in between maneuvers for the maneuver scheduler to use.
Definition at line 137 of file maneuver_controller_node.hpp.
Referenced by registerManeuverServers().
hover_on_cable_maneuver_server_
std::shared_ptr<iii_drone::control::maneuver::HoverOnCableManeuverServer> iii_drone::control::maneuver_controller_node::ManeuverControllerNode::hover_on_cable_maneuver_server_ private
The hover on cable maneuver server shared pointer. Will serve hover on cable action requests as well as generate hover on cable references in between maneuvers for the maneuver scheduler to use.
Definition at line 151 of file maneuver_controller_node.hpp.
Referenced by registerManeuverServers().
maneuver_execution_cb_group_
rclcpp::CallbackGroup::SharedPtr iii_drone::control::maneuver_controller_node::ManeuverControllerNode::maneuver_execution_cb_group_ private
The maneuver execution callback group. Enables multi processing of the execution of maneuvers (scheduling and computing references).
Definition at line 123 of file maneuver_controller_node.hpp.
Referenced by ManeuverControllerNode().
maneuver_scheduler_
iii_drone::control::maneuver::ManeuverScheduler::UniquePtr iii_drone::control::maneuver_controller_node::ManeuverControllerNode::maneuver_scheduler_ private
The maneuver scheduler shared pointer. Responsible for scheduling and executing maneuvers.
Definition at line 129 of file maneuver_controller_node.hpp.
Referenced by ManeuverControllerNode(), and registerManeuverServers().
tf_buffer_
tf2_ros::Buffer::SharedPtr iii_drone::control::maneuver_controller_node::ManeuverControllerNode::tf_buffer_ private
The transform buffer. Shared with the CombinedDroneAwarenessHandler.
Definition at line 101 of file maneuver_controller_node.hpp.
Referenced by ManeuverControllerNode().
tf_listener_
std::shared_ptr<tf2_ros::TransformListener> iii_drone::control::maneuver_controller_node::ManeuverControllerNode::tf_listener_ private
The transform listener for listening to transforms and updating the transform buffer.
Definition at line 106 of file maneuver_controller_node.hpp.
Referenced by ManeuverControllerNode().
trajectory_generator_client_
iii_drone::control::TrajectoryGeneratorClient::SharedPtr iii_drone::control::maneuver_controller_node::ManeuverControllerNode::trajectory_generator_client_ private
The trajectory generator client shared pointer.
Definition at line 117 of file maneuver_controller_node.hpp.
Referenced by ManeuverControllerNode(), and registerManeuverServers().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/maneuver_controller_node/maneuver_controller_node.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/maneuver_controller_node/maneuver_controller_node.cpp