III-Drone: iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestratorConfigurator Class Reference
iii_drone::mission::continuous_mission_orchestrator_node::ContinuousMissionOrchestratorConfigurator Class Reference
Class for handling parameters for ContinuousMissionOrchestrator.
#include <continuous_mission_orchestrator_node_configurator.hpp>
Public Member Functions
ContinuousMissionOrchestratorConfigurator (rclcpp::Node *node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Constructor.
ContinuousMissionOrchestratorConfigurator (rclcpp::Node *node, const rclcpp::QoS &qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Constructor.
const bool simulation () const
Get the simulation flag.
const float under_cable_target_distance () const
Get the under cable target distance.
const bool use_charger_gripper_info () const
Get the use charger gripper info flag.
const int cable_landing_max_retries () const
Get the cable landing max retries.
const float battery_voltage_low_threshold () const
Get the battery voltage low threshold.
const float battery_voltage_high_threshold () const
Get the battery voltage high threshold.
const float charging_power_low_threshold () const
Get the charging power low threshold.
const int action_timeout_ms () const
Get the action timeout in milliseconds.
const int charging_minimum_duration_s () const
Get the charging minimum duration in seconds.
const int charging_maximum_duration_s () const
Get the charging maximum duration in seconds.
Public Member Functions inherited from iii_drone::configuration::Configurator
Configurator (rclcpp::Node *node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Configurator (rclcpp::Node *node, const rclcpp::QoS &qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
~Configurator ()
template<typename T >
void DeclareParameter (const std::string &name)
rclcpp::Parameter GetParameter (const std::string &name) const
Get a parameter.
std::vector< rclcpp::Parameter > GetParameters (const std::vector< std::string > &names) const
Gets multiple parameters.
void SyncParameters (const std::vector< std::string > &names={})
Synchronizes parameters with the parameter server. Should never be necessary.
void PrintParameters () const
Prints all parameters to the console.
Private Member Functions
void declareNodeParameters ()
Declares the node specific parameters.
Additional Inherited Members
Static Public Member Functions inherited from iii_drone::configuration::Configurator
template<typename T >
static std::string GetParameterTypeString ()
Static function for getting string representation of a parameter type from template type.
Protected Attributes inherited from iii_drone::configuration::Configurator
rclcpp::Node * node_
Detailed Description
Class for handling parameters for ContinuousMissionOrchestrator.
Definition at line 30 of file continuous_mission_orchestrator_node_configurator.hpp.
Constructor & Destructor Documentation
ContinuousMissionOrchestratorConfigurator() [1/2]
ContinuousMissionOrchestratorConfigurator::ContinuousMissionOrchestratorConfigurator (rclcpp::Node * node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback = nullptr)
Constructor.
Parameters
node Reference to the handling node
after_parameter_change_callback Callback function called after successful parameter change, default is nullptr
Definition at line 14 of file continuous_mission_orchestrator_node_configurator.cpp.
  : Configurator(
        node,
        after_parameter_change_callback
    ) {
    declareNodeParameters();
}
References declareNodeParameters().
ContinuousMissionOrchestratorConfigurator() [2/2]
ContinuousMissionOrchestratorConfigurator::ContinuousMissionOrchestratorConfigurator (rclcpp::Node * node, const rclcpp::QoS & qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback = nullptr)
Constructor.
Parameters
node Reference to the handling node
qos QoS profile for the parameter event subscription
after_parameter_change_callback Callback function called after successful parameter change, default is nullptr
Definition at line 26 of file continuous_mission_orchestrator_node_configurator.cpp.
  : Configurator(
        node,
        qos,
        after_parameter_change_callback
    ) {
    declareNodeParameters();
}
References declareNodeParameters().
Member Function Documentation
action_timeout_ms()
const int ContinuousMissionOrchestratorConfigurator::action_timeout_ms () const
Get the action timeout in milliseconds.
Returns
Action timeout in milliseconds
Definition at line 82 of file continuous_mission_orchestrator_node_configurator.cpp.
{
    return GetParameter("/mission/continuous_mission_orchestrator/action_timeout_ms").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
battery_voltage_high_threshold()
const float ContinuousMissionOrchestratorConfigurator::battery_voltage_high_threshold () const
Get the battery voltage high threshold.
Returns
Battery voltage high threshold
Definition at line 70 of file continuous_mission_orchestrator_node_configurator.cpp.
{
    return GetParameter("/mission/continuous_mission_orchestrator/battery_voltage_high_threshold").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
battery_voltage_low_threshold()
const float ContinuousMissionOrchestratorConfigurator::battery_voltage_low_threshold () const
Get the battery voltage low threshold.
Returns
Battery voltage low threshold
Definition at line 64 of file continuous_mission_orchestrator_node_configurator.cpp.
{
    return GetParameter("/mission/continuous_mission_orchestrator/battery_voltage_low_threshold").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
cable_landing_max_retries()
const int ContinuousMissionOrchestratorConfigurator::cable_landing_max_retries () const
Get the cable landing max retries.
Returns
Cable landing max retries
Definition at line 58 of file continuous_mission_orchestrator_node_configurator.cpp.
{
    return GetParameter("/mission/continuous_mission_orchestrator/cable_landing_max_retries").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
charging_maximum_duration_s()
const int ContinuousMissionOrchestratorConfigurator::charging_maximum_duration_s () const
Get the charging maximum duration in seconds.
Returns
Charging maximum duration in seconds
Definition at line 94 of file continuous_mission_orchestrator_node_configurator.cpp.
{
    return GetParameter("/mission/continuous_mission_orchestrator/charging_maximum_duration_s").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
charging_minimum_duration_s()
const int ContinuousMissionOrchestratorConfigurator::charging_minimum_duration_s () const
Get the charging minimum duration in seconds.
Returns
Charging minimum duration in seconds
Definition at line 88 of file continuous_mission_orchestrator_node_configurator.cpp.
{
    return GetParameter("/mission/continuous_mission_orchestrator/charging_minimum_duration_s").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
charging_power_low_threshold()
const float ContinuousMissionOrchestratorConfigurator::charging_power_low_threshold () const
Get the charging power low threshold.
Returns
Charging power low threshold
Definition at line 76 of file continuous_mission_orchestrator_node_configurator.cpp.
{
    return GetParameter("/mission/continuous_mission_orchestrator/charging_power_low_threshold").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
declareNodeParameters()
void ContinuousMissionOrchestratorConfigurator::declareNodeParameters () private
Declares the node specific parameters.
Returns
void
Definition at line 100 of file continuous_mission_orchestrator_node_configurator.cpp.
{
    DeclareParameter<bool>("/global/simulation");
    DeclareParameter<float>("/mission/continuous_mission_orchestrator/under_cable_target_distance");
    DeclareParameter<bool>("/mission/continuous_mission_orchestrator/use_charger_gripper_info");
    DeclareParameter<int>("/mission/continuous_mission_orchestrator/cable_landing_max_retries");
    DeclareParameter<float>("/mission/continuous_mission_orchestrator/battery_voltage_low_threshold");
    DeclareParameter<float>("/mission/continuous_mission_orchestrator/battery_voltage_high_threshold");
    DeclareParameter<float>("/mission/continuous_mission_orchestrator/charging_power_low_threshold");
    DeclareParameter<int>("/mission/continuous_mission_orchestrator/action_timeout_ms");
    DeclareParameter<int>("/mission/continuous_mission_orchestrator/charging_minimum_duration_s");
    DeclareParameter<int>("/mission/continuous_mission_orchestrator/charging_maximum_duration_s");
}
References iii_drone::configuration::Configurator::GetParameterTypeString().
Referenced by ContinuousMissionOrchestratorConfigurator(), and ContinuousMissionOrchestratorConfigurator().
simulation()
const bool ContinuousMissionOrchestratorConfigurator::simulation () const
Get the simulation flag.
Returns
Simulation flag
Definition at line 40 of file continuous_mission_orchestrator_node_configurator.cpp.
{
    return GetParameter("/global/simulation").as_bool();
}
References iii_drone::configuration::Configurator::GetParameter().
under_cable_target_distance()
const float ContinuousMissionOrchestratorConfigurator::under_cable_target_distance () const
Get the under cable target distance.
Returns
Under cable target distance
Definition at line 46 of file continuous_mission_orchestrator_node_configurator.cpp.
{
    return GetParameter("/mission/continuous_mission_orchestrator/under_cable_target_distance").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
use_charger_gripper_info()
const bool ContinuousMissionOrchestratorConfigurator::use_charger_gripper_info () const
Get the use charger gripper info flag.
Returns
Use charger gripper info flag
Definition at line 52 of file continuous_mission_orchestrator_node_configurator.cpp.
{
    return GetParameter("/mission/continuous_mission_orchestrator/use_charger_gripper_info").as_bool();
}
References iii_drone::configuration::Configurator::GetParameter().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/mission/continuous_mission_orchestrator_node/continuous_mission_orchestrator_node_configurator.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/mission/continuous_mission_orchestrator_node/continuous_mission_orchestrator_node_configurator.cpp