III-Drone: iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator Class Reference
iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator Class Reference
Class for handling parameters for PowerlineMapper.
#include <pl_mapper_node_configurator.hpp>
Public Member Functions
PowerlineMapperConfigurator (rclcpp::Node *node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Constructor.
PowerlineMapperConfigurator (rclcpp::Node *node, const rclcpp::QoS &qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Constructor.
float kf_r () const
Get the Powerline Kalman filter r coefficient.
float kf_q () const
Get the Powerline Kalman filter q coefficient.
int alive_cnt_low_thresh () const
Get the alive counter low threshold.
int alive_cnt_high_thresh () const
Get the alive counter high threshold.
int alive_cnt_ceiling () const
Get the alive counter ceiling.
float min_point_dist () const
Get the minimum distance between two points in the point cloud.
float max_point_dist () const
Get the maximum distance between two points in the point cloud.
float view_cone_slope () const
Get the slope of the view cone.
float strict_min_point_dist () const
Get the minimum distance between two points in the point cloud (strict)
float strict_max_point_dist () const
Get the maximum distance between two points in the point cloud (strict)
float strict_view_cone_slope () const
Get the slope of the view cone (strict)
float matching_line_max_dist () const
Get the maximum distance between two points in the point cloud (for line matching)
int init_sleep_time_ms () const
Get the initial sleep time in milliseconds.
int odometry_callback_period_ms () const
Get the odometry callback period in milliseconds.
int max_lines () const
Get the maximum number of lines.
int inter_pos_window_size () const
Get the inter line position window size.
bool simulation () const
Get simulation mode flag.
const std::string drone_frame_id () const
Get the drone frame ID.
const std::string world_frame_id () const
Get the world frame ID.
const std::string cable_gripper_frame_id () const
Get the cable gripper frame ID.
const std::string mmwave_frame_id () const
Get the mmWave frame ID.
std::shared_ptr< PowerlineParameters > powerline_parameters () const
PowerlineParameters getter.
Public Member Functions inherited from iii_drone::configuration::Configurator
Configurator (rclcpp::Node *node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Configurator (rclcpp::Node *node, const rclcpp::QoS &qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
~Configurator ()
template<typename T >
void DeclareParameter (const std::string &name)
rclcpp::Parameter GetParameter (const std::string &name) const
Get a parameter.
std::vector< rclcpp::Parameter > GetParameters (const std::vector< std::string > &names) const
Gets multiple parameters.
void SyncParameters (const std::vector< std::string > &names={})
Synchronizes parameters with the parameter server. Should never be necessary.
void PrintParameters () const
Prints all parameters to the console.
Private Member Functions
void declareNodeParameters ()
Declares the node specific parameters.
void initializeParameters ()
Initialize the parameters.
void plMapperOnParameterChange (const rclcpp::Parameter &parameter)
On changed parameter callback.
Private Attributes
std::function< void(const rclcpp::Parameter &) after_parameter_change_callback_)
On parameter change callback handle.
std::shared_ptr< PowerlineParameters > parameters_
The Powerline parameters.
Additional Inherited Members
Static Public Member Functions inherited from iii_drone::configuration::Configurator
template<typename T >
static std::string GetParameterTypeString ()
Static function for getting string representation of a parameter type from template type.
Protected Attributes inherited from iii_drone::configuration::Configurator
rclcpp::Node * node_
Detailed Description
Class for handling parameters for PowerlineMapper.
Definition at line 37 of file pl_mapper_node_configurator.hpp.
Constructor & Destructor Documentation
PowerlineMapperConfigurator() [1/2]
PowerlineMapperConfigurator::PowerlineMapperConfigurator (rclcpp::Node * node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback = nullptr)
Constructor.
Parameters
node Reference to the handling node
after_parameter_change_callback Callback function called after successful parameter change, default is nullptr
Definition at line 14 of file pl_mapper_node_configurator.cpp.
  : Configurator(
        node,
        std::bind(
            &PowerlineMapperConfigurator::plMapperOnParameterChange,
            this,
            std::placeholders::_1
        )
    ) {
    after_parameter_change_callback_ = after_parameter_change_callback;
    declareNodeParameters();
    initializeParameters();
}
References after_parameter_change_callback_, declareNodeParameters(), iii_drone::configuration::Configurator::GetParameterTypeString(), and initializeParameters().
PowerlineMapperConfigurator() [2/2]
PowerlineMapperConfigurator::PowerlineMapperConfigurator (rclcpp::Node * node, const rclcpp::QoS & qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback = nullptr)
Constructor.
Parameters
node Reference to the handling node
qos QoS profile for the parameter event subscription
after_parameter_change_callback Callback function called after successful parameter change, default is nullptr
Definition at line 34 of file pl_mapper_node_configurator.cpp.
  : Configurator(
        node,
        qos,
        std::bind(
            &PowerlineMapperConfigurator::plMapperOnParameterChange,
            this,
            std::placeholders::_1
        )
    ) {
    after_parameter_change_callback_ = after_parameter_change_callback;
    declareNodeParameters();
    initializeParameters();
}
References after_parameter_change_callback_, declareNodeParameters(), iii_drone::configuration::Configurator::GetParameterTypeString(), and initializeParameters().
Member Function Documentation
alive_cnt_ceiling()
int PowerlineMapperConfigurator::alive_cnt_ceiling () const
Get the alive counter ceiling.
Returns
Alive counter ceiling
Definition at line 80 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/perception/pl_mapper/alive_cnt_ceiling").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters().
alive_cnt_high_thresh()
int PowerlineMapperConfigurator::alive_cnt_high_thresh () const
Get the alive counter high threshold.
Returns
Alive counter high threshold
Definition at line 74 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/perception/pl_mapper/alive_cnt_high_thresh").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters().
alive_cnt_low_thresh()
int PowerlineMapperConfigurator::alive_cnt_low_thresh () const
Get the alive counter low threshold.
Returns
Alive counter low threshold
Definition at line 68 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/perception/pl_mapper/alive_cnt_low_thresh").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters().
cable_gripper_frame_id()
const std::string PowerlineMapperConfigurator::cable_gripper_frame_id () const
Get the cable gripper frame ID.
Returns
Cable gripper frame ID
Definition at line 170 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/tf/cable_gripper_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
declareNodeParameters()
void PowerlineMapperConfigurator::declareNodeParameters () private
Declares the node specific parameters.
Returns
void
Definition at line 188 of file pl_mapper_node_configurator.cpp.
{
    DeclareParameter<float>("/perception/pl_mapper/kf_r");
    DeclareParameter<float>("/perception/pl_mapper/kf_q");
    DeclareParameter<int>("/perception/pl_mapper/alive_cnt_low_thresh");
    DeclareParameter<int>("/perception/pl_mapper/alive_cnt_high_thresh");
    DeclareParameter<int>("/perception/pl_mapper/alive_cnt_ceiling");
    DeclareParameter<float>("/perception/pl_mapper/min_point_dist");
    DeclareParameter<float>("/perception/pl_mapper/max_point_dist");
    DeclareParameter<float>("/perception/pl_mapper/view_cone_slope");
    DeclareParameter<float>("/perception/pl_mapper/strict_min_point_dist");
    DeclareParameter<float>("/perception/pl_mapper/strict_max_point_dist");
    DeclareParameter<float>("/perception/pl_mapper/strict_view_cone_slope");
    DeclareParameter<float>("/perception/pl_mapper/matching_line_max_dist");
    DeclareParameter<int>("/perception/pl_mapper/init_sleep_time_ms");
    DeclareParameter<int>("/perception/pl_mapper/odometry_callback_period_ms");
    DeclareParameter<int>("/perception/pl_mapper/max_lines");
    DeclareParameter<int>("/perception/pl_mapper/inter_pos_window_size");
    DeclareParameter<bool>("/global/simulation");
    DeclareParameter<std::string>("/tf/drone_frame_id");
    DeclareParameter<std::string>("/tf/world_frame_id");
    DeclareParameter<std::string>("/tf/cable_gripper_frame_id");
    DeclareParameter<std::string>("/tf/mmwave_frame_id");
}
References Configurator::DeclareParameter< std::string >(), and iii_drone::configuration::Configurator::GetParameterTypeString().
Referenced by PowerlineMapperConfigurator(), and PowerlineMapperConfigurator().
drone_frame_id()
const std::string PowerlineMapperConfigurator::drone_frame_id () const
Get the drone frame ID.
Returns
Drone frame ID
Definition at line 158 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/tf/drone_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters(), iii_drone::perception::pl_mapper_node::PowerlineMapperNode::mmWaveCallback(), iii_drone::perception::pl_mapper_node::PowerlineMapperNode::odometryCallback(), iii_drone::perception::pl_mapper_node::PowerlineMapperNode::PowerlineMapperNode(), and iii_drone::perception::pl_mapper_node::PowerlineMapperNode::publishPoints().
init_sleep_time_ms()
int PowerlineMapperConfigurator::init_sleep_time_ms () const
Get the initial sleep time in milliseconds.
Returns
Initial sleep time in milliseconds
Definition at line 128 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/perception/pl_mapper/init_sleep_time_ms").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by iii_drone::perception::pl_mapper_node::PowerlineMapperNode::PowerlineMapperNode().
initializeParameters()
void PowerlineMapperConfigurator::initializeParameters () private
Initialize the parameters.
Definition at line 216 of file pl_mapper_node_configurator.cpp.
{
    parameters_ = std::make_shared<PowerlineParameters>(
        kf_r(),
        kf_q(),
        alive_cnt_low_thresh(),
        alive_cnt_high_thresh(),
        alive_cnt_ceiling(),
        matching_line_max_dist(),
        max_lines(),
        min_point_dist(),
        max_point_dist(),
        view_cone_slope(),
        strict_min_point_dist(),
        strict_max_point_dist(),
        strict_view_cone_slope(),
        inter_pos_window_size(),
        drone_frame_id(),
        mmwave_frame_id(),
        simulation()
    );
}
References alive_cnt_ceiling(), alive_cnt_high_thresh(), alive_cnt_low_thresh(), drone_frame_id(), inter_pos_window_size(), kf_q(), kf_r(), matching_line_max_dist(), max_lines(), max_point_dist(), min_point_dist(), mmwave_frame_id(), parameters_, simulation(), strict_max_point_dist(), strict_min_point_dist(), strict_view_cone_slope(), and view_cone_slope().
Referenced by PowerlineMapperConfigurator(), and PowerlineMapperConfigurator().
inter_pos_window_size()
int PowerlineMapperConfigurator::inter_pos_window_size () const
Get the inter line position window size.
Returns
Inter line position window size
Definition at line 146 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/perception/pl_mapper/inter_pos_window_size").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters().
kf_q()
float PowerlineMapperConfigurator::kf_q () const
Get the Powerline Kalman filter q coefficient.
Returns
Kalman filter q coefficient
Definition at line 62 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/perception/pl_mapper/kf_q").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters().
kf_r()
float PowerlineMapperConfigurator::kf_r () const
Get the Powerline Kalman filter r coefficient.
Returns
Kalman filter r coefficient
Definition at line 56 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/perception/pl_mapper/kf_r").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters().
matching_line_max_dist()
float PowerlineMapperConfigurator::matching_line_max_dist () const
Get the maximum distance between two points in the point cloud (for line matching)
Returns
Maximum distance between two points in the point cloud (for line matching)
Definition at line 122 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/perception/pl_mapper/matching_line_max_dist").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters().
max_lines()
int PowerlineMapperConfigurator::max_lines () const
Get the maximum number of lines.
Returns
Maximum number of lines
Definition at line 140 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/perception/pl_mapper/max_lines").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters().
max_point_dist()
float PowerlineMapperConfigurator::max_point_dist () const
Get the maximum distance between two points in the point cloud.
Returns
Maximum distance between two points in the point cloud
Definition at line 92 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/perception/pl_mapper/max_point_dist").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters().
min_point_dist()
float PowerlineMapperConfigurator::min_point_dist () const
Get the minimum distance between two points in the point cloud.
Returns
Minimum distance between two points in the point cloud
Definition at line 86 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/perception/pl_mapper/min_point_dist").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters().
mmwave_frame_id()
const std::string PowerlineMapperConfigurator::mmwave_frame_id () const
Get the mmWave frame ID.
Returns
mmWave frame ID
Definition at line 176 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/tf/mmwave_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters(), iii_drone::perception::pl_mapper_node::PowerlineMapperNode::mmWaveCallback(), and iii_drone::perception::pl_mapper_node::PowerlineMapperNode::PowerlineMapperNode().
odometry_callback_period_ms()
int PowerlineMapperConfigurator::odometry_callback_period_ms () const
Get the odometry callback period in milliseconds.
Returns
Odometry callback period in milliseconds
Definition at line 134 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/perception/pl_mapper/odometry_callback_period_ms").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by iii_drone::perception::pl_mapper_node::PowerlineMapperNode::PowerlineMapperNode().
plMapperOnParameterChange()
void PowerlineMapperConfigurator::plMapperOnParameterChange (const rclcpp::Parameter & parameter) private
On changed parameter callback.
Definition at line 240 of file pl_mapper_node_configurator.cpp.
{
    if (parameter.get_name() == "/perception/pl_mapper/kf_r") {
        parameters_->kf_r() = parameter.as_double();
    } else if (parameter.get_name() == "/perception/pl_mapper/kf_q") {
        parameters_->kf_q() = parameter.as_double();
    } else if (parameter.get_name() == "/perception/pl_mapper/alive_cnt_low_thresh") {
        parameters_->alive_cnt_low_thresh() = parameter.as_int();
    } else if (parameter.get_name() == "/perception/pl_mapper/alive_cnt_high_thresh") {
        parameters_->alive_cnt_high_thresh() = parameter.as_int();
    } else if (parameter.get_name() == "/perception/pl_mapper/alive_cnt_ceiling") {
        parameters_->alive_cnt_ceiling() = parameter.as_int();
    } else if (parameter.get_name() == "/perception/pl_mapper/matching_line_max_dist") {
        parameters_->matching_line_max_dist() = parameter.as_double();
    } else if (parameter.get_name() == "/perception/pl_mapper/max_lines") {
        parameters_->max_lines() = parameter.as_int();
    } else if (parameter.get_name() == "/perception/pl_mapper/min_point_dist") {
        parameters_->min_point_dist() = parameter.as_double();
    } else if (parameter.get_name() == "/perception/pl_mapper/max_point_dist") {
        parameters_->max_point_dist() = parameter.as_double();
    } else if (parameter.get_name() == "/perception/pl_mapper/view_cone_slope") {
        parameters_->view_cone_slope() = parameter.as_double();
    } else if (parameter.get_name() == "/perception/pl_mapper/strict_min_point_dist") {
        parameters_->strict_min_point_dist() = parameter.as_double();
    } else if (parameter.get_name() == "/perception/pl_mapper/strict_max_point_dist") {
        parameters_->strict_max_point_dist() = parameter.as_double();
    } else if (parameter.get_name() == "/perception/pl_mapper/strict_view_cone_slope") {
        parameters_->strict_view_cone_slope() = parameter.as_double();
    } else if (parameter.get_name() == "/perception/pl_mapper/inter_pos_window_size") {
        parameters_->inter_pos_window_size() = parameter.as_int();
    }
    if (after_parameter_change_callback_ != nullptr) {
        after_parameter_change_callback_(parameter);
    }
}
References after_parameter_change_callback_, iii_drone::configuration::Configurator::GetParameterTypeString(), and parameters_.
powerline_parameters()
std::shared_ptr< iii_drone::perception::PowerlineParameters > PowerlineMapperConfigurator::powerline_parameters () const
PowerlineParameters getter.
Definition at line 182 of file pl_mapper_node_configurator.cpp.
{
    return parameters_;
}
References parameters_.
Referenced by iii_drone::perception::pl_mapper_node::PowerlineMapperNode::mmWaveCallback().
simulation()
bool PowerlineMapperConfigurator::simulation () const
Get simulation mode flag.
Returns
Simulation mode flag
Definition at line 152 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/global/simulation").as_bool();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters().
strict_max_point_dist()
float PowerlineMapperConfigurator::strict_max_point_dist () const
Get the maximum distance between two points in the point cloud (strict)
Returns
Maximum distance between two points in the point cloud (strict)
Definition at line 110 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/perception/pl_mapper/strict_max_point_dist").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters().
strict_min_point_dist()
float PowerlineMapperConfigurator::strict_min_point_dist () const
Get the minimum distance between two points in the point cloud (strict)
Returns
Minimum distance between two points in the point cloud (strict)
Definition at line 104 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/perception/pl_mapper/strict_min_point_dist").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters().
strict_view_cone_slope()
float PowerlineMapperConfigurator::strict_view_cone_slope () const
Get the slope of the view cone (strict)
Returns
Slope of the view cone (strict)
Definition at line 116 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/perception/pl_mapper/strict_view_cone_slope").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters().
view_cone_slope()
float PowerlineMapperConfigurator::view_cone_slope () const
Get the slope of the view cone.
Returns
Slope of the view cone
Definition at line 98 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/perception/pl_mapper/view_cone_slope").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters().
world_frame_id()
const std::string PowerlineMapperConfigurator::world_frame_id () const
Get the world frame ID.
Returns
World frame ID
Definition at line 164 of file pl_mapper_node_configurator.cpp.
{
    return GetParameter("/tf/world_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by iii_drone::perception::pl_mapper_node::PowerlineMapperNode::odometryCallback().
Member Data Documentation
after_parameter_change_callback_
std::function<void(const rclcpp::Parameter &) iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::after_parameter_change_callback_) private
On parameter change callback handle.
Definition at line 237 of file pl_mapper_node_configurator.hpp.
Referenced by plMapperOnParameterChange(), PowerlineMapperConfigurator(), and PowerlineMapperConfigurator().
parameters_
std::shared_ptr<PowerlineParameters> iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::parameters_ private
The Powerline parameters.
Definition at line 242 of file pl_mapper_node_configurator.hpp.
Referenced by initializeParameters(), plMapperOnParameterChange(), and powerline_parameters().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/perception/pl_mapper_node/pl_mapper_node_configurator.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/perception/pl_mapper_node/pl_mapper_node_configurator.cpp