III-Drone: iii_drone::control::maneuver::Maneuver Class Reference
iii_drone::control::maneuver::Maneuver Class Reference
Abstract representation of a maneuver. Used to pass maneuvers around in the system. Contains a maneuver type, parameters, and goal handle. Created from a maneuver server.
#include <maneuver.hpp>
Public Member Functions
Maneuver ()
Default.
Maneuver (maneuver_type_t maneuver_type, const rclcpp_action::GoalUUID &uuid)
Constructor from type and id.
Maneuver (const Maneuver &rhs)
Copy constructor.
template<typename ActionT >
void SetFromGoal (const std::shared_ptr< const typename ActionT::Goal > goal)
Sets type and parameters from goal.
void Start ()
Triggers the maneuver to start by calling the underlying execute function on the goal handle.
void Terminate (bool success)
Indicate that the maneuver has terminated. Will delete the goal handle pointer.
bool operator== (const Maneuver &rhs) const
Equality operator.
bool operator!= (const Maneuver &rhs) const
Inequality operator.
Maneuver & operator= (const Maneuver &rhs)
Assignment operator.
const std::shared_ptr< void > goal_handle () const
Goal handle getter.
const rclcpp_action::GoalUUID uuid () const
UUID getter.
maneuver_type_t maneuver_type () const
Maneuver type getter.
const std::shared_ptr< void > maneuver_params () const
Maneuver parameters getter.
const rclcpp::Time creation_time () const
Creation time getter.
const rclcpp::Time start_time () const
Start time getter.
bool terminated () const
Getter for the termianted flag.
bool success () const
Getter for the success flag.
Static Public Member Functions
template<typename ActionT >
static Maneuver FromGoalHandle (const std::shared_ptr< rclcpp_action::ServerGoalHandle< ActionT > > goal_handle)
Static constructor from goal handle.
Private Attributes
rclcpp::Time creation_time_
The ROS2 time at which the maneuver was created.
rclcpp::Time start_time_
The ROS2 time at which the maneuver is started.
std::shared_ptr< void > goal_handle_
The ROS2 action server goal handle void pointer.
rclcpp_action::GoalUUID uuid_
The ROS2 goal UUID.
maneuver_type_t maneuver_type_
The maneuver type.
std::shared_ptr< void > maneuver_params_
The maneuver parameters void pointer.
bool terminated_ = false
Whether the maneuver has terminated.
bool success_ = true
Whether the maneuver was successful.
Detailed Description
Abstract representation of a maneuver. Used to pass maneuvers around in the system. Contains a maneuver type, parameters, and goal handle. Created from a maneuver server.
Definition at line 48 of file maneuver.hpp.
Constructor & Destructor Documentation
Maneuver() [1/3]
Maneuver::Maneuver ()
Default.
Definition at line 16 of file maneuver.cpp.
                   :
    goal_handle_(nullptr),
    maneuver_type_(MANEUVER_TYPE_NONE),
    maneuver_params_(nullptr) {
    creation_time_ = rclcpp::Clock().now();
    terminated_ = true;
    success_ = true;
}
References creation_time_, success_, and terminated_.
Maneuver() [2/3]
Maneuver::Maneuver (maneuver_type_t maneuver_type, const rclcpp_action::GoalUUID & uuid)
Constructor from type and id.
Parameters
maneuver_type Maneuver type
uuid ROS2 UUID.
Definition at line 27 of file maneuver.cpp.
  :
    goal_handle_(nullptr),
    uuid_(uuid),
    maneuver_type_(maneuver_type),
    maneuver_params_(nullptr) {
    creation_time_ = rclcpp::Clock().now();
}
References creation_time_.
Maneuver() [3/3]
Maneuver::Maneuver (const Maneuver & rhs)
Copy constructor.
Parameters
other Other maneuver
Definition at line 40 of file maneuver.cpp.
                                         :
    goal_handle_(other.goal_handle_),
    uuid_(other.uuid_),
    maneuver_type_(other.maneuver_type_),
    maneuver_params_(other.maneuver_params_) {
    creation_time_ = rclcpp::Clock().now();
}
References creation_time_.
Member Function Documentation
creation_time()
const rclcpp::Time Maneuver::creation_time () const
Creation time getter.
Returns
The creation time.
Definition at line 291 of file maneuver.cpp.
{
    return creation_time_;
}
References creation_time_.
Referenced by iii_drone::control::maneuver::ManeuverScheduler::progressScheduler(), and iii_drone::control::maneuver::ManeuverScheduler::UpdateManeuver().
FromGoalHandle()
template<typename ActionT > template Maneuver Maneuver::FromGoalHandle (const std::shared_ptr< rclcpp_action::ServerGoalHandle< ActionT > > goal_handle) static
Static constructor from goal handle.
Template Parameters
ActionT Action type
Parameters
goal_handle Goal handle
Definition at line 51 of file maneuver.cpp.
{
    Maneuver m;
    m.goal_handle_ = goal_handle;
    m.uuid_ = goal_handle->get_goal_id();
    m.SetFromGoal<ActionT>(goal_handle->get_goal());
    m.creation_time_ = rclcpp::Clock().now();
    return m;
}
References creation_time_, goal_handle(), goal_handle_, SetFromGoal(), and uuid_.
goal_handle()
const std::shared_ptr< void > Maneuver::goal_handle () const
Goal handle getter.
Returns
The goal handle.
Definition at line 275 of file maneuver.cpp.
{
    return goal_handle_;
}
References goal_handle_.
Referenced by FromGoalHandle(), iii_drone::control::maneuver::ManeuverScheduler::progressScheduler(), iii_drone::control::maneuver::FlyToObjectManeuverServer::publishFeedback(), iii_drone::control::maneuver::FlyToPositionManeuverServer::publishFeedback(), iii_drone::control::maneuver::FlyToObjectManeuverServer::publishResultAndFinalize(), iii_drone::control::maneuver::FlyToPositionManeuverServer::publishResultAndFinalize(), iii_drone::control::maneuver::HoverByObjectManeuverServer::publishResultAndFinalize(), iii_drone::control::maneuver::HoverManeuverServer::publishResultAndFinalize(), iii_drone::control::maneuver::HoverOnCableManeuverServer::publishResultAndFinalize(), and Start().
maneuver_params()
const std::shared_ptr< void > Maneuver::maneuver_params () const
Maneuver parameters getter.
Returns
The maneuver parameters.
Definition at line 287 of file maneuver.cpp.
{
    return maneuver_params_;
}
References maneuver_params_.
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::CanExecuteManeuver(), iii_drone::control::maneuver::FlyToPositionManeuverServer::CanExecuteManeuver(), iii_drone::control::maneuver::HoverByObjectManeuverServer::CanExecuteManeuver(), iii_drone::control::maneuver::HoverOnCableManeuverServer::CanExecuteManeuver(), iii_drone::control::maneuver::HoverOnCableManeuverServer::ExpectedAwarenessAfterExecution(), iii_drone::control::maneuver::FlyToObjectManeuverServer::ExpectedAwarenessAfterExecution(), iii_drone::control::maneuver::FlyToObjectManeuverServer::startExecution(), iii_drone::control::maneuver::FlyToPositionManeuverServer::startExecution(), iii_drone::control::maneuver::HoverByObjectManeuverServer::startExecution(), and iii_drone::control::maneuver::HoverOnCableManeuverServer::startExecution().
maneuver_type()
maneuver_type_t Maneuver::maneuver_type () const
Maneuver type getter.
Returns
The maneuver type.
Definition at line 283 of file maneuver.cpp.
{
    return maneuver_type_;
}
References maneuver_type_.
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::CanExecuteManeuver(), iii_drone::control::maneuver::FlyToPositionManeuverServer::CanExecuteManeuver(), iii_drone::control::maneuver::HoverByObjectManeuverServer::CanExecuteManeuver(), iii_drone::control::maneuver::HoverManeuverServer::CanExecuteManeuver(), iii_drone::control::maneuver::HoverOnCableManeuverServer::CanExecuteManeuver(), iii_drone::control::maneuver::ManeuverScheduler::maneuverCanExecute(), iii_drone::control::maneuver::ManeuverScheduler::progressScheduler(), and iii_drone::control::maneuver::ManeuverScheduler::ProjectExpectedAwarenessSingle().
operator!=()
bool Maneuver::operator!= (const Maneuver & rhs) const
Inequality operator.
Parameters
rhs Right-hand side
Definition at line 263 of file maneuver.cpp.
{
    return !(*this == rhs);
}
operator=()
Maneuver & Maneuver::operator= (const Maneuver & rhs)
Assignment operator.
Parameters
rhs Right-hand side
Definition at line 266 of file maneuver.cpp.
{
    goal_handle_ = rhs.goal_handle_;
    uuid_ = rhs.uuid_;
    maneuver_type_ = rhs.maneuver_type_;
    maneuver_params_ = rhs.maneuver_params_;
    return *this;
}
References goal_handle_, maneuver_params_, maneuver_type_, and uuid_.
operator==()
bool Maneuver::operator== (const Maneuver & rhs) const
Equality operator.
Parameters
rhs Right-hand side
Definition at line 258 of file maneuver.cpp.
{
    return uuid_ == rhs.uuid_ && maneuver_type_ == rhs.maneuver_type_;
}
References maneuver_type_, and uuid_.
SetFromGoal()
template<typename ActionT > void Maneuver::SetFromGoal (const std::shared_ptr< const typename ActionT::Goal > goal)
Sets type and parameters from goal.
Template Parameters
ActionT Action type
Parameters
goal Goal
Definition at line 64 of file maneuver.cpp.
{
    if constexpr (std::is_same<ActionT, iii_drone_interfaces::action::FlyToPosition>::value) {
        maneuver_type_ = MANEUVER_TYPE_FLY_TO_POSITION;
        maneuver_params_ = std::make_shared<fly_to_position_maneuver_params_t>();
        std::shared_ptr<fly_to_position_maneuver_params_t> p = std::static_pointer_cast<fly_to_position_maneuver_params_t>(maneuver_params_);
        if (p == nullptr) {
            std::string msg = "Maneuver::setFromGoal(): Failed to cast maneuver params to fly_to_position_maneuver_params_t";
            RCLCPP_FATAL(rclcpp::get_logger("rclcpp"),msg.c_str());
            throw std::runtime_error(msg);
        }
        *p = fly_to_position_maneuver_params_t(
            goal->frame_id,
            iii_drone::types::pointFromPointMsg(goal->target_position),
            goal->target_yaw
        );
    } else if constexpr (std::is_same<ActionT, iii_drone_interfaces::action::FlyToObject>::value) {
        maneuver_type_ = MANEUVER_TYPE_FLY_TO_OBJECT;
        maneuver_params_ = std::make_shared<fly_to_object_maneuver_params_t>();
        std::shared_ptr<fly_to_object_maneuver_params_t> p = std::static_pointer_cast<fly_to_object_maneuver_params_t>(maneuver_params_);
        if (p == nullptr) {
            std::string msg = "Maneuver::setFromGoal(): Failed to cast maneuver params to fly_to_object_maneuver_params_t";
            RCLCPP_FATAL(rclcpp::get_logger("rclcpp"),msg.c_str());
            throw std::runtime_error(msg);
        }
        *p = fly_to_object_maneuver_params_t(TargetAdapter(goal->target));
    } else if constexpr (std::is_same<ActionT, iii_drone_interfaces::action::CableLanding>::value) {
        maneuver_type_ = MANEUVER_TYPE_CABLE_LANDING;
        maneuver_params_ = nullptr;
    } else if constexpr (std::is_same<ActionT, iii_drone_interfaces::action::CableLanding>::value) {
        maneuver_type_ = MANEUVER_TYPE_CABLE_TAKEOFF;
        maneuver_params_ = std::make_shared<cable_takeoff_maneuver_params_t>();
        std::shared_ptr<cable_takeoff_maneuver_params_t> p = std::static_pointer_cast<cable_takeoff_maneuver_params_t>(maneuver_params_);
        if (p == nullptr) {
            std::string msg = "Maneuver::setFromGoal(): Failed to cast maneuver params to cable_takeoff_maneuver_params_t";
            RCLCPP_FATAL(rclcpp::get_logger("rclcpp"),msg.c_str());
            throw std::runtime_error(msg);
        }
        *p = cable_takeoff_maneuver_params_t(goal->target_cable_distance);
    } else if constexpr (std::is_same<ActionT, iii_drone_interfaces::action::Hover>::value) {
        maneuver_type_ = MANEUVER_TYPE_HOVER;
        maneuver_params_ = std::make_shared<hover_maneuver_params_t>();
        std::shared_ptr<hover_maneuver_params_t> p = std::static_pointer_cast<hover_maneuver_params_t>(maneuver_params_);
        if (p == nullptr) {
            std::string msg = "Maneuver::setFromGoal(): Failed to cast maneuver params to hover_maneuver_params_t";
            RCLCPP_FATAL(rclcpp::get_logger("rclcpp"),msg.c_str());
            throw std::runtime_error(msg);
        }
        *p = hover_maneuver_params_t(goal->duration_s);
    } else if constexpr (std::is_same<ActionT, iii_drone_interfaces::action::HoverByObject>::value) {
        maneuver_type_ = MANEUVER_TYPE_HOVER_BY_OBJECT;
        maneuver_params_ = std::make_shared<hover_by_object_maneuver_params_t>();
        std::shared_ptr<hover_by_object_maneuver_params_t> p = std::static_pointer_cast<hover_by_object_maneuver_params_t>(maneuver_params_);
        if (p == nullptr) {
            std::string msg = "Maneuver::setFromGoal(): Failed to cast maneuver params to hover_by_object_maneuver_params_t";
            RCLCPP_FATAL(rclcpp::get_logger("rclcpp"),msg.c_str());
            throw std::runtime_error(msg);
        }
        *p = hover_by_object_maneuver_params_t(
            TargetAdapter(goal->target),
            goal->duration_s
        );
    } else if constexpr (std::is_same<ActionT, iii_drone_interfaces::action::HoverOnCable>::value) {
        maneuver_type_ = MANEUVER_TYPE_HOVER_ON_CABLE;
        maneuver_params_ = std::make_shared<hover_on_cable_maneuver_params_t>();
        std::shared_ptr<hover_on_cable_maneuver_params_t> p = std::static_pointer_cast<hover_on_cable_maneuver_params_t>(maneuver_params_);
        if (p == nullptr) {
            std::string msg = "Maneuver::setFromGoal(): Failed to cast maneuver params to hover_on_cable_maneuver_params_t";
            RCLCPP_FATAL(rclcpp::get_logger("rclcpp"),msg.c_str());
            throw std::runtime_error(msg);
        }
        *p = hover_on_cable_maneuver_params_t(
            goal->target_z_velocity,
            goal->target_yaw_rate,
            goal->duration_s
        );
    // } else if constexpr (std::is_same<ActionT, iii_drone_interfaces::action::DisarmOnCable>::value) {
    //     maneuver_type_ = MANEUVER_TYPE_DISARM_ON_CABLE;
    //     maneuver_params_ = nullptr;
    // } else if constexpr (std::is_same<ActionT, iii_drone_interfaces::action::ArmOnCable>::value) {
    //     maneuver_type_ = MANEUVER_TYPE_ARM_ON_CABLE;
    //     maneuver_params_ = nullptr;
    // } else {
    //     maneuver_type_ = MANEUVER_TYPE_NONE;
    //     maneuver_params_ = nullptr;
    }
}
References maneuver_params_, maneuver_type_, iii_drone::control::maneuver::MANEUVER_TYPE_CABLE_LANDING, iii_drone::control::maneuver::MANEUVER_TYPE_CABLE_TAKEOFF, iii_drone::control::maneuver::MANEUVER_TYPE_FLY_TO_OBJECT, iii_drone::control::maneuver::MANEUVER_TYPE_FLY_TO_POSITION, iii_drone::control::maneuver::MANEUVER_TYPE_HOVER, iii_drone::control::maneuver::MANEUVER_TYPE_HOVER_BY_OBJECT, iii_drone::control::maneuver::MANEUVER_TYPE_HOVER_ON_CABLE, and iii_drone::types::pointFromPointMsg().
Referenced by FromGoalHandle(), and iii_drone::control::maneuver::ManeuverServer::handleGoal().
Start()
void Maneuver::Start ()
Triggers the maneuver to start by calling the underlying execute function on the goal handle.
Returns
void
Definition at line 192 of file maneuver.cpp.
                     {
    terminated_ = false;
    success_ = false;
    switch(maneuver_type_) {
        case MANEUVER_TYPE_FLY_TO_POSITION: {
            auto goal_handle = std::static_pointer_cast<rclcpp_action::ServerGoalHandle<iii_drone_interfaces::action::FlyToPosition>>(goal_handle_);
            if (!goal_handle->is_executing()) goal_handle->execute();
            break;
        }
        case MANEUVER_TYPE_FLY_TO_OBJECT: {
            auto goal_handle = std::static_pointer_cast<rclcpp_action::ServerGoalHandle<iii_drone_interfaces::action::FlyToObject>>(goal_handle_);
            if (!goal_handle->is_executing()) goal_handle->execute();
            break;
        }
        case MANEUVER_TYPE_CABLE_LANDING: {
            auto goal_handle = std::static_pointer_cast<rclcpp_action::ServerGoalHandle<iii_drone_interfaces::action::CableLanding>>(goal_handle_);
            if (!goal_handle->is_executing()) goal_handle->execute();
            break;
        }
        case MANEUVER_TYPE_CABLE_TAKEOFF: {
            auto goal_handle = std::static_pointer_cast<rclcpp_action::ServerGoalHandle<iii_drone_interfaces::action::CableTakeoff>>(goal_handle_);
            if (!goal_handle->is_executing()) goal_handle->execute();
            break;
        }
        case MANEUVER_TYPE_HOVER: {
            auto goal_handle = std::static_pointer_cast<rclcpp_action::ServerGoalHandle<iii_drone_interfaces::action::Hover>>(goal_handle_);
            if (!goal_handle->is_executing()) goal_handle->execute();
            break;
        }
        case MANEUVER_TYPE_HOVER_BY_OBJECT: {
            auto goal_handle = std::static_pointer_cast<rclcpp_action::ServerGoalHandle<iii_drone_interfaces::action::HoverByObject>>(goal_handle_);
            if (!goal_handle->is_executing()) goal_handle->execute();
            break;
        }
        case MANEUVER_TYPE_HOVER_ON_CABLE: {
            auto goal_handle = std::static_pointer_cast<rclcpp_action::ServerGoalHandle<iii_drone_interfaces::action::HoverOnCable>>(goal_handle_);
            if (!goal_handle->is_executing()) goal_handle->execute();
            break;
        }
        default:
            RCLCPP_ERROR(rclcpp::get_logger("rclcpp"),"Maneuver::Start(): Unknown maneuver type");
            break;
    }
    start_time_ = rclcpp::Clock().now();
}
References goal_handle(), goal_handle_, maneuver_type_, iii_drone::control::maneuver::MANEUVER_TYPE_CABLE_LANDING, iii_drone::control::maneuver::MANEUVER_TYPE_CABLE_TAKEOFF, iii_drone::control::maneuver::MANEUVER_TYPE_FLY_TO_OBJECT, iii_drone::control::maneuver::MANEUVER_TYPE_FLY_TO_POSITION, iii_drone::control::maneuver::MANEUVER_TYPE_HOVER, iii_drone::control::maneuver::MANEUVER_TYPE_HOVER_BY_OBJECT, iii_drone::control::maneuver::MANEUVER_TYPE_HOVER_ON_CABLE, start_time_, success_, and terminated_.
Referenced by iii_drone::control::maneuver::ManeuverScheduler::progressScheduler().
start_time()
const rclcpp::Time Maneuver::start_time () const
Start time getter.
Returns
The start time.
Definition at line 295 of file maneuver.cpp.
{
    return start_time_;
}
References start_time_.
Referenced by iii_drone::control::maneuver::ManeuverScheduler::progressScheduler().
success()
bool Maneuver::success () const
Getter for the success flag.
Returns
Whether the maneuver was successful.
Definition at line 303 of file maneuver.cpp.
{
    return success_;
}
References success_.
Referenced by iii_drone::control::maneuver::ManeuverScheduler::onReferenceCallbackTokenReacquired(), iii_drone::control::maneuver::ManeuverScheduler::progressScheduler(), and Terminate().
Terminate()
void Maneuver::Terminate (bool success)
Indicate that the maneuver has terminated. Will delete the goal handle pointer.
Parameters
success Whether the maneuver was successful.
Returns
void
Definition at line 250 of file maneuver.cpp.
{
    terminated_ = true;
    success_ = success;
    goal_handle_ = nullptr;
}
References goal_handle_, success(), success_, and terminated_.
Referenced by iii_drone::control::maneuver::ManeuverServer::asyncExecute(), and iii_drone::control::maneuver::ManeuverScheduler::UpdateManeuver().
terminated()
bool Maneuver::terminated () const
Getter for the termianted flag.
Returns
Whether the maneuver has terminated.
Definition at line 299 of file maneuver.cpp.
{
    return terminated_;
}
References terminated_.
Referenced by iii_drone::control::maneuver::ManeuverScheduler::CancelManeuver(), iii_drone::control::maneuver::ManeuverScheduler::onManeuverCompleted(), iii_drone::control::maneuver::ManeuverScheduler::onReferenceCallbackTokenReacquired(), and iii_drone::control::maneuver::ManeuverScheduler::progressScheduler().
uuid()
const rclcpp_action::GoalUUID Maneuver::uuid () const
UUID getter.
Returns
The UUID.
Definition at line 279 of file maneuver.cpp.
{
    return uuid_;
}
References uuid_.
Referenced by iii_drone::control::maneuver::ManeuverQueue::find(), iii_drone::control::maneuver::ManeuverScheduler::RegisterManeuverServer(), iii_drone::control::maneuver::ManeuverQueue::Update(), and iii_drone::control::maneuver::ManeuverScheduler::UpdateManeuver().
Member Data Documentation
creation_time_
rclcpp::Time iii_drone::control::maneuver::Maneuver::creation_time_ private
The ROS2 time at which the maneuver was created.
Definition at line 188 of file maneuver.hpp.
Referenced by creation_time(), FromGoalHandle(), Maneuver(), Maneuver(), and Maneuver().
goal_handle_
std::shared_ptr<void> iii_drone::control::maneuver::Maneuver::goal_handle_ private
The ROS2 action server goal handle void pointer.
Definition at line 198 of file maneuver.hpp.
Referenced by FromGoalHandle(), goal_handle(), operator=(), Start(), and Terminate().
maneuver_params_
std::shared_ptr<void> iii_drone::control::maneuver::Maneuver::maneuver_params_ private
The maneuver parameters void pointer.
Definition at line 213 of file maneuver.hpp.
Referenced by maneuver_params(), operator=(), and SetFromGoal().
maneuver_type_
maneuver_type_t iii_drone::control::maneuver::Maneuver::maneuver_type_ private
The maneuver type.
Definition at line 208 of file maneuver.hpp.
Referenced by maneuver_type(), operator=(), operator==(), SetFromGoal(), and Start().
start_time_
rclcpp::Time iii_drone::control::maneuver::Maneuver::start_time_ private
The ROS2 time at which the maneuver is started.
Definition at line 193 of file maneuver.hpp.
Referenced by Start(), and start_time().
success_
bool iii_drone::control::maneuver::Maneuver::success_ = true private
Whether the maneuver was successful.
Definition at line 223 of file maneuver.hpp.
Referenced by Maneuver(), Start(), success(), and Terminate().
terminated_
bool iii_drone::control::maneuver::Maneuver::terminated_ = false private
Whether the maneuver has terminated.
Definition at line 218 of file maneuver.hpp.
Referenced by Maneuver(), Start(), Terminate(), and terminated().
uuid_
rclcpp_action::GoalUUID iii_drone::control::maneuver::Maneuver::uuid_ private
The ROS2 goal UUID.
Definition at line 203 of file maneuver.hpp.
Referenced by FromGoalHandle(), operator=(), operator==(), and uuid().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/maneuver/maneuver.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/maneuver/maneuver.cpp