III-Drone: iii_drone::perception::hough_transformer_node::HoughTransformerConfigurator Class Reference
iii_drone::perception::hough_transformer_node::HoughTransformerConfigurator Class Reference
Class for handling parameters for HoughTransformer.
#include <hough_transformer_node_configurator.hpp>
Public Member Functions
HoughTransformerConfigurator (rclcpp::Node *node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Constructor.
HoughTransformerConfigurator (rclcpp::Node *node, const rclcpp::QoS &qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Constructor.
const std::string drone_frame_id () const
Get the drone frame ID.
const std::string world_frame_id () const
Get the world frame ID.
const std::string cable_gripper_frame_id () const
Get the cable gripper frame ID.
const std::string mmwave_frame_id () const
Get the mmWave frame ID.
int canny_low_threshold () const
Get the Canny low threshold.
int canny_ratio () const
Get the Canny ratio.
int canny_kernel_size () const
Get the Canny kernel size.
int n_lines_include () const
Get the number of lines to include.
std::shared_ptr< HoughTransformerParameters > hough_transformer_parameters () const
HoughTransformerParameters getter.
Public Member Functions inherited from iii_drone::configuration::Configurator
Configurator (rclcpp::Node *node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Configurator (rclcpp::Node *node, const rclcpp::QoS &qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
~Configurator ()
template<typename T >
void DeclareParameter (const std::string &name)
rclcpp::Parameter GetParameter (const std::string &name) const
Get a parameter.
std::vector< rclcpp::Parameter > GetParameters (const std::vector< std::string > &names) const
Gets multiple parameters.
void SyncParameters (const std::vector< std::string > &names={})
Synchronizes parameters with the parameter server. Should never be necessary.
void PrintParameters () const
Prints all parameters to the console.
Private Member Functions
void declareNodeParameters ()
Declares the node specific parameters.
void initHoughTransformerParameters ()
Initialises the HoughTransformer parameters.
void houghTransformerConfiguratorParameterChangeCallback (const rclcpp::Parameter &parameter)
the HoughTransformerConfiguration callback function called after successful parameter change
Private Attributes
std::shared_ptr< HoughTransformerParameters > hough_transformer_parameters_
The HoughTransformer parameters.
std::function< void(const rclcpp::Parameter &) after_parameter_change_callback_) = nullptr
The callback function called after successful parameter change.
Additional Inherited Members
Static Public Member Functions inherited from iii_drone::configuration::Configurator
template<typename T >
static std::string GetParameterTypeString ()
Static function for getting string representation of a parameter type from template type.
Protected Attributes inherited from iii_drone::configuration::Configurator
rclcpp::Node * node_
Detailed Description
Class for handling parameters for HoughTransformer.
Definition at line 36 of file hough_transformer_node_configurator.hpp.
Constructor & Destructor Documentation
HoughTransformerConfigurator() [1/2]
HoughTransformerConfigurator::HoughTransformerConfigurator (rclcpp::Node * node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback = nullptr)
Constructor.
Parameters
node Reference to the handling node
after_parameter_change_callback Callback function called after successful parameter change, default is nullptr
Definition at line 16 of file hough_transformer_node_configurator.cpp.
  : Configurator(
        node,
        std::bind(
            &HoughTransformerConfigurator::houghTransformerConfiguratorParameterChangeCallback,
            this,
            std::placeholders::_1
        )
    ) {
    after_parameter_change_callback_ = after_parameter_change_callback;
    declareNodeParameters();
    initHoughTransformerParameters();
}
References after_parameter_change_callback_, declareNodeParameters(), iii_drone::configuration::Configurator::GetParameterTypeString(), and initHoughTransformerParameters().
HoughTransformerConfigurator() [2/2]
HoughTransformerConfigurator::HoughTransformerConfigurator (rclcpp::Node * node, const rclcpp::QoS & qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback = nullptr)
Constructor.
Parameters
node Reference to the handling node
qos QoS profile for the parameter event subscription
after_parameter_change_callback Callback function called after successful parameter change, default is nullptr
Definition at line 36 of file hough_transformer_node_configurator.cpp.
  : Configurator(
        node,
        qos,
        std::bind(
            &HoughTransformerConfigurator::houghTransformerConfiguratorParameterChangeCallback,
            this,
            std::placeholders::_1
        )
    ) {
    after_parameter_change_callback_ = after_parameter_change_callback;
    declareNodeParameters();
    initHoughTransformerParameters();
}
References after_parameter_change_callback_, declareNodeParameters(), iii_drone::configuration::Configurator::GetParameterTypeString(), and initHoughTransformerParameters().
Member Function Documentation
cable_gripper_frame_id()
const std::string HoughTransformerConfigurator::cable_gripper_frame_id () const
Get the cable gripper frame ID.
Returns
Cable gripper frame ID
Definition at line 93 of file hough_transformer_node_configurator.cpp.
{
    return GetParameter("/tf/cable_gripper_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
canny_kernel_size()
int HoughTransformerConfigurator::canny_kernel_size () const
Get the Canny kernel size.
Returns
Canny kernel size
Definition at line 69 of file hough_transformer_node_configurator.cpp.
{
    return GetParameter("/perception/hough_transformer/canny_kernel_size").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initHoughTransformerParameters().
canny_low_threshold()
int HoughTransformerConfigurator::canny_low_threshold () const
Get the Canny low threshold.
Returns
Canny low threshold
Definition at line 57 of file hough_transformer_node_configurator.cpp.
{
    return GetParameter("/perception/hough_transformer/canny_low_threshold").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initHoughTransformerParameters().
canny_ratio()
int HoughTransformerConfigurator::canny_ratio () const
Get the Canny ratio.
Returns
Canny ratio
Definition at line 63 of file hough_transformer_node_configurator.cpp.
{
    return GetParameter("/perception/hough_transformer/canny_ratio").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initHoughTransformerParameters().
declareNodeParameters()
void HoughTransformerConfigurator::declareNodeParameters () private
Declares the node specific parameters.
Returns
void
Definition at line 111 of file hough_transformer_node_configurator.cpp.
{
    DeclareParameter<std::string>("/tf/drone_frame_id");
    DeclareParameter<std::string>("/tf/world_frame_id");
    DeclareParameter<std::string>("/tf/cable_gripper_frame_id");
    DeclareParameter<std::string>("/tf/mmwave_frame_id");
    DeclareParameter<int>("/perception/hough_transformer/canny_low_threshold");
    DeclareParameter<int>("/perception/hough_transformer/canny_ratio");
    DeclareParameter<int>("/perception/hough_transformer/canny_kernel_size");
    DeclareParameter<int>("/perception/hough_transformer/n_lines_include");
}
References Configurator::DeclareParameter< std::string >(), and iii_drone::configuration::Configurator::GetParameterTypeString().
Referenced by HoughTransformerConfigurator(), and HoughTransformerConfigurator().
drone_frame_id()
const std::string HoughTransformerConfigurator::drone_frame_id () const
Get the drone frame ID.
Returns
Drone frame ID
Definition at line 81 of file hough_transformer_node_configurator.cpp.
{
    return GetParameter("/tf/drone_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
hough_transformer_parameters()
std::shared_ptr< iii_drone::perception::HoughTransformerParameters > HoughTransformerConfigurator::hough_transformer_parameters () const
HoughTransformerParameters getter.
Returns
HoughTransformerParameters
Definition at line 105 of file hough_transformer_node_configurator.cpp.
{
    return hough_transformer_parameters_;
}
References hough_transformer_parameters_.
houghTransformerConfiguratorParameterChangeCallback()
void HoughTransformerConfigurator::houghTransformerConfiguratorParameterChangeCallback (const rclcpp::Parameter & parameter) private
the HoughTransformerConfiguration callback function called after successful parameter change
Parameters
parameter The parameter that was changed
Returns
void
Definition at line 135 of file hough_transformer_node_configurator.cpp.
{
    if (parameter.get_name() == "/perception/hough_transformer/canny_low_threshold") {
        hough_transformer_parameters_->canny_low_threshold() = parameter.as_int();
    } else if (parameter.get_name() == "/perception/hough_transformer/canny_ratio") {
        hough_transformer_parameters_->canny_ratio() = parameter.as_int();
    } else if (parameter.get_name() == "/perception/hough_transformer/canny_kernel_size") {
        hough_transformer_parameters_->canny_kernel_size() = parameter.as_int();
    }
    // If after_parameter_change_callback_ is not null, call it
    if (after_parameter_change_callback_) {
        after_parameter_change_callback_(parameter);
    }
}
References after_parameter_change_callback_, iii_drone::configuration::Configurator::GetParameterTypeString(), and hough_transformer_parameters_.
initHoughTransformerParameters()
void HoughTransformerConfigurator::initHoughTransformerParameters () private
Initialises the HoughTransformer parameters.
Returns
void
Definition at line 125 of file hough_transformer_node_configurator.cpp.
{
    hough_transformer_parameters_ = std::make_shared<iii_drone::perception::HoughTransformerParameters>(
        canny_low_threshold(),
        canny_ratio(),
        canny_kernel_size()
    );
}
References canny_kernel_size(), canny_low_threshold(), canny_ratio(), and hough_transformer_parameters_.
Referenced by HoughTransformerConfigurator(), and HoughTransformerConfigurator().
mmwave_frame_id()
const std::string HoughTransformerConfigurator::mmwave_frame_id () const
Get the mmWave frame ID.
Returns
mmWave frame ID
Definition at line 99 of file hough_transformer_node_configurator.cpp.
{
    return GetParameter("/tf/mmwave_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
n_lines_include()
int HoughTransformerConfigurator::n_lines_include () const
Get the number of lines to include.
Returns
Number of lines to include
Definition at line 75 of file hough_transformer_node_configurator.cpp.
{
    return GetParameter("/perception/hough_transformer/n_lines_include").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
world_frame_id()
const std::string HoughTransformerConfigurator::world_frame_id () const
Get the world frame ID.
Returns
World frame ID
Definition at line 87 of file hough_transformer_node_configurator.cpp.
{
    return GetParameter("/tf/world_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
Member Data Documentation
after_parameter_change_callback_
std::function<void(const rclcpp::Parameter &) iii_drone::perception::hough_transformer_node::HoughTransformerConfigurator::after_parameter_change_callback_) = nullptr private
The callback function called after successful parameter change.
Definition at line 149 of file hough_transformer_node_configurator.hpp.
Referenced by HoughTransformerConfigurator(), HoughTransformerConfigurator(), and houghTransformerConfiguratorParameterChangeCallback().
hough_transformer_parameters_
std::shared_ptr<HoughTransformerParameters> iii_drone::perception::hough_transformer_node::HoughTransformerConfigurator::hough_transformer_parameters_ private
The HoughTransformer parameters.
Definition at line 144 of file hough_transformer_node_configurator.hpp.
Referenced by hough_transformer_parameters(), houghTransformerConfiguratorParameterChangeCallback(), and initHoughTransformerParameters().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/perception/hough_transformer_node/hough_transformer_node_configurator.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/perception/hough_transformer_node/hough_transformer_node_configurator.cpp