III-Drone: iii_drone::adapters::ReferenceAdapter Class Reference
iii_drone::adapters::ReferenceAdapter Class Reference
Class for adapting the III-Drone-Core::Reference to the III-Drone-Interfaces::Reference.
#include <reference_adapter.hpp>
Public Member Functions
ReferenceAdapter ()
Default constructor.
ReferenceAdapter (const iii_drone::control::Reference &reference)
Constructor from III-Drone-Core::Reference.
ReferenceAdapter (const iii_drone_interfaces::msg::Reference &reference)
Constructor from III-Drone-Interfaces::Reference msg.
ReferenceAdapter (const iii_drone_interfaces::msg::Reference::SharedPtr &reference)
Constructor from III-Drone-Interfaces::Reference msg shared pointer.
iii_drone_interfaces::msg::Reference ToMsg () const
Converts to msg.
geometry_msgs::msg::PoseStamped ToPoseStampedMsg (std::string frame_id) const
Converts to pose stamped msg.
iii_drone::control::Reference reference () const
Reference getter.
Private Attributes
iii_drone::control::Reference reference_
Detailed Description
Class for adapting the III-Drone-Core::Reference to the III-Drone-Interfaces::Reference.
Definition at line 38 of file reference_adapter.hpp.
Constructor & Destructor Documentation
ReferenceAdapter() [1/4]
ReferenceAdapter::ReferenceAdapter ()
Default constructor.
Definition at line 15 of file reference_adapter.cpp.
: reference_(iii_drone::control::Reference()) {}
ReferenceAdapter() [2/4]
ReferenceAdapter::ReferenceAdapter (const iii_drone::control::Reference & reference)
Constructor from III-Drone-Core::Reference.
Parameters
reference The III-Drone-Core::Reference.
Definition at line 17 of file reference_adapter.cpp.
: reference_(reference) {}
ReferenceAdapter() [3/4]
ReferenceAdapter::ReferenceAdapter (const iii_drone_interfaces::msg::Reference & reference)
Constructor from III-Drone-Interfaces::Reference msg.
Parameters
reference The III-Drone-Interfaces::Reference msg.
Definition at line 19 of file reference_adapter.cpp.
{
    point_t position = pointFromPointMsg(msg.position);
    double yaw = msg.yaw;
    vector_t velocity = vectorFromVectorMsg(msg.velocity);
    double yaw_rate = msg.yaw_rate;
    vector_t acceleration = vectorFromVectorMsg(msg.acceleration);
    double yaw_acceleration = msg.yaw_acceleration;
    reference_ = iii_drone::control::Reference(
        position,
        yaw,
        velocity,
        yaw_rate,
        acceleration,
        yaw_acceleration,
        msg.stamp
    );
}
References iii_drone::types::pointFromPointMsg(), reference_, and iii_drone::types::vectorFromVectorMsg().
ReferenceAdapter() [4/4]
iii_drone::adapters::ReferenceAdapter::ReferenceAdapter (const iii_drone_interfaces::msg::Reference::SharedPtr & reference)
Constructor from III-Drone-Interfaces::Reference msg shared pointer.
Parameters
reference The III-Drone-Interfaces::Reference msg shared pointer.
Member Function Documentation
reference()
iii_drone::control::Reference ReferenceAdapter::reference () const
Reference getter.
Returns
The III-Drone-Core::Reference.
Definition at line 75 of file reference_adapter.cpp.
{
    return reference_;
}
References reference_.
Referenced by iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNode::computeReferenceTrajectoryCallback(), iii_drone::adapters::ReferenceTrajectoryAdapter::ReferenceTrajectoryAdapter(), iii_drone::adapters::ReferenceTrajectoryAdapter::ReferenceTrajectoryAdapter(), and iii_drone::adapters::px4::TrajectorySetpointAdapter::TrajectorySetpointAdapter().
ToMsg()
iii_drone_interfaces::msg::Reference ReferenceAdapter::ToMsg () const
Converts to msg.
Returns
The III-Drone-Interfaces::Reference msg.
Definition at line 42 of file reference_adapter.cpp.
{
    iii_drone_interfaces::msg::Reference msg;
    msg.position = pointMsgFromPoint(reference_.position());
    msg.yaw = reference_.yaw();
    msg.velocity = vectorMsgFromVector(reference_.velocity());
    msg.yaw_rate = reference_.yaw_rate();
    msg.acceleration = vectorMsgFromVector(reference_.acceleration());
    msg.yaw_acceleration = reference_.yaw_acceleration();
    msg.stamp = reference_.stamp();
    return msg;
}
References iii_drone::control::Reference::acceleration(), iii_drone::types::pointMsgFromPoint(), iii_drone::control::Reference::position(), reference_, iii_drone::control::Reference::stamp(), iii_drone::types::vectorMsgFromVector(), iii_drone::control::Reference::velocity(), iii_drone::control::Reference::yaw(), iii_drone::control::Reference::yaw_acceleration(), and iii_drone::control::Reference::yaw_rate().
Referenced by iii_drone::control::TrajectoryGeneratorClient::ComputeReferenceTrajectoryAsync(), and iii_drone::adapters::ReferenceTrajectoryAdapter::ToMsg().
ToPoseStampedMsg()
geometry_msgs::msg::PoseStamped ReferenceAdapter::ToPoseStampedMsg (std::string frame_id) const
Converts to pose stamped msg.
Parameters
frame_id The frame id.
Returns
The geometry_msgs::msg::PoseStamped msg.
Definition at line 59 of file reference_adapter.cpp.
{
    geometry_msgs::msg::PoseStamped msg;
    msg.pose.position = pointMsgFromPoint(reference_.position());
    msg.pose.orientation = quaternionMsgFromQuaternion(
        eulToQuat(
            euler_angles_t(0.0, 0.0, reference_.yaw())
        )
    );
    msg.header.stamp = reference_.stamp();
    msg.header.frame_id = frame_id;
    return msg;
}
References iii_drone::math::eulToQuat(), iii_drone::types::pointMsgFromPoint(), iii_drone::control::Reference::position(), iii_drone::types::quaternionMsgFromQuaternion(), reference_, iii_drone::control::Reference::stamp(), and iii_drone::control::Reference::yaw().
Referenced by iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNode::publishPlannedTrajectory(), and iii_drone::adapters::ReferenceTrajectoryAdapter::ToPathMsg().
Member Data Documentation
reference_
iii_drone::control::Reference iii_drone::adapters::ReferenceAdapter::reference_ private
Definition at line 90 of file reference_adapter.hpp.
Referenced by reference(), ReferenceAdapter(), ToMsg(), and ToPoseStampedMsg().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/adapters/reference_adapter.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/adapters/reference_adapter.cpp