III-Drone: iii_drone::adapters::PointCloudAdapter Class Reference
iii_drone::adapters::PointCloudAdapter Class Reference
Adapter class for PointCloud2 messages.
#include <point_cloud_adapter.hpp>
Public Member Functions
PointCloudAdapter ()
Default constructor.
PointCloudAdapter (const rclcpp::Time &stamp, const std::string &frame_id, const std::vector< iii_drone::types::point_t > &points)
Constructor.
PointCloudAdapter (const sensor_msgs::msg::PointCloud2::SharedPtr msg)
Constructor from ROS2 message.
const sensor_msgs::msg::PointCloud2 ToMsg () const
Convert to ROS2 message.
const rclcpp::Time & stamp () const
Timestamp getter.
const std::string & frame_id () const
Frame ID getter.
const std::vector< iii_drone::types::point_t > & points () const
Point cloud data getter.
Private Member Functions
const std::vector< iii_drone::types::point_t > readPoints (const sensor_msgs::msg::PointCloud2 msg) const
Reads points from a ROS2 message.
Private Attributes
rclcpp::Time stamp_
Timestamp of the message.
std::string frame_id_
Frame ID of the message.
std::vector< iii_drone::types::point_t > points_
Point cloud data.
Detailed Description
Adapter class for PointCloud2 messages.
Definition at line 34 of file point_cloud_adapter.hpp.
Constructor & Destructor Documentation
PointCloudAdapter() [1/3]
PointCloudAdapter::PointCloudAdapter ()
Default constructor.
Definition at line 14 of file point_cloud_adapter.cpp.
{
    stamp_ = rclcpp::Clock().now();
    frame_id_ = "";
    points_ = std::vector<iii_drone::types::point_t>();
}
References frame_id_, points_, and stamp_.
PointCloudAdapter() [2/3]
PointCloudAdapter::PointCloudAdapter (const rclcpp::Time & stamp, const std::string & frame_id, const std::vector< iii_drone::types::point_t > & points)
Constructor.
Parameters
stamp Timestamp of the message.
frame_id Frame ID of the message.
points Point cloud data.
Definition at line 24 of file point_cloud_adapter.cpp.
  {
    stamp_ = stamp;
    frame_id_ = frame_id;
    points_ = points;
}
References frame_id(), frame_id_, points(), points_, stamp(), and stamp_.
PointCloudAdapter() [3/3]
PointCloudAdapter::PointCloudAdapter (const sensor_msgs::msg::PointCloud2::SharedPtr msg)
Constructor from ROS2 message.
Parameters
msg ROS2 message.
Definition at line 38 of file point_cloud_adapter.cpp.
{
    stamp_ = msg->header.stamp;
    frame_id_ = msg->header.frame_id;
    points_ = readPoints(*msg);
}
References frame_id_, points_, readPoints(), and stamp_.
Member Function Documentation
frame_id()
const std::string & PointCloudAdapter::frame_id () const
Frame ID getter.
Definition at line 109 of file point_cloud_adapter.cpp.
{
    return frame_id_;
}
References frame_id_.
Referenced by PointCloudAdapter().
points()
const std::vector< iii_drone::types::point_t > & PointCloudAdapter::points () const
Point cloud data getter.
Definition at line 115 of file point_cloud_adapter.cpp.
{
    return points_;
}
References points_.
Referenced by iii_drone::perception::pl_mapper_node::PowerlineMapperNode::mmWaveCallback(), PointCloudAdapter(), and readPoints().
readPoints()
const std::vector< iii_drone::types::point_t > PointCloudAdapter::readPoints (const sensor_msgs::msg::PointCloud2 msg) const private
Reads points from a ROS2 message.
Parameters
msg ROS2 message.
Definition at line 121 of file point_cloud_adapter.cpp.
{
    std::vector<iii_drone::types::point_t> points;
    unsigned int pcl_size = msg.width;
    const uint8_t *ptr = msg.data.data();
    uint32_t point_step = msg.point_step;
    for (size_t i = 0; i < pcl_size; i++) {
        point_t point(
            *(float *)(ptr + msg.fields[0].offset),
            *(float *)(ptr + msg.fields[1].offset),
            *(float *)(ptr + msg.fields[2].offset)
        );
        ptr += point_step;
        points.push_back(point);
    }
    return points;
}
References points().
Referenced by PointCloudAdapter().
stamp()
const rclcpp::Time & PointCloudAdapter::stamp () const
Timestamp getter.
Definition at line 103 of file point_cloud_adapter.cpp.
{
    return stamp_;
}
References stamp_.
Referenced by PointCloudAdapter().
ToMsg()
const sensor_msgs::msg::PointCloud2 PointCloudAdapter::ToMsg () const
Convert to ROS2 message.
Returns
ROS2 message.
Definition at line 48 of file point_cloud_adapter.cpp.
{
    sensor_msgs::msg::PointCloud2 msg{};
    msg.header.stamp = stamp_;
    msg.header.frame_id = frame_id_;
    msg.height = 1;
    msg.width = points_.size();
    msg.point_step = 3*sizeof(float);
    msg.is_bigendian = false;
    msg.is_dense = false;
    msg.fields.resize(3);
    msg.fields[0].name = "x";
    msg.fields[0].offset = 0;
    msg.fields[0].datatype = sensor_msgs::msg::PointField::FLOAT32;
    msg.fields[0].count = 1;
    msg.fields[1].name = "y";
    msg.fields[1].offset = sizeof(float);
    msg.fields[1].datatype = sensor_msgs::msg::PointField::FLOAT32;
    msg.fields[1].count = 1;
    msg.fields[2].name = "z";
    msg.fields[2].offset = 2*sizeof(float);
    msg.fields[2].datatype = sensor_msgs::msg::PointField::FLOAT32;
    msg.fields[2].count = 1;
    msg.data.resize(points_.size() * msg.point_step);
    for (size_t i = 0; i < points_.size(); i++) {
        memcpy(
            &msg.data[i * msg.point_step + msg.fields[0].offset],
            &points_[i](0),
            sizeof(float)
        );
        memcpy(
            &msg.data[i * msg.point_step + msg.fields[1].offset],
            &points_[i](1),
            sizeof(float)
        );
        memcpy(
            &msg.data[i * msg.point_step + msg.fields[2].offset],
            &points_[i](2),
            sizeof(float)
        );
    }
    msg.row_step = msg.data.size();
    return msg;
}
References frame_id_, points_, and stamp_.
Referenced by iii_drone::perception::pl_mapper_node::PowerlineMapperNode::publishPoints(), and iii_drone::perception::pl_mapper_node::PowerlineMapperNode::publishPowerline().
Member Data Documentation
frame_id_
std::string iii_drone::adapters::PointCloudAdapter::frame_id_ private
Frame ID of the message.
Definition at line 92 of file point_cloud_adapter.hpp.
Referenced by frame_id(), PointCloudAdapter(), PointCloudAdapter(), PointCloudAdapter(), and ToMsg().
points_
std::vector<iii_drone::types::point_t> iii_drone::adapters::PointCloudAdapter::points_ private
Point cloud data.
Definition at line 97 of file point_cloud_adapter.hpp.
Referenced by PointCloudAdapter(), PointCloudAdapter(), PointCloudAdapter(), points(), and ToMsg().
stamp_
rclcpp::Time iii_drone::adapters::PointCloudAdapter::stamp_ private
Timestamp of the message.
Definition at line 87 of file point_cloud_adapter.hpp.
Referenced by PointCloudAdapter(), PointCloudAdapter(), PointCloudAdapter(), stamp(), and ToMsg().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/adapters/point_cloud_adapter.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/adapters/point_cloud_adapter.cpp