III-Drone: iii_drone::control::CombinedDroneAwarenessHandler Class Reference
iii_drone::control::CombinedDroneAwarenessHandler Class Reference
Class which subscribes to various topics related to the drone awareness and keeps track of the current combined awareness. Does the following:
#include <combined_drone_awareness_handler.hpp>
Public Types
typedef std::shared_ptr< CombinedDroneAwarenessHandler > SharedPtr
Shared pointer type for the CombinedDroneAwarenessHandler.
Public Member Functions
CombinedDroneAwarenessHandler (CombinedDroneAwarenessHandlerParameters::SharedPtr params, tf2_ros::Buffer::SharedPtr tf_buffer, rclcpp::Node *node)
Construct a new CombinedDroneAwarenessHandler object, initializing all the subscriptions.
void RegisterOffboardMode (int navigation_state_id)
Register a new navigation state id which should be considered offboard.
iii_drone::control::State GetState () const
Get the current drone state.
iii_drone::types::transform_matrix_t ComputeTargetTransform (const iii_drone::adapters::TargetAdapter &target_adapter) const
Computes a target transform given a target adapter.
void SetTarget (const iii_drone::adapters::TargetAdapter &target_adapter)
Sets the current target.
void ClearTarget ()
Clears the current target.
const combined_drone_awareness_t combined_drone_awareness () const
Getter for the combined drone awareness simple type by copy.
bool armed () const
Whether the drone is armed.
bool offboard () const
Whether the drone is in offboard mode.
bool has_target () const
Whether the drone has a target.
bool target_position_known () const
Whether the position of the target is known.
iii_drone::adapters::TargetAdapter target_adapter () const
Returns the current target adapter, will have TARGET_TYPE_NONE if no target.
bool on_ground () const
Whether the drone is on the ground.
bool on_cable () const
Whether the drone is on a cable.
bool in_flight () const
Whether the drone is in flight.
int on_cable_id () const
Return the id of the cable that the drone is on if it is on a cable, -1 otherwise. This id can be different from the target cable id.
double ground_altitude_estimate () const
Returns the ground altitude estimate.
drone_location_t drone_location (int &on_cable_id) const
Returns the drone location, checks the drone location and returns the on_cable_id if the drone is on a cable.
drone_location_t drone_location () const
Returns the drone location.
tf2_ros::Buffer::SharedPtr tf_buffer () const
Returns the tf buffer shared ptr.
Private Types
using VehicleStatusAdapterHistory = iii_drone::utils::History<iii_drone::adapters::px4::VehicleStatusAdapter>
using VehicleOdometryAdapterHistory = iii_drone::utils::History<iii_drone::adapters::px4::VehicleOdometryAdapter>
using PowerlineAdapterHistory = iii_drone::utils::History<iii_drone::adapters::PowerlineAdapter>
using GripperStatusAdapterHistory = iii_drone::utils::History<iii_drone::adapters::GripperStatusAdapter>
using AtomicIntVector = iii_drone::utils::Atomic<std::vector<int>>
Private Member Functions
void updateCombinedDroneAwareness ()
Updates the combined drone awareness based on current information. To be called after updating the any internal awareness information.
void updateCombinedDroneAwarenessFromVehicleStatus ()
Updates the combined drone awareness from the vehicle status. Triggers updates of armed, offboard, and location.
void updateCombinedDroneAwarenessFromVehicleStatus (combined_drone_awareness_t &combined_drone_awareness)
Updates the given combined drone awareness from the vehicle status. Triggers updates of armed, offboard, and location.
void updateCombinedDroneAwarenessFromVehicleOdometry ()
Updates the combined drone awareness from the vehicle odometry. Triggers updates of ground altitude estimate and location.
void updateCombinedDroneAwarenessFromVehicleOdometry (combined_drone_awareness_t &combined_drone_awareness)
Updates the given combined drone awareness from the vehicle odometry. Triggers updates of ground altitude estimate and location.
void updateCombinedDroneAwarenessFromPowerline ()
Updates the combined drone awareness from the powerline. Triggers updates of target_cable_position_known and location.
void updateCombinedDroneAwarenessFromPowerline (combined_drone_awareness_t &combined_drone_awareness)
Updates the given combined drone awareness from the powerline. Triggers updates of target_cable_position_known and location.
void updateCombinedDroneAwarenessFromGripperStatus ()
Updates the combined drone awareness from the gripper status. Triggers updates of gripper_open.
void updateCombinedDroneAwarenessFromGripperStatus (combined_drone_awareness_t &combined_drone_awareness)
Updates the given combined drone awareness from the gripper status. Triggers updates of gripper_open.
void updateCombinedDroneAwarenessFromTarget ()
Updates the combined drone awareness from the target adapter. Triggers updates of target_adapter, target_position_known, and has_target.
void updateCombinedDroneAwarenessFromTarget (combined_drone_awareness_t &combined_drone_awareness)
Updates the given combined drone awareness from the target adapter. Triggers updates of target_adapter, target_position_known, and has_target.
void updateGroundAltitudeEstimate (bool armed, bool offboard, bool has_target_cable)
Updates the ground altitude estimate based on given information. Will either start or stop the timer based on whether the drone is on the ground. If the drone is on the ground, and the timer is not running (has elapsed), will start the timer and update the ground altitude estimate. If the drone is on the ground, and the timer is running, will do nothing. If the drone is not on the ground, and the timer is running, will stop the timer. To be called after updates to vehicle odometry, vehicle status, or target cable. Will set the ground altitude estimate to the current altitude if the drone is on the ground, based on the following criteria:
void updateDroneLocation (combined_drone_awareness_t &awareness)
Updates the drone location of a combined drone awareness object based on current awareness information. Additionally updates the on_cable_id member by evaluating whether the drone is currently on a cable. on_cable_id will be set to -1 if the drone is not on a cable. on_cable_id can be different from target_cable_id.
void publishMembers ()
Publishes the members.
Private Attributes
CombinedDroneAwarenessHandlerParameters::SharedPtr params_
Parameters for the combined drone awareness handler.
tf2_ros::Buffer::SharedPtr tf_buffer_
The tf2 buffer.
std::unique_ptr< tf2_ros::TransformBroadcaster > tf_broadcaster_
The tf2 broadcaster fro publishing ground frame.
rclcpp::Node * node_
Simple pointer to the containing node.
iii_drone::utils::Atomic< combined_drone_awareness_t >::SharedPtr combined_drone_awareness_
Atomic combined drone awareness simple type member.
AtomicIntVector offboard_nav_state_ids_
Atomic vector of navigation state ids which are considered to be offboard.
rclcpp::Subscription< px4_msgs::msg::VehicleStatus >::SharedPtr vehicle_status_sub_
PX4 vehicle status subscription.
VehicleStatusAdapterHistory::SharedPtr vehicle_status_adapter_history_
Vehicle status adapter history.
rclcpp::Subscription< px4_msgs::msg::VehicleOdometry >::SharedPtr vehicle_odometry_sub_
PX4 odometry subscription.
VehicleOdometryAdapterHistory::SharedPtr vehicle_odometry_adapter_history_
Vehicle odometry adapter history.
rclcpp::Subscription< iii_drone_interfaces::msg::Powerline >::SharedPtr powerline_sub_
Powerline subscription.
PowerlineAdapterHistory::SharedPtr powerline_adapter_history_
Powerline adapter history.
rclcpp::Subscription< iii_drone_interfaces::msg::GripperStatus >::SharedPtr gripper_status_sub_
Gripper status subscription.
GripperStatusAdapterHistory::SharedPtr gripper_status_adapter_history_
Gripper status adapter history.
iii_drone::utils::Atomic< iii_drone::adapters::TargetAdapter >::SharedPtr target_adapter_
Atomic target adapter member.
rclcpp::Publisher< iii_drone_interfaces::msg::Target >::SharedPtr target_pub_
Target publisher.
iii_drone::utils::Atomic< double >::SharedPtr ground_altitude_estimate_
Atomic ground altitude estimate member.
iii_drone::utils::History< double > ground_altitudes_history_
Ground altitudes history.
rclcpp::TimerBase::SharedPtr ground_altitude_update_timer_
Timer for updating the ground altitude estimate.
rclcpp::TimerBase::SharedPtr publish_timer_
Timer for publishing members.
Detailed Description
Class which subscribes to various topics related to the drone awareness and keeps track of the current combined awareness. Does the following:
Subscribes to the PX4 vehicle status and odometry topics, the powerline topic, the gripper status topic, and the target cable id topic.
Keeps track of the history of the received messages.
Updates the combined drone awareness based on the received messages.
Keeps and updates an estimate of the ground altitude and publishes the ground frame to tf2. To be used from a ROS2 node. Construction of this object will create subscriptions and is not thread-safe.
Definition at line 130 of file combined_drone_awareness_handler.hpp.
Member Typedef Documentation
AtomicIntVector
using iii_drone::control::CombinedDroneAwarenessHandler::AtomicIntVector = iii_drone::utils::Atomic<std::vector<int>> private
Definition at line 136 of file combined_drone_awareness_handler.hpp.
GripperStatusAdapterHistory
using iii_drone::control::CombinedDroneAwarenessHandler::GripperStatusAdapterHistory = iii_drone::utils::History<iii_drone::adapters::GripperStatusAdapter> private
Definition at line 134 of file combined_drone_awareness_handler.hpp.
PowerlineAdapterHistory
using iii_drone::control::CombinedDroneAwarenessHandler::PowerlineAdapterHistory = iii_drone::utils::History<iii_drone::adapters::PowerlineAdapter> private
Definition at line 133 of file combined_drone_awareness_handler.hpp.
SharedPtr
typedef std::shared_ptr<CombinedDroneAwarenessHandler> iii_drone::control::CombinedDroneAwarenessHandler::SharedPtr
Shared pointer type for the CombinedDroneAwarenessHandler.
Definition at line 298 of file combined_drone_awareness_handler.hpp.
VehicleOdometryAdapterHistory
using iii_drone::control::CombinedDroneAwarenessHandler::VehicleOdometryAdapterHistory = iii_drone::utils::History<iii_drone::adapters::px4::VehicleOdometryAdapter> private
Definition at line 132 of file combined_drone_awareness_handler.hpp.
VehicleStatusAdapterHistory
using iii_drone::control::CombinedDroneAwarenessHandler::VehicleStatusAdapterHistory = iii_drone::utils::History<iii_drone::adapters::px4::VehicleStatusAdapter> private
Definition at line 131 of file combined_drone_awareness_handler.hpp.
Constructor & Destructor Documentation
CombinedDroneAwarenessHandler()
CombinedDroneAwarenessHandler::CombinedDroneAwarenessHandler (CombinedDroneAwarenessHandlerParameters::SharedPtr params, tf2_ros::Buffer::SharedPtr tf_buffer, rclcpp::Node * node)
Construct a new CombinedDroneAwarenessHandler object, initializing all the subscriptions.
Parameters
params Shared pointer to the parameters for the combined drone awareness handler object.
tf_buffer Shared pointer to the tf2 buffer.
node Simple pointer to the containing node.
Definition at line 22 of file combined_drone_awareness_handler.cpp.
  : params_(params),
    tf_buffer_(tf_buffer),
    node_(node) {
    tf_broadcaster_ = std::make_unique<tf2_ros::TransformBroadcaster>(*node_);
    vehicle_status_adapter_history_ = std::make_shared<VehicleStatusAdapterHistory>(1);
    vehicle_odometry_adapter_history_ = std::make_shared<VehicleOdometryAdapterHistory>(2);
    powerline_adapter_history_ = std::make_shared<PowerlineAdapterHistory>(1);
    gripper_status_adapter_history_ = std::make_shared<GripperStatusAdapterHistory>(1);
    ground_altitude_estimate_ = std::make_shared<iii_drone::utils::Atomic<double>>(0.0);
    target_adapter_ = std::make_shared<iii_drone::utils::Atomic<TargetAdapter>>();
    offboard_nav_state_ids_->push_back(iii_drone::adapters::px4::NAVIGATION_STATE_OFFBOARD);
    int ground_estimate_window_size = params_->ground_estimate_window_size();
    ground_altitudes_history_ = History<double>(0, ground_estimate_window_size);
    ground_altitude_update_timer_ = node_->create_wall_timer(
        std::chrono::milliseconds(params_->ground_estimate_update_period_ms()),
        [this]() {
            ground_altitude_update_timer_->cancel();
        }
    );
    ground_altitude_update_timer_->cancel();
    updateCombinedDroneAwareness();
    vehicle_status_sub_ = node_->create_subscription<px4_msgs::msg::VehicleStatus>(
        "/fmu/out/vehicle_status",
        10,
        [this](const px4_msgs::msg::VehicleStatus::SharedPtr msg) {
            iii_drone::adapters::px4::VehicleStatusAdapter adapter(*msg);
            vehicle_status_adapter_history_->Store(adapter);
            updateCombinedDroneAwarenessFromVehicleStatus();
        }
    );
    vehicle_odometry_sub_ = node_->create_subscription<px4_msgs::msg::VehicleOdometry>(
        "/fmu/out/vehicle_odometry",
        10,
        [this](const px4_msgs::msg::VehicleOdometry::SharedPtr msg) {
            iii_drone::adapters::px4::VehicleOdometryAdapter adapter(*msg);
            vehicle_odometry_adapter_history_->Store(adapter);
            updateCombinedDroneAwarenessFromVehicleOdometry();
        }
    );
    powerline_sub_ = node_->create_subscription<iii_drone_interfaces::msg::Powerline>(
        "/perception/pl_mapper/powerline",
        10,
        [this](const iii_drone_interfaces::msg::Powerline::SharedPtr msg) {
            iii_drone::adapters::PowerlineAdapter adapter(*msg);
            powerline_adapter_history_->Store(adapter);
            updateCombinedDroneAwarenessFromPowerline();
        }
    );
    gripper_status_sub_ = node_->create_subscription<iii_drone_interfaces::msg::GripperStatus>(
        "/gripper/status",
        10,
        [this](const iii_drone_interfaces::msg::GripperStatus::SharedPtr msg) {
            iii_drone::adapters::GripperStatusAdapter adapter(*msg);
            gripper_status_adapter_history_->Store(adapter);
            updateCombinedDroneAwarenessFromGripperStatus();
        }
    );
    target_pub_ = node_->create_publisher<iii_drone_interfaces::msg::Target>(
        "target",
        10
    );
    publish_timer_ = node_->create_wall_timer(
        std::chrono::milliseconds(100),
        std::bind(
            &CombinedDroneAwarenessHandler::publishMembers,
            this
        )
    );
}
References gripper_status_adapter_history_, gripper_status_sub_, ground_altitude_estimate_, ground_altitude_update_timer_, ground_altitudes_history_, iii_drone::control::CombinedDroneAwarenessHandlerParameters::ground_estimate_update_period_ms(), iii_drone::control::CombinedDroneAwarenessHandlerParameters::ground_estimate_window_size(), iii_drone::adapters::px4::NAVIGATION_STATE_OFFBOARD, node_, offboard_nav_state_ids_, params_, powerline_adapter_history_, powerline_sub_, publish_timer_, publishMembers(), target_adapter_, target_pub_, tf_broadcaster_, updateCombinedDroneAwareness(), updateCombinedDroneAwarenessFromGripperStatus(), updateCombinedDroneAwarenessFromPowerline(), updateCombinedDroneAwarenessFromVehicleOdometry(), updateCombinedDroneAwarenessFromVehicleStatus(), vehicle_odometry_adapter_history_, vehicle_odometry_sub_, vehicle_status_adapter_history_, and vehicle_status_sub_.
Member Function Documentation
armed()
bool CombinedDroneAwarenessHandler::armed () const
Whether the drone is armed.
Returns
true if the drone is armed.
Definition at line 210 of file combined_drone_awareness_handler.cpp.
{
    return ((combined_drone_awareness_t)*combined_drone_awareness_).armed;
}
References combined_drone_awareness_.
Referenced by updateGroundAltitudeEstimate().
ClearTarget()
void CombinedDroneAwarenessHandler::ClearTarget ()
Clears the current target.
Returns
void
Definition at line 198 of file combined_drone_awareness_handler.cpp.
{
    target_adapter_->Store(TargetAdapter());
    updateCombinedDroneAwarenessFromTarget();
}
References target_adapter_, and updateCombinedDroneAwarenessFromTarget().
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::publishResultAndFinalize(), iii_drone::control::maneuver::HoverByObjectManeuverServer::publishResultAndFinalize(), iii_drone::control::maneuver::HoverOnCableManeuverServer::publishResultAndFinalize(), and iii_drone::control::maneuver::HoverManeuverServer::startExecution().
combined_drone_awareness()
const combined_drone_awareness_t CombinedDroneAwarenessHandler::combined_drone_awareness () const
Getter for the combined drone awareness simple type by copy.
Returns
The combined drone awareness member.
Definition at line 206 of file combined_drone_awareness_handler.cpp.
{
    return *combined_drone_awareness_;
}
References combined_drone_awareness_.
Referenced by iii_drone::control::maneuver::ManeuverScheduler::CanExecute(), iii_drone::control::maneuver::ManeuverScheduler::ProjectExpectedAwarenessFull(), updateCombinedDroneAwareness(), updateCombinedDroneAwarenessFromGripperStatus(), updateCombinedDroneAwarenessFromGripperStatus(), updateCombinedDroneAwarenessFromPowerline(), updateCombinedDroneAwarenessFromPowerline(), updateCombinedDroneAwarenessFromTarget(), updateCombinedDroneAwarenessFromTarget(), updateCombinedDroneAwarenessFromVehicleOdometry(), updateCombinedDroneAwarenessFromVehicleOdometry(), updateCombinedDroneAwarenessFromVehicleStatus(), updateCombinedDroneAwarenessFromVehicleStatus(), and updateDroneLocation().
ComputeTargetTransform()
iii_drone::types::transform_matrix_t CombinedDroneAwarenessHandler::ComputeTargetTransform (const iii_drone::adapters::TargetAdapter & target_adapter) const
Computes a target transform given a target adapter.
Parameters
target_adapter The target adapter.
Returns
The target transform.
Definition at line 131 of file combined_drone_awareness_handler.cpp.
{
    iii_drone::control::Reference reference;
    if (target_adapter.target_type() == iii_drone::adapters::TARGET_TYPE_CABLE) {
        iii_drone::adapters::PowerlineAdapter powerline_adapter = (*powerline_adapter_history_)[0];
        iii_drone::adapters::SingleLineAdapter target_line;
        try {
            target_line = powerline_adapter.GetLine(target_adapter.target_id());
        } catch (std::runtime_error & e) {
            throw std::runtime_error("CombinedDroneAwarenessHandler::ComputeTargetReference: target line with id " + std::to_string(target_adapter.target_id()) + " not found");
        }
        geometry_msgs::msg::PoseStamped target_object_pose_stamped = target_line.ToPoseStampedMsg();
        geometry_msgs::msg::PoseStamped target_object_pose_stamped_world;
        try {
            target_object_pose_stamped_world = tf_buffer_->transform(
                target_object_pose_stamped,
                params_->world_frame_id()
            );
        } catch (tf2::TransformException & e) {
            throw std::runtime_error("CombinedDroneAwarenessHandler::ComputeTargetReference: could not transform target object pose to world frame: " + std::string(e.what()));
        }
        iii_drone::types::transform_matrix_t d_T_c = target_adapter.target_transform();
        iii_drone::types::pose_t w_T_c_pose = poseFromPoseMsg(target_object_pose_stamped_world.pose);
        iii_drone::types::transform_matrix_t w_T_c = createTransformMatrix(
            w_T_c_pose.position,
            w_T_c_pose.orientation
        );
        iii_drone::types::transform_matrix_t w_T_d = w_T_c * d_T_c.inverse();
        return w_T_d;
    } else {
        throw std::runtime_error("CombinedDroneAwarenessHandler::ComputeTargetReference: target type not implemented");
    }
}
References iii_drone::math::createTransformMatrix(), iii_drone::adapters::PowerlineAdapter::GetLine(), iii_drone::types::pose_t::orientation, params_, iii_drone::types::poseFromPoseMsg(), iii_drone::types::pose_t::position, target_adapter(), iii_drone::adapters::TargetAdapter::target_id(), iii_drone::adapters::TargetAdapter::target_transform(), iii_drone::adapters::TargetAdapter::target_type(), iii_drone::adapters::TARGET_TYPE_CABLE, tf_buffer_, iii_drone::adapters::SingleLineAdapter::ToPoseStampedMsg(), and iii_drone::control::CombinedDroneAwarenessHandlerParameters::world_frame_id().
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::CanExecuteManeuver(), iii_drone::control::maneuver::HoverByObjectManeuverServer::CanExecuteManeuver(), iii_drone::control::maneuver::HoverByObjectManeuverServer::GetReference(), iii_drone::control::maneuver::HoverByObjectManeuverServer::hasSucceeded(), and iii_drone::control::maneuver::HoverByObjectManeuverServer::Update().
drone_location() [1/2]
drone_location_t CombinedDroneAwarenessHandler::drone_location () const
Returns the drone location.
Returns
The drone location.
Definition at line 255 of file combined_drone_awareness_handler.cpp.
{
    return ((combined_drone_awareness_t)*combined_drone_awareness_).drone_location;
}
References combined_drone_awareness_.
Referenced by drone_location().
drone_location() [2/2]
drone_location_t CombinedDroneAwarenessHandler::drone_location (int & on_cable_id) const
Returns the drone location, checks the drone location and returns the on_cable_id if the drone is on a cable.
Parameters
on_cable_id The id of the cable that the drone is on if it is on a cable, -1 otherwise.
Returns
The drone location.
Definition at line 250 of file combined_drone_awareness_handler.cpp.
{
    on_cable_id = ((combined_drone_awareness_t)*combined_drone_awareness_).on_cable_id;
    return ((combined_drone_awareness_t)*combined_drone_awareness_).drone_location;
}
References combined_drone_awareness_, drone_location(), and on_cable_id().
GetState()
iii_drone::control::State CombinedDroneAwarenessHandler::GetState () const
Get the current drone state.
Returns
The current drone state.
Definition at line 121 of file combined_drone_awareness_handler.cpp.
{
    if (vehicle_status_adapter_history_->empty()) {
        return iii_drone::control::State();
    }
    return (*vehicle_odometry_adapter_history_)[0].ToState();
}
References vehicle_odometry_adapter_history_, and vehicle_status_adapter_history_.
Referenced by iii_drone::control::maneuver::ManeuverScheduler::fetchNextReferenceAndPublish(), iii_drone::control::maneuver::FlyToObjectManeuverServer::publishFeedback(), and updateCombinedDroneAwarenessFromVehicleOdometry().
ground_altitude_estimate()
double CombinedDroneAwarenessHandler::ground_altitude_estimate () const
Returns the ground altitude estimate.
Returns
The ground altitude estimate.
Definition at line 246 of file combined_drone_awareness_handler.cpp.
{
    return ((combined_drone_awareness_t)*combined_drone_awareness_).ground_altitude_estimate;
}
References combined_drone_awareness_.
Referenced by updateGroundAltitudeEstimate().
has_target()
bool CombinedDroneAwarenessHandler::has_target () const
Whether the drone has a target.
Returns
true if the drone has a target.
Definition at line 218 of file combined_drone_awareness_handler.cpp.
{
    return ((combined_drone_awareness_t)*combined_drone_awareness_).has_target();
}
References combined_drone_awareness_.
in_flight()
bool CombinedDroneAwarenessHandler::in_flight () const
Whether the drone is in flight.
Returns
true if the drone is in flight.
Definition at line 238 of file combined_drone_awareness_handler.cpp.
{
    return ((combined_drone_awareness_t)*combined_drone_awareness_).in_flight();
}
References combined_drone_awareness_.
offboard()
bool CombinedDroneAwarenessHandler::offboard () const
Whether the drone is in offboard mode.
Returns
true if the drone is in offboard mode.
Definition at line 214 of file combined_drone_awareness_handler.cpp.
{
    return ((combined_drone_awareness_t)*combined_drone_awareness_).offboard;
}
References combined_drone_awareness_.
Referenced by updateGroundAltitudeEstimate().
on_cable()
bool CombinedDroneAwarenessHandler::on_cable () const
Whether the drone is on a cable.
Returns
true if the drone is on a cable.
Definition at line 234 of file combined_drone_awareness_handler.cpp.
{
    return ((combined_drone_awareness_t)*combined_drone_awareness_).on_cable();
}
References combined_drone_awareness_.
on_cable_id()
int CombinedDroneAwarenessHandler::on_cable_id () const
Return the id of the cable that the drone is on if it is on a cable, -1 otherwise. This id can be different from the target cable id.
Returns
The id of the cable that the drone is on if it is on a cable, -1 otherwise.
Definition at line 242 of file combined_drone_awareness_handler.cpp.
{
    return ((combined_drone_awareness_t)*combined_drone_awareness_).on_cable_id;
}
References combined_drone_awareness_.
Referenced by drone_location().
on_ground()
bool CombinedDroneAwarenessHandler::on_ground () const
Whether the drone is on the ground.
Returns
true if the drone is on the ground.
Definition at line 230 of file combined_drone_awareness_handler.cpp.
{
    return ((combined_drone_awareness_t)*combined_drone_awareness_).on_ground();
}
References combined_drone_awareness_.
publishMembers()
void CombinedDroneAwarenessHandler::publishMembers () private
Publishes the members.
Returns
void
Definition at line 539 of file combined_drone_awareness_handler.cpp.
{
    iii_drone::adapters::TargetAdapter target_adapter = target_adapter_->Load();
    if (target_adapter.target_type() == iii_drone::adapters::TARGET_TYPE_NONE) {
        return;
    }
    iii_drone_interfaces::msg::Target target_msg = target_adapter.ToMsg();
    target_pub_->publish(target_msg);
}
References target_adapter(), target_adapter_, target_pub_, iii_drone::adapters::TargetAdapter::target_type(), iii_drone::adapters::TARGET_TYPE_NONE, and iii_drone::adapters::TargetAdapter::ToMsg().
Referenced by CombinedDroneAwarenessHandler().
RegisterOffboardMode()
void CombinedDroneAwarenessHandler::RegisterOffboardMode (int navigation_state_id)
Register a new navigation state id which should be considered offboard.
Parameters
navigation_state_id The navigation state id to be considered offboard.
Returns
void
Definition at line 110 of file combined_drone_awareness_handler.cpp.
{
    std::vector<int> offboard_states = offboard_nav_state_ids_.Load();
    if (std::find(offboard_states.begin(), offboard_states.end(), navigation_state_id) == offboard_states.end()) {
        offboard_states.push_back(navigation_state_id);
        offboard_nav_state_ids_.Store(offboard_states);
    }
}
References iii_drone::utils::Atomic< T >::Load(), offboard_nav_state_ids_, and iii_drone::utils::Atomic< T >::Store().
Referenced by iii_drone::control::maneuver_controller_node::ManeuverControllerNode::ManeuverControllerNode().
SetTarget()
void CombinedDroneAwarenessHandler::SetTarget (const iii_drone::adapters::TargetAdapter & target_adapter)
Sets the current target.
Parameters
target_adapter The target adapter.
Returns
void
Definition at line 184 of file combined_drone_awareness_handler.cpp.
{
    if (target_adapter.target_type() != iii_drone::adapters::TARGET_TYPE_CABLE) {
        throw std::runtime_error("CombinedDroneAwarenessHandler::SetTarget: target type not implemented");
    }
    target_adapter_->Store(target_adapter);
    updateCombinedDroneAwarenessFromTarget();
}
References target_adapter(), target_adapter_, iii_drone::adapters::TargetAdapter::target_type(), iii_drone::adapters::TARGET_TYPE_CABLE, and updateCombinedDroneAwarenessFromTarget().
target_adapter()
TargetAdapter CombinedDroneAwarenessHandler::target_adapter () const
Returns the current target adapter, will have TARGET_TYPE_NONE if no target.
Returns
The current target adapter.
Definition at line 226 of file combined_drone_awareness_handler.cpp.
{
    return ((combined_drone_awareness_t)*combined_drone_awareness_).target_adapter;
}
References combined_drone_awareness_.
Referenced by ComputeTargetTransform(), publishMembers(), and SetTarget().
target_position_known()
bool CombinedDroneAwarenessHandler::target_position_known () const
Whether the position of the target is known.
Returns
true if the position of the target is known.
Definition at line 222 of file combined_drone_awareness_handler.cpp.
{
    return ((combined_drone_awareness_t)*combined_drone_awareness_).target_position_known;
}
References combined_drone_awareness_.
tf_buffer()
tf2_ros::Buffer::SharedPtr CombinedDroneAwarenessHandler::tf_buffer () const
Returns the tf buffer shared ptr.
Returns
The tf buffer shared ptr.
Definition at line 259 of file combined_drone_awareness_handler.cpp.
{
    return tf_buffer_;
}
References tf_buffer_.
updateCombinedDroneAwareness()
void CombinedDroneAwarenessHandler::updateCombinedDroneAwareness () private
Updates the combined drone awareness based on current information. To be called after updating the any internal awareness information.
Returns
void
Definition at line 263 of file combined_drone_awareness_handler.cpp.
{
    // Update the combined drone awareness
    combined_drone_awareness_t combined_drone_awareness = *combined_drone_awareness_;
    updateCombinedDroneAwarenessFromVehicleStatus(combined_drone_awareness);
    updateCombinedDroneAwarenessFromVehicleOdometry(combined_drone_awareness);
    updateCombinedDroneAwarenessFromPowerline(combined_drone_awareness);
    updateCombinedDroneAwarenessFromGripperStatus(combined_drone_awareness);
    updateCombinedDroneAwarenessFromTarget(combined_drone_awareness);
    // Update the combined drone awareness
    *combined_drone_awareness_ = combined_drone_awareness;
}
References combined_drone_awareness(), combined_drone_awareness_, updateCombinedDroneAwarenessFromGripperStatus(), updateCombinedDroneAwarenessFromPowerline(), updateCombinedDroneAwarenessFromTarget(), updateCombinedDroneAwarenessFromVehicleOdometry(), and updateCombinedDroneAwarenessFromVehicleStatus().
Referenced by CombinedDroneAwarenessHandler().
updateCombinedDroneAwarenessFromGripperStatus() [1/2]
void CombinedDroneAwarenessHandler::updateCombinedDroneAwarenessFromGripperStatus () private
Updates the combined drone awareness from the gripper status. Triggers updates of gripper_open.
Returns
void
Definition at line 365 of file combined_drone_awareness_handler.cpp.
{
    combined_drone_awareness_t combined_drone_awareness = *combined_drone_awareness_;
    updateCombinedDroneAwarenessFromGripperStatus(combined_drone_awareness);
    *combined_drone_awareness_ = combined_drone_awareness;
}
References combined_drone_awareness(), combined_drone_awareness_, and updateCombinedDroneAwarenessFromGripperStatus().
Referenced by CombinedDroneAwarenessHandler(), updateCombinedDroneAwareness(), and updateCombinedDroneAwarenessFromGripperStatus().
updateCombinedDroneAwarenessFromGripperStatus() [2/2]
void CombinedDroneAwarenessHandler::updateCombinedDroneAwarenessFromGripperStatus (combined_drone_awareness_t & combined_drone_awareness) private
Updates the given combined drone awareness from the gripper status. Triggers updates of gripper_open.
Parameters
combined_drone_awareness The combined drone awareness to update.
Returns
void
Definition at line 375 of file combined_drone_awareness_handler.cpp.
{
    // Update the gripper open flag
    if (gripper_status_adapter_history_->empty()) {
        combined_drone_awareness.gripper_open = true;
    } else {
        combined_drone_awareness.gripper_open = (*gripper_status_adapter_history_)[0].open();
    }
}
References combined_drone_awareness(), iii_drone::control::combined_drone_awareness_t::gripper_open, and gripper_status_adapter_history_.
updateCombinedDroneAwarenessFromPowerline() [1/2]
void CombinedDroneAwarenessHandler::updateCombinedDroneAwarenessFromPowerline () private
Updates the combined drone awareness from the powerline. Triggers updates of target_cable_position_known and location.
Returns
void
Definition at line 340 of file combined_drone_awareness_handler.cpp.
{
    combined_drone_awareness_t combined_drone_awareness = *combined_drone_awareness_;
    updateCombinedDroneAwarenessFromPowerline(combined_drone_awareness);
    *combined_drone_awareness_ = combined_drone_awareness;
}
References combined_drone_awareness(), combined_drone_awareness_, and updateCombinedDroneAwarenessFromPowerline().
Referenced by CombinedDroneAwarenessHandler(), updateCombinedDroneAwareness(), and updateCombinedDroneAwarenessFromPowerline().
updateCombinedDroneAwarenessFromPowerline() [2/2]
void CombinedDroneAwarenessHandler::updateCombinedDroneAwarenessFromPowerline (combined_drone_awareness_t & combined_drone_awareness) private
Updates the given combined drone awareness from the powerline. Triggers updates of target_cable_position_known and location.
Parameters
combined_drone_awareness The combined drone awareness to update.
Returns
void
Definition at line 350 of file combined_drone_awareness_handler.cpp.
{
    // Update the target cable position known
    if (powerline_adapter_history_->empty() || !combined_drone_awareness.has_target()) {
        return;
    } else if (combined_drone_awareness.target_adapter.target_type() == TARGET_TYPE_CABLE) {
        int target_cable_id = combined_drone_awareness.target_adapter.target_id();
        combined_drone_awareness.target_position_known = (*powerline_adapter_history_)[0].HasLine(target_cable_id);
    }
    // Update the drone location
    updateDroneLocation(combined_drone_awareness);
}
References combined_drone_awareness(), iii_drone::control::combined_drone_awareness_t::has_target(), powerline_adapter_history_, iii_drone::control::combined_drone_awareness_t::target_adapter, iii_drone::adapters::TargetAdapter::target_id(), iii_drone::control::combined_drone_awareness_t::target_position_known, iii_drone::adapters::TargetAdapter::target_type(), iii_drone::adapters::TARGET_TYPE_CABLE, and updateDroneLocation().
updateCombinedDroneAwarenessFromTarget() [1/2]
void CombinedDroneAwarenessHandler::updateCombinedDroneAwarenessFromTarget () private
Updates the combined drone awareness from the target adapter. Triggers updates of target_adapter, target_position_known, and has_target.
Returns
void
Definition at line 386 of file combined_drone_awareness_handler.cpp.
{
    combined_drone_awareness_t combined_drone_awareness = *combined_drone_awareness_;
    updateCombinedDroneAwarenessFromTarget(combined_drone_awareness);
    *combined_drone_awareness_ = combined_drone_awareness;
}
References combined_drone_awareness(), combined_drone_awareness_, and updateCombinedDroneAwarenessFromTarget().
Referenced by ClearTarget(), SetTarget(), updateCombinedDroneAwareness(), and updateCombinedDroneAwarenessFromTarget().
updateCombinedDroneAwarenessFromTarget() [2/2]
void CombinedDroneAwarenessHandler::updateCombinedDroneAwarenessFromTarget (combined_drone_awareness_t & combined_drone_awareness) private
Updates the given combined drone awareness from the target adapter. Triggers updates of target_adapter, target_position_known, and has_target.
Parameters
combined_drone_awareness The combined drone awareness to update.
Returns
void
Definition at line 396 of file combined_drone_awareness_handler.cpp.
{
    // Update the target cable id
    combined_drone_awareness.target_adapter = target_adapter_->Load();
    // Update the target cable position known
    if (combined_drone_awareness.target_adapter.target_type() == TARGET_TYPE_CABLE) {
        int target_cable_id = combined_drone_awareness.target_adapter.target_id();
        combined_drone_awareness.target_position_known = (*powerline_adapter_history_)[0].HasLine(target_cable_id);
    } else {
        combined_drone_awareness.target_position_known = false;
    }
}
References combined_drone_awareness(), iii_drone::control::combined_drone_awareness_t::target_adapter, target_adapter_, iii_drone::adapters::TargetAdapter::target_id(), iii_drone::control::combined_drone_awareness_t::target_position_known, iii_drone::adapters::TargetAdapter::target_type(), and iii_drone::adapters::TARGET_TYPE_CABLE.
updateCombinedDroneAwarenessFromVehicleOdometry() [1/2]
void CombinedDroneAwarenessHandler::updateCombinedDroneAwarenessFromVehicleOdometry () private
Updates the combined drone awareness from the vehicle odometry. Triggers updates of ground altitude estimate and location.
Returns
void
Definition at line 311 of file combined_drone_awareness_handler.cpp.
{
    combined_drone_awareness_t combined_drone_awareness = *combined_drone_awareness_;
    updateCombinedDroneAwarenessFromVehicleOdometry(combined_drone_awareness);
    *combined_drone_awareness_ = combined_drone_awareness;
}
References combined_drone_awareness(), combined_drone_awareness_, and updateCombinedDroneAwarenessFromVehicleOdometry().
Referenced by CombinedDroneAwarenessHandler(), updateCombinedDroneAwareness(), and updateCombinedDroneAwarenessFromVehicleOdometry().
updateCombinedDroneAwarenessFromVehicleOdometry() [2/2]
void CombinedDroneAwarenessHandler::updateCombinedDroneAwarenessFromVehicleOdometry (combined_drone_awareness_t & combined_drone_awareness) private
Updates the given combined drone awareness from the vehicle odometry. Triggers updates of ground altitude estimate and location.
Parameters
combined_drone_awareness The combined drone awareness to update.
Returns
void
Definition at line 321 of file combined_drone_awareness_handler.cpp.
{
    // Update the ground altitude estimate
    updateGroundAltitudeEstimate(
        combined_drone_awareness.armed,
        combined_drone_awareness.offboard,
        combined_drone_awareness.has_target()
    );
    combined_drone_awareness.ground_altitude_estimate = ground_altitude_estimate_->Load();
    // Update the drone location
    updateDroneLocation(combined_drone_awareness);
    // Update state
    combined_drone_awareness.state = GetState();
}
References iii_drone::control::combined_drone_awareness_t::armed, combined_drone_awareness(), GetState(), iii_drone::control::combined_drone_awareness_t::ground_altitude_estimate, ground_altitude_estimate_, iii_drone::control::combined_drone_awareness_t::has_target(), iii_drone::utils::Atomic< T >::Load(), iii_drone::control::combined_drone_awareness_t::offboard, iii_drone::control::combined_drone_awareness_t::state, updateDroneLocation(), and updateGroundAltitudeEstimate().
updateCombinedDroneAwarenessFromVehicleStatus() [1/2]
void CombinedDroneAwarenessHandler::updateCombinedDroneAwarenessFromVehicleStatus () private
Updates the combined drone awareness from the vehicle status. Triggers updates of armed, offboard, and location.
Returns
void
Definition at line 279 of file combined_drone_awareness_handler.cpp.
{
    combined_drone_awareness_t combined_drone_awareness = *combined_drone_awareness_;
    updateCombinedDroneAwarenessFromVehicleStatus(combined_drone_awareness);
    *combined_drone_awareness_ = combined_drone_awareness;
}
References combined_drone_awareness(), combined_drone_awareness_, and updateCombinedDroneAwarenessFromVehicleStatus().
Referenced by CombinedDroneAwarenessHandler(), updateCombinedDroneAwareness(), and updateCombinedDroneAwarenessFromVehicleStatus().
updateCombinedDroneAwarenessFromVehicleStatus() [2/2]
void CombinedDroneAwarenessHandler::updateCombinedDroneAwarenessFromVehicleStatus (combined_drone_awareness_t & combined_drone_awareness) private
Updates the given combined drone awareness from the vehicle status. Triggers updates of armed, offboard, and location.
Parameters
combined_drone_awareness The combined drone awareness to update.
Returns
void
Definition at line 289 of file combined_drone_awareness_handler.cpp.
{
    // Update the armed and offboard states
    if (vehicle_status_adapter_history_->empty()) {
        combined_drone_awareness.armed = false;
        combined_drone_awareness.offboard = false;
    } else {
        combined_drone_awareness.armed = (*vehicle_status_adapter_history_)[0].arming_state() == iii_drone::adapters::px4::ARMING_STATE_ARMED;
        int navigation_state_id = (*vehicle_status_adapter_history_)[0].nav_state();
        std::vector<int> offboard_states = offboard_nav_state_ids_.Load();
        combined_drone_awareness.offboard = (std::find(offboard_states.begin(), offboard_states.end(), navigation_state_id) != offboard_states.end());
    }
    // Update the drone location:
    updateDroneLocation(combined_drone_awareness);
}
References iii_drone::control::combined_drone_awareness_t::armed, iii_drone::adapters::px4::ARMING_STATE_ARMED, combined_drone_awareness(), iii_drone::utils::Atomic< T >::Load(), iii_drone::control::combined_drone_awareness_t::offboard, offboard_nav_state_ids_, updateDroneLocation(), and vehicle_status_adapter_history_.
updateDroneLocation()
void CombinedDroneAwarenessHandler::updateDroneLocation (combined_drone_awareness_t & awareness) private
Updates the drone location of a combined drone awareness object based on current awareness information. Additionally updates the on_cable_id member by evaluating whether the drone is currently on a cable. on_cable_id will be set to -1 if the drone is not on a cable. on_cable_id can be different from target_cable_id.
Parameters
awareness The combined drone awareness object to update.
Returns
void
Definition at line 459 of file combined_drone_awareness_handler.cpp.
{
    if (vehicle_odometry_adapter_history_->empty() || vehicle_status_adapter_history_->empty()) {
        combined_drone_awareness.drone_location = DRONE_LOCATION_UNKNOWN;
        combined_drone_awareness.on_cable_id = -1;
        return;
    }
    iii_drone::adapters::px4::VehicleOdometryAdapter vehicle_odometry_adapter = (*vehicle_odometry_adapter_history_)[0];
    point_t drone_position = vehicle_odometry_adapter.position();
    // Check if on ground:
    if (drone_position[2] < params_->landed_altitude_threshold()) {
        combined_drone_awareness.drone_location = DRONE_LOCATION_ON_GROUND;
        combined_drone_awareness.on_cable_id = -1;
        return;
    }
    // Check if on cable:
    if (!powerline_adapter_history_->empty()) {
        geometry_msgs::msg::TransformStamped transform_stamped = tf_buffer_->lookupTransform(
            params_->cable_gripper_frame_id(),
            params_->drone_frame_id(),
            tf2::TimePointZero
        );
        vector_t v_drone_to_gripper = vectorFromTransformMsg(transform_stamped.transform);
        point_t gripper_position = drone_position + v_drone_to_gripper;
        iii_drone::adapters::PowerlineAdapter powerline_adapter = (*powerline_adapter_history_)[0];
        iii_drone::adapters::SingleLineAdapter closest_line;
        bool found_closest_line = false;
        try {
            closest_line = powerline_adapter.GetClosestLine(gripper_position);
            found_closest_line = true;
        } catch (std::runtime_error & e) {
            found_closest_line = false;
        }
        if (found_closest_line) {
            point_t closest_line_position = closest_line.position();
            if ((closest_line_position - gripper_position).norm() <= params_->on_cable_max_euc_distance()) {
                combined_drone_awareness.drone_location = DRONE_LOCATION_ON_CABLE;
                combined_drone_awareness.on_cable_id = closest_line.id();
                return;
            }
        }
    }
    // Check if in flight:
    if (combined_drone_awareness.armed) {
        combined_drone_awareness.drone_location = DRONE_LOCATION_IN_FLIGHT;
        return;
    }
    // Throw error if no location found
    std::string error_message = "CombinedDroneAwarenessHandler::updateDroneLocation(): Could not determine drone location.";
    if (params_->fail_on_unable_to_locate()) {
        RCLCPP_FATAL(node_->get_logger(), error_message.c_str());
        throw std::runtime_error(error_message);
    } else {
        RCLCPP_ERROR(node_->get_logger(), error_message.c_str());
        combined_drone_awareness.drone_location = DRONE_LOCATION_UNKNOWN;
        combined_drone_awareness.on_cable_id = -1;
    }
}
References iii_drone::control::combined_drone_awareness_t::armed, iii_drone::control::CombinedDroneAwarenessHandlerParameters::cable_gripper_frame_id(), combined_drone_awareness(), iii_drone::control::CombinedDroneAwarenessHandlerParameters::drone_frame_id(), iii_drone::control::combined_drone_awareness_t::drone_location, iii_drone::control::DRONE_LOCATION_IN_FLIGHT, iii_drone::control::DRONE_LOCATION_ON_CABLE, iii_drone::control::DRONE_LOCATION_ON_GROUND, iii_drone::control::DRONE_LOCATION_UNKNOWN, iii_drone::control::CombinedDroneAwarenessHandlerParameters::fail_on_unable_to_locate(), iii_drone::adapters::PowerlineAdapter::GetClosestLine(), iii_drone::adapters::SingleLineAdapter::id(), iii_drone::control::CombinedDroneAwarenessHandlerParameters::landed_altitude_threshold(), node_, iii_drone::control::combined_drone_awareness_t::on_cable_id, iii_drone::control::CombinedDroneAwarenessHandlerParameters::on_cable_max_euc_distance(), params_, iii_drone::adapters::px4::VehicleOdometryAdapter::position(), iii_drone::adapters::SingleLineAdapter::position(), powerline_adapter_history_, tf_buffer_, iii_drone::types::vectorFromTransformMsg(), vehicle_odometry_adapter_history_, and vehicle_status_adapter_history_.
Referenced by updateCombinedDroneAwarenessFromPowerline(), updateCombinedDroneAwarenessFromVehicleOdometry(), and updateCombinedDroneAwarenessFromVehicleStatus().
updateGroundAltitudeEstimate()
void CombinedDroneAwarenessHandler::updateGroundAltitudeEstimate (bool armed, bool offboard, bool has_target_cable) private
Updates the ground altitude estimate based on given information. Will either start or stop the timer based on whether the drone is on the ground. If the drone is on the ground, and the timer is not running (has elapsed), will start the timer and update the ground altitude estimate. If the drone is on the ground, and the timer is running, will do nothing. If the drone is not on the ground, and the timer is running, will stop the timer. To be called after updates to vehicle odometry, vehicle status, or target cable. Will set the ground altitude estimate to the current altitude if the drone is on the ground, based on the following criteria:
The drone is unarmed; and
The drone is not in a navigation state considered offboard; and
No target cable is registered. The ground altitude estimate is used to determine the drone location (on ground, in flight, on cable). Updates the ground altitude estimate by pushing the current altitude to the history and taking the mean of the history.
Parameters
armed Whether the drone is armed.
offboard Whether the drone is in offboard mode.
has_target_cable Whether the drone has a target cable.
Returns
void
Definition at line 411 of file combined_drone_awareness_handler.cpp.
  {
    bool is_on_ground = !armed && !offboard && !has_target_cable;
    if (!is_on_ground) {
        ground_altitude_update_timer_->cancel();
        return;
    }
    if (vehicle_odometry_adapter_history_->empty()) {
        return;
    }
    if (!ground_altitude_update_timer_->is_canceled()) {
        return;
    }
    double ground_altitude = (*vehicle_odometry_adapter_history_)[0].position()[2];
    ground_altitudes_history_.Store(ground_altitude);
    std::vector<double> ground_altitudes = ground_altitudes_history_.vector();
    double ground_altitude_estimate = std::accumulate(ground_altitudes.begin(), ground_altitudes.end(), 0.0) / ground_altitudes.size();
    ground_altitude_estimate_->Store(ground_altitude_estimate);
    ground_altitude_update_timer_->reset();
    geometry_msgs::msg::TransformStamped ground_tf;
    ground_tf.header.stamp = node_->now();
    ground_tf.header.frame_id = params_->world_frame_id();
    ground_tf.child_frame_id = params_->ground_frame_id();
    ground_tf.transform = transformMsgFromTransform(
        vector_t(0, 0, ground_altitude_estimate),
        quaternion_t(1, 0, 0, 0)
    );
    tf_broadcaster_->sendTransform(ground_tf);
}
References armed(), ground_altitude_estimate(), ground_altitude_estimate_, ground_altitude_update_timer_, ground_altitudes_history_, iii_drone::control::CombinedDroneAwarenessHandlerParameters::ground_frame_id(), node_, offboard(), params_, iii_drone::utils::Atomic< T >::Store(), iii_drone::utils::History< T >::Store(), tf_broadcaster_, iii_drone::types::transformMsgFromTransform(), iii_drone::utils::History< T >::vector(), vehicle_odometry_adapter_history_, and iii_drone::control::CombinedDroneAwarenessHandlerParameters::world_frame_id().
Referenced by updateCombinedDroneAwarenessFromVehicleOdometry().
Member Data Documentation
combined_drone_awareness_
iii_drone::utils::Atomic<combined_drone_awareness_t>::SharedPtr iii_drone::control::CombinedDroneAwarenessHandler::combined_drone_awareness_ private
Atomic combined drone awareness simple type member.
Definition at line 325 of file combined_drone_awareness_handler.hpp.
Referenced by armed(), combined_drone_awareness(), drone_location(), drone_location(), ground_altitude_estimate(), has_target(), in_flight(), offboard(), on_cable(), on_cable_id(), on_ground(), target_adapter(), target_position_known(), updateCombinedDroneAwareness(), updateCombinedDroneAwarenessFromGripperStatus(), updateCombinedDroneAwarenessFromPowerline(), updateCombinedDroneAwarenessFromTarget(), updateCombinedDroneAwarenessFromVehicleOdometry(), and updateCombinedDroneAwarenessFromVehicleStatus().
gripper_status_adapter_history_
GripperStatusAdapterHistory::SharedPtr iii_drone::control::CombinedDroneAwarenessHandler::gripper_status_adapter_history_ private
Gripper status adapter history.
Definition at line 432 of file combined_drone_awareness_handler.hpp.
Referenced by CombinedDroneAwarenessHandler(), and updateCombinedDroneAwarenessFromGripperStatus().
gripper_status_sub_
rclcpp::Subscription<iii_drone_interfaces::msg::GripperStatus>::SharedPtr iii_drone::control::CombinedDroneAwarenessHandler::gripper_status_sub_ private
Gripper status subscription.
Definition at line 427 of file combined_drone_awareness_handler.hpp.
Referenced by CombinedDroneAwarenessHandler().
ground_altitude_estimate_
iii_drone::utils::Atomic<double>::SharedPtr iii_drone::control::CombinedDroneAwarenessHandler::ground_altitude_estimate_ private
Atomic ground altitude estimate member.
Definition at line 483 of file combined_drone_awareness_handler.hpp.
Referenced by CombinedDroneAwarenessHandler(), updateCombinedDroneAwarenessFromVehicleOdometry(), and updateGroundAltitudeEstimate().
ground_altitude_update_timer_
rclcpp::TimerBase::SharedPtr iii_drone::control::CombinedDroneAwarenessHandler::ground_altitude_update_timer_ private
Timer for updating the ground altitude estimate.
Definition at line 493 of file combined_drone_awareness_handler.hpp.
Referenced by CombinedDroneAwarenessHandler(), and updateGroundAltitudeEstimate().
ground_altitudes_history_
iii_drone::utils::History<double> iii_drone::control::CombinedDroneAwarenessHandler::ground_altitudes_history_ private
Ground altitudes history.
Definition at line 488 of file combined_drone_awareness_handler.hpp.
Referenced by CombinedDroneAwarenessHandler(), and updateGroundAltitudeEstimate().
node_
rclcpp::Node* iii_drone::control::CombinedDroneAwarenessHandler::node_ private
Simple pointer to the containing node.
Definition at line 320 of file combined_drone_awareness_handler.hpp.
Referenced by CombinedDroneAwarenessHandler(), updateDroneLocation(), and updateGroundAltitudeEstimate().
offboard_nav_state_ids_
AtomicIntVector iii_drone::control::CombinedDroneAwarenessHandler::offboard_nav_state_ids_ private
Atomic vector of navigation state ids which are considered to be offboard.
Definition at line 338 of file combined_drone_awareness_handler.hpp.
Referenced by CombinedDroneAwarenessHandler(), RegisterOffboardMode(), and updateCombinedDroneAwarenessFromVehicleStatus().
params_
CombinedDroneAwarenessHandlerParameters::SharedPtr iii_drone::control::CombinedDroneAwarenessHandler::params_ private
Parameters for the combined drone awareness handler.
Definition at line 305 of file combined_drone_awareness_handler.hpp.
Referenced by CombinedDroneAwarenessHandler(), ComputeTargetTransform(), updateDroneLocation(), and updateGroundAltitudeEstimate().
powerline_adapter_history_
PowerlineAdapterHistory::SharedPtr iii_drone::control::CombinedDroneAwarenessHandler::powerline_adapter_history_ private
Powerline adapter history.
Definition at line 404 of file combined_drone_awareness_handler.hpp.
Referenced by CombinedDroneAwarenessHandler(), updateCombinedDroneAwarenessFromPowerline(), and updateDroneLocation().
powerline_sub_
rclcpp::Subscription<iii_drone_interfaces::msg::Powerline>::SharedPtr iii_drone::control::CombinedDroneAwarenessHandler::powerline_sub_ private
Powerline subscription.
Definition at line 399 of file combined_drone_awareness_handler.hpp.
Referenced by CombinedDroneAwarenessHandler().
publish_timer_
rclcpp::TimerBase::SharedPtr iii_drone::control::CombinedDroneAwarenessHandler::publish_timer_ private
Timer for publishing members.
Definition at line 536 of file combined_drone_awareness_handler.hpp.
Referenced by CombinedDroneAwarenessHandler().
target_adapter_
iii_drone::utils::Atomic<iii_drone::adapters::TargetAdapter>::SharedPtr iii_drone::control::CombinedDroneAwarenessHandler::target_adapter_ private
Atomic target adapter member.
Definition at line 455 of file combined_drone_awareness_handler.hpp.
Referenced by ClearTarget(), CombinedDroneAwarenessHandler(), publishMembers(), SetTarget(), and updateCombinedDroneAwarenessFromTarget().
target_pub_
rclcpp::Publisher<iii_drone_interfaces::msg::Target>::SharedPtr iii_drone::control::CombinedDroneAwarenessHandler::target_pub_ private
Target publisher.
Definition at line 460 of file combined_drone_awareness_handler.hpp.
Referenced by CombinedDroneAwarenessHandler(), and publishMembers().
tf_broadcaster_
std::unique_ptr<tf2_ros::TransformBroadcaster> iii_drone::control::CombinedDroneAwarenessHandler::tf_broadcaster_ private
The tf2 broadcaster fro publishing ground frame.
Definition at line 315 of file combined_drone_awareness_handler.hpp.
Referenced by CombinedDroneAwarenessHandler(), and updateGroundAltitudeEstimate().
tf_buffer_
tf2_ros::Buffer::SharedPtr iii_drone::control::CombinedDroneAwarenessHandler::tf_buffer_ private
The tf2 buffer.
Definition at line 310 of file combined_drone_awareness_handler.hpp.
Referenced by ComputeTargetTransform(), tf_buffer(), and updateDroneLocation().
vehicle_odometry_adapter_history_
VehicleOdometryAdapterHistory::SharedPtr iii_drone::control::CombinedDroneAwarenessHandler::vehicle_odometry_adapter_history_ private
Vehicle odometry adapter history.
Definition at line 376 of file combined_drone_awareness_handler.hpp.
Referenced by CombinedDroneAwarenessHandler(), GetState(), updateDroneLocation(), and updateGroundAltitudeEstimate().
vehicle_odometry_sub_
rclcpp::Subscription<px4_msgs::msg::VehicleOdometry>::SharedPtr iii_drone::control::CombinedDroneAwarenessHandler::vehicle_odometry_sub_ private
PX4 odometry subscription.
Definition at line 371 of file combined_drone_awareness_handler.hpp.
Referenced by CombinedDroneAwarenessHandler().
vehicle_status_adapter_history_
VehicleStatusAdapterHistory::SharedPtr iii_drone::control::CombinedDroneAwarenessHandler::vehicle_status_adapter_history_ private
Vehicle status adapter history.
Definition at line 348 of file combined_drone_awareness_handler.hpp.
Referenced by CombinedDroneAwarenessHandler(), GetState(), updateCombinedDroneAwarenessFromVehicleStatus(), and updateDroneLocation().
vehicle_status_sub_
rclcpp::Subscription<px4_msgs::msg::VehicleStatus>::SharedPtr iii_drone::control::CombinedDroneAwarenessHandler::vehicle_status_sub_ private
PX4 vehicle status subscription.
Definition at line 343 of file combined_drone_awareness_handler.hpp.
Referenced by CombinedDroneAwarenessHandler().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/combined_drone_awareness_handler.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/combined_drone_awareness_handler.cpp