III-Drone: iii_drone::control::maneuver::ManeuverQueue Class Reference
iii_drone::control::maneuver::ManeuverQueue Class Reference
Class for handling a queue of maneuvers to be executed.
#include <maneuver_queue.hpp>
Public Types
typedef std::shared_ptr< ManeuverQueue > SharedPtr
Shared pointer type.
typedef std::unique_ptr< ManeuverQueue > UniquePtr
Unique pointer type.
Public Member Functions
ManeuverQueue (unsigned int size=0)
Constructor.
bool Push (Maneuver item, bool block=false)
Pushes an item to the queue.
bool Pop (Maneuver &read_item, bool block=false)
Pops an item from the queue.
bool Peak (Maneuver &read_item, bool block=false) const
Peeks an item from the queue.
void Clear ()
Clears the queue.
void ClearFrom (Maneuver maneuver)
Clears the queue from a specific maneuver.
bool Update (Maneuver maneuver)
Updates a maneuver in the queue. Replace the first occurrence of the maneuver.
Maneuver Find (const rclcpp_action::GoalUUID &uuid)
Finds a maneuver from UUID.
std::vector< Maneuver > vector () const
Gets the vector of maneuvers in the queue.
int size () const
Get the current size of the queue.
bool empty () const
Whether the queue is empty.
bool full () const
Whether the queue is full.
Private Member Functions
std::vector< Maneuver >::iterator find (const rclcpp_action::GoalUUID &uuid)
Finds a maneuver in the queue by its UUID.
Private Attributes
unsigned int max_size_
Maximum size of the queue.
std::mutex reader_mutex_
Reader mutex for the queue.
std::mutex writer_mutex_
Writer mutex for the queue.
std::mutex mutex_
General mutex for the queue.
std::condition_variable is_not_full_
Condition variable for the queue not being empty.
std::condition_variable is_not_empty_
Condition variable for the queue not being full.
Detailed Description
Class for handling a queue of maneuvers to be executed.
Definition at line 30 of file maneuver_queue.hpp.
Member Typedef Documentation
SharedPtr
typedef std::shared_ptr<ManeuverQueue> iii_drone::control::maneuver::ManeuverQueue::SharedPtr
Shared pointer type.
Definition at line 139 of file maneuver_queue.hpp.
UniquePtr
typedef std::unique_ptr<ManeuverQueue> iii_drone::control::maneuver::ManeuverQueue::UniquePtr
Unique pointer type.
Definition at line 144 of file maneuver_queue.hpp.
Constructor & Destructor Documentation
ManeuverQueue()
ManeuverQueue::ManeuverQueue (unsigned int size = 0)
Constructor.
Parameters
size Maximum queue size. If 0, the queue is unbounded.
Definition at line 13 of file maneuver_queue.cpp.
{
    max_size_ = size;
    std::vector<Maneuver>::resize(0);
}
References max_size_, and size().
Member Function Documentation
Clear()
void ManeuverQueue::Clear ()
Clears the queue.
Definition at line 131 of file maneuver_queue.cpp.
{
    std::unique_lock<std::mutex> wlck(writer_mutex_);
    {
        std::unique_lock<std::mutex> lck(mutex_);
        std::vector<Maneuver>::clear();
    }
    is_not_full_.notify_all();
}
References is_not_full_, mutex_, and writer_mutex_.
Referenced by iii_drone::control::maneuver::ManeuverScheduler::cancelAllPendingManeuvers().
ClearFrom()
void ManeuverQueue::ClearFrom (Maneuver maneuver)
Clears the queue from a specific maneuver.
Parameters
maneuver Maneuver from which to clear the queue
Definition at line 145 of file maneuver_queue.cpp.
{
    std::unique_lock<std::mutex> wlck(writer_mutex_);
    std::unique_lock<std::mutex> lck(mutex_);
    std::vector<Maneuver>::iterator it = std::find(std::vector<Maneuver>::begin(), std::vector<Maneuver>::end(), maneuver);
    if(it != std::vector<Maneuver>::end()) {
        std::vector<Maneuver>::erase(std::vector<Maneuver>::begin(), it);
        lck.unlock();
        is_not_full_.notify_all();
    }
}
References is_not_full_, mutex_, and writer_mutex_.
empty()
bool ManeuverQueue::empty () const
Whether the queue is empty.
Returns
true If the queue is empty, false otherwise
Definition at line 239 of file maneuver_queue.cpp.
{
    std::unique_lock<std::mutex> rlck(reader_mutex_);
    std::unique_lock<std::mutex> lck(mutex_);
    return std::vector<Maneuver>::empty();
}
References mutex_, and reader_mutex_.
Referenced by iii_drone::control::maneuver::ManeuverScheduler::maneuverIsExecutingOrPending(), Peak(), and Pop().
Find()
Maneuver ManeuverQueue::Find (const rclcpp_action::GoalUUID & uuid)
Finds a maneuver from UUID.
Parameters
uuid UUID of the maneuver
Returns
Maneuver if found, empty maneuver otherwise
Definition at line 186 of file maneuver_queue.cpp.
{
    std::unique_lock<std::mutex> lck(mutex_);
    std::vector<Maneuver>::iterator it = find(uuid);
    if(it != std::vector<Maneuver>::end()) {
        return *it;
    }
    return Maneuver();
}
References find(), and mutex_.
Referenced by iii_drone::control::maneuver::ManeuverScheduler::RegisterManeuverServer(), and iii_drone::control::maneuver::ManeuverScheduler::UpdateManeuver().
find()
std::vector< Maneuver >::iterator ManeuverQueue::find (const rclcpp_action::GoalUUID & uuid) private
Finds a maneuver in the queue by its UUID.
Parameters
uuid UUID of the maneuver
Returns
Iterator to the maneuver if found, end() otherwise
Definition at line 202 of file maneuver_queue.cpp.
{
    std::unique_lock<std::mutex> lck(mutex_);
    return std::find_if(std::vector<Maneuver>::begin(), std::vector<Maneuver>::end(), [&uuid](const Maneuver &maneuver) {
        return maneuver.uuid() == uuid;
    });
}
References mutex_, and iii_drone::control::maneuver::Maneuver::uuid().
Referenced by Find(), and Update().
full()
bool ManeuverQueue::full () const
Whether the queue is full.
Returns
true If the queue is full, false otherwise
Definition at line 248 of file maneuver_queue.cpp.
{
    std::unique_lock<std::mutex> rlck(reader_mutex_);
    std::unique_lock<std::mutex> lck(mutex_);
    return max_size_ > 0 && std::vector<Maneuver>::size() >= max_size_;
}
References max_size_, mutex_, and reader_mutex_.
Peak()
bool ManeuverQueue::Peak (Maneuver & read_item, bool block = false) const
Peeks an item from the queue.
Parameters
read_item Read item
block Whether to block if the queue is empty, default false
Returns
true If the item was read, false otherwise
Definition at line 96 of file maneuver_queue.cpp.
        {
    std::unique_lock<std::mutex> lck(reader_mutex_);
    bool empty = false;
    {
        std::unique_lock<std::mutex> lck(mutex_);
        empty = std::vector<Maneuver>::empty();
    }
    if(empty) {
        if (!block) {
            return false;
        };
        is_not_empty_.wait(lck);
    }
    {
        std::unique_lock<std::mutex> lck(mutex_);
        read_item = std::vector<Maneuver>::front();
    }
    return true;
}
References empty(), is_not_empty_, mutex_, and reader_mutex_.
Pop()
bool ManeuverQueue::Pop (Maneuver & read_item, bool block = false)
Pops an item from the queue.
Parameters
read_item Read item
block Whether to block if the queue is empty, default false
Returns
true If the item was read, false otherwise
Definition at line 57 of file maneuver_queue.cpp.
  {
    std::unique_lock<std::mutex> lck(reader_mutex_);
    bool empty = false;
    {
        std::unique_lock<std::mutex> lck(mutex_);
        empty = std::vector<Maneuver>::empty();
    }
    if(empty) {
        if (!block) {
            return false;
        };
        is_not_empty_.wait(lck);
    }
    {
        std::unique_lock<std::mutex> lck(mutex_);
        read_item = std::vector<Maneuver>::front();
        std::vector<Maneuver>::erase(std::vector<Maneuver>::begin());
    }
    is_not_full_.notify_all();
    return true;
}
References empty(), is_not_empty_, is_not_full_, mutex_, and reader_mutex_.
Referenced by iii_drone::control::maneuver::ManeuverScheduler::progressScheduler().
Push()
bool ManeuverQueue::Push (Maneuver item, bool block = false)
Pushes an item to the queue.
Parameters
item Item to push
block Whether to block if the queue is full, default false
Returns
true If the item was pushed, false otherwise
Definition at line 21 of file maneuver_queue.cpp.
  {
    std::unique_lock<std::mutex> wlck(writer_mutex_);
    bool is_full = false;
    {
        std::unique_lock<std::mutex> lck(mutex_);
        is_full = max_size_ > 0 && std::vector<Maneuver>::size() >= max_size_;
    }
    if(is_full) {
        if (!block)
            return false;
        is_not_full_.wait(wlck);
    }
    {
        std::unique_lock<std::mutex> lck(mutex_);
        std::vector<Maneuver>::push_back(item);
    }
    is_not_empty_.notify_all();
    return true;
}
References is_not_empty_, is_not_full_, max_size_, mutex_, and writer_mutex_.
Referenced by iii_drone::control::maneuver::ManeuverScheduler::RegisterManeuver().
size()
int ManeuverQueue::size () const
Get the current size of the queue.
Returns
Current size of the queue
Definition at line 230 of file maneuver_queue.cpp.
{
    std::unique_lock<std::mutex> rlck(reader_mutex_);
    std::unique_lock<std::mutex> lck(mutex_);
    return std::vector<Maneuver>::size();
}
References mutex_, and reader_mutex_.
Referenced by ManeuverQueue().
Update()
bool ManeuverQueue::Update (Maneuver maneuver)
Updates a maneuver in the queue. Replace the first occurrence of the maneuver.
Parameters
maneuver Maneuver to update
Returns
true If the maneuver was updated, false otherwise
Definition at line 164 of file maneuver_queue.cpp.
{
    std::unique_lock<std::mutex> wlck(writer_mutex_);
    std::unique_lock<std::mutex> lck(mutex_);
    std::vector<Maneuver>::iterator it = find(maneuver.uuid());
    if(it != std::vector<Maneuver>::end()) {
        *it = maneuver;
        lck.unlock();
        return true;
    }
    return false;
}
References find(), mutex_, iii_drone::control::maneuver::Maneuver::uuid(), and writer_mutex_.
Referenced by iii_drone::control::maneuver::ManeuverScheduler::CancelManeuver(), and iii_drone::control::maneuver::ManeuverScheduler::UpdateManeuver().
vector()
std::vector< Maneuver > ManeuverQueue::vector () const
Gets the vector of maneuvers in the queue.
Returns
Vector of maneuvers in the queue
Definition at line 212 of file maneuver_queue.cpp.
{
    std::unique_lock<std::mutex> rlck(reader_mutex_);
    std::unique_lock<std::mutex> lck(mutex_);
    std::vector<Maneuver> maneuvers;
    for (auto it = std::vector<Maneuver>::begin(); it != std::vector<Maneuver>::end(); ++it) {
        maneuvers.push_back(*it);
    }
    return maneuvers;
}
References mutex_, and reader_mutex_.
Referenced by iii_drone::control::maneuver::ManeuverScheduler::ProjectExpectedAwarenessFull().
Member Data Documentation
is_not_empty_
std::condition_variable iii_drone::control::maneuver::ManeuverQueue::is_not_empty_ mutable private
Condition variable for the queue not being full.
Definition at line 175 of file maneuver_queue.hpp.
Referenced by Peak(), Pop(), and Push().
is_not_full_
std::condition_variable iii_drone::control::maneuver::ManeuverQueue::is_not_full_ private
Condition variable for the queue not being empty.
Definition at line 170 of file maneuver_queue.hpp.
Referenced by Clear(), ClearFrom(), Pop(), and Push().
max_size_
unsigned int iii_drone::control::maneuver::ManeuverQueue::max_size_ private
Maximum size of the queue.
Definition at line 150 of file maneuver_queue.hpp.
Referenced by full(), ManeuverQueue(), and Push().
mutex_
std::mutex iii_drone::control::maneuver::ManeuverQueue::mutex_ mutable private
General mutex for the queue.
Definition at line 165 of file maneuver_queue.hpp.
Referenced by Clear(), ClearFrom(), empty(), Find(), find(), full(), Peak(), Pop(), Push(), size(), Update(), and vector().
reader_mutex_
std::mutex iii_drone::control::maneuver::ManeuverQueue::reader_mutex_ mutable private
Reader mutex for the queue.
Definition at line 155 of file maneuver_queue.hpp.
Referenced by empty(), full(), Peak(), Pop(), size(), and vector().
writer_mutex_
std::mutex iii_drone::control::maneuver::ManeuverQueue::writer_mutex_ private
Writer mutex for the queue.
Definition at line 160 of file maneuver_queue.hpp.
Referenced by Clear(), ClearFrom(), Push(), and Update().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/maneuver/maneuver_queue.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/maneuver/maneuver_queue.cpp