III-Drone: iii_drone::control::maneuver::ManeuverServer Class Reference
iii_drone::control::maneuver::ManeuverServer Class Reference abstract
Flight maneuver server abstract base class. Follows a defined interface for handling by the maneuver scheduler. Underlyingly initializes an action server and handles the execution of the actions. Any deriving class must implement the following methods:
#include <maneuver_server.hpp>
Public Types
typedef std::shared_ptr< ManeuverServer > SharedPtr
Shared pointer type.
Public Member Functions
ManeuverServer (rclcpp::Node *node, CombinedDroneAwarenessHandler::SharedPtr awareness_handler, const std::string &action_name, unsigned int wait_for_execute_poll_ms, unsigned int evaluate_done_poll_ms)
Constructor.
void Start (std::function< bool(Maneuver, bool &)> register_maneuver_function, std::function< bool(Maneuver)> update_manuever_function, std::function< bool(Maneuver)> cancel_maneuver_function, std::function< bool(Maneuver)> verify_maneuver_in_queue_function, std::function< bool(Maneuver)> verify_maneuver_active_function, std::function< void(Maneuver)> done_callback, ReferenceCallbackToken::SharedPtr reference_callback_token, std::map< iii_drone::control::maneuver::maneuver_type_t, std::shared_ptr< ManeuverServer > > registered_maneuvers)
Method to start the maneuver server. The maneuver server will reject any new goals until started.
void Stop ()
Method to stop the maneuver server. The maneuver server will reject any new goals until started.
virtual bool CanExecuteManeuver (const Maneuver &maneuver, const combined_drone_awareness_t &awareness) const =0
Virtual function which checks if a maneuver can be executed given an awareness. Must be implemented specific to the maneuver type. Considers only the awareness, and not whether a maneuver is currently being executed.
virtual combined_drone_awareness_t ExpectedAwarenessAfterExecution (const Maneuver &maneuver)=0
Returns the expected combined drone awareness after successful execution of the maneuver. Must be implemented specific to the maneuver type.
std::string action_name () const
Action name getter.
bool running () const
Returns whether the maneuver server is running.
Protected Types
enum maneuver_result_type_t { MANEUVER_RESULT_TYPE_SUCCEED , MANEUVER_RESULT_TYPE_CANCEL , MANEUVER_RESULT_TYPE_ABORT }
Maneuver result type enum.
Protected Member Functions
const CombinedDroneAwarenessHandler::SharedPtr & awareness_handler () const
Combined drone awareness handler, accessible to derived classes through the protected method.
const iii_drone::utils::Atomic< iii_drone::control::maneuver::Maneuver > & current_maneuver () const
The currently executing maneuver, accessible to derived classes through the protected method.
rclcpp::Node * node () const
Node pointer getter.
std::map< iii_drone::control::maneuver::maneuver_type_t, std::shared_ptr< iii_drone::control::maneuver::ManeuverServer > > registered_maneuvers () const
Registered maneuvers map getter.
virtual maneuver_type_t maneuver_type () const =0
Function to get the maneuver type of the specific maneuver server. Must be implemented specific to the maneuver type.
virtual void startExecution (Maneuver &maneuver)=0
Function which is called when starting execution of a maneuver.
virtual bool canCancel ()=0
Can cancel virtual condition function. Must be implemented specific to the maneuver type. Should return true if the maneuver can currently be canceled, and false otherwise.
virtual Reference computeReference (const State &)=0
Compute reference callback. Must be implemented specific to the maneuver type. This function takes the current state of the drone and computes the next reference.
virtual bool hasSucceeded (Maneuver &)=0
Has succeeded callback, must return whether the maneuver has successfully completed.
virtual bool hasFailed (Maneuver &)=0
Has failed callback, returns whether the maneuver has failed.
virtual void publishFeedback (Maneuver &maneuver)=0
Publish feedback virtual function. This function should publish feedback for the maneuver using the maneuver's goal handle, if feedback is desired.
virtual void publishResultAndFinalize (Maneuver &maneuver, maneuver_result_type_t maneuver_result_type)=0
This function should publish the result and finalize the maneuver according to the result type. This must be implemented specific to the maneuver type. Finalization needs to be done on the maneuver's goal handle.
virtual void registerReferenceCallbackOnSuccess (const Maneuver &maneuver)=0
Must register the reference callback function of another maneuver server upon the completion of the current maneuver. Must be implemented specific to the maneuver type. Is called after successful completion of the maneuver. Should use the registerCallback() function.
void registerCallback (const std::function< Reference(const State &)> &callback)
Registers a callback function for the reference. The callback function should be registered with the reference callback token.
template<typename ActionT >
void createServer ()
Creates the underlying action server.
Private Types
using ReferenceCallbackToken = iii_drone::utils::Token<iii_drone::utils::Atomic<std::function<Reference(const State &)>>>
Private Member Functions
template<typename ActionT >
rclcpp_action::GoalResponse handleGoal (const rclcpp_action::GoalUUID &uuid, std::shared_ptr< const typename ActionT::Goal > goal)
Handle goal callback.
template<typename ActionT >
rclcpp_action::CancelResponse handleCancel (const std::shared_ptr< rclcpp_action::ServerGoalHandle< ActionT > > goal_handle)
Handle cancel callback.
template<typename ActionT >
void handleAccepted (const std::shared_ptr< rclcpp_action::ServerGoalHandle< ActionT > > goal_handle)
Handle accepted callback.
template<typename ActionT >
void asyncExecute (const std::shared_ptr< rclcpp_action::ServerGoalHandle< ActionT > > goal_handle)
Execute.
Private Attributes
rclcpp::Node * node_
Node pointer.
CombinedDroneAwarenessHandler::SharedPtr awareness_handler_
Combined drone awareness handler, accessible to derived classes through the protected method.
iii_drone::utils::Atomic< iii_drone::control::maneuver::Maneuver > current_maneuver_
The currently executing maneuver, accessible to derived classes through the protected method.
std::mutex mutex_
Mutex for restricting execution to one goal at a time.
std::string action_name_
Action name.
std::function< bool(Maneuver, bool &) register_maneuver_)
Function pointer for registering a maneuver.
std::function< bool(Maneuver)> update_maneuver_
Function pointer for updating an already registered maneuver (with goal handle).
std::function< bool(Maneuver)> cancel_maneuver_
Function pointer for canceling a maneuver which has already been registered.
std::function< bool(Maneuver)> verify_maneuver_in_queue_
Function pointer for verifying that the maneuver is in the queue, pending execution.
std::function< bool(Maneuver)> verify_maneuver_active_
Function pointer for verifying that the maneuver is currently active for executiong.
std::function< void(Maneuver)> done_callback_
Done callback.
ReferenceCallbackToken::SharedPtr reference_callback_token_
Reference callback token.
const unsigned int wait_for_execute_poll_ms_
Wait for execute poll milliseconds.
const unsigned int evaluate_done_poll_ms_
Evaluate done poll milliseconds.
iii_drone::utils::Atomic< bool > running_
Whether the server is running, atomic.
std::shared_ptr< void > server_
Action server shared void pointer.
std::map< iii_drone::control::maneuver::maneuver_type_t, iii_drone::control::maneuver::ManeuverServer::SharedPtr > registered_maneuvers_
The registered maneuver server map. Is used to register the reference callback of another maneuver server upon the completion of the current maneuver, which is specific to the inheriting maneuver type.
Detailed Description
Flight maneuver server abstract base class. Follows a defined interface for handling by the maneuver scheduler. Underlyingly initializes an action server and handles the execution of the actions. Any deriving class must implement the following methods:
CanExecuteManeuver: Checks if a maneuver can be executed given an awareness.
maneuver_type: Returns the maneuver type of the specific maneuver server.
startExecution: Called when starting execution of a maneuver.
canCancel: Returns whether a registered maneuver can be canceled.
computeReference: Computes the next reference given the current state of the drone.
hasSucceeded: Returns whether the maneuver has successfully completed.
hasFailed: Returns whether the maneuver has failed.
publishFeedback: Publishes feedback for the maneuver.
publishResultAndFinalize: Publishes the result and finalizes the maneuver.
registerReferenceCallbackOnSuccess: Registers a callback function for the reference. Additionally, createServer() must be called in the constructor of the derived class.
After creation, the maneuver server must be started using the Start method from the maneuver scheduler, supplying function pointers for registering and updating maneuvers, and a done callback function. Upon receiving a goal, the maneuver server will register the goal with the maneuver scheduler, which through the function pointer will tell if the maneuver can execute immediately or be queued. The action will be accepted, defered or rejected accordingly. When the action is executing, the maneuver server will register the reference callback function with the maneuver scheduler, and will execute the maneuver. The maneuver server will then periodically check if the maneuver has succeeded or failed, and publish feedback accordingly. When the maneuver is done, the maneuver server will call the done callback function, and the maneuver scheduler will take back the reference callback token.
Definition at line 78 of file maneuver_server.hpp.
Member Typedef Documentation
ReferenceCallbackToken
using iii_drone::control::maneuver::ManeuverServer::ReferenceCallbackToken = iii_drone::utils::Token<iii_drone::utils::Atomic<std::function<Reference(const State &)>>> private
Definition at line 79 of file maneuver_server.hpp.
SharedPtr
typedef std::shared_ptr<ManeuverServer> iii_drone::control::maneuver::ManeuverServer::SharedPtr
Shared pointer type.
Definition at line 190 of file maneuver_server.hpp.
Member Enumeration Documentation
maneuver_result_type_t
enum iii_drone::control::maneuver::ManeuverServer::maneuver_result_type_t protected
Maneuver result type enum.
Enumerator
MANEUVER_RESULT_TYPE_SUCCEED
MANEUVER_RESULT_TYPE_CANCEL
MANEUVER_RESULT_TYPE_ABORT
Definition at line 218 of file maneuver_server.hpp.
{
            MANEUVER_RESULT_TYPE_SUCCEED,
            MANEUVER_RESULT_TYPE_CANCEL,
            MANEUVER_RESULT_TYPE_ABORT
        };
Constructor & Destructor Documentation
ManeuverServer()
ManeuverServer::ManeuverServer (rclcpp::Node * node, CombinedDroneAwarenessHandler::SharedPtr awareness_handler, const std::string & action_name, unsigned int wait_for_execute_poll_ms, unsigned int evaluate_done_poll_ms)
Constructor.
Parameters
node Node pointer
awareness_handler Shared pointer to the combined drone awareness handler
action_name Action name
wait_for_execute_poll_ms Wait for execute poll milliseconds, default 1000
evaluate_done_poll_ms Evaluate done poll milliseconds, default 100
Definition at line 17 of file maneuver_server.cpp.
  : node_(node),
    awareness_handler_(awareness_handler),
    action_name_(action_name),
    wait_for_execute_poll_ms_(wait_for_execute_poll_ms),
    evaluate_done_poll_ms_(evaluate_done_poll_ms),
    server_(nullptr) { }
Member Function Documentation
action_name()
std::string ManeuverServer::action_name () const
Action name getter.
Returns
std::string The action name
Definition at line 61 of file maneuver_server.cpp.
{
    return action_name_;
}
References action_name_.
asyncExecute()
template<typename ActionT > void ManeuverServer::asyncExecute (const std::shared_ptr< rclcpp_action::ServerGoalHandle< ActionT > > goal_handle) private
Execute.
Definition at line 153 of file maneuver_server.cpp.
  {
    Maneuver maneuver = Maneuver::FromGoalHandle<ActionT>(goal_handle);
    rclcpp::Rate rate = rclcpp::Rate(std::chrono::milliseconds(wait_for_execute_poll_ms_));
    while(!goal_handle->is_executing()) {
        rate.sleep();
        if (!verify_maneuver_in_queue_(maneuver)) {
            goal_handle->canceled(std::make_shared<typename ActionT::Result>());
            maneuver.Terminate(false);
            cancel_maneuver_(maneuver);
            current_maneuver_ = Maneuver();
            return;
        }
    }
    std::unique_lock<std::mutex> lock(mutex_, std::try_to_lock);
    if (!lock.owns_lock()) {
        goal_handle->canceled(std::make_shared<typename ActionT::Result>());
        return;
    }
    current_maneuver_ = maneuver;
    if (!reference_callback_token_->Acquire()) {
        goal_handle->canceled(std::make_shared<typename ActionT::Result>());
        maneuver.Terminate(false);
        cancel_maneuver_(maneuver);
        current_maneuver_ = Maneuver();
        return;
    }
    startExecution(maneuver);
    Atomic<std::function<Reference(const State &)>> &get_reference_callback = reference_callback_token_->resource();
    get_reference_callback.Store(
        std::bind(
            &ManeuverServer::computeReference,
            this,
            std::placeholders::_1
        )
    );
    bool success;
    while(true) {
        if (!verify_maneuver_active_(maneuver)) {
            publishResultAndFinalize(
                maneuver,
                MANEUVER_RESULT_TYPE_CANCEL
            );
            maneuver.Terminate(false);
            cancel_maneuver_(maneuver);
            current_maneuver_ = Maneuver();
            return;
        }
        if (goal_handle->is_canceling()) {
            success = false;
            publishResultAndFinalize(
                maneuver,
                MANEUVER_RESULT_TYPE_CANCEL
            );
            break;
        }
        if (hasSucceeded(maneuver)) {
            success = true;
            publishResultAndFinalize(
                maneuver,
                MANEUVER_RESULT_TYPE_SUCCEED
            );
            break;
        }
        if (hasFailed(maneuver)) {
            success = false;
            publishResultAndFinalize(
                maneuver,
                MANEUVER_RESULT_TYPE_ABORT
            );
            break;
        }
        publishFeedback(maneuver);
        rate.sleep();
    }
    if (success) {
        registerReferenceCallbackOnSuccess(maneuver);
    }
    reference_callback_token_->Release();
    maneuver.Terminate(success);
    done_callback_(maneuver);
    current_maneuver_ = Maneuver();
}
References cancel_maneuver_, computeReference(), current_maneuver_, done_callback_, hasFailed(), hasSucceeded(), MANEUVER_RESULT_TYPE_ABORT, MANEUVER_RESULT_TYPE_CANCEL, MANEUVER_RESULT_TYPE_SUCCEED, mutex_, publishFeedback(), publishResultAndFinalize(), reference_callback_token_, registerReferenceCallbackOnSuccess(), startExecution(), iii_drone::control::maneuver::Maneuver::Terminate(), verify_maneuver_active_, verify_maneuver_in_queue_, and wait_for_execute_poll_ms_.
awareness_handler()
const CombinedDroneAwarenessHandler::SharedPtr & ManeuverServer::awareness_handler () const protected
Combined drone awareness handler, accessible to derived classes through the protected method.
Definition at line 65 of file maneuver_server.cpp.
{
    return awareness_handler_;
}
References awareness_handler_.
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::CanExecuteManeuver(), iii_drone::control::maneuver::FlyToPositionManeuverServer::CanExecuteManeuver(), iii_drone::control::maneuver::HoverByObjectManeuverServer::CanExecuteManeuver(), iii_drone::control::maneuver::HoverByObjectManeuverServer::GetReference(), iii_drone::control::maneuver::HoverOnCableManeuverServer::GetReference(), iii_drone::control::maneuver::FlyToObjectManeuverServer::getUpdatedTargetReference(), iii_drone::control::maneuver::FlyToObjectManeuverServer::hasFailed(), iii_drone::control::maneuver::FlyToPositionManeuverServer::hasFailed(), iii_drone::control::maneuver::FlyToObjectManeuverServer::hasSucceeded(), iii_drone::control::maneuver::FlyToPositionManeuverServer::hasSucceeded(), iii_drone::control::maneuver::HoverByObjectManeuverServer::hasSucceeded(), iii_drone::control::maneuver::FlyToObjectManeuverServer::publishFeedback(), iii_drone::control::maneuver::FlyToPositionManeuverServer::publishFeedback(), iii_drone::control::maneuver::FlyToObjectManeuverServer::publishResultAndFinalize(), iii_drone::control::maneuver::HoverByObjectManeuverServer::publishResultAndFinalize(), iii_drone::control::maneuver::HoverOnCableManeuverServer::publishResultAndFinalize(), iii_drone::control::maneuver::FlyToObjectManeuverServer::startExecution(), iii_drone::control::maneuver::FlyToPositionManeuverServer::startExecution(), iii_drone::control::maneuver::HoverManeuverServer::startExecution(), and iii_drone::control::maneuver::HoverByObjectManeuverServer::Update().
canCancel()
virtual bool iii_drone::control::maneuver::ManeuverServer::canCancel () protected pure virtual
Can cancel virtual condition function. Must be implemented specific to the maneuver type. Should return true if the maneuver can currently be canceled, and false otherwise.
Returns
bool True if the maneuver can be canceled, false otherwise
Implemented in iii_drone::control::maneuver::FlyToObjectManeuverServer, iii_drone::control::maneuver::FlyToPositionManeuverServer, iii_drone::control::maneuver::HoverByObjectManeuverServer, iii_drone::control::maneuver::HoverManeuverServer, and iii_drone::control::maneuver::HoverOnCableManeuverServer.
Referenced by handleCancel().
CanExecuteManeuver()
virtual bool iii_drone::control::maneuver::ManeuverServer::CanExecuteManeuver (const Maneuver & maneuver, const combined_drone_awareness_t & awareness) const pure virtual
Virtual function which checks if a maneuver can be executed given an awareness. Must be implemented specific to the maneuver type. Considers only the awareness, and not whether a maneuver is currently being executed.
Parameters
maneuver Maneuver
awareness Combined drone awareness
Returns
bool True if the maneuver can be executed, false otherwise
Implemented in iii_drone::control::maneuver::FlyToObjectManeuverServer, iii_drone::control::maneuver::FlyToPositionManeuverServer, iii_drone::control::maneuver::HoverByObjectManeuverServer, iii_drone::control::maneuver::HoverManeuverServer, and iii_drone::control::maneuver::HoverOnCableManeuverServer.
computeReference()
virtual Reference iii_drone::control::maneuver::ManeuverServer::computeReference (const State &) protected pure virtual
Compute reference callback. Must be implemented specific to the maneuver type. This function takes the current state of the drone and computes the next reference.
Implemented in iii_drone::control::maneuver::FlyToObjectManeuverServer, iii_drone::control::maneuver::FlyToPositionManeuverServer, iii_drone::control::maneuver::HoverByObjectManeuverServer, iii_drone::control::maneuver::HoverManeuverServer, and iii_drone::control::maneuver::HoverOnCableManeuverServer.
Referenced by asyncExecute().
createServer()
template<typename ActionT > void ManeuverServer::createServer () protected
Creates the underlying action server.
Template Parameters
ActionT Action type
Returns
void
Definition at line 270 of file maneuver_server.cpp.
{
    // Create action server
    std::shared_ptr<rclcpp_action::Server<ActionT>> server = rclcpp_action::create_server<ActionT>(
        node_,
        action_name_,
        std::bind(
            &ManeuverServer::handleGoal<ActionT>,
            this,
            std::placeholders::_1,
            std::placeholders::_2
        ),
        std::bind(
            &ManeuverServer::handleCancel<ActionT>,
            this,
            std::placeholders::_1
        ),
        std::bind(
            &ManeuverServer::handleAccepted<ActionT>,
            this,
            std::placeholders::_1
        )
    );
    server_ = std::static_pointer_cast<void>(server);
}
References action_name_, node_, and server_.
current_maneuver()
const iii_drone::utils::Atomic< iii_drone::control::maneuver::Maneuver > & ManeuverServer::current_maneuver () const protected
The currently executing maneuver, accessible to derived classes through the protected method.
Definition at line 69 of file maneuver_server.cpp.
{
    return current_maneuver_;
}
References current_maneuver_.
ExpectedAwarenessAfterExecution()
virtual combined_drone_awareness_t iii_drone::control::maneuver::ManeuverServer::ExpectedAwarenessAfterExecution (const Maneuver & maneuver) pure virtual
Returns the expected combined drone awareness after successful execution of the maneuver. Must be implemented specific to the maneuver type.
Parameters
maneuver Maneuver
Returns
combined_drone_awareness_t The expected combined drone awareness
Implemented in iii_drone::control::maneuver::HoverOnCableManeuverServer, iii_drone::control::maneuver::FlyToObjectManeuverServer, iii_drone::control::maneuver::FlyToPositionManeuverServer, iii_drone::control::maneuver::HoverByObjectManeuverServer, and iii_drone::control::maneuver::HoverManeuverServer.
handleAccepted()
template<typename ActionT > void ManeuverServer::handleAccepted (const std::shared_ptr< rclcpp_action::ServerGoalHandle< ActionT > > goal_handle) private
Handle accepted callback.
Parameters
goal_handle Goal handle
Definition at line 131 of file maneuver_server.cpp.
  {
    Maneuver maneuver = Maneuver::FromGoalHandle<ActionT>(goal_handle);
    if (!update_maneuver_(maneuver)) {
        goal_handle->abort(std::make_shared<typename ActionT::Result>());
        return;
    }
    std::thread{std::bind(
        &ManeuverServer::asyncExecute<ActionT>,
        this,
        std::placeholders::_1
    ),
        goal_handle
    }.detach();
}
References update_maneuver_.
handleCancel()
template<typename ActionT > rclcpp_action::CancelResponse ManeuverServer::handleCancel (const std::shared_ptr< rclcpp_action::ServerGoalHandle< ActionT > > goal_handle) private
Handle cancel callback.
Parameters
goal_handle Goal handle
Returns
rclcpp_action::CancelResponse Cancel response
Definition at line 116 of file maneuver_server.cpp.
  {
    (void)goal_handle;
    if (canCancel()) {
        return rclcpp_action::CancelResponse::ACCEPT;
    }
    return rclcpp_action::CancelResponse::REJECT;
}
References canCancel().
handleGoal()
template<typename ActionT > rclcpp_action::GoalResponse ManeuverServer::handleGoal (const rclcpp_action::GoalUUID & uuid, std::shared_ptr< const typename ActionT::Goal > goal) private
Handle goal callback.
Parameters
uuid Goal UUID
goal Goal
Returns
rclcpp_action::GoalResponse Goal response
Definition at line 82 of file maneuver_server.cpp.
  {
    if (!running_) {
        return rclcpp_action::GoalResponse::REJECT;
    }
    (void)uuid;
    Maneuver maneuver(
        maneuver_type(),
        uuid
    );
    maneuver.SetFromGoal<ActionT>(goal);
    bool executing_instantly;
    bool success = register_maneuver_(maneuver, executing_instantly);
    if (!success) {
        return rclcpp_action::GoalResponse::REJECT;
    }
    if (executing_instantly) {
        return rclcpp_action::GoalResponse::ACCEPT_AND_EXECUTE;
    }
    return rclcpp_action::GoalResponse::ACCEPT_AND_DEFER;
}
References maneuver_type(), register_maneuver_, running_, and iii_drone::control::maneuver::Maneuver::SetFromGoal().
hasFailed()
virtual bool iii_drone::control::maneuver::ManeuverServer::hasFailed (Maneuver &) protected pure virtual
Has failed callback, returns whether the maneuver has failed.
Implemented in iii_drone::control::maneuver::FlyToObjectManeuverServer, iii_drone::control::maneuver::FlyToPositionManeuverServer, iii_drone::control::maneuver::HoverByObjectManeuverServer, iii_drone::control::maneuver::HoverManeuverServer, and iii_drone::control::maneuver::HoverOnCableManeuverServer.
Referenced by asyncExecute().
hasSucceeded()
virtual bool iii_drone::control::maneuver::ManeuverServer::hasSucceeded (Maneuver &) protected pure virtual
Has succeeded callback, must return whether the maneuver has successfully completed.
Implemented in iii_drone::control::maneuver::FlyToObjectManeuverServer, iii_drone::control::maneuver::FlyToPositionManeuverServer, iii_drone::control::maneuver::HoverByObjectManeuverServer, iii_drone::control::maneuver::HoverManeuverServer, and iii_drone::control::maneuver::HoverOnCableManeuverServer.
Referenced by asyncExecute().
maneuver_type()
virtual maneuver_type_t iii_drone::control::maneuver::ManeuverServer::maneuver_type () const protected pure virtual
Function to get the maneuver type of the specific maneuver server. Must be implemented specific to the maneuver type.
Returns
maneuver_type_t The maneuver type
Implemented in iii_drone::control::maneuver::FlyToObjectManeuverServer, iii_drone::control::maneuver::FlyToPositionManeuverServer, iii_drone::control::maneuver::HoverByObjectManeuverServer, iii_drone::control::maneuver::HoverManeuverServer, and iii_drone::control::maneuver::HoverOnCableManeuverServer.
Referenced by handleGoal().
node()
rclcpp::Node * ManeuverServer::node () const protected
Node pointer getter.
Definition at line 77 of file maneuver_server.cpp.
{
    return node_;
}
References node_.
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::computeReference(), iii_drone::control::maneuver::FlyToPositionManeuverServer::computeReference(), iii_drone::control::maneuver::FlyToObjectManeuverServer::startExecution(), and iii_drone::control::maneuver::FlyToPositionManeuverServer::startExecution().
publishFeedback()
virtual void iii_drone::control::maneuver::ManeuverServer::publishFeedback (Maneuver & maneuver) protected pure virtual
Publish feedback virtual function. This function should publish feedback for the maneuver using the maneuver's goal handle, if feedback is desired.
Implemented in iii_drone::control::maneuver::FlyToObjectManeuverServer, iii_drone::control::maneuver::FlyToPositionManeuverServer, iii_drone::control::maneuver::HoverByObjectManeuverServer, iii_drone::control::maneuver::HoverManeuverServer, and iii_drone::control::maneuver::HoverOnCableManeuverServer.
Referenced by asyncExecute().
publishResultAndFinalize()
virtual void iii_drone::control::maneuver::ManeuverServer::publishResultAndFinalize (Maneuver & maneuver, maneuver_result_type_t maneuver_result_type) protected pure virtual
This function should publish the result and finalize the maneuver according to the result type. This must be implemented specific to the maneuver type. Finalization needs to be done on the maneuver's goal handle.
Implemented in iii_drone::control::maneuver::FlyToObjectManeuverServer, iii_drone::control::maneuver::FlyToPositionManeuverServer, iii_drone::control::maneuver::HoverByObjectManeuverServer, iii_drone::control::maneuver::HoverManeuverServer, and iii_drone::control::maneuver::HoverOnCableManeuverServer.
Referenced by asyncExecute().
registerCallback()
void ManeuverServer::registerCallback (const std::function< Reference(const State &)> & callback) protected
Registers a callback function for the reference. The callback function should be registered with the reference callback token.
Parameters
callback The callback function
Returns
void
Definition at line 265 of file maneuver_server.cpp.
{
    reference_callback_token_->resource() = callback;
}
References reference_callback_token_.
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::registerReferenceCallbackOnSuccess(), iii_drone::control::maneuver::FlyToPositionManeuverServer::registerReferenceCallbackOnSuccess(), iii_drone::control::maneuver::HoverByObjectManeuverServer::registerReferenceCallbackOnSuccess(), iii_drone::control::maneuver::HoverManeuverServer::registerReferenceCallbackOnSuccess(), and iii_drone::control::maneuver::HoverOnCableManeuverServer::registerReferenceCallbackOnSuccess().
registered_maneuvers()
std::map< iii_drone::control::maneuver::maneuver_type_t, std::shared_ptr< ManeuverServer > > ManeuverServer::registered_maneuvers () const protected
Registered maneuvers map getter.
Returns
The registered maneuvers map.
Definition at line 73 of file maneuver_server.cpp.
{
    return registered_maneuvers_;
}
References registered_maneuvers_.
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::registerReferenceCallbackOnSuccess(), iii_drone::control::maneuver::FlyToPositionManeuverServer::registerReferenceCallbackOnSuccess(), and Start().
registerReferenceCallbackOnSuccess()
virtual void iii_drone::control::maneuver::ManeuverServer::registerReferenceCallbackOnSuccess (const Maneuver & maneuver) protected pure virtual
Must register the reference callback function of another maneuver server upon the completion of the current maneuver. Must be implemented specific to the maneuver type. Is called after successful completion of the maneuver. Should use the registerCallback() function.
Parameters
maneuver The maneuver which has completed
Returns
void
Implemented in iii_drone::control::maneuver::FlyToObjectManeuverServer, iii_drone::control::maneuver::FlyToPositionManeuverServer, iii_drone::control::maneuver::HoverByObjectManeuverServer, iii_drone::control::maneuver::HoverManeuverServer, and iii_drone::control::maneuver::HoverOnCableManeuverServer.
Referenced by asyncExecute().
running()
bool ManeuverServer::running () const
Returns whether the maneuver server is running.
Returns
bool True if the maneuver server is running, false otherwise
Definition at line 57 of file maneuver_server.cpp.
{
    return running_;
}
References running_.
Start()
void ManeuverServer::Start (std::function< bool(Maneuver, bool &)> register_maneuver_function, std::function< bool(Maneuver)> update_manuever_function, std::function< bool(Maneuver)> cancel_maneuver_function, std::function< bool(Maneuver)> verify_maneuver_in_queue_function, std::function< bool(Maneuver)> verify_maneuver_active_function, std::function< void(Maneuver)> done_callback, ReferenceCallbackToken::SharedPtr reference_callback_token, std::map< iii_drone::control::maneuver::maneuver_type_t, std::shared_ptr< ManeuverServer > > registered_maneuvers)
Method to start the maneuver server. The maneuver server will reject any new goals until started.
Parameters
register_maneuver_function Function pointer for registering a maneuver. Must be supplied by the maneuver scheduler. The function should take the maneuver to be registered, and a boolean reference which should be set to true if the maneuver can be executed instantly and false if the maneuver can only be executed later. The function should return false if the maneuver can not be queued or executed, and true otherwise.
update_manuever_function Function pointer for updating a maneuver. Must be supplied by the maneuver scheduler. The function takes a maneuver initiated with the goal handle, and should internally update the maneuver entry with the new goal handle. This function will be executed at some time after the goal is accepted, and before the goal is executed. Should return false if the maneuver can not be updated, in which case the goal will be aborted, and true otherwise.
cancel_maneuver_function Function pointer for canceling a maneuver. Must be supplied by the maneuver scheduler. The function should take the maneuver to be canceled, and return true if the maneuver was canceled successfully, and false otherwise. The maneuver object must be terminated using the Terminate() method before canceling with success=false.
verify_maneuver_in_queue_function Function pointer for verifying that the maneuver is in the queue, pending execution. Must be supplied by the maneuver scheduler. The function should take the maneuver to be verified, and return true if the maneuver is in the queue or is the currently active maneuver, and false otherwise.
verify_maneuver_active_function Function pointer for verifying that the maneuver is currently active for execution. Must be supplied by the maneuver scheduler. The function should take the maneuver to be verified, and return true if the maneuver is currently active, and false otherwise. If the maneuver is not active, the action will be aborted. The queue integrity must be kept, as the maneuver will not return to the queue if it stops being active.
done_callback Function pointer for done callback. Must be supplied by the maneuver scheduler. The function should take the maneuver. The maneuver object must be terminated using the Terminate() method. Any cleanup or post-maneuver actions should be executed in this function. The function must reacquire the reference callback token from the maneuver server and register an intermediate reference callback function with the token.
reference_callback_token Slave token shared pointer for the reference callback shared function pointer handle. This token will be acquired by the maneuver server upon beginning execution of a maneuver. The maneuver server will register its own reference callback function with the token. The master is responsible for taking the token back when the maneuver is done or have failed.
registered_maneuvers The registered maneuver server map. Is used to register the reference callback of another maneuver server upon the completion of the current maneuver, which is specific to the inheriting maneuver type.
Returns
void
Definition at line 30 of file maneuver_server.cpp.
  {
    register_maneuver_ = register_maneuver_function;
    update_maneuver_ = update_manuever_function;
    cancel_maneuver_ = cancel_maneuver_function;
    verify_maneuver_in_queue_ = verify_maneuver_in_queue_function;
    verify_maneuver_active_ = verify_maneuver_active_function;
    done_callback_ = done_callback;
    reference_callback_token_ = reference_callback_token;
    registered_maneuvers_ = registered_maneuvers;
    running_ = true;
}
References cancel_maneuver_, done_callback_, reference_callback_token_, register_maneuver_, registered_maneuvers(), registered_maneuvers_, running_, update_maneuver_, verify_maneuver_active_, and verify_maneuver_in_queue_.
startExecution()
virtual void iii_drone::control::maneuver::ManeuverServer::startExecution (Maneuver & maneuver) protected pure virtual
Function which is called when starting execution of a maneuver.
Parameters
maneuver The maneuver to start executing
Returns
void
Implemented in iii_drone::control::maneuver::FlyToObjectManeuverServer, iii_drone::control::maneuver::FlyToPositionManeuverServer, iii_drone::control::maneuver::HoverByObjectManeuverServer, iii_drone::control::maneuver::HoverManeuverServer, and iii_drone::control::maneuver::HoverOnCableManeuverServer.
Referenced by asyncExecute().
Stop()
void ManeuverServer::Stop ()
Method to stop the maneuver server. The maneuver server will reject any new goals until started.
Returns
void
Definition at line 53 of file maneuver_server.cpp.
{
    running_ = false;
}
References running_.
Member Data Documentation
action_name_
std::string iii_drone::control::maneuver::ManeuverServer::action_name_ private
Action name.
Definition at line 336 of file maneuver_server.hpp.
Referenced by action_name(), and createServer().
awareness_handler_
CombinedDroneAwarenessHandler::SharedPtr iii_drone::control::maneuver::ManeuverServer::awareness_handler_ private
Combined drone awareness handler, accessible to derived classes through the protected method.
Definition at line 321 of file maneuver_server.hpp.
Referenced by awareness_handler().
cancel_maneuver_
std::function<bool(Maneuver)> iii_drone::control::maneuver::ManeuverServer::cancel_maneuver_ private
Function pointer for canceling a maneuver which has already been registered.
Parameters
maneuver The maneuver to cancel. Terminate() must have been called on the maneuver before canceling.
Returns
bool True if the maneuver was canceled successfully, false otherwise
Definition at line 364 of file maneuver_server.hpp.
Referenced by asyncExecute(), and Start().
current_maneuver_
iii_drone::utils::Atomic<iii_drone::control::maneuver::Maneuver> iii_drone::control::maneuver::ManeuverServer::current_maneuver_ private
The currently executing maneuver, accessible to derived classes through the protected method.
Definition at line 326 of file maneuver_server.hpp.
Referenced by asyncExecute(), and current_maneuver().
done_callback_
std::function<void(Maneuver)> iii_drone::control::maneuver::ManeuverServer::done_callback_ private
Done callback.
Definition at line 387 of file maneuver_server.hpp.
Referenced by asyncExecute(), and Start().
evaluate_done_poll_ms_
const unsigned int iii_drone::control::maneuver::ManeuverServer::evaluate_done_poll_ms_ private
Evaluate done poll milliseconds.
Definition at line 402 of file maneuver_server.hpp.
mutex_
std::mutex iii_drone::control::maneuver::ManeuverServer::mutex_ private
Mutex for restricting execution to one goal at a time.
Definition at line 331 of file maneuver_server.hpp.
Referenced by asyncExecute().
node_
rclcpp::Node* iii_drone::control::maneuver::ManeuverServer::node_ private
Node pointer.
Definition at line 316 of file maneuver_server.hpp.
Referenced by createServer(), and node().
reference_callback_token_
ReferenceCallbackToken::SharedPtr iii_drone::control::maneuver::ManeuverServer::reference_callback_token_ private
Reference callback token.
Definition at line 392 of file maneuver_server.hpp.
Referenced by asyncExecute(), registerCallback(), and Start().
register_maneuver_
std::function<bool(Maneuver, bool &) iii_drone::control::maneuver::ManeuverServer::register_maneuver_) private
Function pointer for registering a maneuver.
Parameters
maneuver The maneuver to register
executing_instantly Output, whether the maneuver can be executed instantly
Returns
bool True if the maneuver was queued successfully, false otherwise
Definition at line 346 of file maneuver_server.hpp.
Referenced by handleGoal(), and Start().
registered_maneuvers_
std::map<iii_drone::control::maneuver::maneuver_type_t, iii_drone::control::maneuver::ManeuverServer::SharedPtr> iii_drone::control::maneuver::ManeuverServer::registered_maneuvers_ private
The registered maneuver server map. Is used to register the reference callback of another maneuver server upon the completion of the current maneuver, which is specific to the inheriting maneuver type.
Definition at line 461 of file maneuver_server.hpp.
Referenced by registered_maneuvers(), and Start().
running_
iii_drone::utils::Atomic<bool> iii_drone::control::maneuver::ManeuverServer::running_ private
Whether the server is running, atomic.
Definition at line 407 of file maneuver_server.hpp.
Referenced by handleGoal(), running(), Start(), and Stop().
server_
std::shared_ptr<void> iii_drone::control::maneuver::ManeuverServer::server_ private
Action server shared void pointer.
Definition at line 412 of file maneuver_server.hpp.
Referenced by createServer().
update_maneuver_
std::function<bool(Maneuver)> iii_drone::control::maneuver::ManeuverServer::update_maneuver_ private
Function pointer for updating an already registered maneuver (with goal handle).
Parameters
maneuver The new maneuver.
Returns
bool True if the maneuver was updated successfully, false otherwise
Definition at line 355 of file maneuver_server.hpp.
Referenced by handleAccepted(), and Start().
verify_maneuver_active_
std::function<bool(Maneuver)> iii_drone::control::maneuver::ManeuverServer::verify_maneuver_active_ private
Function pointer for verifying that the maneuver is currently active for executiong.
Parameters
maneuver The maneuver to verify.
Returns
bool True if the maneuver is currently active, false otherwise
Definition at line 382 of file maneuver_server.hpp.
Referenced by asyncExecute(), and Start().
verify_maneuver_in_queue_
std::function<bool(Maneuver)> iii_drone::control::maneuver::ManeuverServer::verify_maneuver_in_queue_ private
Function pointer for verifying that the maneuver is in the queue, pending execution.
Parameters
maneuver The maneuver to verify.
Returns
bool True if the maneuver is in the queue, false otherwise
Definition at line 373 of file maneuver_server.hpp.
Referenced by asyncExecute(), and Start().
wait_for_execute_poll_ms_
const unsigned int iii_drone::control::maneuver::ManeuverServer::wait_for_execute_poll_ms_ private
Wait for execute poll milliseconds.
Definition at line 397 of file maneuver_server.hpp.
Referenced by asyncExecute().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/maneuver/maneuver_server.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/maneuver/maneuver_server.cpp