III-Drone: iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator Class Reference
iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator Class Reference
Class for handling parameters for a positional MPC.
#include <trajectory_generator_node_configurator.hpp>
Public Member Functions
TrajectoryGeneratorNodeConfigurator (rclcpp::Node *node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Constructor.
TrajectoryGeneratorNodeConfigurator (rclcpp::Node *node, const rclcpp::QoS &qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Constructor.
double dt () const
dt getter.
std::string world_frame_id () const
world_frame_id getter.
std::string drone_frame_id () const
drone_frame_id getter.
const std::shared_ptr< const control::MPCParameters > positional_mpc_parameters () const
Get the MPC parameters object for the positional MPC.
const std::shared_ptr< const control::MPCParameters > cable_landing_mpc_parameters () const
Get the MPC parameters object for the cable landing MPC.
const std::shared_ptr< const control::MPCParameters > cable_takeoff_mpc_parameters () const
Get the MPC parameters object for the cable takeoff MPC.
Public Member Functions inherited from iii_drone::configuration::Configurator
Configurator (rclcpp::Node *node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Configurator (rclcpp::Node *node, const rclcpp::QoS &qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
~Configurator ()
template<typename T >
void DeclareParameter (const std::string &name)
rclcpp::Parameter GetParameter (const std::string &name) const
Get a parameter.
std::vector< rclcpp::Parameter > GetParameters (const std::vector< std::string > &names) const
Gets multiple parameters.
void SyncParameters (const std::vector< std::string > &names={})
Synchronizes parameters with the parameter server. Should never be necessary.
void PrintParameters () const
Prints all parameters to the console.
Private Member Functions
void declareMPCParameters ()
Declares the MPC specific parameters.
void initMPCParametersObject ()
Initializes the MPC parameters object.
void updateMPCParametersObjectCallback (const rclcpp::Parameter &parameter)
Callback function called after successful parameter change to update MPCParameters object.
Private Attributes
std::shared_ptr< control::MPCParameters > positional_mpc_parameters_
MPC parameters object for the positional MPC.
std::shared_ptr< control::MPCParameters > cable_landing_mpc_parameters_
MPC parameters object for the cable landing MPC.
std::shared_ptr< control::MPCParameters > cable_takeoff_mpc_parameters_
MPC parameters object for the cable takeoff MPC.
bool mpc_parameters_initialized_ = false
MPCParameters object initialized flag.
const std::string positional_mpc_parameter_name_prefix = "/control/MPC/position_MPC_"
Positional MPC parameter name prefixes.
const std::string cable_landing_mpc_parameter_name_prefix = "/control/MPC/cable_landing_MPC_"
Cable landing MPC parameter name prefixes.
const std::string cable_takeoff_mpc_parameter_name_prefix = "/control/MPC/cable_takeoff_MPC_"
Cable takeoff MPC parameter name prefixes.
std::function< void(const rclcpp::Parameter &) after_parameter_change_callback_)
Callback function reference called after successful parameter change.
Additional Inherited Members
Static Public Member Functions inherited from iii_drone::configuration::Configurator
template<typename T >
static std::string GetParameterTypeString ()
Static function for getting string representation of a parameter type from template type.
Protected Attributes inherited from iii_drone::configuration::Configurator
rclcpp::Node * node_
Detailed Description
Class for handling parameters for a positional MPC.
Definition at line 38 of file trajectory_generator_node_configurator.hpp.
Constructor & Destructor Documentation
TrajectoryGeneratorNodeConfigurator() [1/2]
TrajectoryGeneratorNodeConfigurator::TrajectoryGeneratorNodeConfigurator (rclcpp::Node * node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback = nullptr)
Constructor.
Parameters
node Reference to the handling node
after_parameter_change_callback Callback function called after successful parameter change, default is nullptr
Definition at line 15 of file trajectory_generator_node_configurator.cpp.
  : Configurator(
        node,
        std::bind(
            &TrajectoryGeneratorNodeConfigurator::updateMPCParametersObjectCallback,
            this,
            std::placeholders::_1
        )
    ),
    after_parameter_change_callback_(after_parameter_change_callback)
{
    declareMPCParameters();
    initMPCParametersObject();
}
References declareMPCParameters(), and initMPCParametersObject().
TrajectoryGeneratorNodeConfigurator() [2/2]
TrajectoryGeneratorNodeConfigurator::TrajectoryGeneratorNodeConfigurator (rclcpp::Node * node, const rclcpp::QoS & qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback = nullptr)
Constructor.
Parameters
node Reference to the handling node
qos QoS profile for the parameter event subscription
after_parameter_change_callback Callback function called after successful parameter change, default is nullptr
Definition at line 34 of file trajectory_generator_node_configurator.cpp.
  : Configurator(
        node,
        qos,
        std::bind(
            &TrajectoryGeneratorNodeConfigurator::updateMPCParametersObjectCallback,
            this,
            std::placeholders::_1
        )
    ),
    after_parameter_change_callback_(after_parameter_change_callback)
{
    declareMPCParameters();
    initMPCParametersObject();
}
References declareMPCParameters(), and initMPCParametersObject().
Member Function Documentation
cable_landing_mpc_parameters()
const std::shared_ptr< const MPCParameters > TrajectoryGeneratorNodeConfigurator::cable_landing_mpc_parameters () const
Get the MPC parameters object for the cable landing MPC.
Returns
MPC parameters object reference
Definition at line 79 of file trajectory_generator_node_configurator.cpp.
{
    return cable_landing_mpc_parameters_;
}
References cable_landing_mpc_parameters_.
cable_takeoff_mpc_parameters()
const std::shared_ptr< const MPCParameters > TrajectoryGeneratorNodeConfigurator::cable_takeoff_mpc_parameters () const
Get the MPC parameters object for the cable takeoff MPC.
Returns
MPC parameters object reference
Definition at line 85 of file trajectory_generator_node_configurator.cpp.
{
    return cable_takeoff_mpc_parameters_;
}
References cable_takeoff_mpc_parameters_.
declareMPCParameters()
void TrajectoryGeneratorNodeConfigurator::declareMPCParameters () private
Declares the MPC specific parameters.
Returns
void
Definition at line 91 of file trajectory_generator_node_configurator.cpp.
{
    DeclareParameter<bool>("/control/MPC/MPC_use_state_feedback");
    DeclareParameter<int>("/control/MPC/MPC_N");
    DeclareParameter<float>("/control/MPC/dt");
    DeclareParameter<std::string>("/tf/world_frame_id");
    DeclareParameter<std::string>("/tf/drone_frame_id");
    auto declareMPCParametersWithPrefix = [this](std::string prefix) {
        DeclareParameter<float>(prefix + "vx_max");
        DeclareParameter<float>(prefix + "vy_max");
        DeclareParameter<float>(prefix + "vz_max");
        DeclareParameter<float>(prefix + "ax_max");
        DeclareParameter<float>(prefix + "ay_max");
        DeclareParameter<float>(prefix + "az_max");
        DeclareParameter<float>(prefix + "wx");
        DeclareParameter<float>(prefix + "wy");
        DeclareParameter<float>(prefix + "wz");
        DeclareParameter<float>(prefix + "wvx");
        DeclareParameter<float>(prefix + "wvy");
        DeclareParameter<float>(prefix + "wvz");
        DeclareParameter<float>(prefix + "wax");
        DeclareParameter<float>(prefix + "way");
        DeclareParameter<float>(prefix + "waz");
        DeclareParameter<float>(prefix + "wjx");
        DeclareParameter<float>(prefix + "wjy");
        DeclareParameter<float>(prefix + "wjz");
    };
    declareMPCParametersWithPrefix(positional_mpc_parameter_name_prefix);
    declareMPCParametersWithPrefix(cable_landing_mpc_parameter_name_prefix);
    declareMPCParametersWithPrefix(cable_takeoff_mpc_parameter_name_prefix);
}
References cable_landing_mpc_parameter_name_prefix, cable_takeoff_mpc_parameter_name_prefix, Configurator::DeclareParameter< std::string >(), iii_drone::configuration::Configurator::GetParameterTypeString(), and positional_mpc_parameter_name_prefix.
Referenced by TrajectoryGeneratorNodeConfigurator(), and TrajectoryGeneratorNodeConfigurator().
drone_frame_id()
std::string TrajectoryGeneratorNodeConfigurator::drone_frame_id () const
drone_frame_id getter.
Definition at line 67 of file trajectory_generator_node_configurator.cpp.
{
    return GetParameter("/tf/drone_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
dt()
double TrajectoryGeneratorNodeConfigurator::dt () const
dt getter.
Definition at line 55 of file trajectory_generator_node_configurator.cpp.
{
    return GetParameter("/control/MPC/dt").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initMPCParametersObject().
initMPCParametersObject()
void TrajectoryGeneratorNodeConfigurator::initMPCParametersObject () private
Initializes the MPC parameters object.
Returns
void
Definition at line 134 of file trajectory_generator_node_configurator.cpp.
{
    auto initMPCParametersObjectWithPrefix = [this](std::string parameter_prefix) {
        bool use_state_feedback = GetParameter("/control/MPC/MPC_use_state_feedback").as_bool();
        int N = GetParameter("/control/MPC/MPC_N").as_int();
        double dt = GetParameter("/control/MPC/dt").as_double();
        vector_t v_max = {
            (float)GetParameter(parameter_prefix + "vx_max").as_double(),
            (float)GetParameter(parameter_prefix + "vy_max").as_double(),
            (float)GetParameter(parameter_prefix + "vz_max").as_double()
        };
        vector_t a_max = {
            (float)GetParameter(parameter_prefix + "ax_max").as_double(),
            (float)GetParameter(parameter_prefix + "ay_max").as_double(),
            (float)GetParameter(parameter_prefix + "az_max").as_double()
        };
        vector_t wp = {
            (float)GetParameter(parameter_prefix + "wx").as_double(),
            (float)GetParameter(parameter_prefix + "wy").as_double(),
            (float)GetParameter(parameter_prefix + "wz").as_double()
        };
        vector_t wv = {
            (float)GetParameter(parameter_prefix + "wvx").as_double(),
            (float)GetParameter(parameter_prefix + "wvy").as_double(),
            (float)GetParameter(parameter_prefix + "wvz").as_double()
        };
        vector_t wa = {
            (float)GetParameter(parameter_prefix + "wax").as_double(),
            (float)GetParameter(parameter_prefix + "way").as_double(),
            (float)GetParameter(parameter_prefix + "waz").as_double()
        };
        vector_t wj = {
            (float)GetParameter(parameter_prefix + "wjx").as_double(),
            (float)GetParameter(parameter_prefix + "wjy").as_double(),
            (float)GetParameter(parameter_prefix + "wjz").as_double()
        };
        std::shared_ptr<MPCParameters> params = std::make_shared<MPCParameters>(
            use_state_feedback,
            N,
            dt,
            v_max,
            a_max,
            wp,
            wv,
            wa,
            wj
        );
        return params;
    };
    positional_mpc_parameters_ = initMPCParametersObjectWithPrefix(positional_mpc_parameter_name_prefix);
    cable_landing_mpc_parameters_ = initMPCParametersObjectWithPrefix(cable_landing_mpc_parameter_name_prefix);
    cable_takeoff_mpc_parameters_ = initMPCParametersObjectWithPrefix(cable_takeoff_mpc_parameter_name_prefix);
    mpc_parameters_initialized_ = true;
}
References cable_landing_mpc_parameter_name_prefix, cable_landing_mpc_parameters_, cable_takeoff_mpc_parameter_name_prefix, cable_takeoff_mpc_parameters_, dt(), iii_drone::configuration::Configurator::GetParameter(), iii_drone::configuration::Configurator::GetParameterTypeString(), mpc_parameters_initialized_, positional_mpc_parameter_name_prefix, and positional_mpc_parameters_.
Referenced by TrajectoryGeneratorNodeConfigurator(), and TrajectoryGeneratorNodeConfigurator().
positional_mpc_parameters()
const std::shared_ptr< const MPCParameters > TrajectoryGeneratorNodeConfigurator::positional_mpc_parameters () const
Get the MPC parameters object for the positional MPC.
Returns
MPC parameters object reference
Definition at line 73 of file trajectory_generator_node_configurator.cpp.
{
    return positional_mpc_parameters_;
}
References positional_mpc_parameters_.
updateMPCParametersObjectCallback()
void TrajectoryGeneratorNodeConfigurator::updateMPCParametersObjectCallback (const rclcpp::Parameter & parameter) private
Callback function called after successful parameter change to update MPCParameters object.
Definition at line 202 of file trajectory_generator_node_configurator.cpp.
{
    auto updateMPCParametersObjectWithPrefix = [&](
        std::string parameter_prefix,
        std::shared_ptr<MPCParameters> & mpc_parameters
    ) {
        if (mpc_parameters_initialized_) {
            std::string parameter_name = parameter.get_name();
            if (
                parameter_name == parameter_prefix + "vx_max" ||
                parameter_name == parameter_prefix + "vy_max" ||
                parameter_name == parameter_prefix + "vz_max"
            ) {
                vector_t v_max = {
                    (float)GetParameter(parameter_prefix + "vx_max").as_double(),
                    (float)GetParameter(parameter_prefix + "vy_max").as_double(),
                    (float)GetParameter(parameter_prefix + "vz_max").as_double()
                };
                mpc_parameters->v_max() = v_max;
            } else if (
                parameter_name == parameter_prefix + "ax_max" ||
                parameter_name == parameter_prefix + "ay_max" ||
                parameter_name == parameter_prefix + "az_max"
            ) {
                vector_t a_max = {
                    (float)GetParameter(parameter_prefix + "ax_max").as_double(),
                    (float)GetParameter(parameter_prefix + "ay_max").as_double(),
                    (float)GetParameter(parameter_prefix + "az_max").as_double()
                };
                mpc_parameters->a_max() = a_max;
            } else if (
                parameter_name == parameter_prefix + "wx" ||
                parameter_name == parameter_prefix + "wy" ||
                parameter_name == parameter_prefix + "wz"
            ) {
                vector_t wp = {
                    (float)GetParameter(parameter_prefix + "wx").as_double(),
                    (float)GetParameter(parameter_prefix + "wy").as_double(),
                    (float)GetParameter(parameter_prefix + "wz").as_double()
                };
                mpc_parameters->wp() = wp;
            } else if (
                parameter_name == parameter_prefix + "wvx" ||
                parameter_name == parameter_prefix + "wvy" ||
                parameter_name == parameter_prefix + "wvz"
            ) {
                vector_t wv = {
                    (float)GetParameter(parameter_prefix + "wvx").as_double(),
                    (float)GetParameter(parameter_prefix + "wvy").as_double(),
                    (float)GetParameter(parameter_prefix + "wvz").as_double()
                };
                mpc_parameters->wv() = wv;
            } else if (
                parameter_name == parameter_prefix + "wax" ||
                parameter_name == parameter_prefix + "way" ||
                parameter_name == parameter_prefix + "waz"
            ) {
                vector_t wa = {
                    (float)GetParameter(parameter_prefix + "wax").as_double(),
                    (float)GetParameter(parameter_prefix + "way").as_double(),
                    (float)GetParameter(parameter_prefix + "waz").as_double()
                };
                mpc_parameters->wa() = wa;
            } else if (
                parameter_name == parameter_prefix + "wjx" ||
                parameter_name == parameter_prefix + "wjy" ||
                parameter_name == parameter_prefix + "wjz"
            ) {
                vector_t wj = {
                    (float)GetParameter(parameter_prefix + "wjx").as_double(),
                    (float)GetParameter(parameter_prefix + "wjy").as_double(),
                    (float)GetParameter(parameter_prefix + "wjz").as_double()
                };
                mpc_parameters->wj() = wj;
            }
        }
    };
    updateMPCParametersObjectWithPrefix(positional_mpc_parameter_name_prefix, positional_mpc_parameters_);
    updateMPCParametersObjectWithPrefix(cable_landing_mpc_parameter_name_prefix, cable_landing_mpc_parameters_);
    updateMPCParametersObjectWithPrefix(cable_takeoff_mpc_parameter_name_prefix, cable_takeoff_mpc_parameters_);
    if (after_parameter_change_callback_ != nullptr) {
        after_parameter_change_callback_(parameter);
    }
}
References after_parameter_change_callback_, cable_landing_mpc_parameter_name_prefix, cable_landing_mpc_parameters_, cable_takeoff_mpc_parameter_name_prefix, cable_takeoff_mpc_parameters_, iii_drone::configuration::Configurator::GetParameter(), iii_drone::configuration::Configurator::GetParameterTypeString(), mpc_parameters_initialized_, positional_mpc_parameter_name_prefix, and positional_mpc_parameters_.
world_frame_id()
std::string TrajectoryGeneratorNodeConfigurator::world_frame_id () const
world_frame_id getter.
Definition at line 61 of file trajectory_generator_node_configurator.cpp.
{
    return GetParameter("/tf/world_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNode::publishPlannedTrajectory().
Member Data Documentation
after_parameter_change_callback_
std::function<void(const rclcpp::Parameter &) iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator::after_parameter_change_callback_) private
Callback function reference called after successful parameter change.
Definition at line 159 of file trajectory_generator_node_configurator.hpp.
Referenced by updateMPCParametersObjectCallback().
cable_landing_mpc_parameter_name_prefix
const std::string iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator::cable_landing_mpc_parameter_name_prefix = "/control/MPC/cable_landing_MPC_" private
Cable landing MPC parameter name prefixes.
Definition at line 130 of file trajectory_generator_node_configurator.hpp.
Referenced by declareMPCParameters(), initMPCParametersObject(), and updateMPCParametersObjectCallback().
cable_landing_mpc_parameters_
std::shared_ptr<control::MPCParameters> iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator::cable_landing_mpc_parameters_ private
MPC parameters object for the cable landing MPC.
Definition at line 110 of file trajectory_generator_node_configurator.hpp.
Referenced by cable_landing_mpc_parameters(), initMPCParametersObject(), and updateMPCParametersObjectCallback().
cable_takeoff_mpc_parameter_name_prefix
const std::string iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator::cable_takeoff_mpc_parameter_name_prefix = "/control/MPC/cable_takeoff_MPC_" private
Cable takeoff MPC parameter name prefixes.
Definition at line 135 of file trajectory_generator_node_configurator.hpp.
Referenced by declareMPCParameters(), initMPCParametersObject(), and updateMPCParametersObjectCallback().
cable_takeoff_mpc_parameters_
std::shared_ptr<control::MPCParameters> iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator::cable_takeoff_mpc_parameters_ private
MPC parameters object for the cable takeoff MPC.
Definition at line 115 of file trajectory_generator_node_configurator.hpp.
Referenced by cable_takeoff_mpc_parameters(), initMPCParametersObject(), and updateMPCParametersObjectCallback().
mpc_parameters_initialized_
bool iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator::mpc_parameters_initialized_ = false private
MPCParameters object initialized flag.
Definition at line 120 of file trajectory_generator_node_configurator.hpp.
Referenced by initMPCParametersObject(), and updateMPCParametersObjectCallback().
positional_mpc_parameter_name_prefix
const std::string iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator::positional_mpc_parameter_name_prefix = "/control/MPC/position_MPC_" private
Positional MPC parameter name prefixes.
Definition at line 125 of file trajectory_generator_node_configurator.hpp.
Referenced by declareMPCParameters(), initMPCParametersObject(), and updateMPCParametersObjectCallback().
positional_mpc_parameters_
std::shared_ptr<control::MPCParameters> iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator::positional_mpc_parameters_ private
MPC parameters object for the positional MPC.
Definition at line 105 of file trajectory_generator_node_configurator.hpp.
Referenced by initMPCParametersObject(), positional_mpc_parameters(), and updateMPCParametersObjectCallback().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/trajectory_generator_node/trajectory_generator_node_configurator.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/trajectory_generator_node/trajectory_generator_node_configurator.cpp