III-Drone: iii_drone::utils::History< T > Class Template Reference
iii_drone::utils::History< T > Class Template Reference
History class, storing the last N values of a type.
#include <history.hpp>
Public Types
typedef std::shared_ptr< History< T > > SharedPtr
Shared ptr type.
Public Member Functions
History (const size_t capacity=2)
Constructor.
History (const T &value, const size_t capacity=2)
Constructor from value.
History (const History< T > &other)
Copy constructor.
~History ()
Destructor.
History< T > & operator= (const History< T > &other)
Assignment operator.
History< T > & operator= (const T &value)
Assignment operator, stores the value as the latest value in the history.
History< T > & operator= (const std::vector< T > &values)
Assignment operator, overwrites the values.
std::vector< T > Load () const
Get the values.
void Store (const T &value)
Store the latest value.
operator T () const
Get the latest value.
T operator() () const
Get the latest value.
void operator() (const T &value)
Store the latest value.
T operator[] (const int index) const
Get the value at negative index.
size_t size () const
Get the size.
size_t capacity () const
Get the capacity.
bool empty () const
Returns true if the history is empty.
bool full () const
Returns true if the history is full.
void clear ()
Clear the history.
std::vector< T > vector () const
Get a copy of the history vector.
Private Attributes
std::vector< T > values_
The values.
std::shared_mutex mutex_
The mutex.
const size_t capacity_
The capacity.
Detailed Description
template<class T>
class iii_drone::utils::History< T >
History class, storing the last N values of a type.
Template Parameters
T The type of the history.
Definition at line 35 of file history.hpp.
Member Typedef Documentation
SharedPtr
template<class T > typedef std::shared_ptr<History<T> > iii_drone::utils::History< T >::SharedPtr
Shared ptr type.
Definition at line 330 of file history.hpp.
Constructor & Destructor Documentation
History() [1/3]
template<class T > iii_drone::utils::History< T >::History (const size_t capacity = 2) inline
Constructor.
Parameters
capacity The capacity of the history, default 2.
Definition at line 42 of file history.hpp.
                                           : capacity_(capacity) {
            COMPATIBLE_T_ASSERTION(T)
            values_.resize(0);
        }
References COMPATIBLE_T_ASSERTION, and iii_drone::utils::History< T >::values_.
History() [2/3]
template<class T > iii_drone::utils::History< T >::History (const T & value, const size_t capacity = 2) inline
Constructor from value.
Parameters
value The value.
capacity The capacity of the history, default 2.
Definition at line 55 of file history.hpp.
          : capacity_(capacity) {
            COMPATIBLE_T_ASSERTION(T)
            values_.resize(0);
            values_.push_back(value);
        }
References COMPATIBLE_T_ASSERTION, and iii_drone::utils::History< T >::values_.
History() [3/3]
template<class T > iii_drone::utils::History< T >::History (const History< T > & other) inline
Copy constructor.
Parameters
other The other history.
Definition at line 71 of file history.hpp.
                                          : capacity_(other.capacity()) {
            COMPATIBLE_T_ASSERTION(T)
            values_.resize(0);
            std::vector<T> values = other.Load();
            for (size_t i = 0; i < values.size(); i++) {
                values_.push_back(values[i]);
            }
        }
References COMPATIBLE_T_ASSERTION, iii_drone::utils::History< T >::Load(), and iii_drone::utils::History< T >::values_.
~History()
template<class T > iii_drone::utils::History< T >::~History () inline
Destructor.
Definition at line 88 of file history.hpp.
{ }
Member Function Documentation
capacity()
template<class T > size_t iii_drone::utils::History< T >::capacity () const inline
Get the capacity.
Definition at line 281 of file history.hpp.
{
            return capacity_;
        }
References iii_drone::utils::History< T >::capacity_.
Referenced by iii_drone::utils::History< T >::operator=().
clear()
template<class T > void iii_drone::utils::History< T >::clear () inline
Clear the history.
Definition at line 310 of file history.hpp.
                     {
            std::unique_lock<std::shared_mutex> lock(mutex_);
            values_.clear();
        }
References iii_drone::utils::History< T >::mutex_, and iii_drone::utils::History< T >::values_.
Referenced by iii_drone::perception::Powerline::Reset().
empty()
template<class T > bool iii_drone::utils::History< T >::empty () const inline
Returns true if the history is empty.
Returns
True if the history is empty.
Definition at line 290 of file history.hpp.
{
            std::shared_lock<std::shared_mutex> lock(mutex_);
            return values_.empty();
        }
References iii_drone::utils::History< T >::mutex_, and iii_drone::utils::History< T >::values_.
Referenced by iii_drone::perception::Powerline::drone_pose(), iii_drone::perception::Powerline::powerline_direction(), iii_drone::perception::PowerlineDirection::quaternion(), iii_drone::perception::PowerlineDirection::resetKalmanFilter(), iii_drone::perception::PowerlineDirection::ToPoseStampedMsg(), iii_drone::perception::PowerlineDirection::ToQuaternionStampedMsg(), and iii_drone::perception::PowerlineDirection::Update().
full()
template<class T > bool iii_drone::utils::History< T >::full () const inline
Returns true if the history is full.
Returns
True if the history is full.
Definition at line 301 of file history.hpp.
{
            std::shared_lock<std::shared_mutex> lock(mutex_);
            return values_.size() == capacity_;
        }
References iii_drone::utils::History< T >::capacity_, iii_drone::utils::History< T >::mutex_, and iii_drone::utils::History< T >::values_.
Referenced by iii_drone::perception::PowerlineDirection::Predict(), iii_drone::perception::Powerline::UpdateDirection(), iii_drone::perception::Powerline::UpdateLine(), and iii_drone::perception::Powerline::UpdateOdometry().
Load()
template<class T > std::vector< T > iii_drone::utils::History< T >::Load () const inline
Get the values.
Returns
The values vector.
Definition at line 165 of file history.hpp.
{
            std::shared_lock<std::shared_mutex> lock(mutex_);
            if (values_.size() == 0) {
                throw std::runtime_error("History is empty");
            }
            return values_;
        }
References iii_drone::utils::History< T >::mutex_, and iii_drone::utils::History< T >::values_.
Referenced by iii_drone::utils::History< T >::History(), and iii_drone::utils::History< T >::operator=().
operator T()
template<class T > iii_drone::utils::History< T >::operator T () const inline
Get the latest value.
Returns
The value.
Definition at line 197 of file history.hpp.
{
            std::shared_lock<std::shared_mutex> lock(mutex_);
            if (values_.size() == 0) {
                throw std::runtime_error("History is empty");
            }
            return values_[values_.size() - 1];
        }
operator()() [1/2]
template<class T > T iii_drone::utils::History< T >::operator() () const inline
Get the latest value.
Returns
The value.
Definition at line 213 of file history.hpp.
{
            std::shared_lock<std::shared_mutex> lock(mutex_);
            if (values_.size() == 0) {
                throw std::runtime_error("History is empty");
            }
            return values_[values_.size() - 1];
        }
References iii_drone::utils::History< T >::mutex_, and iii_drone::utils::History< T >::values_.
operator()() [2/2]
template<class T > void iii_drone::utils::History< T >::operator() (const T & value) inline
Store the latest value.
Parameters
value The value.
Definition at line 229 of file history.hpp.
{
            std::unique_lock<std::shared_mutex> lock(mutex_);
            if (values_.size() == capacity_) {
                values_.erase(values_.begin());
            }
            values_.push_back(value);
        }
References iii_drone::utils::History< T >::capacity_, iii_drone::utils::History< T >::mutex_, and iii_drone::utils::History< T >::values_.
operator=() [1/3]
template<class T > History< T > & iii_drone::utils::History< T >::operator= (const History< T > & other) inline
Assignment operator.
Parameters
other The other history.
Returns
The history.
Definition at line 97 of file history.hpp.
{
            if (this == &other) {
                return *this;
            }
            if (capacity_ != other.capacity()) {
                throw std::runtime_error("Cannot assign history with different capacity");
            }
            std::vector<T> values = other.Load();
            std::unique_lock<std::shared_mutex> lock(mutex_);
            values_.resize(0);
            for (size_t i = 0; i < values.size(); i++) {
                values_.push_back(values[i]);
            }
            return *this;
        }
References iii_drone::utils::History< T >::capacity(), iii_drone::utils::History< T >::capacity_, iii_drone::utils::History< T >::Load(), iii_drone::utils::History< T >::mutex_, and iii_drone::utils::History< T >::values_.
operator=() [2/3]
template<class T > History< T > & iii_drone::utils::History< T >::operator= (const std::vector< T > & values) inline
Assignment operator, overwrites the values.
Parameters
values The values.
Returns
The atomic.
Definition at line 141 of file history.hpp.
{
            std::unique_lock<std::shared_mutex> lock(mutex_);
            values_.resize(0);
            if (values.size() > capacity_) {
                for (size_t i = values.size() - capacity_; i < values.size(); i++) {
                    values_.push_back(values[i]);
                }
            } else {
                for (size_t i = 0; i < values.size(); i++) {
                    values_.push_back(values[i]);
                }
            }
            return *this;
        }
References iii_drone::utils::History< T >::capacity_, iii_drone::utils::History< T >::mutex_, and iii_drone::utils::History< T >::values_.
operator=() [3/3]
template<class T > History< T > & iii_drone::utils::History< T >::operator= (const T & value) inline
Assignment operator, stores the value as the latest value in the history.
Parameters
value The value.
Returns
The history.
Definition at line 127 of file history.hpp.
{
            Store(value);
            return *this;
        }
References iii_drone::utils::History< T >::Store().
operator[]()
template<class T > T iii_drone::utils::History< T >::operator[] (const int index) const inline
Get the value at negative index.
Parameters
index The index [-(size-1):0].
Returns
The value.
Definition at line 248 of file history.hpp.
{
            std::shared_lock<std::shared_mutex> lock(mutex_);
            if (values_.size() == 0) {
                throw std::runtime_error("History is empty");
            }
            int size = values_.size();
            if (index <= -size || index > 0) {
                throw std::runtime_error("Index out of range");
            }
            int i = size - 1 + index;
            return values_[i];
        }
References iii_drone::utils::History< T >::mutex_, iii_drone::utils::History< T >::size(), and iii_drone::utils::History< T >::values_.
size()
template<class T > size_t iii_drone::utils::History< T >::size () const inline
Get the size.
Definition at line 271 of file history.hpp.
{
            std::shared_lock<std::shared_mutex> lock(mutex_);
            return values_.size();
        }
References iii_drone::utils::History< T >::mutex_, and iii_drone::utils::History< T >::values_.
Referenced by iii_drone::utils::History< T >::operator[]().
Store()
template<class T > void iii_drone::utils::History< T >::Store (const T & value) inline
Store the latest value.
Parameters
value The value.
Definition at line 181 of file history.hpp.
{
            std::unique_lock<std::shared_mutex> lock(mutex_);
            if (values_.size() == capacity_) {
                values_.erase(values_.begin());
            }
            values_.push_back(value);
        }
References iii_drone::utils::History< T >::capacity_, iii_drone::utils::History< T >::mutex_, and iii_drone::utils::History< T >::values_.
Referenced by iii_drone::utils::History< T >::operator=(), iii_drone::control::TrajectoryGeneratorClient::serviceResultCallback(), and iii_drone::control::CombinedDroneAwarenessHandler::updateGroundAltitudeEstimate().
vector()
template<class T > std::vector< T > iii_drone::utils::History< T >::vector () const inline
Get a copy of the history vector.
Returns
The history vector.
Definition at line 321 of file history.hpp.
{
            std::shared_lock<std::shared_mutex> lock(mutex_);
            return values_;
        }
References iii_drone::utils::History< T >::mutex_, and iii_drone::utils::History< T >::values_.
Referenced by iii_drone::control::CombinedDroneAwarenessHandler::updateGroundAltitudeEstimate().
Member Data Documentation
capacity_
template<class T > const size_t iii_drone::utils::History< T >::capacity_ private
The capacity.
Definition at line 346 of file history.hpp.
Referenced by iii_drone::utils::History< T >::capacity(), iii_drone::utils::History< T >::full(), iii_drone::utils::History< T >::operator()(), iii_drone::utils::History< T >::operator=(), iii_drone::utils::History< T >::operator=(), and iii_drone::utils::History< T >::Store().
mutex_
template<class T > std::shared_mutex iii_drone::utils::History< T >::mutex_ mutable private
The mutex.
Definition at line 341 of file history.hpp.
Referenced by iii_drone::utils::History< T >::clear(), iii_drone::utils::History< T >::empty(), iii_drone::utils::History< T >::full(), iii_drone::utils::History< T >::Load(), iii_drone::utils::History< double >::operator double(), iii_drone::utils::History< T >::operator()(), iii_drone::utils::History< T >::operator()(), iii_drone::utils::History< T >::operator=(), iii_drone::utils::History< T >::operator=(), iii_drone::utils::History< T >::operator[](), iii_drone::utils::History< T >::size(), iii_drone::utils::History< T >::Store(), and iii_drone::utils::History< T >::vector().
values_
template<class T > std::vector<T> iii_drone::utils::History< T >::values_ private
The values.
Definition at line 336 of file history.hpp.
Referenced by iii_drone::utils::History< T >::clear(), iii_drone::utils::History< T >::empty(), iii_drone::utils::History< T >::full(), iii_drone::utils::History< T >::History(), iii_drone::utils::History< T >::History(), iii_drone::utils::History< T >::History(), iii_drone::utils::History< T >::Load(), iii_drone::utils::History< double >::operator double(), iii_drone::utils::History< T >::operator()(), iii_drone::utils::History< T >::operator()(), iii_drone::utils::History< T >::operator=(), iii_drone::utils::History< T >::operator=(), iii_drone::utils::History< T >::operator[](), iii_drone::utils::History< T >::size(), iii_drone::utils::History< T >::Store(), and iii_drone::utils::History< T >::vector().
The documentation for this class was generated from the following file:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/utils/history.hpp