III-Drone: iii_drone::adapters::ReferenceTrajectoryAdapter Class Reference
iii_drone::adapters::ReferenceTrajectoryAdapter Class Reference
Class for adapting the III-Drone-Core::ReferenceTrajectory to the III-Drone-Interfaces::ReferenceTrajectory.
#include <reference_trajectory_adapter.hpp>
Public Member Functions
ReferenceTrajectoryAdapter ()
Default constructor.
ReferenceTrajectoryAdapter (const iii_drone::control::ReferenceTrajectory &reference_trajectory)
Constructor from III-Drone-Core::ReferenceTrajectory.
ReferenceTrajectoryAdapter (const iii_drone_interfaces::msg::ReferenceTrajectory &reference_trajectory)
Constructor from III-Drone-Interfaces::ReferenceTrajectory msg.
ReferenceTrajectoryAdapter (const iii_drone_interfaces::msg::ReferenceTrajectory::SharedPtr &reference_trajectory)
Constructor from III-Drone-Interfaces::ReferenceTrajectory msg shared pointer.
ReferenceTrajectoryAdapter (const iii_drone::control::Reference &reference)
Constructor from a III-Drone-Core::Reference object.
iii_drone_interfaces::msg::ReferenceTrajectory ToMsg () const
Converts to msg.
nav_msgs::msg::Path ToPathMsg (std::string frame_id) const
Converts to Path msg.
iii_drone::control::ReferenceTrajectory reference_trajectory () const
ReferenceTrajectory getter.
Private Attributes
iii_drone::control::ReferenceTrajectory reference_trajectory_
Detailed Description
Class for adapting the III-Drone-Core::ReferenceTrajectory to the III-Drone-Interfaces::ReferenceTrajectory.
Definition at line 38 of file reference_trajectory_adapter.hpp.
Constructor & Destructor Documentation
ReferenceTrajectoryAdapter() [1/5]
ReferenceTrajectoryAdapter::ReferenceTrajectoryAdapter ()
Default constructor.
Definition at line 15 of file reference_trajectory_adapter.cpp.
: reference_trajectory_(iii_drone::control::ReferenceTrajectory()) {}
ReferenceTrajectoryAdapter() [2/5]
ReferenceTrajectoryAdapter::ReferenceTrajectoryAdapter (const iii_drone::control::ReferenceTrajectory & reference_trajectory)
Constructor from III-Drone-Core::ReferenceTrajectory.
Parameters
reference_trajectory The III-Drone-Core::ReferenceTrajectory.
Definition at line 17 of file reference_trajectory_adapter.cpp.
: reference_trajectory_(reference_trajectory) {}
ReferenceTrajectoryAdapter() [3/5]
ReferenceTrajectoryAdapter::ReferenceTrajectoryAdapter (const iii_drone_interfaces::msg::ReferenceTrajectory & reference_trajectory)
Constructor from III-Drone-Interfaces::ReferenceTrajectory msg.
Parameters
reference_trajectory The III-Drone-Interfaces::ReferenceTrajectory msg.
Definition at line 19 of file reference_trajectory_adapter.cpp.
{
    std::vector<iii_drone::control::Reference> references;
    for (auto reference_msg : msg.references) {
        references.push_back(ReferenceAdapter(reference_msg).reference());
    }
    reference_trajectory_ = iii_drone::control::ReferenceTrajectory(references);
}
References iii_drone::adapters::ReferenceAdapter::reference(), and reference_trajectory_.
ReferenceTrajectoryAdapter() [4/5]
ReferenceTrajectoryAdapter::ReferenceTrajectoryAdapter (const iii_drone_interfaces::msg::ReferenceTrajectory::SharedPtr & reference_trajectory)
Constructor from III-Drone-Interfaces::ReferenceTrajectory msg shared pointer.
Parameters
reference_trajectory The III-Drone-Interfaces::ReferenceTrajectory msg shared pointer.
Definition at line 31 of file reference_trajectory_adapter.cpp.
{
    std::vector<iii_drone::control::Reference> references;
    for (auto reference_msg : msg->references) {
        references.push_back(ReferenceAdapter(reference_msg).reference());
    }
    reference_trajectory_ = iii_drone::control::ReferenceTrajectory(references);
}
References iii_drone::adapters::ReferenceAdapter::reference(), and reference_trajectory_.
ReferenceTrajectoryAdapter() [5/5]
ReferenceTrajectoryAdapter::ReferenceTrajectoryAdapter (const iii_drone::control::Reference & reference)
Constructor from a III-Drone-Core::Reference object.
Parameters
reference The III-Drone-Core::Reference object.
Definition at line 43 of file reference_trajectory_adapter.cpp.
{
    std::vector<iii_drone::control::Reference> references = {reference};
    reference_trajectory_ = iii_drone::control::ReferenceTrajectory(references);
}
References reference_trajectory_.
Member Function Documentation
reference_trajectory()
iii_drone::control::ReferenceTrajectory ReferenceTrajectoryAdapter::reference_trajectory () const
ReferenceTrajectory getter.
Returns
The III-Drone-Core::ReferenceTrajectory.
Definition at line 71 of file reference_trajectory_adapter.cpp.
{
    return reference_trajectory_;
}
References reference_trajectory_.
ToMsg()
iii_drone_interfaces::msg::ReferenceTrajectory ReferenceTrajectoryAdapter::ToMsg () const
Converts to msg.
Returns
The III-Drone-Interfaces::ReferenceTrajectory msg.
Definition at line 51 of file reference_trajectory_adapter.cpp.
{
    iii_drone_interfaces::msg::ReferenceTrajectory msg;
    for (auto reference : reference_trajectory_.references()) {
        msg.references.push_back(ReferenceAdapter(reference).ToMsg());
    }
    return msg;
}
References reference_trajectory_, iii_drone::control::ReferenceTrajectory::references(), and iii_drone::adapters::ReferenceAdapter::ToMsg().
Referenced by iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNode::computeReferenceTrajectoryCallback().
ToPathMsg()
nav_msgs::msg::Path ReferenceTrajectoryAdapter::ToPathMsg (std::string frame_id) const
Converts to Path msg.
Parameters
frame_id The frame id of the Path msg.
Returns
The nav_msgs::msg::Path msg.
Definition at line 61 of file reference_trajectory_adapter.cpp.
{
    nav_msgs::msg::Path msg;
    for (auto reference : reference_trajectory_.references()) {
        msg.poses.push_back(ReferenceAdapter(reference).ToPoseStampedMsg(frame_id));
    }
    return msg;
}
References reference_trajectory_, iii_drone::control::ReferenceTrajectory::references(), and iii_drone::adapters::ReferenceAdapter::ToPoseStampedMsg().
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::publishFeedback(), iii_drone::control::maneuver::FlyToPositionManeuverServer::publishFeedback(), and iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNode::publishPlannedTrajectory().
Member Data Documentation
reference_trajectory_
iii_drone::control::ReferenceTrajectory iii_drone::adapters::ReferenceTrajectoryAdapter::reference_trajectory_ private
Definition at line 97 of file reference_trajectory_adapter.hpp.
Referenced by reference_trajectory(), ReferenceTrajectoryAdapter(), ReferenceTrajectoryAdapter(), ReferenceTrajectoryAdapter(), ToMsg(), and ToPathMsg().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/adapters/reference_trajectory_adapter.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/adapters/reference_trajectory_adapter.cpp