III-Drone: iii_drone::control::maneuver::HoverOnCableManeuverServer Class Reference
iii_drone::control::maneuver::HoverOnCableManeuverServer Class Reference
Class for serving hovering on a cable. When the hover on cable action is called, the drone will start hovering on the cable, and the action will succeed immediately. The maneuver scheduler will then keep hovering on the cable until a new maneuver is scheduled or the timeout elapses by the duration given in the hover action call. Exposes external methods for getting the reference and updating the hover reference parameters. Other maneuver server will use this server to generate references before a new maneuver is scheduled. Will fail if the drone is not on a cable.
#include <hover_on_cable_maneuver_server.hpp>
Public Member Functions
HoverOnCableManeuverServer (rclcpp::Node *node, CombinedDroneAwarenessHandler::SharedPtr combined_drone_awareness_handler, const std::string &action_name, unsigned int wait_for_execute_poll_ms, unsigned int evaluate_done_poll_ms, double default_target_z_velocity, double default_target_yaw_rate)
Constructor.
bool CanExecuteManeuver (const Maneuver &maneuver, const combined_drone_awareness_t &drone_awareness) const override
Whether the maneuver can be executed, will return false if the drone is not on the cable.
combined_drone_awareness_t ExpectedAwarenessAfterExecution (const Maneuver &maneuver)
The expected combined drone awareness after successful execution of the maneuver.
void RegisterOnFailCallback (std::function< void()> on_fail_callback)
Register a callback for when the target is not visible or the drone has drifted too far away from the target relative pose.
bool Update (double target_z_velocity, double target_yaw_rate)
Updates the hover on cable reference.
iii_drone::control::Reference GetReference (const iii_drone::control::State &state)
Gets the hover on cable reference. Will call the on fail callback if the drone is not on the cable.
Public Member Functions inherited from iii_drone::control::maneuver::ManeuverServer
ManeuverServer (rclcpp::Node *node, CombinedDroneAwarenessHandler::SharedPtr awareness_handler, const std::string &action_name, unsigned int wait_for_execute_poll_ms, unsigned int evaluate_done_poll_ms)
Constructor.
void Start (std::function< bool(Maneuver, bool &)> register_maneuver_function, std::function< bool(Maneuver)> update_manuever_function, std::function< bool(Maneuver)> cancel_maneuver_function, std::function< bool(Maneuver)> verify_maneuver_in_queue_function, std::function< bool(Maneuver)> verify_maneuver_active_function, std::function< void(Maneuver)> done_callback, ReferenceCallbackToken::SharedPtr reference_callback_token, std::map< iii_drone::control::maneuver::maneuver_type_t, std::shared_ptr< ManeuverServer > > registered_maneuvers)
Method to start the maneuver server. The maneuver server will reject any new goals until started.
void Stop ()
Method to stop the maneuver server. The maneuver server will reject any new goals until started.
std::string action_name () const
Action name getter.
bool running () const
Returns whether the maneuver server is running.
Private Types
using HoverOnCable = iii_drone_interfaces::action::HoverOnCable
Private Member Functions
maneuver_type_t maneuver_type () const override
Get the maneuver type (MANEUVER_TYPE_HOVER_ON_CABLE).
void startExecution (Maneuver &maneuver) override
Start the execution of the maneuver.
bool canCancel () override
Whether the maneuver can be canceled, will always return false as the action succeeds immediately.
iii_drone::control::Reference computeReference (const iii_drone::control::State &state) override
Compute the hover on cable reference. Will call the on fail callback if the drone is not on the cable.
bool hasSucceeded (Maneuver &maneuver) override
Whether the maneuver has succeeded, will always return true as the action succeeds immediately.
bool hasFailed (Maneuver &maneuver) override
Whether the maneuver has failed, will always return false as the action succeeds immediately.
void publishFeedback (Maneuver &maneuver) override
Will not do anything, as the action succeeds immediately and has no feedback.
void publishResultAndFinalize (Maneuver &maneuver, maneuver_result_type_t maneuver_result_type) override
Publish the result and finalize the maneuver based on the maneuver result type.
void registerReferenceCallbackOnSuccess (const Maneuver &maneuver) override
Register the hover on cable reference callback on success.
bool validateAwareness (combined_drone_awareness_t drone_awareness) const
Validates that the drone is on the cable.
Private Attributes
std::function< void()> on_fail_callback_
The on fail callback, called when the drone is not on the cable.
iii_drone::utils::Atomic< bool > has_on_fail_callback_
Has on fail callback flag.
double target_z_velocity_
The target z velocity.
double target_yaw_rate_
The target yaw rate.
Additional Inherited Members
Public Types inherited from iii_drone::control::maneuver::ManeuverServer
typedef std::shared_ptr< ManeuverServer > SharedPtr
Shared pointer type.
Protected Types inherited from iii_drone::control::maneuver::ManeuverServer
enum maneuver_result_type_t { MANEUVER_RESULT_TYPE_SUCCEED , MANEUVER_RESULT_TYPE_CANCEL , MANEUVER_RESULT_TYPE_ABORT }
Maneuver result type enum.
Protected Member Functions inherited from iii_drone::control::maneuver::ManeuverServer
const CombinedDroneAwarenessHandler::SharedPtr & awareness_handler () const
Combined drone awareness handler, accessible to derived classes through the protected method.
const iii_drone::utils::Atomic< iii_drone::control::maneuver::Maneuver > & current_maneuver () const
The currently executing maneuver, accessible to derived classes through the protected method.
rclcpp::Node * node () const
Node pointer getter.
std::map< iii_drone::control::maneuver::maneuver_type_t, std::shared_ptr< iii_drone::control::maneuver::ManeuverServer > > registered_maneuvers () const
Registered maneuvers map getter.
void registerCallback (const std::function< Reference(const State &)> &callback)
Registers a callback function for the reference. The callback function should be registered with the reference callback token.
template<typename ActionT >
void createServer ()
Creates the underlying action server.
Detailed Description
Class for serving hovering on a cable. When the hover on cable action is called, the drone will start hovering on the cable, and the action will succeed immediately. The maneuver scheduler will then keep hovering on the cable until a new maneuver is scheduled or the timeout elapses by the duration given in the hover action call. Exposes external methods for getting the reference and updating the hover reference parameters. Other maneuver server will use this server to generate references before a new maneuver is scheduled. Will fail if the drone is not on a cable.
Definition at line 55 of file hover_on_cable_maneuver_server.hpp.
Member Typedef Documentation
HoverOnCable
using iii_drone::control::maneuver::HoverOnCableManeuverServer::HoverOnCable = iii_drone_interfaces::action::HoverOnCable private
Definition at line 56 of file hover_on_cable_maneuver_server.hpp.
Constructor & Destructor Documentation
HoverOnCableManeuverServer()
HoverOnCableManeuverServer::HoverOnCableManeuverServer (rclcpp::Node * node, CombinedDroneAwarenessHandler::SharedPtr combined_drone_awareness_handler, const std::string & action_name, unsigned int wait_for_execute_poll_ms, unsigned int evaluate_done_poll_ms, double default_target_z_velocity, double default_target_yaw_rate)
Constructor.
Parameters
node Node pointer
combined_drone_awareness_handler Combined drone awareness handler pointer
action_name Action name
wait_for_execute_poll_ms Wait for execute poll milliseconds
evaluate_done_poll_ms Evaluate done poll milliseconds
default_target_z_velocity The default target z velocity
default_target_yaw_rate The default target yaw rate
Definition at line 15 of file hover_on_cable_maneuver_server.cpp.
  : ManeuverServer(
        node,
        combined_drone_awareness_handler,
        action_name,
        wait_for_execute_poll_ms,
        evaluate_done_poll_ms
    ),
    has_on_fail_callback_(false),
    target_z_velocity_(default_target_z_velocity),
    target_yaw_rate_(default_target_yaw_rate) {
    createServer<HoverOnCable>();
}
Member Function Documentation
canCancel()
bool HoverOnCableManeuverServer::canCancel () override private virtual
Whether the maneuver can be canceled, will always return false as the action succeeds immediately.
Returns
bool Whether the maneuver can be canceled.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 146 of file hover_on_cable_maneuver_server.cpp.
{
    return false;
}
CanExecuteManeuver()
bool HoverOnCableManeuverServer::CanExecuteManeuver (const Maneuver & maneuver, const combined_drone_awareness_t & drone_awareness) const override virtual
Whether the maneuver can be executed, will return false if the drone is not on the cable.
Parameters
maneuver The maneuver.
drone_awareness The drone awareness.
Returns
bool Whether the maneuver can be executed.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 39 of file hover_on_cable_maneuver_server.cpp.
        {
    if (maneuver.maneuver_type() != MANEUVER_TYPE_HOVER_ON_CABLE) {
        return false;
    }
    hover_on_cable_maneuver_params_t params(maneuver.maneuver_params());
    if (params.target_z_velocity < 0.0) {
        return false;
    }
    if (!validateAwareness(drone_awareness)) {
        return false;
    }
    return true;
}
References iii_drone::control::maneuver::Maneuver::maneuver_params(), iii_drone::control::maneuver::Maneuver::maneuver_type(), iii_drone::control::maneuver::MANEUVER_TYPE_HOVER_ON_CABLE, iii_drone::control::maneuver::hover_on_cable_maneuver_params_t::target_z_velocity, and validateAwareness().
computeReference()
Reference HoverOnCableManeuverServer::computeReference (const iii_drone::control::State & state) override private virtual
Compute the hover on cable reference. Will call the on fail callback if the drone is not on the cable.
Parameters
state The current state.
Returns
iii_drone::control::Reference The hover on cable reference.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 152 of file hover_on_cable_maneuver_server.cpp.
{
    return GetReference(state);
}
References GetReference().
ExpectedAwarenessAfterExecution()
combined_drone_awareness_t HoverOnCableManeuverServer::ExpectedAwarenessAfterExecution (const Maneuver & maneuver) virtual
The expected combined drone awareness after successful execution of the maneuver.
Parameters
maneuver Maneuver
Returns
combined_drone_awareness_t The expected combined drone awareness
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 62 of file hover_on_cable_maneuver_server.cpp.
{
    hover_on_cable_maneuver_params_t params(maneuver.maneuver_params());
    combined_drone_awareness_t awareness_after;
    awareness_after.armed = true;
    awareness_after.offboard = true;
    awareness_after.target_adapter = iii_drone::adapters::TargetAdapter(
        iii_drone::adapters::TARGET_TYPE_CABLE,
        0,
        "",
        iii_drone::types::transform_matrix_t()
    );
    awareness_after.target_position_known = true;
    awareness_after.drone_location = DRONE_LOCATION_ON_CABLE;
    return awareness_after;
}
References iii_drone::control::combined_drone_awareness_t::armed, iii_drone::control::combined_drone_awareness_t::drone_location, iii_drone::control::DRONE_LOCATION_ON_CABLE, iii_drone::control::maneuver::Maneuver::maneuver_params(), iii_drone::control::combined_drone_awareness_t::offboard, iii_drone::control::combined_drone_awareness_t::target_adapter, iii_drone::control::combined_drone_awareness_t::target_position_known, and iii_drone::adapters::TARGET_TYPE_CABLE.
GetReference()
Reference HoverOnCableManeuverServer::GetReference (const iii_drone::control::State & state)
Gets the hover on cable reference. Will call the on fail callback if the drone is not on the cable.
Parameters
state The current state, is not used.
Returns
The hover on cable reference.
Definition at line 106 of file hover_on_cable_maneuver_server.cpp.
{
    if (!validateAwareness(awareness_handler()->combined_drone_awareness())) {
        on_fail_callback_();
    }
    return Reference(
        {NAN,NAN,NAN},
        NAN,
        vector_t(NAN,NAN,target_z_velocity_),
        target_yaw_rate_,
        {NAN,NAN,NAN},
        NAN
    );
}
References iii_drone::control::maneuver::ManeuverServer::awareness_handler(), on_fail_callback_, target_yaw_rate_, target_z_velocity_, and validateAwareness().
Referenced by computeReference(), and registerReferenceCallbackOnSuccess().
hasFailed()
bool HoverOnCableManeuverServer::hasFailed (Maneuver & maneuver) override private virtual
Whether the maneuver has failed, will always return false as the action succeeds immediately.
Parameters
maneuver The maneuver.
Returns
bool Whether the maneuver has failed.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 164 of file hover_on_cable_maneuver_server.cpp.
{
    return false;
}
hasSucceeded()
bool HoverOnCableManeuverServer::hasSucceeded (Maneuver & maneuver) override private virtual
Whether the maneuver has succeeded, will always return true as the action succeeds immediately.
Parameters
maneuver The maneuver.
Returns
bool Whether the maneuver has succeeded.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 158 of file hover_on_cable_maneuver_server.cpp.
{
    return true;
}
maneuver_type()
maneuver_type_t HoverOnCableManeuverServer::maneuver_type () const override private virtual
Get the maneuver type (MANEUVER_TYPE_HOVER_ON_CABLE).
Returns
maneuver_type_t The maneuver type.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 125 of file hover_on_cable_maneuver_server.cpp.
{
    return MANEUVER_TYPE_HOVER_ON_CABLE;
}
References iii_drone::control::maneuver::MANEUVER_TYPE_HOVER_ON_CABLE.
publishFeedback()
void HoverOnCableManeuverServer::publishFeedback (Maneuver & maneuver) override private virtual
Will not do anything, as the action succeeds immediately and has no feedback.
Parameters
maneuver The maneuver.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 170 of file hover_on_cable_maneuver_server.cpp.
{
    // No feedback to publish
}
publishResultAndFinalize()
void HoverOnCableManeuverServer::publishResultAndFinalize (Maneuver & maneuver, maneuver_result_type_t maneuver_result_type) override private virtual
Publish the result and finalize the maneuver based on the maneuver result type.
Parameters
maneuver The maneuver.
maneuver_result_type The maneuver result type.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 176 of file hover_on_cable_maneuver_server.cpp.
  {
    auto goal_handle = std::static_pointer_cast<rclcpp_action::ServerGoalHandle<HoverOnCable>>(maneuver.goal_handle());
    auto result = std::make_shared<HoverOnCable::Result>();
    switch (maneuver_result_type){
        case MANEUVER_RESULT_TYPE_SUCCEED:
            goal_handle->succeed(result);
            break;
        case MANEUVER_RESULT_TYPE_ABORT:
            goal_handle->abort(result);
            awareness_handler()->ClearTarget();
            break;
        case MANEUVER_RESULT_TYPE_CANCEL:
            goal_handle->canceled(result);
            awareness_handler()->ClearTarget();
            break;
    }
}
References iii_drone::control::maneuver::ManeuverServer::awareness_handler(), iii_drone::control::CombinedDroneAwarenessHandler::ClearTarget(), iii_drone::control::maneuver::Maneuver::goal_handle(), iii_drone::control::maneuver::ManeuverServer::MANEUVER_RESULT_TYPE_ABORT, iii_drone::control::maneuver::ManeuverServer::MANEUVER_RESULT_TYPE_CANCEL, and iii_drone::control::maneuver::ManeuverServer::MANEUVER_RESULT_TYPE_SUCCEED.
RegisterOnFailCallback()
void HoverOnCableManeuverServer::RegisterOnFailCallback (std::function< void()> on_fail_callback)
Register a callback for when the target is not visible or the drone has drifted too far away from the target relative pose.
Parameters
on_fail_callback The on fail callback, called when the drone is not on the cable.
Definition at line 83 of file hover_on_cable_maneuver_server.cpp.
{
    on_fail_callback_ = on_fail_callback;
    has_on_fail_callback_ = true;
}
References has_on_fail_callback_, and on_fail_callback_.
registerReferenceCallbackOnSuccess()
void HoverOnCableManeuverServer::registerReferenceCallbackOnSuccess (const Maneuver & maneuver) override private virtual
Register the hover on cable reference callback on success.
Parameters
maneuver The maneuver.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 201 of file hover_on_cable_maneuver_server.cpp.
{
    registerCallback(
        std::bind(
            &HoverOnCableManeuverServer::GetReference,
            this,
            std::placeholders::_1
        )
    );
}
References GetReference(), and iii_drone::control::maneuver::ManeuverServer::registerCallback().
startExecution()
void HoverOnCableManeuverServer::startExecution (Maneuver & maneuver) override private virtual
Start the execution of the maneuver.
Parameters
maneuver The maneuver.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 131 of file hover_on_cable_maneuver_server.cpp.
{
    if (!has_on_fail_callback_) {
        throw std::runtime_error("No on fail callback registered for HoverOnCableManeuverServer");
    }
    hover_on_cable_maneuver_params_t params(maneuver.maneuver_params());
    target_z_velocity_ = params.target_z_velocity;
    target_yaw_rate_ = params.target_yaw_rate;
}
References has_on_fail_callback_, iii_drone::control::maneuver::Maneuver::maneuver_params(), iii_drone::control::maneuver::hover_on_cable_maneuver_params_t::target_yaw_rate, target_yaw_rate_, iii_drone::control::maneuver::hover_on_cable_maneuver_params_t::target_z_velocity, and target_z_velocity_.
Update()
bool HoverOnCableManeuverServer::Update (double target_z_velocity, double target_yaw_rate)
Updates the hover on cable reference.
Parameters
target_z_velocity The target z velocity.
target_yaw_rate The target yaw rate.
Returns
bool Whether the update was successful.
Definition at line 90 of file hover_on_cable_maneuver_server.cpp.
  {
    if (target_z_velocity < 0.0) {
        return false;
    }
    target_z_velocity_ = target_z_velocity;
    target_yaw_rate_ = target_yaw_rate;
    return true;
}
References target_yaw_rate_, and target_z_velocity_.
validateAwareness()
bool HoverOnCableManeuverServer::validateAwareness (combined_drone_awareness_t drone_awareness) const private
Validates that the drone is on the cable.
Parameters
drone_awareness The drone awareness.
Returns
bool Whether the state is valid.
Definition at line 213 of file hover_on_cable_maneuver_server.cpp.
{
    if (!drone_awareness.offboard) {
        return false;
    }
    if (!drone_awareness.armed) {
        return false;
    }
    if (!drone_awareness.on_cable()) {
        return false;
    }
    return true;
}
References iii_drone::control::combined_drone_awareness_t::armed, iii_drone::control::combined_drone_awareness_t::offboard, and iii_drone::control::combined_drone_awareness_t::on_cable().
Referenced by CanExecuteManeuver(), and GetReference().
Member Data Documentation
has_on_fail_callback_
iii_drone::utils::Atomic<bool> iii_drone::control::maneuver::HoverOnCableManeuverServer::has_on_fail_callback_ private
Has on fail callback flag.
Definition at line 220 of file hover_on_cable_maneuver_server.hpp.
Referenced by RegisterOnFailCallback(), and startExecution().
on_fail_callback_
std::function<void()> iii_drone::control::maneuver::HoverOnCableManeuverServer::on_fail_callback_ private
The on fail callback, called when the drone is not on the cable.
Definition at line 215 of file hover_on_cable_maneuver_server.hpp.
Referenced by GetReference(), and RegisterOnFailCallback().
target_yaw_rate_
double iii_drone::control::maneuver::HoverOnCableManeuverServer::target_yaw_rate_ private
The target yaw rate.
Definition at line 230 of file hover_on_cable_maneuver_server.hpp.
Referenced by GetReference(), startExecution(), and Update().
target_z_velocity_
double iii_drone::control::maneuver::HoverOnCableManeuverServer::target_z_velocity_ private
The target z velocity.
Definition at line 225 of file hover_on_cable_maneuver_server.hpp.
Referenced by GetReference(), startExecution(), and Update().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/maneuver/hover_on_cable_maneuver_server.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/maneuver/hover_on_cable_maneuver_server.cpp