III-Drone: iii_drone::adapters::TargetAdapter Class Reference
iii_drone::adapters::TargetAdapter Class Reference
Target adapter class.
#include <target_adapter.hpp>
Public Member Functions
TargetAdapter ()
Default constructor.
TargetAdapter (const TargetAdapter &other)
Copy constructor.
TargetAdapter (const iii_drone_interfaces::msg::Target &msg)
Constructor from msg.
TargetAdapter (target_type_t target_type, int target_id, const std::string &reference_frame_id, const iii_drone::types::transform_matrix_t &target_transform)
Constructor from members.
~TargetAdapter ()
Destructor.
iii_drone_interfaces::msg::Target ToMsg () const
Converts to a target message.
target_type_t target_type () const
Gets the target type.
int target_id () const
Gets the target id.
std::string reference_frame_id () const
Gets the reference frame id.
iii_drone::types::transform_matrix_t target_transform () const
Gets the target transform.
TargetAdapter & operator= (const TargetAdapter &other)
Assignment operator.
Private Attributes
target_type_t target_type_
Target type.
int target_id_
Target id.
std::string reference_frame_id_
Reference frame id.
iii_drone::types::transform_matrix_t target_transform_
Target transform.
Detailed Description
Target adapter class.
Definition at line 47 of file target_adapter.hpp.
Constructor & Destructor Documentation
TargetAdapter() [1/4]
TargetAdapter::TargetAdapter ()
Default constructor.
Definition at line 14 of file target_adapter.cpp.
{
    target_type_ = TARGET_TYPE_NONE;
    target_id_ = -1;
    reference_frame_id_ = "";
    target_transform_ = iii_drone::types::transform_matrix_t::Identity();
}
References reference_frame_id_, target_id_, target_transform_, target_type_, and iii_drone::adapters::TARGET_TYPE_NONE.
TargetAdapter() [2/4]
TargetAdapter::TargetAdapter (const TargetAdapter & other)
Copy constructor.
Parameters
other Other target adapter
Definition at line 23 of file target_adapter.cpp.
{
    target_type_ = other.target_type_;
    target_id_ = other.target_id_;
    reference_frame_id_ = other.reference_frame_id_;
    target_transform_ = other.target_transform_;
}
References reference_frame_id_, target_id_, target_transform_, and target_type_.
TargetAdapter() [3/4]
TargetAdapter::TargetAdapter (const iii_drone_interfaces::msg::Target & msg)
Constructor from msg.
Parameters
msg Target message
Definition at line 32 of file target_adapter.cpp.
{
    target_type_ = (target_type_t)target_msg.target_type;
    target_id_ = target_msg.target_id;
    reference_frame_id_ = target_msg.reference_frame_id;
    target_transform_ = iii_drone::types::transformMatrixFromTransformMsg(target_msg.target_transform);
}
References reference_frame_id_, target_id_, target_transform_, target_type_, and iii_drone::types::transformMatrixFromTransformMsg().
TargetAdapter() [4/4]
TargetAdapter::TargetAdapter (target_type_t target_type, int target_id, const std::string & reference_frame_id, const iii_drone::types::transform_matrix_t & target_transform)
Constructor from members.
Parameters
target_type Target type
target_id Target id
reference_frame_id Reference frame id
target_transform Target transform
Definition at line 41 of file target_adapter.cpp.
  {
    target_type_ = target_type;
    target_id_ = target_id;
    reference_frame_id_ = reference_frame_id;
    target_transform_ = target_transform;
}
References reference_frame_id(), reference_frame_id_, target_id(), target_id_, target_transform(), target_transform_, target_type(), and target_type_.
~TargetAdapter()
TargetAdapter::~TargetAdapter ()
Destructor.
Definition at line 55 of file target_adapter.cpp.
{
}
Member Function Documentation
operator=()
TargetAdapter & TargetAdapter::operator= (const TargetAdapter & other)
Assignment operator.
Parameters
other Other target adapter
Definition at line 88 of file target_adapter.cpp.
{
    target_type_ = other.target_type_;
    target_id_ = other.target_id_;
    reference_frame_id_ = other.reference_frame_id_;
    target_transform_ = other.target_transform_;
    return *this;
}
References reference_frame_id_, target_id_, target_transform_, and target_type_.
reference_frame_id()
std::string TargetAdapter::reference_frame_id () const
Gets the reference frame id.
Returns
Reference frame id
Definition at line 80 of file target_adapter.cpp.
{
    return reference_frame_id_;
}
References reference_frame_id_.
Referenced by TargetAdapter().
target_id()
int TargetAdapter::target_id () const
Gets the target id.
Returns
Target id
Definition at line 76 of file target_adapter.cpp.
{
    return target_id_;
}
References target_id_.
Referenced by iii_drone::control::CombinedDroneAwarenessHandler::ComputeTargetTransform(), TargetAdapter(), iii_drone::control::CombinedDroneAwarenessHandler::updateCombinedDroneAwarenessFromPowerline(), and iii_drone::control::CombinedDroneAwarenessHandler::updateCombinedDroneAwarenessFromTarget().
target_transform()
iii_drone::types::transform_matrix_t TargetAdapter::target_transform () const
Gets the target transform.
Returns
Target transform
Definition at line 84 of file target_adapter.cpp.
{
    return target_transform_;
}
References target_transform_.
Referenced by iii_drone::control::CombinedDroneAwarenessHandler::ComputeTargetTransform(), and TargetAdapter().
target_type()
target_type_t TargetAdapter::target_type () const
Gets the target type.
Returns
Target type
Definition at line 72 of file target_adapter.cpp.
{
    return target_type_;
}
References target_type_.
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::CanExecuteManeuver(), iii_drone::control::maneuver::HoverByObjectManeuverServer::CanExecuteManeuver(), iii_drone::control::CombinedDroneAwarenessHandler::ComputeTargetTransform(), iii_drone::control::maneuver::FlyToObjectManeuverServer::ExpectedAwarenessAfterExecution(), iii_drone::control::combined_drone_awareness_t::has_target(), iii_drone::control::CombinedDroneAwarenessHandler::publishMembers(), iii_drone::control::CombinedDroneAwarenessHandler::SetTarget(), TargetAdapter(), iii_drone::control::CombinedDroneAwarenessHandler::updateCombinedDroneAwarenessFromPowerline(), and iii_drone::control::CombinedDroneAwarenessHandler::updateCombinedDroneAwarenessFromTarget().
ToMsg()
iii_drone_interfaces::msg::Target TargetAdapter::ToMsg () const
Converts to a target message.
Parameters
target Target
Returns
Target message
Definition at line 59 of file target_adapter.cpp.
{
    iii_drone_interfaces::msg::Target target_msg;
    target_msg.target_type = target_type_;
    target_msg.target_id = target_id_;
    target_msg.reference_frame_id = reference_frame_id_;
    target_msg.target_transform = iii_drone::types::transformMsgFromTransformMatrix(target_transform_);
    return target_msg;
}
References reference_frame_id_, target_id_, target_transform_, target_type_, and iii_drone::types::transformMsgFromTransformMatrix().
Referenced by iii_drone::control::CombinedDroneAwarenessHandler::publishMembers().
Member Data Documentation
reference_frame_id_
std::string iii_drone::adapters::TargetAdapter::reference_frame_id_ private
Reference frame id.
Definition at line 146 of file target_adapter.hpp.
Referenced by operator=(), reference_frame_id(), TargetAdapter(), TargetAdapter(), TargetAdapter(), TargetAdapter(), and ToMsg().
target_id_
int iii_drone::adapters::TargetAdapter::target_id_ private
Target id.
Definition at line 141 of file target_adapter.hpp.
Referenced by operator=(), target_id(), TargetAdapter(), TargetAdapter(), TargetAdapter(), TargetAdapter(), and ToMsg().
target_transform_
iii_drone::types::transform_matrix_t iii_drone::adapters::TargetAdapter::target_transform_ private
Target transform.
Definition at line 151 of file target_adapter.hpp.
Referenced by operator=(), target_transform(), TargetAdapter(), TargetAdapter(), TargetAdapter(), TargetAdapter(), and ToMsg().
target_type_
target_type_t iii_drone::adapters::TargetAdapter::target_type_ private
Target type.
Definition at line 136 of file target_adapter.hpp.
Referenced by operator=(), target_type(), TargetAdapter(), TargetAdapter(), TargetAdapter(), TargetAdapter(), and ToMsg().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/adapters/target_adapter.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/adapters/target_adapter.cpp