III-Drone: iii_drone::perception::pl_mapper_node::PowerlineMapperNode Class Reference
iii_drone::perception::pl_mapper_node::PowerlineMapperNode Class Reference
Class for computing position of powerlines from mmWave data fused with powerline direction and odometry, using Kalman filtering.
#include <pl_mapper_node.hpp>
Public Member Functions
PowerlineMapperNode (const std::string &node_name="pl_mapper", const std::string &node_namespace="/perception/pl_mapper", const rclcpp::NodeOptions &options=rclcpp::NodeOptions())
Constructor.
Private Member Functions
void odometryCallback ()
Callback for fetching drone transform.
void mmWaveCallback (const sensor_msgs::msg::PointCloud2::SharedPtr msg)
Callback for mmwave data topic.
void plDirectionCallback (const geometry_msgs::msg::QuaternionStamped::SharedPtr msg)
Callback for powerline direction topic.
void publishPowerline () const
Publishes the powerline message.
void publishPoints (std::vector< iii_drone::types::point_t > points, rclcpp::Publisher< sensor_msgs::msg::PointCloud2 >::SharedPtr pub) const
Publishes point cloud data on a given publisher.
Private Attributes
PowerlineMapperConfigurator configurator_
Configurator for the node.
rclcpp::Subscription< geometry_msgs::msg::QuaternionStamped >::SharedPtr pl_direction_sub_
Subscriber for powerline direction.
rclcpp::Subscription< sensor_msgs::msg::PointCloud2 >::SharedPtr mmwave_sub_
Subscriber for mmwave point cloud data.
rclcpp::Publisher< iii_drone_interfaces::msg::Powerline >::SharedPtr powerline_pub_
Publisher for powerline message.
rclcpp::Publisher< sensor_msgs::msg::PointCloud2 >::SharedPtr points_est_pub_
Publisher for estimated powerline points.
rclcpp::Publisher< sensor_msgs::msg::PointCloud2 >::SharedPtr transformed_points_pub_
Publisher for transformed mmwave points.
rclcpp::Publisher< sensor_msgs::msg::PointCloud2 >::SharedPtr projected_points_pub_
Publisher for mmwave points projected onto plane.
std::shared_ptr< tf2_ros::TransformListener > transform_listener_ {nullptr}
std::shared_ptr< tf2_ros::Buffer > tf_buffer_
rclcpp::TimerBase::SharedPtr drone_tf_timer_ {nullptr}
Timer for fetching drone transform.
Powerline powerline_
The powerline object holding the tracked powerlines.
iii_drone::types::rotation_matrix_t R_drone_to_mmw_
Rotation matrix from drone to mmWave frame.
iii_drone::types::vector_t v_drone_to_mmw_
Translation vector from drone to mmWave frame.
iii_drone::types::quaternion_t pl_direction_
Direction of detected powerline.
Detailed Description
Class for computing position of powerlines from mmWave data fused with powerline direction and odometry, using Kalman filtering.
Definition at line 74 of file pl_mapper_node.hpp.
Constructor & Destructor Documentation
PowerlineMapperNode()
PowerlineMapperNode::PowerlineMapperNode (const std::string & node_name = "pl_mapper", const std::string & node_namespace = "/perception/pl_mapper", const rclcpp::NodeOptions & options = rclcpp::NodeOptions()) explicit
Constructor.
Parameters
node_name Name of the node, default is "pl_mapper"
node_namespace Namespace of the node, default is "/perception/pl_mapper"
options Node options, default is rclcpp::NodeOptions()
Definition at line 15 of file pl_mapper_node.cpp.
  : rclcpp::Node(
        node_name,
        node_namespace,
        options
    ),
    configurator_(this),
    powerline_(configurator_.powerline_parameters()) {
    tf_buffer_ = std::make_shared<tf2_ros::Buffer>(this->get_clock());
    transform_listener_ = std::make_shared<tf2_ros::TransformListener>(*tf_buffer_);
    powerline_.tf_buffer() = tf_buffer_;
    pl_direction_sub_ = this->create_subscription<geometry_msgs::msg::QuaternionStamped>(
        "/perception/pl_dir_computer/powerline_direction_quat",
        10,
        std::bind(
            &PowerlineMapperNode::plDirectionCallback,
            this,
            std::placeholders::_1
        )
    );
    mmwave_sub_ = this->create_subscription<sensor_msgs::msg::PointCloud2>(
        "/sensor/mmwave/pcl",
        10,
        std::bind(
            &PowerlineMapperNode::mmWaveCallback,
            this,
            std::placeholders::_1
        )
    );
    powerline_pub_ = this->create_publisher<iii_drone_interfaces::msg::Powerline>(
        "powerline",
        10
    );
    points_est_pub_ = this->create_publisher<sensor_msgs::msg::PointCloud2>(
        "points_est",
        10
    );
    transformed_points_pub_ = this->create_publisher<sensor_msgs::msg::PointCloud2>(
        "transformed_points",
        10
    );
    projected_points_pub_ = this->create_publisher<sensor_msgs::msg::PointCloud2>(
        "projected_points",
        10
    );
    geometry_msgs::msg::TransformStamped mmw_tf;
    rclcpp::Rate tf_poll_rate(std::chrono::milliseconds(500));
    while(true) {
        try {
            mmw_tf = tf_buffer_->lookupTransform(
                configurator_.drone_frame_id(),
                configurator_.mmwave_frame_id(),
                tf2::TimePointZero
            );
            break;
        } catch(tf2::TransformException & ex) {
            RCLCPP_DEBUG(
                this->get_logger(),
                "Could not get mmWave transform, frame drone to iwr6843_frame, trying again..."
            );
        }
        tf_poll_rate.sleep();
    }
    std::chrono::milliseconds sleep_ms(configurator_.init_sleep_time_ms());
    rclcpp::Rate init_sleep_rate(sleep_ms);
    init_sleep_rate.sleep();
    // Call on_timer function every second
    std::chrono::milliseconds odom_callback_ms(configurator_.odometry_callback_period_ms());
    drone_tf_timer_ = this->create_wall_timer(
        odom_callback_ms,
        std::bind(
            &PowerlineMapperNode::odometryCallback,
            this
        )
    );
    quaternion_t mmw_quat = quaternionFromTransformMsg(mmw_tf.transform);
    R_drone_to_mmw_ = quatToMat(mmw_quat);
    v_drone_to_mmw_ = vectorFromTransformMsg(mmw_tf.transform);
}
References configurator_, iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::drone_frame_id(), drone_tf_timer_, iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::init_sleep_time_ms(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::mmwave_frame_id(), mmwave_sub_, mmWaveCallback(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::odometry_callback_period_ms(), odometryCallback(), pl_direction_sub_, plDirectionCallback(), points_est_pub_, powerline_, powerline_pub_, projected_points_pub_, iii_drone::types::quaternionFromTransformMsg(), iii_drone::math::quatToMat(), R_drone_to_mmw_, iii_drone::perception::Powerline::tf_buffer(), tf_buffer_, transform_listener_, transformed_points_pub_, v_drone_to_mmw_, and iii_drone::types::vectorFromTransformMsg().
Member Function Documentation
mmWaveCallback()
void PowerlineMapperNode::mmWaveCallback (const sensor_msgs::msg::PointCloud2::SharedPtr msg) private
Callback for mmwave data topic.
Parameters
msg Message containing the mmwave point cloud data
Returns
void
Definition at line 150 of file pl_mapper_node.cpp.
{
    iii_drone::adapters::PointCloudAdapter pcl_adapter(msg);
    std::vector<point_t> transformed_points;
    std::vector<point_t> projected_points;
    std::vector<point_t> pcl_points = pcl_adapter.points();
    for (size_t i = 0; i < pcl_points.size(); i++) {
        auto line = SingleLine(
            -1,
            pcl_points[i],
            pl_direction_,
            configurator_.mmwave_frame_id(),
            tf_buffer_,
            configurator_.powerline_parameters()
        );
        if(!line.IsInFOVStrict()) {
            continue;
        }
        geometry_msgs::msg::PointStamped pt;
        pt.header.frame_id = msg->header.frame_id;
        pt.point = pointMsgFromPoint(pcl_points[i]);
        pt = tf_buffer_->transform(
            pt,
            configurator_.drone_frame_id()
        );
        point_t transformed_point = pointFromPointMsg(pt.point);
        point_t projected_point = powerline_.UpdateLine(transformed_point);
        transformed_points.push_back(transformed_point);
        projected_points.push_back(projected_point);
    }
    publishPoints(
        transformed_points,
        transformed_points_pub_
    );
    publishPoints(
        projected_points,
        projected_points_pub_
    );
    powerline_.CleanupLines();
    powerline_.ComputeInterLinePositions();
}
References iii_drone::perception::Powerline::CleanupLines(), iii_drone::perception::Powerline::ComputeInterLinePositions(), configurator_, iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::drone_frame_id(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::mmwave_frame_id(), pl_direction_, iii_drone::types::pointFromPointMsg(), iii_drone::types::pointMsgFromPoint(), iii_drone::adapters::PointCloudAdapter::points(), powerline_, iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::powerline_parameters(), projected_points_pub_, publishPoints(), tf_buffer_, transformed_points_pub_, and iii_drone::perception::Powerline::UpdateLine().
Referenced by PowerlineMapperNode().
odometryCallback()
void PowerlineMapperNode::odometryCallback () private
Callback for fetching drone transform.
Returns
void
Definition at line 119 of file pl_mapper_node.cpp.
{
    geometry_msgs::msg::TransformStamped tf;
    try {
        tf = tf_buffer_->lookupTransform(
            configurator_.world_frame_id(),
            configurator_.drone_frame_id(),
            tf2::TimePointZero
        );
    } catch(tf2::TransformException & ex) {
        RCLCPP_WARN(
            this->get_logger(),
            "Could not get odometry transform, frame drone to world"
        );
        return;
    }
    pose_t drone_pose = poseFromTransformMsg(tf.transform);
    powerline_.UpdateOdometry(drone_pose);
    publishPowerline();
}
References configurator_, iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::drone_frame_id(), iii_drone::types::poseFromTransformMsg(), powerline_, publishPowerline(), tf_buffer_, iii_drone::perception::Powerline::UpdateOdometry(), and iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::world_frame_id().
Referenced by PowerlineMapperNode().
plDirectionCallback()
void PowerlineMapperNode::plDirectionCallback (const geometry_msgs::msg::QuaternionStamped::SharedPtr msg) private
Callback for powerline direction topic.
Parameters
msg Message containing the powerline direction
Returns
void
Definition at line 210 of file pl_mapper_node.cpp.
{
    quaternion_t quat = quaternionFromQuaternionMsg(msg->quaternion);
    pl_direction_ = quat;
    powerline_.UpdateDirection(quat);
}
References pl_direction_, powerline_, iii_drone::types::quaternionFromQuaternionMsg(), and iii_drone::perception::Powerline::UpdateDirection().
Referenced by PowerlineMapperNode().
publishPoints()
void PowerlineMapperNode::publishPoints (std::vector< iii_drone::types::point_t > points, rclcpp::Publisher< sensor_msgs::msg::PointCloud2 >::SharedPtr pub) const private
Publishes point cloud data on a given publisher.
Parameters
points Vector of points to publish
pub Publisher to publish on
Returns
void
Definition at line 230 of file pl_mapper_node.cpp.
        {
    iii_drone::adapters::PointCloudAdapter pcl_adapter(
        powerline_.stamp(),
        configurator_.drone_frame_id(),
        points
    );
    pub->publish(pcl_adapter.ToMsg());
}
References configurator_, iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::drone_frame_id(), powerline_, iii_drone::perception::Powerline::stamp(), and iii_drone::adapters::PointCloudAdapter::ToMsg().
Referenced by mmWaveCallback().
publishPowerline()
void PowerlineMapperNode::publishPowerline () const private
Publishes the powerline message.
Returns
void
Definition at line 219 of file pl_mapper_node.cpp.
{
    auto msg = powerline_.ToAdapter(true).ToMsg();
    iii_drone::adapters::PointCloudAdapter pcl_adapter = powerline_.ToPointCloudAdapter(true);
    powerline_pub_->publish(msg);
    points_est_pub_->publish(pcl_adapter.ToMsg());
}
References points_est_pub_, powerline_, powerline_pub_, iii_drone::perception::Powerline::ToAdapter(), iii_drone::adapters::PointCloudAdapter::ToMsg(), iii_drone::adapters::PowerlineAdapter::ToMsg(), and iii_drone::perception::Powerline::ToPointCloudAdapter().
Referenced by odometryCallback().
Member Data Documentation
configurator_
PowerlineMapperConfigurator iii_drone::perception::pl_mapper_node::PowerlineMapperNode::configurator_ private
Configurator for the node.
Definition at line 94 of file pl_mapper_node.hpp.
Referenced by mmWaveCallback(), odometryCallback(), PowerlineMapperNode(), and publishPoints().
drone_tf_timer_
rclcpp::TimerBase::SharedPtr iii_drone::perception::pl_mapper_node::PowerlineMapperNode::drone_tf_timer_ {nullptr} private
Timer for fetching drone transform.
Definition at line 132 of file pl_mapper_node.hpp.
{nullptr};
Referenced by PowerlineMapperNode().
mmwave_sub_
rclcpp::Subscription<sensor_msgs::msg::PointCloud2>::SharedPtr iii_drone::perception::pl_mapper_node::PowerlineMapperNode::mmwave_sub_ private
Subscriber for mmwave point cloud data.
Definition at line 104 of file pl_mapper_node.hpp.
Referenced by PowerlineMapperNode().
pl_direction_
iii_drone::types::quaternion_t iii_drone::perception::pl_mapper_node::PowerlineMapperNode::pl_direction_ private
Direction of detected powerline.
Definition at line 152 of file pl_mapper_node.hpp.
Referenced by mmWaveCallback(), and plDirectionCallback().
pl_direction_sub_
rclcpp::Subscription<geometry_msgs::msg::QuaternionStamped>::SharedPtr iii_drone::perception::pl_mapper_node::PowerlineMapperNode::pl_direction_sub_ private
Subscriber for powerline direction.
Definition at line 99 of file pl_mapper_node.hpp.
Referenced by PowerlineMapperNode().
points_est_pub_
rclcpp::Publisher<sensor_msgs::msg::PointCloud2>::SharedPtr iii_drone::perception::pl_mapper_node::PowerlineMapperNode::points_est_pub_ private
Publisher for estimated powerline points.
Definition at line 114 of file pl_mapper_node.hpp.
Referenced by PowerlineMapperNode(), and publishPowerline().
powerline_
Powerline iii_drone::perception::pl_mapper_node::PowerlineMapperNode::powerline_ private
The powerline object holding the tracked powerlines.
Definition at line 137 of file pl_mapper_node.hpp.
Referenced by mmWaveCallback(), odometryCallback(), plDirectionCallback(), PowerlineMapperNode(), publishPoints(), and publishPowerline().
powerline_pub_
rclcpp::Publisher<iii_drone_interfaces::msg::Powerline>::SharedPtr iii_drone::perception::pl_mapper_node::PowerlineMapperNode::powerline_pub_ private
Publisher for powerline message.
Definition at line 109 of file pl_mapper_node.hpp.
Referenced by PowerlineMapperNode(), and publishPowerline().
projected_points_pub_
rclcpp::Publisher<sensor_msgs::msg::PointCloud2>::SharedPtr iii_drone::perception::pl_mapper_node::PowerlineMapperNode::projected_points_pub_ private
Publisher for mmwave points projected onto plane.
Definition at line 124 of file pl_mapper_node.hpp.
Referenced by mmWaveCallback(), and PowerlineMapperNode().
R_drone_to_mmw_
iii_drone::types::rotation_matrix_t iii_drone::perception::pl_mapper_node::PowerlineMapperNode::R_drone_to_mmw_ private
Rotation matrix from drone to mmWave frame.
Definition at line 142 of file pl_mapper_node.hpp.
Referenced by PowerlineMapperNode().
tf_buffer_
std::shared_ptr<tf2_ros::Buffer> iii_drone::perception::pl_mapper_node::PowerlineMapperNode::tf_buffer_ private
Definition at line 127 of file pl_mapper_node.hpp.
Referenced by mmWaveCallback(), odometryCallback(), and PowerlineMapperNode().
transform_listener_
std::shared_ptr<tf2_ros::TransformListener> iii_drone::perception::pl_mapper_node::PowerlineMapperNode::transform_listener_ {nullptr} private
Definition at line 126 of file pl_mapper_node.hpp.
{nullptr};
Referenced by PowerlineMapperNode().
transformed_points_pub_
rclcpp::Publisher<sensor_msgs::msg::PointCloud2>::SharedPtr iii_drone::perception::pl_mapper_node::PowerlineMapperNode::transformed_points_pub_ private
Publisher for transformed mmwave points.
Definition at line 119 of file pl_mapper_node.hpp.
Referenced by mmWaveCallback(), and PowerlineMapperNode().
v_drone_to_mmw_
iii_drone::types::vector_t iii_drone::perception::pl_mapper_node::PowerlineMapperNode::v_drone_to_mmw_ private
Translation vector from drone to mmWave frame.
Definition at line 147 of file pl_mapper_node.hpp.
Referenced by PowerlineMapperNode().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/perception/pl_mapper_node/pl_mapper_node.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/perception/pl_mapper_node/pl_mapper_node.cpp