III-Drone: iii_drone::adapters::ProjectionPlaneAdapter Class Reference
iii_drone::adapters::ProjectionPlaneAdapter Class Reference
ProjectionPlane message adapter class.
#include <projection_plane_adapter.hpp>
Public Member Functions
ProjectionPlaneAdapter ()
Default constructor.
ProjectionPlaneAdapter (const iii_drone_interfaces::msg::ProjectionPlane &projection_plane_msg)
Constructor from msg.
ProjectionPlaneAdapter (const iii_drone::types::vector_t &normal, const iii_drone::types::point_t &origin)
Constructor from members.
ProjectionPlaneAdapter (const iii_drone::types::plane_t &projection_plane)
Constructor from projection plane.
void UpdateFromMsg (const iii_drone_interfaces::msg::ProjectionPlane &projection_plane_msg)
Updates the projection plane adapter object from a message.
const iii_drone_interfaces::msg::ProjectionPlane ToMsg () const
Converts the projection plane adapter object to a message.
const iii_drone::types::plane_t projection_plane () const
Projection plane getter.
Private Attributes
iii_drone::types::plane_t projection_plane_
Projection plane.
Detailed Description
ProjectionPlane message adapter class.
Definition at line 35 of file projection_plane_adapter.hpp.
Constructor & Destructor Documentation
ProjectionPlaneAdapter() [1/4]
ProjectionPlaneAdapter::ProjectionPlaneAdapter ()
Default constructor.
Definition at line 14 of file projection_plane_adapter.cpp.
{
    projection_plane_.normal = vector_t(1.0, 0.0, 0.0);
    projection_plane_.p = point_t(0.0, 0.0, 0.0);
}
References iii_drone::types::plane_t::normal, iii_drone::types::plane_t::p, and projection_plane_.
ProjectionPlaneAdapter() [2/4]
ProjectionPlaneAdapter::ProjectionPlaneAdapter (const iii_drone_interfaces::msg::ProjectionPlane & projection_plane_msg)
Constructor from msg.
Parameters
projection_plane_msg ProjectionPlane message.
Definition at line 21 of file projection_plane_adapter.cpp.
{
    UpdateFromMsg(projection_plane_msg);
}
References UpdateFromMsg().
ProjectionPlaneAdapter() [3/4]
ProjectionPlaneAdapter::ProjectionPlaneAdapter (const iii_drone::types::vector_t & normal, const iii_drone::types::point_t & origin)
Constructor from members.
Parameters
normal The normal vector.
origin The origin point.
Definition at line 27 of file projection_plane_adapter.cpp.
  {
    projection_plane_.normal = normal;
    projection_plane_.p = point;
}
References iii_drone::types::plane_t::normal, iii_drone::types::plane_t::p, and projection_plane_.
ProjectionPlaneAdapter() [4/4]
ProjectionPlaneAdapter::ProjectionPlaneAdapter (const iii_drone::types::plane_t & projection_plane)
Constructor from projection plane.
Parameters
projection_plane The projection plane.
Definition at line 37 of file projection_plane_adapter.cpp.
{
    projection_plane_ = projection_plane;
}
References projection_plane(), and projection_plane_.
Member Function Documentation
projection_plane()
const iii_drone::types::plane_t ProjectionPlaneAdapter::projection_plane () const
Projection plane getter.
Definition at line 73 of file projection_plane_adapter.cpp.
{
    return projection_plane_;
}
References projection_plane_.
Referenced by ProjectionPlaneAdapter(), and iii_drone::adapters::PowerlineAdapter::UpdateFromMsg().
ToMsg()
const iii_drone_interfaces::msg::ProjectionPlane ProjectionPlaneAdapter::ToMsg () const
Converts the projection plane adapter object to a message.
Definition at line 59 of file projection_plane_adapter.cpp.
{
    iii_drone_interfaces::msg::ProjectionPlane msg{};
    msg.normal.x = projection_plane_.normal.x();
    msg.normal.y = projection_plane_.normal.y();
    msg.normal.z = projection_plane_.normal.z();
    msg.point.x = projection_plane_.p.x();
    msg.point.y = projection_plane_.p.y();
    msg.point.z = projection_plane_.p.z();
    return msg;
}
References iii_drone::types::plane_t::normal, iii_drone::types::plane_t::p, and projection_plane_.
Referenced by iii_drone::adapters::PowerlineAdapter::ToMsg().
UpdateFromMsg()
void ProjectionPlaneAdapter::UpdateFromMsg (const iii_drone_interfaces::msg::ProjectionPlane & projection_plane_msg)
Updates the projection plane adapter object from a message.
Parameters
projection_plane_msg ProjectionPlane message.
Definition at line 43 of file projection_plane_adapter.cpp.
{
    projection_plane_.normal = vector_t(
        projection_plane_msg.normal.x,
        projection_plane_msg.normal.y,
        projection_plane_msg.normal.z
    );
    projection_plane_.p = point_t(
        projection_plane_msg.point.x,
        projection_plane_msg.point.y,
        projection_plane_msg.point.z
    );
}
References iii_drone::types::plane_t::normal, iii_drone::types::plane_t::p, and projection_plane_.
Referenced by ProjectionPlaneAdapter().
Member Data Documentation
projection_plane_
iii_drone::types::plane_t iii_drone::adapters::ProjectionPlaneAdapter::projection_plane_ private
Projection plane.
Definition at line 89 of file projection_plane_adapter.hpp.
Referenced by projection_plane(), ProjectionPlaneAdapter(), ProjectionPlaneAdapter(), ProjectionPlaneAdapter(), ToMsg(), and UpdateFromMsg().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/adapters/projection_plane_adapter.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/adapters/projection_plane_adapter.cpp