III-Drone: iii_drone::perception::SingleLine Class Reference
iii_drone::perception::SingleLine Class Reference
SingleLine class for pose estimation of a single powerline.
#include <single_line.hpp>
Classes
struct kf_est_t
Kalman Filter estimate struct.
Public Member Functions
SingleLine (const SingleLine &other)
Copy constructor.
SingleLine (const int &id, const geometry_msgs::msg::Pose &pose, const std::shared_ptr< tf2_ros::Buffer > &tf_buffer, const std::shared_ptr< PowerlineParameters > &parameters)
Constructor from Pose msg.
SingleLine (const int &id, const iii_drone::types::point_t &position, const iii_drone::types::quaternion_t &quaternion, const std::shared_ptr< tf2_ros::Buffer > &tf_buffer, const std::shared_ptr< PowerlineParameters > &parameters)
Constructor from position and quaternion.
SingleLine (const int &id, const iii_drone::types::point_t &position, const iii_drone::types::quaternion_t &quaternion, const std::string &frame_id, const std::shared_ptr< tf2_ros::Buffer > &tf_buffer, const std::shared_ptr< PowerlineParameters > &parameters)
Constructor from position, quaternion and frame_id.
SingleLine (const iii_drone::adapters::SingleLineAdapter &adapter, const std::shared_ptr< tf2_ros::Buffer > &tf_buffer, const std::shared_ptr< PowerlineParameters > &parameters)
Constructor from SingleLineAdapter.
const iii_drone::adapters::SingleLineAdapter ToAdapter () const
Converts to SingleLineAdapter.
void OverwriteStamp (const rclcpp::Time &stamp)
Overwrites the timestamp.
bool IsAlive ()
Returns whether the line is alive, i.e. whether it is not in the FOV or alive_cnt_ is above alive_cnt_low_thresh_. If in FOV, alive_cnt_ is decremented.
bool IsVisible () const
Returns whether the line is visible, i.e. whether it is in the FOV.
bool IsInFOV (const iii_drone::types::point_t &position, const float min_point_dist, const float max_point_dist, const float view_cone_slope) const
Returns whether the position is in the FOV.
bool IsInFOV () const
Returns whether the line is in FOV, non strict.
bool IsInFOVStrict () const
Returns whether the line is in FOV, using the strict parameters.
void Update (const iii_drone::types::point_t &projected_position)
Runs the Kalman Filter update step and increments the alive counter.
void Predict (const iii_drone::types::vector_t &delta_drone_position, const iii_drone::types::quaternion_t &delta_drone_quat, const iii_drone::types::plane_t &projection_plane)
Runs the Kalman Filter predict step.
void SetPosition (const iii_drone::types::point_t &position)
Sets the position and updates the Kalman Filter estimates.
void SetDirection (const iii_drone::types::quaternion_t &quaternion)
Sets the direction.
const iii_drone::types::point_t position () const
position getter.
int id () const
Id getter.
rclcpp::Time stamp () const
Stamp getter.
std::string frame_id () const
frame_id getter.
iii_drone::types::quaternion_t quaternion () const
quaternion getter.
iii_drone::types::point_t projected_position () const
projected_position getter.
std::shared_ptr< tf2_ros::Buffer > tf_buffer () const
tf_buffer getter.
std::shared_ptr< PowerlineParameters > parameters () const
parameters getter.
int alive_cnt () const
Alive counter getter.
float state_est (const int &i) const
State estimate getter.
float var_est (const int &i) const
Variance estimate getter.
SingleLine & operator= (const SingleLine &other)
Assignment operator overload.
Private Member Functions
void resetKalmanFilter ()
Resets the Kalman Filter estimates.
Private Attributes
iii_drone::utils::Timestamp stamp_
The timestamp.
std::string frame_id_
The frame id.
std::shared_ptr< tf2_ros::Buffer > tf_buffer_
The tf buffer.
std::shared_ptr< PowerlineParameters > parameters_
The powerline parameters.
std::shared_mutex mutex_
The mutex.
kf_est_t estimates [3]
The Kalman Filter estimates.
iii_drone::types::point_t position_
The powerline position.
iii_drone::types::point_t projected_position_
The projected powerline position.
iii_drone::types::quaternion_t quaternion_
The powerline quaternion.
int id_
The line id.
int alive_cnt_
The line alive counter.
Detailed Description
SingleLine class for pose estimation of a single powerline.
Definition at line 58 of file single_line.hpp.
Constructor & Destructor Documentation
SingleLine() [1/5]
SingleLine::SingleLine (const SingleLine & other)
Copy constructor.
Parameters
other The other SingleLine object.
Definition at line 15 of file single_line.cpp.
                                               : mutex_() {
    id_ = other.id();
    position_ = other.position();
    projected_position_ = other.projected_position();
    quaternion_ = other.quaternion();
    frame_id_ = other.frame_id();
    alive_cnt_ = other.alive_cnt();
    stamp_ = other.stamp();
    tf_buffer_ = other.tf_buffer();
    parameters_ = other.parameters();
    for (int i = 0; i < 3; i++) {
        estimates[i].state_est = other.state_est(i);
        estimates[i].var_est = other.var_est(i);
    }
}
References alive_cnt(), alive_cnt_, estimates, frame_id(), frame_id_, id(), id_, parameters(), parameters_, position(), position_, projected_position(), projected_position_, quaternion(), quaternion_, stamp(), stamp_, state_est(), iii_drone::perception::SingleLine::kf_est_t::state_est, tf_buffer(), tf_buffer_, var_est(), and iii_drone::perception::SingleLine::kf_est_t::var_est.
SingleLine() [2/5]
SingleLine::SingleLine (const int & id, const geometry_msgs::msg::Pose & pose, const std::shared_ptr< tf2_ros::Buffer > & tf_buffer, const std::shared_ptr< PowerlineParameters > & parameters)
Constructor from Pose msg.
Parameters
id The id of the line.
pose The pose msg.
tf_buffer The tf buffer.
parameters The powerline parameters.
Definition at line 35 of file single_line.cpp.
  : tf_buffer_(tf_buffer), parameters_(parameters), mutex_() {
    id_ = id;
    position_ = pointFromPointMsg(pose.position);
    projected_position_ = position_;
    quaternion_ = quaternionFromQuaternionMsg(pose.orientation);
    frame_id_ = parameters_->drone_frame_id();
    alive_cnt_ = (parameters_->alive_cnt_low_thresh() + parameters_->alive_cnt_high_thresh()) / 2;
    resetKalmanFilter();
}
References alive_cnt_, frame_id_, id(), id_, parameters_, iii_drone::types::pointFromPointMsg(), position_, projected_position_, quaternion_, iii_drone::types::quaternionFromQuaternionMsg(), and resetKalmanFilter().
SingleLine() [3/5]
SingleLine::SingleLine (const int & id, const iii_drone::types::point_t & position, const iii_drone::types::quaternion_t & quaternion, const std::shared_ptr< tf2_ros::Buffer > & tf_buffer, const std::shared_ptr< PowerlineParameters > & parameters)
Constructor from position and quaternion.
Parameters
id The id of the line.
position The position.
quaternion The quaternion.
tf_buffer The tf buffer.
parameters The powerline parameters.
Definition at line 54 of file single_line.cpp.
  : tf_buffer_(tf_buffer), parameters_(parameters), mutex_() {
    id_ = id;
    position_ = position;
    projected_position_ = position_;
    quaternion_ = quaternion;
    frame_id_ = parameters_->drone_frame_id();
    alive_cnt_ = (parameters_->alive_cnt_low_thresh() + parameters_->alive_cnt_high_thresh()) / 2;
    resetKalmanFilter();
}
References alive_cnt_, frame_id_, id(), id_, parameters_, position(), position_, projected_position_, quaternion(), quaternion_, and resetKalmanFilter().
SingleLine() [4/5]
SingleLine::SingleLine (const int & id, const iii_drone::types::point_t & position, const iii_drone::types::quaternion_t & quaternion, const std::string & frame_id, const std::shared_ptr< tf2_ros::Buffer > & tf_buffer, const std::shared_ptr< PowerlineParameters > & parameters)
Constructor from position, quaternion and frame_id.
Parameters
id The id of the line.
position The position.
quaternion The quaternion.
frame_id The frame id.
tf_buffer The tf buffer.
parameters The powerline parameters.
Definition at line 74 of file single_line.cpp.
  : tf_buffer_(tf_buffer), parameters_(parameters), mutex_() {
    id_ = id;
    position_ = position;
    projected_position_ = position_;
    quaternion_ = quaternion;
    frame_id_ = frame_id;
    alive_cnt_ = (parameters_->alive_cnt_low_thresh() + parameters_->alive_cnt_high_thresh()) / 2;
    resetKalmanFilter();
}
References alive_cnt_, frame_id(), frame_id_, id(), id_, parameters_, position(), position_, projected_position_, quaternion(), quaternion_, and resetKalmanFilter().
SingleLine() [5/5]
SingleLine::SingleLine (const iii_drone::adapters::SingleLineAdapter & adapter, const std::shared_ptr< tf2_ros::Buffer > & tf_buffer, const std::shared_ptr< PowerlineParameters > & parameters)
Constructor from SingleLineAdapter.
Parameters
adapter The SingleLineAdapter.
tf_buffer The tf buffer.
parameters The powerline parameters.
Definition at line 95 of file single_line.cpp.
  : tf_buffer_(tf_buffer), parameters_(parameters), mutex_() {
    id_ = adapter.id();
    position_ = adapter.position();
    projected_position_ = adapter.projected_position();
    quaternion_ = adapter.quaternion();
    alive_cnt_ = (parameters_->alive_cnt_low_thresh() + parameters_->alive_cnt_high_thresh()) / 2;
    resetKalmanFilter();
}
References alive_cnt_, iii_drone::adapters::SingleLineAdapter::id(), id_, parameters_, iii_drone::adapters::SingleLineAdapter::position(), position_, iii_drone::adapters::SingleLineAdapter::projected_position(), projected_position_, iii_drone::adapters::SingleLineAdapter::quaternion(), quaternion_, and resetKalmanFilter().
Member Function Documentation
alive_cnt()
int SingleLine::alive_cnt () const
Alive counter getter.
Definition at line 389 of file single_line.cpp.
{
    std::shared_lock<std::shared_mutex> lock(mutex_);
    return alive_cnt_;
}
References alive_cnt_, and mutex_.
Referenced by operator=(), and SingleLine().
frame_id()
std::string SingleLine::frame_id () const
frame_id getter.
Definition at line 355 of file single_line.cpp.
{
    return frame_id_;
}
References frame_id_.
Referenced by operator=(), SingleLine(), and SingleLine().
id()
int SingleLine::id () const
Id getter.
Definition at line 341 of file single_line.cpp.
{
    std::shared_lock<std::shared_mutex> lock(mutex_);
    return id_;
}
References id_, and mutex_.
Referenced by operator=(), SingleLine(), SingleLine(), SingleLine(), and SingleLine().
IsAlive()
bool SingleLine::IsAlive ()
Returns whether the line is alive, i.e. whether it is not in the FOV or alive_cnt_ is above alive_cnt_low_thresh_. If in FOV, alive_cnt_ is decremented.
Returns
bool Whether the line is alive.
Definition at line 136 of file single_line.cpp.
{
    std::shared_lock<std::shared_mutex> lock(mutex_);
    if (IsInFOV() && --alive_cnt_ <= parameters_->alive_cnt_low_thresh()) {
        return false;
    } else {
        return true;
    }
}
References IsInFOV(), and mutex_.
IsInFOV() [1/2]
bool SingleLine::IsInFOV () const
Returns whether the line is in FOV, non strict.
Returns
bool Whether the line is in FOV, non strict.
Definition at line 189 of file single_line.cpp.
{
    std::shared_lock<std::shared_mutex> lock(mutex_);
    geometry_msgs::msg::PointStamped point_stamped;
    point_stamped.header.frame_id = frame_id_;
    point_stamped.point = pointMsgFromPoint(position_);
    geometry_msgs::msg::PointStamped mmwave_point_stamped = tf_buffer_->transform(
        point_stamped,
        parameters_->mmwave_frame_id()
    );
    point_t mmwave_point = pointFromPointMsg(mmwave_point_stamped.point);
    return IsInFOV(
        mmwave_point,
        parameters_->min_point_dist(),
        parameters_->max_point_dist(),
        parameters_->view_cone_slope()
    );
}
References frame_id_, IsInFOV(), mutex_, parameters_, iii_drone::types::pointFromPointMsg(), iii_drone::types::pointMsgFromPoint(), position_, and tf_buffer_.
Referenced by IsAlive(), IsInFOV(), IsInFOVStrict(), and ToAdapter().
IsInFOV() [2/2]
bool SingleLine::IsInFOV (const iii_drone::types::point_t & position, const float min_point_dist, const float max_point_dist, const float view_cone_slope) const
Returns whether the position is in the FOV.
Parameters
position The position.
min_point_dist The minimum distance of the position.
max_point_dist The maximum distance of the position.
view_cone_slope The slope of the view cone.
Returns
bool Whether the position is in the FOV.
Definition at line 159 of file single_line.cpp.
        {
    bool in_FOV = true;
    float dist = position.norm();
    in_FOV &= dist <= max_point_dist;
    in_FOV &= dist >= min_point_dist;
    if (parameters_->simulation()) {
        float yz_dist = sqrt(position(1)*position(1)+position(2)*position(2));
        in_FOV &= position(0) > view_cone_slope*yz_dist;
    } else {
        float xz_dist = sqrt(position(0)*position(0)+position(2)*position(2));
        in_FOV &= position(1) > view_cone_slope*xz_dist;
    }
    return in_FOV;
}
References parameters_, and position().
IsInFOVStrict()
bool SingleLine::IsInFOVStrict () const
Returns whether the line is in FOV, using the strict parameters.
Returns
bool Whether the line is in FOV, strict.
Definition at line 215 of file single_line.cpp.
{
    std::shared_lock<std::shared_mutex> lock(mutex_);
    geometry_msgs::msg::PointStamped point_stamped;
    point_stamped.header.frame_id = frame_id_;
    point_stamped.point = pointMsgFromPoint(position_);
    geometry_msgs::msg::PointStamped mmwave_point_stamped = tf_buffer_->transform(
        point_stamped,
        parameters_->mmwave_frame_id()
    );
    point_t mmwave_point = pointFromPointMsg(mmwave_point_stamped.point);
    return IsInFOV(
        mmwave_point,
        parameters_->strict_min_point_dist(),
        parameters_->strict_max_point_dist(),
        parameters_->strict_view_cone_slope()
    );
}
References frame_id_, IsInFOV(), mutex_, parameters_, iii_drone::types::pointFromPointMsg(), iii_drone::types::pointMsgFromPoint(), position_, and tf_buffer_.
IsVisible()
bool SingleLine::IsVisible () const
Returns whether the line is visible, i.e. whether it is in the FOV.
Returns
bool Whether the line is visible.
Definition at line 151 of file single_line.cpp.
{
    std::shared_lock<std::shared_mutex> lock(mutex_);
    return alive_cnt_ >= parameters_->alive_cnt_high_thresh();
}
References alive_cnt_, mutex_, and parameters_.
operator=()
SingleLine & SingleLine::operator= (const SingleLine & other)
Assignment operator overload.
Definition at line 424 of file single_line.cpp.
{
    if (this != &other) {
        id_ = other.id();
        position_ = other.position();
        projected_position_ = other.projected_position();
        quaternion_ = other.quaternion();
        frame_id_ = other.frame_id();
        alive_cnt_ = other.alive_cnt();
        stamp_ = other.stamp();
        tf_buffer_ = other.tf_buffer();
        parameters_ = other.parameters();
        for (int i = 0; i < 3; i++) {
            estimates[i].state_est = other.state_est(i);
            estimates[i].var_est = other.var_est(i);
        }
    }
    return *this;
}
References alive_cnt(), alive_cnt_, estimates, frame_id(), frame_id_, id(), id_, parameters(), parameters_, position(), position_, projected_position(), projected_position_, quaternion(), quaternion_, stamp(), stamp_, state_est(), iii_drone::perception::SingleLine::kf_est_t::state_est, tf_buffer(), tf_buffer_, var_est(), and iii_drone::perception::SingleLine::kf_est_t::var_est.
OverwriteStamp()
void SingleLine::OverwriteStamp (const rclcpp::Time & stamp)
Overwrites the timestamp.
Parameters
stamp The new timestamp.
Definition at line 130 of file single_line.cpp.
{
    stamp_ = stamp;
}
References stamp(), and stamp_.
parameters()
std::shared_ptr< PowerlineParameters > SingleLine::parameters () const
parameters getter.
Definition at line 383 of file single_line.cpp.
{
    return parameters_;
}
References parameters_.
Referenced by operator=(), and SingleLine().
position()
const point_t SingleLine::position () const
position getter.
Definition at line 333 of file single_line.cpp.
{
    std::shared_lock<std::shared_mutex> lock(mutex_);
    return position_;
}
References mutex_, and position_.
Referenced by IsInFOV(), operator=(), SetPosition(), SingleLine(), SingleLine(), and SingleLine().
Predict()
void SingleLine::Predict (const iii_drone::types::vector_t & delta_drone_position, const iii_drone::types::quaternion_t & delta_drone_quat, const iii_drone::types::plane_t & projection_plane)
Runs the Kalman Filter predict step.
Parameters
delta_position The delta drone position.
delta_quat The delta drone quaternion orientation.
projection_plane The projection plane.
Definition at line 273 of file single_line.cpp.
  {
    std::unique_lock<std::shared_mutex> lock(mutex_);
    rotation_matrix_t R = quatToMat(delta_drone_quat);
    vector_t projected_delta_drone_position = projectPointOnPlane(
        delta_drone_position,
        projection_plane
    );
    position_ = (R * position_) - projected_delta_drone_position;
    for (int i = 0; i < 3; i++) {
        estimates[i].state_est = position_(i);
        estimates[i].var_est += parameters_->kf_q();
    }
    lock.unlock();
    stamp_.Update();
}
References estimates, mutex_, parameters_, position_, iii_drone::math::projectPointOnPlane(), iii_drone::math::quatToMat(), stamp_, iii_drone::perception::SingleLine::kf_est_t::state_est, iii_drone::utils::Timestamp::Update(), and iii_drone::perception::SingleLine::kf_est_t::var_est.
projected_position()
point_t SingleLine::projected_position () const
projected_position getter.
Definition at line 369 of file single_line.cpp.
{
    std::shared_lock<std::shared_mutex> lock(mutex_);
    return projected_position_;
}
References mutex_, and projected_position_.
Referenced by operator=(), SingleLine(), and Update().
quaternion()
quaternion_t SingleLine::quaternion () const
quaternion getter.
Definition at line 361 of file single_line.cpp.
{
    std::shared_lock<std::shared_mutex> lock(mutex_);
    return quaternion_;
}
References mutex_, and quaternion_.
Referenced by operator=(), SetDirection(), SingleLine(), SingleLine(), and SingleLine().
resetKalmanFilter()
void SingleLine::resetKalmanFilter () private
Resets the Kalman Filter estimates.
Definition at line 413 of file single_line.cpp.
{
    for (int i = 0; i < 3; i++) {
        estimates[i].state_est = position_(i);
        estimates[i].var_est = 0.01;
    }
}
References estimates, position_, iii_drone::perception::SingleLine::kf_est_t::state_est, and iii_drone::perception::SingleLine::kf_est_t::var_est.
Referenced by SingleLine(), SingleLine(), SingleLine(), and SingleLine().
SetDirection()
void SingleLine::SetDirection (const iii_drone::types::quaternion_t & quaternion)
Sets the direction.
Parameters
quaternion The new quaternion.
Definition at line 321 of file single_line.cpp.
{
    std::unique_lock<std::shared_mutex> lock(mutex_);
    quaternion_ = quaternion;
    lock.unlock();
    stamp_.Update();
}
References mutex_, quaternion(), quaternion_, stamp_, and iii_drone::utils::Timestamp::Update().
SetPosition()
void SingleLine::SetPosition (const iii_drone::types::point_t & position)
Sets the position and updates the Kalman Filter estimates.
Parameters
position The new position.
Definition at line 302 of file single_line.cpp.
{
    std::unique_lock<std::shared_mutex> lock(mutex_);
    position_ = position;
    for (int i = 0; i < 3; i++) {
        estimates[i].state_est = position_(i);
        estimates[i].var_est += parameters_->kf_q();
    }
    lock.unlock();
    stamp_.Update();
}
References estimates, mutex_, parameters_, position(), position_, stamp_, iii_drone::perception::SingleLine::kf_est_t::state_est, iii_drone::utils::Timestamp::Update(), and iii_drone::perception::SingleLine::kf_est_t::var_est.
stamp()
rclcpp::Time SingleLine::stamp () const
Stamp getter.
Definition at line 349 of file single_line.cpp.
{
    return stamp_;
}
References stamp_.
Referenced by operator=(), OverwriteStamp(), and SingleLine().
state_est()
float SingleLine::state_est (const int & i) const
State estimate getter.
Definition at line 397 of file single_line.cpp.
{
    std::shared_lock<std::shared_mutex> lock(mutex_);
    return estimates[i].state_est;
}
References estimates, mutex_, and iii_drone::perception::SingleLine::kf_est_t::state_est.
Referenced by operator=(), and SingleLine().
tf_buffer()
std::shared_ptr< tf2_ros::Buffer > SingleLine::tf_buffer () const
tf_buffer getter.
Definition at line 377 of file single_line.cpp.
{
    return tf_buffer_;
}
References tf_buffer_.
Referenced by operator=(), and SingleLine().
ToAdapter()
const iii_drone::adapters::SingleLineAdapter SingleLine::ToAdapter () const
Converts to SingleLineAdapter.
Returns
iii_drone::adapters::SingleLineAdapter The SingleLineAdapter.
Definition at line 112 of file single_line.cpp.
{
    std::shared_lock<std::shared_mutex> lock(mutex_);
    iii_drone::adapters::SingleLineAdapter adapter(
        stamp_,
        frame_id_,
        id_,
        position_,
        projected_position_,
        quaternion_,
        IsInFOV()
    );
    return adapter;
}
References frame_id_, id_, IsInFOV(), mutex_, position_, projected_position_, quaternion_, and stamp_.
Update()
void SingleLine::Update (const iii_drone::types::point_t & projected_position)
Runs the Kalman Filter update step and increments the alive counter.
Parameters
position The new projected position.
Definition at line 239 of file single_line.cpp.
{
    std::unique_lock<std::shared_mutex> lock(mutex_);
    projected_position_ = projected_position;
    for (int i = 0; i < 3; i++) {
        float y_bar = projected_position(i) - estimates[i].state_est;
        float s = estimates[i].var_est + parameters_->kf_r();
        float k = estimates[i].var_est / s;
        estimates[i].state_est += k*y_bar;
        estimates[i].var_est *= 1-k;
        position_(i) = estimates[i].state_est;
    }
    alive_cnt_ += 2;
    if (alive_cnt_ > parameters_->alive_cnt_ceiling()) {
        alive_cnt_ = parameters_->alive_cnt_ceiling();
    }
    lock.unlock();
    stamp_.Update();
}
References alive_cnt_, estimates, mutex_, parameters_, position_, projected_position(), projected_position_, stamp_, iii_drone::perception::SingleLine::kf_est_t::state_est, iii_drone::utils::Timestamp::Update(), and iii_drone::perception::SingleLine::kf_est_t::var_est.
var_est()
float SingleLine::var_est (const int & i) const
Variance estimate getter.
Definition at line 405 of file single_line.cpp.
{
    std::shared_lock<std::shared_mutex> lock(mutex_);
    return estimates[i].var_est;
}
References estimates, mutex_, and iii_drone::perception::SingleLine::kf_est_t::var_est.
Referenced by operator=(), and SingleLine().
Member Data Documentation
alive_cnt_
int iii_drone::perception::SingleLine::alive_cnt_ private
The line alive counter.
Definition at line 354 of file single_line.hpp.
Referenced by alive_cnt(), IsVisible(), operator=(), SingleLine(), SingleLine(), SingleLine(), SingleLine(), SingleLine(), and Update().
estimates
kf_est_t iii_drone::perception::SingleLine::estimates[3] private
The Kalman Filter estimates.
Definition at line 324 of file single_line.hpp.
Referenced by operator=(), Predict(), resetKalmanFilter(), SetPosition(), SingleLine(), state_est(), Update(), and var_est().
frame_id_
std::string iii_drone::perception::SingleLine::frame_id_ private
The frame id.
Definition at line 294 of file single_line.hpp.
Referenced by frame_id(), IsInFOV(), IsInFOVStrict(), operator=(), SingleLine(), SingleLine(), SingleLine(), SingleLine(), and ToAdapter().
id_
int iii_drone::perception::SingleLine::id_ private
The line id.
Definition at line 349 of file single_line.hpp.
Referenced by id(), operator=(), SingleLine(), SingleLine(), SingleLine(), SingleLine(), SingleLine(), and ToAdapter().
mutex_
std::shared_mutex iii_drone::perception::SingleLine::mutex_ mutable private
The mutex.
Definition at line 309 of file single_line.hpp.
Referenced by alive_cnt(), id(), IsAlive(), IsInFOV(), IsInFOVStrict(), IsVisible(), position(), Predict(), projected_position(), quaternion(), SetDirection(), SetPosition(), state_est(), ToAdapter(), Update(), and var_est().
parameters_
std::shared_ptr<PowerlineParameters> iii_drone::perception::SingleLine::parameters_ private
The powerline parameters.
Definition at line 304 of file single_line.hpp.
Referenced by IsInFOV(), IsInFOV(), IsInFOVStrict(), IsVisible(), operator=(), parameters(), Predict(), SetPosition(), SingleLine(), SingleLine(), SingleLine(), SingleLine(), SingleLine(), and Update().
position_
iii_drone::types::point_t iii_drone::perception::SingleLine::position_ private
The powerline position.
Definition at line 334 of file single_line.hpp.
Referenced by IsInFOV(), IsInFOVStrict(), operator=(), position(), Predict(), resetKalmanFilter(), SetPosition(), SingleLine(), SingleLine(), SingleLine(), SingleLine(), SingleLine(), ToAdapter(), and Update().
projected_position_
iii_drone::types::point_t iii_drone::perception::SingleLine::projected_position_ private
The projected powerline position.
Definition at line 339 of file single_line.hpp.
Referenced by operator=(), projected_position(), SingleLine(), SingleLine(), SingleLine(), SingleLine(), SingleLine(), ToAdapter(), and Update().
quaternion_
iii_drone::types::quaternion_t iii_drone::perception::SingleLine::quaternion_ private
The powerline quaternion.
Definition at line 344 of file single_line.hpp.
Referenced by operator=(), quaternion(), SetDirection(), SingleLine(), SingleLine(), SingleLine(), SingleLine(), SingleLine(), and ToAdapter().
stamp_
iii_drone::utils::Timestamp iii_drone::perception::SingleLine::stamp_ private
The timestamp.
Definition at line 289 of file single_line.hpp.
Referenced by operator=(), OverwriteStamp(), Predict(), SetDirection(), SetPosition(), SingleLine(), stamp(), ToAdapter(), and Update().
tf_buffer_
std::shared_ptr<tf2_ros::Buffer> iii_drone::perception::SingleLine::tf_buffer_ private
The tf buffer.
Definition at line 299 of file single_line.hpp.
Referenced by IsInFOV(), IsInFOVStrict(), operator=(), SingleLine(), and tf_buffer().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/perception/single_line.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/perception/single_line.cpp