III-Drone: iii_drone::adapters::SingleLineAdapter Class Reference
iii_drone::adapters::SingleLineAdapter Class Reference
SingleLine message adapter class.
#include <single_line_adapter.hpp>
Public Member Functions
SingleLineAdapter ()
Default constructor.
SingleLineAdapter (const iii_drone_interfaces::msg::SingleLine &msg)
Constructor from msg.
SingleLineAdapter (const rclcpp::Time &stamp, const std::string &frame_id, const int &id, const iii_drone::types::point_t &position, const iii_drone::types::point_t &projected_position, const iii_drone::types::quaternion_t &quaternion, const bool &in_fov)
Constructor from members.
SingleLineAdapter (const rclcpp::Time &stamp, const std::string &frame_id, const int &id, const geometry_msgs::msg::Pose &msg, const bool &in_fov)
Constructor from pose msg.
SingleLineAdapter (const int &id, const geometry_msgs::msg::PoseStamped &msg, const bool &in_fov)
Constructor from PoseStamped msg.
const iii_drone_interfaces::msg::SingleLine ToMsg () const
Converts to SingleLine msg.
const geometry_msgs::msg::Pose ToPoseMsg () const
Converts to Pose msg.
const geometry_msgs::msg::PoseStamped ToPoseStampedMsg () const
Converts to PoseStamped msg.
const rclcpp::Time & stamp () const
Timestamp getter.
const std::string & frame_id () const
Frame id getter.
const int & id () const
Id getter.
const iii_drone::types::point_t & position () const
position getter.
const iii_drone::types::point_t & projected_position () const
Projected position getter.
const iii_drone::types::quaternion_t & quaternion () const
Quaternion getter.
const iii_drone::types::pose_t ToPose () const
Pose getter.
const bool & in_fov () const
In FOV getter.
Private Attributes
rclcpp::Time stamp_
The timestamp.
std::string frame_id_
The frame id.
int id_
The id of the line.
iii_drone::types::point_t position_
The position of the line.
iii_drone::types::point_t projected_position_
The position of the line projected onto the projection plane.
iii_drone::types::quaternion_t quaternion_
The quaternion of the line.
bool in_fov_
Whether the line is in the FOV.
Detailed Description
SingleLine message adapter class.
Definition at line 38 of file single_line_adapter.hpp.
Constructor & Destructor Documentation
SingleLineAdapter() [1/5]
SingleLineAdapter::SingleLineAdapter ()
Default constructor.
Definition at line 13 of file single_line_adapter.cpp.
{
    stamp_ = rclcpp::Clock().now();
    frame_id_ = "drone";
    id_ = -1;
    position_ = iii_drone::types::point_t::Zero();
    projected_position_ = iii_drone::types::point_t::Zero();
    quaternion_ = iii_drone::types::quaternion_t::Zero();
    quaternion_(0) = 1.0;
    in_fov_ = false;
}
References frame_id_, id_, in_fov_, position_, projected_position_, quaternion_, and stamp_.
SingleLineAdapter() [2/5]
SingleLineAdapter::SingleLineAdapter (const iii_drone_interfaces::msg::SingleLine & msg)
Constructor from msg.
Parameters
msg The SingleLine
Definition at line 26 of file single_line_adapter.cpp.
{
    stamp_ = msg.header.stamp;
    frame_id_ = msg.header.frame_id;
    id_ = msg.id;
    position_ = iii_drone::types::pointFromPoseMsg(msg.pose);
    projected_position_ = iii_drone::types::pointFromPointMsg(msg.projected_position);
    quaternion_ = iii_drone::types::quaternionFromPoseMsg(msg.pose);
    in_fov_ = msg.in_field_of_view;
}
References frame_id_, id_, in_fov_, iii_drone::types::pointFromPointMsg(), iii_drone::types::pointFromPoseMsg(), position_, projected_position_, quaternion_, iii_drone::types::quaternionFromPoseMsg(), and stamp_.
SingleLineAdapter() [3/5]
SingleLineAdapter::SingleLineAdapter (const rclcpp::Time & stamp, const std::string & frame_id, const int & id, const iii_drone::types::point_t & position, const iii_drone::types::point_t & projected_position, const iii_drone::types::quaternion_t & quaternion, const bool & in_fov)
Constructor from members.
Parameters
stamp The timestamp.
frame_id The frame id.
id The id of the line.
position The position of the line.
projected_position The position of the line projected onto the projection plane.
quaternion The quaternion of the line.
in_fov Whether the line is in the FOV.
Definition at line 38 of file single_line_adapter.cpp.
  {
    stamp_ = stamp;
    frame_id_ = frame_id;
    id_ = id;
    position_ = position;
    projected_position_ = projected_position;
    quaternion_ = quaternion;
    in_fov_ = in_fov;
}
References frame_id(), frame_id_, id(), id_, in_fov(), in_fov_, position(), position_, projected_position(), projected_position_, quaternion(), quaternion_, stamp(), and stamp_.
SingleLineAdapter() [4/5]
SingleLineAdapter::SingleLineAdapter (const rclcpp::Time & stamp, const std::string & frame_id, const int & id, const geometry_msgs::msg::Pose & msg, const bool & in_fov)
Constructor from pose msg.
Parameters
stamp The timestamp.
frame_id The frame id.
id The id of the line.
msg The pose msg.
in_fov Whether the line is in the FOV.
Definition at line 58 of file single_line_adapter.cpp.
  {
    stamp_ = stamp;
    frame_id_ = frame_id;
    id_ = id;
    position_ = iii_drone::types::pointFromPoseMsg(msg);
    projected_position_ = position_;
    quaternion_ = iii_drone::types::quaternionFromPoseMsg(msg);
    in_fov_ = in_fov;
}
References frame_id(), frame_id_, id(), id_, in_fov(), in_fov_, iii_drone::types::pointFromPoseMsg(), position_, projected_position_, quaternion_, iii_drone::types::quaternionFromPoseMsg(), stamp(), and stamp_.
SingleLineAdapter() [5/5]
SingleLineAdapter::SingleLineAdapter (const int & id, const geometry_msgs::msg::PoseStamped & msg, const bool & in_fov)
Constructor from PoseStamped msg.
Parameters
id The id of the line.
msg The PoseStamped msg.
in_fov Whether the line is in the FOV.
Definition at line 76 of file single_line_adapter.cpp.
  {
    stamp_ = msg.header.stamp;
    frame_id_ = msg.header.frame_id;
    id_ = id;
    position_ = iii_drone::types::pointFromPoseMsg(msg.pose);
    projected_position_ = position_;
    quaternion_ = iii_drone::types::quaternionFromPoseMsg(msg.pose);
    in_fov_ = in_fov;
}
References frame_id_, id(), id_, in_fov(), in_fov_, iii_drone::types::pointFromPoseMsg(), position_, projected_position_, quaternion_, iii_drone::types::quaternionFromPoseMsg(), and stamp_.
Member Function Documentation
frame_id()
const std::string & SingleLineAdapter::frame_id () const
Frame id getter.
Definition at line 136 of file single_line_adapter.cpp.
{
    return frame_id_;
}
References frame_id_.
Referenced by SingleLineAdapter(), and SingleLineAdapter().
id()
const int & SingleLineAdapter::id () const
Id getter.
Definition at line 142 of file single_line_adapter.cpp.
{
    return id_;
}
References id_.
Referenced by iii_drone::perception::SingleLine::SingleLine(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), and iii_drone::control::CombinedDroneAwarenessHandler::updateDroneLocation().
in_fov()
const bool & SingleLineAdapter::in_fov () const
In FOV getter.
Definition at line 176 of file single_line_adapter.cpp.
{
    return in_fov_;
}
References in_fov_.
Referenced by SingleLineAdapter(), SingleLineAdapter(), and SingleLineAdapter().
position()
const iii_drone::types::point_t & SingleLineAdapter::position () const
position getter.
Definition at line 148 of file single_line_adapter.cpp.
{
    return position_;
}
References position_.
Referenced by iii_drone::adapters::PowerlineAdapter::GetClosestLine(), iii_drone::perception::SingleLine::SingleLine(), SingleLineAdapter(), and iii_drone::control::CombinedDroneAwarenessHandler::updateDroneLocation().
projected_position()
const iii_drone::types::point_t & SingleLineAdapter::projected_position () const
Projected position getter.
Definition at line 154 of file single_line_adapter.cpp.
{
    return projected_position_;
}
References projected_position_.
Referenced by iii_drone::perception::SingleLine::SingleLine(), and SingleLineAdapter().
quaternion()
const iii_drone::types::quaternion_t & SingleLineAdapter::quaternion () const
Quaternion getter.
Definition at line 160 of file single_line_adapter.cpp.
{
    return quaternion_;
}
References quaternion_.
Referenced by iii_drone::perception::SingleLine::SingleLine(), and SingleLineAdapter().
stamp()
const rclcpp::Time & SingleLineAdapter::stamp () const
Timestamp getter.
Definition at line 130 of file single_line_adapter.cpp.
{
    return stamp_;
}
References stamp_.
Referenced by SingleLineAdapter(), SingleLineAdapter(), and iii_drone::adapters::PowerlineAdapter::UpdateFromMsg().
ToMsg()
const iii_drone_interfaces::msg::SingleLine SingleLineAdapter::ToMsg () const
Converts to SingleLine msg.
Definition at line 92 of file single_line_adapter.cpp.
{
    iii_drone_interfaces::msg::SingleLine msg;
    msg.header.stamp = stamp_;
    msg.header.frame_id = frame_id_;
    msg.id = id_;
    msg.pose = iii_drone::types::poseMsgFromPose(position_, quaternion_);
    msg.projected_position = iii_drone::types::pointMsgFromPoint(projected_position_);
    msg.in_field_of_view = in_fov_;
    return msg;
}
References frame_id_, id_, in_fov_, iii_drone::types::pointMsgFromPoint(), iii_drone::types::poseMsgFromPose(), position_, projected_position_, quaternion_, and stamp_.
ToPose()
const iii_drone::types::pose_t SingleLineAdapter::ToPose () const
Pose getter.
Definition at line 166 of file single_line_adapter.cpp.
{
    iii_drone::types::pose_t pose;
    pose.orientation = quaternion_;
    pose.position = position_;
    return pose;
}
References iii_drone::types::pose_t::orientation, iii_drone::types::pose_t::position, position_, and quaternion_.
ToPoseMsg()
const geometry_msgs::msg::Pose SingleLineAdapter::ToPoseMsg () const
Converts to Pose msg.
Definition at line 107 of file single_line_adapter.cpp.
{
    geometry_msgs::msg::Pose msg;
    msg.position = iii_drone::types::pointMsgFromPoint(position_);
    msg.orientation = iii_drone::types::quaternionMsgFromQuaternion(quaternion_);
    return msg;
}
References iii_drone::types::pointMsgFromPoint(), position_, quaternion_, and iii_drone::types::quaternionMsgFromQuaternion().
Referenced by ToPoseStampedMsg().
ToPoseStampedMsg()
const geometry_msgs::msg::PoseStamped SingleLineAdapter::ToPoseStampedMsg () const
Converts to PoseStamped msg.
Parameters
frame_id The frame id of the PoseStamped.
Definition at line 118 of file single_line_adapter.cpp.
{
    geometry_msgs::msg::PoseStamped msg;
    msg.header.stamp = stamp_;
    msg.header.frame_id = frame_id_;
    msg.pose = ToPoseMsg();
    return msg;
}
References frame_id_, stamp_, and ToPoseMsg().
Referenced by iii_drone::control::CombinedDroneAwarenessHandler::ComputeTargetTransform().
Member Data Documentation
frame_id_
std::string iii_drone::adapters::SingleLineAdapter::frame_id_ private
The frame id.
Definition at line 170 of file single_line_adapter.hpp.
Referenced by frame_id(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), ToMsg(), and ToPoseStampedMsg().
id_
int iii_drone::adapters::SingleLineAdapter::id_ private
The id of the line.
Definition at line 175 of file single_line_adapter.hpp.
Referenced by id(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), and ToMsg().
in_fov_
bool iii_drone::adapters::SingleLineAdapter::in_fov_ private
Whether the line is in the FOV.
Definition at line 195 of file single_line_adapter.hpp.
Referenced by in_fov(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), and ToMsg().
position_
iii_drone::types::point_t iii_drone::adapters::SingleLineAdapter::position_ private
The position of the line.
Definition at line 180 of file single_line_adapter.hpp.
Referenced by position(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), ToMsg(), ToPose(), and ToPoseMsg().
projected_position_
iii_drone::types::point_t iii_drone::adapters::SingleLineAdapter::projected_position_ private
The position of the line projected onto the projection plane.
Definition at line 185 of file single_line_adapter.hpp.
Referenced by projected_position(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), and ToMsg().
quaternion_
iii_drone::types::quaternion_t iii_drone::adapters::SingleLineAdapter::quaternion_ private
The quaternion of the line.
Definition at line 190 of file single_line_adapter.hpp.
Referenced by quaternion(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), ToMsg(), ToPose(), and ToPoseMsg().
stamp_
rclcpp::Time iii_drone::adapters::SingleLineAdapter::stamp_ private
The timestamp.
Definition at line 165 of file single_line_adapter.hpp.
Referenced by SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), SingleLineAdapter(), stamp(), ToMsg(), and ToPoseStampedMsg().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/adapters/single_line_adapter.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/adapters/single_line_adapter.cpp