III-Drone: iii_drone::control::maneuver::HoverByObjectManeuverServer Class Reference
iii_drone::control::maneuver::HoverByObjectManeuverServer Class Reference
HoverByObject maneuver server class. When the hover by object action is called, and the target is valid (object is visible and the drone is within the maximum euclidean distance to the object), the drone will start hovering by the object, and the action will succeed immediately. The maneuver scheduler will then keep hovering by the object until a new maneuver is scheduled or the timeout elapses by the duration given in the hover by object action call. Exposes external methods for getting the reference and updating the hover reference parameters. Other maneuver servers will use this server to generate references before a new maneuver is scheduled. Will fail if the target is not visible or the drone has drifted too far away from the target relative pose.
#include <hover_by_object_maneuver_server.hpp>
Public Member Functions
HoverByObjectManeuverServer (rclcpp::Node *node, CombinedDroneAwarenessHandler::SharedPtr combined_drone_awareness_handler, const std::string &action_name, unsigned int wait_for_execute_poll_ms, unsigned int evaluate_done_poll_ms, bool use_nans, double max_euc_dist)
Constructor.
bool CanExecuteManeuver (const Maneuver &maneuver, const combined_drone_awareness_t &drone_awareness) const override
Whether the maneuver can be executed, will return false if the target is not visible or the drone has drifted too far away from the target relative pose.
combined_drone_awareness_t ExpectedAwarenessAfterExecution (const Maneuver &maneuver) override
The expected awareness after execution. The drone will be armed and offboard.
void RegisterOnFailCallback (std::function< void()> on_fail_callback)
Register a callback for when the target is not visible or the drone has drifted too far away from the target relative pose.
bool Update (const iii_drone::adapters::TargetAdapter &target_adapter)
Updates the hover reference.
iii_drone::control::Reference GetReference (const iii_drone::control::State &state)
Gets the hover reference. The current state is not used. Will call the on fail callback if the target is not visible or the drone has drifted too far away from the target relative pose.
Public Member Functions inherited from iii_drone::control::maneuver::ManeuverServer
ManeuverServer (rclcpp::Node *node, CombinedDroneAwarenessHandler::SharedPtr awareness_handler, const std::string &action_name, unsigned int wait_for_execute_poll_ms, unsigned int evaluate_done_poll_ms)
Constructor.
void Start (std::function< bool(Maneuver, bool &)> register_maneuver_function, std::function< bool(Maneuver)> update_manuever_function, std::function< bool(Maneuver)> cancel_maneuver_function, std::function< bool(Maneuver)> verify_maneuver_in_queue_function, std::function< bool(Maneuver)> verify_maneuver_active_function, std::function< void(Maneuver)> done_callback, ReferenceCallbackToken::SharedPtr reference_callback_token, std::map< iii_drone::control::maneuver::maneuver_type_t, std::shared_ptr< ManeuverServer > > registered_maneuvers)
Method to start the maneuver server. The maneuver server will reject any new goals until started.
void Stop ()
Method to stop the maneuver server. The maneuver server will reject any new goals until started.
std::string action_name () const
Action name getter.
bool running () const
Returns whether the maneuver server is running.
Private Types
using HoverByObject = iii_drone_interfaces::action::HoverByObject
Private Member Functions
maneuver_type_t maneuver_type () const override
Returns the maneuver type (MANEUVER_TYPE_HOVER_BY_OBJECT).
void startExecution (Maneuver &maneuver) override
Starts the execution of the maneuver. Derives the TargetAdapter from the maneuver object parameters and sets the has_target flag to true.
bool canCancel () override
Returns true as the maneuver can be canceled.
iii_drone::control::Reference computeReference (const iii_drone::control::State &state) override
Computes the hover by object reference for the maneuver server.
bool hasSucceeded (Maneuver &maneuver) override
Returns true if the maneuver has succeeded. Has succeeded if the target is visible and the drone is within the maximum euclidean distance to the object.
bool hasFailed (Maneuver &maneuver) override
Returns true if the maneuver has failed. Has failed if the target is not visible or the drone has drifted too far away from the target relative pose.
void publishFeedback (Maneuver &maneuver) override
Does nothing as there is no feedback to publish.
void publishResultAndFinalize (Maneuver &maneuver, maneuver_result_type_t maneuver_result_type) override
Publishes the result and finalizes the maneuver according to the maneuver result type.
void registerReferenceCallbackOnSuccess (const Maneuver &maneuver) override
Registers the hover by object reference callback on success.
bool validateTargetTransform (const iii_drone::types::transform_matrix_t &target_transform, const iii_drone::control::State &state) const
Validates that the target transform and the drone state are within the maximum euclidean distance.
Private Attributes
iii_drone::utils::Atomic< iii_drone::adapters::TargetAdapter > target_adapter_
The hover reference target adapter.
iii_drone::utils::Atomic< bool > has_target_
Has target flag.
std::function< void()> on_fail_callback_
The callback for when the target is not visible or the drone has drifted too far away from the target relative pose.
iii_drone::utils::Atomic< bool > has_on_fail_callback_
Has on fail callback flag.
bool use_nans_
Whether to use NaNs for velocity and acceleration, otherwise uses zeros.
double max_euc_dist_
The maximum euclidean distance to the object before the fail callback is called.
Additional Inherited Members
Public Types inherited from iii_drone::control::maneuver::ManeuverServer
typedef std::shared_ptr< ManeuverServer > SharedPtr
Shared pointer type.
Protected Types inherited from iii_drone::control::maneuver::ManeuverServer
enum maneuver_result_type_t { MANEUVER_RESULT_TYPE_SUCCEED , MANEUVER_RESULT_TYPE_CANCEL , MANEUVER_RESULT_TYPE_ABORT }
Maneuver result type enum.
Protected Member Functions inherited from iii_drone::control::maneuver::ManeuverServer
const CombinedDroneAwarenessHandler::SharedPtr & awareness_handler () const
Combined drone awareness handler, accessible to derived classes through the protected method.
const iii_drone::utils::Atomic< iii_drone::control::maneuver::Maneuver > & current_maneuver () const
The currently executing maneuver, accessible to derived classes through the protected method.
rclcpp::Node * node () const
Node pointer getter.
std::map< iii_drone::control::maneuver::maneuver_type_t, std::shared_ptr< iii_drone::control::maneuver::ManeuverServer > > registered_maneuvers () const
Registered maneuvers map getter.
void registerCallback (const std::function< Reference(const State &)> &callback)
Registers a callback function for the reference. The callback function should be registered with the reference callback token.
template<typename ActionT >
void createServer ()
Creates the underlying action server.
Detailed Description
HoverByObject maneuver server class. When the hover by object action is called, and the target is valid (object is visible and the drone is within the maximum euclidean distance to the object), the drone will start hovering by the object, and the action will succeed immediately. The maneuver scheduler will then keep hovering by the object until a new maneuver is scheduled or the timeout elapses by the duration given in the hover by object action call. Exposes external methods for getting the reference and updating the hover reference parameters. Other maneuver servers will use this server to generate references before a new maneuver is scheduled. Will fail if the target is not visible or the drone has drifted too far away from the target relative pose.
Definition at line 47 of file hover_by_object_maneuver_server.hpp.
Member Typedef Documentation
HoverByObject
using iii_drone::control::maneuver::HoverByObjectManeuverServer::HoverByObject = iii_drone_interfaces::action::HoverByObject private
Definition at line 48 of file hover_by_object_maneuver_server.hpp.
Constructor & Destructor Documentation
HoverByObjectManeuverServer()
HoverByObjectManeuverServer::HoverByObjectManeuverServer (rclcpp::Node * node, CombinedDroneAwarenessHandler::SharedPtr combined_drone_awareness_handler, const std::string & action_name, unsigned int wait_for_execute_poll_ms, unsigned int evaluate_done_poll_ms, bool use_nans, double max_euc_dist)
Constructor.
Parameters
node Node pointer
combined_drone_awareness_handler Combined drone awareness handler pointer
action_name Action name
wait_for_execute_poll_ms Wait for execute poll milliseconds
evaluate_done_poll_ms Evaluate done poll milliseconds
use_nans Whether to use NaNs for velocity and acceleration, otherwise uses zeros
max_euc_dist The maximum euclidean distance to the object before the fail callback is called.
Definition at line 17 of file hover_by_object_maneuver_server.cpp.
  : ManeuverServer(
    node,
    combined_drone_awareness_handler,
    action_name,
    wait_for_execute_poll_ms,
    evaluate_done_poll_ms
),  has_target_(false),
    has_on_fail_callback_(false),
    use_nans_(use_nans),
    max_euc_dist_(max_euc_dist) {
    createServer<HoverByObject>();
}
Member Function Documentation
canCancel()
bool HoverByObjectManeuverServer::canCancel () override private virtual
Returns true as the maneuver can be canceled.
Returns
bool True.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 261 of file hover_by_object_maneuver_server.cpp.
{
    return true;
}
CanExecuteManeuver()
bool HoverByObjectManeuverServer::CanExecuteManeuver (const Maneuver & maneuver, const combined_drone_awareness_t & drone_awareness) const override virtual
Whether the maneuver can be executed, will return false if the target is not visible or the drone has drifted too far away from the target relative pose.
Parameters
maneuver The maneuver.
drone_awareness The drone awareness.
Returns
bool Whether the maneuver can be executed.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 40 of file hover_by_object_maneuver_server.cpp.
        {
    if (maneuver.maneuver_type() != MANEUVER_TYPE_HOVER_BY_OBJECT) {
        return false;
    }
    hover_by_object_maneuver_params_t params(maneuver.maneuver_params());
    if (params.target_adapter.target_type() != TARGET_TYPE_CABLE) {
        return false;
    }
    if (!drone_awareness.offboard) {
        return false;
    }
    if (!drone_awareness.armed) {
        return false;
    }
    if (!drone_awareness.in_flight()) {
        return false;
    }
    if (!drone_awareness.has_target()) {
        return false;
    }
    if (drone_awareness.target_adapter.target_type() != TARGET_TYPE_CABLE) {
        return false;
    }
    transform_matrix_t target_transform;
    try {
        target_transform = awareness_handler()->ComputeTargetTransform(target_adapter_);
    } catch (const std::runtime_error &e) {
        return false;
    }
    if (!validateTargetTransform(
        target_transform,
        drone_awareness.state
    )) {
        return false;
    }
    return true;
}
References iii_drone::control::combined_drone_awareness_t::armed, iii_drone::control::maneuver::ManeuverServer::awareness_handler(), iii_drone::control::CombinedDroneAwarenessHandler::ComputeTargetTransform(), iii_drone::control::combined_drone_awareness_t::has_target(), iii_drone::control::combined_drone_awareness_t::in_flight(), iii_drone::control::maneuver::Maneuver::maneuver_params(), iii_drone::control::maneuver::Maneuver::maneuver_type(), iii_drone::control::maneuver::MANEUVER_TYPE_HOVER_BY_OBJECT, iii_drone::control::combined_drone_awareness_t::offboard, iii_drone::control::combined_drone_awareness_t::state, iii_drone::control::combined_drone_awareness_t::target_adapter, iii_drone::control::maneuver::hover_by_object_maneuver_params_t::target_adapter, target_adapter_, iii_drone::adapters::TargetAdapter::target_type(), iii_drone::adapters::TARGET_TYPE_CABLE, and validateTargetTransform().
computeReference()
iii_drone::control::Reference HoverByObjectManeuverServer::computeReference (const iii_drone::control::State & state) override private virtual
Computes the hover by object reference for the maneuver server.
Parameters
state The current state.
Returns
iii_drone::control::Reference The hover reference.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 267 of file hover_by_object_maneuver_server.cpp.
{
    return GetReference(state);
}
References GetReference().
ExpectedAwarenessAfterExecution()
combined_drone_awareness_t HoverByObjectManeuverServer::ExpectedAwarenessAfterExecution (const Maneuver & maneuver) override virtual
The expected awareness after execution. The drone will be armed and offboard.
Parameters
maneuver The maneuver.
Returns
combined_drone_awareness_t The expected awareness after execution.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 100 of file hover_by_object_maneuver_server.cpp.
{
    combined_drone_awareness_t awareness_after;
    awareness_after.armed = true;
    awareness_after.offboard = true;
    awareness_after.target_adapter = target_adapter_;
    awareness_after.target_position_known = true;
    awareness_after.drone_location = DRONE_LOCATION_IN_FLIGHT;
    return awareness_after;
}
References iii_drone::control::combined_drone_awareness_t::armed, iii_drone::control::combined_drone_awareness_t::drone_location, iii_drone::control::DRONE_LOCATION_IN_FLIGHT, iii_drone::control::combined_drone_awareness_t::offboard, iii_drone::control::combined_drone_awareness_t::target_adapter, target_adapter_, and iii_drone::control::combined_drone_awareness_t::target_position_known.
GetReference()
iii_drone::control::Reference HoverByObjectManeuverServer::GetReference (const iii_drone::control::State & state)
Gets the hover reference. The current state is not used. Will call the on fail callback if the target is not visible or the drone has drifted too far away from the target relative pose.
Parameters
state The current state, is not used.
Returns
The hover reference.
Definition at line 155 of file hover_by_object_maneuver_server.cpp.
{
    if (!has_on_fail_callback_) {
        throw std::runtime_error("No on fail callback registered for HoverByObjectManeuverServer");
    }
    if (!has_target_) {
        throw std::runtime_error("No target set for HoverByObjectManeuverServer");
    }
    transform_matrix_t target_transform;
    try {
        target_transform = awareness_handler()->ComputeTargetTransform(target_adapter_);
    } catch (const std::runtime_error &e) {
        has_target_ = false;
    }
    if (!validateTargetTransform(
        target_transform,
        awareness_handler()->GetState()
    )) {
        has_target_ = false;
    }
    vector_t position;
    double yaw;
    vector_t velocity;
    double yaw_rate;
    vector_t acceleration;
    double yaw_acceleration;
    if (has_target_) {
        pose_t pose = poseFromTransformMatrix(target_transform);
        position = pose.position;
        yaw = quatToEul(pose.orientation)(2);
    } else {
        on_fail_callback_();
        position = state.position();
        yaw = state.yaw();
    }
    if (use_nans_) {
        velocity = vector_t::Constant(NAN);
        yaw_rate = NAN;
        acceleration = vector_t::Constant(NAN);
        yaw_acceleration = NAN;
    } else {
        velocity = vector_t::Zero();
        yaw_rate = 0;
        acceleration = vector_t::Zero();
        yaw_acceleration = 0;
    }
    return iii_drone::control::Reference(
        position,
        yaw,
        velocity,
        yaw_rate,
        acceleration,
        yaw_acceleration
    );
}
References iii_drone::control::maneuver::ManeuverServer::awareness_handler(), iii_drone::control::CombinedDroneAwarenessHandler::ComputeTargetTransform(), has_on_fail_callback_, has_target_, on_fail_callback_, iii_drone::types::pose_t::orientation, iii_drone::types::poseFromTransformMatrix(), iii_drone::control::State::position(), iii_drone::types::pose_t::position, iii_drone::math::quatToEul(), target_adapter_, use_nans_, validateTargetTransform(), and iii_drone::control::State::yaw().
Referenced by computeReference(), iii_drone::control::maneuver::FlyToObjectManeuverServer::registerReferenceCallbackOnSuccess(), and registerReferenceCallbackOnSuccess().
hasFailed()
bool HoverByObjectManeuverServer::hasFailed (Maneuver & maneuver) override private virtual
Returns true if the maneuver has failed. Has failed if the target is not visible or the drone has drifted too far away from the target relative pose.
Parameters
maneuver The maneuver.
Returns
bool True if the maneuver has failed.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 294 of file hover_by_object_maneuver_server.cpp.
{
    return !hasSucceeded(maneuver);
}
References hasSucceeded().
hasSucceeded()
bool HoverByObjectManeuverServer::hasSucceeded (Maneuver & maneuver) override private virtual
Returns true if the maneuver has succeeded. Has succeeded if the target is visible and the drone is within the maximum euclidean distance to the object.
Parameters
maneuver The maneuver.
Returns
bool True if the maneuver has succeeded.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 273 of file hover_by_object_maneuver_server.cpp.
{
    transform_matrix_t target_transform;
    try {
        target_transform = awareness_handler()->ComputeTargetTransform(target_adapter_);
    } catch (const std::runtime_error &e) {
        has_target_ = false;
    }
    return validateTargetTransform(
        target_transform,
        awareness_handler()->GetState()
    );
}
References iii_drone::control::maneuver::ManeuverServer::awareness_handler(), iii_drone::control::CombinedDroneAwarenessHandler::ComputeTargetTransform(), has_target_, target_adapter_, and validateTargetTransform().
Referenced by hasFailed().
maneuver_type()
maneuver_type_t HoverByObjectManeuverServer::maneuver_type () const override private virtual
Returns the maneuver type (MANEUVER_TYPE_HOVER_BY_OBJECT).
Returns
maneuver_type_t The maneuver type.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 240 of file hover_by_object_maneuver_server.cpp.
{
    return MANEUVER_TYPE_HOVER_BY_OBJECT;
}
References iii_drone::control::maneuver::MANEUVER_TYPE_HOVER_BY_OBJECT.
publishFeedback()
void HoverByObjectManeuverServer::publishFeedback (Maneuver & maneuver) override private virtual
Does nothing as there is no feedback to publish.
Parameters
maneuver The maneuver.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 300 of file hover_by_object_maneuver_server.cpp.
{
    // No feedback to publish
}
publishResultAndFinalize()
void HoverByObjectManeuverServer::publishResultAndFinalize (Maneuver & maneuver, maneuver_result_type_t maneuver_result_type) override private virtual
Publishes the result and finalizes the maneuver according to the maneuver result type.
Parameters
maneuver The maneuver.
maneuver_result_type The maneuver result type.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 306 of file hover_by_object_maneuver_server.cpp.
  {
    auto goal_handle = std::static_pointer_cast<rclcpp_action::ServerGoalHandle<HoverByObject>>(maneuver.goal_handle());
    auto result = std::make_shared<HoverByObject::Result>();
    switch (maneuver_result_type){
        case MANEUVER_RESULT_TYPE_SUCCEED:
            goal_handle->succeed(result);
            break;
        case MANEUVER_RESULT_TYPE_ABORT:
            goal_handle->abort(result);
            awareness_handler()->ClearTarget();
            break;
        case MANEUVER_RESULT_TYPE_CANCEL:
            goal_handle->canceled(result);
            awareness_handler()->ClearTarget();
            break;
    }
}
References iii_drone::control::maneuver::ManeuverServer::awareness_handler(), iii_drone::control::CombinedDroneAwarenessHandler::ClearTarget(), iii_drone::control::maneuver::Maneuver::goal_handle(), iii_drone::control::maneuver::ManeuverServer::MANEUVER_RESULT_TYPE_ABORT, iii_drone::control::maneuver::ManeuverServer::MANEUVER_RESULT_TYPE_CANCEL, and iii_drone::control::maneuver::ManeuverServer::MANEUVER_RESULT_TYPE_SUCCEED.
RegisterOnFailCallback()
void HoverByObjectManeuverServer::RegisterOnFailCallback (std::function< void()> on_fail_callback)
Register a callback for when the target is not visible or the drone has drifted too far away from the target relative pose.
Parameters
on_fail_callback The on fail callback.
Definition at line 113 of file hover_by_object_maneuver_server.cpp.
{
    on_fail_callback_ = on_fail_callback;
    has_on_fail_callback_ = true;
}
References has_on_fail_callback_, and on_fail_callback_.
registerReferenceCallbackOnSuccess()
void HoverByObjectManeuverServer::registerReferenceCallbackOnSuccess (const Maneuver & maneuver) override private virtual
Registers the hover by object reference callback on success.
Parameters
maneuver The maneuver.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 331 of file hover_by_object_maneuver_server.cpp.
{
    registerCallback(
        std::bind(
            &HoverByObjectManeuverServer::GetReference,
            this,
            std::placeholders::_1
        )
    );
}
References GetReference(), and iii_drone::control::maneuver::ManeuverServer::registerCallback().
startExecution()
void HoverByObjectManeuverServer::startExecution (Maneuver & maneuver) override private virtual
Starts the execution of the maneuver. Derives the TargetAdapter from the maneuver object parameters and sets the has_target flag to true.
Parameters
maneuver The maneuver.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 246 of file hover_by_object_maneuver_server.cpp.
{
    if (!has_on_fail_callback_) {
        throw std::runtime_error("No on fail callback registered for HoverByObjectManeuverServer");
    }
    hover_by_object_maneuver_params_t params(maneuver.maneuver_params());
    target_adapter_ = params.target_adapter;
    has_target_ = true;
}
References has_on_fail_callback_, has_target_, iii_drone::control::maneuver::Maneuver::maneuver_params(), iii_drone::control::maneuver::hover_by_object_maneuver_params_t::target_adapter, and target_adapter_.
Update()
bool HoverByObjectManeuverServer::Update (const iii_drone::adapters::TargetAdapter & target_adapter)
Updates the hover reference.
Parameters
target_adapter The hover object target adapter.
Returns
bool Whether the update was successful.
Definition at line 120 of file hover_by_object_maneuver_server.cpp.
{
    transform_matrix_t target_transform;
    try {
        target_transform = awareness_handler()->ComputeTargetTransform(target_adapter);
    } catch (const std::runtime_error &e) {
        has_target_ = false;
        return false;
    }
    if (!validateTargetTransform(
        target_transform,
        awareness_handler()->GetState()
    )) {
        has_target_ = false;
        return false;
    }
    has_target_ = true;
    target_adapter_ = target_adapter;
    return true;
}
References iii_drone::control::maneuver::ManeuverServer::awareness_handler(), iii_drone::control::CombinedDroneAwarenessHandler::ComputeTargetTransform(), has_target_, target_adapter_, and validateTargetTransform().
validateTargetTransform()
bool HoverByObjectManeuverServer::validateTargetTransform (const iii_drone::types::transform_matrix_t & target_transform, const iii_drone::control::State & state) const private
Validates that the target transform and the drone state are within the maximum euclidean distance.
Parameters
target_transform The target transform.
state The drone state.
Returns
bool Whether the target transform and the drone state are within the maximum euclidean distance.
Definition at line 343 of file hover_by_object_maneuver_server.cpp.
        {
    vector_t target_position = poseFromTransformMatrix(target_transform).position;
    vector_t drone_position = state.position();
    if ((target_position - drone_position).norm() > max_euc_dist_) {
        return false;
    }
    return true;
}
References max_euc_dist_, iii_drone::types::poseFromTransformMatrix(), iii_drone::control::State::position(), and iii_drone::types::pose_t::position.
Referenced by CanExecuteManeuver(), GetReference(), hasSucceeded(), and Update().
Member Data Documentation
has_on_fail_callback_
iii_drone::utils::Atomic<bool> iii_drone::control::maneuver::HoverByObjectManeuverServer::has_on_fail_callback_ private
Has on fail callback flag.
Definition at line 220 of file hover_by_object_maneuver_server.hpp.
Referenced by GetReference(), RegisterOnFailCallback(), and startExecution().
has_target_
iii_drone::utils::Atomic<bool> iii_drone::control::maneuver::HoverByObjectManeuverServer::has_target_ private
Has target flag.
Definition at line 210 of file hover_by_object_maneuver_server.hpp.
Referenced by GetReference(), hasSucceeded(), startExecution(), and Update().
max_euc_dist_
double iii_drone::control::maneuver::HoverByObjectManeuverServer::max_euc_dist_ private
The maximum euclidean distance to the object before the fail callback is called.
Definition at line 230 of file hover_by_object_maneuver_server.hpp.
Referenced by validateTargetTransform().
on_fail_callback_
std::function<void()> iii_drone::control::maneuver::HoverByObjectManeuverServer::on_fail_callback_ private
The callback for when the target is not visible or the drone has drifted too far away from the target relative pose.
Definition at line 215 of file hover_by_object_maneuver_server.hpp.
Referenced by GetReference(), and RegisterOnFailCallback().
target_adapter_
iii_drone::utils::Atomic<iii_drone::adapters::TargetAdapter> iii_drone::control::maneuver::HoverByObjectManeuverServer::target_adapter_ private
The hover reference target adapter.
Definition at line 205 of file hover_by_object_maneuver_server.hpp.
Referenced by CanExecuteManeuver(), ExpectedAwarenessAfterExecution(), GetReference(), hasSucceeded(), startExecution(), and Update().
use_nans_
bool iii_drone::control::maneuver::HoverByObjectManeuverServer::use_nans_ private
Whether to use NaNs for velocity and acceleration, otherwise uses zeros.
Definition at line 225 of file hover_by_object_maneuver_server.hpp.
Referenced by GetReference().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/maneuver/hover_by_object_maneuver_server.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/maneuver/hover_by_object_maneuver_server.cpp