III-Drone: iii_drone::perception::HoughTransformer Class Reference
iii_drone::perception::HoughTransformer Class Reference
Class for performing the hough transform on images to detect powerline direction.
#include <hough_transformer.hpp>
Public Member Functions
HoughTransformer (std::shared_ptr< HoughTransformerParameters > parameters)
Constructor.
~HoughTransformer ()
Destructor.
const std::vector< cv::Vec2f > GetHoughLines (const cv::Mat img) const
Performs the hough transform on the given image.
float ComputeAngle (const std::vector< cv::Vec2f > lines, int rows, int cols) const
Computes the hough lines direction angle from hough lines.
bool ComputeAngle (const cv::Mat img, float &angle) const
Computes the hough lines direction angle from an image.
Private Member Functions
int getBestLineIndex (const std::vector< cv::Vec2f > lines, int rows, int cols) const
Finds the index of the best hough line match.
Private Attributes
std::shared_ptr< HoughTransformerParameters > parameters_
The hough transformer parameters.
Detailed Description
Class for performing the hough transform on images to detect powerline direction.
Definition at line 38 of file hough_transformer.hpp.
Constructor & Destructor Documentation
HoughTransformer()
HoughTransformer::HoughTransformer (std::shared_ptr< HoughTransformerParameters > parameters)
Constructor.
Parameters
parameters The hough transformer parameters.
Definition at line 13 of file hough_transformer.cpp.
: parameters_(parameters) { }
~HoughTransformer()
HoughTransformer::~HoughTransformer ()
Destructor.
Definition at line 15 of file hough_transformer.cpp.
{ }
Member Function Documentation
ComputeAngle() [1/2]
bool HoughTransformer::ComputeAngle (const cv::Mat img, float & angle) const
Computes the hough lines direction angle from an image.
Parameters
img The image to perform the hough transform on.
angle The computed angle output.
Returns
True if the angle was computed successfully, false otherwise.
Definition at line 73 of file hough_transformer.cpp.
        {
    const std::vector<cv::Vec2f> lines = GetHoughLines(img);
    if (lines.size() == 0) {
        return false;
    }
    angle = ComputeAngle(
        lines,
        img.rows,
        img.cols
    );
    return true;
}
References ComputeAngle(), and GetHoughLines().
ComputeAngle() [2/2]
float HoughTransformer::ComputeAngle (const std::vector< cv::Vec2f > lines, int rows, int cols) const
Computes the hough lines direction angle from hough lines.
Parameters
lines The hough lines.
rows The number of rows in the image.
cols The number of columns in the image.
Returns
The hough lines direction angle.
Definition at line 49 of file hough_transformer.cpp.
        {
    if (lines.size() == 0) {
        throw std::runtime_error("HoughTransformer::GetHoughLineAngle(): Empty lines vector.");
    }
    float theta = 0.0;
    int idx = getBestLineIndex(
        lines,
        rows,
        cols
    );
    theta = lines[idx][1];
    return theta;
}
References getBestLineIndex().
Referenced by ComputeAngle(), and iii_drone::perception::hough_transformer_node::HoughTransformerNode::OnCameraMsg().
getBestLineIndex()
int HoughTransformer::getBestLineIndex (const std::vector< cv::Vec2f > lines, int rows, int cols) const private
Finds the index of the best hough line match.
Parameters
lines The hough lines.
rows The number of rows in the image.
cols The number of columns in the image.
Returns
The index of the best line match.
Definition at line 94 of file hough_transformer.cpp.
        {
    int best_idx = -1;
    float best_dist = 100000.;
    float x0 = cols/2;
    float y0 = rows/2;
    for( size_t i = 0; i < lines.size(); i++ ) {
        float a = -cos(lines[i][1])/sin(lines[i][1]);
        float b = lines[i][0]/sin(lines[i][1]);
        float dist = abs(a*x0 - y0 + b) / sqrt(a*a+1);
        if (dist < best_dist) {
            best_idx = i;
        }
    }
    return best_idx;
}
Referenced by ComputeAngle().
GetHoughLines()
const std::vector< cv::Vec2f > HoughTransformer::GetHoughLines (const cv::Mat img) const
Performs the hough transform on the given image.
Parameters
img The image to perform the hough transform on.
Returns
The hough transform lines.
Definition at line 17 of file hough_transformer.cpp.
{
    cv::Mat edge;
    int canny_low_threshold = parameters_->canny_low_threshold();
    int canny_ratio = parameters_->canny_ratio();
    int canny_kernel_size = parameters_->canny_kernel_size();
    cv::Canny(
        img,
        edge,
        canny_low_threshold,
        canny_low_threshold * canny_ratio,
        canny_kernel_size
    ); // edge detection
    // Standard Hough Line Transform
    std::vector<cv::Vec2f> lines; // will hold the results of the detection
    cv::HoughLines(
        edge,
        lines,
        1,
        M_PI/180,
        150,
        0,
        0
    ); // runs the actual detection
    return lines;
}
References parameters_.
Referenced by ComputeAngle().
Member Data Documentation
parameters_
std::shared_ptr<HoughTransformerParameters> iii_drone::perception::HoughTransformer::parameters_ private
The hough transformer parameters.
Definition at line 95 of file hough_transformer.hpp.
Referenced by GetHoughLines().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/perception/hough_transformer.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/perception/hough_transformer.cpp