III-Drone: iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode Class Reference
iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode Class Reference
Node for kalman filtering the powerline direction based on hough transform output.
#include <pl_dir_computer_node.hpp>
Public Member Functions
PowerlineDirectionComputerNode (const std::string &node_name="pl_dir_computer", const std::string &node_namespace="/perception/pl_dir_computer", const rclcpp::NodeOptions &options=rclcpp::NodeOptions())
Construct a new Powerline Direction Computer Node object.
Private Member Functions
void odometryCallback ()
Callback function for the odometry timer.
void publishPowerlineDirection ()
Publishes the estimated powerline direction.
Private Attributes
PowerlineDirectionComputerConfigurator configurator_
Configurator object.
PowerlineDirection pl_direction_
Powerline direction object.
rclcpp::Subscription< std_msgs::msg::Float32 >::SharedPtr pl_angle_sub_
Subscription object to powerline yaw angle.
rclcpp::Subscription< iii_drone_interfaces::msg::Powerline >::SharedPtr pl_sub_
Subscription object to powerline topic.
rclcpp::Publisher< geometry_msgs::msg::PoseStamped >::SharedPtr pl_direction_pose_pub_
Estimated powerline direction pose publisher.
rclcpp::Publisher< geometry_msgs::msg::QuaternionStamped >::SharedPtr pl_direction_quat_pub_
Estimated powerline direction quaternion publisher.
std::shared_ptr< tf2_ros::TransformListener > transform_listener_ {nullptr}
std::unique_ptr< tf2_ros::Buffer > tf_buffer_
rclcpp::TimerBase::SharedPtr drone_tf_timer_ {nullptr}
Detailed Description
Node for kalman filtering the powerline direction based on hough transform output.
Definition at line 59 of file pl_dir_computer_node.hpp.
Constructor & Destructor Documentation
PowerlineDirectionComputerNode()
PowerlineDirectionComputerNode::PowerlineDirectionComputerNode (const std::string & node_name = "pl_dir_computer", const std::string & node_namespace = "/perception/pl_dir_computer", const rclcpp::NodeOptions & options = rclcpp::NodeOptions()) explicit
Construct a new Powerline Direction Computer Node object.
Parameters
node_name Name of the node
node_namespace Namespace of the node
options Node options
Definition at line 15 of file pl_dir_computer_node.cpp.
  : rclcpp::Node(
    node_name,
    node_namespace,
    options
),  configurator_(this),
    pl_direction_(configurator_.powerline_direction_parameters()) {
    pl_angle_sub_ = this->create_subscription<std_msgs::msg::Float32>(
        "/perception/hough_transformer/cable_yaw_angle",
        10,
        [this](const std_msgs::msg::Float32::SharedPtr msg) {
            pl_direction_.Update(msg->data);
        }
    );
    pl_sub_ = this->create_subscription<iii_drone_interfaces::msg::Powerline>(
        "/perception/pl_mapper/powerline",
        10,
        std::bind(
            &PowerlineDirection::UpdatePowerlineAdapter,
            &pl_direction_,
            std::placeholders::_1
        )
    );
    pl_direction_pose_pub_ = this->create_publisher<geometry_msgs::msg::PoseStamped>(
        "powerline_direction_pose",
        10
    );
    pl_direction_quat_pub_ = this->create_publisher<geometry_msgs::msg::QuaternionStamped>(
        "powerline_direction_quat",
        10
    );
    tf_buffer_ = std::make_unique<tf2_ros::Buffer>(this->get_clock());
    transform_listener_ = std::make_shared<tf2_ros::TransformListener>(*tf_buffer_);
    std::chrono::milliseconds sleep_ms(configurator_.init_sleep_time_ms());
    rclcpp::Rate rate(sleep_ms);
    rate.sleep();
    std::chrono::milliseconds odom_callback_ms(configurator_.odometry_callback_period_ms());
    drone_tf_timer_ = this->create_wall_timer(
        odom_callback_ms,
        std::bind(
            &PowerlineDirectionComputerNode::odometryCallback,
            this
        )
    );
    RCLCPP_DEBUG(this->get_logger(), "Initialized PowerlineDirectionComputerNode");
}
References configurator_, drone_tf_timer_, iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::init_sleep_time_ms(), iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::odometry_callback_period_ms(), odometryCallback(), pl_angle_sub_, pl_direction_, pl_direction_pose_pub_, pl_direction_quat_pub_, pl_sub_, tf_buffer_, transform_listener_, iii_drone::perception::PowerlineDirection::Update(), and iii_drone::perception::PowerlineDirection::UpdatePowerlineAdapter().
Member Function Documentation
odometryCallback()
void PowerlineDirectionComputerNode::odometryCallback () private
Callback function for the odometry timer.
Returns
void
Definition at line 74 of file pl_dir_computer_node.cpp.
{
    RCLCPP_DEBUG(this->get_logger(), "Fetching odometry transform");
    geometry_msgs::msg::TransformStamped tf;
    try {
        tf = tf_buffer_->lookupTransform(
            configurator_.drone_frame_id(),
            configurator_.world_frame_id(),
            tf2::TimePointZero
        );
    } catch(tf2::TransformException & ex) {
        RCLCPP_WARN(this->get_logger(), "Could not get odometry transform, frame world to drone");
        return;
    }
    quaternion_t quat = quaternionFromTransformMsg(tf.transform);
    pl_direction_.Predict(quat);
    publishPowerlineDirection();
}
References configurator_, iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::drone_frame_id(), pl_direction_, iii_drone::perception::PowerlineDirection::Predict(), publishPowerlineDirection(), iii_drone::types::quaternionFromTransformMsg(), tf_buffer_, and iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::world_frame_id().
Referenced by PowerlineDirectionComputerNode().
publishPowerlineDirection()
void PowerlineDirectionComputerNode::publishPowerlineDirection () private
Publishes the estimated powerline direction.
Returns
void
Definition at line 103 of file pl_dir_computer_node.cpp.
{
    RCLCPP_DEBUG(this->get_logger(), "Publishing powerline direction");
    geometry_msgs::msg::PoseStamped pose_msg = pl_direction_.ToPoseStampedMsg(configurator_.drone_frame_id());
    geometry_msgs::msg::QuaternionStamped quat_msg = pl_direction_.ToQuaternionStampedMsg(configurator_.drone_frame_id());
    pl_direction_pose_pub_->publish(pose_msg);
    pl_direction_quat_pub_->publish(quat_msg);
}
References configurator_, iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::drone_frame_id(), pl_direction_, pl_direction_pose_pub_, pl_direction_quat_pub_, iii_drone::perception::PowerlineDirection::ToPoseStampedMsg(), and iii_drone::perception::PowerlineDirection::ToQuaternionStampedMsg().
Referenced by odometryCallback().
Member Data Documentation
configurator_
PowerlineDirectionComputerConfigurator iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::configurator_ private
Configurator object.
Definition at line 79 of file pl_dir_computer_node.hpp.
Referenced by odometryCallback(), PowerlineDirectionComputerNode(), and publishPowerlineDirection().
drone_tf_timer_
rclcpp::TimerBase::SharedPtr iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::drone_tf_timer_ {nullptr} private
Definition at line 108 of file pl_dir_computer_node.hpp.
{nullptr};
Referenced by PowerlineDirectionComputerNode().
pl_angle_sub_
rclcpp::Subscription<std_msgs::msg::Float32>::SharedPtr iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::pl_angle_sub_ private
Subscription object to powerline yaw angle.
Definition at line 89 of file pl_dir_computer_node.hpp.
Referenced by PowerlineDirectionComputerNode().
pl_direction_
PowerlineDirection iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::pl_direction_ private
Powerline direction object.
Definition at line 84 of file pl_dir_computer_node.hpp.
Referenced by odometryCallback(), PowerlineDirectionComputerNode(), and publishPowerlineDirection().
pl_direction_pose_pub_
rclcpp::Publisher<geometry_msgs::msg::PoseStamped>::SharedPtr iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::pl_direction_pose_pub_ private
Estimated powerline direction pose publisher.
Definition at line 99 of file pl_dir_computer_node.hpp.
Referenced by PowerlineDirectionComputerNode(), and publishPowerlineDirection().
pl_direction_quat_pub_
rclcpp::Publisher<geometry_msgs::msg::QuaternionStamped>::SharedPtr iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::pl_direction_quat_pub_ private
Estimated powerline direction quaternion publisher.
Definition at line 104 of file pl_dir_computer_node.hpp.
Referenced by PowerlineDirectionComputerNode(), and publishPowerlineDirection().
pl_sub_
rclcpp::Subscription<iii_drone_interfaces::msg::Powerline>::SharedPtr iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::pl_sub_ private
Subscription object to powerline topic.
Definition at line 94 of file pl_dir_computer_node.hpp.
Referenced by PowerlineDirectionComputerNode().
tf_buffer_
std::unique_ptr<tf2_ros::Buffer> iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::tf_buffer_ private
Definition at line 107 of file pl_dir_computer_node.hpp.
Referenced by odometryCallback(), and PowerlineDirectionComputerNode().
transform_listener_
std::shared_ptr<tf2_ros::TransformListener> iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::transform_listener_ {nullptr} private
Definition at line 106 of file pl_dir_computer_node.hpp.
{nullptr};
Referenced by PowerlineDirectionComputerNode().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/perception/pl_dir_computer_node/pl_dir_computer_node.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/perception/pl_dir_computer_node/pl_dir_computer_node.cpp