III-Drone: iii_drone::control::flight_controller_node::FlightControllerConfigurator Class Reference
iii_drone::control::flight_controller_node::FlightControllerConfigurator Class Reference
Class for handling parameters for FlightController.
#include <flight_controller_node_configurator.hpp>
Public Member Functions
FlightControllerConfigurator (rclcpp::Node *node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Constructor.
FlightControllerConfigurator (rclcpp::Node *node, const rclcpp::QoS &qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Constructor.
bool always_armed_for_debug () const
Whether the drone should always be armed for debug purposes.
float landed_altitude_threshold () const
The altitude threshold for considering the drone landed.
bool use_ground_altitude_offset () const
Whether the drone should use ground altitude offset.
float reached_position_euclidean_distance_threshold () const
The threshold for considering the drone reached the target position.
float minimum_target_altitude () const
The minimum altitude to be used when the target altitude is below it.
float target_cable_fixed_position_distance_threshold () const
The distance threshold to consider the target position reached when the drone is following a cable.
float target_cable_safety_margin_distance_threshold () const
The distance threshold to consider the target position reached when the drone is following a cable.
float target_cable_safety_margin_max_euc_distance () const
The maximum euclidean distance between the drone and the target position to consider the target position reached when the drone is following a cable.
float target_cable_safety_margin_max_euc_velocity () const
The maximum euclidean velocity between the drone and the target position to consider the target position reached when the drone is following a cable.
float target_cable_safety_margin_max_euc_acceleration () const
The maximum euclidean acceleration between the drone and the target position to consider the target position reached when the drone is following a cable.
float target_cable_safety_margin_max_yaw_distance () const
The maximum yaw distance between the drone and the target position to consider the target position reached when the drone is following a cable.
float target_cable_safety_margin_max_yaw_velocity () const
The maximum yaw velocity between the drone and the target position to consider the target position reached when the drone is following a cable.
float target_cable_set_point_truncate_distance_threshold () const
The distance threshold to truncate the setpoint when the drone is following a cable.
float landed_on_powerline_non_offboard_max_euc_distance () const
The maximum euclidean distance between the drone and the powerline to consider the drone landed on the powerline when the drone is not in offboard mode.
bool always_hover_in_offboard () const
Whether the drone should always hover in offboard mode.
const std::string on_cable_control_mode () const
The control mode to use when the drone is on the cable.
float on_cable_upwards_thrust () const
The upwards thrust to apply when the drone is on the cable.
float on_cable_upwards_velocity () const
The upwards velocity to apply when the drone is on the cable.
bool use_gripper_status_condition () const
Whether to use the gripper status condition when the drone is on the cable.
bool hover_under_cable_on_aborted_cable_landing () const
Whether to perform cable takeoff followed by hovering under cable on aborted cable landing.
float disarming_on_cable_max_descend_distance () const
The maximum descend distance to disarm the drone when the drone is on the cable.
const std::string disarm_on_cable_mode () const
The disarm mode to use when the drone is on the cable.
float disarm_on_cable_thrust_decrease_time_s () const
The time to decrease the thrust to zero when disarming the drone on the cable.
float disarm_on_cable_thrust_wait_for_disarm_time_s () const
The time to wait for disarm after the thrust is zero when disarming the drone on the cable.
float disarm_on_cable_flight_termination_timeout_s () const
The timeout to terminate the flight when disarming the drone on the cable.
float arming_on_cable_spool_up_time_s () const
The time to spool up the motor when arming the drone on the cable.
bool update_home_position () const
Whether to update the home position.
int arm_cnt_timeout () const
The timeout for arming the drone.
int offboard_cnt_timeout () const
The timeout for offboard mode.
int land_cnt_timeout () const
The timeout for landing.
int target_cable_cnt_timeout () const
The timeout for following a cable.
int disarm_on_cable_cnt_timeout () const
The timeout for disarming the drone on the cable.
float dt () const
The time step for the trajectory controller.
bool use_cartesian_PID () const
Whether to use Cartesian PID control for the trajectory controller.
float cartesian_PID_Kp () const
The proportional gain for the Cartesian PID controller.
float cartesian_PID_Ki () const
The integral gain for the Cartesian PID controller.
float cartesian_PID_Kd () const
The derivative gain for the Cartesian PID controller.
float cartesian_PID_integral_reset_error_threshold () const
The error threshold to reset the integral term for the Cartesian PID controller.
int MPC_N () const
The number of points used in the MPC trajectory.
bool MPC_use_state_feedback () const
Whether to use state feedback for the MPC.
float direct_target_setpoint_dist_threshold () const
The distance threshold to use direct target setpoint.
float cable_landing_target_upwards_velocity () const
The upwards velocity to use for cable landing target.
const std::string drone_frame_id () const
Get the drone frame ID.
const std::string world_frame_id () const
Get the world frame ID.
const std::string cable_gripper_frame_id () const
Get the cable gripper frame ID.
const std::string mmwave_frame_id () const
Get the mmWave frame ID.
const std::shared_ptr< const control::BehaviorStateParameters > behavior_state_parameters () const
Get the behavior state parameters object.
Public Member Functions inherited from iii_drone::configuration::Configurator
Configurator (rclcpp::Node *node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Configurator (rclcpp::Node *node, const rclcpp::QoS &qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
~Configurator ()
template<typename T >
void DeclareParameter (const std::string &name)
rclcpp::Parameter GetParameter (const std::string &name) const
Get a parameter.
std::vector< rclcpp::Parameter > GetParameters (const std::vector< std::string > &names) const
Gets multiple parameters.
void SyncParameters (const std::vector< std::string > &names={})
Synchronizes parameters with the parameter server. Should never be necessary.
void PrintParameters () const
Prints all parameters to the console.
Private Member Functions
void declareNodeParameters ()
Declares the node specific parameters.
void initBehaviorStateParameters ()
Initializes the behavior state parameters.
void updateBehavorStateParametersObjectCallback (const rclcpp::Parameter &parameter)
Callback function called after successful parameter change to update BehaviorStateParameters object.
Private Attributes
std::shared_ptr< control::BehaviorStateParameters > behavior_state_parameters_
Behavior state parameters object.
bool behavior_state_parameters_initialized_ = false
BehaviorStateParameters object initialized flag.
std::function< void(const rclcpp::Parameter &) after_parameter_change_callback_)
Callback function reference called after successful parameter change.
Additional Inherited Members
Static Public Member Functions inherited from iii_drone::configuration::Configurator
template<typename T >
static std::string GetParameterTypeString ()
Static function for getting string representation of a parameter type from template type.
Protected Attributes inherited from iii_drone::configuration::Configurator
rclcpp::Node * node_
Detailed Description
Class for handling parameters for FlightController.
Definition at line 37 of file flight_controller_node_configurator.hpp.
Constructor & Destructor Documentation
FlightControllerConfigurator() [1/2]
FlightControllerConfigurator::FlightControllerConfigurator (rclcpp::Node * node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback = nullptr)
Constructor.
Parameters
node Reference to the handling node
after_parameter_change_callback Callback function called after successful parameter change, default is nullptr
Definition at line 14 of file flight_controller_node_configurator.cpp.
  : Configurator(
        node,
        std::bind(
            &FlightControllerConfigurator::updateBehavorStateParametersObjectCallback,
            this,
            std::placeholders::_1
        )
    ),
    after_parameter_change_callback_(after_parameter_change_callback) {
    declareNodeParameters();
    initBehaviorStateParameters();
}
References declareNodeParameters(), and initBehaviorStateParameters().
FlightControllerConfigurator() [2/2]
FlightControllerConfigurator::FlightControllerConfigurator (rclcpp::Node * node, const rclcpp::QoS & qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback = nullptr)
Constructor.
Parameters
node Reference to the handling node
qos QoS profile for the parameter event subscription
after_parameter_change_callback Callback function called after successful parameter change, default is nullptr
Definition at line 32 of file flight_controller_node_configurator.cpp.
  : Configurator(
        node,
        qos,
        std::bind(
            &FlightControllerConfigurator::updateBehavorStateParametersObjectCallback,
            this,
            std::placeholders::_1
        )
    ),
    after_parameter_change_callback_(after_parameter_change_callback) {
    declareNodeParameters();
    initBehaviorStateParameters();
}
References declareNodeParameters(), and initBehaviorStateParameters().
Member Function Documentation
always_armed_for_debug()
bool FlightControllerConfigurator::always_armed_for_debug () const
Whether the drone should always be armed for debug purposes.
Returns
bool The value of the parameter
Definition at line 52 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/always_armed_for_debug").as_bool();
}
References iii_drone::configuration::Configurator::GetParameter().
always_hover_in_offboard()
bool FlightControllerConfigurator::always_hover_in_offboard () const
Whether the drone should always hover in offboard mode.
Returns
bool The value of the parameter
Definition at line 136 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/always_hover_in_offboard").as_bool();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by iii_drone::control::flight_controller_node::FlightController::FlightController().
arm_cnt_timeout()
int FlightControllerConfigurator::arm_cnt_timeout () const
The timeout for arming the drone.
Returns
int The value of the parameter
Definition at line 214 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/arm_cnt_timeout").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
arming_on_cable_spool_up_time_s()
float FlightControllerConfigurator::arming_on_cable_spool_up_time_s () const
The time to spool up the motor when arming the drone on the cable.
Returns
float The value of the parameter
Definition at line 202 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/arming_on_cable_spool_up_time_s").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
behavior_state_parameters()
const std::shared_ptr< const iii_drone::control::BehaviorStateParameters > FlightControllerConfigurator::behavior_state_parameters () const
Get the behavior state parameters object.
Returns
Behavior state parameters object reference
Definition at line 328 of file flight_controller_node_configurator.cpp.
{
    return behavior_state_parameters_;
}
References behavior_state_parameters_.
cable_gripper_frame_id()
const std::string FlightControllerConfigurator::cable_gripper_frame_id () const
Get the cable gripper frame ID.
Returns
Cable gripper frame ID
Definition at line 316 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/tf/cable_gripper_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
cable_landing_target_upwards_velocity()
float FlightControllerConfigurator::cable_landing_target_upwards_velocity () const
The upwards velocity to use for cable landing target.
Returns
float The value of the parameter
Definition at line 298 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/cable_landing_target_upwards_velocity").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
cartesian_PID_integral_reset_error_threshold()
float FlightControllerConfigurator::cartesian_PID_integral_reset_error_threshold () const
The error threshold to reset the integral term for the Cartesian PID controller.
Returns
float The value of the parameter
Definition at line 274 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/cartesian_PID_integral_reset_error_threshold").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
cartesian_PID_Kd()
float FlightControllerConfigurator::cartesian_PID_Kd () const
The derivative gain for the Cartesian PID controller.
Returns
float The value of the parameter
Definition at line 268 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/cartesian_PID_Kd").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
cartesian_PID_Ki()
float FlightControllerConfigurator::cartesian_PID_Ki () const
The integral gain for the Cartesian PID controller.
Returns
float The value of the parameter
Definition at line 262 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/cartesian_PID_Ki").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
cartesian_PID_Kp()
float FlightControllerConfigurator::cartesian_PID_Kp () const
The proportional gain for the Cartesian PID controller.
Returns
float The value of the parameter
Definition at line 256 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/cartesian_PID_Kp").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
declareNodeParameters()
void FlightControllerConfigurator::declareNodeParameters () private
Declares the node specific parameters.
Returns
void
Definition at line 334 of file flight_controller_node_configurator.cpp.
{
    DeclareParameter<bool>("/control/flight_controller/always_armed_for_debug");
    DeclareParameter<float>("/control/flight_controller/landed_altitude_threshold");
    DeclareParameter<bool>("/control/flight_controller/use_ground_altitude_offset");
    DeclareParameter<float>("/control/flight_controller/reached_position_euclidean_distance_threshold");
    DeclareParameter<float>("/control/flight_controller/minimum_target_altitude");
    DeclareParameter<float>("/control/flight_controller/target_cable_fixed_position_distance_threshold");
    DeclareParameter<float>("/control/flight_controller/target_cable_safety_margin_distance_threshold");
    DeclareParameter<float>("/control/flight_controller/target_cable_safety_margin_max_euc_distance");
    DeclareParameter<float>("/control/flight_controller/target_cable_safety_margin_max_euc_velocity");
    DeclareParameter<float>("/control/flight_controller/target_cable_safety_margin_max_euc_acceleration");
    DeclareParameter<float>("/control/flight_controller/target_cable_safety_margin_max_yaw_distance");
    DeclareParameter<float>("/control/flight_controller/target_cable_safety_margin_max_yaw_velocity");
    DeclareParameter<float>("/control/flight_controller/target_cable_set_point_truncate_distance_threshold");
    DeclareParameter<float>("/control/flight_controller/landed_on_powerline_non_offboard_max_euc_distance");
    DeclareParameter<bool>("/control/flight_controller/always_hover_in_offboard");
    DeclareParameter<std::string>("/control/flight_controller/on_cable_control_mode");
    DeclareParameter<float>("/control/flight_controller/on_cable_upwards_thrust");
    DeclareParameter<float>("/control/flight_controller/on_cable_upwards_velocity");
    DeclareParameter<bool>("/control/flight_controller/use_gripper_status_condition");
    DeclareParameter<bool>("/control/flight_controller/hover_under_cable_on_aborted_cable_landing");
    DeclareParameter<float>("/control/flight_controller/disarming_on_cable_max_descend_distance");
    DeclareParameter<std::string>("/control/flight_controller/disarm_on_cable_mode");
    DeclareParameter<float>("/control/flight_controller/disarm_on_cable_thrust_decrease_time_s");
    DeclareParameter<float>("/control/flight_controller/disarm_on_cable_thrust_wait_for_disarm_time_s");
    DeclareParameter<float>("/control/flight_controller/disarm_on_cable_flight_termination_timeout_s");
    DeclareParameter<float>("/control/flight_controller/arming_on_cable_spool_up_time_s");
    DeclareParameter<bool>("/control/flight_controller/update_home_position");
    DeclareParameter<int>("/control/flight_controller/arm_cnt_timeout");
    DeclareParameter<int>("/control/flight_controller/offboard_cnt_timeout");
    DeclareParameter<int>("/control/flight_controller/land_cnt_timeout");
    DeclareParameter<int>("/control/flight_controller/target_cable_cnt_timeout");
    DeclareParameter<int>("/control/flight_controller/disarm_on_cable_cnt_timeout");
    DeclareParameter<float>("/control/flight_controller/dt");
    DeclareParameter<bool>("/control/flight_controller/use_cartesian_PID");
    DeclareParameter<float>("/control/flight_controller/cartesian_PID_Kp");
    DeclareParameter<float>("/control/flight_controller/cartesian_PID_Ki");
    DeclareParameter<float>("/control/flight_controller/cartesian_PID_Kd");
    DeclareParameter<float>("/control/flight_controller/cartesian_PID_integral_reset_error_threshold");
    DeclareParameter<int>("/control/flight_controller/MPC_N");
    DeclareParameter<bool>("/control/flight_controller/MPC_use_state_feedback");
    DeclareParameter<float>("/control/flight_controller/direct_target_setpoint_dist_threshold");
    DeclareParameter<float>("/control/flight_controller/cable_landing_target_upwards_velocity");
    DeclareParameter<std::string>("/tf/drone_frame_id");
    DeclareParameter<std::string>("/tf/world_frame_id");
    DeclareParameter<std::string>("/tf/cable_gripper_frame_id");
    DeclareParameter<std::string>("/tf/mmwave_frame_id");
}
References Configurator::DeclareParameter< std::string >(), and iii_drone::configuration::Configurator::GetParameterTypeString().
Referenced by FlightControllerConfigurator(), and FlightControllerConfigurator().
direct_target_setpoint_dist_threshold()
float FlightControllerConfigurator::direct_target_setpoint_dist_threshold () const
The distance threshold to use direct target setpoint.
Returns
float The value of the parameter
Definition at line 292 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/direct_target_setpoint_dist_threshold").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
disarm_on_cable_cnt_timeout()
int FlightControllerConfigurator::disarm_on_cable_cnt_timeout () const
The timeout for disarming the drone on the cable.
Returns
int The value of the parameter
Definition at line 238 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/disarm_on_cable_cnt_timeout").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
disarm_on_cable_flight_termination_timeout_s()
float FlightControllerConfigurator::disarm_on_cable_flight_termination_timeout_s () const
The timeout to terminate the flight when disarming the drone on the cable.
Returns
float The value of the parameter
Definition at line 196 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/disarm_on_cable_flight_termination_timeout_s").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
disarm_on_cable_mode()
const std::string FlightControllerConfigurator::disarm_on_cable_mode () const
The disarm mode to use when the drone is on the cable.
Returns
std::string The value of the parameter
Definition at line 178 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/disarm_on_cable_mode").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
disarm_on_cable_thrust_decrease_time_s()
float FlightControllerConfigurator::disarm_on_cable_thrust_decrease_time_s () const
The time to decrease the thrust to zero when disarming the drone on the cable.
Returns
float The value of the parameter
Definition at line 184 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/disarm_on_cable_thrust_decrease_time_s").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
disarm_on_cable_thrust_wait_for_disarm_time_s()
float FlightControllerConfigurator::disarm_on_cable_thrust_wait_for_disarm_time_s () const
The time to wait for disarm after the thrust is zero when disarming the drone on the cable.
Returns
float The value of the parameter
Definition at line 190 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/disarm_on_cable_thrust_wait_for_disarm_time_s").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
disarming_on_cable_max_descend_distance()
float FlightControllerConfigurator::disarming_on_cable_max_descend_distance () const
The maximum descend distance to disarm the drone when the drone is on the cable.
Returns
float The value of the parameter
Definition at line 172 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/disarming_on_cable_max_descend_distance").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
drone_frame_id()
const std::string FlightControllerConfigurator::drone_frame_id () const
Get the drone frame ID.
Returns
Drone frame ID
Definition at line 304 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/tf/drone_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
dt()
float FlightControllerConfigurator::dt () const
The time step for the trajectory controller.
Returns
float The value of the parameter
Definition at line 244 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/dt").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by iii_drone::control::flight_controller_node::FlightController::FlightController().
hover_under_cable_on_aborted_cable_landing()
bool FlightControllerConfigurator::hover_under_cable_on_aborted_cable_landing () const
Whether to perform cable takeoff followed by hovering under cable on aborted cable landing.
Returns
bool The value of the parameter
Definition at line 160 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/hover_under_cable_on_aborted_cable_landing").as_bool();
}
References iii_drone::configuration::Configurator::GetParameter().
initBehaviorStateParameters()
void FlightControllerConfigurator::initBehaviorStateParameters () private
Initializes the behavior state parameters.
Definition at line 386 of file flight_controller_node_configurator.cpp.
{
    behavior_state_parameters_ = std::make_shared<iii_drone::control::BehaviorStateParameters>(
        GetParameter("/control/flight_controller/landed_altitude_threshold").as_double(),
        GetParameter("/control/flight_controller/on_cable_max_euc_distance").as_double(),
        GetParameter("/control/flight_controller/minimum_target_altitude").as_double(),
        GetParameter("/tf/cable_gripper_frame_id").as_string(),
        GetParameter("/tf/drone_frame_id").as_string(),
        GetParameter("/tf/world_frame_id").as_string()
    );
    behavior_state_parameters_initialized_ = true;
}
References behavior_state_parameters_, behavior_state_parameters_initialized_, iii_drone::configuration::Configurator::GetParameter(), and iii_drone::configuration::Configurator::GetParameterTypeString().
Referenced by FlightControllerConfigurator(), and FlightControllerConfigurator().
land_cnt_timeout()
int FlightControllerConfigurator::land_cnt_timeout () const
The timeout for landing.
Returns
int The value of the parameter
Definition at line 226 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/land_cnt_timeout").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
landed_altitude_threshold()
float FlightControllerConfigurator::landed_altitude_threshold () const
The altitude threshold for considering the drone landed.
Returns
float The value of the parameter
Definition at line 58 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/landed_altitude_threshold").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
landed_on_powerline_non_offboard_max_euc_distance()
float FlightControllerConfigurator::landed_on_powerline_non_offboard_max_euc_distance () const
The maximum euclidean distance between the drone and the powerline to consider the drone landed on the powerline when the drone is not in offboard mode.
Returns
float The value of the parameter
Definition at line 130 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/landed_on_powerline_non_offboard_max_euc_distance").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
minimum_target_altitude()
float FlightControllerConfigurator::minimum_target_altitude () const
The minimum altitude to be used when the target altitude is below it.
Returns
float The value of the parameter
Definition at line 76 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/minimum_target_altitude").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
mmwave_frame_id()
const std::string FlightControllerConfigurator::mmwave_frame_id () const
Get the mmWave frame ID.
Returns
mmWave frame ID
Definition at line 322 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/tf/mmwave_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
MPC_N()
int FlightControllerConfigurator::MPC_N () const
The number of points used in the MPC trajectory.
Returns
int The value of the parameter
Definition at line 280 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/MPC_N").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
MPC_use_state_feedback()
bool FlightControllerConfigurator::MPC_use_state_feedback () const
Whether to use state feedback for the MPC.
Returns
bool The value of the parameter
Definition at line 286 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/MPC_use_state_feedback").as_bool();
}
References iii_drone::configuration::Configurator::GetParameter().
offboard_cnt_timeout()
int FlightControllerConfigurator::offboard_cnt_timeout () const
The timeout for offboard mode.
Returns
int The value of the parameter
Definition at line 220 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/offboard_cnt_timeout").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
on_cable_control_mode()
const std::string FlightControllerConfigurator::on_cable_control_mode () const
The control mode to use when the drone is on the cable.
Returns
std::string The value of the parameter
Definition at line 142 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/on_cable_control_mode").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
on_cable_upwards_thrust()
float FlightControllerConfigurator::on_cable_upwards_thrust () const
The upwards thrust to apply when the drone is on the cable.
Returns
float The value of the parameter
Definition at line 148 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/on_cable_upwards_thrust").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
on_cable_upwards_velocity()
float FlightControllerConfigurator::on_cable_upwards_velocity () const
The upwards velocity to apply when the drone is on the cable.
Returns
float The value of the parameter
Definition at line 154 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/on_cable_upwards_velocity").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
reached_position_euclidean_distance_threshold()
float FlightControllerConfigurator::reached_position_euclidean_distance_threshold () const
The threshold for considering the drone reached the target position.
Returns
float The value of the parameter
Definition at line 70 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/reached_position_euclidean_distance_threshold").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
target_cable_cnt_timeout()
int FlightControllerConfigurator::target_cable_cnt_timeout () const
The timeout for following a cable.
Returns
int The value of the parameter
Definition at line 232 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/target_cable_cnt_timeout").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
target_cable_fixed_position_distance_threshold()
float FlightControllerConfigurator::target_cable_fixed_position_distance_threshold () const
The distance threshold to consider the target position reached when the drone is following a cable.
Returns
float The value of the parameter
Definition at line 82 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/target_cable_fixed_position_distance_threshold").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
target_cable_safety_margin_distance_threshold()
float FlightControllerConfigurator::target_cable_safety_margin_distance_threshold () const
The distance threshold to consider the target position reached when the drone is following a cable.
Returns
float The value of the parameter
Definition at line 88 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/target_cable_safety_margin_distance_threshold").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
target_cable_safety_margin_max_euc_acceleration()
float FlightControllerConfigurator::target_cable_safety_margin_max_euc_acceleration () const
The maximum euclidean acceleration between the drone and the target position to consider the target position reached when the drone is following a cable.
Returns
float The value of the parameter
Definition at line 106 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/target_cable_safety_margin_max_euc_acceleration").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
target_cable_safety_margin_max_euc_distance()
float FlightControllerConfigurator::target_cable_safety_margin_max_euc_distance () const
The maximum euclidean distance between the drone and the target position to consider the target position reached when the drone is following a cable.
Returns
float The value of the parameter
Definition at line 94 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/target_cable_safety_margin_max_euc_distance").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
target_cable_safety_margin_max_euc_velocity()
float FlightControllerConfigurator::target_cable_safety_margin_max_euc_velocity () const
The maximum euclidean velocity between the drone and the target position to consider the target position reached when the drone is following a cable.
Returns
float The value of the parameter
Definition at line 100 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/target_cable_safety_margin_max_euc_velocity").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
target_cable_safety_margin_max_yaw_distance()
float FlightControllerConfigurator::target_cable_safety_margin_max_yaw_distance () const
The maximum yaw distance between the drone and the target position to consider the target position reached when the drone is following a cable.
Returns
float The value of the parameter
Definition at line 112 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/target_cable_safety_margin_max_yaw_distance").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
target_cable_safety_margin_max_yaw_velocity()
float FlightControllerConfigurator::target_cable_safety_margin_max_yaw_velocity () const
The maximum yaw velocity between the drone and the target position to consider the target position reached when the drone is following a cable.
Returns
float The value of the parameter
Definition at line 118 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/target_cable_safety_margin_max_yaw_velocity").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
target_cable_set_point_truncate_distance_threshold()
float FlightControllerConfigurator::target_cable_set_point_truncate_distance_threshold () const
The distance threshold to truncate the setpoint when the drone is following a cable.
Returns
float The value of the parameter
Definition at line 124 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/target_cable_set_point_truncate_distance_threshold").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
update_home_position()
bool FlightControllerConfigurator::update_home_position () const
Whether to update the home position.
Returns
bool The value of the parameter
Definition at line 208 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/update_home_position").as_bool();
}
References iii_drone::configuration::Configurator::GetParameter().
updateBehavorStateParametersObjectCallback()
void FlightControllerConfigurator::updateBehavorStateParametersObjectCallback (const rclcpp::Parameter & parameter) private
Callback function called after successful parameter change to update BehaviorStateParameters object.
Definition at line 401 of file flight_controller_node_configurator.cpp.
{
    if (parameter.get_name() == "/control/flight_controller/landed_altitude_threshold") {
        behavior_state_parameters_->landed_altitude_threshold() = parameter.as_double();
    } else if (parameter.get_name() == "/control/flight_controller/on_cable_max_euc_distance") {
        behavior_state_parameters_->on_cable_max_euc_distance() = parameter.as_double();
    } else if (parameter.get_name() == "/control/flight_controller/minimum_target_altitude") {
        behavior_state_parameters_->minimum_target_altitude() = parameter.as_double();
    } else if (parameter.get_name() == "/tf/cable_gripper_frame_id") {
        behavior_state_parameters_->cable_gripper_frame_id() = parameter.as_string();
    } else if (parameter.get_name() == "/tf/drone_frame_id") {
        behavior_state_parameters_->drone_frame_id() = parameter.as_string();
    } else if (parameter.get_name() == "/tf/world_frame_id") {
        behavior_state_parameters_->world_frame_id() = parameter.as_string();
    }
    after_parameter_change_callback_(parameter);
}
References after_parameter_change_callback_, behavior_state_parameters_, and iii_drone::configuration::Configurator::GetParameterTypeString().
use_cartesian_PID()
bool FlightControllerConfigurator::use_cartesian_PID () const
Whether to use Cartesian PID control for the trajectory controller.
Returns
bool The value of the parameter
Definition at line 250 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/use_cartesian_PID").as_bool();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by iii_drone::control::flight_controller_node::FlightController::FlightController().
use_gripper_status_condition()
bool FlightControllerConfigurator::use_gripper_status_condition () const
Whether to use the gripper status condition when the drone is on the cable.
Returns
bool The value of the parameter
Definition at line 166 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/use_gripper_status_condition").as_bool();
}
References iii_drone::configuration::Configurator::GetParameter().
use_ground_altitude_offset()
bool FlightControllerConfigurator::use_ground_altitude_offset () const
Whether the drone should use ground altitude offset.
Returns
bool The value of the parameter
Definition at line 64 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/control/flight_controller/use_ground_altitude_offset").as_bool();
}
References iii_drone::configuration::Configurator::GetParameter().
world_frame_id()
const std::string FlightControllerConfigurator::world_frame_id () const
Get the world frame ID.
Returns
World frame ID
Definition at line 310 of file flight_controller_node_configurator.cpp.
{
    return GetParameter("/tf/world_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
Member Data Documentation
after_parameter_change_callback_
std::function<void(const rclcpp::Parameter &) iii_drone::control::flight_controller_node::FlightControllerConfigurator::after_parameter_change_callback_) private
Callback function reference called after successful parameter change.
Definition at line 424 of file flight_controller_node_configurator.hpp.
Referenced by updateBehavorStateParametersObjectCallback().
behavior_state_parameters_
std::shared_ptr<control::BehaviorStateParameters> iii_drone::control::flight_controller_node::FlightControllerConfigurator::behavior_state_parameters_ private
Behavior state parameters object.
Definition at line 397 of file flight_controller_node_configurator.hpp.
Referenced by behavior_state_parameters(), initBehaviorStateParameters(), and updateBehavorStateParametersObjectCallback().
behavior_state_parameters_initialized_
bool iii_drone::control::flight_controller_node::FlightControllerConfigurator::behavior_state_parameters_initialized_ = false private
BehaviorStateParameters object initialized flag.
Definition at line 402 of file flight_controller_node_configurator.hpp.
Referenced by initBehaviorStateParameters().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/_flight_controller_node/flight_controller_node_configurator.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/_flight_controller_node/flight_controller_node_configurator.cpp