III-Drone: iii_drone::control::maneuver::FlyToObjectManeuverServer Class Reference
iii_drone::control::maneuver::FlyToObjectManeuverServer Class Reference
Class for serving flying to an object.
#include <fly_to_object_maneuver_server.hpp>
Public Member Functions
FlyToObjectManeuverServer (rclcpp::Node *node, CombinedDroneAwarenessHandler::SharedPtr combined_drone_awareness_handler, const std::string &action_name, unsigned int wait_for_execute_poll_ms, unsigned int evaluate_done_poll_ms, iii_drone::control::maneuver::FlyToObjectManeuverServerParameters::SharedPtr fly_to_object_maneuver_server_parameters, iii_drone::control::TrajectoryGeneratorClient::SharedPtr trajectory_generator_client)
Constructor.
bool CanExecuteManeuver (const Maneuver &maneuver, const combined_drone_awareness_t &drone_awareness) const override
Whether the maneuver can be executed.
combined_drone_awareness_t ExpectedAwarenessAfterExecution (const Maneuver &maneuver) override
Expected awareness after execution.
Public Member Functions inherited from iii_drone::control::maneuver::ManeuverServer
ManeuverServer (rclcpp::Node *node, CombinedDroneAwarenessHandler::SharedPtr awareness_handler, const std::string &action_name, unsigned int wait_for_execute_poll_ms, unsigned int evaluate_done_poll_ms)
Constructor.
void Start (std::function< bool(Maneuver, bool &)> register_maneuver_function, std::function< bool(Maneuver)> update_manuever_function, std::function< bool(Maneuver)> cancel_maneuver_function, std::function< bool(Maneuver)> verify_maneuver_in_queue_function, std::function< bool(Maneuver)> verify_maneuver_active_function, std::function< void(Maneuver)> done_callback, ReferenceCallbackToken::SharedPtr reference_callback_token, std::map< iii_drone::control::maneuver::maneuver_type_t, std::shared_ptr< ManeuverServer > > registered_maneuvers)
Method to start the maneuver server. The maneuver server will reject any new goals until started.
void Stop ()
Method to stop the maneuver server. The maneuver server will reject any new goals until started.
std::string action_name () const
Action name getter.
bool running () const
Returns whether the maneuver server is running.
Private Types
using FlyToObject = iii_drone_interfaces::action::FlyToObject
using GoalHandleFlyToObject = rclcpp_action::ServerGoalHandle<FlyToObject>
Private Member Functions
maneuver_type_t maneuver_type () const override
The maneuver type (MANEUVER_TYPE_FLY_TO_OBJECT)
void startExecution (Maneuver &maneuver) override
Starts the execution of the maneuver.
bool canCancel () override
Whether the maneuver can be canceled, always returns true.
iii_drone::control::Reference computeReference (const iii_drone::control::State &state) override
Compute the reference.
bool hasSucceeded (Maneuver &maneuver) override
Whether the maneuver has succeeded, returns true if the drone is within the position tolerance.
bool hasFailed (Maneuver &maneuver) override
Whether the maneuver has failed.
void publishFeedback (Maneuver &maneuver) override
Publishes the feedback.
void publishResultAndFinalize (Maneuver &maneuver, maneuver_result_type_t maneuver_result_type) override
Publishes the result and finalizes the maneuver according to the maneuver result type.
void registerReferenceCallbackOnSuccess (const Maneuver &maneuver) override
Registers the hover by object reference callback on success.
iii_drone::control::Reference getUpdatedTargetReference (const iii_drone::control::State &state)
Get updated target reference. Sets the has_failed flag if the target is not visible.
Private Attributes
iii_drone::control::maneuver::FlyToObjectManeuverServerParameters::SharedPtr parameters_
The fly to object maneuver server parameters shared pointer.
iii_drone::control::TrajectoryGeneratorClient::SharedPtr trajectory_generator_client_
The trajectory generator client shared pointer.
iii_drone::utils::Atomic< iii_drone::adapters::TargetAdapter > target_adapter_
The hover reference target adapter.
iii_drone::utils::Atomic< bool > first_iteration_ = true
Flag for first iteration.
iii_drone::utils::Atomic< bool > has_failed_ = false
Has failed flag.
Additional Inherited Members
Public Types inherited from iii_drone::control::maneuver::ManeuverServer
typedef std::shared_ptr< ManeuverServer > SharedPtr
Shared pointer type.
Protected Types inherited from iii_drone::control::maneuver::ManeuverServer
enum maneuver_result_type_t { MANEUVER_RESULT_TYPE_SUCCEED , MANEUVER_RESULT_TYPE_CANCEL , MANEUVER_RESULT_TYPE_ABORT }
Maneuver result type enum.
Protected Member Functions inherited from iii_drone::control::maneuver::ManeuverServer
const CombinedDroneAwarenessHandler::SharedPtr & awareness_handler () const
Combined drone awareness handler, accessible to derived classes through the protected method.
const iii_drone::utils::Atomic< iii_drone::control::maneuver::Maneuver > & current_maneuver () const
The currently executing maneuver, accessible to derived classes through the protected method.
rclcpp::Node * node () const
Node pointer getter.
std::map< iii_drone::control::maneuver::maneuver_type_t, std::shared_ptr< iii_drone::control::maneuver::ManeuverServer > > registered_maneuvers () const
Registered maneuvers map getter.
void registerCallback (const std::function< Reference(const State &)> &callback)
Registers a callback function for the reference. The callback function should be registered with the reference callback token.
template<typename ActionT >
void createServer ()
Creates the underlying action server.
Detailed Description
Class for serving flying to an object.
Definition at line 44 of file fly_to_object_maneuver_server.hpp.
Member Typedef Documentation
FlyToObject
using iii_drone::control::maneuver::FlyToObjectManeuverServer::FlyToObject = iii_drone_interfaces::action::FlyToObject private
Definition at line 45 of file fly_to_object_maneuver_server.hpp.
GoalHandleFlyToObject
using iii_drone::control::maneuver::FlyToObjectManeuverServer::GoalHandleFlyToObject = rclcpp_action::ServerGoalHandle<FlyToObject> private
Definition at line 46 of file fly_to_object_maneuver_server.hpp.
Constructor & Destructor Documentation
FlyToObjectManeuverServer()
FlyToObjectManeuverServer::FlyToObjectManeuverServer (rclcpp::Node * node, CombinedDroneAwarenessHandler::SharedPtr combined_drone_awareness_handler, const std::string & action_name, unsigned int wait_for_execute_poll_ms, unsigned int evaluate_done_poll_ms, iii_drone::control::maneuver::FlyToObjectManeuverServerParameters::SharedPtr fly_to_object_maneuver_server_parameters, iii_drone::control::TrajectoryGeneratorClient::SharedPtr trajectory_generator_client)
Constructor.
Parameters
node Node pointer
combined_drone_awareness_handler Combined drone awareness handler pointer
action_name Action name
wait_for_execute_poll_ms Wait for execute poll milliseconds
evaluate_done_poll_ms Evaluate done poll milliseconds
fly_to_object_maneuver_server_parameters Fly to object maneuver server parameters
trajectory_generator_client Trajectory generator client shared pointer
Definition at line 17 of file fly_to_object_maneuver_server.cpp.
  : ManeuverServer(
    node,
    combined_drone_awareness_handler,
    action_name,
    wait_for_execute_poll_ms,
    evaluate_done_poll_ms
),  parameters_(parameters),
    trajectory_generator_client_(trajectory_generator_client) {
    createServer<FlyToObject>();
}
Member Function Documentation
canCancel()
bool FlyToObjectManeuverServer::canCancel () override private virtual
Whether the maneuver can be canceled, always returns true.
Returns
bool Whether the maneuver can be canceled.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 138 of file fly_to_object_maneuver_server.cpp.
{
    return true;
}
CanExecuteManeuver()
bool FlyToObjectManeuverServer::CanExecuteManeuver (const Maneuver & maneuver, const combined_drone_awareness_t & drone_awareness) const override virtual
Whether the maneuver can be executed.
Parameters
maneuver The maneuver.
drone_awareness The drone awareness.
Returns
bool Whether the maneuver can be executed.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 38 of file fly_to_object_maneuver_server.cpp.
        {
    if (maneuver.maneuver_type() != MANEUVER_TYPE_FLY_TO_OBJECT) {
        return false;
    }
    auto cda_handler = awareness_handler();
    fly_to_object_maneuver_params_t params(maneuver.maneuver_params());
    if (params.target_adapter.target_type() != TARGET_TYPE_CABLE) {
        return false;
    }
    if (!drone_awareness.offboard) {
        return false;
    }
    if (!drone_awareness.armed) {
        return false;
    }
    if (!drone_awareness.in_flight()) {
        return false;
    }
    transform_matrix_t target_transform;
    try {
        target_transform = awareness_handler()->ComputeTargetTransform(target_adapter_);
    } catch (const std::runtime_error &e) {
        return false;
    }
    point_t target_position_in_world_frame = target_transform.block<3, 1>(0, 3);
    bool target_position_valid = target_position_in_world_frame[2] - cda_handler->ground_altitude_estimate() >= parameters_->minimum_target_altitude();
    return target_position_valid;
}
References iii_drone::control::combined_drone_awareness_t::armed, iii_drone::control::maneuver::ManeuverServer::awareness_handler(), iii_drone::control::CombinedDroneAwarenessHandler::ComputeTargetTransform(), iii_drone::control::combined_drone_awareness_t::in_flight(), iii_drone::control::maneuver::Maneuver::maneuver_params(), iii_drone::control::maneuver::Maneuver::maneuver_type(), iii_drone::control::maneuver::MANEUVER_TYPE_FLY_TO_OBJECT, iii_drone::control::maneuver::FlyToObjectManeuverServerParameters::minimum_target_altitude(), iii_drone::control::combined_drone_awareness_t::offboard, parameters_, iii_drone::control::maneuver::fly_to_object_maneuver_params_t::target_adapter, target_adapter_, iii_drone::adapters::TargetAdapter::target_type(), and iii_drone::adapters::TARGET_TYPE_CABLE.
computeReference()
Reference FlyToObjectManeuverServer::computeReference (const iii_drone::control::State & state) override private virtual
Compute the reference.
Parameters
state The current state.
Returns
The reference.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 142 of file fly_to_object_maneuver_server.cpp.
{
    Reference target_reference = getUpdatedTargetReference(state);
    Reference ref;
    if (parameters_->generate_trajectories_asynchronously_with_delay()) {
        if (first_iteration_) {
            if (trajectory_generator_client_->busy()) {
                std::string error_message = "FlyToObjectManeuverServer::computeReference(): Trajectory generator client is busy on first iteration, cannot start execution of maneuver.";
                RCLCPP_FATAL(node()->get_logger(), error_message.c_str());
                throw std::runtime_error(error_message);
            }
            trajectory_generator_client_->Reset(state);
            ref = trajectory_generator_client_->GetReferenceTrajectory().references()[0];
            trajectory_generator_client_->ComputeReferenceTrajectoryAsync(
                state,
                target_reference,
                true,
                true,
                MPC_mode_t::positional
            );
            first_iteration_ = false;
        } else {
            while (!trajectory_generator_client_->done()) {
                rclcpp::sleep_for(std::chrono::milliseconds(parameters_->generate_trajectories_poll_period_ms()));
            }
            ref = trajectory_generator_client_->GetReferenceTrajectory().references()[1];
            trajectory_generator_client_->ComputeReferenceTrajectoryAsync(
                state,
                target_reference,
                true,
                false,
                MPC_mode_t::positional
            );
        }
    } else {
        if (trajectory_generator_client_->busy()) {
            std::string error_message = "FlyToObjectManeuverServer::computeReference(): Trajectory generator client is busy on first iteration, cannot start execution of maneuver.";
            RCLCPP_FATAL(node()->get_logger(), error_message.c_str());
            throw std::runtime_error(error_message);
        }
        bool first_it = first_iteration_;
        if (first_it) {
            trajectory_generator_client_->Reset(state);
            first_iteration_ = false;
        }
        trajectory_generator_client_->ComputeReferenceTrajectoryBlocking(
            state,
            target_reference,
            true,
            first_it,
            MPC_mode_t::positional,
            parameters_->generate_trajectories_poll_period_ms()
        );
        ref = trajectory_generator_client_->GetReferenceTrajectory().references()[0];
    }
    return ref;
}
References iii_drone::control::TrajectoryGeneratorClient::busy(), iii_drone::control::TrajectoryGeneratorClient::ComputeReferenceTrajectoryAsync(), iii_drone::control::TrajectoryGeneratorClient::ComputeReferenceTrajectoryBlocking(), iii_drone::control::TrajectoryGeneratorClient::done(), first_iteration_, iii_drone::control::maneuver::FlyToObjectManeuverServerParameters::generate_trajectories_asynchronously_with_delay(), iii_drone::control::maneuver::FlyToObjectManeuverServerParameters::generate_trajectories_poll_period_ms(), iii_drone::control::TrajectoryGeneratorClient::GetReferenceTrajectory(), getUpdatedTargetReference(), iii_drone::control::maneuver::ManeuverServer::node(), parameters_, iii_drone::control::positional, iii_drone::control::ReferenceTrajectory::references(), iii_drone::control::TrajectoryGeneratorClient::Reset(), and trajectory_generator_client_.
ExpectedAwarenessAfterExecution()
combined_drone_awareness_t FlyToObjectManeuverServer::ExpectedAwarenessAfterExecution (const Maneuver & maneuver) override virtual
Expected awareness after execution.
Parameters
maneuver The maneuver.
Returns
The expected awareness after execution.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 87 of file fly_to_object_maneuver_server.cpp.
{
    fly_to_object_maneuver_params_t params(maneuver.maneuver_params());
    TargetAdapter target_adapter = params.target_adapter;
    if (target_adapter.target_type() != TARGET_TYPE_CABLE) {
        throw std::runtime_error("FlyToObjectManeuverServer::ExpectedAwarenessAfterExecution(): Target type is not TARGET_TYPE_CABLE.");
    }
    combined_drone_awareness_t awareness_after;
    awareness_after.armed = true;
    awareness_after.offboard = true;
    awareness_after.target_adapter = target_adapter;
    awareness_after.target_position_known = true;
    awareness_after.drone_location = DRONE_LOCATION_IN_FLIGHT;
    return awareness_after;
}
References iii_drone::control::combined_drone_awareness_t::armed, iii_drone::control::combined_drone_awareness_t::drone_location, iii_drone::control::DRONE_LOCATION_IN_FLIGHT, iii_drone::control::maneuver::Maneuver::maneuver_params(), iii_drone::control::combined_drone_awareness_t::offboard, iii_drone::control::combined_drone_awareness_t::target_adapter, iii_drone::control::maneuver::fly_to_object_maneuver_params_t::target_adapter, iii_drone::control::combined_drone_awareness_t::target_position_known, iii_drone::adapters::TargetAdapter::target_type(), and iii_drone::adapters::TARGET_TYPE_CABLE.
getUpdatedTargetReference()
Reference FlyToObjectManeuverServer::getUpdatedTargetReference (const iii_drone::control::State & state) private
Get updated target reference. Sets the has_failed flag if the target is not visible.
Returns
Updated target reference.
Definition at line 345 of file fly_to_object_maneuver_server.cpp.
{
    auto cda_handler = awareness_handler();
    transform_matrix_t target_transform;
    try {
        target_transform = cda_handler->ComputeTargetTransform(target_adapter_);
    } catch (const std::runtime_error &e) {
        has_failed_ = true;
        return Reference(
            state.position(),
            state.yaw()
        );
    }
    point_t target_position_in_world_frame = target_transform.block<3, 1>(0, 3);
    quaternion_t target_orientation_in_world_frame = quaternionFromTransformMatrix(target_transform);
    double target_yaw = quatToEul(target_orientation_in_world_frame)[2];
    return Reference(
        target_position_in_world_frame,
        target_yaw
    );
}
References iii_drone::control::maneuver::ManeuverServer::awareness_handler(), has_failed_, iii_drone::control::State::position(), iii_drone::types::quaternionFromTransformMatrix(), iii_drone::math::quatToEul(), target_adapter_, and iii_drone::control::State::yaw().
Referenced by computeReference(), hasSucceeded(), and publishFeedback().
hasFailed()
bool FlyToObjectManeuverServer::hasFailed (Maneuver & maneuver) override private virtual
Whether the maneuver has failed.
Parameters
maneuver The maneuver.
Returns
bool Whether the maneuver has failed.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 267 of file fly_to_object_maneuver_server.cpp.
{
    auto cda_handler = awareness_handler();
    return !cda_handler->in_flight()
        || !cda_handler->offboard()
        || !cda_handler->armed()
        || cda_handler->target_adapter().target_type() != TARGET_TYPE_CABLE
        || !cda_handler->target_position_known()
        || has_failed_;
}
References iii_drone::control::maneuver::ManeuverServer::awareness_handler(), has_failed_, and iii_drone::adapters::TARGET_TYPE_CABLE.
Referenced by hasSucceeded().
hasSucceeded()
bool FlyToObjectManeuverServer::hasSucceeded (Maneuver & maneuver) override private virtual
Whether the maneuver has succeeded, returns true if the drone is within the position tolerance.
Parameters
maneuver The maneuver.
Returns
bool Whether the maneuver has succeeded.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 235 of file fly_to_object_maneuver_server.cpp.
{
    auto cda_handler = awareness_handler();
    State state = cda_handler->GetState();
    Reference target_reference = getUpdatedTargetReference(state);
    if (hasFailed(maneuver)) {
        return false;
    }
    Eigen::Vector4d euc_pos = {
        state.position()[0],
        state.position()[1],
        state.position()[2],
        state.yaw()
    };
    Eigen::Vector4d target_euc_pos = {
        target_reference.position()[0],
        target_reference.position()[1],
        target_reference.position()[2],
        target_reference.yaw()
    };
    double distance = (euc_pos - target_euc_pos).norm();
    return distance < parameters_->reached_position_euclidean_distance_threshold();
}
References iii_drone::control::maneuver::ManeuverServer::awareness_handler(), getUpdatedTargetReference(), hasFailed(), parameters_, iii_drone::control::Reference::position(), iii_drone::control::State::position(), iii_drone::control::maneuver::FlyToObjectManeuverServerParameters::reached_position_euclidean_distance_threshold(), iii_drone::control::Reference::yaw(), and iii_drone::control::State::yaw().
maneuver_type()
maneuver_type_t FlyToObjectManeuverServer::maneuver_type () const override private virtual
The maneuver type (MANEUVER_TYPE_FLY_TO_OBJECT)
Returns
The maneuver type.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 109 of file fly_to_object_maneuver_server.cpp.
{
    return MANEUVER_TYPE_FLY_TO_OBJECT;
}
References iii_drone::control::maneuver::MANEUVER_TYPE_FLY_TO_OBJECT.
publishFeedback()
void FlyToObjectManeuverServer::publishFeedback (Maneuver & maneuver) override private virtual
Publishes the feedback.
Parameters
maneuver The maneuver.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 280 of file fly_to_object_maneuver_server.cpp.
{
    auto feedback = std::make_shared<iii_drone_interfaces::action::FlyToObject::Feedback>();
    ReferenceTrajectory reference_trajectory = trajectory_generator_client_->GetReferenceTrajectory();
    ReferenceTrajectoryAdapter reference_trajectory_adapter(reference_trajectory);
    State state = awareness_handler()->GetState();
    Reference target_reference = getUpdatedTargetReference(state);
    feedback->planned_path = reference_trajectory_adapter.ToPathMsg(parameters_->world_frame_id());
    feedback->vehicle_pose = StateAdapter(awareness_handler()->GetState()).ToPoseStampedMsg(parameters_->world_frame_id());
    feedback->distance_vehicle_to_target = (target_reference.position() - state.position()).norm();
    auto goal_handle = std::static_pointer_cast<GoalHandleFlyToObject>(maneuver.goal_handle());
    goal_handle->publish_feedback(feedback);
}
References iii_drone::control::maneuver::ManeuverServer::awareness_handler(), iii_drone::control::TrajectoryGeneratorClient::GetReferenceTrajectory(), iii_drone::control::CombinedDroneAwarenessHandler::GetState(), getUpdatedTargetReference(), iii_drone::control::maneuver::Maneuver::goal_handle(), parameters_, iii_drone::control::Reference::position(), iii_drone::control::State::position(), iii_drone::adapters::ReferenceTrajectoryAdapter::ToPathMsg(), iii_drone::adapters::StateAdapter::ToPoseStampedMsg(), trajectory_generator_client_, and iii_drone::control::maneuver::FlyToObjectManeuverServerParameters::world_frame_id().
publishResultAndFinalize()
void FlyToObjectManeuverServer::publishResultAndFinalize (Maneuver & maneuver, maneuver_result_type_t maneuver_result_type) override private virtual
Publishes the result and finalizes the maneuver according to the maneuver result type.
Parameters
maneuver The maneuver.
maneuver_result_type The maneuver result type.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 300 of file fly_to_object_maneuver_server.cpp.
  {
    auto result = std::make_shared<iii_drone_interfaces::action::FlyToObject::Result>();
    auto goal_handle = std::static_pointer_cast<GoalHandleFlyToObject>(maneuver.goal_handle());
    switch (maneuver_result_type) {
        case MANEUVER_RESULT_TYPE_SUCCEED:
            result->success = true;
            goal_handle->succeed(result);
            break;
        case MANEUVER_RESULT_TYPE_ABORT:
            result->success = false;
            goal_handle->abort(result);
            awareness_handler()->ClearTarget();
            break;
        case MANEUVER_RESULT_TYPE_CANCEL:
            result->success = false;
            goal_handle->canceled(result);
            awareness_handler()->ClearTarget();
            break;
    }
}
References iii_drone::control::maneuver::ManeuverServer::awareness_handler(), iii_drone::control::CombinedDroneAwarenessHandler::ClearTarget(), iii_drone::control::maneuver::Maneuver::goal_handle(), iii_drone::control::maneuver::ManeuverServer::MANEUVER_RESULT_TYPE_ABORT, iii_drone::control::maneuver::ManeuverServer::MANEUVER_RESULT_TYPE_CANCEL, and iii_drone::control::maneuver::ManeuverServer::MANEUVER_RESULT_TYPE_SUCCEED.
registerReferenceCallbackOnSuccess()
void FlyToObjectManeuverServer::registerReferenceCallbackOnSuccess (const Maneuver & maneuver) override private virtual
Registers the hover by object reference callback on success.
Parameters
maneuver The maneuver.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 327 of file fly_to_object_maneuver_server.cpp.
{
    auto registered_hover_by_object_maneuver = registered_maneuvers().find(MANEUVER_TYPE_HOVER_BY_OBJECT);
    std::shared_ptr<HoverByObjectManeuverServer> hover_by_object_maneuver_server = std::static_pointer_cast<HoverByObjectManeuverServer>(registered_hover_by_object_maneuver->second);
    hover_by_object_maneuver_server->Update(target_adapter_);
    registerCallback(
        std::bind(
            &HoverByObjectManeuverServer::GetReference,
            hover_by_object_maneuver_server,
            std::placeholders::_1
        )
    );
}
References iii_drone::control::maneuver::HoverByObjectManeuverServer::GetReference(), iii_drone::control::maneuver::MANEUVER_TYPE_HOVER_BY_OBJECT, iii_drone::control::maneuver::ManeuverServer::registerCallback(), iii_drone::control::maneuver::ManeuverServer::registered_maneuvers(), and target_adapter_.
startExecution()
void FlyToObjectManeuverServer::startExecution (Maneuver & maneuver) override private virtual
Starts the execution of the maneuver.
Parameters
maneuver The maneuver.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 113 of file fly_to_object_maneuver_server.cpp.
{
    auto cda_handler = awareness_handler();
    fly_to_object_maneuver_params_t params(maneuver.maneuver_params());
    target_adapter_ = params.target_adapter;
    cda_handler->SetTarget(target_adapter_);
    if (trajectory_generator_client_->busy()) {
        std::string error_message = "FlyToObjectManeuverServer::startExecution(): Trajectory generator client is busy, cannot start execution of maneuver.";
        RCLCPP_FATAL(node()->get_logger(), error_message.c_str());
        throw std::runtime_error(error_message);
    }
    first_iteration_ = true;
    has_failed_ = false;
}
References iii_drone::control::maneuver::ManeuverServer::awareness_handler(), iii_drone::control::TrajectoryGeneratorClient::busy(), first_iteration_, has_failed_, iii_drone::control::maneuver::Maneuver::maneuver_params(), iii_drone::control::maneuver::ManeuverServer::node(), iii_drone::control::maneuver::fly_to_object_maneuver_params_t::target_adapter, target_adapter_, and trajectory_generator_client_.
Member Data Documentation
first_iteration_
iii_drone::utils::Atomic<bool> iii_drone::control::maneuver::FlyToObjectManeuverServer::first_iteration_ = true private
Flag for first iteration.
Definition at line 191 of file fly_to_object_maneuver_server.hpp.
Referenced by computeReference(), and startExecution().
has_failed_
iii_drone::utils::Atomic<bool> iii_drone::control::maneuver::FlyToObjectManeuverServer::has_failed_ = false private
Has failed flag.
Definition at line 196 of file fly_to_object_maneuver_server.hpp.
Referenced by getUpdatedTargetReference(), hasFailed(), and startExecution().
parameters_
iii_drone::control::maneuver::FlyToObjectManeuverServerParameters::SharedPtr iii_drone::control::maneuver::FlyToObjectManeuverServer::parameters_ private
The fly to object maneuver server parameters shared pointer.
Definition at line 176 of file fly_to_object_maneuver_server.hpp.
Referenced by CanExecuteManeuver(), computeReference(), hasSucceeded(), and publishFeedback().
target_adapter_
iii_drone::utils::Atomic<iii_drone::adapters::TargetAdapter> iii_drone::control::maneuver::FlyToObjectManeuverServer::target_adapter_ private
The hover reference target adapter.
Definition at line 186 of file fly_to_object_maneuver_server.hpp.
Referenced by CanExecuteManeuver(), getUpdatedTargetReference(), registerReferenceCallbackOnSuccess(), and startExecution().
trajectory_generator_client_
iii_drone::control::TrajectoryGeneratorClient::SharedPtr iii_drone::control::maneuver::FlyToObjectManeuverServer::trajectory_generator_client_ private
The trajectory generator client shared pointer.
Definition at line 181 of file fly_to_object_maneuver_server.hpp.
Referenced by computeReference(), publishFeedback(), and startExecution().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/maneuver/fly_to_object_maneuver_server.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/maneuver/fly_to_object_maneuver_server.cpp