III-Drone: iii_drone::adapters::px4::OffboardControlModeAdapter Class Reference
iii_drone::adapters::px4::OffboardControlModeAdapter Class Reference
#include <offboard_control_mode_adapter.hpp>
Public Member Functions
OffboardControlModeAdapter (const rclcpp::Time &stamp, const bool &position, const bool &velocity, const bool &acceleration, const bool &attitude, const bool &body_rate, const bool &actuator)
Constructor.
px4_msgs::msg::OffboardControlMode ToMsg () const
Convert to ROS2 message.
const rclcpp::Time & stamp () const
Timestamp getter.
const bool & position () const
Position control enabled getter.
const bool & velocity () const
Velocity control enabled getter.
const bool & acceleration () const
Acceleration control enabled getter.
const bool & attitude () const
Attitude control enabled getter.
const bool & body_rate () const
Body rate control enabled getter.
const bool & actuator () const
Actuator control enabled getter.
Private Attributes
rclcpp::Time stamp_
ROS2 timestamp.
bool position_
PX4 timestamp.
bool velocity_
Position control enabled.
bool acceleration_
Velocity control enabled.
bool attitude_
Acceleration control enabled.
bool body_rate_
Attitude control enabled.
bool actuator_
Body rate control enabled.
Detailed Description
Definition at line 34 of file offboard_control_mode_adapter.hpp.
Constructor & Destructor Documentation
OffboardControlModeAdapter()
OffboardControlModeAdapter::OffboardControlModeAdapter (const rclcpp::Time & stamp, const bool & position, const bool & velocity, const bool & acceleration, const bool & attitude, const bool & body_rate, const bool & actuator)
Constructor.
Parameters
stamp ROS2 timestamp
position Position control enabled
velocity Velocity control enabled
acceleration Acceleration control enabled
attitude Attitude control enabled
body_rate Body rate control enabled
actuator Actuator control enabled
Definition at line 5 of file offboard_control_mode_adapter.cpp.
  {
    stamp_ = stamp;
    position_ = position;
    velocity_ = velocity;
    acceleration_ = acceleration;
    attitude_ = attitude;
    body_rate_ = body_rate;
    actuator_ = actuator;
}
References acceleration(), acceleration_, actuator(), actuator_, attitude(), attitude_, body_rate(), body_rate_, position(), position_, stamp(), stamp_, velocity(), and velocity_.
Member Function Documentation
acceleration()
const bool & OffboardControlModeAdapter::acceleration () const
Acceleration control enabled getter.
Returns
Acceleration control enabled
Definition at line 53 of file offboard_control_mode_adapter.cpp.
{
    return acceleration_;
}
References acceleration_.
Referenced by OffboardControlModeAdapter().
actuator()
const bool & OffboardControlModeAdapter::actuator () const
Actuator control enabled getter.
Returns
Actuator control enabled
Definition at line 65 of file offboard_control_mode_adapter.cpp.
{
    return actuator_;
}
References actuator_.
Referenced by OffboardControlModeAdapter().
attitude()
const bool & OffboardControlModeAdapter::attitude () const
Attitude control enabled getter.
Returns
Attitude control enabled
Definition at line 57 of file offboard_control_mode_adapter.cpp.
{
    return attitude_;
}
References attitude_.
Referenced by OffboardControlModeAdapter().
body_rate()
const bool & OffboardControlModeAdapter::body_rate () const
Body rate control enabled getter.
Returns
Body rate control enabled
Definition at line 61 of file offboard_control_mode_adapter.cpp.
{
    return body_rate_;
}
References body_rate_.
Referenced by OffboardControlModeAdapter().
position()
const bool & OffboardControlModeAdapter::position () const
Position control enabled getter.
Returns
Position control enabled
Definition at line 45 of file offboard_control_mode_adapter.cpp.
{
    return position_;
}
References position_.
Referenced by OffboardControlModeAdapter().
stamp()
const rclcpp::Time & OffboardControlModeAdapter::stamp () const
Timestamp getter.
Returns
ROS2 timestamp
Definition at line 41 of file offboard_control_mode_adapter.cpp.
{
    return stamp_;
}
References stamp_.
Referenced by OffboardControlModeAdapter().
ToMsg()
px4_msgs::msg::OffboardControlMode OffboardControlModeAdapter::ToMsg () const
Convert to ROS2 message.
Returns
PX4 OffboardControlMode message
Definition at line 26 of file offboard_control_mode_adapter.cpp.
{
    px4_msgs::msg::OffboardControlMode msg{};
    msg.timestamp = stamp_.nanoseconds() / 1000;
    msg.position = position_;
    msg.velocity = velocity_;
    msg.acceleration = acceleration_;
    msg.attitude = attitude_;
    msg.body_rate = body_rate_;;
    msg.actuator = actuator_;
    return msg;
}
References acceleration_, actuator_, attitude_, body_rate_, position_, stamp_, and velocity_.
velocity()
const bool & OffboardControlModeAdapter::velocity () const
Velocity control enabled getter.
Returns
Velocity control enabled
Definition at line 49 of file offboard_control_mode_adapter.cpp.
{
    return velocity_;
}
References velocity_.
Referenced by OffboardControlModeAdapter().
Member Data Documentation
acceleration_
bool iii_drone::adapters::px4::OffboardControlModeAdapter::acceleration_ private
Velocity control enabled.
Definition at line 132 of file offboard_control_mode_adapter.hpp.
Referenced by acceleration(), OffboardControlModeAdapter(), and ToMsg().
actuator_
bool iii_drone::adapters::px4::OffboardControlModeAdapter::actuator_ private
Body rate control enabled.
Definition at line 147 of file offboard_control_mode_adapter.hpp.
Referenced by actuator(), OffboardControlModeAdapter(), and ToMsg().
attitude_
bool iii_drone::adapters::px4::OffboardControlModeAdapter::attitude_ private
Acceleration control enabled.
Definition at line 137 of file offboard_control_mode_adapter.hpp.
Referenced by attitude(), OffboardControlModeAdapter(), and ToMsg().
body_rate_
bool iii_drone::adapters::px4::OffboardControlModeAdapter::body_rate_ private
Attitude control enabled.
Definition at line 142 of file offboard_control_mode_adapter.hpp.
Referenced by body_rate(), OffboardControlModeAdapter(), and ToMsg().
position_
bool iii_drone::adapters::px4::OffboardControlModeAdapter::position_ private
PX4 timestamp.
Definition at line 122 of file offboard_control_mode_adapter.hpp.
Referenced by OffboardControlModeAdapter(), position(), and ToMsg().
stamp_
rclcpp::Time iii_drone::adapters::px4::OffboardControlModeAdapter::stamp_ private
ROS2 timestamp.
Definition at line 117 of file offboard_control_mode_adapter.hpp.
Referenced by OffboardControlModeAdapter(), stamp(), and ToMsg().
velocity_
bool iii_drone::adapters::px4::OffboardControlModeAdapter::velocity_ private
Position control enabled.
Definition at line 127 of file offboard_control_mode_adapter.hpp.
Referenced by OffboardControlModeAdapter(), ToMsg(), and velocity().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/adapters/px4/offboard_control_mode_adapter.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/adapters/px4/offboard_control_mode_adapter.cpp