III-Drone: iii_drone::utils::drone_frame_broadcaster_node::DroneFrameBroadcasterNode Class Reference
iii_drone::utils::drone_frame_broadcaster_node::DroneFrameBroadcasterNode Class Reference
#include <drone_frame_broadcaster_node.hpp>
Public Member Functions
DroneFrameBroadcasterNode (const std::string &node_name="drone_frame_broadcaster", const std::string &node_namespace="/drone_frame_broadcaster", const rclcpp::NodeOptions &options=rclcpp::NodeOptions())
Private Member Functions
void odometryCallback (const std::shared_ptr< px4_msgs::msg::VehicleOdometry > msg)
Private Attributes
rclcpp::Subscription< px4_msgs::msg::VehicleOdometry >::SharedPtr subscription_
std::unique_ptr< tf2_ros::TransformBroadcaster > tf_broadcaster_
iii_drone::types::rotation_matrix_t R_NED_to_body_frame
DroneFrameBroadcasterConfigurator tf_configurator_
Detailed Description
Definition at line 33 of file drone_frame_broadcaster_node.hpp.
Constructor & Destructor Documentation
DroneFrameBroadcasterNode()
DroneFrameBroadcasterNode::DroneFrameBroadcasterNode (const std::string & node_name = "drone_frame_broadcaster", const std::string & node_namespace = "/drone_frame_broadcaster", const rclcpp::NodeOptions & options = rclcpp::NodeOptions()) explicit
Definition at line 15 of file drone_frame_broadcaster_node.cpp.
  : Node(
    node_name,
    node_namespace,
    options
), tf_configurator_(this) {
    // Initialize the transform broadcaster
    tf_broadcaster_ = std::make_unique<tf2_ros::TransformBroadcaster>(*this);
    std::ostringstream stream;
    rclcpp::QoS sub_qos(rclcpp::KeepLast(1));
    sub_qos.transient_local();
    sub_qos.best_effort();
    subscription_ = this->create_subscription<px4_msgs::msg::VehicleOdometry>(
        "/fmu/out/vehicle_odometry",
        sub_qos,
        std::bind(&DroneFrameBroadcasterNode::odometryCallback, this, std::placeholders::_1));
    R_NED_to_body_frame = eulToMat(euler_angles_t(M_PI, 0, 0));
}
References iii_drone::math::eulToMat(), odometryCallback(), R_NED_to_body_frame, subscription_, and tf_broadcaster_.
Member Function Documentation
odometryCallback()
void DroneFrameBroadcasterNode::odometryCallback (const std::shared_ptr< px4_msgs::msg::VehicleOdometry > msg) private
Definition at line 43 of file drone_frame_broadcaster_node.cpp.
{
    iii_drone::adapters::px4::VehicleOdometryAdapter adapter(*msg);
    geometry_msgs::msg::TransformStamped t = adapter.ToTransformStamped(
        tf_configurator_.drone_frame_id(),
        tf_configurator_.world_frame_id()
    );
    // Send the transformation
    tf_broadcaster_->sendTransform(t);
    // RCLCPP debug published transform
    RCLCPP_DEBUG(this->get_logger(), "Published transform: %s -> %s", t.header.frame_id.c_str(), t.child_frame_id.c_str());
}
References iii_drone::utils::drone_frame_broadcaster_node::DroneFrameBroadcasterConfigurator::drone_frame_id(), tf_broadcaster_, tf_configurator_, iii_drone::adapters::px4::VehicleOdometryAdapter::ToTransformStamped(), and iii_drone::utils::drone_frame_broadcaster_node::DroneFrameBroadcasterConfigurator::world_frame_id().
Referenced by DroneFrameBroadcasterNode().
Member Data Documentation
R_NED_to_body_frame
iii_drone::types::rotation_matrix_t iii_drone::utils::drone_frame_broadcaster_node::DroneFrameBroadcasterNode::R_NED_to_body_frame private
Definition at line 48 of file drone_frame_broadcaster_node.hpp.
Referenced by DroneFrameBroadcasterNode().
subscription_
rclcpp::Subscription<px4_msgs::msg::VehicleOdometry>::SharedPtr iii_drone::utils::drone_frame_broadcaster_node::DroneFrameBroadcasterNode::subscription_ private
Definition at line 45 of file drone_frame_broadcaster_node.hpp.
Referenced by DroneFrameBroadcasterNode().
tf_broadcaster_
std::unique_ptr<tf2_ros::TransformBroadcaster> iii_drone::utils::drone_frame_broadcaster_node::DroneFrameBroadcasterNode::tf_broadcaster_ private
Definition at line 46 of file drone_frame_broadcaster_node.hpp.
Referenced by DroneFrameBroadcasterNode(), and odometryCallback().
tf_configurator_
DroneFrameBroadcasterConfigurator iii_drone::utils::drone_frame_broadcaster_node::DroneFrameBroadcasterNode::tf_configurator_ private
Definition at line 50 of file drone_frame_broadcaster_node.hpp.
Referenced by odometryCallback().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/utils/drone_frame_broadcaster_node/drone_frame_broadcaster_node.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/utils/drone_frame_broadcaster_node/drone_frame_broadcaster_node.cpp