III-Drone: iii_drone::control::maneuver::FlyToPositionManeuverServerParameters Class Reference
iii_drone::control::maneuver::FlyToPositionManeuverServerParameters Class Reference
Class for handling parameters for the FlyToPositionManeuverServer object.
#include <fly_to_position_maneuver_server_parameters.hpp>
Public Types
typedef std::shared_ptr< FlyToPositionManeuverServerParameters > SharedPtr
Shared ptr type.
Public Member Functions
FlyToPositionManeuverServerParameters (double reached_position_euclidean_distance_threshold, double minimum_target_altitude, bool generate_trajectories_asynchronously_with_delay, unsigned int generate_trajectories_poll_period_ms, const std::string &world_frame_id)
Constructor.
double reached_position_euclidean_distance_threshold () const
Get the reached position euclidean distance threshold.
double & reached_position_euclidean_distance_threshold ()
Set the reached position euclidean distance threshold.
double minimum_target_altitude () const
Get the minimum target altitude.
double & minimum_target_altitude ()
Set the minimum target altitude.
bool generate_trajectories_asynchronously_with_delay () const
Get the flag for whether to generate trajectories asynchronously with a one time step delay.
unsigned int generate_trajectories_poll_period_ms () const
Get the period for polling the trajectory generator for new trajectories.
std::string world_frame_id () const
Get the world frame id.
Private Attributes
std::shared_mutex parameters_mutex_
Shared mutex protecting the parameter access.
double reached_position_euclidean_distance_threshold_
The reached position euclidean distance threshold.
double minimum_target_altitude_
The minimum target altitude.
bool generate_trajectories_asynchronously_with_delay_
Whether to generate trajectories asynchronously with a one time step delay.
unsigned int generate_trajectories_poll_period_ms_
The period for polling the trajectory generator for new trajectories.
std::string world_frame_id_
The world frame id.
Detailed Description
Class for handling parameters for the FlyToPositionManeuverServer object.
Definition at line 33 of file fly_to_position_maneuver_server_parameters.hpp.
Member Typedef Documentation
SharedPtr
typedef std::shared_ptr<FlyToPositionManeuverServerParameters> iii_drone::control::maneuver::FlyToPositionManeuverServerParameters::SharedPtr
Shared ptr type.
Definition at line 104 of file fly_to_position_maneuver_server_parameters.hpp.
Constructor & Destructor Documentation
FlyToPositionManeuverServerParameters()
FlyToPositionManeuverServerParameters::FlyToPositionManeuverServerParameters (double reached_position_euclidean_distance_threshold, double minimum_target_altitude, bool generate_trajectories_asynchronously_with_delay, unsigned int generate_trajectories_poll_period_ms, const std::string & world_frame_id)
Constructor.
Parameters
reached_position_euclidean_distance_threshold The threshold for the euclidean distance to the target position for the maneuver to be considered reached.
minimum_target_altitude The minimum altitude for the target position.
generate_trajectories_asynchronously_with_delay Whether to generate trajectories asynchronously with a one time step delay.
generate_trajectories_poll_period_ms The period for polling the trajectory generator for new trajectories.
world_frame_id The world frame id.
Definition at line 13 of file fly_to_position_maneuver_server_parameters.cpp.
  : reached_position_euclidean_distance_threshold_(reached_position_euclidean_distance_threshold),
    minimum_target_altitude_(minimum_target_altitude),
    generate_trajectories_asynchronously_with_delay_(generate_trajectories_asynchronously_with_delay),
    generate_trajectories_poll_period_ms_(generate_trajectories_poll_period_ms),
    world_frame_id_(world_frame_id) { }
Member Function Documentation
generate_trajectories_asynchronously_with_delay()
bool FlyToPositionManeuverServerParameters::generate_trajectories_asynchronously_with_delay () const
Get the flag for whether to generate trajectories asynchronously with a one time step delay.
Returns
The flag for whether to generate trajectories asynchronously with a one time step delay.
Definition at line 49 of file fly_to_position_maneuver_server_parameters.cpp.
{
    std::shared_lock lock(parameters_mutex_);
    return generate_trajectories_asynchronously_with_delay_;
}
References generate_trajectories_asynchronously_with_delay_, and parameters_mutex_.
Referenced by iii_drone::control::maneuver::FlyToPositionManeuverServer::computeReference().
generate_trajectories_poll_period_ms()
unsigned int FlyToPositionManeuverServerParameters::generate_trajectories_poll_period_ms () const
Get the period for polling the trajectory generator for new trajectories.
Returns
The period for polling the trajectory generator for new trajectories.
Definition at line 55 of file fly_to_position_maneuver_server_parameters.cpp.
{
    std::shared_lock lock(parameters_mutex_);
    return generate_trajectories_poll_period_ms_;
}
References generate_trajectories_poll_period_ms_, and parameters_mutex_.
Referenced by iii_drone::control::maneuver::FlyToPositionManeuverServer::computeReference().
minimum_target_altitude() [1/2]
double & FlyToPositionManeuverServerParameters::minimum_target_altitude ()
Set the minimum target altitude.
Returns
The minimum target altitude.
Definition at line 43 of file fly_to_position_maneuver_server_parameters.cpp.
{
    std::unique_lock lock(parameters_mutex_);
    return minimum_target_altitude_;
}
References minimum_target_altitude_, and parameters_mutex_.
minimum_target_altitude() [2/2]
double FlyToPositionManeuverServerParameters::minimum_target_altitude () const
Get the minimum target altitude.
Returns
The minimum target altitude.
Definition at line 37 of file fly_to_position_maneuver_server_parameters.cpp.
{
    std::shared_lock lock(parameters_mutex_);
    return minimum_target_altitude_;
}
References minimum_target_altitude_, and parameters_mutex_.
Referenced by iii_drone::control::maneuver::FlyToPositionManeuverServer::CanExecuteManeuver().
reached_position_euclidean_distance_threshold() [1/2]
double & FlyToPositionManeuverServerParameters::reached_position_euclidean_distance_threshold ()
Set the reached position euclidean distance threshold.
Returns
The reached position euclidean distance threshold.
Definition at line 31 of file fly_to_position_maneuver_server_parameters.cpp.
{
    std::unique_lock lock(parameters_mutex_);
    return reached_position_euclidean_distance_threshold_;
}
References parameters_mutex_, and reached_position_euclidean_distance_threshold_.
reached_position_euclidean_distance_threshold() [2/2]
double FlyToPositionManeuverServerParameters::reached_position_euclidean_distance_threshold () const
Get the reached position euclidean distance threshold.
Returns
The reached position euclidean distance threshold.
Definition at line 25 of file fly_to_position_maneuver_server_parameters.cpp.
{
    std::shared_lock lock(parameters_mutex_);
    return reached_position_euclidean_distance_threshold_;
}
References parameters_mutex_, and reached_position_euclidean_distance_threshold_.
Referenced by iii_drone::control::maneuver::FlyToPositionManeuverServer::hasSucceeded().
world_frame_id()
std::string FlyToPositionManeuverServerParameters::world_frame_id () const
Get the world frame id.
Returns
The world frame id.
Definition at line 61 of file fly_to_position_maneuver_server_parameters.cpp.
{
    std::shared_lock lock(parameters_mutex_);
    return world_frame_id_;
}
References parameters_mutex_, and world_frame_id_.
Referenced by iii_drone::control::maneuver::FlyToPositionManeuverServer::CanExecuteManeuver(), iii_drone::control::maneuver::FlyToPositionManeuverServer::publishFeedback(), and iii_drone::control::maneuver::FlyToPositionManeuverServer::startExecution().
Member Data Documentation
generate_trajectories_asynchronously_with_delay_
bool iii_drone::control::maneuver::FlyToPositionManeuverServerParameters::generate_trajectories_asynchronously_with_delay_ private
Whether to generate trajectories asynchronously with a one time step delay.
Definition at line 125 of file fly_to_position_maneuver_server_parameters.hpp.
Referenced by generate_trajectories_asynchronously_with_delay().
generate_trajectories_poll_period_ms_
unsigned int iii_drone::control::maneuver::FlyToPositionManeuverServerParameters::generate_trajectories_poll_period_ms_ private
The period for polling the trajectory generator for new trajectories.
Definition at line 130 of file fly_to_position_maneuver_server_parameters.hpp.
Referenced by generate_trajectories_poll_period_ms().
minimum_target_altitude_
double iii_drone::control::maneuver::FlyToPositionManeuverServerParameters::minimum_target_altitude_ private
The minimum target altitude.
Definition at line 120 of file fly_to_position_maneuver_server_parameters.hpp.
Referenced by minimum_target_altitude(), and minimum_target_altitude().
parameters_mutex_
std::shared_mutex iii_drone::control::maneuver::FlyToPositionManeuverServerParameters::parameters_mutex_ mutable private
Shared mutex protecting the parameter access.
Definition at line 110 of file fly_to_position_maneuver_server_parameters.hpp.
Referenced by generate_trajectories_asynchronously_with_delay(), generate_trajectories_poll_period_ms(), minimum_target_altitude(), minimum_target_altitude(), reached_position_euclidean_distance_threshold(), reached_position_euclidean_distance_threshold(), and world_frame_id().
reached_position_euclidean_distance_threshold_
double iii_drone::control::maneuver::FlyToPositionManeuverServerParameters::reached_position_euclidean_distance_threshold_ private
The reached position euclidean distance threshold.
Definition at line 115 of file fly_to_position_maneuver_server_parameters.hpp.
Referenced by reached_position_euclidean_distance_threshold(), and reached_position_euclidean_distance_threshold().
world_frame_id_
std::string iii_drone::control::maneuver::FlyToPositionManeuverServerParameters::world_frame_id_ private
The world frame id.
Definition at line 135 of file fly_to_position_maneuver_server_parameters.hpp.
Referenced by world_frame_id().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/maneuver/fly_to_position_maneuver_server_parameters.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/maneuver/fly_to_position_maneuver_server_parameters.cpp