III-Drone: iii_drone::control::Reference Class Reference
iii_drone::control::Reference Class Reference
#include <reference.hpp>
Public Member Functions
Reference (const iii_drone::types::point_t position, double yaw, const iii_drone::types::vector_t velocity=iii_drone::types::vector_t::Zero(), double yaw_rate=0.0, const iii_drone::types::vector_t acceleration=iii_drone::types::vector_t::Zero(), double yaw_acceleration=0.0, const rclcpp::Time stamp=rclcpp::Clock().now())
Reference ()
Reference (const State &state)
const iii_drone::types::point_t position () const
double yaw () const
const iii_drone::types::vector_t velocity () const
double yaw_rate () const
const iii_drone::types::vector_t acceleration () const
double yaw_acceleration () const
const rclcpp::Time stamp () const
Private Attributes
iii_drone::types::point_t position_
double yaw_
iii_drone::types::vector_t velocity_
double yaw_rate_
iii_drone::types::vector_t acceleration_
double yaw_acceleration_
rclcpp::Time stamp_
Detailed Description
Class representing a control reference position and yaw.
Definition at line 30 of file reference.hpp.
Constructor & Destructor Documentation
Reference() [1/3]
Reference::Reference (const iii_drone::types::point_t position, double yaw, const iii_drone::types::vector_t velocity = iii_drone::types::vector_t::Zero(), double yaw_rate = 0.0, const iii_drone::types::vector_t acceleration = iii_drone::types::vector_t::Zero(), double yaw_acceleration = 0.0, const rclcpp::Time stamp = rclcpp::Clock().now())
Constructor.
Parameters
position The reference position.
yaw The reference yaw.
velocity The reference velocity, defaults to zero.
yaw_rate The reference yaw rate, defaults to zero.
acceleration The reference acceleration, defaults to zero.
yaw_acceleration The reference yaw acceleration, defaults to zero.
stamp The timestamp, defaults to now.
Definition at line 14 of file reference.cpp.
  {
    position_ = position;
    yaw_ = yaw;
    velocity_ = velocity;
    yaw_rate_ = yaw_rate;
    acceleration_ = acceleration;
    yaw_acceleration_ = yaw_acceleration;
    stamp_ = stamp;
}
References acceleration(), acceleration_, position(), position_, stamp(), stamp_, velocity(), velocity_, yaw(), yaw_, yaw_acceleration(), yaw_acceleration_, yaw_rate(), and yaw_rate_.
Reference() [2/3]
Reference::Reference ()
Default constructor for empty object.
Definition at line 32 of file reference.cpp.
                     {
    position_ = point_t::Zero();
    yaw_ = 0.0;
    velocity_ = vector_t::Zero();
    yaw_rate_ = 0.0;
    acceleration_ = vector_t::Zero();
    yaw_acceleration_ = 0.0;
    stamp_ = rclcpp::Clock().now();
}
References acceleration_, position_, stamp_, velocity_, yaw_, yaw_acceleration_, and yaw_rate_.
Reference() [3/3]
Reference::Reference (const State & state)
Constructor from state.
Parameters
state The state object.
Definition at line 42 of file reference.cpp.
{
    position_ = state.position();
    euler_angles_t euler = iii_drone::math::quatToEul(state.quaternion());
    yaw_ = euler(2);
    velocity_ = state.velocity();
    yaw_rate_ = 0.0; //Maybe fix this later
    // acceleration_ = state.acceleration();
    // yaw_acceleration_ = 0.0; //Maybe fix this later
    stamp_ = state.stamp();
}
References iii_drone::control::State::position(), position_, iii_drone::control::State::quaternion(), iii_drone::math::quatToEul(), iii_drone::control::State::stamp(), stamp_, iii_drone::control::State::velocity(), velocity_, yaw_, and yaw_rate_.
Member Function Documentation
acceleration()
const vector_t Reference::acceleration () const
Getter for the reference acceleration.
Returns
The reference acceleration.
Definition at line 75 of file reference.cpp.
{
    return acceleration_;
}
References acceleration_.
Referenced by Reference(), iii_drone::adapters::ReferenceAdapter::ToMsg(), iii_drone::adapters::px4::TrajectorySetpointAdapter::TrajectorySetpointAdapter(), and iii_drone::adapters::px4::TrajectorySetpointAdapter::TrajectorySetpointAdapter().
position()
const point_t Reference::position () const
Getter for the reference position.
Returns
The reference position.
Definition at line 59 of file reference.cpp.
{
    return position_;
}
References position_.
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::hasSucceeded(), iii_drone::control::maneuver::FlyToPositionManeuverServer::hasSucceeded(), iii_drone::control::maneuver::FlyToObjectManeuverServer::publishFeedback(), Reference(), iii_drone::control::TrajectoryGenerator::setupMPC(), iii_drone::adapters::ReferenceAdapter::ToMsg(), iii_drone::adapters::ReferenceAdapter::ToPoseStampedMsg(), iii_drone::adapters::px4::TrajectorySetpointAdapter::TrajectorySetpointAdapter(), iii_drone::adapters::px4::TrajectorySetpointAdapter::TrajectorySetpointAdapter(), and iii_drone::control::maneuver::HoverManeuverServer::Update().
stamp()
const rclcpp::Time Reference::stamp () const
Getter for the timestamp.
Definition at line 83 of file reference.cpp.
{
    return stamp_;
}
References stamp_.
Referenced by Reference(), iii_drone::adapters::ReferenceAdapter::ToMsg(), iii_drone::adapters::ReferenceAdapter::ToPoseStampedMsg(), iii_drone::adapters::px4::TrajectorySetpointAdapter::TrajectorySetpointAdapter(), and iii_drone::adapters::px4::TrajectorySetpointAdapter::TrajectorySetpointAdapter().
velocity()
const vector_t Reference::velocity () const
Getter for the reference velocity.
Returns
The reference velocity.
Definition at line 67 of file reference.cpp.
{
    return velocity_;
}
References velocity_.
Referenced by Reference(), iii_drone::control::TrajectoryGenerator::setupMPC(), iii_drone::adapters::ReferenceAdapter::ToMsg(), iii_drone::adapters::px4::TrajectorySetpointAdapter::TrajectorySetpointAdapter(), and iii_drone::adapters::px4::TrajectorySetpointAdapter::TrajectorySetpointAdapter().
yaw()
double Reference::yaw () const
Getter for the reference yaw.
Returns
The reference yaw.
Definition at line 63 of file reference.cpp.
{
    return yaw_;
}
References yaw_.
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::hasSucceeded(), iii_drone::control::maneuver::FlyToPositionManeuverServer::hasSucceeded(), Reference(), iii_drone::adapters::ReferenceAdapter::ToMsg(), iii_drone::adapters::ReferenceAdapter::ToPoseStampedMsg(), iii_drone::adapters::px4::TrajectorySetpointAdapter::TrajectorySetpointAdapter(), iii_drone::adapters::px4::TrajectorySetpointAdapter::TrajectorySetpointAdapter(), and iii_drone::control::maneuver::HoverManeuverServer::Update().
yaw_acceleration()
double Reference::yaw_acceleration () const
Getter for the reference yaw acceleration.
Returns
The reference yaw acceleration.
Definition at line 79 of file reference.cpp.
{
    return yaw_acceleration_;
}
References yaw_acceleration_.
Referenced by Reference(), and iii_drone::adapters::ReferenceAdapter::ToMsg().
yaw_rate()
double Reference::yaw_rate () const
Getter for the reference yaw rate.
Returns
The reference yaw rate.
Definition at line 71 of file reference.cpp.
{
    return yaw_rate_;
}
References yaw_rate_.
Referenced by Reference(), iii_drone::adapters::ReferenceAdapter::ToMsg(), iii_drone::adapters::px4::TrajectorySetpointAdapter::TrajectorySetpointAdapter(), and iii_drone::adapters::px4::TrajectorySetpointAdapter::TrajectorySetpointAdapter().
Member Data Documentation
acceleration_
iii_drone::types::vector_t iii_drone::control::Reference::acceleration_ private
The reference acceleration.
Definition at line 136 of file reference.hpp.
Referenced by acceleration(), Reference(), and Reference().
position_
iii_drone::types::point_t iii_drone::control::Reference::position_ private
The reference position.
Definition at line 116 of file reference.hpp.
Referenced by position(), Reference(), Reference(), and Reference().
stamp_
rclcpp::Time iii_drone::control::Reference::stamp_ private
The timestamp.
Definition at line 146 of file reference.hpp.
Referenced by Reference(), Reference(), Reference(), and stamp().
velocity_
iii_drone::types::vector_t iii_drone::control::Reference::velocity_ private
The reference velocity.
Definition at line 126 of file reference.hpp.
Referenced by Reference(), Reference(), Reference(), and velocity().
yaw_
double iii_drone::control::Reference::yaw_ private
The reference yaw.
Definition at line 121 of file reference.hpp.
Referenced by Reference(), Reference(), Reference(), and yaw().
yaw_acceleration_
double iii_drone::control::Reference::yaw_acceleration_ private
The reference yaw acceleration.
Definition at line 141 of file reference.hpp.
Referenced by Reference(), Reference(), and yaw_acceleration().
yaw_rate_
double iii_drone::control::Reference::yaw_rate_ private
The reference yaw rate.
Definition at line 131 of file reference.hpp.
Referenced by Reference(), Reference(), Reference(), and yaw_rate().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/reference.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/reference.cpp