III-Drone: iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator Class Reference
iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator Class Reference
Class for handling parameters for ManeuverController. Exposes a CombinedDroneAwarenessHandlerParameters object, a ManeuverSchedulerParameters object, and parameters for the maneuver servers.
#include <maneuver_controller_node_configurator.hpp>
Public Member Functions
ManeuverControllerNodeConfigurator (rclcpp::Node *node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Constructor.
ManeuverControllerNodeConfigurator (rclcpp::Node *node, const rclcpp::QoS &qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Constructor.
const std::shared_ptr< control::CombinedDroneAwarenessHandlerParameters > combined_drone_awareness_handler_parameters () const
Get the combined drone awareness handler parameters object.
const std::shared_ptr< control::maneuver::ManeuverSchedulerParameters > maneuver_scheduler_parameters () const
Get the maneuver scheduler parameters object.
const std::shared_ptr< control::maneuver::FlyToPositionManeuverServerParameters > fly_to_position_maneuver_server_parameters () const
Get the fly to position maneuver server parameters object.
const std::shared_ptr< control::maneuver::FlyToObjectManeuverServerParameters > fly_to_object_maneuver_server_parameters () const
Get the fly to object maneuver server parameters object.
int ground_estimate_window_size () const
Get the window size for the ground estimate history.
int ground_estimate_update_period_ms () const
Get the period for updating the ground estimate.
double landed_altitude_threshold () const
Get the altitude threshold for the drone to be considered landed.
double on_cable_max_euc_distance () const
Get the on_cable_max_euc_distance value.
bool fail_on_unable_to_locate () const
Get the fail_on_unable_to_locate value.
std::string cable_gripper_frame_id () const
Get the cable gripper frame id.
std::string drone_frame_id () const
Get the drone frame id.
std::string world_frame_id () const
Get the world frame id.
std::string ground_frame_id () const
Get the ground frame id.
double maneuver_register_update_timeout_s () const
Get the timeout for updating a maneuver after registering it.
double maneuver_start_timeout_s () const
Get the timeout for the server to start executing a maneuver after Start() has been called.
unsigned int maneuver_queue_size () const
Get the size of the maneuver queue.
unsigned int maneuver_execution_period_ms () const
Get the period for executing maneuvers.
bool use_nans_when_hovering () const
Get whether to use NaNs for velocity and acceleration when hovering, otherwise uses zeros.
double no_maneuver_idle_cnt_s () const
Get the number of seconds with no maneuver before the scheduler goes from hovering to idle.
double hover_by_object_max_euc_dist () const
Get the maximum euclidean distance to the object before the fail callback is called.
double hover_on_cable_default_z_velocity () const
Get the default z velocity for hovering on a cable.
double hover_on_cable_default_yaw_rate () const
Get the default yaw rate for hovering on a cable.
std::vector< int64_t > px4_offboard_mode_ids () const
Get the PX4 mode ids considered as offboard.
unsigned int maneuver_wait_for_execute_poll_ms () const
Get the poll period in ms for waiting for execution of maneuver.
unsigned int maneuver_evaluate_done_poll_ms () const
Get the poll period in ms for evaluating if a maneuver is done.
double reached_position_euclidean_distance_threshold () const
Get the reached position threshold for evaluating if the target position has been reached.
double minimum_target_altitude () const
Get the minimum target altitude for the target position.
bool generate_trajectories_asynchronously_with_delay () const
Get the flag for whether to generate trajectories asynchronously with one iteration delay.
unsigned int generate_trajectories_poll_period_ms () const
Get the poll period in ms for waiting for the generation of trajectories.
Public Member Functions inherited from iii_drone::configuration::Configurator
Configurator (rclcpp::Node *node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Configurator (rclcpp::Node *node, const rclcpp::QoS &qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
~Configurator ()
template<typename T >
void DeclareParameter (const std::string &name)
rclcpp::Parameter GetParameter (const std::string &name) const
Get a parameter.
std::vector< rclcpp::Parameter > GetParameters (const std::vector< std::string > &names) const
Gets multiple parameters.
void SyncParameters (const std::vector< std::string > &names={})
Synchronizes parameters with the parameter server. Should never be necessary.
void PrintParameters () const
Prints all parameters to the console.
Private Member Functions
void declareNodeParameters ()
Declares the node specific parameters.
void initParametersObjects ()
Initializes the parameters objects.
void updateParametersObjectsCallback (const rclcpp::Parameter &parameter)
Callback function called after successful parameter change to update parameters object.
Private Attributes
std::shared_ptr< control::CombinedDroneAwarenessHandlerParameters > combined_drone_awareness_handler_parameters_
Combined drone awareness handler parameters object.
std::shared_ptr< control::maneuver::ManeuverSchedulerParameters > maneuver_scheduler_parameters_
Maneuver scheduler parameters object.
std::shared_ptr< control::maneuver::FlyToPositionManeuverServerParameters > fly_to_position_maneuver_server_parameters_
Fly to position maneuver server parameters object.
std::shared_ptr< control::maneuver::FlyToObjectManeuverServerParameters > fly_to_object_maneuver_server_parameters_
Fly to object maneuver server parameters object.
bool parameters_objects_initialized_ = false
Parameters objects initialized flag.
std::function< void(const rclcpp::Parameter &) after_parameter_change_callback_)
Callback function reference called after successful parameter change.
Additional Inherited Members
Static Public Member Functions inherited from iii_drone::configuration::Configurator
template<typename T >
static std::string GetParameterTypeString ()
Static function for getting string representation of a parameter type from template type.
Protected Attributes inherited from iii_drone::configuration::Configurator
rclcpp::Node * node_
Detailed Description
Class for handling parameters for ManeuverController. Exposes a CombinedDroneAwarenessHandlerParameters object, a ManeuverSchedulerParameters object, and parameters for the maneuver servers.
Definition at line 42 of file maneuver_controller_node_configurator.hpp.
Constructor & Destructor Documentation
ManeuverControllerNodeConfigurator() [1/2]
ManeuverControllerNodeConfigurator::ManeuverControllerNodeConfigurator (rclcpp::Node * node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback = nullptr)
Constructor.
Parameters
node Reference to the handling node
after_parameter_change_callback Callback function called after successful parameter change, default is nullptr
Definition at line 15 of file maneuver_controller_node_configurator.cpp.
  : Configurator(
        node,
        std::bind(
            &ManeuverControllerNodeConfigurator::updateParametersObjectsCallback,
            this,
            std::placeholders::_1
        )
    ),
    after_parameter_change_callback_(after_parameter_change_callback) {
    declareNodeParameters();
    initParametersObjects();
}
References declareNodeParameters(), and initParametersObjects().
ManeuverControllerNodeConfigurator() [2/2]
ManeuverControllerNodeConfigurator::ManeuverControllerNodeConfigurator (rclcpp::Node * node, const rclcpp::QoS & qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback = nullptr)
Constructor.
Parameters
node Reference to the handling node
qos QoS profile for the parameter event subscription
after_parameter_change_callback Callback function called after successful parameter change, default is nullptr
Definition at line 33 of file maneuver_controller_node_configurator.cpp.
  : Configurator(
        node,
        qos,
        std::bind(
            &ManeuverControllerNodeConfigurator::updateParametersObjectsCallback,
            this,
            std::placeholders::_1
        )
    ),
    after_parameter_change_callback_(after_parameter_change_callback) {
    declareNodeParameters();
    initParametersObjects();
}
References declareNodeParameters(), and initParametersObjects().
Member Function Documentation
cable_gripper_frame_id()
std::string ManeuverControllerNodeConfigurator::cable_gripper_frame_id () const
Get the cable gripper frame id.
Returns
The cable gripper frame id.
Definition at line 107 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/tf/cable_gripper_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects().
combined_drone_awareness_handler_parameters()
const std::shared_ptr< CombinedDroneAwarenessHandlerParameters > ManeuverControllerNodeConfigurator::combined_drone_awareness_handler_parameters () const
Get the combined drone awareness handler parameters object.
Returns
Combined drone awareness handler parameters object reference
Definition at line 53 of file maneuver_controller_node_configurator.cpp.
{
    return combined_drone_awareness_handler_parameters_;
}
References combined_drone_awareness_handler_parameters_.
Referenced by iii_drone::control::maneuver_controller_node::ManeuverControllerNode::ManeuverControllerNode().
declareNodeParameters()
void ManeuverControllerNodeConfigurator::declareNodeParameters () private
Declares the node specific parameters.
Returns
void
Definition at line 227 of file maneuver_controller_node_configurator.cpp.
{
    DeclareParameter<int>("/control/maneuver_controller/ground_estimate_window_size");
    DeclareParameter<int>("/control/maneuver_controller/ground_estimate_update_period_ms");
    DeclareParameter<double>("/control/maneuver_controller/landed_altitude_threshold");
    DeclareParameter<double>("/control/maneuver_controller/on_cable_max_euc_distance");
    DeclareParameter<bool>("/control/maneuver_controller/fail_on_unable_to_locate");
    DeclareParameter<double>("/control/maneuver_controller/maneuver_register_update_timeout_s");
    DeclareParameter<double>("/control/maneuver_controller/maneuver_start_timeout_s");
    DeclareParameter<int>("/control/maneuver_controller/maneuver_queue_size");
    DeclareParameter<int>("/control/maneuver_controller/maneuver_execution_period_ms");
    DeclareParameter<bool>("/control/maneuver_controller/use_nans_when_hovering");
    DeclareParameter<double>("/control/maneuver_controller/no_maneuver_idle_cnt_s");
    DeclareParameter<double>("/control/maneuver_controller/hover_by_object_max_euc_dist");
    DeclareParameter<double>("/control/maneuver_controller/hover_on_cable_default_z_velocity");
    DeclareParameter<double>("/control/maneuver_controller/hover_on_cable_default_yaw_rate");
    DeclareParameter<int>("/control/maneuver_controller/maneuver_wait_for_execute_poll_ms");
    DeclareParameter<int>("/control/maneuver_controller/maneuver_evaluate_done_poll_ms");
    DeclareParameter<double>("/control/maneuver_controller/reached_position_euclidean_distance_threshold");
    DeclareParameter<double>("/control/maneuver_controller/minimum_target_altitude");
    DeclareParameter<bool>("/control/maneuver_controller/generate_trajectories_asynchronously_with_delay");
    DeclareParameter<int>("/control/maneuver_controller/generate_trajectories_poll_period_ms");
    DeclareParameter<std::string>("/tf/cable_gripper_frame_id");
    DeclareParameter<std::string>("/tf/drone_frame_id");
    DeclareParameter<std::string>("/tf/world_frame_id");
    DeclareParameter<std::string>("/tf/ground_frame_id");
    DeclareParameter<std::vector<int>>("/px4/px4_offboard_mode_ids");
}
References Configurator::DeclareParameter< std::string >(), and iii_drone::configuration::Configurator::GetParameterTypeString().
Referenced by ManeuverControllerNodeConfigurator(), and ManeuverControllerNodeConfigurator().
drone_frame_id()
std::string ManeuverControllerNodeConfigurator::drone_frame_id () const
Get the drone frame id.
Returns
The drone frame id.
Definition at line 113 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/tf/drone_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects().
fail_on_unable_to_locate()
bool ManeuverControllerNodeConfigurator::fail_on_unable_to_locate () const
Get the fail_on_unable_to_locate value.
Returns
The fail_on_unable_to_locate value.
Definition at line 101 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/control/maneuver_controller/fail_on_unable_to_locate").as_bool();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects().
fly_to_object_maneuver_server_parameters()
const std::shared_ptr< FlyToObjectManeuverServerParameters > ManeuverControllerNodeConfigurator::fly_to_object_maneuver_server_parameters () const
Get the fly to object maneuver server parameters object.
Returns
Fly to object maneuver server parameters object reference
Definition at line 71 of file maneuver_controller_node_configurator.cpp.
{
    return fly_to_object_maneuver_server_parameters_;
}
References fly_to_object_maneuver_server_parameters_.
Referenced by iii_drone::control::maneuver_controller_node::ManeuverControllerNode::registerManeuverServers().
fly_to_position_maneuver_server_parameters()
const std::shared_ptr< FlyToPositionManeuverServerParameters > ManeuverControllerNodeConfigurator::fly_to_position_maneuver_server_parameters () const
Get the fly to position maneuver server parameters object.
Returns
Fly to position maneuver server parameters object reference
Definition at line 65 of file maneuver_controller_node_configurator.cpp.
{
    return fly_to_position_maneuver_server_parameters_;
}
References fly_to_position_maneuver_server_parameters_.
Referenced by iii_drone::control::maneuver_controller_node::ManeuverControllerNode::registerManeuverServers().
generate_trajectories_asynchronously_with_delay()
bool ManeuverControllerNodeConfigurator::generate_trajectories_asynchronously_with_delay () const
Get the flag for whether to generate trajectories asynchronously with one iteration delay.
Returns
The flag for whether to generate trajectories asynchronously with one iteration delay.
Definition at line 215 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/control/maneuver_controller/generate_trajectories_asynchronously_with_delay").as_bool();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects().
generate_trajectories_poll_period_ms()
unsigned int ManeuverControllerNodeConfigurator::generate_trajectories_poll_period_ms () const
Get the poll period in ms for waiting for the generation of trajectories.
Returns
The poll period in ms for waiting for the generation of trajectories.
Definition at line 221 of file maneuver_controller_node_configurator.cpp.
{
    return (unsigned int)GetParameter("/control/maneuver_controller/generate_trajectories_poll_period_ms").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects().
ground_estimate_update_period_ms()
int ManeuverControllerNodeConfigurator::ground_estimate_update_period_ms () const
Get the period for updating the ground estimate.
Returns
The period for updating the ground estimate.
Definition at line 83 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/control/maneuver_controller/ground_estimate_update_period_ms").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects().
ground_estimate_window_size()
int ManeuverControllerNodeConfigurator::ground_estimate_window_size () const
Get the window size for the ground estimate history.
Returns
The window size for the ground estimate history.
Definition at line 77 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/control/maneuver_controller/ground_estimate_window_size").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects().
ground_frame_id()
std::string ManeuverControllerNodeConfigurator::ground_frame_id () const
Get the ground frame id.
Returns
The ground frame id.
Definition at line 125 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/tf/ground_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects().
hover_by_object_max_euc_dist()
double ManeuverControllerNodeConfigurator::hover_by_object_max_euc_dist () const
Get the maximum euclidean distance to the object before the fail callback is called.
Returns
The maximum euclidean distance to the object before the fail callback is called.
Definition at line 167 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/control/maneuver_controller/hover_by_object_max_euc_dist").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects(), and iii_drone::control::maneuver_controller_node::ManeuverControllerNode::registerManeuverServers().
hover_on_cable_default_yaw_rate()
double ManeuverControllerNodeConfigurator::hover_on_cable_default_yaw_rate () const
Get the default yaw rate for hovering on a cable.
Returns
The default yaw rate for hovering on a cable.
Definition at line 179 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/control/maneuver_controller/hover_on_cable_default_yaw_rate").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects(), and iii_drone::control::maneuver_controller_node::ManeuverControllerNode::registerManeuverServers().
hover_on_cable_default_z_velocity()
double ManeuverControllerNodeConfigurator::hover_on_cable_default_z_velocity () const
Get the default z velocity for hovering on a cable.
Returns
The default z velocity for hovering on a cable.
Definition at line 173 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/control/maneuver_controller/hover_on_cable_default_z_velocity").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects(), and iii_drone::control::maneuver_controller_node::ManeuverControllerNode::registerManeuverServers().
initParametersObjects()
void ManeuverControllerNodeConfigurator::initParametersObjects () private
Initializes the parameters objects.
Definition at line 259 of file maneuver_controller_node_configurator.cpp.
{
    combined_drone_awareness_handler_parameters_ = std::make_shared<CombinedDroneAwarenessHandlerParameters>(
        ground_estimate_window_size(),
        ground_estimate_update_period_ms(),
        landed_altitude_threshold(),
        on_cable_max_euc_distance(),
        fail_on_unable_to_locate(),
        cable_gripper_frame_id(),
        drone_frame_id(),
        world_frame_id(),
        ground_frame_id()
    );
    maneuver_scheduler_parameters_ = std::make_shared<ManeuverSchedulerParameters>(
        maneuver_register_update_timeout_s(),
        maneuver_start_timeout_s(),
        maneuver_queue_size(),
        maneuver_execution_period_ms(),
        use_nans_when_hovering(),
        no_maneuver_idle_cnt_s(),
        hover_by_object_max_euc_dist(),
        hover_on_cable_default_z_velocity(),
        hover_on_cable_default_yaw_rate()
    );
    fly_to_position_maneuver_server_parameters_ = std::make_shared<FlyToPositionManeuverServerParameters>(
        reached_position_euclidean_distance_threshold(),
        minimum_target_altitude(),
        generate_trajectories_asynchronously_with_delay(),
        generate_trajectories_poll_period_ms(),
        world_frame_id()
    );
    fly_to_object_maneuver_server_parameters_ = std::make_shared<FlyToObjectManeuverServerParameters>(
        reached_position_euclidean_distance_threshold(),
        minimum_target_altitude(),
        generate_trajectories_asynchronously_with_delay(),
        generate_trajectories_poll_period_ms(),
        world_frame_id()
    );
}
References cable_gripper_frame_id(), combined_drone_awareness_handler_parameters_, drone_frame_id(), fail_on_unable_to_locate(), fly_to_object_maneuver_server_parameters_, fly_to_position_maneuver_server_parameters_, generate_trajectories_asynchronously_with_delay(), generate_trajectories_poll_period_ms(), ground_estimate_update_period_ms(), ground_estimate_window_size(), ground_frame_id(), hover_by_object_max_euc_dist(), hover_on_cable_default_yaw_rate(), hover_on_cable_default_z_velocity(), landed_altitude_threshold(), maneuver_execution_period_ms(), maneuver_queue_size(), maneuver_register_update_timeout_s(), maneuver_scheduler_parameters_, maneuver_start_timeout_s(), minimum_target_altitude(), no_maneuver_idle_cnt_s(), on_cable_max_euc_distance(), reached_position_euclidean_distance_threshold(), use_nans_when_hovering(), and world_frame_id().
Referenced by ManeuverControllerNodeConfigurator(), and ManeuverControllerNodeConfigurator().
landed_altitude_threshold()
double ManeuverControllerNodeConfigurator::landed_altitude_threshold () const
Get the altitude threshold for the drone to be considered landed.
Returns
The altitude threshold for the drone to be considered landed.
Definition at line 89 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/control/maneuver_controller/landed_altitude_threshold").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects().
maneuver_evaluate_done_poll_ms()
unsigned int ManeuverControllerNodeConfigurator::maneuver_evaluate_done_poll_ms () const
Get the poll period in ms for evaluating if a maneuver is done.
Returns
The poll period in ms for evaluating if a maneuver is done.
Definition at line 197 of file maneuver_controller_node_configurator.cpp.
{
    return (unsigned int)GetParameter("/control/maneuver_controller/maneuver_evaluate_done_poll_ms").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by iii_drone::control::maneuver_controller_node::ManeuverControllerNode::registerManeuverServers().
maneuver_execution_period_ms()
unsigned int ManeuverControllerNodeConfigurator::maneuver_execution_period_ms () const
Get the period for executing maneuvers.
Returns
The period for executing maneuvers.
Definition at line 149 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/control/maneuver_controller/maneuver_execution_period_ms").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects().
maneuver_queue_size()
unsigned int ManeuverControllerNodeConfigurator::maneuver_queue_size () const
Get the size of the maneuver queue.
Returns
The size of the maneuver queue.
Definition at line 143 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/control/maneuver_controller/maneuver_queue_size").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects().
maneuver_register_update_timeout_s()
double ManeuverControllerNodeConfigurator::maneuver_register_update_timeout_s () const
Get the timeout for updating a maneuver after registering it.
Returns
The timeout for updating a maneuver after registering it.
Definition at line 131 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/control/maneuver_controller/maneuver_register_update_timeout_s").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects().
maneuver_scheduler_parameters()
const std::shared_ptr< ManeuverSchedulerParameters > ManeuverControllerNodeConfigurator::maneuver_scheduler_parameters () const
Get the maneuver scheduler parameters object.
Returns
Maneuver scheduler parameters object reference
Definition at line 59 of file maneuver_controller_node_configurator.cpp.
{
    return maneuver_scheduler_parameters_;
}
References maneuver_scheduler_parameters_.
Referenced by iii_drone::control::maneuver_controller_node::ManeuverControllerNode::ManeuverControllerNode().
maneuver_start_timeout_s()
double ManeuverControllerNodeConfigurator::maneuver_start_timeout_s () const
Get the timeout for the server to start executing a maneuver after Start() has been called.
Returns
The timeout for the server to start executing a maneuver after Start() has been called.
Definition at line 137 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/control/maneuver_controller/maneuver_start_timeout_s").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects().
maneuver_wait_for_execute_poll_ms()
unsigned int ManeuverControllerNodeConfigurator::maneuver_wait_for_execute_poll_ms () const
Get the poll period in ms for waiting for execution of maneuver.
Returns
The poll period in ms for waiting for execution of maneuver.
Definition at line 191 of file maneuver_controller_node_configurator.cpp.
{
    return (unsigned int)GetParameter("/control/maneuver_controller/maneuver_wait_for_execute_poll_ms").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by iii_drone::control::maneuver_controller_node::ManeuverControllerNode::registerManeuverServers().
minimum_target_altitude()
double ManeuverControllerNodeConfigurator::minimum_target_altitude () const
Get the minimum target altitude for the target position.
Returns
The minimum target altitude for the target position.
Definition at line 209 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/control/maneuver_controller/minimum_target_altitude").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects().
no_maneuver_idle_cnt_s()
double ManeuverControllerNodeConfigurator::no_maneuver_idle_cnt_s () const
Get the number of seconds with no maneuver before the scheduler goes from hovering to idle.
Returns
The number of seconds with no maneuver before the scheduler goes from hovering to idle.
Definition at line 161 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/control/maneuver_controller/no_maneuver_idle_cnt_s").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects().
on_cable_max_euc_distance()
double ManeuverControllerNodeConfigurator::on_cable_max_euc_distance () const
Get the on_cable_max_euc_distance value.
Returns
The on_cable_max_euc_distance value.
Definition at line 95 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/control/maneuver_controller/on_cable_max_euc_distance").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects().
px4_offboard_mode_ids()
std::vector< int64_t > ManeuverControllerNodeConfigurator::px4_offboard_mode_ids () const
Get the PX4 mode ids considered as offboard.
Returns
The PX4 mode ids considered as offboard.
Definition at line 185 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/px4/px4_offboard_mode_ids").as_integer_array();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by iii_drone::control::maneuver_controller_node::ManeuverControllerNode::ManeuverControllerNode().
reached_position_euclidean_distance_threshold()
double ManeuverControllerNodeConfigurator::reached_position_euclidean_distance_threshold () const
Get the reached position threshold for evaluating if the target position has been reached.
Returns
The reached position threshold for evaluating if the target position has been reached.
Definition at line 203 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/control/maneuver_controller/reached_position_euclidean_distance_threshold").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects().
updateParametersObjectsCallback()
void ManeuverControllerNodeConfigurator::updateParametersObjectsCallback (const rclcpp::Parameter & parameter) private
Callback function called after successful parameter change to update parameters object.
Definition at line 303 of file maneuver_controller_node_configurator.cpp.
{
    std::string param_name = parameter.get_name();
    if (param_name == "/control/maneuver_controller/landed_altitude_threshold") {
        combined_drone_awareness_handler_parameters_->landed_altitude_threshold() = parameter.as_double();
    } else if (param_name == "/control/maneuver_controller/on_cable_max_euc_distance") {
        combined_drone_awareness_handler_parameters_->on_cable_max_euc_distance() = parameter.as_double();
    } else if (param_name == "/control/maneuver_controller/hover_by_object_max_euc_dist") {
        maneuver_scheduler_parameters_->hover_by_object_max_euc_dist() = parameter.as_double();
    } else if (param_name == "/control/maneuver_controller/hover_by_object_max_euc_dist") {
        maneuver_scheduler_parameters_->hover_by_object_max_euc_dist() = parameter.as_double();
    } else if (param_name == "/control/maneuver_controller/hover_on_cable_default_z_velocity") {
        maneuver_scheduler_parameters_->hover_on_cable_default_z_velocity() = parameter.as_double();
    } else if (param_name == "/control/maneuver_controller/hover_on_cable_default_yaw_rate") {
        maneuver_scheduler_parameters_->hover_on_cable_default_yaw_rate() = parameter.as_double();
    } else if (param_name == "/control/maneuver_controller/reached_position_euclidean_distance_threshold") {
        fly_to_position_maneuver_server_parameters_->reached_position_euclidean_distance_threshold() = parameter.as_double();
        fly_to_object_maneuver_server_parameters_->reached_position_euclidean_distance_threshold() = parameter.as_double();
    } else if (param_name == "/control/maneuver_controller/minimum_target_altitude") {
        fly_to_position_maneuver_server_parameters_->minimum_target_altitude() = parameter.as_double();
        fly_to_object_maneuver_server_parameters_->minimum_target_altitude() = parameter.as_double();
    }
    after_parameter_change_callback_(parameter);
}
References after_parameter_change_callback_, combined_drone_awareness_handler_parameters_, fly_to_object_maneuver_server_parameters_, fly_to_position_maneuver_server_parameters_, iii_drone::configuration::Configurator::GetParameterTypeString(), and maneuver_scheduler_parameters_.
use_nans_when_hovering()
bool ManeuverControllerNodeConfigurator::use_nans_when_hovering () const
Get whether to use NaNs for velocity and acceleration when hovering, otherwise uses zeros.
Returns
Whether to use NaNs for velocity and acceleration when hovering, otherwise uses zeros.
Definition at line 155 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/control/maneuver_controller/use_nans_when_hovering").as_bool();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects(), and iii_drone::control::maneuver_controller_node::ManeuverControllerNode::registerManeuverServers().
world_frame_id()
std::string ManeuverControllerNodeConfigurator::world_frame_id () const
Get the world frame id.
Returns
The world frame id.
Definition at line 119 of file maneuver_controller_node_configurator.cpp.
{
    return GetParameter("/tf/world_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initParametersObjects().
Member Data Documentation
after_parameter_change_callback_
std::function<void(const rclcpp::Parameter &) iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::after_parameter_change_callback_) private
Callback function reference called after successful parameter change.
Definition at line 320 of file maneuver_controller_node_configurator.hpp.
Referenced by updateParametersObjectsCallback().
combined_drone_awareness_handler_parameters_
std::shared_ptr<control::CombinedDroneAwarenessHandlerParameters> iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::combined_drone_awareness_handler_parameters_ private
Combined drone awareness handler parameters object.
Definition at line 278 of file maneuver_controller_node_configurator.hpp.
Referenced by combined_drone_awareness_handler_parameters(), initParametersObjects(), and updateParametersObjectsCallback().
fly_to_object_maneuver_server_parameters_
std::shared_ptr<control::maneuver::FlyToObjectManeuverServerParameters> iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::fly_to_object_maneuver_server_parameters_ private
Fly to object maneuver server parameters object.
Definition at line 293 of file maneuver_controller_node_configurator.hpp.
Referenced by fly_to_object_maneuver_server_parameters(), initParametersObjects(), and updateParametersObjectsCallback().
fly_to_position_maneuver_server_parameters_
std::shared_ptr<control::maneuver::FlyToPositionManeuverServerParameters> iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::fly_to_position_maneuver_server_parameters_ private
Fly to position maneuver server parameters object.
Definition at line 288 of file maneuver_controller_node_configurator.hpp.
Referenced by fly_to_position_maneuver_server_parameters(), initParametersObjects(), and updateParametersObjectsCallback().
maneuver_scheduler_parameters_
std::shared_ptr<control::maneuver::ManeuverSchedulerParameters> iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::maneuver_scheduler_parameters_ private
Maneuver scheduler parameters object.
Definition at line 283 of file maneuver_controller_node_configurator.hpp.
Referenced by initParametersObjects(), maneuver_scheduler_parameters(), and updateParametersObjectsCallback().
parameters_objects_initialized_
bool iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::parameters_objects_initialized_ = false private
Parameters objects initialized flag.
Definition at line 298 of file maneuver_controller_node_configurator.hpp.
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/maneuver_controller_node/maneuver_controller_node_configurator.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/maneuver_controller_node/maneuver_controller_node_configurator.cpp