III-Drone: iii_drone::adapters::PowerlineAdapter Class Reference
iii_drone::adapters::PowerlineAdapter Class Reference
Powerline message adapter class.
#include <powerline_adapter.hpp>
Public Member Functions
PowerlineAdapter ()
Constructor.
PowerlineAdapter (const iii_drone_interfaces::msg::Powerline &msg)
Constructor from message.
PowerlineAdapter (const rclcpp::Time &stamp, const std::vector< SingleLineAdapter > &single_line_adapters, const iii_drone::types::plane_t &projection_plane)
Constructor from members.
void UpdateFromMsg (const iii_drone_interfaces::msg::Powerline &msg)
Updates the powerline adapter object from a message.
const iii_drone_interfaces::msg::Powerline ToMsg () const
Converts the powerline adapter object to a message.
const std::vector< SingleLineAdapter > GetVisibleLineAdapters () const
Returns the line adapters that are currently in the sensor FOV.
bool HasLine (const int id) const
Returns whether a line with the given id is known.
const SingleLineAdapter GetClosestLine (const iii_drone::types::point_t &position) const
Returns the single line adapter which is closest to the given position.
const SingleLineAdapter GetLine (const int id) const
Returns the single line adapter with the given id.
const rclcpp::Time & stamp () const
Stamp getter.
const std::vector< SingleLineAdapter > & single_line_adapters () const
Line adapters getter.
const iii_drone::types::plane_t & projection_plane () const
Projection plane getter.
Private Attributes
rclcpp::Time stamp_
Time stamp for latest change.
std::vector< SingleLineAdapter > single_line_adapters_
The line adapters.
iii_drone::types::plane_t projection_plane_
The projection plane.
Detailed Description
Powerline message adapter class.
Definition at line 40 of file powerline_adapter.hpp.
Constructor & Destructor Documentation
PowerlineAdapter() [1/3]
PowerlineAdapter::PowerlineAdapter ()
Constructor.
Definition at line 14 of file powerline_adapter.cpp.
{
    stamp_ = rclcpp::Clock().now();
    projection_plane_ = createPlane(
        iii_drone::types::point_t::Zero(),
        iii_drone::types::vector_t::UnitX()
    );
}
References iii_drone::types::createPlane(), projection_plane_, and stamp_.
PowerlineAdapter() [2/3]
PowerlineAdapter::PowerlineAdapter (const iii_drone_interfaces::msg::Powerline & msg)
Constructor from message.
Parameters
msg Message containing the powerline data.
Definition at line 25 of file powerline_adapter.cpp.
{
    UpdateFromMsg(msg);
}
References UpdateFromMsg().
PowerlineAdapter() [3/3]
PowerlineAdapter::PowerlineAdapter (const rclcpp::Time & stamp, const std::vector< SingleLineAdapter > & single_line_adapters, const iii_drone::types::plane_t & projection_plane)
Constructor from members.
Parameters
stamp The timestamp.
single_line_adapters The line adapters.
projection_plane The projection plane.
Definition at line 31 of file powerline_adapter.cpp.
  {
    stamp_ = stamp;
    for (unsigned int i = 0; i < single_line_adapters.size(); i++) {
        single_line_adapters_.push_back(single_line_adapters[i]);
    }
    projection_plane_ = projection_plane;
}
References projection_plane(), projection_plane_, single_line_adapters(), single_line_adapters_, stamp(), and stamp_.
Member Function Documentation
GetClosestLine()
const SingleLineAdapter PowerlineAdapter::GetClosestLine (const iii_drone::types::point_t & position) const
Returns the single line adapter which is closest to the given position.
Parameters
position The position.
Returns
The single line adapter which is closest to the given position.
Exceptions
std::runtime_error if the powerline adapter does not contain any lines.
Definition at line 131 of file powerline_adapter.cpp.
{
    if (single_line_adapters_.empty()) {
        throw std::runtime_error("No lines in powerline adapter.");
    }
    int closest_line_adapter_idx = 0;
    float closest_distance = (point - single_line_adapters_[closest_line_adapter_idx].position()).norm();
    for (unsigned int i = 1; i < single_line_adapters_.size(); i++) {
        SingleLineAdapter line_adapter = single_line_adapters_[i];
        float distance = (point - line_adapter.position()).norm();
        if (distance < closest_distance) {
            closest_line_adapter_idx = i;
            closest_distance = distance;
        }
    }
    return single_line_adapters_[closest_line_adapter_idx];
}
References iii_drone::adapters::SingleLineAdapter::position(), and single_line_adapters_.
Referenced by iii_drone::control::CombinedDroneAwarenessHandler::updateDroneLocation().
GetLine()
const SingleLineAdapter PowerlineAdapter::GetLine (const int id) const
Returns the single line adapter with the given id.
Parameters
id The id of the line.
Returns
The single line adapter with the given id.
Exceptions
std::runtime_error if the powerline adapter does not contain a line with the given id.
Definition at line 161 of file powerline_adapter.cpp.
{
    for (unsigned int i = 0; i < single_line_adapters_.size(); i++) {
        if (single_line_adapters_[i].id() == id) {
            return single_line_adapters_[i];
        }
    }
    throw std::runtime_error("No line with id " + std::to_string(id) + " in powerline adapter.");
}
References single_line_adapters_.
Referenced by iii_drone::control::CombinedDroneAwarenessHandler::ComputeTargetTransform().
GetVisibleLineAdapters()
const std::vector< SingleLineAdapter > PowerlineAdapter::GetVisibleLineAdapters () const
Returns the line adapters that are currently in the sensor FOV.
Returns
The lines that are currently in the sensor FOV.
Definition at line 99 of file powerline_adapter.cpp.
{
    std::vector<SingleLineAdapter> visible_line_adapters;
    for (unsigned int i = 0; i < single_line_adapters_.size(); i++) {
        if (single_line_adapters_[i].in_fov()) {
            visible_line_adapters.push_back(single_line_adapters_[i]);
        }
    }
    return visible_line_adapters;
}
References single_line_adapters_.
Referenced by iii_drone::perception::PowerlineDirection::anyCableInFOV().
HasLine()
bool PowerlineAdapter::HasLine (const int id) const
Returns whether a line with the given id is known.
Parameters
id The id of the line.
Returns
true if the line is known.
Definition at line 116 of file powerline_adapter.cpp.
{
    for (unsigned int i = 0; i < single_line_adapters_.size(); i++) {
        if (single_line_adapters_[i].id() == id) {
            return true;
        }
    }
    return false;
}
References single_line_adapters_.
projection_plane()
const iii_drone::types::plane_t & PowerlineAdapter::projection_plane () const
Projection plane getter.
Definition at line 184 of file powerline_adapter.cpp.
{
    return projection_plane_;
}
References projection_plane_.
Referenced by PowerlineAdapter().
single_line_adapters()
const std::vector< SingleLineAdapter > & PowerlineAdapter::single_line_adapters () const
Line adapters getter.
Definition at line 180 of file powerline_adapter.cpp.
{
    return single_line_adapters_;
}
References single_line_adapters_.
Referenced by iii_drone::perception::PowerlineDirection::anyCableInFOV(), and PowerlineAdapter().
stamp()
const rclcpp::Time & PowerlineAdapter::stamp () const
Stamp getter.
Definition at line 176 of file powerline_adapter.cpp.
{
    return stamp_;
}
References stamp_.
Referenced by PowerlineAdapter(), and UpdateFromMsg().
ToMsg()
const iii_drone_interfaces::msg::Powerline PowerlineAdapter::ToMsg () const
Converts the powerline adapter object to a message.
Definition at line 81 of file powerline_adapter.cpp.
{
    iii_drone_interfaces::msg::Powerline msg{};
    msg.stamp = stamp_;
    for (unsigned int i = 0; i < single_line_adapters_.size(); i++) {
        msg.lines.push_back(single_line_adapters_[i].ToMsg());
    }
    msg.projection_plane = ProjectionPlaneAdapter(projection_plane_).ToMsg();
    return msg;
}
References projection_plane_, single_line_adapters_, stamp_, ToMsg(), and iii_drone::adapters::ProjectionPlaneAdapter::ToMsg().
Referenced by iii_drone::perception::pl_mapper_node::PowerlineMapperNode::publishPowerline(), and ToMsg().
UpdateFromMsg()
void PowerlineAdapter::UpdateFromMsg (const iii_drone_interfaces::msg::Powerline & msg)
Updates the powerline adapter object from a message.
Parameters
msg Powerline msg.
Definition at line 49 of file powerline_adapter.cpp.
{
    rclcpp::Time stamp;
    bool first_stamp = true;
    for (unsigned int i = 0; i < msg.lines.size(); i++) {
        SingleLineAdapter line_adapter(msg.lines[i]);
        single_line_adapters_.push_back(line_adapter);
        if (first_stamp) {
            stamp = line_adapter.stamp();
            first_stamp = false;
        } else {
            if (line_adapter.stamp() < stamp) {
                stamp = line_adapter.stamp();
            }
        }
    }
    stamp_ = stamp;
    projection_plane_ = ProjectionPlaneAdapter(msg.projection_plane).projection_plane();
}
References iii_drone::adapters::ProjectionPlaneAdapter::projection_plane(), projection_plane_, single_line_adapters_, stamp(), iii_drone::adapters::SingleLineAdapter::stamp(), and stamp_.
Referenced by PowerlineAdapter(), and iii_drone::perception::PowerlineDirection::UpdatePowerlineAdapter().
Member Data Documentation
projection_plane_
iii_drone::types::plane_t iii_drone::adapters::PowerlineAdapter::projection_plane_ private
The projection plane.
Definition at line 146 of file powerline_adapter.hpp.
Referenced by PowerlineAdapter(), PowerlineAdapter(), projection_plane(), ToMsg(), and UpdateFromMsg().
single_line_adapters_
std::vector<SingleLineAdapter> iii_drone::adapters::PowerlineAdapter::single_line_adapters_ private
The line adapters.
Definition at line 141 of file powerline_adapter.hpp.
Referenced by GetClosestLine(), GetLine(), GetVisibleLineAdapters(), HasLine(), PowerlineAdapter(), single_line_adapters(), ToMsg(), and UpdateFromMsg().
stamp_
rclcpp::Time iii_drone::adapters::PowerlineAdapter::stamp_ private
Time stamp for latest change.
Definition at line 136 of file powerline_adapter.hpp.
Referenced by PowerlineAdapter(), PowerlineAdapter(), stamp(), ToMsg(), and UpdateFromMsg().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/adapters/powerline_adapter.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/adapters/powerline_adapter.cpp