III-Drone: iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator Class Reference
iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator Class Reference
Class for handling parameters for PowerlineDirectionComputer.
#include <pl_dir_computer_node_configurator.hpp>
Public Member Functions
PowerlineDirectionComputerConfigurator (rclcpp::Node *node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Constructor.
PowerlineDirectionComputerConfigurator (rclcpp::Node *node, const rclcpp::QoS &qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Constructor.
float kf_r () const
Get the Kalman filter r coefficient.
float kf_q () const
Get the Kalman filter q coefficient.
int init_sleep_time_ms () const
Get the initial ms sleep time.
int odometry_callback_period_ms () const
Get the odometry callback period ms.
float min_point_dist () const
Get the pl_mapper min_point_dist parameter.
float max_point_dist () const
Get the pl_mapper max_point_dist parameter.
float view_cone_slope () const
Get the pl_mapper view_cone_slope parameter.
const std::string drone_frame_id () const
Get the drone frame ID.
const std::string world_frame_id () const
Get the world frame ID.
const std::string cable_gripper_frame_id () const
Get the cable gripper frame ID.
const std::string mmwave_frame_id () const
Get the mmWave frame ID.
std::shared_ptr< PowerlineDirectionParameters > powerline_direction_parameters () const
Get the PowerlineDirectionParameters.
Public Member Functions inherited from iii_drone::configuration::Configurator
Configurator (rclcpp::Node *node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
Configurator (rclcpp::Node *node, const rclcpp::QoS &qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback=nullptr)
~Configurator ()
template<typename T >
void DeclareParameter (const std::string &name)
rclcpp::Parameter GetParameter (const std::string &name) const
Get a parameter.
std::vector< rclcpp::Parameter > GetParameters (const std::vector< std::string > &names) const
Gets multiple parameters.
void SyncParameters (const std::vector< std::string > &names={})
Synchronizes parameters with the parameter server. Should never be necessary.
void PrintParameters () const
Prints all parameters to the console.
Private Member Functions
void declareNodeParameters ()
Declares the node specific parameters.
void initializeParameters ()
Initializes the parameters.
void powerlineDirectionComputerAfterParameterChangeCallback (const rclcpp::Parameter &parameter)
PowerlineDirectionComputer after parameter change callback.
Private Attributes
std::shared_ptr< PowerlineDirectionParameters > powerline_direction_parameters_
The parameters for the PowerlineDirectionComputer.
std::function< void(const rclcpp::Parameter &) after_parameter_change_callback_)
After parameter change callback.
Additional Inherited Members
Static Public Member Functions inherited from iii_drone::configuration::Configurator
template<typename T >
static std::string GetParameterTypeString ()
Static function for getting string representation of a parameter type from template type.
Protected Attributes inherited from iii_drone::configuration::Configurator
rclcpp::Node * node_
Detailed Description
Class for handling parameters for PowerlineDirectionComputer.
Definition at line 37 of file pl_dir_computer_node_configurator.hpp.
Constructor & Destructor Documentation
PowerlineDirectionComputerConfigurator() [1/2]
PowerlineDirectionComputerConfigurator::PowerlineDirectionComputerConfigurator (rclcpp::Node * node, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback = nullptr)
Constructor.
Parameters
node Reference to the handling node
after_parameter_change_callback Callback function called after successful parameter change, default is nullptr
Definition at line 14 of file pl_dir_computer_node_configurator.cpp.
  : Configurator(
        node,
        std::bind(
            &PowerlineDirectionComputerConfigurator::powerlineDirectionComputerAfterParameterChangeCallback,
            this,
            std::placeholders::_1
        )
    ) {
    after_parameter_change_callback_ = after_parameter_change_callback;
    declareNodeParameters();
    initializeParameters();
}
References after_parameter_change_callback_, declareNodeParameters(), iii_drone::configuration::Configurator::GetParameterTypeString(), and initializeParameters().
PowerlineDirectionComputerConfigurator() [2/2]
PowerlineDirectionComputerConfigurator::PowerlineDirectionComputerConfigurator (rclcpp::Node * node, const rclcpp::QoS & qos, std::function< void(const rclcpp::Parameter &)> after_parameter_change_callback = nullptr)
Constructor.
Parameters
node Reference to the handling node
qos QoS profile for the parameter event subscription
after_parameter_change_callback Callback function called after successful parameter change, default is nullptr
Definition at line 34 of file pl_dir_computer_node_configurator.cpp.
  : Configurator(
        node,
        qos,
        std::bind(
            &PowerlineDirectionComputerConfigurator::powerlineDirectionComputerAfterParameterChangeCallback,
            this,
            std::placeholders::_1
        )
    ) {
    after_parameter_change_callback_ = after_parameter_change_callback;
    declareNodeParameters();
    initializeParameters();
}
References after_parameter_change_callback_, declareNodeParameters(), iii_drone::configuration::Configurator::GetParameterTypeString(), and initializeParameters().
Member Function Documentation
cable_gripper_frame_id()
const std::string PowerlineDirectionComputerConfigurator::cable_gripper_frame_id () const
Get the cable gripper frame ID.
Returns
Cable gripper frame ID
Definition at line 110 of file pl_dir_computer_node_configurator.cpp.
{
    return GetParameter("/tf/cable_gripper_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
declareNodeParameters()
void PowerlineDirectionComputerConfigurator::declareNodeParameters () private
Declares the node specific parameters.
Returns
void
Definition at line 128 of file pl_dir_computer_node_configurator.cpp.
{
    DeclareParameter<float>("/perception/pl_dir_computer/kf_r");
    DeclareParameter<float>("/perception/pl_dir_computer/kf_q");
    DeclareParameter<int>("/perception/pl_dir_computer/init_sleep_time_ms");
    DeclareParameter<int>("/perception/pl_dir_computer/odometry_callback_period_ms");
    DeclareParameter<float>("/perception/pl_mapper/min_point_dist");
    DeclareParameter<float>("/perception/pl_mapper/max_point_dist");
    DeclareParameter<float>("/perception/pl_mapper/view_cone_slope");
    DeclareParameter<std::string>("/tf/drone_frame_id");
    DeclareParameter<std::string>("/tf/world_frame_id");
    DeclareParameter<std::string>("/tf/cable_gripper_frame_id");
    DeclareParameter<std::string>("/tf/mmwave_frame_id");
}
References Configurator::DeclareParameter< std::string >(), and iii_drone::configuration::Configurator::GetParameterTypeString().
Referenced by PowerlineDirectionComputerConfigurator(), and PowerlineDirectionComputerConfigurator().
drone_frame_id()
const std::string PowerlineDirectionComputerConfigurator::drone_frame_id () const
Get the drone frame ID.
Returns
Drone frame ID
Definition at line 98 of file pl_dir_computer_node_configurator.cpp.
{
    return GetParameter("/tf/drone_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters(), iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::odometryCallback(), and iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::publishPowerlineDirection().
init_sleep_time_ms()
int PowerlineDirectionComputerConfigurator::init_sleep_time_ms () const
Get the initial ms sleep time.
Returns
Initial ms sleep time
Definition at line 68 of file pl_dir_computer_node_configurator.cpp.
{
    return GetParameter("/perception/pl_dir_computer/init_sleep_time_ms").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::PowerlineDirectionComputerNode().
initializeParameters()
void PowerlineDirectionComputerConfigurator::initializeParameters () private
Initializes the parameters.
Definition at line 146 of file pl_dir_computer_node_configurator.cpp.
{
    powerline_direction_parameters_ = std::make_shared<iii_drone::perception::PowerlineDirectionParameters>(
        drone_frame_id(),
        kf_r(),
        kf_q()
    );
}
References drone_frame_id(), kf_q(), kf_r(), and powerline_direction_parameters_.
Referenced by PowerlineDirectionComputerConfigurator(), and PowerlineDirectionComputerConfigurator().
kf_q()
float PowerlineDirectionComputerConfigurator::kf_q () const
Get the Kalman filter q coefficient.
Returns
Kalman filter q coefficient
Definition at line 62 of file pl_dir_computer_node_configurator.cpp.
{
    return GetParameter("/perception/pl_dir_computer/kf_q").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters().
kf_r()
float PowerlineDirectionComputerConfigurator::kf_r () const
Get the Kalman filter r coefficient.
Returns
Kalman filter r coefficient
Definition at line 56 of file pl_dir_computer_node_configurator.cpp.
{
    return GetParameter("/perception/pl_dir_computer/kf_r").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by initializeParameters().
max_point_dist()
float PowerlineDirectionComputerConfigurator::max_point_dist () const
Get the pl_mapper max_point_dist parameter.
Returns
pl_mapper max_point_dist parameter
Definition at line 86 of file pl_dir_computer_node_configurator.cpp.
{
    return GetParameter("/perception/pl_mapper/max_point_dist").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
min_point_dist()
float PowerlineDirectionComputerConfigurator::min_point_dist () const
Get the pl_mapper min_point_dist parameter.
Returns
pl_mapper min_point_dist parameter
Definition at line 80 of file pl_dir_computer_node_configurator.cpp.
{
    return GetParameter("/perception/pl_mapper/min_point_dist").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
mmwave_frame_id()
const std::string PowerlineDirectionComputerConfigurator::mmwave_frame_id () const
Get the mmWave frame ID.
Returns
mmWave frame ID
Definition at line 116 of file pl_dir_computer_node_configurator.cpp.
{
    return GetParameter("/tf/mmwave_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
odometry_callback_period_ms()
int PowerlineDirectionComputerConfigurator::odometry_callback_period_ms () const
Get the odometry callback period ms.
Returns
Odometry callback period ms
Definition at line 74 of file pl_dir_computer_node_configurator.cpp.
{
    return GetParameter("/perception/pl_dir_computer/odometry_callback_period_ms").as_int();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::PowerlineDirectionComputerNode().
powerline_direction_parameters()
std::shared_ptr< iii_drone::perception::PowerlineDirectionParameters > PowerlineDirectionComputerConfigurator::powerline_direction_parameters () const
Get the PowerlineDirectionParameters.
Definition at line 122 of file pl_dir_computer_node_configurator.cpp.
{
    return powerline_direction_parameters_;
}
References powerline_direction_parameters_.
powerlineDirectionComputerAfterParameterChangeCallback()
void iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::powerlineDirectionComputerAfterParameterChangeCallback (const rclcpp::Parameter & parameter) private
PowerlineDirectionComputer after parameter change callback.
Parameters
parameter The changed parameter.
view_cone_slope()
float PowerlineDirectionComputerConfigurator::view_cone_slope () const
Get the pl_mapper view_cone_slope parameter.
Returns
pl_mapper view_cone_slope parameter
Definition at line 92 of file pl_dir_computer_node_configurator.cpp.
{
    return GetParameter("/perception/pl_mapper/view_cone_slope").as_double();
}
References iii_drone::configuration::Configurator::GetParameter().
world_frame_id()
const std::string PowerlineDirectionComputerConfigurator::world_frame_id () const
Get the world frame ID.
Returns
World frame ID
Definition at line 104 of file pl_dir_computer_node_configurator.cpp.
{
    return GetParameter("/tf/world_frame_id").as_string();
}
References iii_drone::configuration::Configurator::GetParameter().
Referenced by iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::odometryCallback().
Member Data Documentation
after_parameter_change_callback_
std::function<void(const rclcpp::Parameter &) iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::after_parameter_change_callback_) private
After parameter change callback.
Definition at line 167 of file pl_dir_computer_node_configurator.hpp.
Referenced by PowerlineDirectionComputerConfigurator(), and PowerlineDirectionComputerConfigurator().
powerline_direction_parameters_
std::shared_ptr<PowerlineDirectionParameters> iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::powerline_direction_parameters_ private
The parameters for the PowerlineDirectionComputer.
Definition at line 162 of file pl_dir_computer_node_configurator.hpp.
Referenced by initializeParameters(), and powerline_direction_parameters().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/perception/pl_dir_computer_node/pl_dir_computer_node_configurator.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/perception/pl_dir_computer_node/pl_dir_computer_node_configurator.cpp