III-Drone: iii_drone::adapters::StateAdapter Class Reference
iii_drone::adapters::StateAdapter Class Reference
Class for adapting the III-Drone-Core::State to the III-Drone-Interfaces::State.
#include <state_adapter.hpp>
Public Member Functions
StateAdapter ()
Default constructor.
StateAdapter (const iii_drone::control::State &state)
Constructor from III-Drone-Core::State.
StateAdapter (const iii_drone_interfaces::msg::State &msg)
Constructor from III-Drone-Interfaces::State msg.
StateAdapter (const iii_drone_interfaces::msg::State::SharedPtr &msg)
Constructor from III-Drone-Interfaces::State msg shared pointer.
iii_drone_interfaces::msg::State ToMsg () const
Converts to msg.
geometry_msgs::msg::Pose ToPoseMsg () const
Converts to Pose msg.
geometry_msgs::msg::PoseStamped ToPoseStampedMsg (std::string frame_id, rclcpp::Time stamp=rclcpp::Clock().now()) const
Converts to PoseStamped msg.
iii_drone::control::State state () const
State getter.
Private Attributes
iii_drone::control::State state_
Detailed Description
Class for adapting the III-Drone-Core::State to the III-Drone-Interfaces::State.
Definition at line 39 of file state_adapter.hpp.
Constructor & Destructor Documentation
StateAdapter() [1/4]
StateAdapter::StateAdapter ()
Default constructor.
Definition at line 15 of file state_adapter.cpp.
: state_(iii_drone::control::State()) {}
StateAdapter() [2/4]
StateAdapter::StateAdapter (const iii_drone::control::State & state)
Constructor from III-Drone-Core::State.
Parameters
state The III-Drone-Core::State.
Definition at line 17 of file state_adapter.cpp.
: state_(state) {}
StateAdapter() [3/4]
StateAdapter::StateAdapter (const iii_drone_interfaces::msg::State & msg)
Constructor from III-Drone-Interfaces::State msg.
Parameters
state The III-Drone-Interfaces::State msg.
Definition at line 19 of file state_adapter.cpp.
{
    pose_t pose = poseFromPoseMsg(msg.pose);
    vector_t velocity = vectorFromVectorMsg(msg.velocity);
    vector_t angular_velocity = vectorFromVectorMsg(msg.angular_velocity);
    state_ = iii_drone::control::State(
        pose.position,
        velocity,
        pose.orientation,
        angular_velocity,
        msg.stamp
    );
}
References iii_drone::types::pose_t::orientation, iii_drone::types::poseFromPoseMsg(), iii_drone::types::pose_t::position, state_, and iii_drone::types::vectorFromVectorMsg().
StateAdapter() [4/4]
StateAdapter::StateAdapter (const iii_drone_interfaces::msg::State::SharedPtr & msg)
Constructor from III-Drone-Interfaces::State msg shared pointer.
Parameters
msg The III-Drone-Interfaces::State msg shared pointer.
Definition at line 35 of file state_adapter.cpp.
{
    pose_t pose = poseFromPoseMsg(msg->pose);
    vector_t velocity = vectorFromVectorMsg(msg->velocity);
    vector_t angular_velocity = vectorFromVectorMsg(msg->angular_velocity);
    state_ = iii_drone::control::State(
        pose.position,
        velocity,
        pose.orientation,
        angular_velocity,
        msg->stamp
    );
}
References iii_drone::types::pose_t::orientation, iii_drone::types::poseFromPoseMsg(), iii_drone::types::pose_t::position, state_, and iii_drone::types::vectorFromVectorMsg().
Member Function Documentation
state()
iii_drone::control::State StateAdapter::state () const
State getter.
Returns
The III-Drone-Core::State.
Definition at line 88 of file state_adapter.cpp.
{
    return state_;
}
References state_.
Referenced by iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNode::computeReferenceTrajectoryCallback().
ToMsg()
iii_drone_interfaces::msg::State StateAdapter::ToMsg () const
Converts to msg.
Returns
The III-Drone-Interfaces::State msg.
Definition at line 51 of file state_adapter.cpp.
{
    iii_drone_interfaces::msg::State msg;
    msg.pose = poseMsgFromPose(
        poseFromPose(
            state_.position(),
            state_.quaternion()
        )
    );
    msg.velocity = vectorMsgFromVector(state_.velocity());
    msg.angular_velocity = vectorMsgFromVector(state_.angular_velocity());
    msg.stamp = state_.stamp();
    return msg;
}
References iii_drone::control::State::angular_velocity(), iii_drone::types::poseFromPose(), iii_drone::types::poseMsgFromPose(), iii_drone::control::State::position(), iii_drone::control::State::quaternion(), iii_drone::control::State::stamp(), state_, iii_drone::types::vectorMsgFromVector(), and iii_drone::control::State::velocity().
Referenced by iii_drone::control::TrajectoryGeneratorClient::ComputeReferenceTrajectoryAsync().
ToPoseMsg()
geometry_msgs::msg::Pose StateAdapter::ToPoseMsg () const
Converts to Pose msg.
Returns
The geometry_msgs::msg::Pose msg.
Definition at line 70 of file state_adapter.cpp.
{
    return poseMsgFromPose(
        state_.position(),
        state_.quaternion()
    );
}
References iii_drone::types::poseMsgFromPose(), iii_drone::control::State::position(), iii_drone::control::State::quaternion(), and state_.
Referenced by ToPoseStampedMsg().
ToPoseStampedMsg()
geometry_msgs::msg::PoseStamped StateAdapter::ToPoseStampedMsg (std::string frame_id, rclcpp::Time stamp = rclcpp::Clock().now()) const
Converts to PoseStamped msg.
Parameters
frame_id The frame id.
stamp The stamp, default is rclcpp::Clock().now().
Returns
The geometry_msgs::msg::PoseStamped msg.
Definition at line 77 of file state_adapter.cpp.
        {
    geometry_msgs::msg::PoseStamped msg;
    msg.header.frame_id = frame_id;
    msg.header.stamp = stamp;
    msg.pose = ToPoseMsg();
    return msg;
}
References ToPoseMsg().
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::publishFeedback(), and iii_drone::control::maneuver::FlyToPositionManeuverServer::publishFeedback().
Member Data Documentation
state_
iii_drone::control::State iii_drone::adapters::StateAdapter::state_ private
Definition at line 102 of file state_adapter.hpp.
Referenced by state(), StateAdapter(), StateAdapter(), ToMsg(), and ToPoseMsg().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/adapters/state_adapter.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/adapters/state_adapter.cpp