III-Drone: iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNode Class Reference
iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNode Class Reference
#include <trajectory_generator_node.hpp>
Public Member Functions
TrajectoryGeneratorNode (const std::string node_name="trajectory_generator", const std::string node_namespace="/control/trajectory_generator", const rclcpp::NodeOptions &options=rclcpp::NodeOptions())
~TrajectoryGeneratorNode ()
Private Member Functions
void computeReferenceTrajectoryCallback (const std::shared_ptr< iii_drone_interfaces::srv::ComputeReferenceTrajectory::Request > request, std::shared_ptr< iii_drone_interfaces::srv::ComputeReferenceTrajectory::Response > response)
The compute reference trajectory service callback.
void publishPlannedTrajectory ()
Publishes the currently planned trajectory.
Private Attributes
TrajectoryGeneratorNodeConfigurator configurator_
Configurator.
TrajectoryGenerator trajectory_generator_
The trajectory generator object.
rclcpp::Service< iii_drone_interfaces::srv::ComputeReferenceTrajectory >::SharedPtr compute_reference_trajectory_service_
The compute reference trajectory service.
rclcpp::TimerBase::SharedPtr publish_timer_
Publish timer.
rclcpp::Publisher< nav_msgs::msg::Path >::SharedPtr reference_trajectory_path_publisher_
Publisher for planned trajectory path.
rclcpp::Publisher< geometry_msgs::msg::PoseStamped >::SharedPtr reference_pose_publisher_
Publisher for trajectory target pose.
iii_drone::utils::Atomic< iii_drone::control::ReferenceTrajectory > reference_trajectory_
The most recently planned state trajectory.
iii_drone::utils::Atomic< iii_drone::control::Reference > reference_
The current target for the trajectory planning.
Detailed Description
Definition at line 53 of file trajectory_generator_node.hpp.
Constructor & Destructor Documentation
TrajectoryGeneratorNode()
TrajectoryGeneratorNode::TrajectoryGeneratorNode (const std::string node_name = "trajectory_generator", const std::string node_namespace = "/control/trajectory_generator", const rclcpp::NodeOptions & options = rclcpp::NodeOptions())
Constructor.
Parameters
node_name The name of the node.
node_namespace The namespace of the node.
options The options for the node.
Definition at line 13 of file trajectory_generator_node.cpp.
  : Node(node_name, node_namespace, options),
    configurator_(this),
    trajectory_generator_(
        configurator_.positional_mpc_parameters(),
        configurator_.cable_landing_mpc_parameters(),
        configurator_.cable_takeoff_mpc_parameters()
    )
{
    compute_reference_trajectory_service_ = this->create_service<iii_drone_interfaces::srv::ComputeReferenceTrajectory>(
        "compute_reference_trajectory",
        std::bind(
            &TrajectoryGeneratorNode::computeReferenceTrajectoryCallback,
            this,
            std::placeholders::_1,
            std::placeholders::_2
        )
    );
    reference_trajectory_path_publisher_ = this->create_publisher<nav_msgs::msg::Path>("reference_trajectory", 10);
    reference_pose_publisher_ = this->create_publisher<geometry_msgs::msg::PoseStamped>("reference", 10);
    publish_timer_ = this->create_wall_timer(
        std::chrono::milliseconds(100),
        std::bind(&TrajectoryGeneratorNode::publishPlannedTrajectory, this)
    );
}
References compute_reference_trajectory_service_, computeReferenceTrajectoryCallback(), publish_timer_, publishPlannedTrajectory(), reference_pose_publisher_, and reference_trajectory_path_publisher_.
~TrajectoryGeneratorNode()
TrajectoryGeneratorNode::~TrajectoryGeneratorNode ()
Destructor.
Definition at line 46 of file trajectory_generator_node.cpp.
{}
Member Function Documentation
computeReferenceTrajectoryCallback()
void TrajectoryGeneratorNode::computeReferenceTrajectoryCallback (const std::shared_ptr< iii_drone_interfaces::srv::ComputeReferenceTrajectory::Request > request, std::shared_ptr< iii_drone_interfaces::srv::ComputeReferenceTrajectory::Response > response) private
The compute reference trajectory service callback.
Parameters
request The request
response The response
Returns
void
Definition at line 48 of file trajectory_generator_node.cpp.
  {
    adapters::StateAdapter state_adapter(request->state);
    adapters::ReferenceAdapter reference_adapter(request->reference);
    if (request->set_reference || request->reset) {
        reference_ = reference_adapter.reference();
    }
    // Compute the reference trajectory
    ReferenceTrajectory ref_traj = trajectory_generator_.ComputeReferenceTrajectory(
        state_adapter.state(),
        reference_adapter.reference(),
        request->set_reference,
        request->reset,
        (MPC_mode_t)request->mpc_mode.mode
    );
    reference_trajectory_ = ref_traj;
    // Set the response
    response->reference_trajectory = adapters::ReferenceTrajectoryAdapter(ref_traj).ToMsg();
    // Start publish thread, detach
    std::thread publish_thread = std::thread(&TrajectoryGeneratorNode::publishPlannedTrajectory, this);
    publish_thread.detach();
}
References iii_drone::control::TrajectoryGenerator::ComputeReferenceTrajectory(), publishPlannedTrajectory(), iii_drone::adapters::ReferenceAdapter::reference(), reference_, reference_trajectory_, iii_drone::adapters::StateAdapter::state(), iii_drone::adapters::ReferenceTrajectoryAdapter::ToMsg(), and trajectory_generator_.
Referenced by TrajectoryGeneratorNode().
publishPlannedTrajectory()
void TrajectoryGeneratorNode::publishPlannedTrajectory () private
Publishes the currently planned trajectory.
Returns
void
Definition at line 80 of file trajectory_generator_node.cpp.
{
    nav_msgs::msg::Path path = iii_drone::adapters::ReferenceTrajectoryAdapter(reference_trajectory_).ToPathMsg(configurator_.world_frame_id());
    geometry_msgs::msg::PoseStamped reference_pose = iii_drone::adapters::ReferenceAdapter(reference_).ToPoseStampedMsg(configurator_.world_frame_id());
    reference_trajectory_path_publisher_->publish(path);
    reference_pose_publisher_->publish(reference_pose);
}
References configurator_, reference_, reference_pose_publisher_, reference_trajectory_, reference_trajectory_path_publisher_, iii_drone::adapters::ReferenceTrajectoryAdapter::ToPathMsg(), iii_drone::adapters::ReferenceAdapter::ToPoseStampedMsg(), and iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator::world_frame_id().
Referenced by computeReferenceTrajectoryCallback(), and TrajectoryGeneratorNode().
Member Data Documentation
compute_reference_trajectory_service_
rclcpp::Service<iii_drone_interfaces::srv::ComputeReferenceTrajectory>::SharedPtr iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNode::compute_reference_trajectory_service_ private
The compute reference trajectory service.
Definition at line 89 of file trajectory_generator_node.hpp.
Referenced by TrajectoryGeneratorNode().
configurator_
TrajectoryGeneratorNodeConfigurator iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNode::configurator_ private
Configurator.
Definition at line 79 of file trajectory_generator_node.hpp.
Referenced by publishPlannedTrajectory().
publish_timer_
rclcpp::TimerBase::SharedPtr iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNode::publish_timer_ private
Publish timer.
Definition at line 107 of file trajectory_generator_node.hpp.
Referenced by TrajectoryGeneratorNode().
reference_
iii_drone::utils::Atomic<iii_drone::control::Reference> iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNode::reference_ private
The current target for the trajectory planning.
Definition at line 127 of file trajectory_generator_node.hpp.
Referenced by computeReferenceTrajectoryCallback(), and publishPlannedTrajectory().
reference_pose_publisher_
rclcpp::Publisher<geometry_msgs::msg::PoseStamped>::SharedPtr iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNode::reference_pose_publisher_ private
Publisher for trajectory target pose.
Definition at line 117 of file trajectory_generator_node.hpp.
Referenced by publishPlannedTrajectory(), and TrajectoryGeneratorNode().
reference_trajectory_
iii_drone::utils::Atomic<iii_drone::control::ReferenceTrajectory> iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNode::reference_trajectory_ private
The most recently planned state trajectory.
Definition at line 122 of file trajectory_generator_node.hpp.
Referenced by computeReferenceTrajectoryCallback(), and publishPlannedTrajectory().
reference_trajectory_path_publisher_
rclcpp::Publisher<nav_msgs::msg::Path>::SharedPtr iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNode::reference_trajectory_path_publisher_ private
Publisher for planned trajectory path.
Definition at line 112 of file trajectory_generator_node.hpp.
Referenced by publishPlannedTrajectory(), and TrajectoryGeneratorNode().
trajectory_generator_
TrajectoryGenerator iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNode::trajectory_generator_ private
The trajectory generator object.
Definition at line 84 of file trajectory_generator_node.hpp.
Referenced by computeReferenceTrajectoryCallback().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/trajectory_generator_node/trajectory_generator_node.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/trajectory_generator_node/trajectory_generator_node.cpp