III-Drone: iii_drone::utils::Token< T > Class Template Reference
iii_drone::utils::Token< T > Class Template Reference
Token class for managing access to a resource shared between threads from a master thread.
#include <token.hpp>
Classes
struct slave_request_t
Slave request struct.
Public Types
typedef std::shared_ptr< Token< T > > SharedPtr
Shared pointer type.
Public Member Functions
Token (const Token< T > &other)
Copy constructor.
Token (T &resource, std::function< void()> master_acquired_token_callback)
Constructor.
Token (std::shared_ptr< T > resource, std::function< void()> master_acquired_token_callback)
Constructor from shared ptr.
~Token ()
Destructor.
Token< T > CreateSlaveHandle (const std::string &slave_name)
Creates a slave handle.
bool Acquire (unsigned int timeout_ms=0)
Request to acquire the token, to be called by a slave.
void Release ()
Releases the token, to be called by a slave.
void Give (const std::string &slave_name)
Gives the token to a slave, to be called by the master.
void Deny (const std::string &slave_name)
Denies the token to a slave, to be called by the master.
void DenyAll ()
Denies all pending token requests, to be called by the master.
T & resource () const
Get the resource.
std::vector< std::string > slaves () const
Get all slave names.
std::string token_holder () const
Get the token holder name.
bool has_token () const
Whether the token is held by the calling thread.
bool has_token (const std::string &name) const
Whether the token is held by a thread.
bool master_has_token () const
Whether the token is held by the master.
bool has_requested_token (const std::string &slave_name) const
Whether a slave has requested the token.
std::vector< std::string > requested_token_slaves () const
Slaves that have requested the token.
Token< T > & operator= (const T &rhs)
Assignment operator.
Private Member Functions
void answerSlaveAcquisitionRequest (const std::string &slave_name, bool give)
Answers a slave acquisition request.
bool is_master () const
Is master.
void masterAcquiredTokenInternalCallback ()
Master acquired token internal callback.
Private Attributes
std::shared_ptr< std::mutex > resource_mutex_
Resource mutex.
std::unique_lock< std::mutex > resource_local_lock_
Resource local lock.
std::shared_ptr< T > resource_
Resource.
std::string name_
Handle name.
std::shared_ptr< std::mutex > slaves_mutex_
Slaves mutex.
std::shared_ptr< std::vector< std::string > > slaves_
Slaves vector.
iii_drone::utils::Atomic< std::string >::SharedPtr token_holder_
Name of thread that has the token.
std::shared_ptr< std::mutex > slaves_request_queue_mutex_
Slaves request queue mutex.
std::shared_ptr< std::vector< slave_request_t > > slaves_request_queue_
Slaves request queue.
std::function< void()> master_acquired_token_callback_
Callback executed when master reacquires token from a slave.
Detailed Description
template<typename T>
class iii_drone::utils::Token< T >
Token class for managing access to a resource shared between threads from a master thread.
Template Parameters
T Resource type
Definition at line 35 of file token.hpp.
Member Typedef Documentation
SharedPtr
template<typename T > typedef std::shared_ptr<Token<T> > iii_drone::utils::Token< T >::SharedPtr
Shared pointer type.
Definition at line 577 of file token.hpp.
Constructor & Destructor Documentation
Token() [1/3]
template<typename T > iii_drone::utils::Token< T >::Token (const Token< T > & other) inline
Copy constructor.
Parameters
other The other token.
Definition at line 43 of file token.hpp.
{
            resource_mutex_ = other.resource_mutex_;
            resource_local_lock_ = std::unique_lock<std::mutex>(*resource_mutex_);
            resource_ = other.resource_;
            name_ = other.name_;
            slaves_mutex_ = other.slaves_mutex_;
            slaves_ = other.slaves_;
            token_holder_ = other.token_holder_;
            slaves_request_queue_mutex_ = other.slaves_request_queue_mutex_;
            slaves_request_queue_ = other.slaves_request_queue_;
            master_acquired_token_callback_ = other.master_acquired_token_callback_;
        }
References iii_drone::utils::Token< T >::master_acquired_token_callback_, iii_drone::utils::Token< T >::name_, iii_drone::utils::Token< T >::resource_, iii_drone::utils::Token< T >::resource_local_lock_, iii_drone::utils::Token< T >::resource_mutex_, iii_drone::utils::Token< T >::slaves_, iii_drone::utils::Token< T >::slaves_mutex_, iii_drone::utils::Token< T >::slaves_request_queue_, iii_drone::utils::Token< T >::slaves_request_queue_mutex_, and iii_drone::utils::Token< T >::token_holder_.
Token() [2/3]
template<typename T > iii_drone::utils::Token< T >::Token (T & resource, std::function< void()> master_acquired_token_callback) inline
Constructor.
Parameters
resource Resource
master_acquired_token_callback Callback to be called when master acquires token
Definition at line 69 of file token.hpp.
          {
            resource_mutex_ = std::make_shared<std::mutex>();
            resource_local_lock_ = std::unique_lock<std::mutex>(*resource_mutex_);
            resource_ = std::make_shared<T>(resource);
            name_ = "master";
            slaves_mutex_ = std::make_shared<std::mutex>();
            slaves_ = std::make_shared<std::vector<std::string>>();
            token_holder_ = std::make_shared<iii_drone::utils::Atomic<std::string>>("master");
            slaves_request_queue_mutex_ = std::make_shared<std::mutex>();
            slaves_request_queue_ = std::make_shared<std::vector<slave_request_t>>();
            master_acquired_token_callback_ = master_acquired_token_callback;
        }
References iii_drone::utils::Token< T >::master_acquired_token_callback_, iii_drone::utils::Token< T >::name_, iii_drone::utils::Token< T >::resource(), iii_drone::utils::Token< T >::resource_, iii_drone::utils::Token< T >::resource_local_lock_, iii_drone::utils::Token< T >::resource_mutex_, iii_drone::utils::Token< T >::slaves_, iii_drone::utils::Token< T >::slaves_mutex_, iii_drone::utils::Token< T >::slaves_request_queue_, iii_drone::utils::Token< T >::slaves_request_queue_mutex_, and iii_drone::utils::Token< T >::token_holder_.
Token() [3/3]
template<typename T > iii_drone::utils::Token< T >::Token (std::shared_ptr< T > resource, std::function< void()> master_acquired_token_callback) inline
Constructor from shared ptr.
Parameters
resource Resource
master_acquired_token_callback Callback to be called when master acquires token
Definition at line 98 of file token.hpp.
          {
            resource_mutex_ = std::make_shared<std::mutex>();
            resource_local_lock_ = std::unique_lock<std::mutex>(*resource_mutex_);
            resource_ = resource;
            name_ = "master";
            slaves_mutex_ = std::make_shared<std::mutex>();
            slaves_ = std::make_shared<std::vector<std::string>>();
            token_holder_ = std::make_shared<iii_drone::utils::Atomic<std::string>>("master");
            slaves_request_queue_mutex_ = std::make_shared<std::mutex>();
            slaves_request_queue_ = std::make_shared<std::vector<slave_request_t>>();
            master_acquired_token_callback_ = master_acquired_token_callback;
        }
References iii_drone::utils::Token< T >::master_acquired_token_callback_, iii_drone::utils::Token< T >::name_, iii_drone::utils::Token< T >::resource(), iii_drone::utils::Token< T >::resource_, iii_drone::utils::Token< T >::resource_local_lock_, iii_drone::utils::Token< T >::resource_mutex_, iii_drone::utils::Token< T >::slaves_, iii_drone::utils::Token< T >::slaves_mutex_, iii_drone::utils::Token< T >::slaves_request_queue_, iii_drone::utils::Token< T >::slaves_request_queue_mutex_, and iii_drone::utils::Token< T >::token_holder_.
~Token()
template<typename T > iii_drone::utils::Token< T >::~Token () inline
Destructor.
Definition at line 124 of file token.hpp.
                 {
            if (is_master()) {
                std::unique_lock<std::mutex> lock(*slaves_mutex_);
                if (!slaves_->empty()) {
                    std::cerr << "Master destroyed with slaves still alive." << std::endl;
                }
                lock.unlock();
            } else {
                std::unique_lock<std::mutex> request_lock(*slaves_request_queue_mutex_);
                // Remove any request from slave
                auto it1 = std::find_if(
                    slaves_request_queue_->begin(),
                    slaves_request_queue_->end(),
                    [this](const slave_request_t & slave_request_queue_item) {
                        return slave_request_queue_item.slave_name == name_;
                    }
                );
                if (it1 != slaves_request_queue_->end()) {
                    slaves_request_queue_->erase(it1);
                }
                request_lock.unlock();
                std::unique_lock<std::mutex> slaves_lock(*slaves_mutex_);
                // Remove slave from master
                auto it2 = std::find(slaves_->begin(), slaves_->end(), name_);
                if (it2 != slaves_->end()) {
                    slaves_->erase(it2);
                } else {
                    std::cerr << "Slave destroyed but not in master's slave list.";
                }
                slaves_lock.unlock();
                if (has_token()) {
                    Release();
                }
            }
        }
References iii_drone::utils::Token< T >::has_token(), iii_drone::utils::Token< T >::is_master(), iii_drone::utils::Token< T >::name_, iii_drone::utils::Token< T >::Release(), iii_drone::utils::Token< T >::slaves_, iii_drone::utils::Token< T >::slaves_mutex_, iii_drone::utils::Token< T >::slaves_request_queue_, and iii_drone::utils::Token< T >::slaves_request_queue_mutex_.
Member Function Documentation
Acquire()
template<typename T > bool iii_drone::utils::Token< T >::Acquire (unsigned int timeout_ms = 0) inline
Request to acquire the token, to be called by a slave.
Parameters
timeout_ms Timeout in milliseconds, 0 for infinite timeout
Returns
True if token was acquired, false otherwise
Definition at line 249 of file token.hpp.
          {
            if (is_master()) {
                throw std::runtime_error("Master cannot request token.");
            }
            if (has_token()) {
                return true;
            }
            std::unique_lock<std::mutex> lock(*slaves_request_queue_mutex_);
            // Check if slave has already requested token:
            auto it1 = std::find_if(
                slaves_request_queue_->begin(),
                slaves_request_queue_->end(),
                [this](const slave_request_t & slave_request_queue_item) {
                    return slave_request_queue_item.slave_name == name_;
                }
            );
            if (it1 != slaves_request_queue_->end()) {
                throw std::runtime_error("Slave has already requested token.");
            }
            slave_request_t slave_request {
                name_,
                std::make_shared<std::promise<bool>>()
            };
            slaves_request_queue_->push_back(slave_request);
            auto acquired_token_future = slave_request.acquired_token_promise->get_future();
            lock.unlock();
            if (timeout_ms == 0) {
                acquired_token_future.wait();
                if (acquired_token_future.get()) {
                    if (!has_token()) {
                        throw std::runtime_error("Slave acquired token but does not have it.");
                    }
                    if (!resource_local_lock_.try_lock()) {
                        throw std::runtime_error("Slave acquired token but cannot lock resource mutex.");
                    }
                    return true;
                }
            } else {
                if (acquired_token_future.wait_for(std::chrono::milliseconds(timeout_ms)) == std::future_status::ready) {
                    if (acquired_token_future.get()) {
                        if (!has_token()) {
                            throw std::runtime_error("Slave acquired token but does not have it.");
                        }
                        if (!resource_local_lock_.try_lock()) {
                            throw std::runtime_error("Slave acquired token but cannot lock resource mutex.");
                        }
                        return true;
                    }
                }
            }
            lock.lock();
            auto it2 = std::find_if(
                slaves_request_queue_->begin(),
                slaves_request_queue_->end(),
                [&slave_request](const slave_request_t & slave_request_queue_item) {
                    return slave_request_queue_item.slave_name == slave_request.slave_name;
                }
            );
            if (it2 != slaves_request_queue_->end()) {
                slaves_request_queue_->erase(it2);
            }
            return false;
        }
References iii_drone::utils::Token< T >::has_token(), iii_drone::utils::Token< T >::is_master(), iii_drone::utils::Token< T >::name_, iii_drone::utils::Token< T >::resource_local_lock_, iii_drone::utils::Token< T >::slaves_request_queue_, and iii_drone::utils::Token< T >::slaves_request_queue_mutex_.
answerSlaveAcquisitionRequest()
template<typename T > void iii_drone::utils::Token< T >::answerSlaveAcquisitionRequest (const std::string & slave_name, bool give) inline private
Answers a slave acquisition request.
Parameters
slave_name Slave name
give Whether to give the token to the slave
Definition at line 586 of file token.hpp.
          {
            if (!is_master()) {
                throw std::runtime_error("Only master can give token.");
            }
            if (slave_name == "master") {
                throw std::runtime_error("Slave name cannot be \"master\".");
            }
            std::unique_lock<std::mutex> slaves_lock(*slaves_mutex_);
            if (std::find(slaves_->begin(), slaves_->end(), slave_name) == slaves_->end()) {
                throw std::runtime_error("Slave name does not exist.");
            }
            slaves_lock.unlock();
            if (give && !has_token()) {
                throw std::runtime_error("Master does not have token to give.");
            }
            std::unique_lock<std::mutex> slaves_request_queue_lock(*slaves_request_queue_mutex_);
            auto it = std::find_if(
                slaves_request_queue_->begin(),
                slaves_request_queue_->end(),
                [this, &slave_name](const slave_request_t & slave_request_queue_item) {
                    return slave_request_queue_item.slave_name == slave_name;
                }
            );
            if (it == slaves_request_queue_->end()) {
                throw std::runtime_error("Slave has not requested token.");
            }
            auto acquired_token_promise = it->acquired_token_promise;
            slaves_request_queue_->erase(it);
            slaves_request_queue_lock.unlock();
            (*token_holder_) = slave_name;
            if (give) {
                resource_local_lock_.unlock();
            }
            acquired_token_promise->set_value(give);
        }
References iii_drone::utils::Token< T >::has_token(), iii_drone::utils::Token< T >::is_master(), iii_drone::utils::Token< T >::resource_local_lock_, iii_drone::utils::Token< T >::slaves_, iii_drone::utils::Token< T >::slaves_mutex_, iii_drone::utils::Token< T >::slaves_request_queue_, and iii_drone::utils::Token< T >::slaves_request_queue_mutex_.
Referenced by iii_drone::utils::Token< T >::Deny(), and iii_drone::utils::Token< T >::Give().
CreateSlaveHandle()
template<typename T > Token< T > iii_drone::utils::Token< T >::CreateSlaveHandle (const std::string & slave_name) inline
Creates a slave handle.
Parameters
slave_name Slave name
Returns
Slave handle
Definition at line 191 of file token.hpp.
{
            std::unique_lock<std::mutex> lock(*slaves_mutex_);
            if (!is_master()) {
                throw std::runtime_error("Only master can create slave tokens.");
            }
            if (slave_name == "master") {
                throw std::runtime_error("Slave name cannot be \"master\".");
            }
            if (std::find(slaves_->begin(), slaves_->end(), slave_name) != slaves_->end()) {
                throw std::runtime_error("Slave name already exists.");
            }
            Token<T> slave_handle(
                resource_,
                master_acquired_token_callback_
            );
            slave_handle.resource_mutex_ = resource_mutex_;
            slave_handle.resource_local_lock_ = std::unique_lock<std::mutex>(*resource_mutex_, std::defer_lock);
            slave_handle.resource_ = resource_;
            slave_handle.name_ = slave_name;
            slave_handle.slaves_mutex_ = slaves_mutex_;
            slave_handle.slaves_ = slaves_;
            slave_handle.slaves_->push_back(slave_name);
            slave_handle.token_holder_ = token_holder_;
            slave_handle.slaves_request_queue_mutex_ = slaves_request_queue_mutex_;
            slave_handle.slaves_request_queue_ = slaves_request_queue_;
            slave_handle.master_acquired_token_callback_ = std::bind(
                &Token<T>::masterAcquiredTokenInternalCallback,
                this
            );
            return slave_handle;
        }
References iii_drone::utils::Token< T >::is_master(), iii_drone::utils::Token< T >::master_acquired_token_callback_, iii_drone::utils::Token< T >::name_, iii_drone::utils::Token< T >::resource_, iii_drone::utils::Token< T >::resource_local_lock_, iii_drone::utils::Token< T >::resource_mutex_, iii_drone::utils::Token< T >::slaves_, iii_drone::utils::Token< T >::slaves_mutex_, iii_drone::utils::Token< T >::slaves_request_queue_, iii_drone::utils::Token< T >::slaves_request_queue_mutex_, and iii_drone::utils::Token< T >::token_holder_.
Referenced by iii_drone::control::maneuver::ManeuverScheduler::RegisterManeuverServer().
Deny()
template<typename T > void iii_drone::utils::Token< T >::Deny (const std::string & slave_name) inline
Denies the token to a slave, to be called by the master.
Parameters
slave_name Slave name
Definition at line 403 of file token.hpp.
{
            answerSlaveAcquisitionRequest(
                slave_name,
                false
            );
        }
References iii_drone::utils::Token< T >::answerSlaveAcquisitionRequest().
DenyAll()
template<typename T > void iii_drone::utils::Token< T >::DenyAll () inline
Denies all pending token requests, to be called by the master.
Definition at line 415 of file token.hpp.
                       {
            if (!is_master()) {
                throw std::runtime_error("Only master can give token.");
            }
            std::unique_lock<std::mutex> lock(*slaves_request_queue_mutex_);
            for (auto & slave_request_queue_item : *slaves_request_queue_) {
                slave_request_queue_item.acquired_token_promise->set_value(false);
            }
            slaves_request_queue_->clear();
        }
References iii_drone::utils::Token< T >::is_master(), iii_drone::utils::Token< T >::slaves_request_queue_, and iii_drone::utils::Token< T >::slaves_request_queue_mutex_.
Referenced by iii_drone::control::maneuver::ManeuverScheduler::progressScheduler().
Give()
template<typename T > void iii_drone::utils::Token< T >::Give (const std::string & slave_name) inline
Gives the token to a slave, to be called by the master.
Parameters
slave_name Slave name
Definition at line 389 of file token.hpp.
{
            answerSlaveAcquisitionRequest(
                slave_name,
                true
            );
        }
References iii_drone::utils::Token< T >::answerSlaveAcquisitionRequest().
Referenced by iii_drone::control::maneuver::ManeuverScheduler::progressScheduler().
has_requested_token()
template<typename T > bool iii_drone::utils::Token< T >::has_requested_token (const std::string & slave_name) const inline
Whether a slave has requested the token.
Parameters
slave_name Slave name
Definition at line 516 of file token.hpp.
{
            std::unique_lock<std::mutex> lock(*slaves_request_queue_mutex_);
            auto it = std::find_if(
                slaves_request_queue_->begin(),
                slaves_request_queue_->end(),
                [this, &slave_name](const slave_request_t & slave_request_queue_item) {
                    return slave_request_queue_item.slave_name == slave_name;
                }
            );
            return it != slaves_request_queue_->end();
        }
References iii_drone::utils::Token< T >::slaves_request_queue_, and iii_drone::utils::Token< T >::slaves_request_queue_mutex_.
Referenced by iii_drone::control::maneuver::ManeuverScheduler::progressScheduler().
has_token() [1/2]
template<typename T > bool iii_drone::utils::Token< T >::has_token () const inline
Whether the token is held by the calling thread.
Definition at line 485 of file token.hpp.
{
            return token_holder_->Load() == name_;
        }
References iii_drone::utils::Token< T >::name_, and iii_drone::utils::Token< T >::token_holder_.
Referenced by iii_drone::utils::Token< T >::Acquire(), iii_drone::utils::Token< T >::answerSlaveAcquisitionRequest(), iii_drone::utils::Token< T >::operator=(), iii_drone::utils::Token< T >::Release(), iii_drone::utils::Token< T >::resource(), and iii_drone::utils::Token< T >::~Token().
has_token() [2/2]
template<typename T > bool iii_drone::utils::Token< T >::has_token (const std::string & name) const inline
Whether the token is held by a thread.
Parameters
name Name
Definition at line 496 of file token.hpp.
{
            return token_holder_->Load() == name;
        }
References iii_drone::utils::Token< T >::token_holder_.
is_master()
template<typename T > bool iii_drone::utils::Token< T >::is_master () const inline private
Is master.
Definition at line 671 of file token.hpp.
{
            return name_ == "master";
        }
References iii_drone::utils::Token< T >::name_.
Referenced by iii_drone::utils::Token< T >::Acquire(), iii_drone::utils::Token< T >::answerSlaveAcquisitionRequest(), iii_drone::utils::Token< T >::CreateSlaveHandle(), iii_drone::utils::Token< T >::DenyAll(), iii_drone::utils::Token< T >::Release(), and iii_drone::utils::Token< T >::~Token().
master_has_token()
template<typename T > bool iii_drone::utils::Token< T >::master_has_token () const inline
Whether the token is held by the master.
Definition at line 505 of file token.hpp.
{
            return token_holder_->Load() == "master";
        }
References iii_drone::utils::Token< T >::token_holder_.
Referenced by iii_drone::control::maneuver::ManeuverScheduler::onReferenceCallbackTokenReacquired(), and iii_drone::control::maneuver::ManeuverScheduler::progressScheduler().
masterAcquiredTokenInternalCallback()
template<typename T > void iii_drone::utils::Token< T >::masterAcquiredTokenInternalCallback () inline private
Master acquired token internal callback.
Definition at line 732 of file token.hpp.
{
            if (!resource_local_lock_.try_lock()) {
                throw std::runtime_error("Master acquired token but cannot lock resource mutex.");
            }
            if (master_acquired_token_callback_) {
                master_acquired_token_callback_();
            }
        }
References iii_drone::utils::Token< T >::master_acquired_token_callback_, and iii_drone::utils::Token< T >::resource_local_lock_.
operator=()
template<typename T > Token< T > & iii_drone::utils::Token< T >::operator= (const T & rhs) inline
Assignment operator.
Definition at line 554 of file token.hpp.
{
            if (!has_token()) {
                throw std::runtime_error("Thread does not have token.");
            }
            if (!resource_local_lock_.owns_lock()) {
                throw std::runtime_error("Thread does not own resource local lock.");
            }
            *resource_ = rhs;
            return *this;
        }
References iii_drone::utils::Token< T >::has_token(), iii_drone::utils::Token< T >::resource_, and iii_drone::utils::Token< T >::resource_local_lock_.
Release()
template<typename T > void iii_drone::utils::Token< T >::Release () inline
Releases the token, to be called by a slave.
Definition at line 362 of file token.hpp.
                       {
            if (is_master()) {
                throw std::runtime_error("Master cannot release token.");
            }
            if (!has_token()) {
                throw std::runtime_error("Slave does not have token.");
            }
            resource_local_lock_.unlock();
            (*token_holder_) = "master";
            master_acquired_token_callback_();
        }
References iii_drone::utils::Token< T >::has_token(), iii_drone::utils::Token< T >::is_master(), iii_drone::utils::Token< T >::master_acquired_token_callback_, and iii_drone::utils::Token< T >::resource_local_lock_.
Referenced by iii_drone::utils::Token< T >::~Token().
requested_token_slaves()
template<typename T > std::vector< std::string > iii_drone::utils::Token< T >::requested_token_slaves () const inline
Slaves that have requested the token.
Definition at line 535 of file token.hpp.
{
            std::unique_lock<std::mutex> lock(slaves_request_queue_mutex_);
            std::vector<std::string> requested_token_slaves;
            for (auto & slave_request_queue_item : *slaves_request_queue_) {
                requested_token_slaves.push_back(slave_request_queue_item.slave_name);
            }
            return requested_token_slaves;
        }
References iii_drone::utils::Token< T >::requested_token_slaves(), iii_drone::utils::Token< T >::slaves_request_queue_, and iii_drone::utils::Token< T >::slaves_request_queue_mutex_.
Referenced by iii_drone::utils::Token< T >::requested_token_slaves().
resource()
template<typename T > T & iii_drone::utils::Token< T >::resource () const inline
Get the resource.
Returns
Resource
Definition at line 440 of file token.hpp.
{
            if (!has_token()) {
                throw std::runtime_error("Thread does not have token.");
            }
            if (!resource_local_lock_.owns_lock()) {
                throw std::runtime_error("Thread does not own resource local lock.");
            }
            return *resource_;
        }
References iii_drone::utils::Token< T >::has_token(), iii_drone::utils::Token< T >::resource_, and iii_drone::utils::Token< T >::resource_local_lock_.
Referenced by iii_drone::control::maneuver::ManeuverScheduler::onReferenceCallbackTokenReacquired(), iii_drone::utils::Token< T >::Token(), and iii_drone::utils::Token< T >::Token().
slaves()
template<typename T > std::vector< std::string > iii_drone::utils::Token< T >::slaves () const inline
Get all slave names.
Returns
Slave names
Definition at line 463 of file token.hpp.
{
            std::unique_lock<std::mutex> lock(slaves_mutex_);
            return *slaves_;
        }
References iii_drone::utils::Token< T >::slaves_, and iii_drone::utils::Token< T >::slaves_mutex_.
token_holder()
template<typename T > std::string iii_drone::utils::Token< T >::token_holder () const inline
Get the token holder name.
Returns
Token holder name
Definition at line 476 of file token.hpp.
{
            return token_holder_->Load();
        }
References iii_drone::utils::Token< T >::token_holder_.
Member Data Documentation
master_acquired_token_callback_
template<typename T > std::function<void()> iii_drone::utils::Token< T >::master_acquired_token_callback_ private
Callback executed when master reacquires token from a slave.
Definition at line 727 of file token.hpp.
Referenced by iii_drone::utils::Token< T >::CreateSlaveHandle(), iii_drone::utils::Token< T >::masterAcquiredTokenInternalCallback(), iii_drone::utils::Token< T >::Release(), iii_drone::utils::Token< T >::Token(), iii_drone::utils::Token< T >::Token(), and iii_drone::utils::Token< T >::Token().
name_
template<typename T > std::string iii_drone::utils::Token< T >::name_ private
Handle name.
Definition at line 680 of file token.hpp.
Referenced by iii_drone::utils::Token< T >::Acquire(), iii_drone::utils::Token< T >::CreateSlaveHandle(), iii_drone::utils::Token< T >::has_token(), iii_drone::utils::Token< T >::is_master(), iii_drone::utils::Token< T >::Token(), iii_drone::utils::Token< T >::Token(), iii_drone::utils::Token< T >::Token(), and iii_drone::utils::Token< T >::~Token().
resource_
template<typename T > std::shared_ptr<T> iii_drone::utils::Token< T >::resource_ private
Resource.
Definition at line 666 of file token.hpp.
Referenced by iii_drone::utils::Token< T >::CreateSlaveHandle(), iii_drone::utils::Token< T >::operator=(), iii_drone::utils::Token< T >::resource(), iii_drone::utils::Token< T >::Token(), iii_drone::utils::Token< T >::Token(), and iii_drone::utils::Token< T >::Token().
resource_local_lock_
template<typename T > std::unique_lock<std::mutex> iii_drone::utils::Token< T >::resource_local_lock_ private
Resource local lock.
Definition at line 661 of file token.hpp.
Referenced by iii_drone::utils::Token< T >::Acquire(), iii_drone::utils::Token< T >::answerSlaveAcquisitionRequest(), iii_drone::utils::Token< T >::CreateSlaveHandle(), iii_drone::utils::Token< T >::masterAcquiredTokenInternalCallback(), iii_drone::utils::Token< T >::operator=(), iii_drone::utils::Token< T >::Release(), iii_drone::utils::Token< T >::resource(), iii_drone::utils::Token< T >::Token(), iii_drone::utils::Token< T >::Token(), and iii_drone::utils::Token< T >::Token().
resource_mutex_
template<typename T > std::shared_ptr<std::mutex> iii_drone::utils::Token< T >::resource_mutex_ private
Resource mutex.
Definition at line 656 of file token.hpp.
Referenced by iii_drone::utils::Token< T >::CreateSlaveHandle(), iii_drone::utils::Token< T >::Token(), iii_drone::utils::Token< T >::Token(), and iii_drone::utils::Token< T >::Token().
slaves_
template<typename T > std::shared_ptr<std::vector<std::string> > iii_drone::utils::Token< T >::slaves_ private
Slaves vector.
Definition at line 690 of file token.hpp.
Referenced by iii_drone::utils::Token< T >::answerSlaveAcquisitionRequest(), iii_drone::utils::Token< T >::CreateSlaveHandle(), iii_drone::utils::Token< T >::slaves(), iii_drone::utils::Token< T >::Token(), iii_drone::utils::Token< T >::Token(), iii_drone::utils::Token< T >::Token(), and iii_drone::utils::Token< T >::~Token().
slaves_mutex_
template<typename T > std::shared_ptr<std::mutex> iii_drone::utils::Token< T >::slaves_mutex_ private
Slaves mutex.
Definition at line 685 of file token.hpp.
Referenced by iii_drone::utils::Token< T >::answerSlaveAcquisitionRequest(), iii_drone::utils::Token< T >::CreateSlaveHandle(), iii_drone::utils::Token< T >::slaves(), iii_drone::utils::Token< T >::Token(), iii_drone::utils::Token< T >::Token(), iii_drone::utils::Token< T >::Token(), and iii_drone::utils::Token< T >::~Token().
slaves_request_queue_
template<typename T > std::shared_ptr<std::vector<slave_request_t> > iii_drone::utils::Token< T >::slaves_request_queue_ private
Slaves request queue.
Definition at line 722 of file token.hpp.
Referenced by iii_drone::utils::Token< T >::Acquire(), iii_drone::utils::Token< T >::answerSlaveAcquisitionRequest(), iii_drone::utils::Token< T >::CreateSlaveHandle(), iii_drone::utils::Token< T >::DenyAll(), iii_drone::utils::Token< T >::has_requested_token(), iii_drone::utils::Token< T >::requested_token_slaves(), iii_drone::utils::Token< T >::Token(), iii_drone::utils::Token< T >::Token(), iii_drone::utils::Token< T >::Token(), and iii_drone::utils::Token< T >::~Token().
slaves_request_queue_mutex_
template<typename T > std::shared_ptr<std::mutex> iii_drone::utils::Token< T >::slaves_request_queue_mutex_ private
Slaves request queue mutex.
Definition at line 717 of file token.hpp.
Referenced by iii_drone::utils::Token< T >::Acquire(), iii_drone::utils::Token< T >::answerSlaveAcquisitionRequest(), iii_drone::utils::Token< T >::CreateSlaveHandle(), iii_drone::utils::Token< T >::DenyAll(), iii_drone::utils::Token< T >::has_requested_token(), iii_drone::utils::Token< T >::requested_token_slaves(), iii_drone::utils::Token< T >::Token(), iii_drone::utils::Token< T >::Token(), iii_drone::utils::Token< T >::Token(), and iii_drone::utils::Token< T >::~Token().
token_holder_
template<typename T > iii_drone::utils::Atomic<std::string>::SharedPtr iii_drone::utils::Token< T >::token_holder_ private
Name of thread that has the token.
Definition at line 695 of file token.hpp.
Referenced by iii_drone::utils::Token< T >::CreateSlaveHandle(), iii_drone::utils::Token< T >::has_token(), iii_drone::utils::Token< T >::has_token(), iii_drone::utils::Token< T >::master_has_token(), iii_drone::utils::Token< T >::Token(), iii_drone::utils::Token< T >::Token(), iii_drone::utils::Token< T >::Token(), and iii_drone::utils::Token< T >::token_holder().
The documentation for this class was generated from the following file:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/utils/token.hpp