III-Drone: iii_drone::control::maneuver::HoverManeuverServer Class Reference
iii_drone::control::maneuver::HoverManeuverServer Class Reference
Class for serving hovering. When the hover action is called, the drone will start hovering, and the action will succeed immediately. The maneuver scheduler will then keep hovering until a new maneuver is scheduled or the timeout elapses by the duration given in the hover action call. Exposes external methods for getting the reference and updating the hover reference. Other maneuver servers will use this server to generate references before a new maneuver is scheduled.
#include <hover_maneuver_server.hpp>
Public Member Functions
HoverManeuverServer (rclcpp::Node *node, CombinedDroneAwarenessHandler::SharedPtr combined_drone_awareness_handler, const std::string &action_name, unsigned int wait_for_execute_poll_ms, unsigned int evaluate_done_poll_ms, bool use_nans=true)
Constructor.
bool CanExecuteManeuver (const Maneuver &maneuver, const combined_drone_awareness_t &drone_awareness) const override
Whether the maneuver can be executed, will return true if the drone is armed and offboard.
combined_drone_awareness_t ExpectedAwarenessAfterExecution (const Maneuver &maneuver) override
Expected awareness after execution.
void Update (const iii_drone::control::State &state)
Updates the hover reference.
void Update (const iii_drone::control::Reference &reference)
Updates the hover reference.
iii_drone::control::Reference GetReference (const iii_drone::control::State &state)
Gets the hover reference.
Public Member Functions inherited from iii_drone::control::maneuver::ManeuverServer
ManeuverServer (rclcpp::Node *node, CombinedDroneAwarenessHandler::SharedPtr awareness_handler, const std::string &action_name, unsigned int wait_for_execute_poll_ms, unsigned int evaluate_done_poll_ms)
Constructor.
void Start (std::function< bool(Maneuver, bool &)> register_maneuver_function, std::function< bool(Maneuver)> update_manuever_function, std::function< bool(Maneuver)> cancel_maneuver_function, std::function< bool(Maneuver)> verify_maneuver_in_queue_function, std::function< bool(Maneuver)> verify_maneuver_active_function, std::function< void(Maneuver)> done_callback, ReferenceCallbackToken::SharedPtr reference_callback_token, std::map< iii_drone::control::maneuver::maneuver_type_t, std::shared_ptr< ManeuverServer > > registered_maneuvers)
Method to start the maneuver server. The maneuver server will reject any new goals until started.
void Stop ()
Method to stop the maneuver server. The maneuver server will reject any new goals until started.
std::string action_name () const
Action name getter.
bool running () const
Returns whether the maneuver server is running.
Private Types
using Hover = iii_drone_interfaces::action::Hover
Private Member Functions
maneuver_type_t maneuver_type () const override
The maneuver type (MANEUVER_TYPE_HOVER)
void startExecution (Maneuver &maneuver) override
Starts the execution of the maneuver. Registers the current drone state as the hover reference.
bool canCancel () override
Whether the maneuver can be canceled, always returns true.
iii_drone::control::Reference computeReference (const iii_drone::control::State &state) override
Compute the hover reference.
bool hasSucceeded (Maneuver &maneuver) override
Whether the maneuver has succeeded, always returns true.
bool hasFailed (Maneuver &maneuver) override
Whether the maneuver has failed, always returns false.
void publishFeedback (Maneuver &maneuver) override
Does nothing.
void publishResultAndFinalize (Maneuver &maneuver, maneuver_result_type_t maneuver_result_type) override
Publishes the result and finalizes the maneuver according to the maneuver result type.
void registerReferenceCallbackOnSuccess (const Maneuver &maneuver) override
Registers the hover reference callback on success.
Private Attributes
iii_drone::utils::Atomic< Reference > hover_reference_
The hover reference.
bool use_nans_
Whether to use NaNs for velocity and acceleration, otherwise uses zeros.
Additional Inherited Members
Public Types inherited from iii_drone::control::maneuver::ManeuverServer
typedef std::shared_ptr< ManeuverServer > SharedPtr
Shared pointer type.
Protected Types inherited from iii_drone::control::maneuver::ManeuverServer
enum maneuver_result_type_t { MANEUVER_RESULT_TYPE_SUCCEED , MANEUVER_RESULT_TYPE_CANCEL , MANEUVER_RESULT_TYPE_ABORT }
Maneuver result type enum.
Protected Member Functions inherited from iii_drone::control::maneuver::ManeuverServer
const CombinedDroneAwarenessHandler::SharedPtr & awareness_handler () const
Combined drone awareness handler, accessible to derived classes through the protected method.
const iii_drone::utils::Atomic< iii_drone::control::maneuver::Maneuver > & current_maneuver () const
The currently executing maneuver, accessible to derived classes through the protected method.
rclcpp::Node * node () const
Node pointer getter.
std::map< iii_drone::control::maneuver::maneuver_type_t, std::shared_ptr< iii_drone::control::maneuver::ManeuverServer > > registered_maneuvers () const
Registered maneuvers map getter.
void registerCallback (const std::function< Reference(const State &)> &callback)
Registers a callback function for the reference. The callback function should be registered with the reference callback token.
template<typename ActionT >
void createServer ()
Creates the underlying action server.
Detailed Description
Class for serving hovering. When the hover action is called, the drone will start hovering, and the action will succeed immediately. The maneuver scheduler will then keep hovering until a new maneuver is scheduled or the timeout elapses by the duration given in the hover action call. Exposes external methods for getting the reference and updating the hover reference. Other maneuver servers will use this server to generate references before a new maneuver is scheduled.
Definition at line 43 of file hover_maneuver_server.hpp.
Member Typedef Documentation
Hover
using iii_drone::control::maneuver::HoverManeuverServer::Hover = iii_drone_interfaces::action::Hover private
Definition at line 44 of file hover_maneuver_server.hpp.
Constructor & Destructor Documentation
HoverManeuverServer()
HoverManeuverServer::HoverManeuverServer (rclcpp::Node * node, CombinedDroneAwarenessHandler::SharedPtr combined_drone_awareness_handler, const std::string & action_name, unsigned int wait_for_execute_poll_ms, unsigned int evaluate_done_poll_ms, bool use_nans = true)
Constructor.
Parameters
node Node pointer
combined_drone_awareness_handler Combined drone awareness handler pointer
action_name Action name
wait_for_execute_poll_ms Wait for execute poll milliseconds
evaluate_done_poll_ms Evaluate done poll milliseconds
use_nans Whether to use NaNs for velocity and acceleration, otherwise uses zeros, default true.
Definition at line 15 of file hover_maneuver_server.cpp.
  : ManeuverServer(
    node,
    combined_drone_awareness_handler,
    action_name,
    wait_for_execute_poll_ms,
    evaluate_done_poll_ms
),  use_nans_(use_nans) {
    createServer<Hover>();
}
Member Function Documentation
canCancel()
bool HoverManeuverServer::canCancel () override private virtual
Whether the maneuver can be canceled, always returns true.
Returns
bool Whether the maneuver can be canceled.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 163 of file hover_maneuver_server.cpp.
{
    return true;
}
CanExecuteManeuver()
bool HoverManeuverServer::CanExecuteManeuver (const Maneuver & maneuver, const combined_drone_awareness_t & drone_awareness) const override virtual
Whether the maneuver can be executed, will return true if the drone is armed and offboard.
Parameters
maneuver The maneuver.
drone_awareness The drone awareness.
Returns
bool Whether the maneuver can be executed.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 34 of file hover_maneuver_server.cpp.
        {
    if (maneuver.maneuver_type() != MANEUVER_TYPE_HOVER) {
        return false;
    }
    if (!drone_awareness.offboard) {
        return false;
    }
    if (!drone_awareness.armed) {
        return false;
    }
    if (!drone_awareness.in_flight()) {
        return false;
    }
    return true;
}
References iii_drone::control::combined_drone_awareness_t::armed, iii_drone::control::combined_drone_awareness_t::in_flight(), iii_drone::control::maneuver::Maneuver::maneuver_type(), iii_drone::control::maneuver::MANEUVER_TYPE_HOVER, and iii_drone::control::combined_drone_awareness_t::offboard.
computeReference()
iii_drone::control::Reference HoverManeuverServer::computeReference (const iii_drone::control::State & state) override private virtual
Compute the hover reference.
Parameters
state The current state.
Returns
The hover reference.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 167 of file hover_maneuver_server.cpp.
{
    return GetReference(state);
}
References GetReference().
ExpectedAwarenessAfterExecution()
combined_drone_awareness_t HoverManeuverServer::ExpectedAwarenessAfterExecution (const Maneuver & maneuver) override virtual
Expected awareness after execution.
Parameters
maneuver The maneuver.
Returns
The expected awareness after execution.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 59 of file hover_maneuver_server.cpp.
{
    combined_drone_awareness_t awareness_after;
    awareness_after.armed = true;
    awareness_after.offboard = true;
    awareness_after.target_adapter = iii_drone::adapters::TargetAdapter();
    awareness_after.target_position_known = false;
    awareness_after.drone_location = DRONE_LOCATION_IN_FLIGHT;
    return awareness_after;
}
References iii_drone::control::combined_drone_awareness_t::armed, iii_drone::control::combined_drone_awareness_t::drone_location, iii_drone::control::DRONE_LOCATION_IN_FLIGHT, iii_drone::control::combined_drone_awareness_t::offboard, iii_drone::control::combined_drone_awareness_t::target_adapter, and iii_drone::control::combined_drone_awareness_t::target_position_known.
GetReference()
iii_drone::control::Reference HoverManeuverServer::GetReference (const iii_drone::control::State & state)
Gets the hover reference.
Parameters
state The current state, is not used.
Returns
The hover reference.
Definition at line 138 of file hover_maneuver_server.cpp.
{
    return Reference(
        hover_reference_->position(),
        hover_reference_->yaw(),
        hover_reference_->velocity(),
        hover_reference_->yaw_rate(),
        hover_reference_->acceleration(),
        hover_reference_->yaw_acceleration()
    );
}
References hover_reference_.
Referenced by computeReference(), iii_drone::control::maneuver::ManeuverScheduler::onReferenceCallbackTokenReacquired(), iii_drone::control::maneuver::FlyToPositionManeuverServer::registerReferenceCallbackOnSuccess(), and registerReferenceCallbackOnSuccess().
hasFailed()
bool HoverManeuverServer::hasFailed (Maneuver & maneuver) override private virtual
Whether the maneuver has failed, always returns false.
Parameters
maneuver The maneuver.
Returns
bool Whether the maneuver has failed.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 177 of file hover_maneuver_server.cpp.
{
    return false;
}
hasSucceeded()
bool HoverManeuverServer::hasSucceeded (Maneuver & maneuver) override private virtual
Whether the maneuver has succeeded, always returns true.
Parameters
maneuver The maneuver.
Returns
bool Whether the maneuver has succeeded.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 173 of file hover_maneuver_server.cpp.
{
    return true;
}
maneuver_type()
maneuver_type_t HoverManeuverServer::maneuver_type () const override private virtual
The maneuver type (MANEUVER_TYPE_HOVER)
Returns
The maneuver type.
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 151 of file hover_maneuver_server.cpp.
{
    return MANEUVER_TYPE_HOVER;
}
References iii_drone::control::maneuver::MANEUVER_TYPE_HOVER.
publishFeedback()
void HoverManeuverServer::publishFeedback (Maneuver & maneuver) override private virtual
Does nothing.
Parameters
maneuver The maneuver.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 181 of file hover_maneuver_server.cpp.
{
    // No feedback to publish
}
publishResultAndFinalize()
void HoverManeuverServer::publishResultAndFinalize (Maneuver & maneuver, maneuver_result_type_t maneuver_result_type) override private virtual
Publishes the result and finalizes the maneuver according to the maneuver result type.
Parameters
maneuver The maneuver.
maneuver_result_type The maneuver result type.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 185 of file hover_maneuver_server.cpp.
  {
    auto result = std::make_shared<Hover::Result>();
    auto goal_handle = std::static_pointer_cast<rclcpp_action::ServerGoalHandle<Hover>>(maneuver.goal_handle());
    switch (maneuver_result_type) {
        case MANEUVER_RESULT_TYPE_SUCCEED:
            goal_handle->succeed(result);
            break;
        case MANEUVER_RESULT_TYPE_ABORT:
            goal_handle->abort(result);
            break;
        case MANEUVER_RESULT_TYPE_CANCEL:
            goal_handle->canceled(result);
            break;
    }
}
References iii_drone::control::maneuver::Maneuver::goal_handle(), iii_drone::control::maneuver::ManeuverServer::MANEUVER_RESULT_TYPE_ABORT, iii_drone::control::maneuver::ManeuverServer::MANEUVER_RESULT_TYPE_CANCEL, and iii_drone::control::maneuver::ManeuverServer::MANEUVER_RESULT_TYPE_SUCCEED.
registerReferenceCallbackOnSuccess()
void HoverManeuverServer::registerReferenceCallbackOnSuccess (const Maneuver & maneuver) override private virtual
Registers the hover reference callback on success.
Parameters
maneuver The maneuver.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 207 of file hover_maneuver_server.cpp.
{
    registerCallback(
        std::bind(
            &HoverManeuverServer::GetReference,
            this,
            std::placeholders::_1
        )
    );
}
References GetReference(), and iii_drone::control::maneuver::ManeuverServer::registerCallback().
startExecution()
void HoverManeuverServer::startExecution (Maneuver & maneuver) override private virtual
Starts the execution of the maneuver. Registers the current drone state as the hover reference.
Parameters
maneuver The maneuver.
Returns
void
Implements iii_drone::control::maneuver::ManeuverServer.
Definition at line 155 of file hover_maneuver_server.cpp.
{
    Update(awareness_handler()->GetState());
    awareness_handler()->ClearTarget();
}
References iii_drone::control::maneuver::ManeuverServer::awareness_handler(), iii_drone::control::CombinedDroneAwarenessHandler::ClearTarget(), and Update().
Update() [1/2]
void HoverManeuverServer::Update (const iii_drone::control::Reference & reference)
Updates the hover reference.
Parameters
reference The hover reference.
Returns
void
Definition at line 105 of file hover_maneuver_server.cpp.
{
    point_t position = hover_reference.position();
    double yaw = hover_reference.yaw();
    vector_t velocity;
    vector_t acceleration;
    double yaw_rate;
    double yaw_acceleration;
    if(use_nans_) {
        velocity = vector_t(NAN, NAN, NAN);
        acceleration = vector_t(NAN, NAN, NAN);
        yaw_rate = NAN;
        yaw_acceleration = NAN;
    } else {
        velocity = vector_t(0.0, 0.0, 0.0);
        acceleration = vector_t(0.0, 0.0, 0.0);
        yaw_rate = 0.0;
        yaw_acceleration = 0.0;
    }
    hover_reference_ = iii_drone::control::Reference(
        position,
        yaw,
        velocity,
        yaw_rate,
        acceleration,
        yaw_acceleration
    );
}
References hover_reference_, iii_drone::control::Reference::position(), use_nans_, and iii_drone::control::Reference::yaw().
Update() [2/2]
void HoverManeuverServer::Update (const iii_drone::control::State & state)
Updates the hover reference.
Parameters
state The current state.
Returns
void
Definition at line 72 of file hover_maneuver_server.cpp.
{
    point_t position = hover_state.position();
    double yaw = hover_state.yaw();
    vector_t velocity;
    vector_t acceleration;
    double yaw_rate;
    double yaw_acceleration;
    if(use_nans_) {
        velocity = vector_t(NAN, NAN, NAN);
        acceleration = vector_t(NAN, NAN, NAN);
        yaw_rate = NAN;
        yaw_acceleration = NAN;
    } else {
        velocity = vector_t(0.0, 0.0, 0.0);
        acceleration = vector_t(0.0, 0.0, 0.0);
        yaw_rate = 0.0;
        yaw_acceleration = 0.0;
    }
    hover_reference_ = iii_drone::control::Reference(
        position,
        yaw,
        velocity,
        yaw_rate,
        acceleration,
        yaw_acceleration
    );
}
References hover_reference_, iii_drone::control::State::position(), use_nans_, and iii_drone::control::State::yaw().
Referenced by startExecution().
Member Data Documentation
hover_reference_
iii_drone::utils::Atomic<Reference> iii_drone::control::maneuver::HoverManeuverServer::hover_reference_ private
The hover reference.
Definition at line 199 of file hover_maneuver_server.hpp.
Referenced by GetReference(), Update(), and Update().
use_nans_
bool iii_drone::control::maneuver::HoverManeuverServer::use_nans_ private
Whether to use NaNs for velocity and acceleration, otherwise uses zeros.
Definition at line 204 of file hover_maneuver_server.hpp.
Referenced by Update(), and Update().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/maneuver/hover_maneuver_server.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/maneuver/hover_maneuver_server.cpp