III-Drone: iii_drone::control::State Class Reference
iii_drone::control::State Class Reference
#include <state.hpp>
Public Member Functions
State (const iii_drone::types::point_t position, const iii_drone::types::vector_t velocity, const iii_drone::types::quaternion_t quaternion, const iii_drone::types::vector_t angular_velocity, const rclcpp::Time stamp=rclcpp::Clock().now())
State (const iii_drone::types::point_t position, const iii_drone::types::vector_t velocity, double yaw, const iii_drone::types::vector_t angular_velocity, const rclcpp::Time stamp=rclcpp::Clock().now())
State ()
const iii_drone::types::point_t position () const
const iii_drone::types::vector_t velocity () const
const iii_drone::types::quaternion_t quaternion () const
double yaw () const
const iii_drone::types::vector_t angular_velocity () const
const rclcpp::Time stamp () const
Private Attributes
iii_drone::types::point_t position_
iii_drone::types::vector_t velocity_
iii_drone::types::quaternion_t quaternion_
double yaw_
iii_drone::types::vector_t angular_velocity_
rclcpp::Time stamp_
Detailed Description
Class representing a drone state.
Definition at line 29 of file state.hpp.
Constructor & Destructor Documentation
State() [1/3]
State::State (const iii_drone::types::point_t position, const iii_drone::types::vector_t velocity, const iii_drone::types::quaternion_t quaternion, const iii_drone::types::vector_t angular_velocity, const rclcpp::Time stamp = rclcpp::Clock().now())
Constructor.
Parameters
position The position.
velocity The velocity.
quaternion The quaternion.
angular_velocity The angular velocity.
stamp The timestamp, defaults to now.
Definition at line 14 of file state.cpp.
  {
    position_ = position;
    velocity_ = velocity;
    quaternion_ = quaternion;
    euler_angles_t eul = iii_drone::math::quatToEul(quaternion);
    yaw_ = eul(2);
    angular_velocity_ = angular_velocity;
    stamp_ = stamp;
}
References angular_velocity(), angular_velocity_, position(), position_, quaternion(), quaternion_, iii_drone::math::quatToEul(), stamp(), stamp_, velocity(), velocity_, and yaw_.
State() [2/3]
State::State (const iii_drone::types::point_t position, const iii_drone::types::vector_t velocity, double yaw, const iii_drone::types::vector_t angular_velocity, const rclcpp::Time stamp = rclcpp::Clock().now())
Constructor.
Parameters
position The position.
velocity The velocity.
yaw The yaw.
angular_velocity The angular velocity.
stamp The timestamp, defaults to now.
Definition at line 32 of file state.cpp.
  {
    position_ = position;
    velocity_ = velocity;
    yaw_ = yaw;
    quaternion_ = iii_drone::math::eulToQuat(euler_angles_t(0, 0, yaw));
    angular_velocity_ = angular_velocity;
    stamp_ = stamp;
}
References angular_velocity(), angular_velocity_, iii_drone::math::eulToQuat(), position(), position_, quaternion_, stamp(), stamp_, velocity(), velocity_, yaw(), and yaw_.
State() [3/3]
State::State ()
Default constructor for empty object.
Definition at line 49 of file state.cpp.
             {
    position_ = point_t::Zero();
    velocity_ = vector_t::Zero();
    quaternion_ = quaternion_t::Identity();
    angular_velocity_ = vector_t::Zero();
    stamp_ = rclcpp::Clock().now();
}
References angular_velocity_, position_, quaternion_, stamp_, and velocity_.
Member Function Documentation
angular_velocity()
const vector_t State::angular_velocity () const
Getter for the angular velocity.
Returns
The angular velocity.
Definition at line 75 of file state.cpp.
{
    return angular_velocity_;
}
References angular_velocity_.
Referenced by State(), State(), iii_drone::adapters::StateAdapter::ToMsg(), and iii_drone::adapters::px4::TrajectorySetpointAdapter::TrajectorySetpointAdapter().
position()
const point_t State::position () const
Getter for the position.
Returns
The position.
Definition at line 59 of file state.cpp.
{
    return position_;
}
References position_.
Referenced by iii_drone::control::maneuver::HoverByObjectManeuverServer::GetReference(), iii_drone::control::maneuver::FlyToObjectManeuverServer::getUpdatedTargetReference(), iii_drone::control::maneuver::FlyToObjectManeuverServer::hasSucceeded(), iii_drone::control::maneuver::FlyToPositionManeuverServer::hasSucceeded(), iii_drone::control::maneuver::FlyToObjectManeuverServer::publishFeedback(), iii_drone::control::Reference::Reference(), iii_drone::control::TrajectoryGeneratorClient::Reset(), iii_drone::control::TrajectoryGenerator::setupMPC(), State(), State(), iii_drone::adapters::StateAdapter::ToMsg(), iii_drone::adapters::StateAdapter::ToPoseMsg(), iii_drone::adapters::px4::TrajectorySetpointAdapter::TrajectorySetpointAdapter(), iii_drone::control::maneuver::HoverManeuverServer::Update(), and iii_drone::control::maneuver::HoverByObjectManeuverServer::validateTargetTransform().
quaternion()
const quaternion_t State::quaternion () const
Getter for the quaternion.
Returns
The quaternion.
Definition at line 67 of file state.cpp.
{
    return quaternion_;
}
References quaternion_.
Referenced by iii_drone::control::Reference::Reference(), State(), iii_drone::adapters::StateAdapter::ToMsg(), iii_drone::adapters::StateAdapter::ToPoseMsg(), and iii_drone::adapters::px4::TrajectorySetpointAdapter::TrajectorySetpointAdapter().
stamp()
const rclcpp::Time State::stamp () const
Getter for the timestamp.
Definition at line 79 of file state.cpp.
{
    return stamp_;
}
References stamp_.
Referenced by iii_drone::control::TrajectoryGenerator::ComputeReferenceTrajectory(), iii_drone::control::Reference::Reference(), State(), State(), iii_drone::adapters::StateAdapter::ToMsg(), and iii_drone::adapters::px4::TrajectorySetpointAdapter::TrajectorySetpointAdapter().
velocity()
const vector_t State::velocity () const
Getter for the velocity.
Returns
The velocity.
Definition at line 63 of file state.cpp.
{
    return velocity_;
}
References velocity_.
Referenced by iii_drone::control::Reference::Reference(), iii_drone::control::TrajectoryGenerator::setupMPC(), State(), State(), iii_drone::adapters::StateAdapter::ToMsg(), and iii_drone::adapters::px4::TrajectorySetpointAdapter::TrajectorySetpointAdapter().
yaw()
double State::yaw () const
Getter for the yaw.
Returns
The yaw.
Definition at line 71 of file state.cpp.
{
    return yaw_;
}
References yaw_.
Referenced by iii_drone::control::maneuver::HoverByObjectManeuverServer::GetReference(), iii_drone::control::maneuver::FlyToObjectManeuverServer::getUpdatedTargetReference(), iii_drone::control::maneuver::FlyToObjectManeuverServer::hasSucceeded(), iii_drone::control::maneuver::FlyToPositionManeuverServer::hasSucceeded(), iii_drone::control::TrajectoryGeneratorClient::Reset(), State(), and iii_drone::control::maneuver::HoverManeuverServer::Update().
Member Data Documentation
angular_velocity_
iii_drone::types::vector_t iii_drone::control::State::angular_velocity_ private
The angular velocity.
Definition at line 134 of file state.hpp.
Referenced by angular_velocity(), State(), State(), and State().
position_
iii_drone::types::point_t iii_drone::control::State::position_ private
The position.
Definition at line 114 of file state.hpp.
Referenced by position(), State(), State(), and State().
quaternion_
iii_drone::types::quaternion_t iii_drone::control::State::quaternion_ private
The quaternion.
Definition at line 124 of file state.hpp.
Referenced by quaternion(), State(), State(), and State().
stamp_
rclcpp::Time iii_drone::control::State::stamp_ private
The timestamp.
Definition at line 139 of file state.hpp.
Referenced by stamp(), State(), State(), and State().
velocity_
iii_drone::types::vector_t iii_drone::control::State::velocity_ private
The velocity.
Definition at line 119 of file state.hpp.
Referenced by State(), State(), State(), and velocity().
yaw_
double iii_drone::control::State::yaw_ private
The yaw.
Definition at line 129 of file state.hpp.
Referenced by State(), State(), and yaw().
The documentation for this class was generated from the following files:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/control/state.hpp
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/control/state.cpp