III-Drone: iii_drone::utils::BlockingQueue< T > Class Template Reference
iii_drone::utils::BlockingQueue< T > Class Template Reference
Generic blocking queue class.
#include <blocking_queue.hpp>
Public Member Functions
BlockingQueue (int size)
Constructor.
bool Push (T item, bool block)
Pushes an item to the queue.
bool Pop (T &read_item, bool block)
Pops an item from the queue.
bool Peak (T &read_item, bool block)
Peeks an item from the queue.
bool Empty ()
Peeks an item from the queue.
bool Full ()
Whether the queue is full.
void Clear ()
Clears the queue.
int size ()
Get the current size of the queue.
Private Member Functions
bool readItem (T &read_item, bool block, bool pop)
Reads an item from the queue.
Private Attributes
int max_size_
Maximum size of the queue.
std::mutex reader_mutex_
Reader mutex for the queue.
std::mutex writer_mutex_
Writer mutex for the queue.
std::condition_variable is_not_full_
Condition variable for the queue not being empty.
std::condition_variable is_not_empty_
Condition variable for the queue not being full.
Detailed Description
template<class T>
class iii_drone::utils::BlockingQueue< T >
Generic blocking queue class.
Template Parameters
T Type of the queue
Definition at line 26 of file blocking_queue.hpp.
Constructor & Destructor Documentation
BlockingQueue()
template<class T > iii_drone::utils::BlockingQueue< T >::BlockingQueue (int size) inline
Constructor.
Parameters
size Queue size
Definition at line 33 of file blocking_queue.hpp.
{
            max_size_ = size;
        }
References iii_drone::utils::BlockingQueue< T >::max_size_, and iii_drone::utils::BlockingQueue< T >::size().
Member Function Documentation
Clear()
template<class T > void iii_drone::utils::BlockingQueue< T >::Clear () inline
Clears the queue.
Definition at line 150 of file blocking_queue.hpp.
                     {
            std::unique_lock<std::mutex> wlck(writer_mutex_);
            std::queue<T>::clear();
            is_not_full_.notify_all();
        }
References iii_drone::utils::BlockingQueue< T >::is_not_full_, and iii_drone::utils::BlockingQueue< T >::writer_mutex_.
Empty()
template<class T > bool iii_drone::utils::BlockingQueue< T >::Empty () inline
Peeks an item from the queue.
Parameters
compare_item Item to compare
Returns
true If the item was read, false otherwise
Definition at line 130 of file blocking_queue.hpp.
                     {
            return std::queue<T>::empty();
        }
Referenced by iii_drone::utils::BlockingQueue< T >::readItem().
Full()
template<class T > bool iii_drone::utils::BlockingQueue< T >::Full () inline
Whether the queue is full.
Returns
true If the queue is full, false otherwise
Definition at line 141 of file blocking_queue.hpp.
                   {
            return std::queue<T>::size() >= max_size_;
        }
References iii_drone::utils::BlockingQueue< T >::max_size_.
Referenced by iii_drone::utils::BlockingQueue< T >::Push(), and iii_drone::utils::BlockingQueue< T >::readItem().
Peak()
template<class T > bool iii_drone::utils::BlockingQueue< T >::Peak (T & read_item, bool block) inline
Peeks an item from the queue.
Parameters
read_item Read item
block Whether to block if the queue is empty
Returns
true If the item was read, false otherwise
Definition at line 93 of file blocking_queue.hpp.
{
            return readItem(read_item, block, false);
        }
References iii_drone::utils::BlockingQueue< T >::readItem().
Pop()
template<class T > bool iii_drone::utils::BlockingQueue< T >::Pop (T & read_item, bool block) inline
Pops an item from the queue.
Parameters
read_item Read item
block Whether to block if the queue is empty
Returns
true If the item was read, false otherwise
Definition at line 79 of file blocking_queue.hpp.
{
            return readItem(read_item, block, true);
        }
References iii_drone::utils::BlockingQueue< T >::readItem().
Push()
template<class T > bool iii_drone::utils::BlockingQueue< T >::Push (T item, bool block) inline
Pushes an item to the queue.
Parameters
item Item to push
block Whether to block if the queue is full
Returns
true If the item was pushed, false otherwise
Definition at line 47 of file blocking_queue.hpp.
          {
            std::unique_lock<std::mutex> wlck(writer_mutex_);
            if(Full()) {
                if (!block)
                    return false;
                is_not_full_.wait(wlck);
            }
            std::queue<T>::push(item);
            is_not_empty_.notify_all();
            return true;
        }
References iii_drone::utils::BlockingQueue< T >::Full(), iii_drone::utils::BlockingQueue< T >::is_not_empty_, iii_drone::utils::BlockingQueue< T >::is_not_full_, and iii_drone::utils::BlockingQueue< T >::writer_mutex_.
readItem()
template<class T > bool iii_drone::utils::BlockingQueue< T >::readItem (T & read_item, bool block, bool pop) inline private
Reads an item from the queue.
Parameters
read_item Read item
block If true, blocks until there is an item in the queue
pop If true, pops the item from the queue
Returns
true if item was read, false otherwise
Definition at line 205 of file blocking_queue.hpp.
{
            std::unique_lock<std::mutex> lck(reader_mutex_);
            while(Empty()) {
                if (!block) {
                    return false;
                };
                is_not_empty_.wait(lck);
            }
            read_item = std::queue<T>::front();
            if (pop)
                std::queue<T>::pop();
            if(!Full())
                is_not_full_.notify_all();
            return true;
        }
References iii_drone::utils::BlockingQueue< T >::Empty(), iii_drone::utils::BlockingQueue< T >::Full(), iii_drone::utils::BlockingQueue< T >::is_not_empty_, iii_drone::utils::BlockingQueue< T >::is_not_full_, and iii_drone::utils::BlockingQueue< T >::reader_mutex_.
Referenced by iii_drone::utils::BlockingQueue< T >::Peak(), and iii_drone::utils::BlockingQueue< T >::Pop().
size()
template<class T > int iii_drone::utils::BlockingQueue< T >::size () inline
Get the current size of the queue.
Returns
Current size of the queue
Definition at line 164 of file blocking_queue.hpp.
                   {
            return std::queue<T>::size();
        }
Referenced by iii_drone::utils::BlockingQueue< T >::BlockingQueue().
Member Data Documentation
is_not_empty_
template<class T > std::condition_variable iii_drone::utils::BlockingQueue< T >::is_not_empty_ private
Condition variable for the queue not being full.
Definition at line 194 of file blocking_queue.hpp.
Referenced by iii_drone::utils::BlockingQueue< T >::Push(), and iii_drone::utils::BlockingQueue< T >::readItem().
is_not_full_
template<class T > std::condition_variable iii_drone::utils::BlockingQueue< T >::is_not_full_ private
Condition variable for the queue not being empty.
Definition at line 189 of file blocking_queue.hpp.
Referenced by iii_drone::utils::BlockingQueue< T >::Clear(), iii_drone::utils::BlockingQueue< T >::Push(), and iii_drone::utils::BlockingQueue< T >::readItem().
max_size_
template<class T > int iii_drone::utils::BlockingQueue< T >::max_size_ private
Maximum size of the queue.
Definition at line 174 of file blocking_queue.hpp.
Referenced by iii_drone::utils::BlockingQueue< T >::BlockingQueue(), and iii_drone::utils::BlockingQueue< T >::Full().
reader_mutex_
template<class T > std::mutex iii_drone::utils::BlockingQueue< T >::reader_mutex_ private
Reader mutex for the queue.
Definition at line 179 of file blocking_queue.hpp.
Referenced by iii_drone::utils::BlockingQueue< T >::readItem().
writer_mutex_
template<class T > std::mutex iii_drone::utils::BlockingQueue< T >::writer_mutex_ private
Writer mutex for the queue.
Definition at line 184 of file blocking_queue.hpp.
Referenced by iii_drone::utils::BlockingQueue< T >::Clear(), and iii_drone::utils::BlockingQueue< T >::Push().
The documentation for this class was generated from the following file:
/home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/include/iii_drone_core/utils/blocking_queue.hpp