III-Drone: /home/ffn/Workspace/ros2_humble_ws/src/III-Drone-Core/src/configuration/configurator.cpp File Reference
configurator.cpp File Reference
#include "iii_drone_core/configuration/configurator.hpp"
#include <iostream>
Functions
template void Configurator::DeclareParameter< std::string > (const std::string &name)
template void Configurator::DeclareParameter< std::vector< bool > > (const std::string &name)
template void Configurator::DeclareParameter< std::vector< int > > (const std::string &name)
template void Configurator::DeclareParameter< std::vector< double > > (const std::string &name)
template void Configurator::DeclareParameter< std::vector< float > > (const std::string &name)
template void Configurator::DeclareParameter< std::vector< std::string > > (const std::string &name)
template std::string Configurator::GetParameterTypeString< std::string > ()
template std::string Configurator::GetParameterTypeString< std::vector< bool > > ()
template std::string Configurator::GetParameterTypeString< std::vector< int > > ()
template std::string Configurator::GetParameterTypeString< std::vector< double > > ()
template std::string Configurator::GetParameterTypeString< std::vector< float > > ()
template std::string Configurator::GetParameterTypeString< std::vector< std::string > > ()
Function Documentation
Configurator::DeclareParameter< std::string >()
template void Configurator::DeclareParameter< std::string > (const std::string & name)
Referenced by iii_drone::control::trajectory_generator_node::TrajectoryGeneratorNodeConfigurator::declareMPCParameters(), iii_drone::control::flight_controller_node::FlightControllerConfigurator::declareNodeParameters(), iii_drone::control::maneuver_controller_node::ManeuverControllerNodeConfigurator::declareNodeParameters(), iii_drone::perception::hough_transformer_node::HoughTransformerConfigurator::declareNodeParameters(), iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerConfigurator::declareNodeParameters(), iii_drone::perception::pl_mapper_node::PowerlineMapperConfigurator::declareNodeParameters(), and iii_drone::utils::drone_frame_broadcaster_node::DroneFrameBroadcasterConfigurator::declareNodeParameters().
Configurator::DeclareParameter< std::vector< bool > >()
template void Configurator::DeclareParameter< std::vector< bool > > (const std::string & name)
Configurator::DeclareParameter< std::vector< double > >()
template void Configurator::DeclareParameter< std::vector< double > > (const std::string & name)
Configurator::DeclareParameter< std::vector< float > >()
template void Configurator::DeclareParameter< std::vector< float > > (const std::string & name)
Configurator::DeclareParameter< std::vector< int > >()
template void Configurator::DeclareParameter< std::vector< int > > (const std::string & name)
Configurator::DeclareParameter< std::vector< std::string > >()
template void Configurator::DeclareParameter< std::vector< std::string > > (const std::string & name)
Configurator::GetParameterTypeString< std::string >()
template std::string Configurator::GetParameterTypeString< std::string > ()
Configurator::GetParameterTypeString< std::vector< bool > >()
template std::string Configurator::GetParameterTypeString< std::vector< bool > > ()
Configurator::GetParameterTypeString< std::vector< double > >()
template std::string Configurator::GetParameterTypeString< std::vector< double > > ()
Configurator::GetParameterTypeString< std::vector< float > >()
template std::string Configurator::GetParameterTypeString< std::vector< float > > ()
Configurator::GetParameterTypeString< std::vector< int > >()
template std::string Configurator::GetParameterTypeString< std::vector< int > > ()
Configurator::GetParameterTypeString< std::vector< std::string > >()
template std::string Configurator::GetParameterTypeString< std::vector< std::string > > ()