III-Drone: iii_drone::types Namespace Reference
iii_drone::types Namespace Reference
Classes
struct line_t
struct plane_t
struct pose_t
Typedefs
typedef Eigen::Vector3f point_t
typedef Eigen::Vector4f point4_t
typedef Eigen::Vector3f euler_angles_t
typedef Eigen::Vector4f quaternion_t
typedef Eigen::Vector3f vector_t
typedef struct iii_drone::types::pose_t pose_t
typedef Eigen::Matrix3f rotation_matrix_t
typedef Eigen::Matrix4f transform_matrix_t
Functions
const plane_t createPlane (const point_t &p, const vector_t &normal)
const geometry_msgs::msg::Point pointMsgFromPoint (const point_t &point)
const point_t pointFromPointMsg (const geometry_msgs::msg::Point &point_msg)
const geometry_msgs::msg::Vector3 vectorMsgFromVector (const vector_t &vector)
const vector_t vectorFromVectorMsg (const geometry_msgs::msg::Vector3 &vector_msg)
const geometry_msgs::msg::Quaternion quaternionMsgFromQuaternion (const quaternion_t &quaternion)
const quaternion_t quaternionFromQuaternionMsg (const geometry_msgs::msg::Quaternion &quaternion_msg)
const geometry_msgs::msg::Pose poseMsgFromPose (const point_t &position, const quaternion_t &quaternion)
const geometry_msgs::msg::Pose poseMsgFromPose (const pose_t &pose)
const pose_t poseFromPoseMsg (const geometry_msgs::msg::Pose &pose_msg)
const pose_t poseFromPose (const point_t &position, const quaternion_t &orientation)
const pose_t poseFromTransformMsg (const geometry_msgs::msg::Transform &transform_msg)
const quaternion_t quaternionFromPoseMsg (const geometry_msgs::msg::Pose &pose_msg)
const point_t pointFromPoseMsg (const geometry_msgs::msg::Pose &pose_msg)
const quaternion_t quaternionFromTransformMsg (const geometry_msgs::msg::Transform &transform_msg)
const quaternion_t quaternionFromTransformMatrix (const transform_matrix_t &transform_matrix)
const vector_t vectorFromTransformMsg (const geometry_msgs::msg::Transform &transform_msg)
const geometry_msgs::msg::Transform transformMsgFromTransform (const vector_t &vector, const quaternion_t &quaternion)
const geometry_msgs::msg::Transform transformMsgFromTransformMatrix (const transform_matrix_t &transform_matrix)
const iii_drone::types::transform_matrix_t transformMatrixFromTransformMsg (const geometry_msgs::msg::Transform &transform_msg)
const iii_drone::types::pose_t poseFromTransformMatrix (const iii_drone::types::transform_matrix_t &transform)
Typedef Documentation
euler_angles_t
typedef Eigen::Vector3f iii_drone::types::euler_angles_t
Definition at line 26 of file types.hpp.
point4_t
typedef Eigen::Vector4f iii_drone::types::point4_t
Definition at line 24 of file types.hpp.
point_t
typedef Eigen::Vector3f iii_drone::types::point_t
Definition at line 22 of file types.hpp.
pose_t
typedef struct iii_drone::types::pose_t iii_drone::types::pose_t
quaternion_t
typedef Eigen::Vector4f iii_drone::types::quaternion_t
Definition at line 28 of file types.hpp.
rotation_matrix_t
typedef Eigen::Matrix3f iii_drone::types::rotation_matrix_t
Definition at line 66 of file types.hpp.
transform_matrix_t
typedef Eigen::Matrix4f iii_drone::types::transform_matrix_t
Definition at line 68 of file types.hpp.
vector_t
typedef Eigen::Vector3f iii_drone::types::vector_t
Definition at line 30 of file types.hpp.
Function Documentation
createPlane()
const plane_t iii_drone::types::createPlane (const point_t & p, const vector_t & normal)
Definition at line 21 of file types.cpp.
{
    plane_t plane;
    plane.p = p;
    plane.normal = normal;
    return plane;
}
References iii_drone::types::plane_t::normal, and iii_drone::types::plane_t::p.
Referenced by iii_drone::adapters::PowerlineAdapter::PowerlineAdapter(), iii_drone::perception::Powerline::Reset(), and iii_drone::perception::Powerline::updateProjectionPlane().
pointFromPointMsg()
const point_t iii_drone::types::pointFromPointMsg (const geometry_msgs::msg::Point & point_msg)
Definition at line 45 of file types.cpp.
{
    point_t point;
    point(0) = point_msg.x;
    point(1) = point_msg.y;
    point(2) = point_msg.z;
    return point;
}
Referenced by iii_drone::perception::SingleLine::IsInFOV(), iii_drone::perception::SingleLine::IsInFOVStrict(), iii_drone::perception::pl_mapper_node::PowerlineMapperNode::mmWaveCallback(), pointFromPoseMsg(), poseFromPoseMsg(), iii_drone::adapters::ReferenceAdapter::ReferenceAdapter(), iii_drone::control::maneuver::Maneuver::SetFromGoal(), iii_drone::perception::SingleLine::SingleLine(), iii_drone::adapters::SingleLineAdapter::SingleLineAdapter(), and iii_drone::control::maneuver::fly_to_position_maneuver_params_t::transform_target_position().
pointFromPoseMsg()
const point_t iii_drone::types::pointFromPoseMsg (const geometry_msgs::msg::Pose & pose_msg)
Definition at line 174 of file types.cpp.
{
    point_t point;
    point = pointFromPointMsg(pose_msg.position);
    return point;
}
References pointFromPointMsg().
Referenced by iii_drone::adapters::SingleLineAdapter::SingleLineAdapter(), iii_drone::adapters::SingleLineAdapter::SingleLineAdapter(), and iii_drone::adapters::SingleLineAdapter::SingleLineAdapter().
pointMsgFromPoint()
const geometry_msgs::msg::Point iii_drone::types::pointMsgFromPoint (const point_t & point)
Definition at line 33 of file types.cpp.
{
    geometry_msgs::msg::Point point_msg;
    point_msg.x = point(0);
    point_msg.y = point(1);
    point_msg.z = point(2);
    return point_msg;
}
Referenced by iii_drone::perception::SingleLine::IsInFOV(), iii_drone::perception::SingleLine::IsInFOVStrict(), iii_drone::perception::pl_mapper_node::PowerlineMapperNode::mmWaveCallback(), poseMsgFromPose(), poseMsgFromPose(), iii_drone::adapters::ReferenceAdapter::ToMsg(), iii_drone::adapters::SingleLineAdapter::ToMsg(), iii_drone::adapters::SingleLineAdapter::ToPoseMsg(), iii_drone::adapters::ReferenceAdapter::ToPoseStampedMsg(), and iii_drone::control::maneuver::fly_to_position_maneuver_params_t::transform_target_position().
poseFromPose()
const pose_t iii_drone::types::poseFromPose (const point_t & position, const quaternion_t & orientation)
Definition at line 142 of file types.cpp.
{
    pose_t pose;
    pose.position = position;
    pose.orientation = orientation;
    return pose;
}
References iii_drone::types::pose_t::orientation, and iii_drone::types::pose_t::position.
Referenced by iii_drone::adapters::StateAdapter::ToMsg().
poseFromPoseMsg()
const pose_t iii_drone::types::poseFromPoseMsg (const geometry_msgs::msg::Pose & pose_msg)
Definition at line 131 of file types.cpp.
{
    pose_t pose;
    pose.position = pointFromPointMsg(pose_msg.position);
    pose.orientation = quaternionFromQuaternionMsg(pose_msg.orientation);
    return pose;
}
References iii_drone::types::pose_t::orientation, pointFromPointMsg(), iii_drone::types::pose_t::position, and quaternionFromQuaternionMsg().
Referenced by iii_drone::control::CombinedDroneAwarenessHandler::ComputeTargetTransform(), iii_drone::adapters::StateAdapter::StateAdapter(), and iii_drone::adapters::StateAdapter::StateAdapter().
poseFromTransformMatrix()
const pose_t iii_drone::types::poseFromTransformMatrix (const iii_drone::types::transform_matrix_t & transform)
Definition at line 235 of file math.cpp.
{
    pose_t pose;
    pose.position = transform.block<3, 1>(0, 3);
    pose.orientation = quaternionFromTransformMatrix(transform);
    return pose;
}
References iii_drone::types::pose_t::orientation, iii_drone::types::pose_t::position, and quaternionFromTransformMatrix().
Referenced by iii_drone::control::maneuver::HoverByObjectManeuverServer::GetReference(), and iii_drone::control::maneuver::HoverByObjectManeuverServer::validateTargetTransform().
poseFromTransformMsg()
const pose_t iii_drone::types::poseFromTransformMsg (const geometry_msgs::msg::Transform & transform_msg)
Definition at line 153 of file types.cpp.
{
    pose_t pose;
    pose.position = vectorFromVectorMsg(transform_msg.translation);
    pose.orientation = quaternionFromQuaternionMsg(transform_msg.rotation);
    return pose;
}
References iii_drone::types::pose_t::orientation, iii_drone::types::pose_t::position, quaternionFromQuaternionMsg(), and vectorFromVectorMsg().
Referenced by iii_drone::perception::pl_mapper_node::PowerlineMapperNode::odometryCallback().
poseMsgFromPose() [1/2]
const geometry_msgs::msg::Pose iii_drone::types::poseMsgFromPose (const point_t & position, const quaternion_t & quaternion)
Definition at line 109 of file types.cpp.
{
    geometry_msgs::msg::Pose pose_msg;
    pose_msg.position = pointMsgFromPoint(position);
    pose_msg.orientation = quaternionMsgFromQuaternion(quaternion);
    return pose_msg;
}
References pointMsgFromPoint(), and quaternionMsgFromQuaternion().
Referenced by iii_drone::adapters::SingleLineAdapter::ToMsg(), iii_drone::adapters::StateAdapter::ToMsg(), iii_drone::adapters::StateAdapter::ToPoseMsg(), and iii_drone::perception::PowerlineDirection::ToPoseStampedMsg().
poseMsgFromPose() [2/2]
const geometry_msgs::msg::Pose iii_drone::types::poseMsgFromPose (const pose_t & pose)
Definition at line 120 of file types.cpp.
{
    geometry_msgs::msg::Pose pose_msg;
    pose_msg.position = pointMsgFromPoint(pose.position);
    pose_msg.orientation = quaternionMsgFromQuaternion(pose.orientation);
    return pose_msg;
}
References iii_drone::types::pose_t::orientation, pointMsgFromPoint(), iii_drone::types::pose_t::position, and quaternionMsgFromQuaternion().
quaternionFromPoseMsg()
const quaternion_t iii_drone::types::quaternionFromPoseMsg (const geometry_msgs::msg::Pose & pose_msg)
Definition at line 164 of file types.cpp.
{
    quaternion_t quaternion;
    quaternion = quaternionFromQuaternionMsg(pose_msg.orientation);
    return quaternion;
}
References quaternionFromQuaternionMsg().
Referenced by iii_drone::adapters::SingleLineAdapter::SingleLineAdapter(), iii_drone::adapters::SingleLineAdapter::SingleLineAdapter(), and iii_drone::adapters::SingleLineAdapter::SingleLineAdapter().
quaternionFromQuaternionMsg()
const quaternion_t iii_drone::types::quaternionFromQuaternionMsg (const geometry_msgs::msg::Quaternion & quaternion_msg)
Definition at line 94 of file types.cpp.
{
    quaternion_t quaternion;
    quaternion(0) = quaternion_msg.w;
    quaternion(1) = quaternion_msg.x;
    quaternion(2) = quaternion_msg.y;
    quaternion(3) = quaternion_msg.z;
    return quaternion;
}
Referenced by iii_drone::perception::pl_mapper_node::PowerlineMapperNode::plDirectionCallback(), poseFromPoseMsg(), poseFromTransformMsg(), quaternionFromPoseMsg(), quaternionFromTransformMsg(), iii_drone::perception::SingleLine::SingleLine(), and transformMatrixFromTransformMsg().
quaternionFromTransformMatrix()
const quaternion_t iii_drone::types::quaternionFromTransformMatrix (const transform_matrix_t & transform_matrix)
Definition at line 223 of file math.cpp.
{
    quaternion_t quaternion;
    rotation_matrix_t R = transform_matrix.block<3, 3>(0, 0);
    quaternion = matToQuat(R);
    return quaternion;
}
References iii_drone::math::matToQuat().
Referenced by iii_drone::control::maneuver::FlyToObjectManeuverServer::getUpdatedTargetReference(), poseFromTransformMatrix(), and transformMsgFromTransformMatrix().
quaternionFromTransformMsg()
const quaternion_t iii_drone::types::quaternionFromTransformMsg (const geometry_msgs::msg::Transform & transform_msg)
Definition at line 184 of file types.cpp.
{
    quaternion_t quaternion;
    quaternion = quaternionFromQuaternionMsg(transform_msg.rotation);
    return quaternion;
}
References quaternionFromQuaternionMsg().
Referenced by iii_drone::perception::pl_dir_computer_node::PowerlineDirectionComputerNode::odometryCallback(), and iii_drone::perception::pl_mapper_node::PowerlineMapperNode::PowerlineMapperNode().
quaternionMsgFromQuaternion()
const geometry_msgs::msg::Quaternion iii_drone::types::quaternionMsgFromQuaternion (const quaternion_t & quaternion)
Definition at line 81 of file types.cpp.
{
    geometry_msgs::msg::Quaternion quaternion_msg;
    quaternion_msg.w = quaternion(0);
    quaternion_msg.x = quaternion(1);
    quaternion_msg.y = quaternion(2);
    quaternion_msg.z = quaternion(3);
    return quaternion_msg;
}
Referenced by poseMsgFromPose(), poseMsgFromPose(), iii_drone::adapters::SingleLineAdapter::ToPoseMsg(), iii_drone::adapters::ReferenceAdapter::ToPoseStampedMsg(), iii_drone::perception::PowerlineDirection::ToQuaternionStampedMsg(), transformMsgFromTransform(), and transformMsgFromTransformMatrix().
transformMatrixFromTransformMsg()
const transform_matrix_t iii_drone::types::transformMatrixFromTransformMsg (const geometry_msgs::msg::Transform & transform_msg)
Definition at line 203 of file math.cpp.
{
    transform_matrix_t transform_matrix;
    transform_matrix.block<3, 1>(0, 3) = vectorFromVectorMsg(transform_msg.translation);
    transform_matrix.block<3, 3>(0, 0) = quatToMat(
        quaternionFromQuaternionMsg(
            transform_msg.rotation
        )
    );
    transform_matrix(3, 0) = 0;
    transform_matrix(3, 1) = 0;
    transform_matrix(3, 2) = 0;
    transform_matrix(3, 3) = 1;
    return transform_matrix;
}
References quaternionFromQuaternionMsg(), iii_drone::math::quatToMat(), and vectorFromVectorMsg().
Referenced by iii_drone::adapters::TargetAdapter::TargetAdapter().
transformMsgFromTransform()
const geometry_msgs::msg::Transform iii_drone::types::transformMsgFromTransform (const vector_t & vector, const quaternion_t & quaternion)
Definition at line 204 of file types.cpp.
{
    geometry_msgs::msg::Transform transform_msg;
    transform_msg.translation = vectorMsgFromVector(vector);
    transform_msg.rotation = quaternionMsgFromQuaternion(quaternion);
    return transform_msg;
}
References quaternionMsgFromQuaternion(), and vectorMsgFromVector().
Referenced by iii_drone::adapters::px4::VehicleOdometryAdapter::ToTransformStamped(), and iii_drone::control::CombinedDroneAwarenessHandler::updateGroundAltitudeEstimate().
transformMsgFromTransformMatrix()
const geometry_msgs::msg::Transform iii_drone::types::transformMsgFromTransformMatrix (const transform_matrix_t & transform_matrix)
Definition at line 214 of file types.cpp.
{
    geometry_msgs::msg::Transform transform_msg;
    transform_msg.translation = vectorMsgFromVector(transform_matrix.block<3, 1>(0, 3));
    transform_msg.rotation = quaternionMsgFromQuaternion(quaternionFromTransformMatrix(transform_matrix));
    return transform_msg;
}
References quaternionFromTransformMatrix(), quaternionMsgFromQuaternion(), and vectorMsgFromVector().
Referenced by iii_drone::adapters::TargetAdapter::ToMsg().
vectorFromTransformMsg()
const vector_t iii_drone::types::vectorFromTransformMsg (const geometry_msgs::msg::Transform & transform_msg)
Definition at line 194 of file types.cpp.
{
    vector_t vector;
    vector = vectorFromVectorMsg(transform_msg.translation);
    return vector;
}
References vectorFromVectorMsg().
Referenced by iii_drone::perception::pl_mapper_node::PowerlineMapperNode::PowerlineMapperNode(), and iii_drone::control::CombinedDroneAwarenessHandler::updateDroneLocation().
vectorFromVectorMsg()
const vector_t iii_drone::types::vectorFromVectorMsg (const geometry_msgs::msg::Vector3 & vector_msg)
Definition at line 69 of file types.cpp.
{
    vector_t vector;
    vector(0) = vector_msg.x;
    vector(1) = vector_msg.y;
    vector(2) = vector_msg.z;
    return vector;
}
Referenced by poseFromTransformMsg(), iii_drone::adapters::ReferenceAdapter::ReferenceAdapter(), iii_drone::adapters::StateAdapter::StateAdapter(), iii_drone::adapters::StateAdapter::StateAdapter(), transformMatrixFromTransformMsg(), and vectorFromTransformMsg().
vectorMsgFromVector()
const geometry_msgs::msg::Vector3 iii_drone::types::vectorMsgFromVector (const vector_t & vector)
Definition at line 57 of file types.cpp.
{
    geometry_msgs::msg::Vector3 vector_msg;
    vector_msg.x = vector(0);
    vector_msg.y = vector(1);
    vector_msg.z = vector(2);
    return vector_msg;
}
Referenced by iii_drone::adapters::ReferenceAdapter::ToMsg(), iii_drone::adapters::StateAdapter::ToMsg(), transformMsgFromTransform(), and transformMsgFromTransformMatrix().