III-Drone: iii_drone::math Namespace Reference
iii_drone::math Namespace Reference
Functions
const iii_drone::types::vector_t rotateVector (const iii_drone::types::rotation_matrix_t &R, const iii_drone::types::vector_t &v)
const iii_drone::types::point_t projectPointOnPlane (const iii_drone::types::point_t &point, const iii_drone::types::plane_t &plane)
const iii_drone::types::euler_angles_t quatToEul (const iii_drone::types::quaternion_t &quat)
const iii_drone::types::quaternion_t quatInv (const iii_drone::types::quaternion_t &quat)
const iii_drone::types::quaternion_t quatMultiply (const iii_drone::types::quaternion_t &quat1, const iii_drone::types::quaternion_t &quat2)
const iii_drone::types::rotation_matrix_t eulToMat (const iii_drone::types::euler_angles_t &eul)
const iii_drone::types::rotation_matrix_t quatToMat (const iii_drone::types::quaternion_t &quat)
const iii_drone::types::quaternion_t matToQuat (const iii_drone::types::rotation_matrix_t &R)
const iii_drone::types::quaternion_t eulToQuat (const iii_drone::types::euler_angles_t &eul)
const iii_drone::types::transform_matrix_t createTransformMatrix (const iii_drone::types::vector_t &vector, const iii_drone::types::quaternion_t &quaternion)
Function Documentation
createTransformMatrix()
const transform_matrix_t iii_drone::math::createTransformMatrix (const iii_drone::types::vector_t & vector, const iii_drone::types::quaternion_t & quaternion)
Definition at line 174 of file math.cpp.
  {
    transform_matrix_t T;
    rotation_matrix_t R = iii_drone::math::quatToMat(quat);
    for ( int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            T(i,j) = R(i,j);
        }
        T(i,3) = vec(i);
    }
    T(3,0) = 0;
    T(3,1) = 0;
    T(3,2) = 0;
    T(3,3) = 1;
    return T;
}
References quatToMat().
Referenced by iii_drone::control::CombinedDroneAwarenessHandler::ComputeTargetTransform().
eulToMat()
const rotation_matrix_t iii_drone::math::eulToMat (const iii_drone::types::euler_angles_t & eul)
Definition at line 15 of file math.cpp.
{
    float cos_yaw = cos(eul[2]);
    float cos_pitch = cos(eul[1]);
    float cos_roll = cos(eul[0]);
    float sin_yaw = sin(eul[2]);
    float sin_pitch = sin(eul[1]);
    float sin_roll = sin(eul[0]);
    rotation_matrix_t mat;
    mat(0,0) = cos_pitch*cos_yaw;
    mat(0,1) = sin_roll*sin_pitch*cos_yaw-cos_roll*sin_yaw;
    mat(0,2) = cos_roll*sin_pitch*cos_yaw+sin_roll*sin_yaw;
    mat(1,0) = cos_pitch*sin_yaw;
    mat(1,1) = sin_roll*sin_pitch*sin_yaw+cos_roll*cos_yaw;
    mat(1,2) = cos_roll*sin_pitch*sin_yaw-sin_roll*cos_pitch; // wrong? cos_roll*sin_pitch*sin_yaw-sin_roll*cos_yaw
    mat(2,0) = -sin_pitch;
    mat(2,1) = sin_roll*cos_pitch;
    mat(2,2) = cos_roll*cos_pitch;
    return mat;
}
Referenced by iii_drone::utils::drone_frame_broadcaster_node::DroneFrameBroadcasterNode::DroneFrameBroadcasterNode(), quatToMat(), and iii_drone::perception::Powerline::updateProjectionPlane().
eulToQuat()
const quaternion_t iii_drone::math::eulToQuat (const iii_drone::types::euler_angles_t & eul)
Definition at line 154 of file math.cpp.
{
    // Abbreviations for the various angular functions
    float cy = cos(eul(2) * 0.5);
    float sy = sin(eul(2) * 0.5);
    float cp = cos(eul(1) * 0.5);
    float sp = sin(eul(1) * 0.5);
    float cr = cos(eul(0) * 0.5);
    float sr = sin(eul(0) * 0.5);
    quaternion_t q;
    q(0) = cr * cp * cy + sr * sp * sy;
    q(1) = sr * cp * cy - cr * sp * sy;
    q(2) = cr * sp * cy + sr * cp * sy;
    q(3) = cr * cp * sy - sr * sp * cy;
    return q;
}
Referenced by iii_drone::control::State::State(), iii_drone::adapters::ReferenceAdapter::ToPoseStampedMsg(), and iii_drone::adapters::px4::VehicleOdometryAdapter::UpdateFromMsg().
matToQuat()
const quaternion_t iii_drone::math::matToQuat (const iii_drone::types::rotation_matrix_t & R)
Definition at line 108 of file math.cpp.
{
    float tr = R(0,0) + R(1,1) + R(2,2);
    float qw, qx, qy, qz;
    if (tr > 0) {
        float S = sqrt(tr+1.0) * 2; // S=4*qw
        qw = 0.25 * S;
        qx = (R(2,1) - R(1,2)) / S;
        qy = (R(0,2) - R(2,0)) / S;
        qz = (R(1,0) - R(0,1)) / S;
    } else if ((R(0,0) > R(1,1)) && (R(0,0) > R(2,2))) {
        float S = sqrt(1.0 + R(0,0) - R(1,1) - R(2,2)) * 2; // S=4*qx
        qw = (R(2,1) - R(1,2)) / S;
        qx = 0.25 * S;
        qy = (R(0,1) + R(1,0)) / S;
        qz = (R(0,2) + R(2,0)) / S;
    } else if (R(1,1) > R(2,2)) {
        float S = sqrt(1.0 + R(1,1) - R(0,0) - R(2,2)) * 2; // S=4*qy
        qw = (R(0,2) - R(2,0)) / S;
        qx = (R(0,1) + R(1,0)) / S;
        qy = 0.25 * S;
        qz = (R(1,2) + R(2,1)) / S;
    } else {
        float S = sqrt(1.0 + R(2,2) - R(0,0) - R(1,1)) * 2; // S=4*qz
        qw = (R(1,0) - R(0,1)) / S;
        qx = (R(0,2) + R(2,0)) / S;
        qy = (R(1,2) + R(2,1)) / S;
        qz = 0.25 * S;
    }
    quaternion_t quat(qw, qx, qy, qz);
    return quat;
}
Referenced by iii_drone::perception::Powerline::predictLines(), and iii_drone::types::quaternionFromTransformMatrix().
projectPointOnPlane()
const point_t iii_drone::math::projectPointOnPlane (const iii_drone::types::point_t & point, const iii_drone::types::plane_t & plane)
Definition at line 50 of file math.cpp.
  {
    float t = (plane.normal.dot(plane.p) - plane.normal.dot(point)) / plane.normal.dot(plane.normal);
    point_t proj_point = point + (point_t)(t*plane.normal);
    return proj_point;
}
References iii_drone::types::plane_t::normal, and iii_drone::types::plane_t::p.
Referenced by iii_drone::perception::SingleLine::Predict(), and iii_drone::perception::Powerline::projectPoint().
quatInv()
const quaternion_t iii_drone::math::quatInv (const iii_drone::types::quaternion_t & quat)
Definition at line 75 of file math.cpp.
{
    quaternion_t ret_quat(quat[0], -quat[1], -quat[2], -quat[3]);
    return ret_quat;
}
Referenced by iii_drone::perception::Powerline::ComputeInterLinePositions().
quatMultiply()
const quaternion_t iii_drone::math::quatMultiply (const iii_drone::types::quaternion_t & quat1, const iii_drone::types::quaternion_t & quat2)
Definition at line 83 of file math.cpp.
  {
    quaternion_t ret_quat(
        quat1[0]*quat2[0] - quat1[1]*quat2[1] - quat1[2]*quat2[2] - quat1[3]*quat2[3],
        quat1[0]*quat2[1] + quat1[1]*quat2[0] + quat1[2]*quat2[3] - quat1[3]*quat2[2],
        quat1[0]*quat2[2] - quat1[1]*quat2[3] + quat1[2]*quat2[0] + quat1[3]*quat2[1],
        quat1[0]*quat2[3] + quat1[1]*quat2[2] - quat1[2]*quat2[1] + quat1[3]*quat2[0]
    );
    return ret_quat;
}
quatToEul()
const euler_angles_t iii_drone::math::quatToEul (const iii_drone::types::quaternion_t & quat)
Definition at line 63 of file math.cpp.
{
    euler_angles_t eul(
        atan2(2*(quat[0]*quat[1] + quat[2]*quat[3]), 1-2*(quat[1]*quat[1] + quat[2]*quat[2])),
        asin(2*(quat[0]*quat[2] - quat[3]*quat[1])),
        atan2(2*(quat[0]*quat[3] + quat[1]*quat[2]), 1-2*(quat[2]*quat[2]+quat[3]*quat[3]))
    );
    return eul;
}
Referenced by iii_drone::control::maneuver::HoverByObjectManeuverServer::GetReference(), iii_drone::control::maneuver::FlyToObjectManeuverServer::getUpdatedTargetReference(), quatToMat(), iii_drone::control::Reference::Reference(), iii_drone::perception::PowerlineDirection::resetKalmanFilter(), iii_drone::control::State::State(), iii_drone::adapters::px4::TrajectorySetpointAdapter::TrajectorySetpointAdapter(), iii_drone::adapters::px4::VehicleOdometryAdapter::UpdateFromMsg(), and iii_drone::perception::Powerline::updateProjectionPlane().
quatToMat()
const rotation_matrix_t iii_drone::math::quatToMat (const iii_drone::types::quaternion_t & quat)
Definition at line 99 of file math.cpp.
{
    euler_angles_t eul = quatToEul(quat);
    rotation_matrix_t mat = eulToMat(eul);
    return mat;
}
References eulToMat(), and quatToEul().
Referenced by iii_drone::perception::Powerline::ComputeInterLinePositions(), createTransformMatrix(), iii_drone::perception::pl_mapper_node::PowerlineMapperNode::PowerlineMapperNode(), iii_drone::perception::SingleLine::Predict(), iii_drone::perception::Powerline::predictLines(), and iii_drone::types::transformMatrixFromTransformMsg().
rotateVector()
const vector_t iii_drone::math::rotateVector (const iii_drone::types::rotation_matrix_t & R, const iii_drone::types::vector_t & v)
Definition at line 40 of file math.cpp.
  {
    vector_t ret_vec = R*v;
    return ret_vec;
}
Referenced by iii_drone::perception::Powerline::updateProjectionPlane().