III-Drone: pos_MPC::coder::internal Namespace Reference
pos_MPC::coder::internal Namespace Reference
Namespaces
namespace blas
namespace lapack
Functions
double maximum (const double x[31])
double minimum (const double x[31])
void trisolve (const double A[961], double B[961])
Function Documentation
maximum()
double pos_MPC::coder::internal::maximum (const double x[31])
Definition at line 20 of file minOrMax.cpp.
{
  double ex;
  int idx;
  int k;
  if (!std::isnan(x[0])) {
    idx = 1;
  } else {
    boolean_T exitg1;
    idx = 0;
    k = 2;
    exitg1 = false;
    while ((!exitg1) && (k < 32)) {
      if (!std::isnan(x[k - 1])) {
        idx = k;
        exitg1 = true;
      } else {
        k++;
      }
    }
  }
  if (idx == 0) {
    ex = x[0];
  } else {
    ex = x[idx - 1];
    idx++;
    for (k = idx; k < 32; k++) {
      double d;
      d = x[k - 1];
      if (ex < d) {
        ex = d;
      }
    }
  }
  return ex;
}
Referenced by pos_MPC::coder::qpkwik().
minimum()
double pos_MPC::coder::internal::minimum (const double x[31])
Definition at line 57 of file minOrMax.cpp.
{
  double ex;
  int idx;
  int k;
  if (!std::isnan(x[0])) {
    idx = 1;
  } else {
    boolean_T exitg1;
    idx = 0;
    k = 2;
    exitg1 = false;
    while ((!exitg1) && (k < 32)) {
      if (!std::isnan(x[k - 1])) {
        idx = k;
        exitg1 = true;
      } else {
        k++;
      }
    }
  }
  if (idx == 0) {
    ex = x[0];
  } else {
    ex = x[idx - 1];
    idx++;
    for (k = idx; k < 32; k++) {
      double d;
      d = x[k - 1];
      if (ex > d) {
        ex = d;
      }
    }
  }
  return ex;
}
Referenced by pos_MPC::coder::mpcblock_optimizer().
trisolve()
void pos_MPC::coder::internal::trisolve (const double A[961], double B[961])
Definition at line 19 of file trisolve.cpp.
{
  for (int j{0}; j < 31; j++) {
    int jBcol;
    jBcol = 31 * j - 1;
    for (int k{0}; k < 31; k++) {
      double d;
      int i;
      int kAcol;
      kAcol = 31 * k - 1;
      i = (k + jBcol) + 1;
      d = B[i];
      if (d != 0.0) {
        int i1;
        B[i] = d / A[(k + kAcol) + 1];
        i1 = k + 2;
        for (int b_i{i1}; b_i < 32; b_i++) {
          int i2;
          i2 = b_i + jBcol;
          B[i2] -= B[i] * A[b_i + kAcol];
        }
      }
    }
  }
}
Referenced by pos_MPC::coder::mpcblock_optimizer().