III-Drone: pos_MPC Namespace Reference
pos_MPC Namespace Reference
Namespaces
namespace coder
Classes
struct struct10_T
struct struct4_T
struct struct5_T
struct struct6_T
struct struct7_T
struct struct8_T
Functions
static double rt_powd_snf (double u0, double u1)
void mpcmoveCodeGeneration_initialize ()
int div_nde_s32_floor (int numerator, int denominator)
void mpcmoveCodeGeneration_terminate ()
static double rt_hypotd_snf (double u0, double u1)
Function Documentation
div_nde_s32_floor()
int pos_MPC::div_nde_s32_floor (int numerator, int denominator)
Definition at line 17 of file mpcmoveCodeGeneration_rtwutil.cpp.
{
  int b_numerator;
  if (((numerator < 0) != (denominator < 0)) &&
      (numerator % denominator != 0)) {
    b_numerator = -1;
  } else {
    b_numerator = 0;
  }
  return numerator / denominator + b_numerator;
}
Referenced by pos_MPC::coder::KWIKfactor(), and pos_MPC::coder::internal::lapack::xpotrf().
mpcmoveCodeGeneration_initialize()
void pos_MPC::mpcmoveCodeGeneration_initialize ()
Definition at line 17 of file mpcmoveCodeGeneration_initialize.cpp.
{
}
mpcmoveCodeGeneration_terminate()
void pos_MPC::mpcmoveCodeGeneration_terminate ()
Definition at line 17 of file mpcmoveCodeGeneration_terminate.cpp.
{
  // (no terminate code required)
}
rt_hypotd_snf()
static double pos_MPC::rt_hypotd_snf (double u0, double u1) static
Definition at line 360 of file qpkwik.cpp.
{
  double a;
  double y;
  a = std::abs(u0);
  y = std::abs(u1);
  if (a < y) {
    a /= y;
    y *= std::sqrt(a * a + 1.0);
  } else if (a > y) {
    y /= a;
    y = a * std::sqrt(y * y + 1.0);
  } else if (!std::isnan(y)) {
    y = a * 1.4142135623730951;
  }
  return y;
}
Referenced by pos_MPC::coder::KWIKfactor().
rt_powd_snf()
static double pos_MPC::rt_powd_snf (double u0, double u1) static
Definition at line 29 of file mpcblock_optimizer.cpp.
{
  double y;
  if (std::isnan(u0) || std::isnan(u1)) {
    y = rtNaN;
  } else {
    double d;
    double d1;
    d = std::abs(u0);
    d1 = std::abs(u1);
    if (std::isinf(u1)) {
      if (d == 1.0) {
        y = 1.0;
      } else if (d > 1.0) {
        if (u1 > 0.0) {
          y = rtInf;
        } else {
          y = 0.0;
        }
      } else if (u1 > 0.0) {
        y = 0.0;
      } else {
        y = rtInf;
      }
    } else if (d1 == 0.0) {
      y = 1.0;
    } else if (d1 == 1.0) {
      if (u1 > 0.0) {
        y = u0;
      } else {
        y = 1.0 / u0;
      }
    } else if (u1 == 2.0) {
      y = u0 * u0;
    } else if ((u1 == 0.5) && (u0 >= 0.0)) {
      y = std::sqrt(u0);
    } else if ((u0 < 0.0) && (u1 > std::floor(u1))) {
      y = rtNaN;
    } else {
      y = std::pow(u0, u1);
    }
  }
  return y;
}
References rtInf, and rtNaN.
Referenced by pos_MPC::coder::mpcblock_optimizer().