hough_transformer:
  hough_transformer:
    ros__parameters:
      canny_low_threshold: 50
      canny_ratio: 4
      canny_kernel_size: 3
      n_lines_include: 8

offboard_control:
  offboard_control:
    ros__parameters:
      yaw_frac: 0.1
      pos_frac: 0.5
      hover_height: 2.
    
pl_dir_computer:
  pl_dir_computer:
    ros__parameters:
      kf_r: 0.999
      kf_q: 0.001
      init_sleep_time_ms: 1000
      odometry_callback_period_ms: 25

pl_mapper:
  pl_mapper:
    ros__parameters:
      kf_r: 1.
      kf_q: 0.25
      alive_cnt_low_thresh: 0
      alive_cnt_high_thresh: 60
      alive_cnt_ceiling: 150
      matching_line_max_dist: 3.
      min_point_dist: 0.1
      min_point_dist_strict: 0.6
      max_point_dist: 20.
      max_point_dist_strict: 18.
      view_cone_slope: 0.55
      view_cone_slope_strict: 0.75
      init_sleep_time_ms: 1000
      odometry_callback_period_ms: 25

mmwave:
  iwr6843_pcl_pub:
    ros__parameters:
      cli_port: /dev/ttyUSB0
      data_port: /dev/ttyUSB1

cable_camera:
  cable_camera:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "yuyv"
      image_width: 640
      image_height: 480
      camera_name: "test_camera"
      camera_info_url: "package://usb_cam/config/camera_info.yaml"
      cfg_path: "/home/mp4d/ros2_ws/src/iwr6843aop/cfg_files/30deg_Group_18m_30Hz.cfg"

trajectory_controller:
  trajectory_controller:
    ros__parameters:
      controller_period_ms: 200
      landed_altitude_threshold: 0.1
      reached_position_euclidean_distance_threshold: 0.1
      min_target_altitude: 1.
      target_cable_fixed_position_distance_threshold: 0.5
      target_cable_safety_margin_distance_threshold: 0.25
      target_cable_safety_margin_max_euc_distance: 0.1
      target_cable_safety_margin_max_euc_velocity: 1.
      target_cable_safety_margin_max_euc_acceleration: 1.
      target_cable_safety_margin_max_yaw_distance: 0.314159265
      target_cable_safety_margin_max_yaw_velocity: 1.570796327
      target_cable_set_point_truncate_distance_threshold: 0.25
      MPC_dt: 0.2
      position_MPC_vx_max: 0.5
      position_MPC_vy_max: 0.5
      position_MPC_vz_max: 0.5
      position_MPC_ax_max: 1.0
      position_MPC_ay_max: 1.0
      position_MPC_az_max: 1.0
      position_MPC_wx: 1.
      position_MPC_wy: 1.
      position_MPC_wz: 1.
      position_MPC_wvx: 1.0
      position_MPC_wvy: 1.0
      position_MPC_wvz: 1.0
      position_MPC_wax: 0.01
      position_MPC_way: 0.01
      position_MPC_waz: 0.01
      position_MPC_wjx: 0.1
      position_MPC_wjy: 0.1
      position_MPC_wjz: 0.1
      cable_landing_MPC_vx_max: 0.5
      cable_landing_MPC_vy_max: 0.5
      cable_landing_MPC_vz_max: 0.5
      cable_landing_MPC_ax_max: 1.
      cable_landing_MPC_ay_max: 1.
      cable_landing_MPC_az_max: 1.
      cable_landing_MPC_wx: 15.
      cable_landing_MPC_wy: 15.
      cable_landing_MPC_wz: 1.
      cable_landing_MPC_wvx: 2.
      cable_landing_MPC_wvy: 2.
      cable_landing_MPC_wvz: 1.
      cable_landing_MPC_wax: 0.01
      cable_landing_MPC_way: 0.01
      cable_landing_MPC_waz: 0.01
      cable_landing_MPC_wjx: 0.1
      cable_landing_MPC_wjy: 0.1
      cable_landing_MPC_wjz: 0.1
      cable_takeoff_MPC_vx_max: 2.
      cable_takeoff_MPC_vy_max: 2.
      cable_takeoff_MPC_vz_max: 2.
      cable_takeoff_MPC_ax_max: 1.
      cable_takeoff_MPC_ay_max: 1.
      cable_takeoff_MPC_az_max: 1.
      cable_takeoff_MPC_wx: 1.
      cable_takeoff_MPC_wy: 1.
      cable_takeoff_MPC_wz: 10.
      cable_takeoff_MPC_wvx: 1.
      cable_takeoff_MPC_wvy: 1.
      cable_takeoff_MPC_wvz: 1.
      cable_takeoff_MPC_wax: 0.01
      cable_takeoff_MPC_way: 0.01
      cable_takeoff_MPC_waz: 0.01
      cable_takeoff_MPC_wjx: 0.1
      cable_takeoff_MPC_wjy: 0.1
      cable_takeoff_MPC_wjz: 0.1

/**:
  ros__parameters:
    world_frame_id: "world"
    drone_frame_id: "drone"
    cable_drum_frame_id: "cable_drum"
    cable_gripper_frame_id: "cable_gripper"
    mmwave_frame_id: "mmwave"
    depth_cam_frame_id: "depth_cam"

tf:
  sim:
    ros__parameters:
      drone_to_cable_drum: [0.0, 0.0, 0.09, 1.57079632679, 0.0, 0.0]
      drone_to_cable_gripper: [0.0, 0.0, 0.09, 1.57079632679, 0.0, 0.0]
      drone_to_mmwave: [0.035, -0.23, 0.28, 3.1415, -1.57079632679, 0.0] 
      drone_to_depth_cam: [0.035, -0.23, 0.28, -1.57079632679, 0.0, 0.0]
  real:
    ros__parameters:
      drone_to_cable_drum: [-0.13, -0.01, -0.09, 3.1415, 0.0, 0.0]
      drone_to_cable_gripper: [0.0, 0.0, 0.13, 0.0, 0.0, 0.0]
      drone_to_mmwave: [0.0, 0.0, 0.05, 3.1415, -1.57079632679, 0.0] 
      
