iii_gui:
  iii_gui:
    ros__parameters:
      config_file_path: "III-Drone-ROS2-pkg/config/params.yaml"

perc_rc_node_launcher:
  rc_node_launcher:
    ros__parameters:
      rc_channel_indexes: [6,7]
      rc_channel_thresholds: [0.75, 0.75]
      rc_channel_launch_files: ["sensors_real.launch.py", "pl_mapper_SW.launch.py"]
      rc_channel_launch_packages: ["iii_drone", "iii_drone"]
      rc_channel_terminate_all_idx: 11
      rc_channel_terminate_all_threshold: 0.75

ctrl_rc_node_launcher:
  rc_node_launcher:
    ros__parameters:
      rc_channel_indexes: [6,8]
      rc_channel_thresholds: [0.75, 0.75]
      rc_channel_launch_files: ["tf_real.launch.py", "controller.launch.py"]
      rc_channel_launch_packages: ["iii_drone", "iii_drone"]
      rc_channel_terminate_all_idx: 11
      rc_channel_terminate_all_threshold: 0.75

hough_transformer:
  hough_transformer:
    ros__parameters:
      canny_low_threshold: 50
      canny_ratio: 4
      canny_kernel_size: 3
      n_lines_include: 8

pl_dir_computer:
  pl_dir_computer:
    ros__parameters:
      kf_r: 0.999
      kf_q: 0.001
      init_sleep_time_ms: 1000
      odometry_callback_period_ms: 25

pl_mapper:
  pl_mapper:
    ros__parameters:
      kf_r: 0.999
      kf_q: 0.001
      alive_cnt_low_thresh: 0
      alive_cnt_high_thresh: 60
      alive_cnt_ceiling: 150
      matching_line_max_dist: 3.
      min_point_dist: 0.1
      min_point_dist_strict: 1.0
      max_point_dist: 20.
      max_point_dist_strict: 18.
      view_cone_slope: 0.55
      view_cone_slope_strict: 0.75
      init_sleep_time_ms: 1000
      odometry_callback_period_ms: 25
      max_lines: 10

mmwave:
  iwr6843_pcl_pub:
    ros__parameters:
      cli_port: /dev/ttyUSB0
      data_port: /dev/ttyUSB1

cable_camera:
  usb_cam:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 10.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "yuyv"
      image_width: 640
      image_height: 480
      camera_name: "test_camera"
      camera_info_url: "package://usb_cam/config/camera_info.yaml"

trajectory_controller:
  trajectory_controller:
    ros__parameters:
      controller_period_ms: 200
      landed_altitude_threshold: 0.1
      reached_position_euclidean_distance_threshold: 0.1
      min_target_altitude: 1.
      target_cable_fixed_position_distance_threshold: 0.5
      target_cable_safety_margin_distance_threshold: 0.25
      target_cable_safety_margin_max_euc_distance: 0.1
      target_cable_safety_margin_max_euc_velocity: 1.
      target_cable_safety_margin_max_euc_acceleration: 1.
      target_cable_safety_margin_max_yaw_distance: 0.314159265
      target_cable_safety_margin_max_yaw_velocity: 1.570796327
      target_cable_set_point_truncate_distance_threshold: 0.25
      max_acceleration: 1.
      dt: 0.2
      use_cartesian_PID: false
      cartesian_PID_Kp: 1.5
      cartesian_PID_Ki: 0.2
      cartesian_PID_Kd: 0.2
      MPC_N: 10
      MPC_use_state_feedback: false
      direct_target_setpoint_dist_threshold: 0.05
      position_MPC_vx_max: 0.5
      position_MPC_vy_max: 0.5
      position_MPC_vz_max: 0.5
      position_MPC_ax_max: 0.25
      position_MPC_ay_max: 0.25
      position_MPC_az_max: 0.25
      position_MPC_wx: 1.0
      position_MPC_wy: 1.0
      position_MPC_wz: 1.0
      position_MPC_wvx: 1.0
      position_MPC_wvy: 1.0
      position_MPC_wvz: 1.0
      position_MPC_wax: 0.1
      position_MPC_way: 0.1
      position_MPC_waz: 0.1
      position_MPC_wjx: 0.1
      position_MPC_wjy: 0.1
      position_MPC_wjz: 0.1
      fly_along_cable_MPC_vz_max: 0.5
      fly_along_cable_MPC_ax_max: 1.0
      fly_along_cable_MPC_ay_max: 1.0
      fly_along_cable_MPC_az_max: 1.0
      fly_along_cable_MPC_wx: 1.1
      fly_along_cable_MPC_wy: 1.1
      fly_along_cable_MPC_wz: 1.1
      fly_along_cable_MPC_wvx: 1.0
      fly_along_cable_MPC_wvy: 1.0
      fly_along_cable_MPC_wvz: 1.0
      fly_along_cable_MPC_wax: 0.01
      fly_along_cable_MPC_way: 0.01
      fly_along_cable_MPC_waz: 0.01
      fly_along_cable_MPC_wjx: 0.1
      fly_along_cable_MPC_wjy: 0.1
      fly_along_cable_MPC_wjz: 0.1
      cable_landing_MPC_vx_max: 0.2
      cable_landing_MPC_vy_max: 0.2
      cable_landing_MPC_vz_max: 0.2
      cable_landing_MPC_ax_max: 1.
      cable_landing_MPC_ay_max: 1.
      cable_landing_MPC_az_max: 1.
      cable_landing_MPC_wx: 15.
      cable_landing_MPC_wy: 15.
      cable_landing_MPC_wz: 1.
      cable_landing_MPC_wvx: 2.
      cable_landing_MPC_wvy: 2.
      cable_landing_MPC_wvz: 1.
      cable_landing_MPC_wax: 0.01
      cable_landing_MPC_way: 0.01
      cable_landing_MPC_waz: 0.01
      cable_landing_MPC_wjx: 0.1
      cable_landing_MPC_wjy: 0.1
      cable_landing_MPC_wjz: 0.1
      cable_takeoff_MPC_vx_max: 2.
      cable_takeoff_MPC_vy_max: 2.
      cable_takeoff_MPC_vz_max: 2.
      cable_takeoff_MPC_ax_max: 1.
      cable_takeoff_MPC_ay_max: 1.
      cable_takeoff_MPC_az_max: 1.
      cable_takeoff_MPC_wx: 1.
      cable_takeoff_MPC_wy: 1.
      cable_takeoff_MPC_wz: 10.
      cable_takeoff_MPC_wvx: 1.
      cable_takeoff_MPC_wvy: 1.
      cable_takeoff_MPC_wvz: 1.
      cable_takeoff_MPC_wax: 0.01
      cable_takeoff_MPC_way: 0.01
      cable_takeoff_MPC_waz: 0.01
      cable_takeoff_MPC_wjx: 0.1
      cable_takeoff_MPC_wjy: 0.1
      cable_takeoff_MPC_wjz: 0.1

/**:
  ros__parameters:
    world_frame_id: "world"
    drone_frame_id: "drone"
    fmu_frame_id: "fmu"
    cable_drum_frame_id: "cable_drum"
    cable_gripper_frame_id: "cable_gripper"
    mmwave_frame_id: "mmwave"
    depth_cam_frame_id: "depth_cam"
    t265_world_frame_id: "t265_world"
    t265_camera_frame_id: "t265_camera"

tf:
  sim:
    ros__parameters:
      drone_to_cable_drum: [0.0, 0.0, 0.09, 1.57079632679, 0.0, 0.0]
      drone_to_cable_gripper: [0.0, 0.0, 0.5, 1.57079632679, 0.0, 0.0]
      drone_to_mmwave: [0.035, -0.23, 0.28, 3.1415, -1.57079632679, 0.0] 
      drone_to_depth_cam: [0.035, -0.23, 0.28, -1.57079632679, 0.0, 0.0]
  real:
    ros__parameters:
      drone_to_cable_drum: [-0.13, -0.01, -0.09, 3.1415, 0.0, 0.0]
      drone_to_cable_gripper: [0.0, 0.0, 0.13, 1.57079632679, 0.0, 0.0]
      drone_to_mmwave: [0.0375, -0.23, 0.0725, 0.0, 0.0, 1.57079632679] 
      drone_to_t265: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      world_to_t265_world: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      
